### ISSUE TITLE
Windows processing won't complete if a worker dies and is replaced

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1002]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

Windows2012

**Installation method:**

Dev install

**Description of problem:**

If a worker dies and the foreman starts a replacement, it will inherit a file handle to the session storage file. This will block the file rename at the end of processing.

**Debug output/tracebacks:**

N/A

**Source data:**

N/A

**Comment by Onager** [comment]
Hmm, I think if the main process has a task storage open for merge when it starts a replacement worker, we'll also end up locking that file too.

**Comment by Onager** [comment]
We could stop opening replacement workers on windows, or try to stop the workers inheriting the handles.
Possibly useful stackoverflow: http://stackoverflow.com/questions/948119/preventing-file-handle-inheritance-in-multiprocessing-lib

**Comment by joachimmetz** [comment]
> think if the main process has a task storage open for merge when it starts a replacement worker, we'll also end up locking that file too.

per https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/task_engine.py#L783 that behavior should no longer occur unless there is some delayed process start going on?

Another option is to split the session writer and the task file management.

**Comment by joachimmetz** [comment]
per discussion, this happens because a newly spawned worker does has an open file handle on the session storage. @Onager has a pending fix, hence assigning to him.
