### ISSUE TITLE
Tagging output incorrect

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1011]
**Plaso version:**

1.5.0 Release

**Operating system Plaso is running on:**

XUbuntu 64 bit

**Installation method:**

Installed from GiFT

**Description of problem:**

Tagging events using the `--analysis tagging` option works fine. When writing the events to output though, incorrect tag labels are written. The correct events are tagged with a label, but the label value is set to the first label written.

Let's say that we have event 1, 2 and 3. We have a tagging file which contains rules to tag event 1 with label 'one', and tag event 3 with label 'three'. After using the tagging option, the storage file contains correct labels for events 1 and 3. When using an output option (like `-o l2tcsv` or `-o json_line` for instance), the output contains label 'one' for both events 1 and 3. Event 2 is written without a tag.

**Source data:**

Problem can be fixed in `plaso/storage/zip_file.py` : on line 1831, replace `tag_index_value.store_index` with `tag_index_value.offset` .

**Comment by Onager** [comment]
This is now fixed - thanks for the super-helpful report!
