### ISSUE TITLE
Suggestions to enhance collection filters (filter files)

### ISSUE THREAD

**Issue by dnides** [log2timeline/plaso#103]
Related to my inquiry:

Do you have any examples of plaso filters for specific files in the recycle bin? We've tried something like: /$Recycle.Bin/.+/$I30 with no success.Also have tried something like /\$Recycle.Bin/.+/.+ etc to try to get everything x dirs down (this same type of pattern works in other cases)...also did not work.

Requesting support for the following two items in the collection filters:
- [ ] having the ability to define "negative" filter files, eg. a separate filter file of files to exclude
  * Tracked in https://github.com/log2timeline/plaso/issues/1537
- [ ] add ADS support

(Unclear what the request is)
- [ ]  blacklisting entries in the filter files
- [ ] adding recursive support
- [ ] use "native" OS path notation
- [ ] Add a "startswith" and "endswith" into the filter criteria

My understanding is the current support is limited, since it does not have recursive behavior....

**Comment by rodgermoore** [comment]
:+1:  for this

**Comment by joachimmetz** [comment]
The realization of this enhance will depend on: https://github.com/log2timeline/plaso/issues/646

**Comment by rgayon** [comment]
I would also like to see the "exclude" filter be implemented.

**Comment by ilyaglow** [comment]
Any updates here?

**Comment by ctmayhew** [comment]
This would be super handy for all those pointless files in C:\Windows\WinSxS

**Comment by joachimmetz** [comment]
Added to next milestone for consideration

**Comment by joachimmetz** [comment]
Update: filters in plaso are in desperate need of some love, but this will take some time.

I'll start with the filter file. Github project to follow progress: https://github.com/log2timeline/plaso/projects/6

**Comment by MariasStory** [comment]
Cool tool to get ideas from: https://github.com/EricZimmerman/MFTECmd

**Comment by joachimmetz** [comment]
@MariasStory please explain your comment we cannot assess every tool out there nor can we guess what you mean.

What element(s) of MFTECmd regarding collection filtering to do you think plaso needs to adopt?

**Comment by MariasStory** [comment]
Hi @joachimmetz and sorry for not being precise. Now, I am not sure if this comment is in the right place/issue.
I was referring to "ADS support" from the check list above. The MFTECmd does a good job there with "Zone.Identifier", as explained in: https://binaryforay.blogspot.com/2018/06/introducing-mftecmd.html
The ads info is extracted in: https://github.com/EricZimmerman/MFT/blob/96af1eb2124824bd41b505a3ecd29cd9362978e9/MFT/Other/ExtensionMethods.cs
-----------------
public static bool HasAds(this FileRecord record)
record.Attributes.Where(t =>
                    t.AttributeType == AttributeType.Data && t.NameSize > 0).ToList();
-----------------
public static List<AdsInfo> GetAlternateDataStreams(this FileRecord record)
...
-----------------
There are also another MFT atributes to look for, like flags. Also, the function public string GetFullParentPath(string recordKey) in https://github.com/EricZimmerman/MFT/blob/f16feea02a1d68965e68f0d3fb7bf5892d822cdd/MFT/Mft.cs

**Comment by joachimmetz** [comment]
@MariasStory still unclear to me what you mean. This issue is about enhancing the collection filters. The ADS support mentioned above is to update the [Collection Filter](https://github.com/log2timeline/plaso/wiki/Collection-Filters) specification to allow to specify the name of an ADS. The gotcha here is the Windows ADS naming convention allows for ambiguity (when applied cross-platform). Such as how to distinguish between a filename with `:` or an ADS. 

> There are also another MFT atributes to look for, like flags. 

I'm unfamiliar with a "flags" MFT attribute (Also: https://github.com/libyal/libfsntfs/blob/master/documentation/New%20Technologies%20File%20System%20(NTFS).asciidoc#61-the-attribute-types). 

> GetFullParentPath

I'm skeptical this takes into account that file A is part of directory B, file A gets deleted, directory B gets renamed to. Should the full path be "/B/A" or "/C/A" ?

**Comment by predictiple** [comment]
> This would be super handy for all those pointless files in C:\Windows\WinSxS

Collection filters support regex so the following seems to work:

`/(?i)^((?!winsxs).)*$`

**Comment by joachimmetz** [comment]
@dnides could you provide some additional explanation what you mean with the following suggestions in your original request.

- [ ] blacklisting entries in the filter files
- [ ] adding recursive support
- [ ] use "native" OS path notation

**Comment by dnides** [comment]
Sorry don’t recall what the need was anymore but no longer needed at this time. Feel free to close if you would like.

**Comment by joachimmetz** [comment]
Then closing this in favor of https://github.com/log2timeline/plaso/issues/1537
