### ISSUE TITLE
Should a 120GB raw OSX image take 4+ days to process?

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#1031]
**Plaso version:**

1.5.0

**Operating system Plaso is running on:**

Fedora 24

**Installation method:**

Installed via CERT Forensic Repo

**Description of problem:**

Parsing a raw dd image of an unencrypted 120GB OSX drive took over 4 days to parse (not mentioning ultimate failure due to https://github.com/log2timeline/plaso/issues/1014), using a Quad Core, 8 CPU, 16B RAM machine using all 8 cores and doing nothing but processing this evidence.

**Debug output/tracebacks:**

N/A

**Source data:**

Raw DD image acquired via dd of unencrypted physical drive.

**Comment by jasonblanks** [comment]
Have you tested the difference in time using '--disable_zeromq'? I believe at least in my instance (CentOS w/ virtualenv) my time was cut nearly in half.

**Comment by jpoling-dswrx** [comment]
I have not, but can. Will that also solve the stack pop/fail issue?

**Comment by joachimmetz** [comment]
Hard to tell how long plaso should take, this highly depends on data on the image. Running with [profiling](https://github.com/log2timeline/plaso/wiki/Profiling) can tell you more where the time is consumed.

**Comment by joachimmetz** [comment]
> Will that also solve the stack pop/fail issue?

https://codereview.appspot.com/309610043/ should fix issue #1014

**Comment by jpoling-dswrx** [comment]
Thanks for the heads up on profiling, wasn't aware of that. What specifically should be done in these cases to determine where the fault(s) may be? I can profile the CPU and memory, but how will that tell me where the inefficiencies or issues might be within the code?

**Comment by joachimmetz** [comment]
```
  --profiling_type TYPE, --profiling-type TYPE
                        The profiling type: "all", "memory", "parsers",
                        "processing" or "serializers".
```

to start, run with "processing" and "parsers" and share the results with us.

you'll need to be somewhat familiar with plaso internals to determine where the "inefficiencies or issues might be within the code".

Also read: https://github.com/log2timeline/plaso/wiki/Troubleshooting

**Comment by jpoling-dswrx** [comment]
May I specify multiple profiling options as `--profiling-type processing,parsers` ?

**Comment by joachimmetz** [comment]
don't think that is not supported yet; if you don't have guppy installed "all" should do the trick for now

**Comment by jpoling-dswrx** [comment]
Will do. 

As an aside, no more option "--use_old_preprocess" to pick back up where it left off?

**Comment by joachimmetz** [comment]
> As an aside, no more option "--use_old_preprocess" to pick back up where it left off?

not sure what you mean with "pick back up where it left off", use_old_preprocess would only re-use the previous pre-processing information, which is not a resume.

At the moment this functionality is no longer there, due to https://github.com/log2timeline/plaso/issues/241. There are ideas to re-implement a similar functionality to use_old_preprocess in the future. Also see: https://github.com/log2timeline/plaso/issues/787

**Comment by jpoling-dswrx** [comment]
Sorry, that is what I meant. 

Thanks for the feedback. Re-running the tool with profiling after making the zip_file.py changes. Will see what happens now.

**Comment by jpoling-dswrx** [comment]
`log2timeline.py --profiling_type all --profiling_directory l2t_profiling/ ...` yielded no output in the specified directory.

**Comment by jpoling-dswrx** [comment]
See: https://github.com/log2timeline/plaso/issues/1043

**Comment by Onager** [comment]
Profiling UX was changed in #1209 and processing extensively refactored in #1301 so these issue should no longer occurring. Please open a new issue if you see more examples of slowness.
