### ISSUE TITLE
pyvshadow issue

### ISSUE THREAD

**Issue by stumpyuk1** [log2timeline/plaso#1032]
Plaso 1.5.0 Win amd64 vs210 running on Win 8.1 

Running executable from folder, package downloaded from:
https://github.com/log2timeline/plaso/releases/download/1.5.0/plaso-1.5.0-win-amd64-vs2010.zip

When I try to run the executable to create a storage file, I get an error message:

> **Unable to scan source with error: unable to open file system with error: pyvshadow_volume_open_file_object: unable to open volume: libvshadow_store_block_read: invalid store block list store header identifier..**

Adding the option of --no_vss results in same error.    All dependencies are installed and up-to-date, this was a fresh install of python_plaso.

This looks like a repeat of issue #401 which was apparently fixed in version 1.40

**Comment by joachimmetz** [comment]
#401 is about Win2k3, the issue could be similar but is unlikely to be the same. Can you provide me a debug output log of running vshadowinfo on the same image (See: https://github.com/libyal/libvshadow/wiki/Troubleshooting#verbose-and-debug-output). That could help me determine the actual cause of the issue.

**Comment by jckpiumbini** [comment]
I have the same problem.
![2017-10-02 14_08_55-jean dfed-proc_](https://user-images.githubusercontent.com/8741548/31089898-1d9564cc-a77c-11e7-8eea-d6d82defa046.png)

**Comment by joachimmetz** [comment]
@jckpiumbini based on your screenshots you don't have the same error. You seem to have a volume without VSS,

**Comment by jckpiumbini** [comment]
@joachimmetz Can you help me?

**Comment by joachimmetz** [comment]
you'll need to be more specific, first stop hijacking this issue and file a new one with more explanation what issue you are encountering.

**Comment by jckpiumbini** [comment]
@joachimmetz I tried run the log2timeline.py in an specific clone. But I received the error.
 2017-10-03 17:56:16,196 [WARNING] (MainProcess) PID:6577 <log2timeline> Unable to scan source with error: Unable to open file system with error: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_store_block_read: unable to read store block data. libvshadow_store_descriptor_read_store_header: unable to read store block at offset: 26843545600. libvshadow_volume_open_read: unable to read store: 0 header. libvshadow_volume_open_file_io_handle: unable to read from file IO handle..

**Comment by joachimmetz** [comment]
> libvshadow_store_block_read: unable to read store block data. 

This is very low level error message, indicating it cannot read a structure it need.
How large is your source image? It is all there?

**Comment by Onager** [comment]
No updates in a year, closing issue.
