### ISSUE TITLE
USN Journal parsing

### ISSUE THREAD

**Issue by marcurdy** [log2timeline/plaso#1034]
**Plaso version:**

1.5.0

**Operating system Plaso is running on:**

Ubuntu 14.04

**Installation method:**

GIFT from SIFT infused distro

**Description of problem:**

Running a standard log2timeline against a USN journal file only produces a FILE parsed entry and does not parse it as a valid USN journal entry.

9/27/2016 15:04:47	UTC	**..C.**	FILE	OS **ctime	ctime**	c_UsnJrnl.bin	OS:/…./c_UsnJrnl.bin Type: file	filestat	file_size: (537198592 )  file_system_type: OS  is_allocated: True  sha256_hash: xxxxxxxx

9/27/2016	15:04:47	UTC	**M...**	FILE	OS **mtime	mtime**	c_UsnJrnl.bin	OS:/…./c_UsnJrnl.bin Type: file	filestat	file_size: (537198592 )  file_system_type: OS  is_allocated: True  sha256_hash: xxxxxxxx

9/29/2016	3:53:38	UTC	**.A..**	FILE	OS **atime	atime**	c_UsnJrnl.bin	OS:/…./c_UsnJrnl.bin Type: file	filestat	file_size: (537198592 )  file_system_type: OS  is_allocated: True  sha256_hash: xxxxxxxx

What does the tool not do that it should? What would you like it to do?

I would like the data from this file to be expanded out instead of treating the file as a mactime only.

A debug of the process only shows these parsers and extractors:
===parsers===
mac_appfirewall_log
mac_securityd
macwifi
popularity_contest
selinux
skydrive_log_old
winfirewall
winiis
xchatlog
xchatscrollback
===extractors===
android_app_usage
bencode
bsm_log
chrome_cache
chrome_preferences
cups_ipp
custom_destinations
dockerjson
firefox_cache
firefox_cache2
hachoir
java_idx
mac_appfirewall_log
mac_keychain
mac_securityd
mactime
macwifi
mcafee_protection
openxml
opera_global
opera_typed_history
[ParseDataStream]
plist
pls_recall
popularity_contest
sccm
selinux
skydrive_log
skydrive_log_old
symantec_scanlog
syslog
utmp
utmpx
winfirewall
winiis
winjob
xchatlog
xchatscrollback

**Source data:**
win2008sp2x64 offlined USN journal from the disk

Please describe the source that is causing the issue.

I could only guess.

**Comment by joachimmetz** [comment]
> Running a standard log2timeline against a USN journal file only produces a FILE parsed entry and does not parse it as a valid USN journal entry.

Parsing the USN change journal as a stand-alone file is currently not supported plaso.

**Comment by marcurdy** [comment]
Thought I saw it in the timeline crossed off in the 1.4 category.  Must be a different aspect of USN.

**Comment by joachimmetz** [comment]
parsing it as part of a volume is currently supported. This has to do that the stand-alone file does not have a distinct signature. I'm considering adding an option that can force a single file to be parse as an USN change journal but this is far from efficient, seeing that the $J data stream will have a large sparse section when written as a stand-alone file.
