### ISSUE TITLE
Unable to use more than one tagging source

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1037]
**Plaso version:**

1.5.0 Release

**Operating system Plaso is running on:**

XUbuntu 64 bit

**Installation method:**

Installed from GiFT

**Description of problem:**

I have been using the `nsrlsvr` analysis as well as the `tagging` analysis plugin. Both plugins tag events. After running both analysis plugins, tags from both plugins end up in the `event_tag_data` files in the dump file. 

When outputting formatted data, the tags are retrieved from that dump file. When one event is tagged by both plugins, only one of the tags is exported. I'd like to see both tags in the output.

**Source data:**

A single tag is set in line 1565 of `storage/zip_file.py`: 

```
event.tag = self._ReadEventTagByIdentifier(event.store_number, event.store_index, event.uuid)
```

Apart from the assignment there, `_ReadEventTagByIdentifier` itself would also need changes. In this function, a tag is retrieved by using `event_uuid` as a reference. More than one tag could be available with that reference though, so which tag would need to be read by the function is ambiguous.

**Comment by Onager** [comment]
I think this is bug, not an FR - we should be returning both tags.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/303250043/ addresses some of these issues already.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/314840043 adds multiple tags in generated tests files.

**Comment by joachimmetz** [comment]
Bumping this to 1.6 needs storage improvements

**Comment by pettai** [comment]
> https://codereview.appspot.com/314840043 adds multiple tags in generated tests files.

Will this work as an interim solution or do we need to wait for 1.6 ?

(btw. the "tagging" analysis plugin is painfully slow (average at ~6 events /second) ...is there any way to improve it's performance?)

**Comment by pettai** [comment]
@kinky-it do you actually get any tagged events out of --analysis tagging and the included tag_windows.txt file ? I've tried it on two different windows images and I got zero hits = zero tag.

**Comment by kinky-it** [comment]
On 2016-12-06 23:45, pettai wrote:
> @kinky-it [1] do you actually get any tagged events out of --analysis
> tagging and the included tag_windows.txt file ? I've tried it on two
> different windows images and I got zero hits = zero tag.

I do. Quickest check is to run log2timeline on a single file. 
Afterwards, apply tags using a tagging file with the following content:

test_volume
   display_name contains 'volume'

test_mtime
   type contains 'mtime'

Then create a json_line output file. You will notice the tags in the 
json output.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/1364

**Comment by joachimmetz** [comment]
Changed tests indicate this currently working as intended: https://codereview.appspot.com/327150043
