### ISSUE TITLE
Syslog parser attempts to parse wifi.log files on MacOS.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1040]
The syslog parser attempts to parse wifi.log files, even though we have a dedicated wifi.log parser (macwifi). It would be nice if we didn't do this.

**Comment by jnettesheim** [comment]
I looked at this quickly today, can knock out this week.  Please assign to me?

**Comment by joachimmetz** [comment]
@jnettesheim this might require some changes to the core of the how the parsers are handled. The original designed behavior, to match l2t.pl was to brute force every parser on files.

**Comment by jnettesheim** [comment]
Might be worth a chat about to see if there's consensus about a solution, I have a few thoughts.  

On a separate note, I have noticed that the current implementation drops the "header" log entry.  For example, from the test file:

#1 Thu Nov 14 20:14:37.123 ***Starting Up***
#2 Thu Nov 14 20:36:37.222 <airportd[88]> airportdProcessDLILEvent: en0 attached (up)

Line # 1 is purposefully dropped so the parser does not output the "Starting Up" entry.  Is that typically something we would want?  Logic for it is in the parser at:

https://github.com/log2timeline/plaso/blob/master/plaso/parsers/mac_wifi.py#L212

**Comment by joachimmetz** [comment]
> Might be worth a chat about to see if there's consensus about a solution

SG, some of the design decisions here might date back to the perl version of log2timeline

> Is that typically something we would want?

IMO this is an event as well, I'm OK with adding it

**Comment by jnettesheim** [comment]
Code pushed, closing out.
