### ISSUE TITLE
Profiling yields no output

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#1043]
**Plaso version:**

1.5.0

**Operating system Plaso is running on:**

Fedora 24

**Installation method:**

Installed via CERT Forensic Repo

**Description of problem:**

Running the "--profiling all" option yields no output.

**Debug output/tracebacks:**

Full command run:

`log2timeline.py --profiling_type all --profiling_directory l2t_profiling/ --parsers macosx --workers 7 --status_view window --show_memory_usage --logfile disk_l2t.log Evidence1.dmg`

**Comment by joachimmetz** [comment]
Thx for the report, I'll have a look to see if I can reproduce it

**Comment by Onager** [comment]
Unintuitively, you also need to pass the `--profile` flag.  I'd like to kill this flag, and refactor the whole set of profiling options, as it's pretty untidy at present.

**Comment by jpoling-dswrx** [comment]
Agreed - rather unintuitive. Thanks for the heads up.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/324760043

**Comment by joachimmetz** [comment]
Changes merged see if UX is easier now
