### ISSUE TITLE
IO Error Unable to close zip file

### ISSUE THREAD

**Issue by JJGNinja** [log2timeline/plaso#1044]
**Plaso version:**

1.5.0 Release

**Operating system Plaso is running on:**

Windows 7 64 bit

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

I am running log2timeline against a Windows 7 EnCase image and I get the following error. The error is similar when I run release 1.4

log2timeline.exe D:\outputfile.dump C:\Image.E01

**Debug output/tracebacks:**

_1ed3e39fa0e82451.manifest - running: True
Worker_05 (PID: 8936) - events produced: 73761 - file: TSK:/Windows/winsxs/Manif
ests/amd64_560f6c4c530c3f334550c7fe16f3bfe8_b03f5f7f11d50a3a_6.1.7601.18523_none
_11276d372684ac0e.manifest - running: True
Worker_06 (PID: 8244) - events produced: 35166 - file: TSK:/Windows/winsxs/Manif
ests/amd64_1801ff46b0038a215bcb9a578c41e381_31bf3856ad364e35_6.1.7601.22948_none
_f628d446d8c33259.manifest - running: True
Worker_00 (PID: 7300) - events produced: 39046 - file: TSK:/Windows/winsxs/Manif
ests/amd64_1807bad8b2b2f763ead7c8283af89418_31bf3856ad364e35_6.1.7601.22948_none
_8952cdbe225ebe4c.manifest - running: True
Worker_01 (PID: 9828) - events produced: 38960 - file: TSK:/Windows/winsxs/Manif
ests/amd64_c64c420f5864b56f41d74a09d3a4941a_31bf3856ad364e35_6.1.7601.18283_none
_b5294749e54eed83.manifest - running: True
Worker_02 (PID: 6976) - events produced: 142582 - file: TSK:/Windows/winsxs/Mani
fests/amd64_c676a0020db510e03f85c3c282649d4b_b03f5f7f11d50a3a_6.1.7601.22126_non
e_68209002c0eb95f1.manifest - running: True
Worker_03 (PID: 5920) - events produced: 33303 - file: TSK:/Windows/winsxs/Manif
ests/amd64_c674cf3fa12c9cc4f7660de00e347f5c_31bf3856ad364e35_8.0.7601.18896_none
_5a8189255a43ef92.manifest - running: True
Worker_04 (PID: 3652) - events produced: 37179 - file: TSK:/Windows/winsxs/Manif
ests/amd64_17d14f100ce72ece57016d46cc15798a_31bf3856ad364e35_6.1.7601.22012_none
_1ed3e39fa0e82451.manifest - running: True
Worker_05 (PID: 8936) - events produced: 73889 - file: TSK:/Windows/winsxs/Manif
ests/amd64_182eb380a45e99158ce9ac3afdad9374_b03f5f7f11d50a3a_6.1.7601.17966_none
_556819c98849a84e.manifest - running: True
Worker_06 (PID: 8244) - events produced: 35166 - file: TSK:/Windows/winsxs/Manif
ests/amd64_1801ff46b0038a215bcb9a578c41e381_31bf3856ad364e35_6.1.7601.22948_none
_f628d446d8c33259.manifest - running: True
Traceback (most recent call last):
  File "tools\log2timeline.py", line 767, in <module>
  File "tools\log2timeline.py", line 753, in Main
  File "tools\log2timeline.py", line 664, in ProcessSources
  File "plaso\frontend\extraction_frontend.py", line 483, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 796, in ProcessSources
  File "plaso\storage\zip_file.py", line 3090, in Close
  File "plaso\storage\zip_file.py", line 2489, in Close
IOError: Unable to close storage file.
Failed to execute script log2timeline

**Source data:**

Windows 7 image.

**Comment by joachimmetz** [comment]
ZIP storage has been removed, marking issue as obsolete
