### ISSUE TITLE
psort: hasher analysis plugin not aborting when server is not available

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1046]
psort happily continues when:

```
2016-10-15 12:30:54,829 [ERROR] (nsrlsvr   ) PID:18910 <nsrlsvr> Error communicating with nsrlsvr [Errno 111] Connection refused. nsrlsvr plugin is aborting
```
- [x] ~~[Check connectivity in CLI helper - nsrlsvr](https://codereview.appspot.com/312850043/)~~
- [x] ~~[Check connectivity in CLI helper - viper](https://codereview.appspot.com/310530043/)~~
- [x] [Check connectivity in CLI helper - virustotal](https://codereview.appspot.com/326200043/)

**Comment by Onager** [comment]
Isn't this WAI, as stated? One analysis plugin dying shouldn't kill psort.

It looks like you actually want to check if the options are correct up front, but that's different to aborting if the server becomes unavailable.

**Comment by joachimmetz** [comment]
IMO this is a usability in the bug in the analysis hash tagging plugins, why bother running the analysis plugin if the server is not available or internet connectivity at all.

**Comment by joachimmetz** [comment]
bumping VT connectivity check to version 1.6
