### ISSUE TITLE
Hashing status info is shown which hashers are disabled

### ISSUE THREAD

**Issue by jamdunnDFW** [log2timeline/plaso#1055]
**Plaso version:**

1.5 Release

**Operating system Plaso is running on:**

Windows Server 2008 R2

**Installation method:**

Windows Packaged Release

**Description of problem:**

I am unable to disable hashing using the "--hashers none" option in version 1.5. Has anyone else run into this?

**Comment by Onager** [comment]
I had a look, but I can't reproduce this - can you try running with debugging on `-d` and look at the output (you might want to redirect to a file with `--logfile c:\some_file.txt`).

You should see a line like this:

`2016-10-21 13:51:57,730 [DEBUG] (MainProcess) PID:11411 <hashing_analyzer> Got hasher names []`

Or, if the hashers aren't being disabled, it'll say something in those empty brackets instead.

**Comment by jamdunnDFW** [comment]
I'm re-running now. I'll get back to you soon.

**Comment by joachimmetz** [comment]
this is because there is a disjunct between the hashing and the status information.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/317790043/

**Comment by joachimmetz** [comment]
Added some changes to improve UX
