### ISSUE TITLE
Duplicate Event Tags in pinfo

### ISSUE THREAD

**Issue by jamdunnDFW** [log2timeline/plaso#1067]
**Plaso version:**

Ubuntu Development Release 1.5.2_20161224 

**Operating system Plaso is running on:**

Windows XP

**Installation method:**

Built using git clone https://github.com/log2timeline/plaso.git

**Description of problem:**

I ran two (slightly different) tagging analyses over the same storage file and found the number of event tags doubled when an entry was tagged twice with the same tag. 

The output using psort de-duplicates fine and doesn't appear to cause any issues. The only thing that seems to be affected is the pinfo report "Event tags generated per label", which reports double the amount of tags that actually exist. 

Not sure if this qualifies as an issue or something I should just not do again.

**Comment by joachimmetz** [comment]
How tags are currently stored are far from optimal. We are planning to overhaul this as part of https://github.com/log2timeline/plaso/issues/568

**Comment by jamdunnDFW** [comment]
10-4, thanks for the update

**Comment by joachimmetz** [comment]
Closing issue, it refers to the old ZIP based storage file.
