### ISSUE TITLE
Please update docker image to 1.5.1

### ISSUE THREAD

**Issue by mckeowbc** [log2timeline/plaso#1072]
I talked with Daniel yesterday at OSDFCon about getting the log2timeline/plaso Docker image updated to 1.5.1 on Docker Hub.  He mentioned that he could ping the maintainer of that image.  Just wanted to make sure that stayed in someone's queue, since I know I forget many things that were said during happy hours.

Cheers!

**Comment by rgayon** [comment]
Pushed the update on docker.io.
I'll mark as resolved once the current issue is over ( https://status.docker.com/ ) and the tags show up.

**Comment by rgayon** [comment]
1.5.1 image has been updated on https://hub.docker.com/r/log2timeline/plaso/tags/

**Comment by rgayon** [comment]
Updated Maintainer's guide: **https://github.com/log2timeline/plaso/wiki/Maintainers-guide#updating-the-plasos-image-on-dockers-hub-to-the-latest-version-in-ppa**
