### ISSUE TITLE
Import Error libscca.so.1

### ISSUE THREAD

**Issue by jacob827** [log2timeline/plaso#1080]
Been using log2timeline 1.4 and had no problems. I ran sudo apt-get update and sudo apt-get install python-plaso, but the installation failed midway through. I'm unable to get log2timeline to run or reinstall. Any assistance would be appreciated.

Plaso version: 1.5.1
Operating system Plaso is running on: Ubuntu 14.04, Sift Workstation 3.19.0-25-generic

Installation method: apt-get install python-plaso

Description of problem: Unable to launch log2timeline.py; provides error message ImportError: libscca.so.1: cannot open shared object file: no such file or directory

**Debug output/tracebacks:**

![error](https://cloud.githubusercontent.com/assets/15809908/20147440/14d63c10-a676-11e6-84ab-a00a32b7f049.jpg)
Please run the tool with "-d" to generate debug output, and include anything relevant.

**Source data:**

Please describe the source that is causing the issue.

**Comment by joachimmetz** [comment]
From which repository did you install libscca-python?

**Comment by joachimmetz** [comment]
Just checked GIFT PPA on Ubuntu 14.04 live boot, packages are fine. Can you check if you're actually downloading the packages from GIFT. Also see: https://github.com/log2timeline/plaso/wiki/Troubleshooting-Ubuntu

**Comment by joachimmetz** [comment]
No response from OP closing.
