### ISSUE TITLE
JSON serializer support for AttributeContainers inside AttributeContainers

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#1085]
**Plaso version:**

1.5.2-20161108

**Operating system Plaso is running on:**

Windows 7 64 bit

**Installation method:**

Dev environment

**Description of problem:**

Currently the JSON serializer assumes all dictionaries inside AttributeContainers are native dictionaries and doesn't consider that the dictionary could be another AttributeContainer or another non-native JSON type (like a tuple). 

I would like to provide a code submission that fixes this issue.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/319730043/

**Comment by joachimmetz** [comment]
@dc3-plaso sorry for the slow response, this change is not forgotten. I'll revisit this after ZIP storage deprecation https://github.com/log2timeline/plaso/issues/1585

**Comment by joachimmetz** [comment]
Closing this, this should not be a goal by itself but driven by the needs of the data mode.
