### ISSUE TITLE
Missing sleep time during opening of gzip storage file.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#1088]
plaso.storage.gzip_file module is missing sleep time during open (https://github.com/log2timeline/plaso/blob/master/plaso/storage/gzip_file.py#L320) which is sometimes causing IOErrors when running psort with analysis plugins (on Windows).

It should have:
```python
 time.sleep(self._LOCKED_FILE_SLEEP_TIME)
```
similar to merge function: https://github.com/log2timeline/plaso/blob/master/plaso/storage/gzip_file.py#L425

**Comment by Onager** [comment]
This is now fixed.
