### ISSUE TITLE
add multi volume support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#109]
Depends on phased processing changes
- [x] ~~change source scanner and collector to handle multiple file system path specs~~
- [x] ~~add support to process multi volumes to the extraction frontend~~
- [x] ~~add support for encrypted volumes for now BDE~~
  - ~~https://codereview.appspot.com/251910043~~
  - ~~make sure to rescan BDE for VSS in BDE~~
  - ~~determine which credentials are actually available in the BDE volume~~
- [x] ~~[add support to select a range of partitions/volumes](https://github.com/log2timeline/plaso/issues/537)~~
- [x] ~~fix preprocessor to handle more than one system configuration~~
  - **moved to https://github.com/log2timeline/plaso/issues/2286**
- [x] ~~fix tools to handle more than one source~~
  - **moved to https://github.com/log2timeline/plaso/issues/2287**
- [x] ~~Store scanning options in VolumeScanOptions objects ?~~
  - ~~https://codereview.appspot.com/340700043/~~
  - ~~make VolumeShadowSnapshotsOptions more generic?~~
  - ~~move part of this functionality into dfvfs~~
  - **moved to https://github.com/log2timeline/dfvfs/issues/341**
- [x] ~~print overview of volumes to be processed~~
  - **moved to https://github.com/log2timeline/plaso/issues/4610**

Related:
- ~~https://github.com/log2timeline/plaso/issues/180~~
- ~~https://codereview.appspot.com/238390043~~
- ~~https://codereview.appspot.com/232710043~~
- ~~https://codereview.appspot.com/246600043~~

**Comment by f-s-p** [comment]
+1

**Comment by pettai** [comment]
Is this issue about being able to understand Linux LVM too? (I noted that LVM was mentioned in https://github.com/log2timeline/plaso/issues/180) Or should I open a new issue?

It doesn't seem to it work ATM:

-bash-4.3$ log2timeline.py plaso.dump clone.vmdk
[INFO] Data files will be loaded from /usr/share/plaso by default.
The following partitions were found:
Identifier	Offset (in bytes)	Size (in bytes)
p1		1048576 (0x00100000)	243.0MiB / 254.8MB (254803968 B)
p2		256901120 (0x0f500000)	19.8GiB / 21.2GB (21216886784 B)

Please specify the identifier of the partition that should be processed.
All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
p2
2015-09-13 16:29:54,395 [WARNING] (MainProcess) PID:24955 <log2timeline> No supported file system found in source.

**Comment by joachimmetz** [comment]
> Is this issue about being able to understand Linux LVM too? 

Yes. Also see: https://github.com/log2timeline/dfvfs/wiki/Roadmap#volume-systems

> It doesn't seem to it work ATM:

This is still on the to do list.

**Comment by pettai** [comment]
just wanna add +1 for fixing LVM support
