### ISSUE TITLE
output analysis reports without stripping all the newlines

### ISSUE THREAD

**Issue by TABrowne** [log2timeline/plaso#1090]
1.5.2 Release

Linux Ubuntu 14.04

Installed and compiled from source Github

Can the analysis search function of psort.py revert back to output similar in plaso version 1.3. 
When I run psort.py --analysis browser_search or unique_domains , it runs correctly but the output is very congested and hard to read. If the search terms could be outputted on separate lines like it used to do in plaso version 1.3, it would be more easy to read and comprehend.

**Comment by Onager** [comment]
Yep, these are just about unreadable at present. I'll fix this up.

**Comment by Onager** [comment]
Tracked the cause of this to the CLITableView class, which pinfo uses to output analysis reports. As part of getting the line wrapping to look nice, it removes all lines breaks from analysis reports. This raises a few questions about correct formatting/outputting of analysis reports, so this might take a little longer to end up with a tidy fix.

**Comment by joachimmetz** [comment]
@Onager what needs to be done here?

**Comment by Onager** [comment]
There needs to be a way to output analysis reports without stripping all the newlines.

**Comment by joachimmetz** [comment]
Moving away for analysis reports in favor of analysis results https://github.com/log2timeline/plaso/issues/1590
