### ISSUE TITLE
Does Plaso support the YAML definitions on ForensicAritfacts?

### ISSUE THREAD

**Issue by herptroll** [log2timeline/plaso#1091]
Hi,

Instead of using the standard provided filter_windows.txt that ships with Plaso, is it possible to provide the yaml files from ForensicArtifacts as argument instead? Is this supported? I get an error when trying to do so.

Thanks

**Comment by Onager** [comment]
It's not presently possible, but it is a good idea. @jnettesheim said he'd take a look at implementing this.

**Comment by joachimmetz** [comment]
Already a feature request for this: https://github.com/log2timeline/plaso/issues/155
