### ISSUE TITLE
Add database schema matching to sqlite plugins.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#1093]
**Plaso version:**

1.5.2_20161108

**Operating system Plaso is running on:**

Windows 7 64 bit

**Installation method:**

Dev environment

**Description of problem:**

Would like to add database schema matching capabilities to the sqlite plugins. This will help to detect when certain applications have changed their database since the last time the plugin was developed as well as produce a stronger confidence that the results are accurate.

I would like to create a code submission for this change.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/316460043/ has been merged

**Comment by joachimmetz** [comment]
Fix post commit comment in https://codereview.appspot.com/316460043/
