### ISSUE TITLE
Firefox_cache parser needed to be modified

### ISSUE THREAD

**Issue by kimtaehong** [log2timeline/plaso#1100]
Since the record header and major version of version 2 of Firefox Cache2 file have recently changed, it is necessary to modify the module contents of "ParseFileObject".

**Comment by joachimmetz** [comment]
Can you be more specific of what needs to be modified and how

**Comment by joachimmetz** [comment]
@kimtaehong can you be more specific on what you think needs to be changed

**Comment by Onager** [comment]
We need more information to be able to act on this. Feel free to reopen with more clarification.
