### ISSUE TITLE
Missing ".git" in repo origin URL breaks review.py

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1101]
in review.py : 
```
self._git_repo_url = b'https://github.com/log2timeline/{0:s}.git'.format(
        self._project_name)
```

If the repo is cloned using:
`git clone https://github.com/log2timeline/plaso` instead of `git clone https://github.com/log2timeline/plaso.git`

then the origin url will mismatch in 
```def CheckHasProjectOrigin(self):                                                                                                  
    origin_git_repo_url = self.GetRemoteOrigin()                                 
    return origin_git_repo_url == self._git_repo_url
```

because of the trailing ".git" in  `self._git_repo_url`.

**Comment by joachimmetz** [comment]
Please file this against l2tdevtools, we'll likely need to add more error tolerance there

**Comment by rgayon** [comment]
Bug is now https://github.com/log2timeline/l2tdevtools/issues/102
Closing
