### ISSUE TITLE
Add SCCM metering execution artifact

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1105]
Use the mandiant parser to improve the program execution evidence. 

https://www.fireeye.com/blog/threat-research/2016/12/do_you_see_what_icc.html

**Comment by joachimmetz** [comment]
@nwf9 if you are asking to add CIM support (WMI) that is already pending in https://github.com/log2timeline/plaso/issues/179

There are some issues with the flare-cmi implementation why we cannot directly use it.

**Comment by nwf9** [comment]
Thanks
