### ISSUE TITLE
Elasticsearch with Windows binary version

### ISSUE THREAD

**Issue by orlikoski** [log2timeline/plaso#1106]
**Plaso version:** 1.5.x
**Operating system Plaso is running on:** Windows 10 64-bit
**Description of problem:**

Is it possible to use the elasticsearch output module while using the pre-compiled windows binaries?  If so, what is required to enable it?

thank you

**Comment by joachimmetz** [comment]
> Is it possible to use the elasticsearch output module while using the pre-compiled windows binaries? 

likely, try installing pyelasticsearch

**Comment by rough007** [comment]
I tried installing that with pip on python 2.7 but psort.exe -o list still
shows elasticsearch disabled.  I also added python and python\scripts to
the path to see if that made a difference. It did not.  Any suggestions for
other things I can try?

Thanks

**Comment by berggren** [comment]
@rough007 We have switched to the official Elastic python client in order to get the best support for new versions. You can install it by:

    pip install elasticsearch

This will enable the elastic output module.

**Comment by rough007** [comment]
@berggren thanks and tried installing it (Python 27) with and without having "C:\Python27\Scripts;C:\Python" as the first entries in the path.  "Elastic" still shows up in the disabled list when I do "psort.exe -o list".

I'm starting to think it may not be possible with the precompiled binaries.  If someone does have it working; I would be very grateful if they would please respond to this thread with the details.

**Comment by joachimmetz** [comment]
Try copying the elasticsearch module (and dependencies) into the pyinstaller built directory

**Comment by joachimmetz** [comment]
blocked by #1828

**Comment by joachimmetz** [comment]
Changes for https://github.com/log2timeline/plaso/issues/1828 should bundle elasticsearch-py in Windows pyinstaller build. I'll close this issue in favor of #1828
