### ISSUE TITLE
Fix failing AppVeyor tests

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1108]
* [x] ~~part 1 https://ci.appveyor.com/project/joachimmetz/plaso/build/2486~~
* [x] ~~Test failing on Windows not on Linux and macOS~~
  * ~~https://ci.appveyor.com/project/joachimmetz/plaso/build/2514#L2442~~
  * ~~credentials not being passed to workers https://github.com/log2timeline/plaso/issues/1112~~
* [x] ~~https://ci.appveyor.com/project/joachimmetz/plaso/build/2537#L2283~~

**Comment by Onager** [comment]
We need appveyor tests to be passing before we release.
