### ISSUE TITLE
BDE credentials are not passed to worker processes on Windows

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1112]
Per troubleshooting: https://github.com/log2timeline/plaso/issues/1108 determined that BDE credentials are not passed to worker processes on Windows

* [x] ~~https://codereview.appspot.com/311490043/~~
* [x] ~~Work-around on AppVeyor~~
* [ ] add end-to-end test https://github.com/log2timeline/plaso/issues/1905
* [x] Fix scanner failing when BDE volume already unlocked

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/311490043

**Comment by joachimmetz** [comment]
solved the issue on test vm, but still an issue on appveyor
https://ci.appveyor.com/project/joachimmetz/plaso/build/2627#L2465

**Comment by Onager** [comment]
Not making September release, removing milestone.

**Comment by joachimmetz** [comment]
Pending changes for unit test in https://github.com/log2timeline/plaso/pull/3037
