### ISSUE TITLE
limit maximum amount of memory used by worker

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1121]
Prevent a grinding slow down before OOO killer by having the foreman monitor and limit the maximum amount of memory used by worker.

* [x] ~~kill process when more then X amount of memory is consumed~~
* [x] ~~[retry task if worker was killed because of OOM](https://github.com/log2timeline/plaso/issues/1200)~~
* [x] ~~make sure new process is monitored also see https://github.com/log2timeline/plaso/issues/1203~~
* [x] ~~test on linux~~

For a distributed worker we likely want to adopt a nanny approach similar to that of GRR

**Comment by Onager** [comment]
I've tested this on Linux, and can confirm the worker is killed when it uses too much memory. Regarding #1203, we now catch this error and retry starting a replacement worker, as of #1301.

**Comment by joachimmetz** [comment]
Closing issue did some rough checks on Windows and macOS.
