### ISSUE TITLE
Feature request : Add Kaspersky event log into timeline

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1126]
Grab the Kaspersky endpoint security Windows event log where is present at 
C:\\Windows\System32\winevt\Logs\Kaspersky Event Log.evtx into the timeline.

**Comment by joachimmetz** [comment]
EVTX is already supported can you provide an example of the file and describe in detail what your feature request is.

**Comment by nwf9** [comment]
Yes evtx was supported but this event log journal is not include on a timeline like mcafee while those content is very useful.

**Comment by joachimmetz** [comment]
That is dependent on how you invoke log2timeline.py.

Can you try running log2timeline.py directly on "C:\Windows\System32\winevt\Logs\Kaspersky Event Log.evtx" and see if it returns results.

**Comment by nwf9** [comment]
When you invoke log2timeline you have an automatic detection of parser by default. That's why i think it will be useful for the analysis to add directly this log on the timeline.

**Comment by joachimmetz** [comment]
For evtx this is already the case, if this is not working this can be because:

* either the invocation of lg2timeline indicates to skip the file
* it is not an evtx file
* there is an error parsing the file

Per previous request can you try running log2timeline.py directly on "C:\Windows\System32\winevt\Logs\Kaspersky Event Log.evtx" and see if it returns results.

**Comment by nwf9** [comment]
Yes it's works without any errors.

**Comment by joachimmetz** [comment]
Then we need to figure out why it is not working in the other case. Can you provide the following information:

```
**Plaso version:**

For example 1.4.0 Release

**Operating system Plaso is running on:**

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

Please describe the problem in as much detail as possible, including relevant command line arguments, flags etc.
What does the tool not do that it should? What would you like it to do?

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.

**Source data:**

Please describe the source that is causing the issue.
```

**Comment by Onager** [comment]
@nwf9 Any more information on this? Plaso has a parser for .evtx files, so it should be processing the kaspersky log you mention.

**Comment by Onager** [comment]
No recent reply, closing this out.
