### ISSUE TITLE
Feature request : Add Srum database 

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1127]
Add the new parser Srum database parser into the timeline https://github.com/williballenthin/srum-dump

**Comment by joachimmetz** [comment]
Duplicate of: https://github.com/log2timeline/plaso/issues/427

**Comment by joachimmetz** [comment]
For context https://github.com/williballenthin/srum-dump is an out of date fork (copy) of https://github.com/MarkBaggett/srum-dump with some alterations.
