### ISSUE TITLE
Feature request : Generate registry timeline based on Last write  time

### ISSUE THREAD

**Issue by nwf9** [log2timeline/plaso#1128]
Use the "Last write time" timestamp to generate a timeline for the registry plugin

**Comment by joachimmetz** [comment]
REGF is already supported can you provide an example of the file and describe in detail what your feature request is.

**Comment by nwf9** [comment]
There is no plugin with preg which permit to check the last write time on each hive directly.

**Comment by joachimmetz** [comment]
last write time is stored per key not per hive

**Comment by nwf9** [comment]
Yes,  but the main need is that actually you cannot generate a timeline on the hive to detect the last write time for each key.

**Comment by joachimmetz** [comment]
why not? log2timeline will create a timeline of a REGF file.

**Comment by nwf9** [comment]
It check various artifact to generate a super or micro timeline but not only a last write time key. Actually i have to use also regtime to retrieve this metadata https://github.com/keydet89/RegRipper2.8/blob/master/plugins/regtime.pl

**Comment by joachimmetz** [comment]
log2timeline should parse the last written time in REGF files, if this is not working please provide the following information:

```
**Plaso version:**

For example 1.4.0 Release

**Operating system Plaso is running on:**

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

Please describe the problem in as much detail as possible, including relevant command line arguments, flags etc.
What does the tool not do that it should? What would you like it to do?

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.

**Source data:**

Please describe the source that is causing the issue.
```

**Comment by joachimmetz** [comment]
> It check various artifact to generate a super or micro timeline but not only a last write time key.

I think I finally suspect what you are asking:
You only want events based on the last written time not based on the winreg_plugins.
Have you tried disabling the winreg_plugins?

**Comment by nwf9** [comment]
Correct, i don't have test to disable this plugin.

**Comment by joachimmetz** [comment]
Assuming question was answered, closing issue.
