### ISSUE TITLE
Syslog parser will stop parsing if log contains un-parseable date

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1142]
When parsing test_data/syslog with preferred year 2013 (non-leap) the syslog parser will only generate 9 events with year 2012 (leap) is returns 16. Preferred behavior is to generate 15 events and 1 error for a non-leap year.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/320020043/

**Comment by Onager** [comment]
@joachimmetz Can this be closed now?
