### ISSUE TITLE
deprecate not needed event values (attributes)

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1148]
deprecate not needed attributes

* [x] event remove the need for tag https://github.com/log2timeline/plaso/pull/3028
* [ ] report remove the need for report_dict ~~and report_list~~
  * moved to https://github.com/log2timeline/plaso/issues/1590

**Comment by Onager** [comment]
Removing from milestone for 1.5.2 - this is a nice to have, not essential.
