### ISSUE TITLE
Request:  Quickstart for log2timeline-legacy users

### ISSUE THREAD

**Issue by DigiAngel** [log2timeline/plaso#1152]
Topic says it...my script was like so:
~~~
log2timeline -z MST -f mft -p -r /media/forensics > newbodyfile.txt
log2timeline -z MST -f iehistory -p -r /media/forensics/Documents\ and\ Settings/ >> newbodyfile.txt
log2timeline -z MST -f ntuser -p -r /media/forensics/Documents\ and\ Settings/ >> newbodyfile.txt
log2timeline -z MST -f system /media/forensics/WINDOWS/system32/config/system >> newbodyfile.txt
log2timeline -z MST -f evt -p -r /media/forensics/WINDOWS/system32/config >> newbodyfile.txt
log2timeline -z MST -f prefetch /media/forensics/WINDOWS/Prefetch >> newbodyfile.txt
log2timeline -z MST -f wmiprov /media/forensics/WINDOWS/system32/wbem/Logs/wmiprov.log >> newbodyfile.txt
l2t_process -b newbodyfile.txt <MM-DD-YYYY-MM-DD-YYYY> > timeline.csv
~~~

With this never version I'm pretty lost though....is there a quickstart somewhere that will allow me to get similar to the above?  Thanks...sorry for the ignorance.

**Comment by joachimmetz** [comment]
Have you looked at https://github.com/log2timeline/plaso/wiki/Upgrading-From-0.x-Branch ?

**Comment by DigiAngel** [comment]
Heh...of course one was already don and I missed it like an idiot...yugh 8-|  I'll run the again my image on Monday and see if I can get the same results...thank you!

**Comment by joachimmetz** [comment]
It me interesting for us to know where/how you were searching for this information, so we can make it more discoverable

**Comment by DigiAngel** [comment]
Ah...well I hit here a lot:
~~~
https://github.com/log2timeline/plaso/wiki/Using-log2timeline
~~~
Truth be told the "Upgrading from 0.x Branch" link made me think of how to actually upgrade the application...like...which new packages and dependencies and whatnot, not actual usage, so I never went there.  And, my perception at least, the Using-log2timeline link doesn't actually show you how to create a timeline...almost all the commands shown on that page show how to gather the data.  Only one command example under Triage isn't about gathering data, but is only for data verification...no where on the Using page does it show how to ACTUALLY make a usable timeline.  And pretty much everything on the net right now shows the old information about log2timeline, not the new stuff.

I would love to see a side link under the User Guide one day that could be something like "Your first timeline" that could take you start to finish with the result a usable csv or xlsx.  Anyway thank you...and thanks for all your hard work on plaso!

**Comment by joachimmetz** [comment]
Renamed the wiki patge: https://github.com/log2timeline/plaso/wiki/Log2Timeline-Perl-(Legacy)

> start to finish with the result a usable csv or xlsx

Ack, I think Kristinn his original idea was to do this on the blog
http://blog.kiddaland.net/2012/12/first-alpha-release-of-log2timeline.html?view=sidebar

Should be easy to add some example use cases

**Comment by joachimmetz** [comment]
I've added https://github.com/log2timeline/plaso/wiki/Creating-a-timeline we'll will start filling this.

**Comment by DigiAngel** [comment]
Beautiful...thank you so much for this...really appreciate it.

**Comment by Onager** [comment]
@aguilajesus who was asking about this

**Comment by joachimmetz** [comment]
@aguilajesus what is the status of this?

**Comment by joachimmetz** [comment]
No update from @aguilajesus and looks like request from original reporter was addressed, closing.
