### ISSUE TITLE
Winprefetch and pyscca 20170105 incompatibility

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1159]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

N/A

**Installation method:**

Travis install, using GIFT

**Description of problem:**

Winprefetch test fails after an unrelated change: https://travis-ci.org/log2timeline/plaso/jobs/197239351

Comparing with the last passing Travis run: https://travis-ci.org/log2timeline/plaso/jobs/195764080

Shows that the pyscca version has changed to 20170105, probably due a new package on GIFT.

I assume that the winprefetch parser needs to be changed to account for the new version, but this could also be a bug in pyscca.

**Debug output/tracebacks:**
```
======================================================================
ERROR: testParse17 (parsers.winprefetch.WinPrefetchParserTest)
Tests the Parse function on a version 17 Prefetch file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/log2timeline/plaso/tests/parsers/winprefetch.py", line 23, in testParse17
    storage_writer = self._ParseFile([u'CMD.EXE-087B4001.pf'], parser_object)
  File "./tests/parsers/test_lib.py", line 177, in _ParseFile
    timezone=timezone)
  File "./tests/parsers/test_lib.py", line 206, in _ParseFileByPathSpec
    parser.Parse(parser_mediator, file_object)
  File "./plaso/parsers/interface.py", line 269, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "./plaso/parsers/winprefetch.py", line 141, in ParseFileObject
    file_reference = file_metrics.file_reference
IOError: pyscca_file_metrics_get_file_reference: unable to retrieve file reference.
```

**Source data:**

Please describe the source that is causing the issue.

**Comment by Onager** [comment]
@joachimmetz Can you take a look at this please?

**Comment by joachimmetz** [comment]
Is a bug in pyscca I'll prep a fix

**Comment by joachimmetz** [comment]
Pushed new release
https://github.com/libyal/libscca/releases/tag/20170205

pending GIFT build
https://launchpad.net/~gift/+archive/ubuntu/testing/+packages?field.name_filter=libscca&field.status_filter=published&field.series_filter=

**Comment by joachimmetz** [comment]
test build green again; closing issue
https://travis-ci.org/log2timeline/plaso/builds/198014036
