### ISSUE TITLE
Bug with markdown format

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#1167]
**Plaso version:**

1.5.2-20170103

**Operating system Plaso is running on:**

Windows 7 64 bit

**Installation method:**

pip

**Description of problem:**

When you change the default text format to markdown for pinfo I discovered an issue when markdown prints rows. *(btw, I suggest adding the ability to select markdown in pinfo)*

```python
File "D:\dev\plaso\tools\pinfo.py", line 589, in PrintStorageInformation
  self._PrintStorageInformation(storage_file)
File "D:\dev\plaso\tools\pinfo.py", line 413, in _PrintStorageInformation
  table_view.Write(self._output_writer)
File "D:\dev\plaso\plaso\cli\views.py", line 212, in Write
  output_writer.Write(u' | '.join(values))
TypeError: sequence item 1: expected string or Unicode, int found
```

A quick fix to this issue is to add the following above https://github.com/log2timeline/plaso/blob/master/plaso/cli/views.py#L212
```python
values = [u'{0!s}'.format(value) for value in values]
```

**Comment by Onager** [comment]
Thanks for the report, I'll fix this up.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/314700043
