### ISSUE TITLE
No raw fields in Kibana (Elasticsearch)

### ISSUE THREAD

**Issue by JohnDoe60** [log2timeline/plaso#1169]
**Plaso version:** 
Plaso 1.5.1

**Operating system Plaso is running on:**
Ubuntu: 14.04 LTS (desktop and server)

**Installation method:**
pip

**Description of problem:**

After processing my image I'm not seeing any raw fields in Kibana. I've already added `--raw_fields`
Elasticsearch 2.3.3 (lucene 5.5.0) / Kibana 4.5.1 build 9892
Updated Elasticsearch and Kibana to latest version (v. 5.2.1)
Still no raw fields in Kibana.

commands used:
```
log2timeline.py plaso.dump win7_image.E01
psort.py -o elastic --raw_fields --index_name case_win7 plaso.dump
```

**Comment by Onager** [comment]
@berggren can you chime in on this one?

@JohnDoe60 Have you been reinserting to the same index, or have you been changing the index or deleting it between attempts?

**Comment by JohnDoe60** [comment]
@Onager 
- Inserting with and without the `--raw_fields` option (new index name)
- Reinserted after deleting existing index (same **and** new index name used)
- Inserting in 3 different Ubuntu systems (server (2) and desktop (1) )
- Processed different E01 images

Tried almost every possible option.

**Comment by Onager** [comment]
Removed from milestone, and we haven't been able to make progress on this one.

**Comment by joachimmetz** [comment]
blocked by #1828

**Comment by joachimmetz** [comment]
@Onager @berggren does this issue require further follow up?

**Comment by berggren** [comment]
Yes, if we want to keep this option (--raw_fields) we need to make this compatible with ES 5.x (and 6.x in the near future). For the record, I think we want to keep the option :)

I'll try to have a look at this asap, as time permits.

**Comment by joachimmetz** [comment]
@Onager @berggren what is the status of this issue?

**Comment by joachimmetz** [comment]
@Onager @berggren what is the status of this issue?

**Comment by joachimmetz** [comment]
Closing this one out, ES is at 7 and Plaso 1.5.1 is many years old.
