### ISSUE TITLE
Loading .Plaso file to ELK Error

### ISSUE THREAD

**Issue by siddiqains** [log2timeline/plaso#1170]
For example 1.4.0 Release

**Operating system Plaso is running on:**
Win7 64bit

I have been trying to load .plaso file to elk engine using psort.py. But i am getting the following Authentication Error. Error: elasticsearch.exceptions.AuthenticationException: TransportError(401, u'')
also I have disabled xpath security

**Source data:**
.Plaso file

**Comment by Onager** [comment]
@siddiqains Per your other issue, please provide the information in the issue template.  

This looks like an issue connecting to elasticsearch, check that you're specifying the username, password, host and port correctly.

**Comment by siddiqains** [comment]
sorry .. very new to this .. Do not how to add username and password to Psort.py command. Alternatively, have tired disabling the ELK login.

**Comment by berggren** [comment]
@siddiqains Do you have Elastic Shield activated? This is the authentication package from Elasticsearch.
If you do, you need to run Plaso from HEAD because the authn feature is not in the latest release.

**Comment by siddiqains** [comment]
@berggren: sorry for being a goon.. but what does "Running from HEAD" mean ?

**Comment by berggren** [comment]
@siddiqains Good question, it means that you need to clone the Plaso repository on your computer and install from there. This is a bit involved though, and it might not be needed. Are you running Elasticsearch with authentication configured?

**Comment by siddiqains** [comment]
Hi Thanks for the answer, I am running Elasticsearch with xpath authentication but its turned off now. Also added Elastic Shield = False. But nothing changed :(

**Comment by joachimmetz** [comment]
@siddiqains your output shows certain dependencies are missing and that plaso and its dependencies might not be properly installed

**Comment by joachimmetz** [comment]
blocked by #1828

**Comment by joachimmetz** [comment]
No update form original reporter closing issue.
