### ISSUE TITLE
Make parser error queue operational

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#119]
Presently, we have a parser error queue, but errors are not written to storage, but are silently discarded. It would be better if we actually wrote these to storage.

**Comment by kiddinn** [comment]
This is closely related to #102 I think I'll close this issue down and add this as a requirement to the storage redesign issue

**Comment by joachimmetz** [comment]
Need to reopen this there is a storage part to this and a non-storage part.

Daniel and me will work on the non-storage part.

**Comment by kiddinn** [comment]
the storage aspect has already been added into #102, I'll then assign this bug to you for non-storage related items.

**Comment by joachimmetz** [comment]
Waiting for #102 

This includes:

* changing parsers to use parser error queue
* having pinfo list the errors

**Comment by joachimmetz** [comment]
Related: https://github.com/log2timeline/plaso/issues/19

**Comment by joachimmetz** [comment]
Is put on hold due to queuing issues: https://github.com/log2timeline/plaso/issues/193

**Comment by joachimmetz** [comment]
Depends on phased processing changes

**Comment by joachimmetz** [comment]
Phased processing will remove the need for a parse error queue. Changes are pending to store the parse errors in the storage making this issue obsolete. Closing issue.
