### ISSUE TITLE
syslog parser stops after empty line

### ISSUE THREAD

**Issue by StefanKelm** [log2timeline/plaso#1190]
**Plaso version:**

1.5.1

**Operating system Plaso is running on:**

Ubuntu 14.04 LTS

**Installation method:**

SIFT forensic workstation

**Description of problem:**

The syslog parser does not parse lines that follow an empty line.

**Source data:**

There's a number of manipulated log files contained within this [forensic challenge](http://www.bnd.bund.de/DE/Karriere/Forensik_Challenge/Forensik_Challenge_node.html). Many of the log files from /var/log/ (syslog, auth.log, ...) start with an empty line which causes the syslog parser to stop parsing the rest of the file.

**Comment by joachimmetz** [comment]
Thx for reporting I'll have a look. We recently made some changes to the syslog parser https://github.com/log2timeline/plaso/issues/1142 I'll double check if empty lines are an issue.

**Comment by Onager** [comment]
This is unlikely to be due to the change, but due to our validation - we aren't checking for "\nMar 29...." we're just checking for "Mar 29". We can tweak the expressions to make this work.

**Comment by Onager** [comment]
That said, I'm not particularly keen on making tweaks to the parser to account for a made up data set. @StefanKelm do you know if these files were deliberately modified, or does this occur in normal operation on some systems?

**Comment by StefanKelm** [comment]
@Onager I don't know for sure but I'm fairly certain that these log files have been made up as part of the forensic challenge. In fact, every single log file within /var/log/ starts with an empty line.

To be honest, I've not seen this in real life but you never know...

**Comment by Onager** [comment]
Closing this out, we won't tweak the Plaso to account for deliberately modified logs in this way.
