### ISSUE TITLE
Update appcompatcache for compatibility with Windows 10 creator update

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1192]
We'll need a test file.

Ref: https://binaryforay.blogspot.ch/2017/03/windows-10-creators-update-vs-shimcache.html

**Comment by joachimmetz** [comment]
https://www.microsoft.com/en-us/windows/upcoming-features

Windows 10 Creators Update: Coming April 11

**Comment by joachimmetz** [comment]
> We'll need a test file.

Used available test data instead
