### ISSUE TITLE
Add task retry

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1200]
Tasks can be abandoned due to worker death, and workers can die from multiple causes that are unrelated to the specific pathspec being processed. We'd like to try failed pathspecs once.

The idea is that if we report an inability to process a pathspec, it's due to an issue with that pathspec, rather than with some other task that happened to bloat memory usage before the subject pathspec was processed by the worker.

**Comment by joachimmetz** [comment]
Mentioned in https://github.com/log2timeline/plaso/issues/1121

**Comment by Onager** [comment]
Implemented in #1272
