### ISSUE TITLE
Timeline and Windows FS (fls vs log2timeline)

### ISSUE THREAD

**Issue by Nicknam3** [log2timeline/plaso#1201]
**Plaso version:**

log2timeline.py --version
psorplaso - log2timeline version 1.5.2_20170403

**Operating system Plaso is running on:**

Ubuntu 14.04

**Description of problem:**

Hi,
I currently have a problem comparing the data generated with log2timeline and psort.py with fls.

It appears that several data in fls (mac time on all the files in the FS) are not present in the result of the psort tool, for example:

```
17465	.ac.	r/r-wx-wx-wx	0	0	135290-128-5	/Users/XXXXX/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.Outlook/7LRYCA7Q/blabla.docx

17465	.acb	r/rrwxrwxrwx	0	0	135298-128-4	/Users/XXXXX/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.Outlook/7LRYCA7Q/blabla (00000002).docx

1755	...b	r/rrwxrwxrwx	0	0	132873-128-5	/Users/XXXXX/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/DS2E3U7K/dnserrordiagoff[1]

304	macb	d/drwxrwxrwx	0	0	137254-144-1	/Users/XXXXX/AppData/Local/Temp/TCD1F33.tmp

280	macb	d/drwxrwxrwx	0	0	137731-144-1	/Users/XXXXX/AppData/Local/Temp/TCD1F34.tmp

272	macb	d/drwxrwxrwx	0	0	137922-144-1	/Users/XXXXX/AppData/Local/Temp/TCD1F35.tmp

217137	macb	r/rrwxrwxrwx	0	0	137924-128-4	/Users/XXXXX/AppData/Local/Temp/TCD1F34.tmp/iso690XXXcal.xsl
```

These data are present in my timeline generated with fls but not with log2timeline and psort.py.

I used these commands to generate my timeline with plaso:
```
sudo log2timeline.py --workers 4 /tmp/case.plaso /media/test/Windows

sudo psort.py -o l2tcsv -w test.csv case.plaso
```

Is it normal or i missed some options ? 

Thanks :)

**Comment by Onager** [comment]
What data do you have for these files? 
What timestamps do you have in Plaso for "/Users/XXXXX/AppData/Local/Temp/TCD1F35.tmp", to pick one of these files at random.

**Comment by Nicknam3** [comment]
Hi Onager,

I've not this file in my psort data:
`
cat all.csv |grep TCD1F35.tmp = nothing
`
all.csv = psort results

`
cat case1.plaso |grep TCD1F35.tmp (i don't think i can grep on this file)
`
`
cat mactime.csv |grep TCD1F35.tmp
`

`
Tue Feb 07 2017 18:55:03,272,macb,d/drwxrwxrwx,0,0,137922-144-1,"/Users/XXXXXX/AppData/Local/Temp/TCD1F35.tmp"
Tue Feb 07 2017 18:55:03,251032,macb,r/rrwxrwxrwx,0,0,137926-128-4,"/Users/XXXXXX/AppData/Local/Temp/TCD1F35.tmp/gosttitle.xsl
`
mactime.csv = fls/mactime results

**Comment by Onager** [comment]
Apologies for delay getting back to you - this slipped my mind.

When log2timeline.py finishes running, are there any error messages about path specifications that can't be processed? I notice you're running this on a mounted file system, so there could be some strangeness there - is the data there if you run this as on the raw image/device?

Try running log2timeline with debugging on, redirect the output to a file, and see what messages there are about these files.

**Comment by joachimmetz** [comment]
No response from OP in more than 3 months closing issue.
