### ISSUE TITLE
Remove and re-factor all _GetYear functions

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#121]
Throughout the code there is a function called:
def _GetYear(self, stat, zone):

This function originally got in to the codebase via syslog.py, one of the oldest parsers. It uses datetime directly, and not correctly and should be removed in all places, and thus eliminate the import of datetime in other files than timelib, which should be the only instance where it is needed (or almost, some test libraries, etc may require it still)

**Comment by joachimmetz** [comment]
Since this is code clean up I'm marking this as enhancement.

**Comment by joachimmetz** [comment]
@Onager I think this was done in the syslog refactor, can you confirm and close this issue.

**Comment by Onager** [comment]
This method is gone, replaced in syslog refactor.
