### ISSUE TITLE
Allow user to set data size limit for cryptographic hash calculation

### ISSUE THREAD

**Issue by jamdunnDFW** [log2timeline/plaso#1211]
Plaso version: Plaso 1.5.1
Operating system Plaso is running on: Ubuntu 14.04
Installation method: installed from [GiFT][https://launchpad.net/~gift]

**Description of problem:**

Not so much a problem, but more of a feature request. Can there be an optional way to set a size threshold for hashing? i.e - don't hash files over 100mb.

**Comment by joachimmetz** [comment]
Currently the hashing and other analyzers are run over the same data. Limiting the file size for hashing when other analyzers are run will still require the entire file to be read.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/326210043/
