### ISSUE TITLE
preg.py failing to run

### ISSUE THREAD

**Issue by Erritmuller** [log2timeline/plaso#1212]
**Plaso version:**

1.5.1

**Operating system Plaso is running on:**

Ubuntu 14.04
**Installation method:**

Fresh install of Ubuntu on a VMWare fusion 8.5.
Followed this guide: https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release

**Description of problem:**

When running preg.py against an image with two partitions, I'll get the error messages below.
The command:
preg.py -i /mnt/hgfs/TMP.nosync/rm/R0.img.dd -c SYSTEM
 

**Debug output/tracebacks:**

Traceback (most recent call last):
  File "/usr/bin/preg.py", line 1716, in <module>
    if not Main():
  File "/usr/bin/preg.py", line 1697, in Main
    if not tool.ParseArguments():
  File "/usr/bin/preg.py", line 731, in ParseArguments
    self.ParseOptions(options)
  File "/usr/bin/preg.py", line 820, in ParseOptions
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 1110, in ScanSource
    partitions=self._partitions)
TypeError: _GetTSKPartitionIdentifiers() got an unexpected keyword argument 'partitions'

**Source data:**

preg.py

**Comment by joachimmetz** [comment]
thx for the report. At first glance this looks like a bug due to internal API changes. I'll have a look when time permits.

**Comment by Erritmuller** [comment]
Thanks. Will try to get back to a working version of 1.3.0 on Ubuntu 14.04. Can you point me to an installation guide. Have tried a few but without any luck.

**Comment by joachimmetz** [comment]
Per: https://github.com/log2timeline/plaso/blob/1.5.1/plaso/cli/storage_media_tool.py#L162

Could you check if you installed plaso correctly. Do you have multiple versions installed on your system?

**Comment by joachimmetz** [comment]
You could try if the following work-around https://codereview.appspot.com/316500043/ works for you.

**Comment by Erritmuller** [comment]
I have applied the patch and get the following output when running preg.py again.

Traceback (most recent call last):
  File "/usr/bin/preg.py", line 1715, in <module>
    if not Main():
  File "/usr/bin/preg.py", line 1696, in Main
    if not tool.ParseArguments():
  File "/usr/bin/preg.py", line 730, in ParseArguments
    self.ParseOptions(options)
  File "/usr/bin/preg.py", line 819, in ParseOptions
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 1110, in ScanSource
    partitions=self._partitions)
  File "/usr/bin/preg.py", line 264, in _GetTSKPartitionIdentifiers
    partition_string = partitions[0]
IndexError: list index out of range


Version 1.5.1 is the only one installed. It's a completely fresh Ubuntu install.

**Comment by Rangie** [comment]
Any solution to this problem? I am experiencing the same, and the patch did not help.

**Comment by joachimmetz** [comment]
I've update the patch.

**Comment by Rangie** [comment]
Thank you for your response . Might be applying the patch wrong. How do I
run the patch? Any directions? When I unzipped the bz2, I ended up with 2
folders a and b, each with tools with the preg.py. how do I reconcile the
3. How do I apply the patch? I am sorry this might be a 101 question.
Apologies.

**Comment by joachimmetz** [comment]
patch is just a text file you can apply with patch, but if you're trying to patch against 1.5.1 there might be differences. Easiest way is to copy the changes in https://codereview.appspot.com/316500043/

**Comment by joachimmetz** [comment]
Closing issue, not additional feedback from OP.
