### ISSUE TITLE
Filters hive by specific registry keys

### ISSUE THREAD

**Issue by bobbypistol** [log2timeline/plaso#1218]
**Description of problem:**

I have a question regarding filtering and i'm not sure if this is possible. If you parse only a registry hive, can you filter by parsing only specified keys? For example only the RunOnce keys?

[https://github.com/ForensicArtifacts/artifacts/blob/master/definitions/windows.yaml#L1334](https://github.com/ForensicArtifacts/artifacts/blob/master/definitions/windows.yaml#L1334)

**Comment by joachimmetz** [comment]
What you could do at the moment is to only enable the corresponding Windows Registry parser plugin.

We are working on adding artifact support to plaso.

**Comment by bobbypistol** [comment]
Can you link the ticket related to this feature?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/155 "add artifact based targeted collection"

**Comment by joachimmetz** [comment]
Closing this issue seeing there is duplication in #155
