### ISSUE TITLE
No such collection filter file

### ISSUE THREAD

**Issue by CGO00** [log2timeline/plaso#1219]
**Plaso version:**
plaso - log2timeline version 1.5.1

**Operating system Plaso is running on:**
Ubuntu 14.04 + SIFT (fresh install)

**Installation method:**
Installation through the SIFT bash installation method 

**Description of problem:**
Hello,

I'm following the (maybe quite old) SANS Tutorial in order to create a timeline. A year or two ago i was able to create it without problem, so i'm wondering if something changed drastically or not.

with root access an after mounting my Encase image, i launched : 
`log2timeline.py -p -r -f winxp -z UTC /mnt/windows_mount /cases/Timeline/timeline.csv`

that return `log2timeline.py: error: unrecognized arguments: -r`

Then without the `- r` : `ERROR: No such collection filter file: winxp.`

`log2timeline.py --info` return : 

```
******************************** Parser Presets ********************************
       Name : Description
--------------------------------------------------------------------------------
    android : android_app_usage,...
      linux : bencode, ...
     macosx : sqlite/appusage, a...
macosx_slow : macosx, syslog
    webhist : binary_cookies, ...
       win7 : recycle_bin, custom_destinations, esedb/esedb_file_history,
              olecf/olecf_automatic_destinations, win_gen, winevtx
  win7_slow : hachoir, win7
    win_gen : bencode, esedb, ...
      winxp : recycle_bin_info2, win_gen, winevt
 winxp_slow : hachoir, winxp
```

Any idea ? Any other uptodate tutorial ?

Many thanks

**Comment by Onager** [comment]
I don't have the SANS tutorial (which one?) in front of me for a comparison, but `log2timeline.py -h` will show you all the options and their meaning. `--info` is for details about what parsers are enabled, etc.

Based on your command line, I think you want to do:
`log2timeline.py -p -f /usr/share/plaso/filter_windows.txt -z UTC /mnt/windows_mount /cases/Timeline/timeline.plaso`
then
`psort.py -w /cases/Timeline/timeline.csv /cases/Timeline/timeline.plaso`

**Comment by CGO00** [comment]
Thank you, it really helped !

I never found any word about : 

> /usr/share/plaso/filter_windows.txt

But i think that the correct syntax should be (.plaso first then partition to analyze) : 

`log2timeline.py -p -f /usr/share/plaso/filter_windows.txt -z UTC /cases/Timeline/timeline.plaso /mnt/windows_mount`

For the psort part, i prefer add a `-o l2tcsv` option :)
`psort.py -o l2tcsv -w /cases/Timeline/timeline.csv /cases/Timeline/timeline.plaso`

I think it may help if any Plaso export is able to update this : https://github.com/log2timeline/plaso/wiki/Creating-a-timeline because it's just empty :)
