### ISSUE TITLE
Feature request: configurable tag label for nsrlsvr analysis plugin

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1220]
Currently, the nsrlsvr analysis plugin assigns the label [nsrl_present](https://github.com/log2timeline/plaso/blob/1.5.1/plaso/analysis/nsrlsvr.py#L182) tag to events with a matching hash. Using a configurable label to tag hits with would enable the use of several lists (both blacklists and whitelists). This would require the analysis plugin to be run multiple times, of course. Another prerequisite would be a fix of #1037.

**Comment by Onager** [comment]
The label name flag is now implemented.

**Comment by Onager** [comment]
I'm going to close this out, even though #1037 is still open. Otherwise we're just tracking the same issue twice.
