### ISSUE TITLE
Data limits?

### ISSUE THREAD

**Issue by zappeee** [log2timeline/plaso#1223]
**Plaso version:**

1.5.1

**Operating system Plaso is running on:**

Ubuntu 14.04

**Installation method:**

Via SIFT

**Description of problem:**

Are there any limits on how much data plaso can handle?
I use analyzemft, then l2t and then psort.
One of the body files were 240mb
The dump file was 1.4gb
And the CSV output was 4.2gb.
Though it didn't contain all the information.

**Debug output/tracebacks:**

-

**Source data:**

All the collected data were about 2,7GB. 
One of the mft bins were 2gb.

**Comment by joachimmetz** [comment]
@zappeee I'm not sure what you are asking

> Are there any limits on how much data plaso can handle?

yes, actual numbers depends on many factors

**Comment by zappeee** [comment]
My question is really how I can find out what factor is limiting me from getting all the output.
I have a similar issue now with a collection of files.

**Comment by joachimmetz** [comment]
Is 4G the limit you are hitting?

**Comment by joachimmetz** [comment]
> My question is really how I can find out what factor is limiting me from getting all the output.

there is no straight forward answer, this highly depends on your configuration
with the necessary details I can only speculate very broadly

**Comment by zappeee** [comment]
> Is 4G the limit you are hitting?

Is there a 4G limit on CSV outputs?

**Comment by joachimmetz** [comment]
depends if you're writing to specific file systems then yes.

**Comment by zappeee** [comment]
I'm using Ubuntu 14.04 64bit with ext4

**Comment by joachimmetz** [comment]
> I'm using Ubuntu 14.04 64bit with ext4

If this is file system where the data is stored, the FS should not be a a limiting factor

can you answer the follow questions (please not with a counter question)

Is 4G the limit you are hitting? or do you see different sizes? If so what are these?
what output are you missing? anything that hints to a commonality?

**Comment by zappeee** [comment]
As I stated in the first comment the output was 4.2GB.
The hints are that the last message in the file is at 2016, where it should include all 2017 also.

**Comment by joachimmetz** [comment]
> As I stated in the first comment the output was 4.2GB.

yes but you later added "I have a similar issue now with a collection of files." what about those?

could you provide me as much detail as possible, it is impossible for me to help you with the necessary details, I have a hard time figuring out what you are telling us.

> The hints are that the last message in the file is at 2016, where it should include all 2017 also.

This is what I currently make of your description

You ran analyzeMFT, have it generate a [SleuthKit bodyfile](https://wiki.sleuthkit.org/index.php?title=Body_file). You ran log2timeline.py on that body file only and then psort.py on the resulting plaso file. You are missing the 2017 dates in the output of psort.

Correct?

**Comment by zappeee** [comment]
> yes but you later added "I have a similar issue now with a collection of files." what about those?
I think that was a mistake on my side. At the moment I only have issue with one set of files.

> could you provide me as much detail as possible, it is impossible for me to help you without the necessary details, I have a hard time figuring out what you are telling us.
Sure, is there any specific info you need?

> You ran analyzeMFT, have it generate a SleuthKit bodyfile. You ran log2timeline.py on that body file only and then psort.py on the resulting plaso file. You are missing the 2017 dates in the output of psort.
> Correct?

Almost. I run analyzeMFT on two mft-bins and then log2timeline on those body files.
Then another log2timeline on multiple other collected files.
Then psort on that dump file.
Then I was missing content from 2017.

**Comment by joachimmetz** [comment]
Does log2timeline.py indicate that there were errors during extraction? If you can you provide me more details about them (you can use pinfo.py on the plaso storage file to list them).

**Comment by joachimmetz** [comment]
No update from OP closing issue.
