### ISSUE TITLE
UnboundLocalError in psort

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#1234]
**Plaso version:**

20170515

**Operating system Plaso is running on:**

Windows 7 64bit

**Installation method:**

pip

**Description of problem:**

Getting an UnboundLocalError due to `used_memory` variable not being set for both if statement conditions before https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/psort.py#L230

**Debug output/tracebacks:**

```python
File "D:\dev\plaso\plaso\multi_processing\psort.py", line 230, in _CheckStatusAanalysisProcess
  self._UpdateProcessingStatus(pid, process_status, used_memory)
UnboundLocalError: local variable 'used_memory' referenced before assignment
```

**Comment by joachimmetz** [comment]
Thx for the report I'll fix after CLI options clean up https://codereview.appspot.com/326740043/

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/328930043/
