### ISSUE TITLE
Create a $MFT metadata file parser

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#124]
Need to have an independent MFT parser that can be used to parse extracted $MFT file.

Several options available, including using analyzeMFT as a library and import it.

**Comment by joachimmetz** [comment]
Patience.

**Comment by SANS-SIFT** [comment]
Yes -- the main idea here is that Id like to be able to remotely mount a server and with the utilization of the -fi filelist and --parsers option only pull data from the MFT, EVTX logs, and the IIS logfiles.  Those three basically make easy work when someone does something strange on a system especially a web server.  But without the MFT parsing it is still useful but really trying to pull this data in minutes via a remote agent connection.  Thanks for looking into this.  Should I get David Kovar involved to see if he can help rewriting analyzeMFT.py to function as a plaso plugin?

**Comment by joachimmetz** [comment]
I can ping David if I think that's the effective way to proceed. Early experiments with MTF parsing code have indicated Python might not be the most effective option to parse large MFT "files".

**Comment by dnides** [comment]
Just an FYI last year Kovar made some changes so mftanalyzer could be imported as a lib. The intent of this was so we could leverage it as a Plaso parser. That said I recall some good feedback from Kiddi why this wouldn't be the preferred method to proceed. 

.. Maybe we need to wait till you complete a new lib :)

**Comment by SANS-SIFT** [comment]
any MFT parser -- even an imperfect one would be very useful for targeted triage extraction and would save time.  A good plan is better in most cases than a perfect one.  If it is close, then it would be very useful to have a parser in there for now until a more efficient one can be finalized.
It would alos the "MFT" to be called during a filter file based extraction.
--Rob

**Comment by joachimmetz** [comment]
Not sure what your points you are trying to make? You can already script analyzeMFT and plaso together and get what you want. You can do that in a couple of lines of shell script.

We have different priorities for plaso at the moment, so you'll have to be patient for us to implement or write a few lines of shell script or Python yourself in the mean time.

**Comment by SANS-SIFT** [comment]
Yes -- this is easy to script -- just will lead to the follow on question of "Why wouldn't they add it?"  To the average individual seeing the project for the first time ever it will look like duct tape solution and not polish -- not something they would want to run in their own organization.   What we are trying to show is a filter file targeting just key files to produce a timeline in mere minutes.  Without the MFT a part of that we do have to script it:

0.  Run log2timeline with filter file against remote system via F-Response enterprise /dev/sdc
1.  Mount remote system device /dev/sdc2 or icat out MFT (multiple ways here)
2.  run analyzeMFT.py against $MFT
3.  Run log2timeline.py against output etc to include in database

Yes this is easy -- but for someone who is new this is annoying and it gives the appearance that it is not slick.  Again Im trying to not only solve problems but start to increase your user base.  Im sure there are other ways to accomplish this -- but hoping you might increase the priority just a tad.  Not the highest thing Im sure -- but just "up there" if you would consider it.

--Rob

**Comment by joachimmetz** [comment]
Understood alas time is limited and keeping on slapping on functionality will bite us in the sort term future.

**Comment by joachimmetz** [comment]
Deprecating feature request in favor of: https://github.com/log2timeline/plaso/issues/316
