### ISSUE TITLE
End to end test script needs to account for spaces in windows paths

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1247]
When the path to python.exe has a space in it:

'C:\Program Files\Python27\python.exe' .\tests\end-to-end.py
python.exe : [INFO] Running: C:\Program Files\Python27\python.exe 
C:\jenkins\workspace\student_pc1_windows2012\plaso\tools\log2timeline.py --status-view=none  
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1.plaso test_data/System.evtx > 
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1-log2timeline.out 2> 
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1-log2timeline.err
At line:1 char:1
+ & 'C:\Program Files\Python27\python.exe' .\tests\end-to-end.py
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ([INFO] Running:...og2timeline.err:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[ERROR] Running: "C:\Program Files\Python27\python.exe 
C:\jenkins\workspace\student_pc1_windows2012\plaso\tools\log2timeline.py --status-view=none  
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1.plaso test_data/System.evtx > 
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1-log2timeline.out 2> 
c:\users\plaso_~1\appdata\local\temp\2\tmpen7z0p\extract_and_output1-log2timeline.err" failed.*

....

the .err files all contain:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rgayon** [comment]
in `def _RunCommand(self, command):`  end-to-end.py calls `subprocess.call()` with `shell=True`.
Turning it to False on windows seems to do the trick ?

**Comment by Onager** [comment]
Hey @rgayon - was this fixed in https://github.com/log2timeline/plaso/commit/cb2b206f2ebfd5e30089b7133249792426c3838e ?

**Comment by rgayon** [comment]
Fixed in cb2b206
