### ISSUE TITLE
Parser selection behavior is not adequately defined

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#125]
Parser selection is only based on the parser name, if you have a plugin, like "firefox_history" the actual parser "sqlite" does not get chosen as part of the included parsers.

**Comment by joachimmetz** [comment]
Please add a tests to prevent regression.

**Comment by joachimmetz** [comment]
Also please define the desired behavior regarding excludes and includes.

**Comment by kiddinn** [comment]
code review: https://codereview.appspot.com/203470043/

**Comment by kiddinn** [comment]
This has been fixed, but needs to be backported to the last release (at least in the SIFT package)

**Comment by kiddinn** [comment]
backport has been issued and confirmed that it is working, safe to close this bug.

**Comment by joachimmetz** [comment]
I'm seeing the following behavior:
```
log2timeline.py plaso.db NTUSER.DAT
```
Events are parsed

```
log2timeline.py --parsers bagmru plaso.db NTUSER.DAT
```
No events are parsed

**Comment by kiddinn** [comment]
well, the reason for that is the fact that there is no plugin named bagmru... it's called winreg_bagmru, and if you call it like:

    log2timeline.py --parsers winreg_bagmru plaso.db NTUSER.DAT

it parses it properly..... 

the question is whether we should get rid of the winreg_ prefix now, since that should not be necessary anymore... the same goes to other prefixes of plugin names, such as:
 + winreg_
 + olecf_
 + plist_
 + bencode_

There are other prefixes that I think still should be there, such as:
 + chrome_
 + firefox_
 + android_

So either make the documentation more specific, eg; not use bagmru, but winreg_bagmru or get rid of the prefix.

**Comment by joachimmetz** [comment]
I opt to drop it where it does not add value and keep it where it does. IMO with chrome_X, etc. it does since it depicts the application, with winreg_ it does not since it depicts a subsystem. However the parser/plugin managers have to be sure there are no name conflicts.

**Comment by kiddinn** [comment]
First CL for changing this behavior: http://codereview.appspot.com/232210043
(removes the winreg_ prefix for registry plugins and fixes some issues with running preg)

**Comment by kiddinn** [comment]
I think we should still stick with the olecf_ prepend, since those plugins are still quite general. 

Removed plist_ and think that should conclude this issue (once both CL's are checked in).

CL: http://codereview.appspot.com/232210044

**Comment by kiddinn** [comment]
Fixed the two remaining open issues. Closing this issue.
