### ISSUE TITLE
Parser Chain building is broken

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#127]
Running against tdungan image and then looking at the results I see parser chains like:

        Counter: sqlite/zeitgeist/mackeeper_cache/skype/chrome_history/appusage/android_sms/ls_quarantine/chrome_extension_activity/firefox_downloads/firefox_cookies/google_drive/firefox_history = 874

sqlite/zeitgeist/mackeeper_cache/skype/chrome_history/appusage/android_sms/ls_quarantine/chrome_extension_activity/firefox_downloads/firefox_cookies/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/google_analytics_utmb/google_analytics_utmz/google_analytics_utma/goo:

**Comment by Onager** [comment]
I noticed this yesterday too, and took a very quick look at it. It appears to be a bug BasePluginsParser.

**Comment by kiddinn** [comment]
It seems as if a plugin is being evaluated it adds itself to the chain, but
it's not popped/removed if it is invalid (eg not the correct plugin)

**Comment by Onager** [comment]
Fixed in 31afcc6
