### ISSUE TITLE
StatusView has no member _view_format_type

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1278]
StatusView has no member _view_format_type:
https://github.com/log2timeline/plaso/blob/790d5e8706a0658f102744ac34921a7ce0560f28/plaso/cli/status_view_tool.py#L195

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/327950044

**Comment by joachimmetz** [comment]
No need for `_PrintAnalysisReportsDetails` to be defined in `StatusView`
