### ISSUE TITLE
Improve Python3 bdist_rpm support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1299]
on HEAD when I run: `python3 ./setup.py bdist_rpm`

```
RPM build errors:
    File not found: Projects/plasobuild/bdist.linux-x86_64/rpm/BUILDROOT/plaso-20170710-1.x86_64/usr/lib/python3.5/site-packages/plaso/output/__pycache__/xlsx.cpython-35.pyc
    File not found: Projects/plaso/build/bdist.linux-x86_64/rpm/BUILDROOT/plaso-20170710-1.x86_64/usr/lib/python3.5/site-packages/plaso/output/__pycache__/xlsx.cpython-35.opt-1.pyc
error: command 'rpmbuild' failed with exit status 1
```

**Comment by Onager** [comment]
@joachimmetz I think we need this before the release - what do you think?

**Comment by joachimmetz** [comment]
I'll have a look when time permits

**Comment by joachimmetz** [comment]
`setup.py bdist_rpm` includes `__pycache__` files by default to fix this we'll need to tweak the bdist_rpm target in setup.py some more

**Comment by joachimmetz** [comment]
Added a fix in https://codereview.appspot.com/322370043 a more elegant (future) solution might be generating an rpm spec file and have setup.py read this. Added a reminder to https://github.com/log2timeline/l2tdevtools/issues/157
