### ISSUE TITLE
ERROR: Missing required artifact definition: WindowsCurrentVersion

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1310]
**Plaso version:**

20170715

**Operating system Plaso is running on:**

Ubuntu 16.04.2

**Installation method:**

GIFT/PPA, Github clone, python setup.
**Description of problem:**

Running "log2timeline --parsers winreg <plasofile> <directory mount from Raw>"
created the "ERROR: Missing required artifact definition: WindowsCurrentVersion"
Log2timeline did not run.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/1309

**Comment by joachimmetz** [comment]
Thx, for reporting, this is a problem with the development version HEAD not 20170715

**Comment by joachimmetz** [comment]
Try if updating artifacts works for you, as with the end-to-end tests or point log2timeline to the artifact definitions `--artifact_definitions` manually
