### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1323]
- [x] Create a logger per sub module
  - logging still used in plaso/filters
- [x] ~~what about logging used in lib?~~
  - no longer applicable 
- [x] ~~Merge changes/ideas for logging changes (from https://codereview.appspot.com/291530043/)~~
  - most important warnings now should be stored in the Plaso storage file
- [x] ~~find a solution for the multi processing logger issue https://github.com/log2timeline/plaso/issues/460~~
  - every worker has its own log now
- [x] replace logging by processing warning

**Comment by Onager** [comment]
Should look at restruturing logging in general, at present, we stomp over any other code that loads plaso as a library.
