### ISSUE TITLE
ERROR : Unsupported option : preferred_year integer type required

### ISSUE THREAD

**Issue by madsumm** [log2timeline/plaso#1329]
**Plaso version:**
Plaso 20170731

**Operating system Plaso is running on:**

Linux Ubuntu 16.04.2
**Installation method:**

Git pull, manual GIFT install dependencies.

**Description of problem:**

Executed "--preferred_year 2017", returned error as in the subject field.

**Comment by joachimmetz** [comment]
thx for the report, I'll have a look as soon as time permits

**Comment by joachimmetz** [comment]
Was able to reproduce this
