### ISSUE TITLE
Queued tasks not correctly timed out

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1355]
In the task manager, HasPendingTasks checks for TasksPendingRetry https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/task_manager.py#L297 before attempting to time out tasks that are queued https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/task_manager.py#L303.

HasTasksPendingRetry checks for abandoned tasks that haven't been retried https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/task_manager.py#L333 while GetRetryTask (correctly) checks for abandoned tasks that haven't been retried and are not themselves retries of an abandoned task https://github.com/log2timeline/plaso/blob/master/plaso/multi_processing/task_manager.py#L347

This leads to tasks that have been queued, picked up by a worker, and then abandoned never being timed out, while the engine continues to be told by the manager that there are still tasks being processed by workers.

**Comment by joachimmetz** [comment]
Let's also check if recent changes fixed https://github.com/log2timeline/plaso/issues/1350 or more work is needed for that
