### ISSUE TITLE
image_export preserve date and time exported files

### ISSUE THREAD

**Issue by steveo-ct** [log2timeline/plaso#1361]
**Plaso version:**

For example 1.5.1 Release

**Operating system Plaso is running on:**

windows server 2016

**Installation method:**

downloaded windows binaries from github

**Description of problem:**

When using image_export.exe, files are exported to the filesystem with the date and time of the export, not with the date and time contained within the image file.

Can an enhancement be made to export the file with the date and time as contained in the image file?

**Source data:**

encase image file e01 format, mounted as a physical drive. image_export is reading from the mounted drive.

**Comment by joachimmetz** [comment]
> Can an enhancement be made to export the file with the date and time as contained in the image file?

This will be highly operating and file system specific.

**Comment by jalwood** [comment]
I was looking at the image_export.py file and I see how image_export is making the copy.  Would shutil.copy2 work as a replacement?  There is some metadata it doesn't get and the python standard library docs notes what it doesn't get, but if all we're worried about is the timestamps this seems like it solves the problem.

**Comment by joachimmetz** [comment]
@jalwood thx for the pointer, but the thing is that the metadata comes from the image not from another file.

**Comment by joachimmetz** [comment]
I fail to see the use case here, if this is to preserve the timestamps IMHO exporting to a writable file system is not the best option.

**Comment by joachimmetz** [comment]
I'll close this for now. Feel free to comment or reopen if you can explain the use case to me.
