### ISSUE TITLE
Unable to find tagging file

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1364]
version: 20170819

`./config/tests/generate_test_files.sh`

```
No tag definition file specified, and plaso was not able to autoselect a tagging file. As no definitions were specified, no events will be tagged.
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/324270043

**Comment by ktwombley** [comment]
There must have been a regression.

I am getting the same issue again in 20171118. I checked my copy of tool_options.py against  https://codereview.appspot.com/324270043 and the changes must have been reverted.
