### ISSUE TITLE
Excessive event output due to duplicate event reads

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1383]
Psort is currently stalling, and outputting many duplicate events. From a `psort + | uniq -c | sort -nr`:
```
   1033 12/24/2003,00:47:46,UTC,M..B,FILE,NTFS Content Modification Time,Content Modification Time; Creation Time,-,-,/home/onager/PycharmProjects/onager_plaso/test_data/MFT 934...,OS:/usr/loc
   1033 12/24/2003,00:47:46,UTC,M..B,FILE,NTFS Content Modification Time,Content Modification Time; Creation Time,-,-,/home/onager/PycharmProjects/onager_plaso/test_data/MFT 934...,OS:/usr/loc
   1033 12/24/2003,00:47:46,UTC,M..B,FILE,NTFS Content Modification Time,Content Modification Time; Creation Time,-,-,/home/onager/PycharmProjects/onager_plaso/test_data/MFT 934...,OS:/usr/loc
```
So we're outputting some lines up to 1032 times more than we should be...

**Comment by Onager** [comment]
The _event_heap in zip_storage_file contains the same event multiple times. Their _identifier._identifer values are different, but stream_number and entry_index are identical.

**Comment by Onager** [comment]
Additionally, the events are ordered properly. From `cut -f1 -d"," ~/test/dynamic.csv | uniq: 
```
1970-01-04T21:39:30.926000+00:00
1970-09-28T06:00:00+00:00
1984-01-11T08:00:00+00:00
1992-06-19T22:22:17+00:00
1995-11-22T18:25:07+00:00
1970-01-01T00:00:00+00:00
1970-01-01T00:00:00.116231+00:00
```

**Comment by Onager** [comment]
I suspect this is due to the new temporary file stream extraction. If we fill up the cached number of streams, when we reopen a stream we've expired from the cache, we start again at offset 0 in the stream, which is an issue.

**Comment by Onager** [comment]
This seems to have been introduced in https://github.com/log2timeline/plaso/commit/83fd8857116952eaf2c9a9c2f0dac8e1b3ba22ee as this is when the end2end tests started timing out.

**Comment by joachimmetz** [comment]
@Onager could you give the changes in https://codereview.appspot.com/324290043 a try, see if that solves the issue

**Comment by Onager** [comment]
Tried that fix, doesn't resolve the issue.

**Comment by Onager** [comment]
Starting to wonder if there's an issue with writing as well. From some debugging:
```
-11644473599869962 from stream 56 index 0
-11644473599869494 from stream 56 index 1
-11644473599869962 from stream 56 index 2
-11644473599869494 from stream 56 index 3

-11644473599869962 from stream 90 index 0
-11644473599869494 from stream 90 index 1
-11644473599869962 from stream 90 index 2
```
I believe the zip store expects that the events in each stream are ordered when reading.

**Comment by Onager** [comment]
Look directly at the stream, it seems like it's being read incorrectly:
``
timestamp": -11644473599869962
timestamp": -11644473599869494
timestamp": -11644473599758531
```
These are the timestamps from stream 56 in the test storage file, so it looks like the streams are still being re-read incorrectly. Perhaps the offsets are wrong? entry_index is increasing as expected.

**Comment by Onager** [comment]
Missed an underscore in "_stream_offset" during another fix =(

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/17e8ac3fc1ecfe3c1987f9aae09f17dd10598695
