### ISSUE TITLE
Need some help here 

### ISSUE THREAD

**Issue by MarkDubs123** [log2timeline/plaso#1396]
I keep getting this error. 

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 21, in <module>
    from plaso.cli import extraction_tool
  File "/Library/Python/2.7/site-packages/plaso/cli/extraction_tool.py", line 9, in <module>
    from plaso.engine import engine
  File "/Library/Python/2.7/site-packages/plaso/engine/engine.py", line 14, in <module>
    from plaso.preprocessors import interface as preprocess_interface
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/__init__.py", line 5, in <module>
    from plaso.preprocessors import macosx
  File "/Library/Python/2.7/site-packages/plaso/preprocessors/macosx.py", line 11, in <module>
    from plaso.parsers.plist_plugins import interface as plist_interface
  File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 33, in <module>
    from plaso.parsers import pe
  File "/Library/Python/2.7/site-packages/plaso/parsers/pe.py", line 3, in <module>
    import pefile
ImportError: No module named pefile

**Comment by Onager** [comment]
It looks like the pefile library isn't installed. How did you install Plaso?

**Comment by MarkDubs123** [comment]
downloaded the file from this website and then installed via command line.

**Comment by Onager** [comment]
Which file? What OS are you running on?

By the way, we have a new issue template that asks for exactly this information, which would have made the debugging here go a lot faster. Please use it if you have further issues.

**Comment by MarkDubs123** [comment]
Alright, My bad! Mac version 10.12.6 and I downloaded plaso-1.5.1-macosx-10.12.dmg

**Comment by Onager** [comment]
OK, installing this:
https://github.com/log2timeline/l2tbinaries/blob/master/macos/pefile-2017.8.1.dmg
should
fix it. It looks like we already had a report of this in
https://github.com/log2timeline/plaso/issues/1147

I guess we didn't get around to repackaging this, but I'll double check.

**Comment by MarkDubs123** [comment]
Alright I did that it works but now I am getting a error like this:: 

WARNING: unable to determine location of data files.
Checking availability and versions of dependencies.
[FAILURE]	missing: IPython.


I have install ipython not sure why it keeps saying its missing

**Comment by joachimmetz** [comment]
> I have install ipython not sure why it keeps saying its missing

how did you install Ipython?

**Comment by MarkDubs123** [comment]
Via command line

On Sep 7, 2017 2:42 PM, "Joachim Metz" <notifications@github.com> wrote:

I have install ipython not sure why it keeps saying its missing

how did you install Ipython?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/log2timeline/plaso/issues/1396#issuecomment-327888538>,
or mute the thread

**Comment by MarkDubs123** [comment]
Via command line

**Comment by joachimmetz** [comment]
and what was this command line?

**Comment by MarkDubs123** [comment]
Yes

**Comment by MarkDubs123** [comment]
Terminal on Mac      Mac Version 10.12.6

**Comment by Onager** [comment]
Joachim means "what command did you run to install iPython".

**Comment by MarkDubs123** [comment]
pip install ipython

**Comment by joachimmetz** [comment]
so you likely installed ipython in a different location then your version of Python support. Try the ipython package provided by https://github.com/log2timeline/l2tbinaries/tree/master/macos

**Comment by Onager** [comment]
No response from OP for a few weeks, and we're about to do a new release. Closing.
