### ISSUE TITLE
parser mediator does not set event.inode value

### ISSUE THREAD

**Issue by jtsylve** [log2timeline/plaso#1399]
**Plaso version:**

20170819

Full package list:
```
artifacts (20170818)
bencode.py (1.2.0)
binplist (0.1.4)
certifi (2017.7.27.1)
chardet (3.0.4)
construct (2.5.3)
dfdatetime (20170719)
dfvfs (20170723)
dfwinreg (20170706)
dpkt (1.9.1)
efilter (1-1.5)
future (0.16.0)
hachoir-core (1.3.3)
hachoir-metadata (1.3.3)
hachoir-parser (1.3.4)
idna (2.6)
libbde-python (20170902)
libesedb-python (20170121)
libevt-python (20170120)
libevtx-python (20170122)
libewf-python (20170703)
libfsntfs-python (20170315)
libfvde-python (20160801)
libfwnt-python (20170115)
libfwsi-python (20170117)
liblnk-python (20160420)
libmsiecf-python (20170116)
libolecf-python (20170825)
libqcow-python (20170222)
libregf-python (20170130)
libscca-python (20170205)
libsigscan-python (20170124)
libsmdev-python (20170225)
libsmraw-python (20170803)
libvhdi-python (20170223)
libvmdk-python (20170226)
libvshadow-python (20170902)
libvslvm-python (20160110)
pefile (2017.9.3)
pip (9.0.1)
plaso (20170819)
psutil (5.3.0)
pycrypto (2.6.1)
pyliblzma (0.5.3)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytsk3 (20170802)
pytz (2017.2)
PyYAML (3.12)
pyzmq (16.0.2)
requests (2.18.4)
setuptools (36.4.0)
six (1.10.0)
urllib3 (1.22)
wheel (0.29.0)
XlsxWriter (0.9.9)
yara-python (3.6.3)
```

**Operating system Plaso is running on:**

MacOS 10.12.6

**Installation method:**

[virtualenv](https://github.com/log2timeline/plaso/wiki/Running-plaso-in-virtualenv)

**Description of problem:**

The fs:stat plugin always shows an `inode` number of 0.  

**Source data:**

I've tested on the small recovery partition of the NIST CFREDS PC image (E01) from here https://www.cfreds.nist.gov/data_leakage_case/data-leakage-case.html

**Comment by joachimmetz** [comment]
This is correct: https://github.com/log2timeline/plaso/issues/316

We are planning to add support for file name hints, seeing that MFT entries can have multiple path associated to them.

**Comment by joachimmetz** [comment]
Thx for the report we'll have a look as soon at time permits

**Comment by joachimmetz** [comment]
Note to self the "inode" is set by the mediator in ProcessEvent https://github.com/log2timeline/plaso/blob/452a6ea1f60a65d433be8e76e104d0ade4157691/plaso/parsers/mediator.py#L371 based on the dfvfs.StatObject

**Comment by joachimmetz** [comment]
Found the culprit, this is a bug in mediator checking for the existence of event.inode instead of the value is None. Added necessary test coverage.

https://codereview.appspot.com/335120043/

**Comment by joachimmetz** [comment]
Changes committed. Reopen if issue still persist.
