### ISSUE TITLE
Floating point exception in libtsk 

### ISSUE THREAD

**Issue by rickdeckardt** [log2timeline/plaso#1404]
**Plaso version:**
latest snapshot down to 1.4.1

**Operating system Plaso is running on:**
Kali Linux, latest updates

**Installation method:**
Binary & source from github

**Description of problem:**

**Debug output/tracebacks:**
# ./run_tests.py 
Checking availability and versions of dependencies.
[OK]		Crypto version: 2.6.1
[OK]		artifacts version: 20170808
[OK]		bencode
[OK]		binplist version: 0.1.5
[OK]		certifi version: 2016.09.26
[OK]		chardet version: 3.0.4
[OK]		construct version: 2.5.2
[OK]		dateutil version: 2.6.1
[OK]		dfdatetime version: 20170719
[OK]		dfvfs version: 20170723
[OK]		dfwinreg version: 20170706
[OK]		dpkt version: 1.8
[OK]		efilter
[OK]		future version: 0.16.0
[OPTIONAL]	hachoir_core version: 1.3.3.
[OPTIONAL]	hachoir_metadata version: 1.3.3.
[OPTIONAL]	hachoir_parser version: 1.3.4.
[OK]		idna
[OPTIONAL]	missing: lzma.
[OK]		pefile version: 2017.9.3
[OK]		psutil version: 5.0.1
[OK]		pybde version: 20170902
[OK]		pyesedb version: 20170121
[OK]		pyevt version: 20170120
[OK]		pyevtx version: 20170122
[OK]		pyewf version: 20140608
[OK]		pyfsntfs version: 20170315
[OK]		pyfvde version: 20160918
[OK]		pyfwnt version: 20170115
[OK]		pyfwsi version: 20170117
[OK]		pylnk version: 20170111
[OK]		pymsiecf version: 20170116
[OK]		pyolecf version: 20170825
[OK]		pyparsing version: 2.1.10
[OK]		pyqcow version: 20170222
[OK]		pyregf version: 20170130
[OK]		pyscca version: 20170205
[OK]		pysigscan version: 20170124
[OK]		pysmdev version: 20170225
[OK]		pysmraw version: 20170803
[OK]		pytsk3 version: 20170802
[OK]		pytz
[OK]		pyvhdi version: 20170223
[OK]		pyvmdk version: 20170226
[OK]		pyvshadow version: 20170902
[OK]		pyvslvm version: 20160110
[OK]		requests version: 2.18.1
[OK]		six version: 1.10.0
[OK]		pysqlite2.dbapi2 version: 3.20.1
[OK]		urllib3 version: 1.21.1
[OK]		xlsxwriter version: 0.9.6
[OK]		yaml version: 3.12
[OK]		yara version: 3.6.2
[OK]		zmq version: 16.0.2

Checking availability and versions of test dependencies.
[OK]		mock version: 2.0.0

testGetAttributeNames (containers.storage_media.MountPointTest)
Tests the GetAttributeNames function. ... ok
testCopyToDict (containers.artifacts.EnvironmentVariableArtifactTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.artifacts.HostnameArtifactTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.artifacts.SystemConfigurationArtifactTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.artifacts.UserAccountArtifactTest)
Tests the CopyToDict function. ... ok
testGetAttributeNames (containers.errors.ExtractionErrorTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.windows_events.WindowsDistributedLinkTrackingEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.windows_events.WindowsRegistryInstallationEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.windows_events.WindowsRegistryListEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.windows_events.WindowsRegistryServiceEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.windows_events.WindowsVolumeEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.events.EventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.events.EventObjectTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.events.EventTagTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.analyzer_result.AnalyzerResultTest)
Tests the GetAttributeNames function. ... ok
testCopyToDict (containers.tasks.TaskCompletionTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.tasks.TaskStartTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.tasks.TaskTest)
Tests the CopyToDict function. ... ok
testCreateRetry (containers.tasks.TaskTest)
Tests the CreateRetry function. ... ok
testGetAttributeNames (containers.time_events.DateTimeValuesEventTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.time_events.TimestampEventTest)
Tests the GetAttributeNames function. ... ok
testCopyToDict (containers.sessions.SessionCompletionTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.sessions.SessionStartTest)
Tests the CopyToDict function. ... ok
testCopyToDict (containers.sessions.SessionTest)
Tests the CopyToDict function. ... ok
testGetAttributeNames (containers.shell_item_events.ShellItemFileEntryEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.reports.AnalysisReportTest)
Tests the GetAttributeNames function. ... ok
testAttributeContainerRegistration (containers.manager.AttributeContainersManagerTest)
Tests the Register and DeregisterAttributeContainer functions. ... ok
testGetAttributeNames (containers.plist_event.PlistTimeEventDataTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.event_sources.EventSourceTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeNames (containers.event_sources.FileEntryEventSourceTest)
Tests the GetAttributeNames function. ... ok
testCopyToString (containers.interface.AttributeContainerIdentifierTest)
Tests the CopyToString function. ... ok
testCopyToDict (containers.interface.AttributeContainerTest)
Tests the CopyToDict function. ... ok
testGetAttributeNames (containers.interface.AttributeContainerTest)
Tests the GetAttributeNames function. ... ok
testGetAttributeValuesString (containers.interface.AttributeContainerTest)
Tests the GetAttributeValuesString function. ... ok
testGetAttributes (containers.interface.AttributeContainerTest)
Tests the GetAttributes function. ... ok
testGetIdentifier (containers.interface.AttributeContainerTest)
Tests the GetIdentifier function. ... ok
testGetSessionIdentifier (containers.interface.AttributeContainerTest)
Tests the GetSessionIdentifier function. ... ok
testSetIdentifier (containers.interface.AttributeContainerTest)
Tests the SetIdentifier function. ... ok
testSetSessionIdentifier (containers.interface.AttributeContainerTest)
Tests the SetSessionIdentifier function. ... ok
testAddRow (cli.views.BaseTableViewTests)
Tests the AddRow function. ... ok
testWrite (cli.views.CLITableViewTests)
Tests the Write function. ... ok
testWrite (cli.views.MarkdownTableViewTests)
Tests the Write function. ... ok
testAddCredentialOptions (cli.storage_media_tool.StorageMediaToolTest)
Tests the AddCredentialOptions function. ... ok
testAddStorageMediaImageOptions (cli.storage_media_tool.StorageMediaToolTest)
Tests the AddStorageMediaImageOptions function. ... ok
testAddVSSProcessingOptions (cli.storage_media_tool.StorageMediaToolTest)
Tests the AddVSSProcessingOptions function. ... ok
testFormatHumanReadableSize (cli.storage_media_tool.StorageMediaToolTest)
Tests the _FormatHumanReadableSize function. ... ok
testGetNormalizedTSKVolumeIdentifiers (cli.storage_media_tool.StorageMediaToolTest)
Tests the _GetNormalizedTSKVolumeIdentifiers function. ... Floating point exception

**Source data:**

dmesg shows:
[   93.117292] traps: run_tests.py[2075] trap divide error ip:7fd55620a6fa sp:7ffc0f397610 error:0 in libtsk.so.13.3.1[7fd5561ed000+b2000]

**Comment by rickdeckardt** [comment]
issue identified w/ Kali sleuth kit libtsk13
solution: uninstall libtsk13 package, & install sleuthkit from sources

**Comment by joachimmetz** [comment]
For reference: https://github.com/sleuthkit/sleuthkit/issues/953

**Comment by hillu** [comment]
@rickdeckardt pytsk3/20170802-2 will contain a static-linked `libtsk`, so the reason for building sleuthkit from source should be gone.
