### ISSUE TITLE
Release preparations for Docker/Dockerhub

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1406]
- [ ] Make sure we didn't break the docker container
- [ ] Ensure dockerhub will result in containers that will include the new release

**Comment by ilyaglow** [comment]
Hey, any chances to see an automated docker build for Plaso one day? Plaso is developed with very high pace, which is great, and one-docker-container-per-year strategy feels kinda really long time to wait for the new features for docker users.

**Comment by rgayon** [comment]
Closing this issue. The Automated plaso image build is a good idea, I moved it in #1429
