### ISSUE TITLE
L2tcsv AttributeError

### ISSUE THREAD

**Issue by crazydahveed** [log2timeline/plaso#141]
First, I wanted to say thanks; plaso has come a long way and is now functional in our environment.  That said, when I try to export data using the l2tcsv output, I'm getting AttributeErrors.  However, if I utilize L2ttln, I get no such error.  I haven't tried the other modules, as L2ttln was sufficient for the job at hand.  I am essentially running in development style (dependencies check out, copied plaso to Lib\site-packages, copied frontend files to scripts).  This bug may (?) be related to bug #115.

```
psort.py -o L2tcsv plaso.db -w plaso.csv
Traceback (most recent call last):
  File "C:\Python27\Scripts\psort.py", line 761, in <module>
    if not Main():
  File "C:\Python27\Scripts\psort.py", line 735, in Main
    counter = front_end.ParseStorage(options)
  File "C:\Python27\Scripts\psort.py", line 361, in ParseStorage
    self._filter_buffer, event_queue_producers)
  File "C:\Python27\lib\site-packages\plaso\lib\output.py", line 295, in __exit__
    self.End()
  File "C:\Python27\lib\site-packages\plaso\lib\output.py", line 288, in End
    self.Flush()
  File "C:\Python27\lib\site-packages\plaso\lib\output.py", line 255, in Flush
    self.formatter.WriteEvent(event_object)
  File "C:\Python27\lib\site-packages\plaso\output\l2t_csv.py", line 59, in WriteEvent
    self.EventBody(event_object)
  File "C:\Python27\lib\site-packages\plaso\output\l2t_csv.py", line 127, in EventBody
    helper.GetLegacy(event_object),
  File "C:\Python27\lib\site-packages\plaso\output\helper.py", line 44, in GetLegacy
    if evt.timestamp_desc in [
AttributeError: 'EventObject' object has no attribute 'timestamp_desc'
```

**Comment by joachimmetz** [comment]
Do you still have this error?

**Comment by crazydahveed** [comment]
I downloaded the nightly/dev build this morning.  I am now able to create a
l2t csv file.  However, during creation, I am getting several "Unable to
write event: Unsupported data type: windows:registry:service." errors (it
fills up the terminal buffer of 200 lines).  However, that could very well
be a different bug.  Thanks!

**Comment by joachimmetz** [comment]
It's a different error and a strange one from the sound of it. I'll have a look and see if I can reproduce it.

**Comment by joachimmetz** [comment]
The error notification `Unable to write event:  originates here:
```
https://github.com/log2timeline/plaso/blob/master/plaso/output/interface.py#L200
```

**Comment by joachimmetz** [comment]
Closing issue, reopen if this is still reproducible with version 1.3.

**Comment by muhamadli302** [comment]
I also have this problem im using plaso version 1.4.0 on a linux vmdk file
while trying to do this command" psort.py -o L2tcsv linuxtest.plaso  -w plaso.csv"
this error appears "'EventObject' object has no attribute 'timestamp_desc'"

**Comment by joachimmetz** [comment]
* with which version did you create linuxtest.plaso?
* can you try the latest development version we are in the process of making a new release

**Comment by muhamadli302** [comment]
1.4.0 also
