### ISSUE TITLE
Update Linux repositories for Heimdall

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1421]
- [x] GIFT update dependencies
  * add pbr, setuptools for bencode
  * add idna, certifi for requests
  * add future for pefile
  * update stable with pre release
  * test pre release on live CD
- [x] GIFT update plaso
- [x] COPR update dependencies
- [x] COPR update plaso

**Comment by joachimmetz** [comment]
launchpad:
* add pbr for bencode

**Comment by joachimmetz** [comment]
Added: https://github.com/log2timeline/plaso/wiki/Fedora-Core-Packaged-Release
