### ISSUE TITLE
Automate plaso's docker image export

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1429]
Have a logt2timeline/plaso:dev image, automatically built & pushed to the registry

**Comment by rgayon** [comment]
See comment on #1406

**Comment by ilyaglow** [comment]
FYI I've tried to make a [dockerfile](https://github.com/ilyaglow/docker-plaso/blob/master/Dockerfile) based on Alpine Linux that builds latest plaso from this repo code base. I'm actually using it now and it seems to work. Hope it will help somehow, although Alpine is not really a `:dev` kind of a tag :)

**Comment by joachimmetz** [comment]
@Onager what is the status of this? I though this was fairly automated now.

**Comment by joachimmetz** [comment]
There are some inter-dependencies for fully automated deployment. Since plaso docker uses GIFT PPA stable that needs to be up to date first.
