### ISSUE TITLE
Issues with path detection for the Windows Event signature database

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#143]
Running plaso in virtualenv, I parse a disk image

    $ log2timeline.py /tmp/foo.dump evil.dd

And then run psort in the following way:

    $ psort.py /tmp/foo.dump "parser contains 'evt'"

Get a traceback:
    Traceback (most recent call last):
    ...
    File "/plaso_playground/virtual/local/lib/python2.7/site-packages/plaso-1.2.1_20150318-py2.7.egg/plaso/formatters/winevt_rc.py", line 82, in GetValues
    raise RuntimeError(u'Cannot retrieve values database not opened.')
    RuntimeError: Cannot retrieve values database not opened.

Run the tool in debug mode to get the exact location where the tool auto-detects the location of the database:

    $ psort.py /tmp/foo.dump "parser contains 'evt'" -d

This results in the crash and the following pdb session:

    (Pdb) self.filename
    u'/test/plaso_playground/virtual/share/plaso/winevt-rc.db'
    (Pdb) !import os
    (Pdb) !os.path.isfile(self.filename)
    False

I then go check and see that the file is actually here:
/test/plaso_playground/virtual/lib/python2.7/site-packages/plaso-1.2.1_20150318-py2.7.egg/share/plaso/winevt-rc.db

That is the location for the file is wrongly calculated.... or the database file is not properly copied over to the appropriate location....

**Comment by kiddinn** [comment]
copying the file manually to the location where the tool points to "fixes" the issue as in I can then run the tool and get the correct results, but not solving the underlying issue

**Comment by joachimmetz** [comment]
> This results in the crash and the following pdb session:

See for dis ambiguity: https://github.com/log2timeline/plaso/wiki/Troubleshooting#crashes-hangs-and-tracebacks

For setup.py data locationsee: https://docs.python.org/2/install/ 

So I'm not sure why the data files end up in the data directory unless it changes the prefix for some reason. Agree that the application should continue when it cannot find it's data path. Do you get a warning before the exception is raised?

**Comment by kiddinn** [comment]
no warning, just a crash

**Comment by kiddinn** [comment]
no, sorry, take that back,... there was a warning but it got quickly drowned by other things,

**Comment by joachimmetz** [comment]
Fixes for handling non existing data location: http://codereview.appspot.com/213450043

**Comment by joachimmetz** [comment]
@kiddinn can you:

* determine if virtual env does something special with the data path; if so we could add the default to the search order

**Comment by kiddinn** [comment]
This should be done, the issue here was when you install by setup.py install you install an egg file, and that case was not covered. Pushed: 6d52966ba932cff612697a52b92245401e2d0cab in which fixes this
