### ISSUE TITLE
psteal with Timesketch requires -w

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#1433]
**Plaso version:**
20170930

**Operating system Plaso is running on:**
Ubuntu 16.04

**Installation method:**
GIFT
apt-get install python-plaso plaso-tools

**Description of problem:**
When running psteal.py with Timesketch as output module it complains that it needs -w OUTPUT_FILE. This doesn't makes sense with Timesketch. Can we make that flag optional for certain output modules?

$ psteal.py --source System.evtx -o timesketch --name steal_test
ERROR: Output format: timesketch requires an output file (-w OUTPUT_FILE)

Workaround:
$ psteal.py --source System.evtx -o timesketch --name steal_test **-w none**

**Comment by Onager** [comment]
@rgayon Can you fix this please?
