### ISSUE TITLE
Update "Adding a new dependency" wiki page

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1440]
~~https://github.com/log2timeline/plaso/wiki/Adding-a-new-dependency needs to be be updated to account for recent changes to dependency-file-generation code.~~

* [x] ~~Generate plaso/dependency.py~~
* [ ] Generate https://github.com/log2timeline/plaso/blob/master/docs/sources/developer/Licenses-dependencies.md

**Comment by joachimmetz** [comment]
ack

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/335930043/ on the way to automate the generation of plaso/dependency.py

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/wiki/Adding-a-new-dependency was moved to https://github.com/log2timeline/l2tdocs/blob/master/process/Dependencies.md

**Comment by Onager** [comment]
Closing this out, as the indicated page no longer exists.
