### ISSUE TITLE
log2timeline: allow to set "initial date" for time source without a year (or date)

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#146]
The syslog parser determines the year based on the date of the file entry: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/syslog.py#L58

* Maybe add a warning (have to reduce the output of the tool as well for it to be visible)
* Add an option to override the "initial date"

**Comment by Onager** [comment]
I wonder if we could do something about checking if the file spans a year boundary, and then adjusting the year based on that.

**Comment by Onager** [comment]
Maybe read the file from the end, if the crtime can't be read?

**Comment by joachimmetz** [comment]
> I wonder if we could do something about checking if the file spans a year boundary, and then adjusting the year based on that.

This should already be in.

The issue is that if you copy a file e.g. the time values are changed, so you have incorrect start information. Hence having an override.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/302980043/
