### ISSUE TITLE
MFT not being parsed using default log2timeline parser arguments on an NTFS disk image

### ISSUE THREAD

**Issue by john-corcoran** [log2timeline/plaso#1466]
**Plaso version:**

20170930

**Operating system Plaso is running on:**

Windows 10 x64

**Installation method:**

Windows packaged release at https://github.com/log2timeline/plaso/releases

**Description of problem:**

No MFT events are being generated when a Windows disk image is being processed with default log2timeline arguments, as follows:
log2timeline.exe --logfile log.txt -d output.db image.E01

MFT events are however generated when running with the mft parser explicitly selected:
log2timeline.exe --logfile log.txt --parsers mft -d output.db image.E01

MFT events are also generated if the MFT files are copied to a folder:
log2timeline.exe --logfile log.txt -d output.db /folderpath/

Perhaps this is normal behaviour and filestat events replace MFT parsing on default settings for Windows disk images?

**Debug output/tracebacks:**

log2timeline.exe --logfile log.txt -d output.db image.E01
For this run, the $MFT and $MFTMirr files are identified and scheduled tasks are queued, but the tasks never enter processing: merge and task completion occurs only 14 seconds after the task is originally queued.

log2timeline.exe --logfile log.txt --parsers mft -d output.db image.E01
For this run, the $MFT and $MFTMirr are queued and also enter processing, before being merged and completed a number of hours later. 

**Source data:**

Windows 7 disk image (a compressed E01 file) with one NTFS partition.

**Comment by Onager** [comment]
This is because the MFT parser isn't enabled by default when Plaso detects a Windows operating system. If you enable the win7_slow parser preset: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/presets.py the MFT parser will be enabled.

This is because the MFT parser takes a long time to run, and we need to add some extra features to increase its usefulness: https://github.com/log2timeline/plaso/issues/316

**Comment by EricZimmerman** [comment]
you should look at MFTECmd for processing MFTs. it handles most, regardless of size in just a few seconds to a minute or so for really large (1GB+) MFTs =)

**Comment by joachimmetz** [comment]
@EricZimmerman very nice that you are pitching your own tools here. A couple of considerations:

* Can you run MFTECmd directly on a BDE encrypted volume?
* Does is correctly handle NTFS sequence numbers?
* Does it correctly handle full paths, not blindly assuming the name of the parent is the actual original path (e.g. hard links)?

If it uses the same naive approach and blind assumption as most of the other MFT parsers out there, from a forensics point of view I don't think speed is an improvement.

**Comment by joachimmetz** [comment]
I'll continue with you this conversation off thread, seeing that you are hijacking this issue now multiple times for your own purposes.

**Comment by joachimmetz** [comment]
For context about the "accuracy" of MFTECmd https://github.com/EricZimmerman/MFTECmd/issues/5
