### ISSUE TITLE
Cache Full Error

### ISSUE THREAD

**Issue by stumpyuk1** [log2timeline/plaso#147]
Whenever I try and run log2timeline.py, I get a repeating "CacheFullError" error message.   The dump file will not go beyond 20MB in size

What steps will reproduce the problem?
Using log2timeline.py.  Have experimented with different switches, including no_vss, problem and passing the correct partition offset but same problem seems to occur in all circumstances.
Last command tried was:

log2timeline.py --partition 2 --no_vss plaso/plaso.dump TEST_MAXTOR.E01
What version of plaso/log2timeline are you using? (use log2timeline.py -v
to see)
log2timeline - plaso back-end 1.2.0 (Installed from the .tar.gz archive hosted on Google Drive)

What versions of the underlying parser libraries are you using? (run
utils/check_dependencies.py from the source)

[OK]            bencode
[OK]            dateutil.parser
[OK]            binplist version: 0.1.4
[OK]            six version: 1.9.0
[OK]            psutil version: 1.2.1
[OK]            construct version: 2.5.2
[OK]            dpkt version: 1.8
[OK]            pyparsing version: 2.0.3
[OK]            pytz
[OK]            google.protobuf
[OK]            dfvfs version: 20150303
[OK]            sqlite3 version: 3.8.2
[OK]            yaml version: 3.11
[OK]            IPython version: 1.2.1
[OK]            SleuthKit version: 4.1.3
[OK]            pytsk3 version: 20150111
[INFO]          libbde (pybde) version: 20150106 installed, version: 20150204 available.
[OK]            libesedb (pyesedb) version: 20141110
[OK]            libevt (pyevt) version: 20150105
[OK]            libevtx (pyevtx) version: 20150105
[INFO]          libewf (pyewf) version: 20140608 installed, version: 20150126 available.
[INFO]          libfwsi (pyfwsi) version: 20150105 installed, version: 20150124 available.
[OK]            liblnk (pylnk) version: 20150105
[INFO]          libmsiecf (pymsiecf) version: 20141130 installed, version: 20150314 available.
[OK]            libolecf (pyolecf) version: 20150106
[OK]            libqcow (pyqcow) version: 20150105
[OK]            libregf (pyregf) version: 20150315
[OK]            libsmdev (pysmdev) version: 20150105
[OK]            libsmraw (pysmraw) version: 20150105
[OK]            libvhdi (pyvhdi) version: 20150110
[OK]            libvmdk (pyvmdk) version: 20150105
[OK]            libvshadow (pyvshadow) version: 20150106

On what operating system? (be specific, as in Mac OS X Mountain Lion,
10.8.2 for instance)

Distributor ID: LinuxMint
Description:    Linux Mint 17 Qiana
Release:        17
Codename:       qiana

Linux AERO 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Where you running this against an image or a mount point?

Run against E01 image (not mounted)

What is the expected output? What do you see instead?
The terminal output, repeats the following error:

CacheFullError: Maximum number of cached values reached.
2015-03-23 09:51:21,511 [ERROR] (Worker_1  ) PID:25767 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "build/bdist.linux-x86_64/egg/plaso/parsers/oxml.py", line 96, in Parse
    file_object = file_entry.GetFileObject()
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 125, in GetFileObject
    self.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_io.py", line 79, in open
    self._resolver_context.CacheFileObject(path_spec, self)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/context.py", line 52, in CacheFileObject
    self._file_object_cache.CacheObject(path_spec.comparable, file_object)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')

**Comment by joachimmetz** [comment]
This is related to: https://github.com/log2timeline/dfvfs/issues/10.

Since you are using 1.2.0 you'll have to use a version of dfVFS before Feb 24, 2015 e.g. https://github.com/log2timeline/dfvfs/releases/tag/20150117 or the latest version of plaso.

**Comment by jahrome** [comment]
Not sure if it is normal but I still have *CacheFullError* with latest plaso + dfvfs:
```
2015-07-13 13:16:57,177 [ERROR] (Worker_00 ) PID:6164 <worker> Maximum number of cached values reached.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/plaso/engine/worker.py", line 439, in _ProcessPathSpec
    path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 53, in OpenFileEntry
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 166, in OpenFileSystem
    file_system.Open(path_spec=path_spec)
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/file_system.py", line 234, in Open
    self._resolver_context.CacheFileSystem(path_spec, self)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/context.py", line 62, in CacheFileSystem
    self._file_system_cache.CacheObject(identifier, file_system)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/cache.py", line 83, in CacheObject
    raise errors.CacheFullError(u'Maximum number of cached values reached.')
CacheFullError: Maximum number of cached values reached.
```

Checking availability and versions of plaso dependencies.
[OK]		artifacts version: 20150409
[OK]		bencode
[OK]		binplist version: 0.1.4
[OK]		construct version: 2.5.2
[OK]		dateutil version: 2.4.2
[OK]		dfvfs version: 20150708
[OK]		dpkt version: 1.8
[OK]		google.protobuf
[OK]		hachoir_core version: 1.3.3
[OK]		hachoir_parser version: 1.3.4
[OK]		hachoir_metadata version: 1.3.3
[OK]		IPython version: 3.2.0
[OK]		pefile version: 1.2.10-139
[OK]		psutil version: 3.0.1
[OK]		pyparsing version: 2.0.3
[OK]		pytz
[OK]		requests version: 2.7.0
[OK]		six version: 1.9.0
[OK]		sqlite3 version: 3.8.10.2
[OK]		yaml version: 3.11
[OK]		SleuthKit version: 4.1.3
[OK]		pytsk3 version: 20150406
[OK]		libbde (pybde) version: 20150204
[OK]		libesedb (pyesedb) version: 20150409
[OK]		libevt (pyevt) version: 20150706
[OK]		libevtx (pyevtx) version: 20150105
[INFO]		libewf (pyewf) version: 20140608 installed, version: 20150126 available.
[OK]		libfwsi (pyfwsi) version: 20150701
[OK]		liblnk (pylnk) version: 20150617
[OK]		libmsiecf (pymsiecf) version: 20150708
[OK]		libolecf (pyolecf) version: 20150630
[OK]		libqcow (pyqcow) version: 20150105
[OK]		libregf (pyregf) version: 20150704
[OK]		libsigscan (pysigscan) version: 20150627
[OK]		libsmdev (pysmdev) version: 20150105
[OK]		libsmraw (pysmraw) version: 20150105
[OK]		libvhdi (pyvhdi) version: 20150110
[OK]		libvmdk (pyvmdk) version: 20150516
[OK]		libvshadow (pyvshadow) version: 20150106

**Comment by joachimmetz** [comment]
No that is not normal, any notifications/errors that indicate if certain file objects are not closed explicitly?

**Comment by jahrome** [comment]
No, no other messages around those errors. FYI, it is occuring while
processing Firefox' cache2/entries, got 5272 exceptions for 13380 file
in the cache.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/257

**Comment by joachimmetz** [comment]
This error typically means there are too many files open at the same time, meaning that something did not close its file object handle, or that the maximum recursion depth has been reached.

> No, no other messages around those errors.

Maybe earlier.
