### ISSUE TITLE
Certain event data attributes are represented as bytes not strings

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1477]
**Plaso version:**

plaso-20171020 (pre-release)

**Operating system Plaso is running on:**

Ubuntu 14

**Installation method:**

Manual installation (setup.py from plaso-20171020.tar.gz)

**Description of problem:**

When exporting in json_line format, the output of some properties from some parsers are in the following format:

`"imphash": {"__type__": "bytes", "stream": "1234567890abcdef1234567890abcdef"}`

I would expect the output to look like this instead:

`"imphash": "1234567890abcdef1234567890abcdef"`

* [x] ~~msiecf and pe https://codereview.appspot.com/337030043/~~
* [x] ~~oxml: https://codereview.appspot.com/337020043/~~

**Comment by joachimmetz** [comment]
This is due to the imphash being stored at runtime as bytes not as a string. Likely the type it receives from pefile. An explicit decode at https://github.com/log2timeline/plaso/blob/f0480c8b61f5c0ffa1da8aaa24dd56ec31d9472b/plaso/parsers/pe.py#L188 likely does the trick.

**Comment by kinky-it** [comment]
Would it help if I would list more parser/field combinations that could benefit from such a change? 

Or do you consider this a won't-fix?

**Comment by joachimmetz** [comment]
So I've been pushing numerous Unicode changes recently and work on [dfkinds](https://github.com/log2timeline/dfkinds) should make these things more consistent as well. However it will take some time before we're at the desired state. In the mean time feel free to point these out. Maybe we can bulk them up into a single fix-it change.

**Comment by kinky-it** [comment]
I found the following parser/field combinations written in the specified format:

**openxml:** app_version, author, creating_app, doc_security, hyperlinks_changed, i4, last_saved_by, links_up_to_date, number_of_characters, number_of_characters_with_spaces, number_of_lines, number_of_pages, number_of_paragraphs, number_of_words, revision_number, scale_crop, shared_doc, template, total_time
**msiecf**: cache_directory_name
**pe**: dll_name, imphash

**Comment by joachimmetz** [comment]
thx, I'll have a look, likely this weekend, which one of these could be changed to string

**Comment by joachimmetz** [comment]
oxml: https://codereview.appspot.com/337020043/

**Comment by joachimmetz** [comment]
removing bug label, there is nothing broken.

**Comment by joachimmetz** [comment]
msiecf and pe https://codereview.appspot.com/337030043/

**Comment by joachimmetz** [comment]
Changes integrated, closing issue. I'll expect that we'll find some more of these over time until dfkinds is fully operational.
