### ISSUE TITLE
Tagging label stored as bytes

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1478]
**Plaso version:**

plaso-20171020 (pre-release)

**Operating system Plaso is running on:**

Ubuntu 14

**Installation method:**

Manual installation (setup.py from plaso-20171020.tar.gz)

**Description of problem:**

It is now possible to run several analysis plugins (like tagging and nsrlsvr) on the plaso dump file, by running psort.py twice. The JSON output of an event tagged by both tagging and nsrlsvr looks like this:

`"tag": {"__container_type__": "event_tag", "__type__": "AttributeContainer", "comment": "Tag applied by tagging analysis plugin.Tag applied by nsrlsvr analysis plugin", "labels": [{"__type__": "bytes", "stream": "doc_open"}, "nsrl_present"]}`

I would expect the tag to look like this instead:

`"tag": {"__container_type__": "event_tag", "__type__": "AttributeContainer", "comment": ["Tag applied by tagging analysis plugin.","Tag applied by nsrlsvr analysis plugin"], "labels": ["doc_open","nsrl_present"]}`

(Note that #1477 also applies to the labels)

**Comment by joachimmetz** [comment]
> (Note that #1477 also applies to the labels)

The JSON serializer will serialize any byte stream/string to `{"__type__": "bytes", "stream": "..."}`

**Comment by kinky-it** [comment]
Note that the comments of two tags are concatenated, and the labels of two tags are combined in an array.

**Comment by joachimmetz** [comment]
Note to self, have a look to see if the label (included user provided one) is Unicode otherwise make it so.

**Comment by joachimmetz** [comment]
@kinky-it Unicode strings are now the runtime default. https://github.com/log2timeline/plaso/issues/1268. If you have some time to test again, with recent HEAD, much appreciated.

I'll have a look (when time permits) if the tagging labels read from the tagging file and those provided for nsrlsrv are correctly read as Unicode strings.

**Comment by kinky-it** [comment]
HEAD now produces the following data. 

Event only tagged by tagging, one label:
`"tag": {"__container_type__": "event_tag", "__type__": "AttributeContainer", "comment": "Tag applied by tagging analysis plugin.", "labels": [{"__type__": "bytes", "stream": "test_tag_two"}]}
`

Event only tagged by tagging, two labels:
`"tag": {"__container_type__": "event_tag", "__type__": "AttributeContainer", "comment": "Tag applied by tagging analysis plugin.", "labels": [{"__type__": "bytes", "stream": "test_tag_one"}, {"__type__": "bytes", "stream": "test_tag_two"}]}
`

Event tagged by tagging and nsrlsvr:
`"tag": {"__container_type__": "event_tag", "__type__": "AttributeContainer", "comment": "Tag applied by tagging analysis plugin.Tag applied by nsrlsvr analysis plugin", "labels": [{"__type__": "bytes", "stream": "test_tag_two"}, "nsrl_present"]}
`

Analysis plugin tagging produces byte streams, nsrlsvr produces strings. Combining tags results in concatenated tag comments and mixed type labels.

**Comment by joachimmetz** [comment]
thx, then it looks like the tagging labels are not properly converted to string, as suspected.

**Comment by joachimmetz** [comment]
Added documentation to define the tagging file as UTF-8 https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-tagging

**Comment by joachimmetz** [comment]
Marked as clean up, seeing this is not really a bug more undesired behavior.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/333210043

**Comment by joachimmetz** [comment]
Changes merged
