### ISSUE TITLE
storage: zipfile open fails on some implementations due to negative seek

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#148]
On some implementations the [append mode](https://github.com/log2timeline/plaso/blob/master/plaso/lib/storage.py#L297) seems to cause zipfile to make a negative seek (before 0), strictly speaking this is non-POSIX compliant behavior.

From man lseek:

```
EINVAL whence is not valid.  Or: the resulting file offset would be negative, or beyond the end of a seekable device.
```

Work around is to use write mode if the zip file does not exists, however we cannot rely on os.path.exists() to determine if the file exists.

**Comment by kiddinn** [comment]
do you have a proposal on how we can fix this?

**Comment by joachimmetz** [comment]
Needs more research. I opt to keep it open for now as a reminder to myself.

**Comment by joachimmetz** [comment]
Obsolete by SQLite storage replacing ZIP storage
