### ISSUE TITLE
Update plist support

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1480]
Our current binary plist handler, binplist, isn't Python3 compatible, and hasn't been updated in a while.

We need to either update binplist, or move to a different library, possibly [biplist](https://bitbucket.org/wooster/biplist).

**Comment by Onager** [comment]
biplist looks a very easy replacement.

**Comment by joachimmetz** [comment]
* License looks OK, BSD 3-clause (https://pypi.python.org/pypi/biplist/1.0.3).
* No additional requirements (https://bitbucket.org/wooster/biplist/src/14ff29cb3c88c2728c16df9bf788717ce022b01c/setup.py?at=master&fileviewer=file-view-default#setup.py-55)

IMHO go for it. Necessary steps that come to mind:
* add it to l2tdevtools
* add it to l2tbinaries, GIFT and COPR
* migrate the source, update dependency information

**Comment by joachimmetz** [comment]
Unlikely to be implemented before Jan 25, bumping release

**Comment by joachimmetz** [comment]
@Onager let's check the plist corruption of https://github.com/log2timeline/plaso/issues/1776 on biplist as well

**Comment by Onager** [comment]
Completed in https://github.com/log2timeline/plaso/commit/054b67f8e4cbacd9e946716179fbc8c779db8aa3
