### ISSUE TITLE
Set up Python 3 end-to-end tests

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1486]
Set up Python 3 end-to-end tests and compare results with Python 2

**Comment by Onager** [comment]
We have python 3 tests running in travis now, can this be closed?

**Comment by joachimmetz** [comment]
nope this issue says end-to-end tests

**Comment by joachimmetz** [comment]
Per conversation with @Onager there are now Python 3 end-to-end tests.

**Comment by Onager** [comment]
Python end-to-end tests are running, moving automated test comparison to a separate issue.
