### ISSUE TITLE
Update dependency information to support pycrypto versioning

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1489]
Pycrypto uses both x.y and x.y.z release numbers. We are currently check for 2.6.0 instead of 2.6.
https://github.com/dlitz/pycrypto/releases

**Comment by joachimmetz** [comment]
Originally reported by @freddiebarrsmith in https://github.com/log2timeline/plaso/pull/1488 and https://github.com/log2timeline/plaso/pull/1487

**Comment by joachimmetz** [comment]
Changes integrated in https://codereview.appspot.com/335930043/

**Comment by freddiebarrsmith** [comment]
You haven't fixed the problem I suggested? ...

**Comment by joachimmetz** [comment]
Had not pushed the updates yet.

**Comment by joachimmetz** [comment]
Changes have been merged
