### ISSUE TITLE
log2timeline --vss-stores accepts 'all', but no mention in help

### ISSUE THREAD

**Issue by f-s-p** [log2timeline/plaso#149]
Neither the --help output nor the online documentation mention that log2timeline --vss-stores argument can take the value "all" in order to process all vss stores at once without first determining how many and without additional prompts to the user.  This is useful for automating processing of drive images.  I had to read through the code to find that the "all" value was valid.

**Comment by joachimmetz** [comment]
Thanks for the feedback. Agree makes sense to add this to the help output.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/216400043/
