### ISSUE TITLE
Update to new TSK version

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1490]
* [x] update pytsk source
* [x] package pytsk for GIFT PPA
* [x] package pytsk for GIFT COPR
* [x] package pytsk for l2tbinaries macos
* [x] package pytsk for l2tbinaries win32
* [x] package pytsk for l2tbinaries win64

**Comment by joachimmetz** [comment]
Pytsk updated. Ran into some C89 compatibility issues: https://github.com/sleuthkit/sleuthkit/issues/1002

**Comment by joachimmetz** [comment]
Updated dev
