### ISSUE TITLE
Show storage/output/analysis plugins that are missing dependencies as disabled, rather than hiding them altogether.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#150]
Reference: https://plus.google.com/112566021383500810194/posts/5f7D2cP9pT5

**Comment by joachimmetz** [comment]
+ an indicator that they are disabled

**Comment by kiddinn** [comment]
Created http://codereview.appspot.com/230580043 as a first attempt (for output modules)

**Comment by kiddinn** [comment]
The code is in for output modules, they are now displayed in a separate view if they are disabled.

The only modules ATM we allow to be "not loaded" if dependencies are missing are the output modules, so this issue can be closed now.

We just need to make sure that we add comparable solution to future parts of the tool if/when that is needed.
