### ISSUE TITLE
"preprocess" on a directory should not stop processing

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1510]
**Plaso version:**

$ python tools/log2timeline.py --version
plaso - log2timeline version 20171120

**Operating system Plaso is running on:**
$ uname -a
Linux grimbergen 4.4.0-97-generic #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linu

**Installation method:**

Git clone sources

**Description of problem:**

When running log2timeline.py on a directory, preprocess is turned on, when the documentation says otherwise:
```
  -p, --preprocess      Turn on preprocessing. Preprocessing is turned on by
                        default when parsing image files, however if a mount
                        point is being parsed then this parameter needs to be
                        set manually.
```
This was detected when debugging issue #1509

**Debug output/tracebacks:**

**Source data:**

**To do:**
* [x] Update `--help` information
  * removed the option
  * https://codereview.appspot.com/337130043/
* [x] "preprocess" on a directory should not stop/block processing
  * https://github.com/log2timeline/dfvfs/issues/247

**Comment by rgayon** [comment]
When looking at the backtrace in #1509 , i saw that PreprocessSources was being run, which is unexpected since the documentation seems to be indicating otherwise

**Comment by joachimmetz** [comment]
per conversation documentation here is `--help`

**Comment by joachimmetz** [comment]
for some reason the end-to-end tests on travis are failing

**Comment by joachimmetz** [comment]
end-to-end test issue solved itself
