### ISSUE TITLE
Analysis plugin nsrlsvr: exception on unicode self._port

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1512]
**Plaso version:**

Release 20171118

**Operating system Plaso is running on:**

```
$ lsb_release -si
Ubuntu

$ lsb_release -sr
14.04

$ uname -m
x86_64
```

**Installation method:**

```
python setup.py build
python setup.py install
```

**Description of problem:**

An exception is thrown when the nsrlsvr analysis plugin is used. The exception is thrown directly after starting psort.py with the plugin. The exception is thrown regardless of specifying the nsrlsvr_port command line argument.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171118-py2.7.egg/plaso/analysis/interface.py", line 438, in run
    hash_analyses = self.Analyze(hashes)
  File "/usr/local/lib/python2.7/dist-packages/plaso-20171118-py2.7.egg/plaso/analysis/nsrlsvr.py", line 99, in Analyze
    'Opening connection to {0:s}:{1:d}'.format(self._host, self._port))
ValueError: Unknown format code 'd' for object of type 'unicode'
```

**Comment by joachimmetz** [comment]
thx for the report, I'll need to have a closer look what is causing this issue.

**Comment by joachimmetz** [comment]
Looks like the port in the analysis plugin is never set by the argument helper (including the default).

**Comment by joachimmetz** [comment]
With: https://codereview.appspot.com/332310043/ applies this reports:
```
ERROR: Unable to connect to nsrlsvr localhost:9120
```

**Comment by joachimmetz** [comment]
Fixes and additional tests pending in: https://codereview.appspot.com/335080043

**Comment by joachimmetz** [comment]
Changes merged.
