### ISSUE TITLE
Analysis plugin tagging: --tagging-file argument not parsed

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1513]
**Plaso version:**

Release 20171118

**Operating system Plaso is running on:**

```
$ lsb_release -si
Ubuntu

$ lsb_release -sr
14.04

$ uname -m
x86_64
```

**Installation method:**

```
python setup.py build
python setup.py install
```

**Description of problem:**

The analysis plugin tagging does not seam to parse the --tagging-file argument correctly. The following error message is shown:

```
No tag definition file specified, and plaso was not able to autoselect a tagging file. As no definitions were specified, no events will be tagged.
```

**Comment by ktwombley** [comment]
This appears to be a regression of #1364

**Comment by ktwombley** [comment]
Manually applying the patch in the code review link on #1364 will fix the issue until an update is released. I have tested this myself.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/332310043/

**Comment by joachimmetz** [comment]
Changes merged, reopen if issue persists.
