### ISSUE TITLE
Analysis plugin nsrlsvr: label argument ignored 

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1518]
**Plaso version:**

Release 20171118, added https://codereview.appspot.com/332310043/

**Operating system Plaso is running on:**

Ubuntu 14.04 64-bit

**Installation method:**

```
python setup.py build
python setup.py install
```

**Description of problem:**

The analysis plugin nsrlsvr does not use the --nsrlsvr-label and --nsrlsvr_label arguments. 

**Source data:**

Typo in /plaso/cli/helpers/nsrlsvr_analysis.py, line 52: dest='nsrlvr_label' in stead of dest='nsrlsvr_label'

**Comment by joachimmetz** [comment]
Thx, for the report. Similar issue as https://github.com/log2timeline/plaso/issues/1512. Fixes and additional tests pending in: https://codereview.appspot.com/335080043

**Comment by joachimmetz** [comment]
Changes merged.
