### ISSUE TITLE
foreman: improvements

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#153]
Done:

* [x] [merge foreman and engine](https://codereview.appspot.com/243100043/)
* [x] Instead of spamming the console create a top like view and use the foreman to get the status of the workers (experimental)
* [x] Pad worker identifiers with 0s, so they sort more nicely
* [x] Making error status visible
* [x] Handle termination on error status
* [x] Change log2timeline to print "Processing aborted" if applicable instead of "Processing completed"
* [x] introduce RaiseIfNotRegistered(pid) and RaiseIfNotMonitored(pid)
* [x] ~~make sure workers catch relevant exceptions e.g. https://github.com/log2timeline/plaso/issues/215~~
* [x] catch segfault and register what broke?
  * ~~https://codereview.appspot.com/245790043/~~
  * Issue causing the workers to hang again when catching a real segfault, works with kill -11 (not feasible)
* [x] in status view window indicate display name of source path specification is being processed

To do:

* [ ] Keep track of crashing workers and provide a report at the end of the processing.
* [ ] [have ProcessSources return process status](https://codereview.appspot.com/243100043/)
  * need single processing use processing status as well
  * Store this process in the storage file?
* [ ] add automated tests for scenarios
* [ ] remove time out from multi-processing queue

**Comment by kiddinn** [comment]
Assigning this to @joachimmetz since he's been adding this functionality in, already few CL's in.

What's still missing is the report at the end that gets stored inside the storage file.

**Comment by joachimmetz** [comment]
Foreman keeps repeating:
```
[WARNING] Error while making RPC call: [Errno 111] Connection refused
[ERROR] Process Worker_1 (PID: 9565) is not functioning when it should be. Terminating it and removing from list.
[WARNING] Process Worker_1 (PID: 9565) is still alive.
[WARNING] Error while making RPC call: [Errno 111] Connection refused
[ERROR] Process Worker_3 (PID: 9567) is not functioning when it should be. Terminating it and removing from list.
[WARNING] Process Worker_3 (PID: 9567) is still alive
```

**Comment by joachimmetz** [comment]
Worker stuck in running mode:
```
Worker_5        10029   running         9303 (583)      TSK:/Users/...
```

**Comment by joachimmetz** [comment]
* [ ] Making error status visible: http://codereview.appspot.com/237630043
* [ ] Handle termination on error status
