### ISSUE TITLE
Upgrade Safari parser to a SQLite parser plugin

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#1531]
Later versions of Safari no longer use a plist to store the history file but a SQLite file. The parser needs to be updated to support both versions.

**Comment by kiddinn** [comment]
this is already being worked on by @chimau

**Comment by joachimmetz** [comment]
@chimau FYI the SQLite plugin API slightly changed recently. See:  https://github.com/log2timeline/plaso/commit/3eee9262b7ea2476168e41a8163285897e099cfd

**Comment by Onager** [comment]
Completed by #1552
