### ISSUE TITLE
filestat parser timestamps incorrect

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1533]
**Plaso version:**

plaso-20171129 (HEAD)

**Operating system Plaso is running on:**

Fedora 26

**Installation method:**

Manual installation (setup.py from plaso-master.zip on 20171129)

**Description of problem:**

Parser filestat produces events with timestamps in seconds, not microseconds.

**Source data:**

My guess is that the error was introduced in commit cd2424e8192950f1614e7208ba24c920e0b0c201.

**Comment by kinky-it** [comment]
**Source data:**

EWF image of a FAT32 partition. 

Volume label leads to events with `"timestamp_desc": "Creation Time"` and `"timestamp_desc": "Last Access Time"`, both set to 0. Volume label event with `"timestamp_desc": "Content Modification Time"` has timestamp in seconds.

$MBR, $FAT1 and $FAT2 lead to events with `"timestamp_desc": "Creation Time"`, `"timestamp_desc": "Last Access Time"` and `"timestamp_desc": "Content Modification Time"`, all set to 0.

Regular files are timestamped in seconds.

**Comment by joachimmetz** [comment]
Which version of pytsk / libtsk and dfvfs ?

**Comment by kinky-it** [comment]
Installed plaso-20171118 from forensics.cert.org repo, then downloaded HEAD on the 29th and installed using setup.py.

Name         : pytsk3
Version      : 20170802
Release      : 1.fc26
Arch         : x86_64
Size         : 8.5 M
Source       : pytsk3-20170802-1.fc26.src.rpm

Name         : dfvfs
Version      : 20171022
Release      : 1.fc26
Arch         : noarch
Size         : 1.4 M
Source       : dfvfs-20171022-1.fc26.src.rpm

**Comment by joachimmetz** [comment]
thx; seeing we recently made some changes to dfvfs and pytsk making sure if they could be a contributing factor as well. I'll have a more detailed look later this week.

**Comment by joachimmetz** [comment]
For some reason tests/parsers/filestat.py did not check for date and time values :|

Think I'm able to reproduce a similar issue with some additional test coverage.
```
FAIL: testTSKFile (__main__.FileStatTest)
Read a file within an image file and make few tests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/parsers/filestat.py", line 49, in testTSKFile
    self.assertEqual(event.timestamp, expected_timestamp)
AssertionError: 1337961653L != 1337961653000000
```

**Comment by joachimmetz** [comment]
Issue in dfvfs https://github.com/log2timeline/dfvfs/blob/master/dfvfs/vfs/tsk_file_entry.py#L102 where timestamp is only corrected when pytsk has a seconds fragment.

https://codereview.appspot.com/332400043/

**Comment by joachimmetz** [comment]
And additional filestat test coverage:
https://codereview.appspot.com/336300043

**Comment by joachimmetz** [comment]
dfvfs updated, additional test coverage added
