### ISSUE TITLE
Add user documentation for analysis plugins

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1538]
Extend:

* [ ] https://github.com/log2timeline/plaso/wiki/Analysis-plugins
* [x] https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-tagging
* [x] https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-viper
* [x] https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-virustotal

**Comment by Onager** [comment]
Made some minimal updates for some analysis plugins, but leaving the larger analysis plugin set for later.

**Comment by joachimmetz** [comment]
Documentation was moved to readthedocs, closing this issue.
