### ISSUE TITLE
artifacts integration

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#155]
Integrate [artifacts](https://github.com/ForensicArtifacts/artifacts) support

- [x] ~~[Improve artifact definition specification](https://github.com/ForensicArtifacts/artifacts/issues/13)~~
- [x] ~~Step 1 of artifacts support~~
  - ~~move knowledge base to engine~~
  - ~~add artifacts as a dependency~~
- [x] ~~Move Registry handling out of preprocessor plugins~~
  - ~~[clean up of Windows preprocessor](https://codereview.appspot.com/250920043/)~~
- [x] ~~[clean up of Max OS X preprocessor](http://codereview.appspot.com/249540043)~~
- [x] ~~refactor preprocess plugins to be data based not platform based, e.g. hostname preprocess plugin~~
  - data per platform-based for now
- [x] ~~[make preprocessor artifact driven](https://codereview.appspot.com/150170043/)~~
  - ~~Necessary changes to artifacts~~
    - ~~https://github.com/ForensicArtifacts/artifacts/pull/150~~
    - ~~https://github.com/ForensicArtifacts/artifacts/pull/152~~
  - ~~Changes to dfvfs~~
    - ~~[file system searcher add glob support](https://codereview.appspot.com/278640043/)~~
  - ~~Changes to dfwinreg~~
    - ~~[add searcher with glob support](https://codereview.appspot.com/323020043/)~~
  - ~~Changes to tools~~
    - ~~[pass artifacts definition location](https://codereview.appspot.com/321000043/)~~

To do after 2017 mid year release:
* https://github.com/log2timeline/plaso/issues/1312

**Comment by Onager** [comment]
This isn't going to be complete for 1.4, moving to 1.5 for now.
