### ISSUE TITLE
Logic of pending merge task prioritizing is reversed

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1550]
**Plaso version:**

plaso-20171129 (HEAD)

**Operating system Plaso is running on:**

Fedora 26

**Installation method:**

Manual installation (setup.py from plaso-master.zip on 20171129)

**Description of problem:**

While troubleshooting and testing the merge depletion issue, I noticed that the logic in the task scheduler seems to be reversed.

https://github.com/log2timeline/plaso/blob/20e61d60710f9e37cda8fb7b4f5316cd178c4d88/plaso/multi_processing/task_manager.py#L224

The code does not match the function description: the next task swaps out the current one when the priority of the next one is **lower** (or equal to) the current. As far as I understand, this may cause big tasks to be pushed back as smaller tasks are added. 

In my tests, reversing the logic does not prevent merge depletion, though.

**Comment by joachimmetz** [comment]
From: https://github.com/log2timeline/plaso/blob/452a6ea1f60a65d433be8e76e104d0ade4157691/plaso/containers/tasks.py#L28

```
    merge_priority (int): priority used for the task storage file merge, where
        a lower value indicates a higher priority to merge.
```

**Comment by joachimmetz** [comment]
@kinky-it that the logic is reserved might have to do that a lower value is considered a higher priority.

Regarding merge depletion this is a challenging problem to solve. What happens is that event sources are collected by the workers. But that these event sources only come available for the mail process (foreman) after they are merged to the main storage. Plaso merges directories before plain files to partially address merge depletion.

**Comment by kinky-it** [comment]
Apologies, thanks for clarifying.

**Comment by joachimmetz** [comment]
Closing issue, question answered.
