### ISSUE TITLE
ZIPStorageFile performance improvements not fully used

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1558]
**Plaso version:**

plaso-20171118

**Operating system Plaso is running on:**

Fedora 26

**Installation method:**

Manual installation (setup.py from plaso-20171118.tar.gz)

**Description of problem:**

_GetAttributeContainerByIndex does not benefit from the performance improvements of ZIPStorageFile. Instead of using the set of data streams that is kept decompressed, it opens the ZIP every time. This causes a significant delay. 

It seems that the line which needs a change is:

https://github.com/log2timeline/plaso/blob/09abf0cd49a5b4938b382f86962794a0a22888d1/plaso/storage/zip_file.py#L1040

Suggested change:

`data_stream = self._GetSerializedDataStream( container_type, stream_number )`

On a test image, this change causes a significant speed improvement. Full analysis time (all parsers enabled) on a test image changed from 279 minutes to 88 minutes, producing a total of 2305688 events.

**Comment by joachimmetz** [comment]
We need to check carefully some ZIP storage performance features were disabled for causing issues for large data sets.
