### ISSUE TITLE
Syslog parser doesn't work for ChromeOS syslogs

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#156]

**Comment by kiddinn** [comment]
that's because they don't follow the "standard" syslog format... the dates are actual dates, ISO compliant and all.... sample line:

2015-01-01T10:30:20.210234+00:00 INFO kernel: [    0.000000] Initializing foo bar subset

**Comment by jnettesheim** [comment]
I can take a look at this, can you assign to me?
