### ISSUE TITLE
chrome_history plugin failing

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/plaso#1560]
Message : plugin: chrome_history unable to parse SQLite database
                     with error: 'NoneType' object has no attribute 'keys'
      Parser chain : sqlite
Path specification : type: OS, location:
                     /Library/Application Support/Google/Chrome/Default/History

**Comment by joachimmetz** [comment]
Looks like an issue with keys to index mapping work-around needed for unicode compatibility.

**Comment by Onager** [comment]
@aguilajesus and I took a quick look at this yesterday, and https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite.py#L73 looked like a likely culprit, as https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite.py#L68 can return None.

**Comment by aguilajesus** [comment]
I checked and indeed https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite.py#L68 is returning None.

More specific when ParseLastVisitedRow (L318) query its cache to get visit_source https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite_plugins/chrome.py#L363
https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite_plugins/chrome.py#L255

a simple check against row solves the issue.

**Comment by Onager** [comment]
@tomchop who was also looking at Chrome issues

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/338280043
