### ISSUE TITLE
Question:  List of filter attributes?  

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1562]
**Plaso version:**
20171118 release

**Operating system Plaso is running on:**
Ubuntu 16.04

Questions:

Where could I find a list of attributes that can be used with filters?

Where can I find a list of all the fields that can be output via psort.py?  I am looking beyond the -o output list.  I have seen an example on this site where the -o option is not used but rather a list of fields.  The l2tcsv option is nice but I would like to see what else is available.

**Comment by joachimmetz** [comment]
> Where could I find a list of attributes that can be used with filters?

Alas, there is no comprehensive documented list here, yet. The next best thing is to look at the event / event data class definitions e.g. https://github.com/log2timeline/plaso/blob/master/plaso/parsers/winlnk.py#L24

The docstring contains an explanation of the available attributes.

**Comment by mark-hallman** [comment]
Joachim,

Thank you for the info.  I think I can now dig through the code and put together a good list of filter attributes.  I will be happy to share once I have completed it.  

-Mark

**Comment by joachimmetz** [comment]
Mark, thanks that would be useful. I was thinking of generating such a list
from the code (when priorities and time permit).
