### ISSUE TITLE
Question:  $UsnJrnl entires

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1563]
Is there documentation of the methodology used to parse out the $UsnJrnl entries.  This new output can be great in certain circumstances but it can also be overwhelming.  I am seeing 300 - 400% increase in my output due to these entries.

How could I use psort and filters to remove these entries if I want?  Once I have narrowed in a time frame I can then rerun with slice and put them back in.  I think.  ;-0

**Comment by joachimmetz** [comment]
@mark-hallman what specially do you want to know about the methodology? The parser can be found here https://github.com/log2timeline/plaso/blob/master/plaso/parsers/ntfs.py#L306 and the process of parsing `USN_RECORD_V2` is very straight forward

> How could I use psort and filters to remove these entries if I want?

Did you try event filters. Also see: https://github.com/log2timeline/plaso/wiki/Event-Filters
You could skip events with data type 'fs:ntfs:usn_change'

**Comment by mark-hallman** [comment]
Joachim,

Thanks for the info.  I was hoping for more detailed info than that provided in the link you sent.  Good info but I want to really understand what the possibilities are with filters. 

I can see data_types by running psort.py like this:

`psort.py --fields data_type -w additional_fields.csv my_data.dump`

For my image, this gives me 39 data types.  Is there a way to get a complete list of data_types?  

[Plaso_Data_Types.xlsx](https://github.com/log2timeline/plaso/files/1563558/Plaso_Data_Types.xlsx)

Is there a way to list all the available output fields, in addition to the default fields?  

Lastly,  can you add additional fields to a standard output format like "l2tcsv"?

Thanks for all your help.

-Mark

**Comment by joachimmetz** [comment]
Last questions also asked in https://github.com/log2timeline/plaso/issues/1636
