### ISSUE TITLE
Wrong version number string on plaso-20171118

### ISSUE THREAD

**Issue by yukinobu-n** [log2timeline/plaso#1566]
**Plaso version:**

plaso-20171118-amd64

**Operating system Plaso is running on:**

Windows 7 SP1 (64bit)

**Installation method:**

I downloaded [amd64 binary](https://github.com/log2timeline/plaso/releases/download/20171118/plaso-20171118-amd64.zip) (sha1: `d90934f3f68f7ff9fd7b863087d0275f7d6fe4fe`) and I unzipped it to my local folder.

**Description of problem:**

In this version of plaso, it seems the `--version` option not show right version.

Expected:
```
$ ./log2timeline --version
plaso - log2timeline version 20171118
```

Actual:
```
$ ./log2timeline --version
plaso - log2timeline version 20170926
```

**Comment by joachimmetz** [comment]
thx for informing us, maybe something went wrong with the upload. I'll have a look later this week.

**Comment by joachimmetz** [comment]
I've confirmed the issue. I've removed plaso-20171118-amd64.zip. Seeing that we're planning a December release soon we should be releasing a new packaged version as well.

**Comment by yukinobu-n** [comment]
I confirmed the issue has been fixed. Thanks to your kindness.
