### ISSUE TITLE
have data location auto-detection handle data sub directory in site-packages

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#1568]
**Outcome triage:**

Installation of hexdump module on FreeBSD indicates that data location auto-detection gets confused by the data sub directory in site-packages.

**Plaso version:**

20171118

**Operating system Plaso is running on:**

FreeBSD

**Installation method:**

FreeBSD packages
The data files for plaso and artifacts are in the following locations:

```
% find /usr/local/share/artifacts/ /usr/local/share/plaso/
/usr/local/share/artifacts/
/usr/local/share/artifacts/config_files.yaml
/usr/local/share/artifacts/macos.yaml
/usr/local/share/artifacts/antivirus.yaml
/usr/local/share/artifacts/installed_modules.yaml
/usr/local/share/artifacts/unix_common.yaml
/usr/local/share/artifacts/windows.yaml
/usr/local/share/artifacts/ntfs.yaml
/usr/local/share/artifacts/linux_proc.yaml
/usr/local/share/artifacts/webbrowser.yaml
/usr/local/share/artifacts/linux.yaml
/usr/local/share/artifacts/wmi.yaml
/usr/local/share/artifacts/applications.yaml
/usr/local/share/artifacts/kaspersky_careto.yaml
/usr/local/share/artifacts/java.yaml
/usr/local/share/artifacts/cloud_services.yaml
/usr/local/share/artifacts/windows_dll_hijacking.yaml
/usr/local/share/artifacts/legacy.yaml
/usr/local/share/plaso/
/usr/local/share/plaso/signatures.conf
/usr/local/share/plaso/plaso_kibana_example.json
/usr/local/share/plaso/filter_windows.txt
/usr/local/share/plaso/tag_macosx.txt
/usr/local/share/plaso/winevt-rc.db
/usr/local/share/plaso/README
/usr/local/share/plaso/tag_windows.txt
```

**Description of problem:**

I noticed that on one of my hosts,  I had to specify data path or artifact definitions path for plaso to run correctly.
On the problematic host,  hexdump module is installed [https://pypi.python.org/pypi/hexdump](url)
For some reasons,  hexdump installs `/usr/local/lib/python2.7/site-packages/data/hexfile.bin
` and this messes up `data_location` automatic selection.

Maybe `plaso/cli/helpers/data_location.py` should check that a file exists instead of a `data` directory.

**Comment by ant1** [comment]
I don't think it's specific to FreeBSD.  When I remove the hexdump module, automatic data_location works fine again.

**Comment by joachimmetz** [comment]
This is strange since we don't use hexdump in plaso. Does hexdump do anything to `__file__` ?

For more detail on how plaso determines the data location: https://github.com/log2timeline/plaso/blob/master/plaso/cli/helpers/data_location.py

**Comment by ant1** [comment]
I had hexdump installed for reasons unrelated to plaso.

hexdump adds a data directory to /usr/local/lib/python2.7/site-packages/ ,  so this check is successful:

```
      data_location = os.path.dirname(cls._PATH)
      data_location = os.path.dirname(data_location)
      data_location = os.path.dirname(data_location)
      data_location = os.path.dirname(data_location)
...
      data_location_source = os.path.join(data_location, 'data')
...
      elif os.path.exists(data_location_source):
        data_location = data_location_source
```

**Comment by joachimmetz** [comment]
@ant1 So what you're saying is that hexdump is installing a data directory into site-packages which confuses the data location auto-detection. From the plaso we can have a look at making the data location auto-detection resilient against this. However this sounds like a deployment issue on the hexdump side that they deploy data like this instead of using the system default location.

**Comment by ant1** [comment]
Yes, that's exactly what I'm saying.
