### ISSUE TITLE
Remove _GetHostname method from chrome history parser

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1575]
Ref: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite_plugins/chrome.py#L192

Issues:
- This functionality should be in the formatter, if it's needed
- We should be reusing a library to do this, rather than implementing our own version
- We probably don't want to have this "host" field on the event anyway, downstream processing that needs it can extract it if required

**Comment by chimau** [comment]
you can assign this to me

**Comment by Onager** [comment]
Thanks @chimau - let me know if you need a hand.

**Comment by chimau** [comment]
i just finished working on it but for some reason i get a 403 error when i try to pull

**Comment by joachimmetz** [comment]
@chimau what is the feature branch you're trying to create a PR of

**Comment by chimau** [comment]
chrome is the branch name 
chimau@chimau2:~/project/plaso$ git push origin chrome
Username for 'https://github.com': chimau
Password for 'https://chimau@github.com': 
remote: Permission to log2timeline/plaso.git denied to chimau.
fatal: unable to access 'https://github.com/log2timeline/plaso.git/': The requested URL returned error: 403
chimau@chimau2:~/project/plaso$

**Comment by chimau** [comment]
the branch is chrome 
this is the error i get chimau@chimau2:~/project/plaso$ git push origin chrome
Username for 'https://github.com': chimau
Password for 'https://chimau@github.com': 
remote: Permission to log2timeline/plaso.git denied to chimau.
fatal: unable to access 'https://github.com/log2timeline/plaso.git/': The requested URL returned error: 403
chimau@chimau2:~/project/plaso$

**Comment by joachimmetz** [comment]
@chimau I think that with "remove" @Onager meant refactor this to use urllib instead

**Comment by chimau** [comment]
I though  @Onager wanted to remove the host field entirely from the parser as the hostname can be extracted from the URL if needed. if i recall correctly the host field was removed  entirely from the safari plugin too

**Comment by chimau** [comment]
@joachimmetz and @Onager  i didnt get a definite answer if we are removing the host field entirely or using a library instead ?

**Comment by Onager** [comment]
Having looked at this a bit more, I think deleting the _GetHostname method and removing the 'host' attribute from ChromeHistoryPageVisitedEventData is the best option here, since it's not used by any Plaso code, and per https://github.com/log2timeline/plaso/issues/1575#issuecomment-360297738 and https://github.com/log2timeline/plaso/issues/1575#issue-284700908 any downstream code that needs this can extract it from the url attribute anyway.

@joachimmetz Was there some reason you thought this was necessary to keep?

**Comment by joachimmetz** [comment]
> @joachimmetz Was there some reason you thought this was necessary to keep?

largely based on our conversation, that you wanted to move the functionality into formatter.

If we don't need/use it, removing it SGTM.
