### ISSUE TITLE
chrome_cache_parser: add version 2.1 format support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#16]
chrome_cache_parser: add version 2.1 format support
https://code.google.com/p/plaso/issues/detail?id=79

Also look at newer formats

**Comment by joachimmetz** [comment]
```
2015-01-26 13:35:32,747 [ERROR] (Worker_4  ) PID:5227 <chrome_cache> Unable to parse cache entry with error: Unable to parse cache entry with error: expected 4, found 0
```

**Comment by kiddinn** [comment]
Should we split this up in two issues?

a) the enhancement request to add support for version 2.1
b) the "bug" or the unhandled exception that comes up when the parser attempts to parse a 2.1 file format?

**Comment by joachimmetz** [comment]
I opt leave as-is.

**Comment by joachimmetz** [comment]
Related issue: https://github.com/log2timeline/plaso/issues/74

**Comment by joachimmetz** [comment]
@rgayon FYI

**Comment by joachimmetz** [comment]
Closing this issue. The 2.1 format seems to correspond to the 2.0 format based on the test files seen so far. https://github.com/libyal/dtformats/blob/master/documentation/Chrome%20Cache%20file%20format.asciidoc

Will need (test) files that represent these differences.
