### ISSUE TITLE
OS detection failing on dean-mac test image

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1611]
The Dean-mac test image is not being detecting as OSX correctly, and all parsers are being enabled.

**Comment by joachimmetz** [comment]
```
2018-01-03 21:19:08,638 [INFO] (MainProcess) PID:18413 <engine> Preprocessing detected platforms: MacOSX, MacOSX
```

Per https://github.com/log2timeline/plaso/issues/109  fix preprocessor to handle more than one system configuration

**Comment by joachimmetz** [comment]
Issue: preset is not set by parsers_manager.ParsersManager.GetPresetForOperatingSystem in
https://github.com/log2timeline/plaso/blob/master/plaso/cli/extraction_tool.py#L103

Seeing the result of GuessOS is ignore. Adding a small work-around but a more structural fix is needed.

**Comment by joachimmetz** [comment]
I've created https://github.com/log2timeline/plaso/issues/1631

**Comment by joachimmetz** [comment]
Temporary work around in place #1631 for a structural fix
