### ISSUE TITLE
Create documentation for writing syslog plugins

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1623]
Update: adding a parser or plugin documentation
https://github.com/log2timeline/plaso/wiki/How-to-write-a-parser

to explain syslog plugins

**Comment by Onager** [comment]
This is complete: https://github.com/log2timeline/plaso/wiki/How-to-write-a-parser and https://github.com/log2timeline/plaso/wiki/How-to-write-a-Syslog-plugin
