### ISSUE TITLE
Redesign and simplify storage interface

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1624]
BaseStore defines methods that are duplicated in StorageWriter (Add*) and StorageReader (Get*). Look into removing these methods from BaseStore.

**Comment by joachimmetz** [comment]
Also let's consider a "SQL builder" (or equiv) to keep the SQL definitions in a single place

**Comment by Onager** [comment]
Sure, but that's a separate issue. The BaseStore and Writer/Reader interface shouldn't care about SQL.

**Comment by joachimmetz** [comment]
Storage interface has be simplified for https://github.com/log2timeline/plaso/issues/3024. More can be done but addressing Redis support first
