### ISSUE TITLE
Deprecate usage of knowledge_base.platform in favor of per source path specification system configuration

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1631]
Deprecate usage of knowledge_base.platform in favor of per source path specification system configuration

* [x] ~~Deprecate usage of knowledge_base.platform in favor of operating_system value~~
  * ~~https://codereview.appspot.com/331540043/~~

**Comment by joachimmetz** [comment]
related https://github.com/log2timeline/plaso/issues/109

**Comment by Onager** [comment]
Is this really feasible for the January release?

**Comment by joachimmetz** [comment]
Maybe, let me have a look later this week.

**Comment by joachimmetz** [comment]
Step 1. https://codereview.appspot.com/331540043/

**Comment by joachimmetz** [comment]
Moved additional work to https://github.com/log2timeline/plaso/issues/1651
