### ISSUE TITLE
Set up autobuilds for Plaso docker container

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1641]
Ref: https://docs.docker.com/docker-hub/builds/

Assigning to @rgayon because he's a Docker expert.

**Comment by Onager** [comment]
This was done, we still need to updated docs and procedures etc.

**Comment by joachimmetz** [comment]
@Onager could you specify what needs to be done in this issue (also check for overlap with other docker related issues)

**Comment by Onager** [comment]
Autobuilds are set up, but don't work correctly due to the way we do releases. Specifically, the autobuild is triggered when a new git tag is created, but no packages with that version exist at that time. We would need to automate building in a different way than using autobuilds.
