### ISSUE TITLE
update elasticsearch and timesketch output modules to support elasticsearch >= 6.0.0

### ISSUE THREAD

**Issue by infosecjosh** [log2timeline/plaso#1653]
Plaso version: 20180111
Ubuntu 16.04

Not the operating system of the image/files you're trying to analyze. No issue with analysis

python setup.py install

**Description of problem:**

psort output to Elastic 6.1 creates indices but data does not get inserted into index.  No errors from psort.py 

elasticsearch-py 6.1 is installed.

**Comment by joachimmetz** [comment]
@infosecjosh there are 2 output formats (modules) that use elastic search which one are you using `elastic` or `timesketch` ?

**Comment by infosecjosh** [comment]
I tried elastic.  I will try timesketch and report back.

**Comment by infosecjosh** [comment]
I tried timesketch as well.  No luck.

**Comment by tobraha** [comment]
Starting in version 6 of ElasticSearch, [mapping types are removed](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_custom_type_field).  This is somewhat related to #1716.  

See this [note on mapping parameters](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-index.html).  Though I haven't fully tested this, it should only affect elastic output; timesketch output uses a different mapping.  Not sure why that's disabled for you @infosecjosh.

It also doesn't seem to like the 'ignore_above' parameter:
`"status":400,
"error":{
"type":"mapper_parsing_exception",
"reason":"Mapping definition for [fields] has unsupported parameters:  [ignore_above : 10922]`

I was able to get it working by removing the 'index' and 'ignore_above' parameters altogether, though I'm not certain that's how it should be going forward.

**Comment by joachimmetz** [comment]
blocked by https://github.com/log2timeline/plaso/issues/1828

**Comment by joachimmetz** [comment]
We currently support elasticsearch >=5.4.0,< 6.0.0

**Comment by joachimmetz** [comment]
@berggren any planned timeline for timesketch moving to >= 6.0.0 we should align with?

**Comment by berggren** [comment]
Later this Q, but before summer :)

The complexity is not in the code, it is breaking changes in ES that renders all current 5.x installs broken. I'm working on a migration plan that need to cover most use-cases.

**Comment by berggren** [comment]
^-- the supporting code is already written in Timesketch. I'm just not pushing it by default as it will brake many installs if there is no migration support done.

**Comment by joachimmetz** [comment]
Per conversation with @berggren we need to align this with the timesketch changes, hence marked as blocked and we are aiming for June/July (best-effort).

**Comment by MariasStory** [comment]
elasticsearch >= 5.4.0,<= 5.5.1

**Comment by joachimmetz** [comment]
@MariasStory what is your question? what that particular comment means?

**Comment by MariasStory** [comment]
Hi @joachimmetz this one is from requirements. I don't understand why would plaso need elasticsearch 5.
I am frustrated with such development. If you are to require elasticsearch, please make sure that use support the last stable version.
I don't need to export to elasticsearch, just collect the artifacts to plaso file and export them to csv. Why do I need to install elasticsearch 5? 
I have version 6 on the server, it is a standard version for the system. Do I really have to downgrade it?
Please concentrate on the feature that is needed for core functionality and make it work with any version of elasticsearch or use alternative db.
I am new to the project, but I like the idea of such a parser and already recommended the project to several other developers. Please don't spoil my reputation.
Do you need help in getting this one working with elasticsearch 6? Please define what has to be done.

**Comment by joachimmetz** [comment]
@MariasStory 

> I don't understand why would plaso need elasticsearch 5.

Because that is what timesketch currently supports and upgrading to 6 will take time and effort that we currently do not have.

The development of plaso as open source is best effort. If you feel is not fast enough I recommend getting actively involved and helping out.

* You can try upgrading plaso to elasticsearh 6 yourself and create a PR that proposes the necessary changes
* Help with timesketch to migrate to elasticsearch 6 also see https://github.com/google/timesketch/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+elasticsearch

**Comment by Onager** [comment]
Fixed inhttps://github.com/log2timeline/plaso/pull/2087
