### ISSUE TITLE
refactor dpkg.log parser to support plugins

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1656]
refactor dpkg.log parser to support plugins

**Comment by joachimmetz** [comment]
Information about dpkg.log
http://manpages.ubuntu.com/manpages/xenial/man1/dpkg.1.html

**Comment by joachimmetz** [comment]
dpkg.log
```
2009-02-25 11:45:23 conffile /etc/X11/Xsession keep
```

exim 4 mainlog
```
2011-02-06 15:21:02 SMTP command timeout on connection from [192.168.56.1]
```

**Comment by Onager** [comment]
These logs are similar, but don't seem related. An exim log isn't a "kind of" dpkg log. https://www.exim.org/exim-html-current/doc/html/spec_html/ch-log_files.html indicates that different options will change the format of the exim log (log_timezone, for example).

**Comment by joachimmetz** [comment]
so the high-level though here is to have a base level parser that is invoked based on the date time format and then based on the format and contents of the rest of the log line provides a best fit, instead of parsing the same log with multiple parsers.

**Comment by joachimmetz** [comment]
Closing this for now
