### ISSUE TITLE
incorrect path in SAM Registry parser plugin filter

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1660]
**Description of problem:**

When running log2timeline sam_users Registry plugin didn't create events.

**Plaso version:**

20171231

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**
GIFT

**Debug output/tracebacks:**

2018-01-10T05:44:26.926135+00:00,Content Modification Time,REG,UNKNOWN,[HKEY_LOCAL_MACHINE\SAM\SAM\Domains\Account] F: [REG_BINARY] V: [REG_BINARY],winreg/winreg_default,OS:/mnt/Windows/System32/config/SAM,-

**Source data:**

Source file available to developers.

**Comment by Onager** [comment]
Looks like a problem in dfwinreg, calling `list(root_key.RecurseKeys())` gives the following sequence:
0: u'HKEY_LOCAL_MACHINE\\SAM'
1: u'HKEY_LOCAL_MACHINE\\SAM\\SAM'
2: u'HKEY_LOCAL_MACHINE\\SAM\\SAM\\Domains'
etc.

**Comment by Onager** [comment]
Possibly a problem in pyregf, not dfwinreg. A breakpoint here: https://github.com/log2timeline/dfwinreg/blob/master/dfwinreg/regf.py#L194 has:

```
self._key_path = u'HKEY_LOCAL_MACHINE\\SAM'
pyregf_key.name = u'SAM'
key_path = u'HKEY_LOCAL_MACHINE\\SAM\\SAM'
```

So it looks like SAM is being reported as its own subkey, which is not right.

**Comment by Onager** [comment]
Test also has the doubled SAM, was introduced: https://github.com/log2timeline/plaso/commit/eadf8e86bf6201087f4f5acb0edf30c4d9e72418#diff-5f822bddef9d33291b03a965f8a9df6aR27

**Comment by Onager** [comment]
@joachimmetz Is this path intentional?

**Comment by joachimmetz** [comment]
I'll have a look when time permits

**Comment by joachimmetz** [comment]
> So it looks like SAM is being reported as its own subkey, which is not right.

This is correct, see regedit or https://answers.microsoft.com/en-us/windows/forum/windows_7-security/windows-7-locked-after-scam-call-syskey/5933abb9-4f1b-46cf-bc6a-f81ed33c0a85?db=5&auth=1

**Comment by joachimmetz** [comment]
Working as intended

**Comment by joachimmetz** [comment]
Per: https://codereview.appspot.com/339260043/ the path in the filter is incorrect.
