### ISSUE TITLE
Refactor formatter tests

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1669]
Formatters are clearly closely tied to the events produced by the parsers, but tests for formatters would seem to logically live in the formatter tests. 

Currently, the GetMessages() methods of formatters are tested in parser tests, with todos for adding GetMessages() also added to formatter tests.

**Comment by joachimmetz** [comment]
one historical reason to keep them with the parsers was that it was easier to test different messages without having reproduce the same logic in the formatter. Moving it to the formatter is likely the better option but we need to do this for the entire codebase.

**Comment by joachimmetz** [comment]
With event formatters moving to configurations most of the formatter unittest files will be removed.
Having a message formatting test in the parser for now seems the best place.

@Onager thoughts? Should we close this issue?

**Comment by joachimmetz** [comment]
No response closing issue.
