### ISSUE TITLE
Improve FSEvents parser

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1683]
- [ ] Produce additional documentation on flag meanings/values
- [ ] Make message string more useful, separating type and event flags

**Comment by joachimmetz** [comment]
Rough WIP documentation https://github.com/libyal/dtformats/blob/master/documentation/MacOS%20File%20System%20Events%20Disk%20Log%20Stream%20format.asciidoc

**Comment by joachimmetz** [comment]
Related https://opensource.apple.com/source/xnu/xnu-2050.22.13/bsd/sys/fsevents.h

**Comment by joachimmetz** [comment]
Closing issue since this is now documented and unclear what is meant with "separating type and event flags" since there are only flags.
