### ISSUE TITLE
Pinfo JSON output broken

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1687]
Parsers counter output should look like this:
```
    "parsers_counter": {
      "__type__": "collections.Counter",
      "hachoir": 8,
      "pls_recall": 2,
      "filestat": 383066,
      "utmp": 58,
      "syslog": 11827,
      "pe": 2,
      "total": 402039,
      "dpkg": 7076
    },
```

But looks like this:
```
    "parsers_counter": {
      "total": 402029,
      "__type__": "collections.Counter",
      "N/A": 402029
    },
```

**Comment by Onager** [comment]
This is probably due to the event data split, now that I think about it - events no longer have a data_type to examine.

**Comment by Onager** [comment]
https://github.com/log2timeline/plaso/blob/294d4927a98f9eb39d4e38182575b2047eb7bdd5/plaso/storage/interface.py#L1059 looks like part of the problem, counters aren't being updated as expected.

**Comment by Onager** [comment]
I think the best short term fix (bearing in mind #1658 and probably further, related changes will affect this) is to add the parser chain information to the event (it's already stored on the event data).

I'm not immediately sure we need to set `parser` on both the event and event_data, but I suspect so. We want to be able to trace which parser/plugin produced these objects.

**Comment by joachimmetz** [comment]
merged changes proposed in https://codereview.appspot.com/338420043/

**Comment by Onager** [comment]
Fix in https://codereview.appspot.com/338420043/ wasn't complete.

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/05a88037e5adc662f4b588b9bed8e9afa4b78451
