### ISSUE TITLE
log2timeline: multiple issues with multi processing and IPC

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#169]
log2timeline: occasionally gets stuck with "Waiting for storage writer".
```
[INFO] (MainProcess) PID:21754 <multi_process> Waiting for storage writer.
```

Current challenge is to find a reproducible test case.

**Comment by joachimmetz** [comment]
```
[INFO] Extraction workers stopped.
[INFO] Waiting for storage writer.
[INFO] [Storage] Closing the storage, number of events processed: 46827
[INFO] Storage writer stopped.
[INFO] Processing completed.
```
Not terminating with 2 processes remaining

**Comment by joachimmetz** [comment]
https://docs.python.org/2/library/multiprocessing.html#multiprocessing-programming

**Comment by joachimmetz** [comment]
Also issue with missing file name.
```
INFO] Worker_0 (PID: 27397) - events extracted: 2220 - file:  - running: True <running>
```

**Comment by joachimmetz** [comment]
Improve solution:

* have foreman monitor collector and storage writer process as well

**Comment by joachimmetz** [comment]
Process appears to still get stuck:
```
[WARNING] Terminating worker process: Worker_5 (PID: 26016)
[INFO] Waiting for storage writer.
[WARNING] Forcing termination of storage writer (PID: 26006)
[INFO] Storage writer stopped.
[INFO] Processing completed.
```

**Comment by joachimmetz** [comment]
It appear multiprocessing.Queue is not FIFO, and its get() method will block if the queue is empty. Some changes to handle this behavior: https://codereview.appspot.com/225680044/

**Comment by kiddinn** [comment]
Seems to still be an issue for some cases, https://codereview.appspot.com/224610044/ sent in as well, seems to at least fix the issue regarding the test images I had that I could reproduce this on.

**Comment by joachimmetz** [comment]
Observed behavior:
```
[INFO] Worker_3 (PID: 16947) - events extracted: 53970 - file: /Windows/System32/config/COMPONENTS - running: True <sleeping>
[INFO] Worker_4 (PID: 16949) - events extracted: 58423 - file: /Windows/System32/drivers/b57nd60a.sys - running: True <sleeping>
[INFO] Worker_5 (PID: 16951) - events extracted: 69976 - file: /Windows/System32/config/SOFTWARE - running: True <sleeping>
```

Workers remain sleeping for a long time.

**Comment by joachimmetz** [comment]
Keyboard interrupt is not cleanly handled now.

**Comment by joachimmetz** [comment]
Still an issue if a worker is misbehaving the process does not terminate.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/230620043/

**Comment by joachimmetz** [comment]
Still an issue with the main process not terminating. The cause is likely the python queue locking: http://stackoverflow.com/questions/21349850/multiprocessing-queue-deadlocks-after-reader-process-death

**Comment by joachimmetz** [comment]
Improve "worker idle abort" logic, currently possible that the workers are processing for 5 mins without extracting event objects e.g. when only very specific parsers are enabled. Make sure not to abort prematurely.

**Comment by joachimmetz** [comment]
Parser error queue disabled for now per: https://github.com/log2timeline/plaso/commit/7853aafbe6e19f6a2f70e5438fc6ee2d7017176d

**Comment by joachimmetz** [comment]
Testing indicates still an issue on Windows XP

**Comment by joachimmetz** [comment]
The abort path is still not always handled cleanly.

**Comment by joachimmetz** [comment]
Check handling of no collector input.

**Comment by joachimmetz** [comment]
Closing this one in favor of #153
