### ISSUE TITLE
Yara analyzer does not start

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1702]
**Description of problem:**

The yara analyzer does not start. When running log2timeline.py with a working yara rule file, the output does not contain a yara_match hit. This seems to be caused by the command line argument providing the yara rules path not being parsed. When specifying a non-existing or erroneous rule file, log2timeline.py does not report an error.

**Command line and arguments:**

`log2timeline.py --yara_rules rule.yara test.plaso source`

**Source data:**

In my test case, the source folder contains a single PNG image. The yara rule contains a simple PNG signature.

**Plaso version:**

plaso-20180127

**Operating system Plaso is running on:**

Fedora 26

**Installation method:**

Installed from https://forensics.cert.org/ repository.

**Comment by Onager** [comment]
It looks like there's no call to parse the yara arguments in log2timeline_tool.py

**Comment by Onager** [comment]
There was never a call to parse yara options when the option parsing was refactored in https://github.com/log2timeline/plaso/pull/1259

**Comment by Onager** [comment]
This was fixed in 79dc824
