### ISSUE TITLE
psort.py ignores --worker_memory_limit

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#1710]
**Description of problem:**

The `--worker_memory_limit` command line option is ignored by `psort.py`. When disabling the limit (by setting the limit to 0), `psort.py` still kills an analyzer which consumes more than 2GB of memory. The same happens when specifying a limit of (for instance) 3GB. 

**Command line and arguments:**

`psort.py --worker_memory_limit 0 -o null --analysis nsrlsvr --nsrlsvr-host nsrl.local test.plaso`

**Plaso version:**

plaso-20180127

**Operating system Plaso is running on:**

Fedora 26

**Installation method:**

Installed from https://forensics.cert.org/ repository.

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/bfb59324ee9895646ce53f6022d75508c6c59b7e
