### ISSUE TITLE
Enable Python 3 in tox tests

### ISSUE THREAD

**Issue by puccia** [log2timeline/plaso#1719]
**Description of problem:**

Tox is set up to run a Python 3.4 environment, but the testing command is running Python 2.7.

**Source data:**

See pull request #1718. The Tox test run by Travis is passing, but inspecting the log shows:

py34 runtests: PYTHONHASHSEED='2230121155'
py34 runtests: commands[0] | ./run_tests.py
Using Python version sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
testAddProcessingOptions (cli.log2timeline_tool.Log2TimelineToolTest)
Tests the AddProcessingOptions function. ... ok

[...]

PR #1698 solves the problem, but of course the unit tests (rightfully) appear to be broken.

**Plaso version:**

HEAD on the hosted Travis instance.

**Comment by Onager** [comment]
I discussed this with @joachimmetz briefly today - let's enable the python3 tests ala #1698, but configure Travis to not fail for the known broken tests.

**Comment by joachimmetz** [comment]
This has been fixed (https://codereview.appspot.com/341040043) though Python 3 tests are still failing due to missing binplist dependency (https://travis-ci.org/log2timeline/plaso/jobs/361106791#L496).

Closing this issue.
