### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by andy5876** [log2timeline/plaso#1720]
**Description of problem:**

sqlite error (database is locked) when running log2timeline.py

**Command line and arguments:**

log2timeline.py /path/plaso.plaso /mnt/ewf/ewf1

**Plaso version:**

20180127

**Operating system Plaso is running on:**

Fedora27

**Installation method:**

* installed from CERT Forensics Repo for Fedora 27 (https://forensics.cert.org/)

**Debug output/tracebacks:**

Traceback (most recent call last):
  File "/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 487, in ExtractEventsFromSources
    worker_memory_limit=self._worker_memory_limit)
  File "/usr/lib/python2.7/site-packages/plaso/multi_processing/task_engine.py", line 819, in ProcessSources
    storage_writer.Open()
  File "/usr/lib/python2.7/site-packages/plaso/storage/interface.py", line 1340, in Open
    self._storage_file.Open(path=self._output_file, read_only=False)
  File "/usr/lib/python2.7/site-packages/plaso/storage/sqlite/sqlite_file.py", line 946, in Open
    self._WriteStorageMetadata()
  File "/usr/lib/python2.7/site-packages/plaso/storage/sqlite/sqlite_file.py", line 460, in _WriteStorageMetadata
    self._cursor.execute(self._CREATE_METADATA_TABLE_QUERY)
sqlite3.OperationalError: database is locked

**Comment by Onager** [comment]
@andy5876 to clarify, this happened at log2timeline.py startup, correct? And there's nothing else you can think of that might have the file open at the same time? And was this appending to an existing storage file, or creating a new one?

**Comment by andy5876** [comment]
Hi Onager. yes, so it starts up and displays the workers list, but then immediately calls this error. I have rebooted the machine to try and overcome file lock issues and have tried on new and existing storage files.

**Comment by andy5876** [comment]
Ok, so previously trying to write the storage file to a share mounted with CIFS, which I do have write permissions for. If i write to local disk it does not throw this error

**Comment by Onager** [comment]
Hey @andy5876 - we've seen similar issues where some other process on the file server or another system are checking the file for some reason (AV scan, indexing service, DLP thing) and Plaso can't access it. We could try being a little more tenacious about retrying queries that fail for this reason, but I don't know how much that would help.

**Comment by joachimmetz** [comment]
No response from original reporter, issue has gone stale, closing.
