### ISSUE TITLE
Add registry plugin for parsing the "bam" key

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1734]
References:

https://padawan-4n6.hatenablog.com/entry/2018/02/22/131110
https://twitter.com/Requiem_fr/status/967880724400541696
https://thisweekin4n6.com/2018/02/25/week-8-2018/

**Comment by js-forensic** [comment]
@joachimmetz I'll pick this one up.

**Comment by joachimmetz** [comment]
@js-forensic great thanks, assigned to you. I think you have the access now to assign issues to yourself as well.
