### ISSUE TITLE
safari sqlite plugins not called

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#1736]
I have noticed that the safari sqlite plugins are not being imported in the __init__.py file. This causes them to never be registered when running log2timeline.

**Comment by Onager** [comment]
Thanks for the report, I'll fix this now.

**Comment by odibrowne** [comment]
Thank you

Would it also be possible to put in support fro yahoo search terms in the
analysis_browser plugin.


Regards

Alan

**Comment by Onager** [comment]
Sure, I'll open a new issue for that.

**Comment by Onager** [comment]
This was fixed in https://github.com/log2timeline/plaso/commit/bfb59324ee9895646ce53f6022d75508c6c59b7e
