### ISSUE TITLE
Add Yahoo search terms to browser_search analysis plugin

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1743]
See https://github.com/log2timeline/plaso/issues/1736. This should be pretty straightforward once we have some sample URLs.

**Comment by kiddinn** [comment]
https://search.yahoo.com/search?p=foobar&fr=yfp-t&fp=1&toggle=1&cop=mss&ei=UTF-8

https://search.yahoo.com/search;_ylt=AwrE<LONG_VALUE>g--?p=stuff+bar&fr2=sb-top&fr=yfp-t&fp=1

That is, the option is "p=SEARCH_STRING"

**Comment by kiddinn** [comment]
done
