### ISSUE TITLE
Support for event value processing during formatting

### ISSUE THREAD

**Issue by puccia** [log2timeline/plaso#1744]
Currently formatters must override interface methods, and duplicate code, when they need to preprocess event values in order to make them human-readable, or just more amenable to display in event strings.

It could be useful to support this use case as part of the interface. (I will add an example after committing the Trend Micro parser code.)

**Comment by joachimmetz** [comment]
We are moving towards configuration driven formatters and formatting helpers. Closing issue, reopen if example is still relevant.
