### ISSUE TITLE
New Google Chrome schema observed in version 65.0.3325.162

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/plaso#1758]
**Description of problem:**
it seems Chrome 65.0.3325.162 added a few default values into History's schema thus, it breaks our current check for [_SCHEMA_63](https://github.com/log2timeline/plaso/blob/895e249feada713a1e4d60c753d5c20571c6f2a8/plaso/parsers/sqlite_plugins/chrome.py#L677)

**Source data:**
Chrome 65.0.3325.162 on OSX 10.13.3

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/334590043/
