### ISSUE TITLE
Make service analysis plugin tests faster

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#176]
They presently do a full parse of a registry hive, which takes a while.

**Comment by Onager** [comment]
Causing problems on Travis.

**Comment by joachimmetz** [comment]
Bumped to next release

**Comment by joachimmetz** [comment]
Unlikely to be implemented before Jan 25, bumping release

**Comment by Onager** [comment]
Unlikely to make release, removing from milestone.

**Comment by joachimmetz** [comment]
analysis plugin has been removed
