### ISSUE TITLE
sql4n6 output missing event_object on line 233

### ISSUE THREAD

**Issue by jasonblanks** [log2timeline/plaso#177]
format_variables = self._output_mediator.GetFormatStringAttributeNames()
should be:
format_variables = self._output_mediator.GetFormatStringAttributeNames(event_object)

also, could just be me but with a fresh git clone, json_out_test is erroring out run_tests for me.

**Comment by joachimmetz** [comment]
Are you running the latest dvfvs?
https://github.com/log2timeline/dfvfs/releases/tag/20150408
```
Release of version 20150408. Warning breaks JSON serialization in plaso.
````

There is already a CL in the pipeline but reviewer is very busy: https://codereview.appspot.com/229760043/

**Comment by joachimmetz** [comment]
Regarding sql4n6 @dnides can you add a test or create some format documentation so we can prevent breakage of this output module. If not I'll have to disable this output for now.

**Comment by dnides** [comment]
Yes Jason is helping with that. Will get it done.

**Comment by joachimmetz** [comment]
Great, thx

**Comment by joachimmetz** [comment]
So CL 229760043 is now in

**Comment by joachimmetz** [comment]
Related: https://github.com/log2timeline/plaso/issues/123

**Comment by joachimmetz** [comment]
I assume this is fixed now, reopen if not.
