### ISSUE TITLE
Make --partition argument accept a list or "all"

### ISSUE THREAD

**Issue by f-s-p** [log2timeline/plaso#180]
The log2timeline --vss_stores option takes a comma-separated list of store numbers or the word "all", while --partition only allows a single number as its argument.  It would be helpful, especially for automation, for the --partition option to accept a comma-separated list as well as the word "all" to indicate the desire to process all partitions found.

**Comment by joachimmetz** [comment]
Not only partitions but multiple volume support e.g. LVM is what I want to add: https://github.com/log2timeline/plaso/issues/109. To support this more changes are needed to the collection process adding just the "all" keyword is not going to work. Closing since this is a duplicate.
