### ISSUE TITLE
Recent introduced style changes need clarification

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1813]
The recent introduced style changes regarding `return None` need more clarification. I've added information about generators and functions/methods that do not return values. However we need to say something about functions/methods that return multiple values should they use `return None` or `return None, ...`

https://github.com/log2timeline/plaso/wiki/Style-guide#return-statements

**Comment by Onager** [comment]
This is for developer documentation, and isn't required for the release, removing from milestone,

**Comment by Onager** [comment]
Update style guide to indicate that `return None, None...` is the preferred returned type.
