### ISSUE TITLE
Missing timesketch dependencies ?

### ISSUE THREAD

**Issue by adrastee** [log2timeline/plaso#1825]
**Description of problem:**
From documention of psort : http://plaso.readthedocs.io/en/latest/Using-psort/
> If you are missing any optional dependencies not all output modules may be available, which would be displayed by the -o list switch:

i guess I am missing timesketch dependencies. How do I install them ?

**Command line and arguments:**
psort.exe -o timesketch -w  ts file.plaso
**ERROR: Unsupported output format: timesketch.**

**Plaso version:**
plaso-20180127-amd64

**Operating system Plaso is running on:**
Windows x64

**Installation method:**
Release .zip

**Comment by adrastee** [comment]
Ok thanks !
"I'll have a look if we can make this a bit more clear" maybe just after the "If you are missing any optional dependencies not all output modules may be available"

**Comment by adrastee** [comment]
MSI "pyelasticsearch-1.4.1.win-amd64.msi" installed, but the output is still the same:
ERROR: Unsupported output format: timesketch.

**Comment by joachimmetz** [comment]
This is likely related to the pyinstaller packaged version. I'll chat with @Onager if we should add pyelasticsearch to the next release.

**Comment by joachimmetz** [comment]
@adrastee at the moment it appears you'll also need timesketch and flask installed

https://github.com/log2timeline/plaso/blob/master/plaso/output/timesketch_out.py#L10

```
try:
  from flask import current_app
  import timesketch
  from timesketch.models import db_session
  from timesketch.models.sketch import SearchIndex
  from timesketch.models.user import User
except ImportError:
  timesketch = None
```

**Comment by berggren** [comment]
To enable the timeksketch output module you need timesketch installed and configured, as documented here: https://github.com/google/timesketch/blob/master/docs/Installation.md

If you have a Timesketch server and want to import a plaso file you probably want to use the timesketch client library here: https://github.com/google/timesketch/tree/master/api_client/python/timesketch_api_client

I'm working on a light weight CLI client for end users to use, tracked here: https://github.com/google/timesketch/issues/590

To export to plain Elasticsearch, you need to use the "elastic" output option in psort. To enable this module you need to install the python package "elasticsearch".

NOTE: We support ES 5.x only at this time.

**Comment by joachimmetz** [comment]
Stared with merging documentation about dependencies: https://github.com/log2timeline/plaso/wiki/Dependencies

Added link to: https://github.com/google/timesketch/blob/master/docs/Installation.md

**Comment by joachimmetz** [comment]
Closing issue, seeing initial question is answered.
