### ISSUE TITLE
add a timeout to the bulk call for elasticsearch output module

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#1826]
add a timeout to the bulk call for elastic

https://github.com/log2timeline/plaso/blob/84aefcbb4cb619923f66d70be843e10ab2ac6a79/plaso/output/elastic.py

```
 self.client.bulk(
          index=self._index, doc_type=self._doc_type, body=self._events)
```

Please change to:
```
 self.client.bulk(
          index=self._index, doc_type=self._doc_type, body=self._events, request_timeout=300)
```

**Comment by MariasStory** [comment]
Reference:
https://github.com/google/timesketch/issues/121
I had this issue on one machine, but not on another.

Basically, the request_timeout for elastic search bulk insert is too small in this case.

**Comment by joachimmetz** [comment]
Ack I've updated the issue to reflect this request

**Comment by joachimmetz** [comment]
Will include this into https://github.com/log2timeline/plaso/issues/1864

**Comment by joachimmetz** [comment]
API documentation says the name of the kwargs is timeout
http://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.bulk
