### ISSUE TITLE
Add systemd binary log parser

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#184]
Systemd replaces upstart in Ubuntu starting with 15.04, as well as Debian from Jessie. This looks like a reasonable reference on the file format: http://www.freedesktop.org/wiki/Software/systemd/journal-files/

**Comment by rgayon** [comment]
Some comments on this:
https://github.com/systemd/python-systemd provides python bindings for reading a systemd journal file. It builds upon  libsystemd-journal0. Unfortunately, the d_journal_open_files() call for opening specific journal files was implemented in v205. So to parse offline journal files, libsystemd-journal0 >= v205 is needed. Ubuntu 14.04 shipps 204.

**Comment by Onager** [comment]
Can we build libsystemd-journal for OSX and Windows?

**Comment by rgayon** [comment]
We don't need to, the format actually allows easy parsing of all events. CL pending =)

**Comment by Onager** [comment]
@rgayon This was completed in https://github.com/log2timeline/plaso/commit/72d6ed3e223dfc21646ee1f239bf543351a9d0f2 correct? Is there anything more to do?

**Comment by Onager** [comment]
Ping for @rgayon

**Comment by rgayon** [comment]
@Onager : indeed.
