### ISSUE TITLE
Missing dependencies in the documentation

### ISSUE THREAD

**Issue by oneeyeman1** [log2timeline/plaso#186]
The documentation that is available on https://github.com/log2timeline/plaso/wiki/Dependencies-Windows is missing artifacts and pefile

**Comment by joachimmetz** [comment]
Thanks for letting us know. FYI more documentation updating is needed: https://github.com/log2timeline/plaso/issues/114. I'll address the missing dependencies.

**Comment by joachimmetz** [comment]
Issue addressed with the note that documentation is still WIP.
