### ISSUE TITLE
Move common elasticsearch and timesketch output modules functionality into base class

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1864]
Currently the elasticsearch and timesketch output modules duplicate functionality, move this into a shared base class

* ~~refactor ElasticSearchHelper into a base output module?~~
* ~~add time out https://github.com/log2timeline/plaso/issues/1826~~
* move the functionality to configure the logger into a method?
* add unit tests, use fake/test implementation of output module for testing
* add connectivity check (similar to Viper)

**Comment by joachimmetz** [comment]
WIP: https://github.com/joachimmetz/plaso/tree/elasticsearch2

**Comment by berggren** [comment]
FYI: The timesketch module uses the ElasticSearchHelper base/helper class from the elastic module already. All common code should go into that class.
