### ISSUE TITLE
psort --help points to non existing https://github.com/log2timeline/plaso/wiki/Filters

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1870]
**Description of problem:**
Please describe the problem in as much detail as possible.
What does the tool not do that it should? What would you like it to do?

**Command line and arguments:**

python tools/psort.py --help

**Source data:**

N/A

**Plaso version:**

python tools/psort.py --version
plaso - psort version 20180501

**Operating system Plaso is running on:**

Linux

**Installation method:**

git clone https://github.com/log2timeline/plaso/

**Debug output/tracebacks:**

N/A

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/342130043/
