### ISSUE TITLE
Feature Request: Parse chrome's  Web Data sqlite DB

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#1875]

**Comment by rgayon** [comment]
not really.
I've just sqlite'd  this table there
CREATE TABLE autofill (name VARCHAR, value VARCHAR, value_lower VARCHAR, date_created INTEGER DEFAULT 0, date_last_used INTEGER DEFAULT 0, count INTEGER DEFAULT 1, PRIMARY KEY (name, value));

**Comment by rgayon** [comment]
I expect code to be there
https://chromium.googlesource.com/chromium/src/+/master/components/autofill/core/browser/webdata

**Comment by Onager** [comment]
Not going to make the August release, moving to September
