### ISSUE TITLE
Question:  Tagging - What happens when an event meets multiple conditions?

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1876]
When using a tagging file with psort,  what happens when the event meets more than one rule in the tagging file? 

1.  When there is more than one condition met within the same tag label, does processing stop and move on to the next tag label,  still processing the same event?
2. When there is a hit on any condition within the tagging file,  does processing jump to the next event or does processing move on the next tag, still processing the same row?

Thanks!

**Comment by joachimmetz** [comment]
@mark-hallman 

> When there is more than one condition met within the same tag label, does processing stop and move on to the next tag label, still processing the same event?

The [tagging analysis plugin](https://github.com/log2timeline/plaso/blob/master/plaso/analysis/tagging.py) should apply all labels to tag the event.

> When there is a hit on any condition within the tagging file, does processing jump to the next event or does processing move on the next tag, still processing the same row?

the labels are applied on a per-event basis, so every event is analyzed (or processed in your terminology).

**Comment by joachimmetz** [comment]
Closing issue, questions appear to be answered.
