### ISSUE TITLE
elasticsearch output module: add option to load a custom mappings file 

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1879]
Per https://github.com/log2timeline/plaso/issues/1156 add an option to load a custom mappings file (JSON) for the elasticsearch output module.

Consider how to test this:
* e.g. add ES connectivity test that tests the mappings as well?

**Comment by Onager** [comment]
Not going to make the June release, bumping to next release.

**Comment by Onager** [comment]
Not making September release, removing milestone.

**Comment by goorgoorlou** [comment]
Hi,
Will this feature be added in the next milestone (>Nov 2018)?  (As the problem of #1156 still exist).
Thank you!

**Comment by joachimmetz** [comment]
resurfacing this since it is also needed to be able to combine ES and TS output modules
