### ISSUE TITLE
Failed to execute script psteal

### ISSUE THREAD

**Issue by imsdala** [log2timeline/plaso#1882]
**Description of problem:**
PID 16924 <zeromq_queue> Queue main task queue responder exiting.
Process complete

Traceback most recent calls:
ValueError: Unknown format code 'd' for object of type 'unicode'
[16924] Failed to execute script psteal

It had been running for several hours with 15 different workers.
Any ideas? I am located in Sweden, perhaps some error with unicode?

**Command line and arguments:**

psteal.exe --source evidence.e01 -o xlsx output.csv -z Europe/Amsterdam

**Source data:**

A E01-evidence file with WIN 10, approx 500gb.

**Plaso version:**

Plaso 20180127

**Operating system Plaso is running on:**

Windows 10 x64

**Installation method:**

For example:
* installed from [GiFT PPA][https://launchpad.net/~gift] stable track
* installed from [GiFT COPR][https://copr.fedorainfracloud.org/coprs/g/gift/] stable track
* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch
* built using [l2devtools][https://github.com/log2timeline/l2tdevtools]
* other, namely ...

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://github.com/log2timeline/plaso/wiki/Troubleshooting#producing-debug-logs]

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Comment by Onager** [comment]
Thanks for report. I've been investigating a similar issue and found a (recently fixed) bug in dfVFS. Is there any more of the stack trace available, before `ValueError: Unknown format code 'd' for object of type 'unicode'`?

**Comment by Onager** [comment]
No reply from reporter, and this looks like it might have been related to the issue fixed in https://github.com/log2timeline/dfvfs/commit/d2295590823fc604d63802b80841f33e6e8de194
