### ISSUE TITLE
Plugin to parse/analyse Windows 10 Timeline database

### ISSUE THREAD

**Issue by pstirparo** [log2timeline/plaso#1885]
Develop a plugin to analyse Windows 10 Timeline SQLite database.
Some references:
https://cclgroupltd.com/windows-10-timeline-forensic-artefacts/
https://salt4n6.com/2018/05/03/windows-10-timeline-forensic-artefacts/amp/

**Comment by Onager** [comment]
@pstirparo is not actually working on this, my bad.
