### ISSUE TITLE
Refactor/revisit MacOS parsers and plugins

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1888]
Many of the MacOS parsers and plugins have been minimally updated to be compatible with core changes. It would be useful to see if there are more structural changes that would be helpful.

Specific things to look at:

- [ ] Error handling in macuser plist plugin

**Comment by joachimmetz** [comment]
@Onager with "MacOS parsers and plugins" are you referring to the plist parser plugins or also other ones?

**Comment by Onager** [comment]
Others as well, last time I looked at BSM it looked a little papered-over. I haven't made an exhaustive list of what needs to be done yet though.

**Comment by joachimmetz** [comment]
Yes BSM uses construct, I opt to make a list (be it a first draft) and determine what needs to be done and what could overlap with #1893

**Comment by joachimmetz** [comment]
@Onager is there still work to be done on this issue? if so please update the issue with the details of what needs to be done, if not please close.

**Comment by joachimmetz** [comment]
Considering this issue addressed. Create a new issue if there are specific things remaining in line of this issue.
