### ISSUE TITLE
Forever pausing in log2timeline.py

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#189]
When processing FAT32 (non-System drive) disk, log2timeline.py processed up till a point and then pause forever. Please advise what’s the issue? Any way to solve that problem?

2015-05-09 07:03:45,835 [INFO] (MainProcess) PID:10423 <foreman> Worker_1 [10432] has been removed from foreman monitoring.

If not, what is the best way to pause or stop the processing which I can have the output file successfully processed by psort.py?

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/169
