### ISSUE TITLE
improve error output

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#19]
Change the following error to be tell what file entry caused the error.
```
2014-11-08 18:58:41,242 [WARNING] (Worker_3  ) PID:18333 <timelib> Unable to create timestamp from 0000-00-00 00:00:00.000000 with error: year is out of range
```

This requires:
* [ ] Changing https://github.com/log2timeline/plaso/blob/master/plaso/lib/timelib.py#L642 so that it does not return 0 but raises an exception
* [ ] Change all parsers that use timelib.Timestamp.FromTimeParts to handle that exception and emit a parser error.

**Comment by kiddinn** [comment]
This requires:
 - [ ] Changing https://github.com/log2timeline/plaso/blob/master/plaso/lib/timelib.py#L642 so that it does not return 0 but raises an exception
 - [ ] Change all parsers that use timelib.Timestamp.FromTimeParts to handle that exception and emit a parser error.

```
$ grep FromTimeParts -r plaso/parsers/ | awk -F ':' '{ n=split($1,s,"/"); print s[n];}' | sort -u
iis.py
mac_appfirewall.py
mac_keychain.py
mac_securityd.py
mac_wifi.py
sccm.py
skydrivelog.py
skydrivelogerr.py
symantec.py
text_parser.py
winfirewall.py
winjob.py
xchatlog.py
```
