### ISSUE TITLE
Multiple chinese encoding processing issues

### ISSUE THREAD

**Issue by ricci3** [log2timeline/plaso#190]
When exploring the use of log2timeline.py for processing Chinese encoding, I realised that there are a number of different encoding scheme used in Windows for handling that. It can be found in the Windows registry. However, because the encoding scheme are different, plaso (may be log2timeline.py or psort.py) cannot handle three different scheme separately which resulted in some output results cannot be further analysed after output from psort.py.

Please advise if that could be fixed? If the encoding scheme is known, how can that be input and passed to plaso for processing?

**Comment by joachimmetz** [comment]
Unless the system somewhere indicates what the correct encoding is, it will be difficult to guess the correct encoding. If you have some examples or can make some test images with the behavior we can look into it and see if we can come up with a way. Windows typically uses [codepage 936](http://en.wikipedia.org/wiki/Code_page_936) and UTF-16 litte-endian for Chinese systems, so I'm not sure what other encodings you are referring to.

log2timeline.py should normalize all text to UTF-8. I'll have a look if I can add an option to user specify the encoding, we've been talking about this in the past, maybe it fell of our radar.

**Comment by joachimmetz** [comment]
@ricci3 can you provide some more clarification.

**Comment by joachimmetz** [comment]
No update from OP closing issue. Feel free to reopen if you have the necessary clarification.
