### ISSUE TITLE
Add end-to-end test for nsrlsvr

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1904]
Add end-to-end test for nsrlsvr

* [x] package nsrlsvr in GIFT PPA - https://github.com/log2timeline/l2tdevtools/pull/872
  * Source https://github.com/rjhansen/nsrlsvr
  * ubuntu 18.04 does not seem to support 1.7.0 (libboost version requirements), building 1.6.1 instead
* [x] create script to install and set up nsrlsvr https://github.com/log2timeline/plaso/pull/3063
  * pull in minimal RDS https://s3.amazonaws.com/rds.nsrl.nist.gov/RDS/current/rds_modernm.zip
  * add minimal RDS to server: `nsrlupdate NSRLFile.txt`
    * nsrlupdate seems to require access to /usr/share/nsrlsvr
    * build takes about 5 mins on test VM, NSRLFile.txt is about 4G
  * otherwise prebuild nsrlsvr
    * data file and ship as part of package? Unclear what the license of the minimal RDS is, so redistribution might not be possible.
    * otherwise as part of the non-public test data
* [x] create nsrlsvr end-to-end test configuration https://github.com/log2timeline/plaso/pull/3063
* [x] set up end-to-end CI test
  * install nsrlsvr and plaso
  * start nsrlsvr and run plaso with analysis plugin
* [x] update configuration after merge

**Comment by Onager** [comment]
Not making September release, removing.

**Comment by joachimmetz** [comment]
```
2020-06-11 07:37:52,933 [INFO] (MainProcess) PID:4267 <data_location> Determined data location: data
2020-06-11 07:37:53,096 [ERROR] (MainProcess) PID:4267 <nsrlsvr> Unable to connect to nsrlsvr with error: [Errno 111] Connection refused.
```
