### ISSUE TITLE
'all' VSS selection option doesn't work

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#192]
Please specify the identifier of the partition that should be processed:
Note that you can abort with Ctrl^C.
p2
The following Volume Shadow Snapshots (VSS) were found:
Identifier      VSS store identifier    Creation Time
vss1            ce5600fb-3dbd-11e4-a134-0800270fb1eb    2014-09-16T20:07:14.9854                                                                                                                                                             70+00:00

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores can
be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can
also be combined as: 1,3..5. The first store is 1. All stores can be defined as:                                                                                                                                                              'all'.
If no stores are specified none will be processed.
You can abort with Ctrl^C.
all

Unsupported VSS identifier(s), please try again or abort with Ctrl^C.

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores can
be defined as: 1,3,5 (a list of comma separated values). Ranges and lists can
also be combined as: 1,3..5. The first store is 1. All stores can be defined as:                                                                                                                                                              'all'.
If no stores are specified none will be processed.
You can abort with Ctrl^C.
1

[then things work]

**Comment by Onager** [comment]
I suspect this is only when specifying 'all' interactively

**Comment by joachimmetz** [comment]
--vss-stores=all works I'll have a look at fixing the interactive one.

**Comment by joachimmetz** [comment]
Adding fix to: https://codereview.appspot.com/238090043
