### ISSUE TITLE
replace multiprocessing.Queue with something else

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#193]
Python's multiprocessing.Queue has proven to have some unwanted side effects. See: https://github.com/log2timeline/plaso/issues/169

* [x] ~~Look for a cleaner multi processing queue implementation, maybe something with RPC support?~~
  * zeroMQ
* [x] ~~[package zeroMQ](https://github.com/log2timeline/l2tdevtools/issues/29) - @joachimmetz~~
* [x] ~~replace multiprocessing Queue - @Onager~~
  * ~~log2timeline~~
  * ~~psort - https://codereview.appspot.com/258120043/~~
* [x] ~~Look into zeromq timeouts (resource not available) https://github.com/log2timeline/plaso/issues/794~~
* [x] ~~provide graceful abort path~~
* [x] Look into zeroMQ stability issues
  * ~~https://github.com/log2timeline/plaso/issues/814~~
  * ~~https://github.com/log2timeline/plaso/issues/822~~

**Comment by kiddinn** [comment]
This would most likely be zeroMQ (http://zeromq.org/)

**Comment by joachimmetz** [comment]
Additional changes:

* provide graceful abort path

**Comment by Onager** [comment]
WIP on a ZeroMQ...Queue.

**Comment by Onager** [comment]
The bits of this that are necessary for 1.4 are complete.
