### ISSUE TITLE
Rawpy output module is broken

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#194]
/home/onager/code/plaso/plaso/lib/storage.py:864: UserWarning: Duplicate name: 'information.dump'
  self._zipfile.writestr(stream_name, stream_data)
[INFO] [Storage] Closing the storage, number of events processed: 0
[ERROR] 'NativePythonOutputModule' object has no attribute '_file_object'
> /home/onager/code/plaso/plaso/output/rawpy.py(20)WriteEventBody()
-> self._file_object.filehandle.WriteLine(event_object.GetString())

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/235470043

**Comment by joachimmetz** [comment]
Related: https://github.com/log2timeline/plaso/issues/123

**Comment by joachimmetz** [comment]
Can you please add a test for this output module before closing the issue.

**Comment by Onager** [comment]
Ack, will do - module is fixed for now.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/240350043/

**Comment by joachimmetz** [comment]
Tests are failing on Windows:
https://ci.appveyor.com/project/joachimmetz/plaso/build/103

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/238450045/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/0b85b6ffb957a83b7d9eb6bde4e75714b47b460d
