### ISSUE TITLE
Question: optimal log2timline preset for windows-raw-images?

### ISSUE THREAD

**Issue by sansstudent** [log2timeline/plaso#1942]
Hello,

this is not an issue (at least for now).
when i run log2timeline against an image i always finish with errors. I believe it hangs on a smsts-logfile (which is microsoft sccm i believe). so i read through a lot of things here and decided to use only parsers for windows.

for now i would use win7_slow, because it contains win_gen, webhist, win7. But i'm not sure if this parser-presets contains all possible windows(7) parsers?

It makes no sense to parse with linux-parsers on windows for me. Before opening an issue-ticket i will try the windows-preset first. 

thanks for clarifiying

**Comment by sansstudent** [comment]
Hello,

attached my environment-settings:

**Command line and arguments:**

sudo log2timeline.py --status-view window --log-file /home/administrator/log2timeline_problem.log.gz --debug --vss_stores all /home/administrator/test.plaso /tmp/test/.../TD3-1.001

for psort:
sudo psort.py -o timesketch ./plasofile.plaso

**Source data:**

DD-Image, cannot provide that, sorry. 
But i can provide the debug-logfile. 
But: It seems to fail on a specific file. (i assume it hangs here):

**Plaso version:**
20180524

**Operating system Plaso is running on:**
Sift Workstation, Ubuntu 16.04.04 LTS xenial
Linux 4.13.0-45-generic #50~16.04.01-Ubuntu SMP Wed May 30 11::18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method:**

sift workstation: sudo sift install

**Debug output/tracebacks:**
Log2Timeline:
Processing completed.
Number of errors encountered while extracting events: 107696.
Use pinfo to inspect errors in more detail.

for psort:


by the was i have a missing lsma message when starting.

**Comment by sansstudent** [comment]
Additional Infos: pinfo shows me a lot of errors with the sccm parser chain:
CmRCService.log
FSPStateMessage.log
ClientLocation.log
SettingsAgent.log
PolicyAgentProvider.log

The eventlog Microsoft-Windows-WPD-MTPClassicDriver%40Operational.evtx also creates an error (parser chain winevtx), but i dont want to disable this parser.


I will attach the pinfo-output as textfile and if needed the CmRCService.log, FSPStateMessage.log, ClientLocation.log, SettingsAgent.log, PolicyAgentProvider.log

How can i disable for example sccm parser chain only?
How can i build an new parser list based on existing ones without the sccm parser chain? The sccm parser chain and the seems to be the problem in my case. 

thanks in advance

**Comment by Onager** [comment]
Hey, the command you probably want to run is:

`log2timeline.py --parsers=win7,!sccm --log-file /home/administrator/log2timeline_problem.log.gz --vss_stores all /home/administrator/test.plaso /tmp/test/.../TD3-1.001`

This is in the help for the parsers option:
```
/log2timeline.py -h
<snip>
  --parsers PARSER_LIST
                        Define a list of parsers to use by the tool. This is a
                        comma separated list where each entry can be either a
                        name of a parser or a parser list. Each entry can be
                        prepended with an exclamation mark to negate the
                        selection (exclude it). The list match is an exact
                        match while an individual parser matching is a case
                        insensitive substring match, with support for glob
                        patterns. Examples would be: "reg" that matches the
                        substring "reg" in all parser names or the glob
                        pattern "sky[pd]" that would match all parsers that
                        have the string "skyp" or "skyd" in its name. All
                        matching is case insensitive. Use "--parsers list" or
                        "--info" to list the available parsers.
```
But it is a little tricky to find.

Please let us know if that works.

**Comment by sansstudent** [comment]
Hello,

i will try and let you know the results. i guess the run will be ready tonight. 
best regards

**Comment by sansstudent** [comment]
okay it runs much faster now. thank you. closed. I will open an issue ticket for the sccm logs and some event-logs which could not be read from log2timeline.
