### ISSUE TITLE
possibly unsupported sccm log

### ISSUE THREAD

**Issue by sansstudent** [log2timeline/plaso#1960]
Description 
when creating a timeline, i cannot use this timeline with psort. Error message file is not an zip file. 
I figured out, that most of the sccm logfiles located in windows\ccm\Log\ could not be read by the parser. it always fails. 

Error-Message for sccm:

The Logfiles for sccm looks like this:

```
> 
> <![LOG[+++ Application not discovered. [AppDT Id: ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/DeploymentType_8739cb54-daf3-4bb0-9f7c-bc6df52a2cb5, Revision: 4]]LOG]!><time="16:51:46.388-120" date="05-17-2018" component="AppDiscovery" context="" type="1" thread="5412" file="localapphandler.cpp:171">
> <![LOG[+++ Evaluating expression to discover application. [AppDT Id: ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/DeploymentType_2c18b432-22cb-4c77-bb85-19a05990677c, Revision: 3]]LOG]!><time="16:51:46.404-120" date="05-17-2018" component="AppDiscovery" context="" type="1" thread="5412" file="localapphandler.cpp:131">
> <![LOG[+++ Application not discovered. [AppDT Id: ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/DeploymentType_2c18b432-22cb-4c77-bb85-19a05990677c, Revision: 3]]LOG]!><time="16:51:46.419-120" date="05-17-2018" component="AppDiscovery" context="" type="1" thread="5412" file="localapphandler.cpp:171">
> <![LOG[--- Completed Indicating 1 settings change(s).]LOG]!><time="15:42:01.564-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6624" file="instanceobjectsink.cpp:222">
> <![LOG[[000000000115DFE8] Queued worker to process these 8 settings change(s)]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="5316" file="instanceobjectsink.cpp:402">
> <![LOG[--- Processing 8 settings change(s).]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:173">
> <![LOG[--- [1] __InstanceDeletionEvent settings change on object CCM_CIVersionInfo.ModelName="ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/Application_a994b598-4f80-4b79-bdb1-1ec6a231e5a2",Version="7".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [2] __InstanceDeletionEvent settings change on object CCM_CIVersionInfo.ModelName="ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/DeploymentType_fc9e0b4e-20e3-4d77-a8cb-23f80912b427",Version="5".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [3] __InstanceModificationEvent settings change on object CCM_ApplicationCIAssignment.AssignmentID="{3165C7AF-DB22-45F7-875F-7CFCB5838FD6}".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [4] __InstanceCreationEvent settings change on object CCM_CIVersionInfo.ModelName="ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/Application_a994b598-4f80-4b79-bdb1-1ec6a231e5a2",Version="8".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [5] __InstanceCreationEvent settings change on object CCM_CIVersionInfo.ModelName="ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/DeploymentType_fc9e0b4e-20e3-4d77-a8cb-23f80912b427",Version="6".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [6] __InstanceCreationEvent settings change on object CCM_CIVersionInfo.ModelName="ScopeId_6214EFE6-FA28-48B4-A7A4-090176983A13/RequiredApplication_a994b598-4f80-4b79-bdb1-1ec6a231e5a2",Version="8".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [7] __InstanceModificationEvent settings change on object CCM_Scheduler_ScheduledMessage.ScheduledMessageID="DEADLINE:{3165C7AF-DB22-45F7-875F-7CFCB5838FD6}".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- [8] __InstanceModificationEvent settings change on object CCM_Scheduler_ScheduledMessage.ScheduledMessageID="{3165C7AF-DB22-45F7-875F-7CFCB5838FD6}".]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:198">
> <![LOG[--- Begin Indicating 8 settings change(s).]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:206">
> <![LOG[--- Completed Indicating 8 settings change(s).]LOG]!><time="15:42:01.580-120" date="05-14-2018" component="PolicyAgentProvider" context="" type="1" thread="6080" file="instanceobjectsink.cpp:222">
> 
```

```
> Error-Message for eventlogs:
>  Message : unable to parse recovered event record: 0 with error:
>                      pyevtx_file_get_recovered_record_by_index: unable to
>                      retrieve recovered record: 0. libfwevt_xml_token_read:
>                      unsupported binary XML token type: 0x6c.
>                      libfwevt_xml_document_read_template_instance: unable to
>                      read binary XML sub token.
>                      libfwevt_xml_document_substitute_template_value: unable to
>                      read document template instance.
>                      libfwevt_xml_document_read_optional_substitution: unable
>                      to substitute template value.
>                      libfwevt_xml_document_read_element: unable to read
>                      optional substitution.
>                      libfwevt_xml_document_read_template_instance: unable to
>                      read element. libfwevt_xml_document_read_fragment: unable
>                      to read document template instance.
>                      libfwevt_xml_document_read_with_template_values: unable to
>                      read fragment header. libfwevt_xml_document_read: unable
>                      to read XML document.
>                      libevtx_record_values_read_xml_document: unable to read
>                      binary XML document. libevtx_io_handle_read_chunk: unable
>                      to read record values XML document.
>                      libfdata_list_get_element_value: unable to read element
>                      data at offset: 0x00003e00.
>                      libfdata_list_get_element_value_by_index: unable to
>                      retrieve element value. libevtx_file_get_recovered_record:
>                      unable to retrieve record values: 0.
>       Parser chain : winevtx
> Path specification : type: OS, location:
>                      /tmp/test/Images_Arbeitskopie/2018-05-24_11-55-42/TD3-1-.001
>                    : type: RAW
>                    : type: TSK_PARTITION, location: /p1, part index: 2, start
>                      offset: 0x00100000
>                    : type: TSK, inode: 105783, location:
>                      /Windows/System32/winevt/Logs/Microsoft-Windows-WPD-MTPClassDriver%4O
> perational.evtx
> --------------------------------------------------------------------------------
```

Command line and arguments:

sudo log2timeline.py --parsers=win7 --status-view window --log-file /../log2timeline_problem.log.gz --debug --vss_stores all /../test.plaso /tmp/test/.../TD3-1.001

Source data:
I can provide the eventlog, which could not be read and an sccmlog, which could not be read.
sccmlog is not encrypted or something, cleartext file. 

Plaso version:
 20180524

Operating system Plaso is running on:
 Sift Workstation, Ubuntu 16.04.04 LTS xenial
 Linux 4.13.0-45-generic #50~16.04.01-Ubuntu SMP Wed May 30 11::18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Installation method:

sift workstation: sudo sift install

**Comment by joachimmetz** [comment]
```
 Message : unable to parse recovered event record: 0 with error:
```
This is expected this is a recovered record. Recovery is best effort.

**Comment by joachimmetz** [comment]
Also sccm has many different types of logs. I wonder if the format you provided is supported. I'll have a look when time permits.

**Comment by sansstudent** [comment]
thank you for your answer. the snippet is from the CertificateMaintenance.log from sccm.  The DataTransferservice.log has the same format. 
All named Logfiles in the https://blogs.msdn.microsoft.com/lxchen/2009/04/03/a-list-of-sccm-log-files/ have the format of the snippet on all of our devices. AFAIK they are not customized in any way. 
i forgot to send the error-message for the sccm-log in my post above. the shown error message in my first post is from an evtx parser error which comes up when parsing the /Windows/System32/winevt/Logs/Microsoft-Windows-WPD-MTPClassDriver%4Operational.evtx Eventlog. 

the corresponding error log for the SCCM Files:
*********************************** Error: 0 ***********************************
           Message : unable to parse log line: u'<![LOG[The connection has
                     been terminated (ID = 4294967295). (OnConnectionTer...'
      Parser chain : sccm
Path specification : type: OS, location:
                     /tmp/test/Images_Arbeitskopie/2018-05-24_11-55-42/TD3-1-.001
                   : type: RAW
                   : type: TSK_PARTITION, location: /p1, part index: 2, start
                     offset: 0x00100000
                   : type: TSK, inode: 101466, location:
                     /Windows/CCM/Logs/CertificateMaintenance.log
--------------------------------------------------------------------------------

********************************** Error: 32 ***********************************
           Message : unable to parse log line: u'<![LOG[State message with
                     TopicType 1000 and TopicId CCM Framework Communicat...'
      Parser chain : sccm
Path specification : type: OS, location:
                     /tmp/test/Images_Arbeitskopie/2018-05-24_11-55-42/TD3-1-.001
                   : type: RAW
                   : type: TSK_PARTITION, location: /p1, part index: 2, start
                     offset: 0x00100000
                   : type: TSK, inode: 101468, location:
                     /Windows/CCM/Logs/DataTransferservice.log
--------------------------------------------------------------------------------

>>This is expected this is a recovered record. Recovery is best effort. 
Is there a way to produce a plaso file without the errors? I mean, i cannot disable evtx-log parsing. but when the parser cannot handle this eventlog, how can i ignore that single evtx-file or ignore the recovery-part when recordrecovery is not successfull?

i can provide the event-log which could not be parsed and some sccm logs which could not be parsed for debugging purposes on your side if you want to try. 

by the way, sorry for my bad english, it's not my native language. 

best regards

**Comment by joachimmetz** [comment]
> Is there a way to produce a plaso file without the errors?

Not at the moment, we are thinking about making these warnings instead of errors, but still save them in the plaso file.

**Comment by sansstudent** [comment]
Thanks for your answer. This means i cannot produce a plaso file (at least for now) because of the fact, that the parsing of the evtx-files failed because of the recovery-records., right?
And i have no way around it except not parsing evtx files, right?

**Comment by joachimmetz** [comment]
> This means i cannot produce a plaso file (at least for now) because of the fact, that the parsing of the evtx-files failed because of the recovery-records., right?

Why not? the extraction errors are more like warnings of data that could not be parsed.

**Comment by sansstudent** [comment]
thanks for your reply, i cannot use the produced output with psort because it says "File is not a zip-file. "

**Comment by joachimmetz** [comment]
Please use the latest version of plaso, we no longer use or support ZIP file plaso file format.

**Comment by sansstudent** [comment]
Hello Joachim,

i believe i allready do so:
is 20180524 not the latest release?
Plaso version:
 20180524

Operating system Plaso is running on:
 Sift Workstation, Ubuntu 16.04.04 LTS xenial
 Linux 4.13.0-45-generic #50~16.04.01-Ubuntu SMP Wed May 30 11::18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Installation method:

sift workstation: sudo sift install

**Comment by sansstudent** [comment]
hello joachim,

i think i figured out what my problem is:
i am using the latest version on my sift workstation.
but i am not using the latest version on my timesketch-box, which do the psort export to timesketch for me. 

the timesketch box runs ubuntu 18.04 LTS bionic
the psort.py on this box is 1.5.1
so i believe this is my problem.

i tried to get the latest version of plaso:
sudo add-apt-repository universe
sudo add-apt-repository ppa:gift/dev
sudo apt-get update
sudo apt-get install python-plaso

returns the depot http://ppa.launchpad.net/gift/stable/ubuntu bionic release did not contain a release-file. 

there is no gift for 18.04. 
is there a way to get it running on 18.04 ?

therefore, i have no good idea how to get the latest version running. simply downloading the release did not work, when i use psort from the released version it terminates with errors. 

thanks for your ungoing support, i really appreciate that.

**Comment by joachimmetz** [comment]
> so i believe this is my problem.

I agree with your assessment.

> http://ppa.launchpad.net/gift/stable/ubuntu

there is no bionic support yet, we have started building bionic packages in testing

**Comment by joachimmetz** [comment]
Bionic packages were added to GIFT PPA stable. Note that I've not tested this yet, if packages might be missing.

**Comment by joachimmetz** [comment]
Moved missing SCCM log to FR, closing this issue.
