### ISSUE TITLE
Disable the elasticsearch output module?

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1969]
I would like to disable the elasticsearch output module.  The version of elasticsearh on my VM is too recent.

plaso - log2timeline version 20180524

Ubuntu 16.04

![log2timeline_error_elasticsearch](https://user-images.githubusercontent.com/16808320/41742733-869c39c6-7564-11e8-9bb7-210b9440ac78.png)

**Comment by Onager** [comment]
There's a few elasticsearch issues we need to sort out, as a workaround, try using the --no-dependencies-check flag, to let l2t still run.

**Comment by mark-hallman** [comment]
David,

Thanks for the reply.  I am not sure where / how to use the
"--no-dependencies-check"
flag.  Is this a log2timeline option,  an apt-get option when
reinstalling,  or something else?

-Mark
