### ISSUE TITLE
Refactor elastic output module

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#197]
The module needs refactoring to be able to test. We also share lots of code with the Timesketch output module, and this should be reused.

* [x] Move from pyelasticsearch -> official elasticsearch python module
* [x] Add index template for aggregation purposes. Addresses #47 
* [x] Refactor out what can be reused for Timesketch output
* [x] Add tests
* [x] remove direct calls to sys.stdout 
* [x] re-enable after refactor

**Comment by joachimmetz** [comment]
Let's disable it for the next release and then get back to cleaning it up in 1.5

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/301030043/

**Comment by berggren** [comment]
https://codereview.appspot.com/299550043

**Comment by joachimmetz** [comment]
All tasks completed
