### ISSUE TITLE
Question:  Can image_export be used to collect system files?

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#1978]
Can image_export be used to collect system files?  I'm asking because I am getting access denied errors on most systems files I am trying to do a triage type collection.

**Comment by Onager** [comment]
I'm guessing you're trying to use image_export on a mounted file system (we have a question about the source data in the issue template....) and the OS is denying image_export access to certain files based on NTFS ACLs. If you can point the tool at the block device or disk image, you should be ok.

**Comment by joachimmetz** [comment]
question looks answered closing issue
