### ISSUE TITLE
how to prase data from $MFT file ???

### ISSUE THREAD

**Issue by evilcode1** [log2timeline/plaso#1979]
i already extract a $MFT file from a raw image how i can create a CVS timeline ?? i try this options they did not work : 
log2timeline.pl -z local -f mft -w timeline.csv /home/$MFT

**Comment by Onager** [comment]
You seem to be using a (very) old version of log2timeline, written in Perl. This repository is for Plaso, a re-write of log2timeline in Python. If you need a introduction to the tool, you can take a look at this video: https://www.youtube.com/watch?v=JZGfhd1PNhU
