### ISSUE TITLE
Ensure that all error messages that include exception strings use an explicit conversion

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#1982]
In Python 3 `'{0:s}'.format(exception)` causes a `TypeError: unsupported format string passed`. Such strings need to an explicit conversion of the exception to a string, for example, '{0!s}'.format(exception)`.

We need to hunt these style of string down in the codebase, and change them.

**Comment by joachimmetz** [comment]
@Onager what is the status of this issue?

**Comment by Onager** [comment]
This is complete.
