### ISSUE TITLE
failed to install dependencies

### ISSUE THREAD

**Issue by DevStudent77495** [log2timeline/plaso#1988]
**Description of problem:**

i try to install the dependencies from the wiki here:
https://github.com/log2timeline/plaso/wiki/Dependencies#packaged-release-2
ackaged release

To add the stable track to your apt configuration run:

sudo add-apt-repository ppa:gift/stable

To install the dependencies run:

sh config/linux/gift_ppa_install.sh

**Command line and arguments:**

sh config/linux/gift_ppa_install.sh
OR
sudo sh config/linux/gift_ppa_install.sh

**Operating system Plaso is running on:**
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

uname -a
Linux LLABA-Timesketch 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

.

**Debug output/tracebacks:**
sh config/linux/gift_ppa_install.sh
sh: 0: Can't open config/linux/gift_ppa_install.sh

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://github.com/log2timeline/plaso/wiki/Troubleshooting#producing-debug-logs]

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Comment by joachimmetz** [comment]
```
sh: 0: Can't open config/linux/gift_ppa_install.sh
```

This script is run by the jenkins test on Travis

Could you try `./config/linux/gift_ppa_install.sh`

**Comment by DevStudent77495** [comment]
Hello,

i'm sorry, but no success here:
administrator@Timesketch:~$ sh config/linux/gift_ppa_install.sh
sh: 0: Can't open config/linux/gift_ppa_install.sh
administrator@Timesketch:~$ sudo sh config/linux/gift_ppa_install.sh
sh: 0: Can't open config/linux/gift_ppa_install.sh
administrator@Timesketch:~$ sudo ./config/linux/gift_ppa_install.sh
sudo: ./config/linux/gift_ppa_install.sh: Befehl nicht gefunden
administrator@Timesketch:~$ sudo sh ./config/linux/gift_ppa_install.sh
sh: 0: Can't open ./config/linux/gift_ppa_install.sh

**Comment by joachimmetz** [comment]
Are you running inside docker?

**Comment by joachimmetz** [comment]
No update from original reporter closing issue.
