### ISSUE TITLE
setup.py build as zip breaks dtFabric integration

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#1999]
need to add:
```
zip_safe = False
```

to setup.py

**Comment by Onager** [comment]
What about setting data_files instead or as well?

**Comment by joachimmetz** [comment]
> What about setting data_files instead or as well? https://docs.python.org/2/distutils/setupscript.html

Unclear what you're implying. We already set data files:
https://github.com/joachimmetz/plaso/commit/13abc3f504630854ff84f191f3fa2cf2d4704d20#diff-2eeaed663bd0d25b7e608891384b7298L210

but that is unreleated

**Comment by joachimmetz** [comment]
Discussed data_files comment. Concluded that moving the dtFabric yaml files to data files is not a desirable alternative. Closing issue.
