### ISSUE TITLE
Error attempting to use new artifacts features of V 20180630

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2007]
**Description of problem:**
I am attempting to use/test the new artifacts features of V 20180630 that i installed in the SANS SIFT Workstation.  The old set of commands work.  I have installed/configured, or I should say that I think that I have,  the Forensic Artifacts library from their GitHub page.  For now,  I have placed the artifacts in /tmp/artifacts.  When I run log2timeline referencing a specific artifact on the command link I get 
**_"RuntimeError: Error processing filters, no valid specifications built."_**  

**Command line and arguments:**
`log2timeline.py --no_dependencies_check --no_vss --artifact_definitions /tmp/artifacts/data --artifact_filters WindowsAutorun artifact_test.plaso /cases/blake/blake-c-drive/blake-c-drive.e01`

**Source data:**
I can provide a download link to the image but I really don't that is necessary at this point. 

**Plaso version:**
20180630 - Ubuntu

**Operating system Plaso is running on:**
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

**Installation method:**

https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

![artifact_error1](https://user-images.githubusercontent.com/16808320/42289105-54229976-7f83-11e8-8c66-98f2e73b7873.jpg)

![artifact_error2](https://user-images.githubusercontent.com/16808320/42289110-5943c7ea-7f83-11e8-8c65-ec52b9815e0d.jpg)

**Comment by mark-hallman** [comment]
I installed the windows version and I get the same error.

**Comment by joachimmetz** [comment]
https://github.com/ForensicArtifacts/artifacts/blob/5bcf73249e6563c56e18aba39055c14d69ede551/data/windows.yaml#L158

**Comment by joachimmetz** [comment]
You'll need to install Python mock to run the tests.

**Comment by jnettesheim** [comment]
The problem with WindowsAutorun is likely that %%environ_systemdrive%% isn't being filled out properly.  

Can you try another test with WindowsXMLEventLogSecurity?

**Comment by jnettesheim** [comment]
For your test with CloudStorageClients, that's an Artifact Group, which isn't currently supported, that will be added for support ASAP.  You would have to try to use the individual members of that directly right now.

**Comment by jnettesheim** [comment]
Also as an fyi, you shouldn't need to download the Forensic Artifacts and point to them with "--artifact_definitions /tmp/artifacts/data", that is already happening in the background.

**Comment by mark-hallman** [comment]
Thanks for your help so far.  My test with `WindowsXMLEventLogSecurity` worked.  Testing with other artifacts in the windows.yaml has not worked.  One example of nonworking artifacts is `WindowsCurrentVersion`.  

`log2timeline.py --no_dependencies_check --no_vss --artifact_filters WindowsCurrentVersion artifact_test.plaso /cases/blake/blake-c-drive/blake-c-drive.e01`

The attached screenshot shows a successful run and a failed run.  If only specific artifacts work,  how can I identify those?  Is it just trial and error?

![image](https://user-images.githubusercontent.com/16808320/42300253-1c751efc-7fd5-11e8-9ae0-8733bbcf3f00.png)

**Comment by mark-hallman** [comment]
Hey guys,

Any follow up on this issue?  If only specific artifacts work, how can I identify those? Is it just trial and error?  I have not gone through all the Windows artifacts but of the ones I have  tried, the only one that has worked so far is "WindowsXMLEventLogSecurity".  This there something I am doing wrong?  

-Mark

**Comment by jnettesheim** [comment]
Hi Mark - I'm looking into this for the registry keys, will update once I've been able to dive a little deeper.

**Comment by jnettesheim** [comment]
Hi Mark - so the overall issue, is that when specifying just "WindowsCurrentVersion" as an artifact, it doesn't have any File artifacts specified, so it is raising an error as it doesn't have the corresponding registry hive specified to parse.  You could specify that file, but I just found a separate bug that I'll need to fix first as well.  Hope to get that pushed in next day or two.  In the long run specifying a windows registry artifact will automatically pull in the required registry hive.

**Comment by mark-hallman** [comment]
Thanks for the update.  Really looking forward to using these features.

**Comment by joachimmetz** [comment]
Screw auto-close

**Comment by joachimmetz** [comment]
Closing issue, recent version has major overhaul of artifact functionality; reopen or open new issue if issue persists
