### ISSUE TITLE
Issues with 20180630 macOS installer

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2012]
**Description of problem:**

Running macOS 10.13.5

1. Running installer gets an error on every dependency package that is attempted to install.  I can manually install the packages one at a time or through a simple for loop in the shell but the .install.sh script fails.

2.  reviewing the install script,  it appears that there should be a package named "plaso-20180630.pkg".  I can't find this package in the .dmg.  should it be there?  

3. When I run `psort.py -V ` ,  that script it there but it does not run.

I have attached a screenshot to illustrate.

Thanks ... 

![image](https://user-images.githubusercontent.com/16808320/42332447-98603a70-803d-11e8-9e41-33205eab4bec.png)

**Comment by joachimmetz** [comment]
Having a look when time permits, this might be bug in the build package script.

**Comment by Onager** [comment]
Looks like some bug in packaging - the plaso module seems to be called python-plaso-20180630.pkg, rather than plaso-2080630.pkg

**Comment by Onager** [comment]
Additionally, the install script doesn't seem to be looking for particular versions of the dependencies, just package name itself.

**Comment by Onager** [comment]
Also line 82 is syntactically invalid.

**Comment by Onager** [comment]
I've upload a fixed version of the MacOS package to the 20180630 release - please try this again, and reopen if it's still broken.

**Comment by mark-hallman** [comment]
The new package installs and works nicely.  Thanks!
