### ISSUE TITLE
Improve handling of unsupported artifacts

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2017]
Per #2007  getting  `RuntimeError: Error processing filters, no valid specifications built.` isn't particularly easy for users to understand.

**Comment by joachimmetz** [comment]
@Onager what is the status of this?

**Comment by Onager** [comment]
This still needs some more testing and refinement.

**Comment by joachimmetz** [comment]
@Onager can you be more specific to what additional testing and refinement is needed?

**Comment by Onager** [comment]
More testing of what happens when invalid or unknown artifacts are specified, and what errors are shown to the user.

**Comment by joachimmetz** [comment]
@Onager is this still and issue?

**Comment by joachimmetz** [comment]
No response closing issue
