### ISSUE TITLE
[parsers/systemd_journald] Properly parse LZ4 compressed message bits

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#2018]
**Description of problem:**

Journald can compress some log bits with LZ4:
https://cgit.freedesktop.org/systemd/systemd/tree/src/journal/journal-def.h
whereas we only support XZ currently.

**Comment by rgayon** [comment]
Currently we raise because of a utf-8 decoding error.
First fix is to recover the compressed string and report it as a "dirty" event (PR #2019)
Next step is to actually decompress LZ4 strings properly (PR #2004 )

**Comment by Onager** [comment]
@rgayon @joachimmetz what's the status of this, after the migration to dtfabric?

**Comment by joachimmetz** [comment]
LZ4 compression support is implemented. Closing thiss @rgayon reopen if this is still pending work.
