### ISSUE TITLE
Mac OS X install issue

### ISSUE THREAD

**Issue by dptom** [log2timeline/plaso#202]
After installing on Mac OS X (ver 10.10.3), I'm getting th following error when I attempt to run log2tiomeline. I've tried reinstalling and get the same error each time. Since I don't have a Google account, this seems to be the only place to post this.  Let me add that I searched the Google group for this but didn't find any references. 

t-sirtalis:plaso-1.2.0 dptom$ log2timeline.py --help
Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 31, in <module>
    from plaso.frontend import frontend
  File "/Library/Python/2.7/site-packages/plaso/frontend/frontend.py", line 36, in <module>
    from plaso import parsers   # pylint: disable=unused-import
  File "/Library/Python/2.7/site-packages/plaso/parsers/__init__.py", line 49, in <module>
    from plaso.parsers import skydrivelogerr
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelogerr.py", line 56, in <module>
    class SkyDriveLogErrorParser(text_parser.PyparsingMultiLineTextParser):
  File "/Library/Python/2.7/site-packages/plaso/parsers/skydrivelogerr.py", line 105, in SkyDriveLogErrorParser
    pyparsing.lineEnd())
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by joachimmetz** [comment]
Which version of pyparsing?

**Comment by mspreitz** [comment]
I get the same errors. Version of pyparsing is 2.0.1

**Comment by joachimmetz** [comment]
Try pyparsing 2.0.3, also see: https://github.com/log2timeline/plaso/wiki/Dependencies-Mac-OS-X#pyparsing

**Comment by mspreitz** [comment]
error message stays the same :(

Here is a full list of installed python modules, maybe this helps:
altgraph==0.10.2
bdist-mpkg==0.5.0
bencode==1.0
binplist==0.1.4
bonjour-py==0.3
construct==2.5.2
dfvfs==20141220
Django==1.8.1
django-tastypie==0.12.1
dpkt==1.8
drozer==2.3.3
ipython==1.2.1
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
plaso==1.2.0
protobuf==2.4.1
psutil==1.2.1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13
pyparsing==2.0.3
pysqlite==2.6.3
python-dateutil==1.5
python-evtx==0.3.1
python-mimeparse==0.1.4
pytsk3==4.1.3.post20140506
pytz==2013.7
PyYAML==3.11
raven==5.3.1
requests==2.7.0
scipy==0.13.0b1
six==1.4.1
Twisted==13.2.0
xattr==0.6.4
zope.interface==4.1.1

**Comment by joachimmetz** [comment]
What version of pyparsing does the following script return:
```
./utils/check_dependencies.py
```

**Comment by mspreitz** [comment]
strange, there it is still showing 2.0.1

**Comment by joachimmetz** [comment]
Not so strange, Mac OS X has multiple versions of Python, make sure to run and install the package for the right one.

**Comment by mspreitz** [comment]
ok, this works for now...but log2timeline is still throwing errors:

ImportError: No module named pysigscan

do you have any hint how to install this module?

**Comment by joachimmetz** [comment]
See: https://github.com/log2timeline/plaso/wiki/Dependencies-Mac-OS-X#libyal

**Comment by joachimmetz** [comment]
Closing issue no response in more than a week and no response from OP. Reopen if needed.

**Comment by mspreitz** [comment]
sorry for not responding in time, but it is still not working and I'm not able to get pysigscan working

**Comment by joachimmetz** [comment]
No worries, that why I said reopen if needed. Can you be more specific what you did and what is not working? Also know we provide macosx packages here: https://github.com/log2timeline/l2tbinaries/tree/master/macosx

**Comment by mspreitz** [comment]
I installed nearly all of the pre-build dmg files but I still get:

    pyparsing.lineEnd())
TypeError: __call__() takes exactly 2 arguments (1 given)

version of pyparsing is 2.0.3

**Comment by joachimmetz** [comment]
But you got that working last time? What is the issue with pysigscan you saw?

**Comment by joachimmetz** [comment]
Can you see if you have any duplicate packages in the output of:
```
/usr/sbin/pkgutil --packages
```

**Comment by mspreitz** [comment]
I've no idea why I'm now back to the initial error message. I got the error that there is no pysigscan package to import. After installing the dmg files I'm now back at the error from pyparsing.

with the command you provided I'm getting the following list (no duplicates as far as I can see):

com.github.erocarrer.pefile
com.github.libyal.libesedb
com.github.libyal.libmsiecf
com.github.libyal.libsigscan
com.github.log2timeline.dfvfs
com.github.log2timeline.plaso
com.github.sleuthkit.sleuthkit
com.google.code.p.binplist
com.google.code.p.dpkt
com.google.code.p.libbde
com.google.code.p.libesedb
com.google.code.p.libevt
com.google.code.p.libevtx
com.google.code.p.libewf
com.google.code.p.libfwsi
com.google.code.p.liblnk
com.google.code.p.libmsiecf
com.google.code.p.libolecf
com.google.code.p.libqcow
com.google.code.p.libregf
com.google.code.p.libsmdev
com.google.code.p.libsmraw
com.google.code.p.libvhdi
com.google.code.p.libvmdk
com.google.code.p.libvshadow
com.google.code.p.protobuf
com.google.code.p.python-protobuf
com.google.code.p.pytsk
com.intel.kext.haxm.1.1.1
com.lightheadsw.caffeine
com.literatureandlatte.scapple
com.macitbetter.betterzip
com.oracle.jdk8u45
com.oracle.jre
com.paragon-software.filesystems.ExtFS.pkg
com.prect.NavicatEssentialsForSQLite
com.prect.NavicatLiteForMySQL
com.prect.NavicatLiteForPG
com.SweetScape.010Editor.pkg
com.twitter.twitter-mac
de.stoegerit.OutBankMac
eu.vivica.AnyVideoConverter
net.sourceforge.projects.pyparsing
org.github.ipython.ipython
org.gpgtools.checkprivatekey.pkg
org.gpgtools.gpgkeychain.pkg
org.gpgtools.gpgmail_lml.pkg
org.gpgtools.gpgpreferences.pkg
org.gpgtools.gpgservices.pkg
org.gpgtools.key
org.gpgtools.libmacgpg.xpc.pkg
org.gpgtools.libmacgpgB.pkg
org.gpgtools.macgpg2.pkg
org.gpgtools.pinentry-mac.pkg
org.python.pypi.bencode
org.python.pypi.construct
org.python.pypi.psutil
org.python.pypi.pysqlite
org.python.pypi.pytz
org.python.pypi.PyYAML
org.python.pypi.six
org.samba.talloc
org.tug.mactex.ghostscript9.10
org.tug.mactex.gui2014
org.tug.mactex.texlive2014
org.wireshark.ChmodBPF.pkg
org.wireshark.cli.pkg
org.wireshark.Wireshark.pkg

**Comment by Onager** [comment]
Apple also ships version 2.0.1 of pyparsing in /System/Library/Frameworks/Python.framework.... which is usually loaded first, even if you have a newer pyparsing installed. You can work around this by specifying the PYTHONPATH - try ```PYTHONPATH=/Library/Python/2.7/site-packages ./run_tests.py```

**Comment by mspreitz** [comment]
run_test.py is always giving me "OK"

and changing the PATH doesn't help either

**Comment by Onager** [comment]
You mean the PYTHONPATH? ```PYTHONPATH=/Library/Python/2.7/site-packages ./log2timeline.py -h``` fails too?

**Comment by Onager** [comment]
You might need ```PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH ./log2timeline.py --help```

**Comment by mspreitz** [comment]
ok, thank both of you very much....no it is working

**Comment by Onager** [comment]
Great to hear, I've added a note to the wiki on the OS X page for future suffers of this issue.
