### ISSUE TITLE
When I press CTRL+C, plaso is not stopping

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#2039]
**Description of problem:**

When I press CTRL+C, plaso is not stopping. I tried both worker and --single-process, but CTRL+C is not working to cancel both psteal or log2timeline.py.

**Command line and arguments:**

plaso is run via docker log2timeline/plaso log2timeline.py --options

**Source data:**

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

**Plaso version:**

For example 20180630

**Operating system Plaso is running on:**

Arch linux host on mounted windows file system

**Installation method:**

For example:
* installed from [GiFT PPA][https://launchpad.net/~gift] stable track
* installed from [GiFT COPR][https://copr.fedorainfracloud.org/coprs/g/gift/] stable track
* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch
* built using [l2devtools][https://github.com/log2timeline/l2tdevtools]
* other, namely ...

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://github.com/log2timeline/plaso/wiki/Troubleshooting#producing-debug-logs]

For more information see the [troubleshooting
guide][https://github.com/log2timeline/plaso/wiki/Troubleshooting].

**Comment by Onager** [comment]
Possibly related to https://github.com/log2timeline/plaso/issues/1754 where workers aren't terminating properly.

**Comment by joachimmetz** [comment]
> Might be result of #2040 where workers are stuck at 100% CPU with sccm parser bug.

sccm parser is not stuck, just very slow, and consumes a lot of CPU

**Comment by bf** [comment]
I found out this is a docker issue. When running plaso through docker, you need to add `-t -i` options so docker forwards CTRL+C to the python script and terminates afterwards.

Running `docker -t -i -v /mnt:/mnt log2timeline/plaso log2timeline.py /tmp/l2t.dump /mnt/` it works as expected.
