### ISSUE TITLE
Add option to open locked plaso SQLite storage files

### ISSUE THREAD

**Issue by bf** [log2timeline/plaso#2041]
**Description of problem:**

When plaso is killed forcefully, SQLite database might remain in a locked state. Afterwards, plaso is not starting any more because it fails with error

```Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/log2timeline_tool.py", line 434, in ExtractEventsFromSources
    status_update_callback=status_update_callback)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/single_process.py", line 271, in ProcessSources
    storage_writer.WriteSessionStart()
  File "/usr/lib/python2.7/dist-packages/plaso/storage/interface.py", line 1729, in WriteSessionStart
    self._storage_file.WriteSessionStart(session_start)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 1049, in WriteSessionStart
    self._WriteAttributeContainer(session_start)
  File "/usr/lib/python2.7/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 387, in _WriteAttributeContainer
    self._cursor.execute(query, (serialized_data, ))
sqlite3.OperationalError: database is locked
```

**Command line and arguments:**

Any command line arguments to log2timeline.py

**Source data:**

not relevant

**Plaso version:**

20180630

**Operating system Plaso is running on:**

arch linux via docker container

**Installation method:**

docker latest

**Comment by bf** [comment]
It would be great if there is an option to forcefully unlock the database once this error occurs.

**Comment by Onager** [comment]
Ping for @rgayon

**Comment by Onager** [comment]
Thinking more about this, this can be solved by invoking Plaso in the container differently, specifying a temporary file path. I'll update the documentation, but we don't need to change the container at present.

**Comment by bf** [comment]
Yes that sounds like a good solution. Thanks for following up on this. Please let me know if I can contribute.

**Comment by Onager** [comment]
After discussing with @rgayon offline, I think I might have made some wrong assumptions - @bf how were you invoking Plaso in the container? Were you logging into the container, or doing something like `docker run -v /data/:/data log2timeline/plaso psort /data/evidence.plaso`, like the example in the [documentation](https://plaso.readthedocs.io/en/latest/sources/user/Installing-with-docker.html)?

**Comment by rgayon** [comment]
Sorry for joining the discussion so late.

Outside a docker container environment, if I `pkill -9 log2timeline` while it's running I end up with the two usual sqlite db and the -journal file.
The -journal is used by the sqlite engine, when you open the DB again (through the python API or sqlite3 CLI client) to replay the not-yet-committed updates to the database.
Either re-running log2timeline.py or even opening the plaso file with `sqlite3` command restores the database into a clean status (and deletes the -journal)

The "database is locked" issue usually comes from when you have multiple threads opening different connections and trying to update a table at the same time (ie: running log2timeline twice).
This may happen if you're running plaso from 2 containers, on the same plaso storage file outside the containers

**Comment by joachimmetz** [comment]
No update on issue in a while, closing
