### ISSUE TITLE
Running directly against artifact ERROR: Missing required artifact

### ISSUE THREAD

**Issue by infosecjosh** [log2timeline/plaso#2045]
run 
log2timeline.py -d --parsers sqlite ~/ack.plaso ~/plaso/test_data/cookies.db

OUTPUT
ERROR: Missing required artifact definition: LinuxIssueFile

run
log2timeline.py -d ~/ack.plaso ~/plaso/test_data/iis.log

OUTPUT
ERROR: Missing required artifact definition: LinuxIssueFile

What does the tool not do that it should? What would you like it to do?
doesn't actually run against single files

I would like it to work like it used to before all of this artifact definition stuff was added.

Please provide the command with arguments you ran when you experienced
the problem.
log2timeline.py -d --parsers sqlite ~/ack.plaso ~/plaso/test_data/cookies.db

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

plaso/test_data/iis.log
plaso/test_data/cookies.db

**Plaso version:**

plaso - log2timeline version 20180703

**Operating system Plaso is running on:**

Ubuntu 16.04
**Installation method:**

cloned from plaso github repo and ran setup.py install

**Debug output/tracebacks:**
ran -d but produced nothing

**Comment by joachimmetz** [comment]
> ERROR: Missing required artifact definition: LinuxIssueFile

It looks like l2tdevtools cannot find the artifacts definitions. You can set the path of the artifact definitions with `--artifact_definitions` and `--custom_artifact_definitions`.

**Comment by infosecjosh** [comment]
ran log2timeline.py -d --parsers sqlite ~/ack.plaso ~/origin.db --artifact_definitions=/usr/share/artifacts..

Still same error.  not sure why I need to use a artifact definition when I'm pointing directly to a single artifact.

**Comment by joachimmetz** [comment]
> Still same error

And your artifact yaml files contain the `LinuxIssueFile` artifact definition? 

> Still same error. not sure why I need to use a artifact definition when I'm pointing directly to a single artifact.

Because the preprocessors use artifact definitions as well

**Comment by infosecjosh** [comment]
Yes.  I added LinuxIssueFile then realized I didn't have the latest Artifacts.  Suggest perhaps changing minimum required version of artifacts to match the dependencies in plaso.
