### ISSUE TITLE
how to process just one artifcate e.g. $usnjrnl

### ISSUE THREAD

**Issue by slippery60** [log2timeline/plaso#2048]
**Description of problem:**

I want to process 2 artifacts, the $usnjrnl, and the $mft. When I try to run just those two parsers, I have to process all of the files in the image.  I tried applying the filter.  I think the filter would work but how do you specify just the $mft and $extend files. 

two items might help this, 
more information on how to write filters,
of a switch that directs the program to only locate specific files. 

thanks

**Comment by joachimmetz** [comment]
This might be the thing you're looking for https://github.com/log2timeline/plaso/wiki/Collection-Filters. Though information about recent forensicsartifacts support needs to be added to the documentation.

**Comment by slippery60** [comment]
joachimmetz;

Thank you very much for the response.  I read that specified wiki prior to posting.  The posting did provide insight.  But apparently not enough for me to solve my issue. 

I want to parse two files, the $usnjrnl and the $mft. 
the $mft so I can find the specific MFT records number(inode) and the $usnjrnl so I can track the changes to the selected file for analysis, without having to plow through all the files. 

I tried a number of variations such as;
                     /$extend/+./$usnjrnl
                     /+./$mft
or
                    /+. /$extend
                    /$mft

and other less likely options e.g. 
                    /\$mft
                   /\$extend/+./\$usnjrnl

**Comment by mark-hallman** [comment]
Scott,

Try these two lines in your filter file.

```
/[$]MFT
/[$]Extend/$UsnJrnl
```

Your log2timeline command should look similar to this

`log2timeline.py -o l2tcsv --no_vss -f filter_mft.txt --parsers "mft,usnjrnl" mft.plaso image.e01`

If you don't specify a parser with log2timeline,  on Windows systems, the parser will be defaulted to "win7".  "win7"  does not include the "mft" parser.  "usnjrnl" is, indirectly, included in "win7".  The mft parser is going to take a long time to run.  You might consider using something like Eric Zimmerman's mft parser.  I believe that there will be a l2t output soon for MFTECmd. 

[Zimmerman's MFTECmd](https://binaryforay.blogspot.com/2018/06/mftecmd-v0260-released.html)

-Mark

**Comment by slippery60** [comment]
Thanks

**Comment by slippery60** [comment]
Mark-hallman;

I am running the command now. The option "-o l2tcsv" didn't work, caused
cli errors. I must have an earlier version than you.
I altered the filter to match yours.  I would not have thought to use the
"[]". The filter seems to be working nicely.  The MFT is the only string
running.

Thanks

I'll keep you posted.

**Comment by mark-hallman** [comment]
Sure,  happy to help.  The -o l2tcsv error is my fault.  I got ahead of my self. That is a psort option for the output format.

Mark
830.255.1551

**Comment by Onager** [comment]
No news on this since July, and per @slippery60's last post, this was "working nicely". Closing issue.
