### ISSUE TITLE
Hard set file limit in DSV parser breaks parsing of analyzeMFT outputs

### ISSUE THREAD

**Issue by soundwave01** [log2timeline/plaso#2056]
**Description of problem:**

It looks like change #1812 which applied a hard set file size limit in the DSV parser, appears to break the processing of output from analyzeMFT.

**Command line and arguments:**

analyzeMFT.py -f '$MFT' --bodyfull -p -w -b MFTbody

log2timeline.py -d --no_dependencies_check --logfile out.txt /tmp/log2timeline-xxxxxx MFTbody

**Plaso version:**

20180630

**Operating system Plaso is running on:**

Ubuntu 16.04.5 LTS

**Debug output/tracebacks:**

2018-07-25 11:54:52,257 [DEBUG] (MainProcess) PID:23895 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/tmp/xxxxxxxxxx/MFTbody with parser: mactime
2018-07-25 11:54:52,257 [DEBUG] (MainProcess) PID:23895 <extractors> mactime unable to parse file: OS:/tmp/xxxxxxxxxxx/MFTbody with error: [mactime] Unable to parse DSV file: OS:/tmp/xxxxxxxx/MFTbody size of file exceeds maximum supported size

**Comment by soundwave01** [comment]
I have performed some more testing and can confirm removing the file size check, does solve the issue.

**Comment by Onager** [comment]
@joachimmetz the fix in #1812 isn't doesn't make sense to me - the BinaryLineReader from the reproduction doesn't use the CSV library, and I'm surprised we're exhausting memory, given we're using an iterator vs parsing everything into a list.

**Comment by joachimmetz** [comment]
The memory usage is internal to the csv module

**Comment by Onager** [comment]
Going to try to tackle this for the release, as this is breaking a lot of DSV-derived parsers.

**Comment by Onager** [comment]
Removed limit in https://github.com/log2timeline/plaso/commit/df20c2635eda9a1a53770cefd4237984f6768795
