### ISSUE TITLE
Adding dpkt to requirements.txt

### ISSUE THREAD

**Issue by ohnonocat** [log2timeline/plaso#2058]
**Description of problem:**

Hi,
When installing plaso latest release (20180630) using `pip` and `requirement.txt` file (using this documentation : https://github.com/log2timeline/plaso/wiki/Running-plaso-in-virtualenv), it seems that there's a missing dependencies (dpkt).

Indeed, `log2timeline.py` says dpkt is missing and won't start.
Using` pip install dpkt` solves the problem (version 1.9.1 worked fine for me).

I may have missed a step somewhere. If not, please consider adding dpkt to the `requirement.txt` file ?

**Command line and arguments:**

`log2timeline.py ~/test.plaso test.e01`

**Plaso version:**

20180630

**Operating system Plaso is running on:**

Windows 10 w/ WSL (Ubuntu 18.04)

**Installation method:**

virtualenv + plaso-20180630.tar.gz
https://github.com/log2timeline/plaso/wiki/Running-plaso-in-virtualenv

**Debug output/tracebacks:**
`$ ./bin/log2timeline.py ~/test.plaso test.e01`
`Checking availability and versions of dependencies.`
`[FAILURE]       missing: dpkt.`
`[OPTIONAL]      missing: lzma.`

**Comment by joachimmetz** [comment]
dpkt was recently removed as a dependency https://github.com/log2timeline/plaso/commit/7934558d76a418b359d3918470a2d42ed6ad682b

As you can see here: https://github.com/log2timeline/plaso/blob/master/plaso/dependencies.py#L21 there is no requirement for dpkt. 

Version 20180630 requires dpkt, the current version in git does not (for which the requirements file is intended).

https://github.com/log2timeline/plaso/wiki/Running-plaso-in-virtualenv does not instruct you to install plaso via pip. And clearly indicates **Note that this is intended for development use only**
