### ISSUE TITLE
Amcache last execution time

### ISSUE THREAD

**Issue by KieranEvans89** [log2timeline/plaso#2059]
**Description of problem:**

I found that the amcache decoder on a Windows 8 machine (being analysed) gave the content modification timestamp of the file as the "last executed time".

Data type: windows:registry:amcache
parser: amcache
Source_long: Amcache Registry Entry

**Plaso version:**

plaso - log2timeline version 20171002

**Comment by Onager** [comment]
@rbdebeer - any comments on this, seeing as you wrote the original parser?

**Comment by rbdebeer** [comment]
This is a bug in below line, will fix in the next 2 weeks. 
https://github.com/log2timeline/plaso/blob/9eaef8d5d44b003e69b3c5b09f4877f728faa2a1/plaso/parsers/amcache.py#L310

**Comment by joachimmetz** [comment]
Per chat the timestamp_desc should be content modified
only the first timestamp is executed, content modified will always be correct in relation to that timestamp

**Comment by joachimmetz** [comment]
Per slack conversation this appears not working as expected. Reopening and having a closer look

**Comment by joachimmetz** [comment]
For context relevant info from slack:
`tzworks shows process execution time while the plaso parser is showing modification time`

Plaso version is: 20180930

**Comment by joachimmetz** [comment]
Still had not time to look into this, bumping milestone

**Comment by joachimmetz** [comment]
Unable to validate against tzworks wacu, complains that it needs a license while certain sources claim it is free of cost
