### ISSUE TITLE
Wrong link redirection in documentation

### ISSUE THREAD

**Issue by tomchop** [log2timeline/plaso#2060]
The last three links in https://github.com/log2timeline/plaso/wiki/Developers-Guide#getting-started point to pages that redirect to the Wiki homepage.

**Comment by Onager** [comment]
Going to take a look at this today

**Comment by Onager** [comment]
These links were never live, I presume they were intended to be placeholders.

**Comment by Onager** [comment]
I've added some content to these pages, so they go somewhere useful now.
