### ISSUE TITLE
Parent file reference traversal.

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#2061]
The "Parent file reference:" entries are confusing. 
It is possible to do the references traversals to give "full" path for the files?
This feature could also be implemented in psort.

**Comment by Onager** [comment]
Yes, this is a known issue, and we plan to solve this at some point using MFT path hints, see #316 

I'm going to close this issue out, but know this is definitely something we want to do.

**Comment by joachimmetz** [comment]
> Is it possible to do the references traversals to give "full" path for the files?

Reconstruction paths from MFT does not necessary yield a single full path. These should be considered more like "full path hints".
