### ISSUE TITLE
Pyparsing parsers can dramatically slow processing 

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2064]
As noted in #2040 pyparsing-derived parsers can be very slow when there are large number of non-matching lines.

**Comment by Onager** [comment]
@joachimmetz - can you elaborate on what you mean by "there is an underlying issue with the selection of the pyparsing grammar"? What's the issue?

**Comment by joachimmetz** [comment]
Per #2040 

sccm.VerifyStructure() returns True. PyparsingMultiLineTextParser continues to loop though available line "line structures" but cannot find a match;

**Comment by Onager** [comment]
Reverted title. @joachimmetz this same situation also applies to the single line parser

**Comment by Onager** [comment]
Resolved in https://github.com/log2timeline/plaso/commit/c36de45e8facbe7d5dbda3b5afd3aa6c3ad3698a
