### ISSUE TITLE
psort: l2tcsv output module ignores the timezone setting

### ISSUE THREAD

**Issue by yukinobu-n** [log2timeline/plaso#2067]
**Description of problem:**

In plaso-20180630, it seems `l2tcsv` output module of `psort` ignores the timezone setting which is specified by `-z` option.

In case of using default output module, `psort` treats the timezone setting correctly.

From the following test, it is considered that this issue was occurred after plaso-20180127.

**Command line and arguments:**

**Test 1 (l2tcsv):** With plaso-20180630, I ran the following command including `-o l2tcsv` option. 

```
log2timeline --parsers winevt,winevtx ./winevt.db /path/to/eventlogs && psort -z Japan -w eventlog_timeline.csv -o l2tcsv ./winevt.db
```

Then I saw the first time on the timeline is `07/19/2018,06:27:51,Japan`. But the correct time is 15:27:51 (JST). 06:27:51 seems like UTC time. `-z Japan` option seems to be ignored.

**Test 2 (default):** With plaso-20180630, after I removed db and timeline, I ran the following command which is not including any `-o ` option. 

```
log2timeline --parsers winevt,winevtx ./winevt.db /path/to/eventlogs && psort -z Japan -w eventlog_timeline.csv ./winevt.db
```

Then I saw the first time on the timeline is `2018-07-19T15:27:51.267307+09:00`. This is the correct time.

**Test 3 (20180127):** With plaso-20180127, after I removed db and timeline, I ran the following command that is exactly same as Test 1.

```
log2timeline --parsers winevt,winevtx ./winevt.db /path/to/eventlogs && psort -z Japan -w eventlog_timeline.csv -o l2tcsv ./winevt.db
```

Then I saw the first time on the timeline is `07/19/2018,15:27:51,Japan`. This is the correct time.

**Source data:**

Eventlogs: [eventlogs.zip](https://github.com/log2timeline/plaso/files/2252228/eventlogs.zip)

**Plaso version:**

plaso-20180630-amd64

**Operating system Plaso is running on:**

Windows 7 SP1 (64bit)

**Installation method:**

I downloaded plaso-20180630-amd64.zip (sha1: `0e10b5a99c99bdd04fd8a5dcbc7e4d96f9a982c8`) and I unzipped it to my local folder.

**Debug output/tracebacks:**

Debug output in Test 1: [debug_out.zip](https://github.com/log2timeline/plaso/files/2252227/debug_out.zip)

**Comment by Onager** [comment]
Thanks for the detailed report. This is actually a missing feature, there's a TODO here: https://github.com/log2timeline/plaso/blob/master/plaso/output/l2t_csv.py#L115 that needs fixing.

I'll take a look at fixing this up across the output modules.

**Comment by yukinobu-n** [comment]
Thank you for confirmation and reply.
I understood that you were already aware of this issue. Sorry!

**Comment by big-husky** [comment]
I made a duplicate bug in #2177 and will close that one.  I can confirm this issue still exists in 20180930 and that the time presented is UTC with a label of whatever was chosen by the '-z <timezone>' argument.

**Comment by Onager** [comment]
Is isn't going to make release, removing from milestone.

**Comment by joachimmetz** [comment]
Blocked on https://github.com/log2timeline/dfdatetime/issues/47

**Comment by joachimmetz** [comment]
Will put a fix and end-to-end tests in place for now. Need to move this to dfDateTime or a better solution long term.

**Comment by joachimmetz** [comment]
Changes merged.
