### ISSUE TITLE
Frequent error messages from msie_zone plugin parsing win7 registry

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#207]
Getting lots of these on a test image:
[ERROR] Error in winreg/msie_zone while parsing file TSK:/Users/bperry/NTUSER.DAT: Key: \Software\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones missing values.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/da17398e7a6c9acbd3a7489653874649985ef6b3
