### ISSUE TITLE
plaso 20180630 in virtualenv does not work for me on several E01 files

### ISSUE THREAD

**Issue by winnotor** [log2timeline/plaso#2071]
**Description of problem:**

Hi, there's a trouble about the plaso version 20180630 for recognize Operating System partitions about some encase. The two encase files in plaso test_data work.

There isn't the same comportment with the plaso version 20180127. Indeed, this specific encase partition 
 in my job are recognize with this OLD version(no virtualenv mode)

**Command line and arguments:**

source ./plaso_20180630/bin/activate
log2timeline.py /tmp/recognize_partitions_encase.plaso xxxxxxxxxxxxxxxx.E01

response:

2018-08-02 07:13:17,272 [WARNING] (MainProcess) PID:5308 <log2timeline> No supported file system found in source.

**Source data:**

TD3 generated source file .E01

**Plaso version:**

20180630

**Operating system Plaso is running on:**

Ubuntu 16.04.4 LTS

**Installation method:**

* installed before in a virtualenv directory on Linux Mint 18.1 Serena
   * require file "requirements.txt" with module pip dpkt" use with command "pip install -r requirrements.txt"
   * build and install plaso-20180630.tgz in 
   - VENVDIR=`readlink -f plaso_20180630`
       - ${VENVDIR}/bin/python setup.py build
       - ${VENVDIR}/bin/python setup.py install
   * test log2timeline.py with directory test_data in plaso-20180630.tgz  ===> OK (dependencies OPTIONAL lzma)
* installed virtualenv directory generated on Ubuntu 16.04.4 LTS
    * test log2timeline.py with directory test_data in plaso-20180630.tgz  ===> OK (dependencies OPTIONAL lzma)

**Debug output/tracebacks:**

2018-08-02 07:13:17,272 [WARNING] (MainProcess) PID:5308 <log2timeline> No supported file system found in source.

**Comment by joachimmetz** [comment]
What version of libewf/pyewf do you use?

**Comment by winnotor** [comment]
Oups, sorry i come to the message. I am going to answer tomorrow.

Le jeu. 2 août 2018 à 12:33, Joachim Metz <notifications@github.com> a
écrit :

**Comment by joachimmetz** [comment]
@winnotor friendly ping

**Comment by winnotor** [comment]
Hi joachim,

to answer your question about libewf version,

I use in the virtualenv plaso_20180630 la version libewf-python 

* libewf-python 20171104

I give you, the other version 


* artifacts         20180628 
* backports.lzma    0.0.13   
* bencode.py        2.0.0    
* biplist           1.0.3    
* certifi           2018.4.16
* chardet           3.0.4    
* construct         2.5.3    
* dfdatetime        20180704 
* dfvfs             20180703 
* dfwinreg          20180712 
* dpkt              1.9.1    
* dtfabric          20180707 
* efilter           1-1.5    
* elasticsearch     5.5.1    
* future            0.16.0   
* hachoir-core      1.3.3    
* hachoir-metadata  1.3.3    
* hachoir-parser    1.3.4    
* idna              2.7      
* libbde-python     20170902 
* libesedb-python   20170121 
* libevt-python     20180317 
* libevtx-python    20170122 
* libfsntfs-python  20170315 
* libfvde-python    20180108 
* libfwnt-python    20180117 
* libfwsi-python    20180630 
* liblnk-python     20180626 
* libmsiecf-python  20170116 
* libolecf-python   20170825 
* libqcow-python    20170222 
* libregf-python    20170130 
* libscca-python    20170205 
* libsigscan-python 20170124 
* libsmdev-python   20171112 
* libsmraw-python   20171105 
* libvhdi-python    20170223 
* libvmdk-python    20170226 
* libvshadow-python 20170902 
* libvslvm-python   20160110 
* pefile            2017.11.5
* pip               18.0     
* plaso             20180630 
* psutil            5.4.6    
* pycrypto          2.6.1    
* pylzma            0.4.9    
* pyparsing         2.2.0    
* python-dateutil   2.7.3    
* pytsk3            20180225 
* pytz              2018.5   
* PyYAML            3.13     
* pyzmq             17.1.0   
* requests          2.19.1   
* setuptools        40.0.0   
* six               1.11.0   
* urllib3           1.21.1   
* wheel             0.31.1   
* XlsxWriter        1.0.5    
* yara-python       3.7.0

**Comment by joachimmetz** [comment]
20171104 is an experimental version please try https://github.com/libyal/libewf-legacy version 20140804 instead

**Comment by joachimmetz** [comment]
Pip is not supported by plaso as a production platform at this point. Largely because it does not support release teacks

**Comment by winnotor** [comment]
Okay i get you. The plaso 1.5.1 or 1.5.2 it's the more stable plaso ?

**Comment by winnotor** [comment]
okay, 
about a production plaso release platform, what are the recommendations ?

 
There is a .deb package mirror with stable version ?

**Comment by joachimmetz** [comment]
> There is a .deb package mirror with stable version ?

There is the GIFT PPA: https://github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release

> I know, there's a lot of dependencies with python. Not easy for everybody lol

For this there is build.py in l2tdevtools: https://github.com/log2timeline/plaso/wiki/Dependencies#batch-build, not perfect but does a good job

**Comment by winnotor** [comment]
Okay about gift, I use SIFT 3.0 on an Ubuntu 16.04 LTS and there is it in the database repository.

i didn't know the batch-build.
Thank's for all.

It's the reason why i used virtualenv with pip on SIFT 3.0 for not destroy my stable plaso release. 

There is a trouble about plaso 20180127 with source investigation. So i use the lastest plaso 20180630,  Terminates successfully .

**Comment by joachimmetz** [comment]
Thx, for confirming. I'll close this issue then. Work is in the pipeline to get to a new stable libewf but this will depend on available time.
