### ISSUE TITLE
Add parser for Spotlight databases

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2093]
References: https://github.com/ydkhatri/spotlight_parser

**Comment by everestmz** [comment]
Parser coming after https://github.com/libyal/dtformats/pull/4 is finished and merged

**Comment by Onager** [comment]
@toryc has volunteered to pick this issue up

**Comment by joachimmetz** [comment]
Unfortunately the spotlight_parser is a script and not a re-usable Python module.
I've started looking into understanding the data format.

**Comment by joachimmetz** [comment]
PR with basic functionality https://github.com/log2timeline/plaso/pull/3125

**Comment by joachimmetz** [comment]
Initial version of parser merged. A couple of remaining nice to hives like making output message more extensive.
