### ISSUE TITLE
Question: Custom tagging for all events

### ISSUE THREAD

**Issue by masfar85** [log2timeline/plaso#2095]
I am trying to add custom tags to all events within my plaso file during post-processing using psort. I understand the tagging is based on data_type, but if I want to add a tag for "machine name" , which data_type do I specify? What data_type is appropriate for "ALL" records? 
 I have tried the following, but not tags were applied to the timeline:

MachineName
   data_type is '*'

Thanks!

**Comment by joachimmetz** [comment]
You should be able to tag on more than just data_type. Also see https://github.com/log2timeline/plaso/wiki/Event-Filters and https://github.com/log2timeline/plaso/wiki/Analysis-plugin:-tagging

> What data_type is appropriate for "ALL" records?

If I'm not mistaken there is no need to specify "data_type for ALL record". You only need to specify what you want to filter on. In your case you add a filter for machine name.
