### ISSUE TITLE
file system collection loop 

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#21]
When running:
```
PYTHONPATH=~/Projects/plaso/ python ~/Projects/plaso/plaso/frontend/log2timeline.py plaso.db SIFT\ Workstation\ 3.0\ Core\ Drive.vmdk
```

This seems to loop on:
/home/sansforensics/.cpan/sources/authors/id/M/MA/lib/lib/core/common.py/zones.py/core/...

Also see: https://code.google.com/p/plaso/issues/detail?id=96

**Comment by Onager** [comment]
+1 anecdotal report of this occurring.

**Comment by joachimmetz** [comment]
Something for after the 1.3 release there is a lot of work involved working around bugs and limitations in libtsk.

**Comment by Onager** [comment]
Yep. Further anecdata - this was on an ext4 volume.

**Comment by joachimmetz** [comment]
Needs futher analysis and likely a fix in libtsk.

**Comment by joachimmetz** [comment]
Some changes to dfVFS detect realloc entries: https://github.com/log2timeline/dfvfs/issues/49

**Comment by kiddinn** [comment]
is this still an issue? And is this something we can fix or is this a bug in TSK that we have no control over?

**Comment by joachimmetz** [comment]
Just looked at this one this morning. We need to test with latest dfvfs and TSK.

**Comment by joachimmetz** [comment]
With sleuthkit 4.2.0 and dfvfs 20150915, I've not been able to reproduce the behavior with recursive_hasher.py. Think the latest changes to dfvfs log2timeline/dfvfs#49 prevent the issue from happening since the "file" is marked as realloc.

log2timeline still does not like the image, but I've not seen the looping behavior again.

**Comment by joachimmetz** [comment]
Closing issue and having a look at why l2t is not liking the image.
