### ISSUE TITLE
Processing not working after updating plaso from GIFT/dev plaso20180703 to GIFT/stable plaso20180818

### ISSUE THREAD

**Issue by hannipot** [log2timeline/plaso#2101]
**Description of problem:**

Currently I'm trying to automate timlining with GRR data and plaso to process it and push it into timesketch. First I started with Windows Event Logs.

Installed python-plaso and palso-tools via GIFT/PPA. GRR is on that machine (Ubuntu 16.04 LTS) and I installed timesketch using pip install timesketch

I tried the dev version of plaso because the previous stable one 20180630 caused problems. With the dev buld 20180703 I had no problem and everything worked. I thought maybe the issue I had has been solved in the new released version.

The path is readable an accessable. It worked without any problems with the dev version of plaso 20180703.

**Command line and arguments:**

```
/usr/bin/log2timeline.py -q -z UTC --hashers all
                             --workers 6 --buffer_size 2048M --status_view none
                             --parsers winevtx
                             /root/plaso/C.33cb46eca149ba74.plaso
                             /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs
```

**Here is the output from pinfo.py of the plaso file created:**
Processing Windows Event Logs

```
************************** Plaso Storage Information ***************************
            Filename : C.33cb46eca149ba74.plaso
      Format version : 20180101
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
004e1197-b212-41c2-90b1-a2e96c2732ef : 2018-08-22T08:48:16.640376+00:00
--------------------------------------------------------------------------------

**************** Session: 004e1197-b212-41c2-90b1-a2e96c2732ef *****************
                Start time : 2018-08-22T08:48:16.640376+00:00
           Completion time : 2018-08-22T08:48:18.234918+00:00
              Product name : plaso
           Product version : 20180818
    Command line arguments : /usr/bin/log2timeline.py -q -z UTC --hashers all
                             --workers 6 --buffer_size 2048M --status_view none
                             --parsers winevtx
                             /root/plaso/C.33cb46eca149ba74.plaso
                             /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs
  Parser filter expression : winevtx
Enabled parser and plugins : winevtx
        Preferred encoding : UTF-8
                Debug mode : False
          Artifact filters : N/A
               Filter file : N/A
--------------------------------------------------------------------------------

*********************************** Error: 0 ***********************************
           Message : unable to process path specification with error: [Errno
                     14] Bad address
      Parser chain :
Path specification : type: OS, location:
                     /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs/Security.evtx
--------------------------------------------------------------------------------

*********************************** Error: 1 ***********************************
           Message : unable to process path specification with error: [Errno
                     14] Bad address
      Parser chain :
Path specification : type: OS, location:
                     /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs/Application.evtx
--------------------------------------------------------------------------------

*********************************** Error: 2 ***********************************
           Message : unable to process path specification with error: [Errno
                     14] Bad address
      Parser chain :
Path specification : type: OS, location:
                     /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs/System.evtx
--------------------------------------------------------------------------------

No analysis reports stored.
```

**Problem processing Window Registry Hives**
```
********************************** Error: 62 ***********************************
           Message : unable to process path specification with error:
                     pysigscan_scanner_scan_file_object: unable to scan file.
                     libsigscan_scanner_scan_file_io_handle: unable to read
                     buffer.
      Parser chain :
Path specification : type: OS, location:
                     /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/config/SAM
--------------------------------------------------------------------------------
```

**Another dependency problem during execution of log2timeline.py**

/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!

**Python modules installed**

root@XXX:~# pip list
alembic (0.9.5)
amqp (2.2.1)
aniso8601 (1.2.1)
artifacts (20180628)
asn1crypto (0.24.0)
astroid (1.5.3)
backports.functools-lru-cache (1.4)
backports.lzma (0.0.12)
bcrypt (3.1.3)
BeautifulSoup (3.2.1)
bencode.py (2.0.0)
billiard (3.5.0.3)
biplist (1.0.3)
blinker (1.4)
celery (4.1.0)
certifi (2017.7.27.1)
cffi (1.10.0)
chardet (3.0.4)
click (6.7)
configparser (3.5.0)
construct (2.5.3)
coverage (4.4.1)
cryptography (2.2.2)
datasketch (1.2.5)
dfdatetime (20180704)
dfvfs (20180703)
dfwinreg (20180712)
dpkt (1.9.1)
dtfabric (20180707)
efilter (1!1.5)
elasticsearch (6.3.1)
elasticsearch5 (5.5.5)
enum34 (1.1.6)
Flask (0.12.2)
Flask-Bcrypt (0.7.1)
Flask-Login (0.4.0)
Flask-Migrate (2.1.1)
Flask-RESTful (0.3.6)
Flask-Script (2.0.5)
Flask-SQLAlchemy (2.2)
Flask-Testing (0.6.2)
Flask-WTF (0.14.2)
funcsigs (1.0.2)
fusepy (2.0.4)
future (0.16.0)
gunicorn (19.7.1)
hachoir-core (1.3.3)
hachoir-metadata (1.3.3)
hachoir-parser (1.3.4)
idna (2.6)
ipaddress (1.0.22)
isort (4.2.15)
itsdangerous (0.24)
Jinja2 (2.9.6)
kombu (4.1.0)
lazy-object-proxy (1.3.1)
lz4 (2.1.0)
Mako (1.0.7)
MarkupSafe (1.0)
mccabe (0.6.1)
mock (2.0.0)
mysqlclient (1.3.7)
neo4jrestclient (2.1.1)
nose (1.3.7)
numpy (1.13.3)
parameterized (0.6.1)
pbr (3.1.1)
pefile (2018.8.8)
pip (8.1.1)
plaso (20180818)
psutil (5.4.6)
psycopg2 (2.7.5)
pycparser (2.18)
pycrypto (2.6.1)
pycypher (0.5.9)
PyJWT (1.6.4)
pylint (1.7.2)
pyparsing (2.2.0)
pysqlite (2.8.3)
python-dateutil (2.6.1)
python-editor (1.0.3)
pytsk3 (20180225)
pytz (2017.2)
PyYAML (4.1)
pyzmq (17.0.0)
redis (2.10.6)
requests (2.18.4)
setuptools (36.2.7)
singledispatch (3.4.0.3)
six (1.10.0)
SQLAlchemy (1.1.13)
timesketch (20180613)
urllib3 (1.23)
utils (0.9.0)
vine (1.1.4)
virtualenv (15.0.1)
Werkzeug (0.12.2)
wheel (0.29.0)
wrapt (1.10.11)
WTForms (2.1)
XlsxWriter (1.0.5)
yara-python (3.7.0)

**Comment by Onager** [comment]
At first glance, this looks a file system problem - the error being reported here comes from the OS, not Plaso's code: https://docs.python.org/2/library/errno.html#errno.EFAULT

Is  /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs on some sort of a networked file system?

**Comment by nifalle** [comment]
The files are there and accessible. It is a fuse mount of the GRR datastore on the same machine.

**Comment by nifalle** [comment]
I rebooted tha machine and mounted the GRR datasore again. I tried it again for Windows Event Logs. 

**************** Session: 5154b506-255d-4833-bdb4-1f188d0e19a9 *****************
                Start time : 2018-08-22T09:39:20.412592+00:00
           Completion time : 2018-08-22T09:40:05.190670+00:00
              Product name : plaso
           Product version : 20180818
    Command line arguments : /usr/bin/log2timeline.py -q -z UTC --hashers all
                             --workers 6 --buffer_size 2048M --status_view none
                             --parsers winevtx
                             /root/plaso/C.33cb46eca149ba74.plaso
                             /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs
  Parser filter expression : winevtx
Enabled parser and plugins : winevtx
        Preferred encoding : UTF-8
                Debug mode : False
          Artifact filters : N/A
               Filter file : N/A
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
             winevtx : 34144
               Total : 34144
--------------------------------------------------------------------------------

*********************************** Error: 0 ***********************************
           Message : unable to parse recovered event record: 0 with error:
                     pyevtx_file_get_recovered_record_by_index: unable to
                     retrieve recovered record: 0.
                     libcdata_array_get_entry_by_index: invalid entry index
                     value out of bounds.
                     libfwevt_xml_document_substitute_template_value: unable to
                     retrieve template value: 19 from array.
                     libfwevt_xml_document_read_optional_substitution: unable
                     to substitute template value.
                     libfwevt_xml_document_read_element: unable to read
                     optional substitution.
                     libfwevt_xml_document_read_template_instance: unable to
                     read element. libfwevt_xml_document_read_fragment: unable
                     to read document template instance.
                     libfwevt_xml_document_read_with_template_values: unable to
                     read fragment header. libfwevt_xml_document_read: unable
                     to read XML document.
                     libevtx_record_values_read_xml_document: unable to read
                     binary XML document. libevtx_io_handle_read_chunk: unable
                     to read record values XML document.
                     libfdata_list_get_element_value: unable to read element
                     data at offset: 0x001454c8.
                     libfdata_list_get_element_value_by_index: unable to
                     retrieve element value. libevtx_file_get_recovered_record:
                     unable to retrieve record values: 0.
      Parser chain : winevtx
Path specification : type: OS, location:
                     /mnt/grr_datastore/C.33cb46eca149ba74/fs/os/C:/Windows/System32/winevt/Logs/System.evtx
--------------------------------------------------------------------------------

**Comment by nifalle** [comment]
It is working for most of the entries in the EVTX files. Errors are only for 289 of 34k. 
So I guess the reboot solved the issues I encountered before after upgrading to plaso 20180818.

**Comment by Onager** [comment]
I suspect the GRR fuse layer is bit buggy here. Have you tried dftimewolf? It handles the GRR->Plaso->Timesketch workflow via the new GRR client API, which is seeing a bit more love at present.

**Comment by joachimmetz** [comment]
Also did you install dependencies using both pip and deb files (GIFT PPA)? Note that this could versions to clash if pip and apt-get install the same dependencies.

**Comment by orlikoski** [comment]
Have you tried using CDQR https://github.com/orlikoski/CDQR? All of the components to do what you're trying to do are also in the Open Source Skadi tool https://github.com/orlikoski/Skadi

**Comment by nifalle** [comment]
@Onager no I didn't try other tools so far. Thanks for the suggestion! 

@joachimmetz  I installed everything via the GIFT PPA (stable) and apt-get like in the instructions on how to install plaso. After the reboot it seems to work properly.

@orlikoski  I will take a look thank you.
