### ISSUE TITLE
Elasticsearch version dependency check not optional

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2102]
dependencies.py fails when optional dependencies are specified with a version requirement.
```
~$ log2timeline.py examples.desktop examples.desktop.plaso
Checking availability and versions of dependencies.
[FAILURE]    elasticsearch version: 5.4.0 is too old, 6.0 or later required.
[OPTIONAL]    missing: lzma.
```

**Comment by Onager** [comment]
`--no_dependencies_check` is a workaround for this.

**Comment by joachimmetz** [comment]
> dependencies.py fails when optional dependencies are specified with a version requirement.

The reasoning for this is: the dependency is there but it is the incorrect version

The changes in https://github.com/log2timeline/plaso/commit/d4e6e866e855993e948293a2a3060aa11566b148 might have some unwanted side effects for lzma, seeing we no longer do a minimum version check

**Comment by Onager** [comment]
This specific issue was fixed in https://github.com/log2timeline/plaso/commit/d4e6e866e855993e948293a2a3060aa11566b148 the other issue @joachimmetz mentioned is around though. We'll see if the current approach works in the September release.

Removing from milestone.

**Comment by Onager** [comment]
No reports post-September release about lzma problems. Closing issue for now, we can reopen if we see problems.
