### ISSUE TITLE
Add parser for macOS knowledgeC.db

### ISSUE THREAD

**Issue by pstirparo** [log2timeline/plaso#2113]
database containing precise user and application usage.

Reference:
https://www.mac4n6.com/blog/2018/8/5/knowledge-is-power-using-the-knowledgecdb-database-on-macos-and-ios-to-determine-precise-user-and-application-usage

**Comment by moxilo** [comment]
Hi. If nobody has implemented this parser, I have finally time and I can do it. Please kindly confirm if it is implemented or not. I couldn't see it in the code (https://github.com/log2timeline/plaso/tree/master/plaso/parsers/sqlite_plugins) looking for duet or KnowledgeC. Thanks.

**Comment by moxilo** [comment]
@joachimmetz this is done. Tested in version 20190131. I will create a vm with the dev version using last available github Plaso version and submit diff.

**Comment by Onager** [comment]
Great! The dev process is here: https://github.com/log2timeline/l2tdocs/blob/master/process/Code%20review%20process.md and we're looking forward to your pull request!

**Comment by joachimmetz** [comment]
@moxilo that is great news. Thanks. Could you please follow the process indicated by @Onager and get your PR in and start the. He'll loop either @pstirparo or me in when needed.

**Comment by moxilo** [comment]
Hello, 

The dev environment and the new parser is ready, but I am having some issues trying to submit the code to Github (it has been a white without using github). I have followed this manual without luck (https://github.com/log2timeline/l2tdocs/blob/master/process/Code%20review%20process.md), I assume I am doing something wrong sorry for that:

```
root@ubuntu:/plaso# git push
Everything up-to-date
root@ubuntu:/plaso# git checkout
M	plaso/formatters/__init__.py
A	plaso/formatters/mac_knowledgec.py
M	plaso/parsers/sqlite_plugins/__init__.py
A	plaso/parsers/sqlite_plugins/mac_knowledgec.py
Your branch is up-to-date with 'origin/feature'.
root@ubuntu:/plaso# git status
On branch feature
Your branch is up-to-date with 'origin/feature'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   plaso/formatters/__init__.py
	new file:   plaso/formatters/mac_knowledgec.py
	modified:   plaso/parsers/sqlite_plugins/__init__.py
	new file:   plaso/parsers/sqlite_plugins/mac_knowledgec.py

root@ubuntu:/plaso# git push --set-upstream origin feature
Branch 'feature' set up to track remote branch 'feature' from 'origin'.
Everything up-to-date
root@ubuntu:/plaso# git push
Everything up-to-date
root@ubuntu:/plaso# cd ..
root@ubuntu:/# PYTHONPATH=./l2tdevtools python ./l2tdevtools/tools/review.py --project_path=/plaso create-pr
Traceback (most recent call last):
  File "./l2tdevtools/tools/review.py", line 231, in <module>
    if not Main():
  File "./l2tdevtools/tools/review.py", line 180, in Main
    if not review_helper.InitializeHelpers():
  File "/l2tdevtools/l2tdevtools/review_helpers/review.py", line 301, in InitializeHelpers
    project_definition = self._project_helper.ReadDefinitionFile()
  File "/l2tdevtools/l2tdevtools/helpers/project.py", line 197, in ReadDefinitionFile
    with open(project_file, 'r') as file_object:
IOError: [Errno 2] No such file or directory: u'plaso.ini'
root@ubuntu:/# cat plaso/plaso.ini 
[project]
name: plaso
status: beta
name_description: plaso (log2timeline)
maintainer: Log2Timeline maintainers <log2timeline-maintainers@googlegroups.com>
homepage_url: https://github.com/log2timeline/plaso
description_short: Super timeline all the things.
description_long: Plaso (log2timeline) is a framework to create super timelines. Its
    purpose is to extract timestamps from various files found on typical
    computer systems and aggregate them.
```

**Comment by joachimmetz** [comment]
Try running the review script from the plaso directory:

PYTHONPATH=../l2tdevtools ../l2tdevtools/tools/review.py create-pr

**Comment by moxilo** [comment]
Yes, I passed this part. Fighting with pylint right now. I have defined the schema and the SQL queries using triple double quotes (""") instead of using single quotes for each line. Don't see the benefits of using single quotes for each line as the SQL query is more difficult to read.

Example of currently landed in plaso:

```
  QUERIES = [
      (('SELECT f.file_name AS name, f.file_path AS path, '
        'f.file_last_seen AS last_time, g.generation_path AS version_path, '
       ...
        'WHERE f.file_storage_id = g.generation_storage_id;'),
       'DocumentVersionsRow')]
```

Example of my code:
```
  QUERIES = [
      (("""
        SELECT
          ZOBJECT.ZCREATIONDATE AS "entry_creation", 
          ZOBJECT.ZSTARTDATE AS "start", 
          ZOBJECT.ZENDDATE AS "end",
           ...
        FROM ZOBJECT
        LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA = ZSTRUCTUREDMETADATA.Z_PK
        """),
       'KnowledgeCRow')]
```
Due to this I am getting errors in pylint all associated to long SQL queries (8X chars instead of 80) or white spaces:
```
$ pylint --rcfile=/l2tdevtools/.pylintrc plaso/parsers/sqlite_plugins/mac_knowledgec.py  | cut -d ':' -f 3- | cut -d '(' -f -1 | sort | uniq -c
     56  Line too long 
     97  Trailing whitespace
```
So:
```
$ PYTHONPATH=../l2tdevtools python ../l2tdevtools/tools/review.py --project_path=plaso create-pr
...
C:197, 0: Trailing whitespace (trailing-whitespace)
C:198, 0: Trailing whitespace (trailing-whitespace)
C:199, 0: Line too long (94/80) (line-too-long)
C:241, 0: Line too long (81/80) (line-too-long)
C:242, 0: Line too long (82/80) (line-too-long)
C:249, 0: Line too long (81/80) (line-too-long)
C:250, 0: Line too long (82/80) (line-too-long)

Files with linter errors:
plaso/parsers/sqlite_plugins/mac_knowledgec.py

Create-Pr aborted - unable to pass linter.
```

Is there any manner to bypass the pylint checks and send the diff to review, I would like to show the query to understand why in my opinion is better in this way. Thanks.

**Comment by joachimmetz** [comment]
`97  Trailing whitespace` this is a different error, it means you have spaced at the end of your line

The 80 char per line is a hard limit, we can indefinitely debate pros and cons, but this is what we choose for plaso

An alternative you could try
```
  _SQL_QUERY1 = ("""\
        SELECT
          ZOBJECT.ZCREATIONDATE AS "entry_creation", 
          ZOBJECT.ZSTARTDATE AS "start", 
          ZOBJECT.ZENDDATE AS "end",
           ...
        FROM ZOBJECT
        LEFT JOIN ZSTRUCTUREDMETADATA ON ZOBJECT.ZSTRUCTUREDMETADATA =
            ZSTRUCTUREDMETADATA.Z_PK"""

  QUERIES = [
      (_SQL_QUERY1, 'KnowledgeCRow')]
```

**Comment by moxilo** [comment]
Yes sorry, my fault for the trailing space, this is fixed. Only issue is that I have 4 fields in the SCHEMA that are super long. I could declare the schema out and then declare it inside, but not benefits honestly. As an example of variable name (:-1:)
```
Z_DKAPPLICATIONACTIVITYMETADATAKEY__ITEMRELATEDUNIQUEIDENTIFIER VARCHAR,
```
I have disabled and enable the pylint error only in the SCHEMA part, hope it is ok }8-) (at least temporally). 

So almost done, I am getting a permission error:
```
$ PYTHONPATH=../l2tdevtools python ../l2tdevtools/tools/review.py --project_path=plaso create-pr
...
----------------------------------------------------------------------
Ran 1262 tests in 255.610s

OK (skipped=7)
Automatic generated description of code review:
Update lint

Enter a description for the code review or hit enter to use the
automatic generated one:
Mac OS Duet / KnowledgeC Sqlite database parser
Unable to create pull request with error: Failed requesting URL https://api.github.com/repos/log2timeline/plaso/pulls?access_token=... with error: HTTP Error 401: Unauthorized.
```
Thanks and sorry, it has been a long time :(

**Comment by joachimmetz** [comment]
you only need to create the PR once, after that you can just git push updates to your feature branch

**Comment by moxilo** [comment]
Perfect Joachim! I do not know when, but I have made a second commit (Lint fix) over the first one (I miss mercurial):

Pre lint: https://github.com/moxilo/plaso/commit/220e9abb194faf828bfa7abd663955317f61eaa3
Post lint: https://github.com/moxilo/plaso/commit/4c396bc159f7ce39369989a243172fcfbc786caf

Anyways, first one.

**Comment by joachimmetz** [comment]
That is fine and normal (https://github.com/moxilo/plaso/commits/feature) we squash merge PRs on commit so this is no problem. git allows you to rebase and squash the commits but there is no need.

**Comment by moxilo** [comment]
@Onager let me know if you can see the diff as it is in my repo (https://github.com/moxilo/plaso/commit/4c396bc159f7ce39369989a243172fcfbc786caf)

**Comment by joachimmetz** [comment]
@moxilo can you create a PR (pull request)?

**Comment by moxilo** [comment]
@joachimmetz I have tried to create it as described in documentation (https://github.com/log2timeline/l2tdocs/blob/master/process/Code%20review%20process.md), but I am getting unauthorised errors:

$ git branch
* feature
  master
$ PYTHONPATH=../l2tdevtools ../l2tdevtools/tools/review.py create-pr
...
Enter a description for the code review or hit enter to use the
automatic generated one:
Mac OS KnowledgeC
Unable to create pull request with error: Failed requesting URL https://api.github.com/repos/log2timeline/plaso/pulls?access_token=XXXXX with error: HTTP Error 401: Unauthorized.

Thank you and sorry for wasting your time in simple things :(

**Comment by joachimmetz** [comment]
@moxilo you likely need to configure your `.netrc` file. You can also open a PR via the web interface instead
