### ISSUE TITLE
Change l2t_csv to support time values with fraction of second 

### ISSUE THREAD

**Issue by PBreezy** [log2timeline/plaso#2132]
Plaso is only recording the timestamps in hour/minute/seconds and it's dropping the decimal after for milliseconds. 

Source of data was a windows 10 image

My Plaso is currently running on Windows 10

**Comment by joachimmetz** [comment]
What output format did you use?

**Comment by cshanahan** [comment]
**Plaso version:**
20180818

**Operating system Plaso is running on:**
openSUSE Leap 15 64-bit

**Installation method:**
Installed Plaso from source using python virtualenv

**Description of problem:**
I too would like to know how to get millisecond precision from Plaso. Is it possible?
Of course, I am referring to timestamps that contain that degree of precision (i.e., FILETIME).

- What output format did you use?

I almost always use Elastic output, version 5.x to be specific, but l2tcsv doesn't have millisecond precision either.
`
07/17/2014,19:27:14,UTC,....,WEBHIST,MSIE Cache File URL record,Last Checked Time,-,-,Location: ietld:+ACE-hh.ru,Location: ietld:+ACE-hh.ru Number of hits: 1 Cached file size: 0,2,OS:c:\Users\BLAH\AppData\Roaming\Microsoft\Windows\IETldCache\index.dat,0,-,msiecf,cache_directory_index: -2; recovered: False; sha256_hash: 48cfa29b9e915c51665b01a3487c17231f6f4818a1c711594a7450f83c8ba372
07/17/2014,19:27:14,UTC,....,WEBHIST,MSIE Cache File URL record,Last Checked Time,-,-,Location: ietld:+ACE-jv.ru,Location: ietld:+ACE-jv.ru Number of hits: 1 Cached file size: 0,2,OS:c:\Users\BLAH\AppData\Roaming\Microsoft\Windows\IETldCache\index.dat,0,-,msiecf,cache_directory_index: -2; recovered: False; sha256_hash: 48cfa29b9e915c51665b01a3487c17231f6f4818a1c711594a7450f83c8ba372
`

Is there a psort output type that supports precision beyond HH:MM:SS ?

- What parser/data format are you referring to?

Any artifacts that support precision greater than HH:MM:SS, such as FILETIME.

This is from a single record (Windows event log record) in Elastic generated by log2timeline and psort version 20180818. All recent versions of Plaso have the same behavior.

This is the datetime field:
`August 18th 2018, 20:27:21.000`

This is the xml_string field:
`
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-User Profiles Service" Guid="{89B1E9F0-5AFF-44A6-9B44-0A07A7CE5845}"/>
    <EventID>5</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2018-08-18T20:27:21.468037800Z"/>
    <EventRecordID>653079</EventRecordID>
    <Correlation/>
    <Execution ProcessID="1064" ThreadID="5960"/>
    <Channel>Microsoft-Windows-User Profile Service/Operational</Channel>
    <Computer>BLAH-BLAH-BLAH</Computer>
    <Security UserID="S-1-5-18"/>
  </System>
  <EventData>
    <Data Name="File">C:\Users\BLAH\ntuser.dat</Data>
    <Data Name="Key">S-1-5-21-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxx-xxxx</Data>
  </EventData>
</Event>
`

I am using Plaso v20180818 with Elastic and Kibana version 5.6.10. Kibana is configured to use the default dateFormat (MMMM Do YYYY, HH:mm:ss.SSS).

Thank you.

##
Chris

**Comment by PBreezy** [comment]
I used l2tcsv for output

**Comment by joachimmetz** [comment]
At the moment I opt to use a different output format. The l2tcsv format only specified seconds.
https://www.forensicswiki.org/wiki/L2T_CSV

Though it states "in future versions this may change to include ms values in the format of HH:MM:SS.ms", I don't think this was ever implemented. @kiddinn might have more context.

**Comment by Onager** [comment]
@kiddinn any thoughts of making a new version of the schema? L2TCSV2?

**Comment by joachimmetz** [comment]
If we are planning this, I would recommend using a new identifier as L2TCSV2 as well.

**Comment by kiddinn** [comment]
I didn't even notice that I was mentioned here.

We can make a new schema of L2tCSV if we think that is still being used that widely. There are some tools that ingest l2tcsv though, that may need to change, or we can just make a new output module for the second version, that only adds the ms precision.

**Comment by joachimmetz** [comment]
Kristinn if I recall correctly the reason for going with dynamic instead of l2tcsv from the start was the limited information the l2tcsv format can express. It looks like l2tcsv has a version indicator:

```
version: version number of the timestamp object. Current version is 2.
```

A minor iteration on the format could be to bump the version to 3 and add fraction of second support. I assume microseconds precision will be sufficient for a while.

**Comment by joachimmetz** [comment]
Since dynamic format can output similar to l2t_csv and has sub-second precision holding off on creating a new version of l2t_csv format.
