### ISSUE TITLE
Debug pefile installation on fedora

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2152]
COPR installation script may need to have versions specified

**Comment by joachimmetz** [comment]
installation script seems to prefer older pefile from fedora repo above newer one from GIFT COPR

**Comment by joachimmetz** [comment]
python-pefile is renamed to python2-pefile to match new naming schema. This should also solve the version issues.

**Comment by joachimmetz** [comment]
This has been fixed by now
