### ISSUE TITLE
Failure: Elasticsearch 5.5.1 is too old 

### ISSUE THREAD

**Issue by Pitbully7** [log2timeline/plaso#2154]
The Windows version of log2timeline does not include the updated elasticsearch as 5.5.1 is too old
log2timeline.exe \test.plaso \file.e01
Plaso version 20180818
Windows 10 OS
Downloaded package 
I tried to install Elasticsearch 6.4 but the prepackaged exe does not detect it 

Thanks

**Comment by joachimmetz** [comment]
How did you install plaso? L2tbinaries should provide you with both elasticsearch-py 6 and 5. And this runs as part of our city tests.

**Comment by jvaldezjr1** [comment]
I have a simliar error message, but I've just unzipped the windows binaries for plaso.

**Comment by joachimmetz** [comment]
I see this is the PyInstaller build version of plaso.

**Comment by jvaldezjr1** [comment]
That did the trick, thanks.

**Comment by Onager** [comment]
@Pitbully7 are you still seeing this on the latest release?

**Comment by Pitbully7** [comment]
It works without the --no_dependencies_check. Elasticsearch shows as optional.

Thanks
