### ISSUE TITLE
Preprocess is no longer triggered due to multi volume changes

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#217]
For some reason GuessOS does not work anymore, resulting in no preprocessing being run on disk images, and no filter selection being done.

    In [5]: list(searcher.Find(find_specs=find_specs))
    Out[5]: []

Using the searcher that is passed in to the function and adding an ipython shell for debug (Line 201 in the preprocessors interface file)

    In [1]: fs = searcher._file_system
    In [2]: fs.LOCATION_ROOT
    Out[2]: u'/'

    In [3]: fs.TYPE_INDICATOR
    Out[3]: u'TSK_PARTITION'

    In [4]: root = fs.GetRootFileEntry()

    In [5]: for s in root.sub_file_entries:
        print s.name
       ...: 
    
    
    p1
    
    
    In [6]: 

Need to fix this and add tests to catch this regression going forward.

* [x] Fix bug: https://codereview.appspot.com/242020043/
* [ ] Add test to l2t and/or engine to make sure preprocess is working

**Comment by joachimmetz** [comment]
Looks like the entire preprocess is not triggered.

**Comment by kiddinn** [comment]
this is done

**Comment by joachimmetz** [comment]
Is pending to add tests.
