### ISSUE TITLE
Timezone Bug in Windows PSORT

### ISSUE THREAD

**Issue by big-husky** [log2timeline/plaso#2177]
**Description of problem:**

psort.exe when given a timezone using '-z <timezone>' doesn't correct the time.  Confirmed the storage file had time in UTC and the same time is printed by psort.exe regardless of which timezone is specified.  It does print the timezone that was selected in the output file.

**Command line and arguments:**

psort.exe -z EST5EDT -o l2tcsv -w test.l2tcsv storage.plaso

**Source data:**

Should be easily reproducible with any log2time storage output.

**Plaso version:**

20180930
20180630

**Operating system Plaso is running on:**

Windows 10 1803

**Installation method:**

zip package & Visual C++ 2008 redistributable

**Debug output/tracebacks:**

Ran psort.exe with '-d' and did not see any additional output.

**Comment by Onager** [comment]
This looks like a duplicate of #2067 which I haven't had a chance to fix yet =( 

I'll look into this a little more to confirm.

**Comment by big-husky** [comment]
Duplicate of #2067
