### ISSUE TITLE
log2timeline Crash on Windows

### ISSUE THREAD

**Issue by big-husky** [log2timeline/plaso#2178]
**Description of problem:**

log2timeline.exe fails to run on windows with a traceback.

**Command line and arguments:**

.\log2timeline.exe -z EST5EDT --status_view window --logfile ..\plaso_test
\d3\plaso-error.log --parsers filestat ..\plaso_test\d3\storage.plaso ..\plaso_test\data.E01

**Source data:**

Crashed same way on two different images.  First was a NTFS volume, second was a disk from an Android.

**Plaso version:**

20180930

**Operating system Plaso is running on:**

Windows 10 1803

**Installation method:**

zip package & Visual C++ 2008 redistributable

**Debug output/tracebacks:**

plaso - log2timeline version 20180930

Source path     : C:\Users\big-husky\Downloads\plaso_test\data.E01
Source type     : storage media image
Processing time : 00:00:15

Tasks:          Queued  Processing      Merging         Abandoned       Total
                1       0               0               0               1

Identifier      PID     Status          Memory          Sources         Events          File
Main            1104    running         0 B             1 (0)           0 (0)
Worker_00       9856    idle            0 B             32 (32)         0 (0)           TSK:/
Worker_01       4968    idle            0 B             0 (0)           0 (0)
Worker_02       14596   idle            0 B             0 (0)           0 (0)
Worker_03       7612    idle            0 B             0 (0)           0 (0)
Worker_04       9236    idle            0 B             0 (0)           0 (0)
Worker_05       10720   idle            0 B             0 (0)           0 (0)
Worker_06       10448   idle            0 B             0 (0)           0 (0)

Traceback (most recent call last):
  File "tools\log2timeline.py", line 68, in <module>
  File "tools\log2timeline.py", line 54, in Main
  File "plaso\cli\log2timeline_tool.py", line 445, in ExtractEventsFromSources
  File "plaso\multi_processing\task_engine.py", line 827, in ProcessSources
  File "plaso\multi_processing\task_engine.py", line 346, in _ProcessSources
  File "plaso\multi_processing\task_engine.py", line 452, in _ScheduleTasks
  File "plaso\multi_processing\task_engine.py", line 200, in _MergeTaskStorage
  File "plaso\storage\interface.py", line 1442, in GetProcessedTaskIdentifiers
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'..\\plaso_test\\d3\\tmp6oqyaq\\processed\\*.*'
Failed to execute script log2timeline

**Comment by big-husky** [comment]
Hmm, I tried this on my working plaso, 20180630, and it crashed just about the same way.  I rebooted the system and now the 20180630 install is working.  I'll try to see if I can reproduce the above on 20180930 in a few days and report back.

**Comment by big-husky** [comment]
I just tried 20180930 and it is working.  Not sure what was messed up that would cause the above and resolve itself after a reboot.  Closing issue.

**Comment by joachimmetz** [comment]
> Not sure what was messed up that would cause the above and resolve itself after a reboot. Closing issue.

The error indicates clearly that Windows has the file open and log2timeline can therefore not access it. Unfortunately this is a fatal Windows specific issue. This could be caused by e.g. programs like AV trying to scan the plaso temporary files.
