### ISSUE TITLE
files with same path overwritten by image_extract.py

### ISSUE THREAD

**Issue by stuhli** [log2timeline/plaso#2183]
Hi all!

When `image_export.py` recognizes more than one partition in an image file it interactively asks the user which partition should be processed. The user has the possibility to choose all partitions by typing "all".

**Problem:**
Because the export is done for all partitions into the same directory (either the default one or the choosen one by `-w`), files with the same filenames / pathes are skipped for the following partitions (for example `$MFT` or other NTFS metadata files). This is logged to stdout though. But with a lot of log output (because of same-file-duplicate-messages) this can be overlooked quickly.

A relevant command line could be:
`image_export.py -f filter.txt -d -w <OUTPUT_FOLDER> <IMAGE_FILE>`

The argument `--include_duplicates` does not change anything (but according to the help it is only relevant for included VSSs).

My question is: is this the intended behavior? I haven't found anything related in other issues (including #109). An extraction to different subfolders (e. g. `p1`, `p2`, ...) of `<OUTPUT_FOLDER>` would prevent this.

I'm not able to provide source data but this can be reproduced with images containing more than one partition with an existing file system and duplicated files / pathes in each file systems.

The following example is generated by only filtering for `$MFT` and `$LogFile` (with `filter.txt`) using `-d`:

>The following partitions were found:
>
>Identifier      Offset (in bytes)       Size (in bytes)
>p1              1048576 (0x00100000)    100.0MiB / 104.9MB (104857600 B)
>p2              105906176 (0x06500000)  59.9GiB / 64.3GB (64316506112 B)
>
>Please specify the identifier of the partition that should be processed.
>All partitions can be defined as: "all". Note that you can abort with Ctrl^C.
>all
>
>Export started.
>Extracting file entries from: TSK:/
>Extracting file entries from: TSK:/
>[skipping] unable to export contents of file entry: TSK:/$LogFile because exported file: output_folder/_LogFile already exists.
>[skipping] unable to export contents of file entry: TSK:/$MFT because exported file: output_folder/_MFT already exists.
>Export completed.

Plaso version: 20180127

OS version: Ubuntu 16.04.4 LTS

Image OS version: different Windows versions (only tested with NTFS)

Thank you for your help!

**Comment by Onager** [comment]
Thanks for the report @stuhli - this looks like less-than-optimal behavior. We'll look at a fix when as time becomes available.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/d81513e2b21996d3031541bca5e727b56692484b addresses multi-volume issue
