### ISSUE TITLE
log2timeline does not process real-world sized mactime body files

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2184]
**Description of problem:**

log2timeline does not process real-world sized mactime body files.  This is a small image used in a classroom.  The test data body file does work.

I have seen Issues #1760 & #2056 and they seem to acknowledge the size limitation but as far as I can tell,  no solution is offered. 

**Command line and arguments:**

```log2timeline --no_dependencies_check --no_vss --debug --logfile test_body.log --parsers mactime mftecmd_body.plaso MFTECmd_Output.body```

Log file entry
```2018-10-20 11:36:47,118 [DEBUG] (MainProcess) PID:8660 <extractors> mactime unable to parse file: OS:D:\google-drive\DFIR\plaso_mft\MFTECmd_Output.body with error: [mactime] Unable to parse DSV file: OS:D:\google-drive\DFIR\plaso_mft\MFTECmd_Output.body size of file exceeds maximum supported size```

**Plaso version:** . 20180818 running on Windows 10

**Comment by Onager** [comment]
Per #2046 the file size limit was removed in https://github.com/log2timeline/plaso/commit/df20c2635eda9a1a53770cefd4237984f6768795, and the fix released in 20180930.
