### ISSUE TITLE
Error: Unable to read artifact definitions

### ISSUE THREAD

**Issue by 3Fingers** [log2timeline/plaso#2186]
**Description of problem:**

Trying to run log2timeline.exe (Windows 10) over E01 image.
ERROR: Unable to read artifact definitions from C:\Tools\Plaso\artifacts with error: At start Artifact definition: HapoopAppRoot found undefined label: Hadoop.

**Command line and arguments:**

log2timeline.exe G:\body.l2t D:\image.e01

**Source data:**

Image of Windows 10 based system

**Plaso version:**

20180930

**Operating system Plaso is running on:**

Windows 10 Pro

**Installation method:**

Downloaded latest package release from site. Python 2.7 and 3.6, and Visual C++ packages already installed.

**Debug output/tracebacks:**

**Comment by ggala** [comment]
Comment out the line 'labels: [Hadoop]' in file 'C:\Tools\Plaso\artifacts\hadoop.yaml'

**Comment by goorgoorlou** [comment]
Already reported: https://github.com/log2timeline/plaso/issues/2170

**Comment by Onager** [comment]
Duplicate of #2170
