### ISSUE TITLE
improve docker experience

### ISSUE THREAD

**Issue by aguilajesus** [log2timeline/plaso#2194]
tracking list for some docker ideas:
 - [ ] Improve documentation in [dockerhub](https://hub.docker.com/r/log2timeline/plaso/)
 - [ ] Create wrapper aliases for plaso/tools i.e docker_psort.sh for `docker run <image> ....`
 - [ ] abstract volumes mapping (probably only for image files/dirc)
 - [ ] Add script to build image from dockerfile.

**Comment by joachimmetz** [comment]
@aguilajesus are you actively working on this? If so feel free to re-add yourself and please sync with @Onager and @rgayon for docker related issue https://github.com/log2timeline/plaso/issues/2284.

**Comment by joachimmetz** [comment]
@Onager another docker related issue, is this still wanted, WIP or completed?

**Comment by Onager** [comment]
This is still wanted.

**Comment by joachimmetz** [comment]
@Onager can you highlight what needs to be done here and let's plan this for the may release, since docker is now the preferred deployment method

**Comment by joachimmetz** [comment]
No response closing issue.
