### ISSUE TITLE
Question: Is there a way to negate the winreg_default parser?

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#2200]
**Description of problem:**

I would like to omit the winreg_default parser when running the win7 parser preset.  I have tried the following command:
```log2timeline --debug --log_file test.log --no_vss  --parsers win7,!winreg_default -f filter_small.txt  c-drive.E01```

I get the following warning message:
```2018-11-12 16:12:08,342 [WARNING] (MainProcess) PID:60400 <manager> The excluded parser: winreg_default is not associated with the included parsers: esedb, chrome_preferences, winfirewall, recycle_bin, filestat, sqlite, sccm, amcache, lnk, symantec_scanlog, winevtx, plist, binary_cookies, pe, skydrive_log_old, opera_global, custom_destinations, chrome_cache, winreg, msiecf, bencode, skydrive_log, openxml, usnjrnl, opera_typed_history, winjob, olecf, prefetch, java_idx, firefox_cache, mcafee_protection, gdrive_synclog. Ignoring excluded parser.```

I have provided a snippet of the pinfo output below showing that winreg_default events were processed.

Other uses of the negate (!) operator like the one below seem to work.
```--parsers win7,!winevtx,!filestat,!usnjrnl,!mft,```

Is there something "special" about the winreg_default parser? 

Thanks for any help you can provide.

-Mark

**Plaso version:**

Windows 20180930

```--------------------------------------------------------------------------------

************************* Events generated per parser **************************
                Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
                              bagmru : 336
               explorer_mountpoints2 : 14
              explorer_programscache : 1
                            filestat : 1860
                                 lnk : 1069
               microsoft_outlook_mru : 1
                      mrulist_string : 43
           mrulistex_shell_item_list : 10
                    mrulistex_string : 28
     mrulistex_string_and_shell_item : 24
mrulistex_string_and_shell_item_list : 1
                           msie_zone : 12
        olecf_automatic_destinations : 316
                       olecf_default : 24
                             openxml : 9
                            prefetch : 1104
                         recycle_bin : 6
                         shell_items : 1716
                          userassist : 300
                         windows_run : 2
                  windows_typed_urls : 2
                      winreg_default : 17200
                               Total : 24078
--------------------------------------------------------------------------------```

**Comment by Onager** [comment]
This could be because winreg_default is a winreg plugin, not a standalone parser.

**Comment by joachimmetz** [comment]
Closing issue in favor of https://github.com/log2timeline/plaso/issues/3690
