### ISSUE TITLE
Performance Issue with 20180930

### ISSUE THREAD

**Issue by big-husky** [log2timeline/plaso#2202]
**Description of problem:**

I ran a few tests of all parsers against a Windows 10 image I made recently.  For Plaso I used the Windows versions 20180630 and 20180930 on Windows 10 1803.  The 20180930 took significantly longer to run, 55 hours compared to 23 hours on 20180630.

I'd like to help track down where the speed difference is coming from, can anyone provide some tips to help troubleshoot this?

**Command line and arguments:**

.\log2timeline.exe -z EST5EDT --status_view window --logfile plaso-error.log storage.plaso c_drive.E01

**Source data:**

I'm able to share the source image as it may contain private information.

**Plaso version:**

For example 20180930 and 20180630 as comparison/reference.

**Operating system Plaso is running on:**

Windows 10 1803

**Installation method:**

Packaged release zip files, 20180930 is the most recent release of that version.

**Debug output/tracebacks:**

I did not run a debug, I'd like feedback on best approach before making another run since it takes a lot of time.

**Comment by joachimmetz** [comment]
@big-husky could you run some tests with profiling to see where potential differences might be. Also see: https://github.com/log2timeline/plaso/wiki/Profiling

**Comment by joachimmetz** [comment]
Closing issue, unable to address issue without necessary input.
