### ISSUE TITLE
microsoft defender eventlog strings

### ISSUE THREAD

**Issue by dominiquevocat** [log2timeline/plaso#2204]
Hi, i found this project because i am looking for a way to generate a few tables or a database with all the strings in english for referencing when reading windows eventlog messages in xml format.

So i stumbled over then winevt-rd.db and quite a few eventlogs that i kinda need (especially defender) are missing.

Is it pobbile you would generate a newer version including defender or how can i generate the database with my list of event log channels myself (using some python script or whatever)?

**Comment by joachimmetz** [comment]
No follow up from reporter, assuming question was answered.
