### ISSUE TITLE
Using psort timesketch output with TimeSketch Docker

### ISSUE THREAD

**Issue by orlikoski** [log2timeline/plaso#2237]
**Description of problem:**
The issue I'm having is the TimeSketch output option for `psort` is disabled when running TimeSketch as a Docker while Plaso is installed on the host machine directly. The machine is an Ubuntu 16.04 Server using the current version Plaso installed using apt-get. Since both the Postgres and ES ports are exposed shouldn't psort be able to insert to TimeSketch? Is there a way to force it to try?  Or am I missing a key bit of knowledge about how the check for that works.

This is the working `docker-compose.yml` [https://github.com/orlikoski/Skadi/blob/master/Docker/docker-compose.yml](url) for the Docker instances

I know that the web API option is available for TimeSketch but it is not as script friendly and it has other security related concerns in about having to use usernames/passwords.  `psort` is much cleaner and safer.  

Thanks!

**Comment by Onager** [comment]
Hey @orlikoski - the psort timesketch export needs the Timesketch python code to be installed on the machine it's running on in order to do load the data into Elasticsearch. If you install Timesketch via pip on the host machine, this should be resolved.
@berggren because we've talked about making an apt-installable Timesketch client package that would also address this.

**Comment by orlikoski** [comment]
Oh, interesting. I did not know that. I will give that a try and report back how it worked

**Comment by orlikoski** [comment]
An update on this. It doesn't work out of the box with the TimeSketch docker image.  The pip install version requires the same `/etc/timesketch.conf` file and work will need to be done by each user to make sure that file is in sync with the all the support components inside of Docker space as well as on the host itself. 

Some of those settings are ephemeral and don't persist between docker container restarts/rebuilds so it's going to be a challenge. I'll keep working on it and post back here if I solve it in a repeatable way.

**Comment by orlikoski** [comment]
I was able to solve the issue and it required the following changes to the Docker project files found on the TimeSketch github.

The changes that were required were:

 - Heavily modify the docker-entrypoint.sh
 - Modify the Dockerfile
 - Heavily modify the docker-compose.yml
 - Share the /etc/timesketch.conf file between host and Dockers
 - Install TimeSketch on Host but use the Docker containers with, exposed ports routed through Nginx, for Postgres, ES, and TimeSketch

I'm doing final testing but sometime this week I'll post the link to my Skadi repo that has all of those changes merged to the master branch.
