### ISSUE TITLE
Add support to parse MacOS unified logs

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2242]
Add support to parse MacOS unified logs
https://developer.apple.com/documentation/os/logging

Seeing that the tracev3 files reference data in the uuidtext files this likely needs to be a file entry parser
https://github.com/libyal/dtformats/blob/master/documentation/Apple%20Unified%20Logging%20and%20Activity%20Tracing%20formats.asciidoc

This currently blocked, working with ydkhatri to get https://github.com/ydkhatri/UnifiedLogReader into a state that it can be used by plaso. Then will look at what is needed to integrated into plaso.

**Comment by joachimmetz** [comment]
https://github.com/mac4n6/Presentations/blob/master/Logs%20Unite!%20-%20Forensic%20Analysis%20of%20Apple%20Unified%20Logs/LogsUnite.pdf

**Comment by tyrells** [comment]
Found some information on other python tools which could be leveraged:
- https://github.com/ydkhatri/mac_apt
- https://jsac.jpcert.or.jp/archive/2022/pdf/JSAC2022_2_kobayashi_en.pdf

**Comment by joachimmetz** [comment]
@tyrells unfortunately mac_apt is not a reusable module. We worked in the past making https://github.com/ydkhatri/UnifiedLogReader more modular and testable, but this needs a lot of work. If you strongly feel about this I recommend helping getting that project in a better shape.
