### ISSUE TITLE
Some documentation links are not properly working

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2245]
When visiting https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html#high-memory-usage and selecting "Profiling memory usage" (which points to https://plaso.readthedocs.io/en/latest/sources/user/Profiling.html#profiling-memory-usage) I get a page not found.

**Comment by Onager** [comment]
The profiling page is actually in the developer docs, not user - I'll change this together with #2220

**Comment by joachimmetz** [comment]
Looks like this has been fixed, closing issue.
