### ISSUE TITLE
Change plaso.kiddaland.net to redirect to readthedocs

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2252]
plaso.kiddaland.net currently redirect to the github wiki change it to redirect to readthedocs

**Comment by Onager** [comment]
@kiddinn Can you take care of this please?

**Comment by Onager** [comment]
Ping for @kiddinn

**Comment by kiddinn** [comment]
ack on my side, I'll fix this

**Comment by kiddinn** [comment]
domain records changed, will take a bit for the changes to be reflected

**Comment by kiddinn** [comment]
I'll keep this issue opened until I can confirm this is completed

**Comment by kiddinn** [comment]
this is done now

**Comment by joachimmetz** [comment]
Confirmed, for me it took quite some time for DNS to catch up
