### ISSUE TITLE
UserAssist entries need decoding

### ISSUE THREAD

**Issue by InsaneTechnologies** [log2timeline/plaso#2270]
**Description of problem:**

UserAssist registry values are ROT encoded.

**Command line and arguments:**

"log2timeline.py" "--partition" "all" "--vss_stores" "all" "--status_view" "linear" "--process_archives" "--parsers" "amcache,appcompatcache,bash,bash_history,bagmru,bencode_transmission,bencode_utorrent,binary_cookies,ccleaner,chrome_cache,chrome_cookies,chrome_extension_activity,chrome_history,chrome_preferences,cron,explorer_mountpoints2,explorer_programscache,filestat,firefox_cache,firefox_cache2,firefox_cookies,firefox_downloads,firefox_history,google_drive,hachoir,java_idx,lnk,mcafee_protection,mft,microsoft_office_mru,microsoft_outlook_mru,mrulist_shell_item_list,mrulist_string,mrulistex_shell_item_list,mrulistex_string,mrulistex_string_and_shell_item,mrulistex_string_and_shell_item_list,msie_zone,msiecf,mstsc_rdp,mstsc_rdp_mru,network_drives,olecf,openxml,opera_global,opera_typed_history,pe,pls_recall,prefetch,recycle_bin,recycle_bin_info2,rplog,safari_history,sccm,sophos_av,sqlite,syslog,ssh,symantec_scanlog,userassist,usnjrnl,windows_boot_execute,windows_boot_verify,windows_run,windows_sam_users,windows_services,windows_shutdown,windows_task_cache,windows_timezone,windows_typed_urls,windows_usb_devices,windows_usbstor_devices,windows_version,winevt,winevtx,winfirewall,winjob,winlogon,winrar_mru,winreg,winreg_default,xchatlog,xchatscrollback" "--hashers" "md5" "--workers" "8" "Results_20-Dec-18_03-16-59/DATA.plaso" "Results_20-Dec-18_03-16-59/artifacts/DATA" "--no_dependencies_check"

**Source data:**

Windows Server

**Plaso version:**

Plaso Version: 20180930

**Operating system Plaso is running on:**

Debian Stretch/Sid

**Installation method:**

SKADI VM (https://github.com/orlikoski/Skadi)

**Debug output/tracebacks:**

Will re-run tomorrow (takes 2 1/2 hours to process and heading home!)

Output as seen:
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{F4E57C4B-2036-45F0-A9AB-443BCFE33D9F}\Count] HRZR_PGYFRFFVBA: [REG_BINARY] HRZR_PGYPHNPbhag:pgbe: [REG_BINARY] P:\CebtenzQngn\Zvpebfbsg\Jvaqbjf\Fgneg Zrah\Srgpu Cbegny.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\ANFU Betnavfngvba Pregvsvpngr Genpxre.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\Bssvpr Zrqvp.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\CenpFbsg.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\Cerprqrapr Pbaarpgbe.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\Cra PF PNG4.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\ENVQ Jro Pbafbyr 2.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\ErcbegArg.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\UPA Znvagranapr.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\UrnyguYvax Nqinaprq Bcgvbaf.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\UrnyguYvax Pyvrag.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\Zbmvyyn Sversbk.yax: [REG_BINARY] P:\Hfref\Choyvp\Qrfxgbc\Zrqvpny Qverpgbe.yax: [REG_BINARY]

**Comment by joachimmetz** [comment]
Having look after the December release is done

**Comment by joachimmetz** [comment]
Command used to generate timeline: `cdqr.py --es_es elasticindexname -z --max-cpu ziparchivename.zip`

**Comment by joachimmetz** [comment]
This does not appear to be a plaso issue. Closing this.
