### ISSUE TITLE
Run time always ends with a message about the tool being aborted

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#228]
Each time you run log2timeline it will end with the following message:

    All extraction workers completed - waiting for storage.

    Processing aborted.

That is irrelevant whether the tool actually successfully completed or the user aborted the processing.

**Comment by kiddinn** [comment]
The reason is inside the tools/log2timeline.py

```python
    result = self._front_end.ProcessSources(
        self._source_path_specs,
        filter_file=self._filter_file,
        hasher_names_string=self._hasher_names_string,
        parser_filter_string=self._parser_filter_string,
        single_process_mode=self._single_process_mode,
        status_update_callback=status_update_callback,
        storage_serializer_format=self._storage_serializer_format,
        timezone=self._timezone)

    if result:
      self._output_writer.Write(u'Processing completed.\n')
    else:
      self._output_writer.Write(u'Processing aborted.\n')
    self._output_writer.Write(u'\n')
```

The tool is expecting that front end ProcessSources  returns a value, but ProcessSources has no return value, and thus always returns None back..... thus the tool will always print out "`Processing aborted.`"

**Comment by kiddinn** [comment]
being fixed in https://codereview.appspot.com/245860043/

**Comment by kiddinn** [comment]
assigning to joachim since the cl he has out fixes it

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/9a3c505eddef076ea43d43cd107e179d2385744d
