### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2302]
In https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html#tests

"Plaso follows the log2timeline style guide." 

Link to style guide is broken https://github.com/log2timeline/l2tdocs/blob/master/process/Style-guide.html

**Comment by joachimmetz** [comment]
@Onager was this addressed with your latest changes?

**Comment by Onager** [comment]
Yes, this was fixed a while ago.
