### ISSUE TITLE
Add end-to-end test that processes an Android image

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2313]
Android Nougat image available here: https://aboutdfir.com/dfir-research/

**Comment by joachimmetz** [comment]
The link no longer refers to an Android image, but I'll do some testing with those of the forensics corpora and add them to the e2e tests.

**Comment by joachimmetz** [comment]
uploading android 7 and android 8 disk image from forensics corpora to e2e test data repository

**Comment by joachimmetz** [comment]
uploading android 11 GSI image to e2e test data repository
