### ISSUE TITLE
Release version 20190131

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2323]
- [x] ~~Update version~~
- [x] ~~Update parser and plugins documentation~~
  - ~~`PYTHONPATH=. ./tools/log2timeline.py --parsers list --use-markdown > docs/sources/user/Parsers-and-plugins.md`~~
  - ~~https://github.com/log2timeline/plaso/pull/2324~~
- [x] ~~Create github release and tag~~
- [x] ~~Upload source package and signature to Github release page~~
  - ~~`./setup.py sdist_test_data`~~
  - ~~`gpg --armor --detach-sign dist/plaso-$VERSION.tar.gz > dist/plaso-$VERSION.tar.gz.asc`~~
- [x] ~~[Update pypi](https://github.com/log2timeline/l2tdocs/blob/master/process/PyPI.md)~~
- [x] ~~[Update GIFT PPA](https://github.com/log2timeline/l2tdocs/blob/master/process/GIFT%20PPA.md)~~
  - ~~Build Ubuntu source debs: `PYTHONPATH=. ./tools/build.py --preset plaso dpkg-source`~~
  - ~~Update GIFT PPA testing, dev, stable~~
  - **16.04 overwrites shebang, but 18.04 does not :(...**
- [x] [Update GIFT COPR](https://github.com/log2timeline/l2tdocs/blob/master/process/GIFT%20COPR.md)
  - ~~Build Fedora source rpms: `PYTHONPATH=. ./tools/build.py --preset plaso srpm`~~
  - ~~Update GIFT COPR testing, dev, stable~~
  - **Building on COPR is flaky**
  - ~~Additional changes to l2tdevtools required https://github.com/log2timeline/l2tdevtools/pull/577~~
  - Artifacts missing artifacts-data in python3 package
  - Tested FC27 dev, FC27 stable, FC28 dev, FC28 stable
- [x] ~~[Update l2tbinaries](https://github.com/log2timeline/l2tdocs/blob/master/process/l2tbinaries.md) macos~~
  - ~~Build MacOS binaries: `PYTHONPATH=. ./tools/build.py --preset plaso pkg`~~
  - ~~update l2tbinaries, testing, dev, stable~~
- [x] ~~[Update l2tbinaries](https://github.com/log2timeline/l2tdocs/blob/master/process/l2tbinaries.md) win32~~
  - ~~Build 32-bit Windows binaries: `PYTHONPATH=. ./tools/build.py --preset plaso msi`~~
  - ~~update l2tbinaries, ~~testing~~, dev, stable~~
- [x] ~~[Update l2tbinaries](https://github.com/log2timeline/l2tdocs/blob/master/process/l2tbinaries.md) win64~~
  - ~~Build 64-bit Windows binaries: `PYTHONPATH=. ./tools/build.py --preset plaso msi`~~
  - ~~update l2tbinaries, ~~testing~~, dev, stable~~
- [x] [Update docker image](https://github.com/log2timeline/l2tdocs/blob/master/process/Maintainers%20guide.md#updating-the-plasos-image-on-dockers-hub-to-the-latest-version-in-ppa)
- [x] Update Github release with binaries
  - [Build macOS packaged release](https://github.com/log2timeline/l2tdocs/blob/master/process/Maintainers%20guide.md#macos-packaged-release)
  - ~~[Build Windows pyinstaller packaged release](https://github.com/log2timeline/l2tdocs/blob/master/process/Packaging%20with%20pyinstaller.md)~~
- [x] Write and publish blog post

**Comment by joachimmetz** [comment]
@Onager do we need to add a step to regenerate readthedocs for a release as well?

**Comment by Onager** [comment]
No, they're rebuilt on each push and tag.

**Comment by joachimmetz** [comment]
Hmm then the https://github.com/log2timeline/plaso/commit/4d5d2392076b0c850f748173c5c6a900470b5c4e changes don't seem to have (yet) propagated

e.g. https://plaso.readthedocs.io/en/latest/sources/user/Fedora-Core-Packaged-Release.html#fedora-core-27-and-28

**Comment by joachimmetz** [comment]
readthedocs seems to have caught up
