### ISSUE TITLE
Add parser for NetworkMiner 2.4 CSV exports

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#2339]
NetworkMiner 2.4 has proper datetime format in it's exported CSV file. Let's create a parser for it.
https://www.netresec.com/?page=Blog&month=2019-01&post=NetworkMiner-2-4-Released

**Comment by erik4711** [comment]
See the attached CSV output from NetworkMinerCLI. The "*.FileInfos.csv" export if probably the one that is most interesting to include in the timeline.
[NetworkMiner-CSV-Export.zip](https://github.com/log2timeline/plaso/files/2828196/NetworkMiner-CSV-Export.zip)
