### ISSUE TITLE
Python3 default plaso of GIFT PPA Xenial release prevents plaso to detect Python 2 timesketch installation

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2344]
Filing for tracking - user reports that psort in Plaso 20190131 has a shebang of `#!/usr/bin/python3.5`  in the Python 2 package.

**Comment by Onager** [comment]
This is also likely the source of the Timesketch end to end test breaking, as there's no Timesketch Python3 package.

**Comment by joachimmetz** [comment]
which file? which ubuntu?

**Comment by Onager** [comment]
Ubuntu, psort.py

**Comment by joachimmetz** [comment]
Which version of Ubuntu

Per comments in https://github.com/log2timeline/plaso/issues/2323
* **16.04 overwrites shebang, but 18.04 does not :(...**

**Comment by joachimmetz** [comment]
So 16.04 plaso-tools installation should be pinned to python3-plaso 
And 18.04 plaso-tools installation should be pinned to python-plaso

**Comment by Onager** [comment]
I don't understand - pinned how? What should do the pinning? Where should this pinning occur?

**Comment by joachimmetz** [comment]
pinning as in dependency/version pinning this is done via "depends:" in the dpkg configuration

**Comment by joachimmetz** [comment]
https://launchpad.net/~gift/+archive/ubuntu/stable/+sourcefiles/plaso/20190131-2ppa1~xenial/plaso_20190131-2ppa1~xenial.debian.tar.xz

**Comment by joachimmetz** [comment]
```
Package: plaso-tools
Architecture: all
Depends: python3-plaso, ${python3:Depends}, ${misc:Depends}
Description: Tools of plaso (log2timeline)
 Plaso (log2timeline) is a framework to create super timelines. Its
 purpose is to extract timestamps from various files found on typical
 computer systems and aggregate them.
```

**Comment by joachimmetz** [comment]
There should be no shebang in the `python-plaso` package. Could you please point me to the original issue?

**Comment by Onager** [comment]
This was reported directly, specifically because the Timesketch output wasn't working, which makes sense as there's no Timesketch Python 3 package.

**Comment by joachimmetz** [comment]
Chatting with @berggren the actual issue is that the Python3 default plaso of GIFT PPA Xenial release prevents plaso to detect Python 2 timesketch installation using psort.

**Comment by joachimmetz** [comment]
Possible options

* install timesketch as python 3 (pip3)
* use bionic instead
* try if changing the build order in plaso rules from 2 then 3 to 3 then 2 specifically for Xenial

**Comment by joachimmetz** [comment]
@Onager @berggren also let's make sure we set up an integration test for plaso-timesketch

**Comment by Onager** [comment]
The integration test is running and caught this issue, see https://github.com/log2timeline/plaso/issues/2344#issuecomment-461340055

This only started firing after the packages were updated in stable, however.

**Comment by berggren** [comment]
Timesketch mitigation and fixes in the works:
* Push py3 compatible release to enable pip3 installs
* Change documentation for TS to refelct this for 16.04 folks
* Use 18.04 for docker installs

Tracking in: https://github.com/google/timesketch/issues/823

**Comment by joachimmetz** [comment]
Closing this in favor of the timesketch issue.
