### ISSUE TITLE
artifacts add default for _FAMILY_AND_VERSION_PER_NAME

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2351]
```
Processing started.
2019-02-16 10:40:23,288 [INFO] (MainProcess) PID:7212 <engine> Preprocessing detected operating systems: Windows NT
Traceback (most recent call last):
 File "/usr/bin/psteal.py", line 78, in <module>
   if not Main():
 File "/usr/bin/psteal.py", line 63, in Main
   tool.ExtractEventsFromSources()
 File "/usr/lib/python2.7/site-packages/plaso/cli/psteal_tool.py", line 319, in ExtractEventsFromSources
   extraction_engine.knowledge_base)
 File "/usr/lib/python2.7/site-packages/plaso/cli/extraction_tool.py", line 113, in _CreateProcessingConfiguration
   operating_system_version))
 File "/usr/lib/python2.7/site-packages/plaso/parsers/manager.py", line 430, in GetPresetsForOperatingSystem
   return cls._presets.GetPresetsByOperatingSystem(operating_system)
 File "/usr/lib/python2.7/site-packages/plaso/parsers/presets.py", line 173, in GetPresetsByOperatingSystem
   if preset_operating_system.IsEquivalent(operating_system):
 File "/usr/lib/python2.7/site-packages/plaso/containers/artifacts.py", line 208, in IsEquivalent
   other_family, _ = self._FAMILY_AND_VERSION_PER_NAME.get(other.name)
TypeError: 'NoneType' object is not iterable
```

**Comment by joachimmetz** [comment]
Image that surfaced the issue: https://www.binary-zone.com/2015/09/16/digital-forensic-challenge-4/

**Comment by joachimmetz** [comment]
Product string of image is "Windows Server (R) 2008 Standard"

**Comment by joachimmetz** [comment]
Marking as bug for not having a default value for get and as enhancement to add support for "(R)" to the normalization method.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2352

**Comment by woanware** [comment]
I have seen this issue again, if I print "product" in artifacts.py I get the following result: 

[u'Windows', u'Web', u'Server', u'2008', u'R2']

**Comment by woanware** [comment]
My code now looks like so which works for my image:

```
if 'windows' in product_lower_case:
      segment_index = product_lower_case.index('windows') + 1

      if product_lower_case[segment_index] == 'web':
        segment_index += 1
      if product_lower_case[segment_index] == 'server':
        segment_index += 1
```

**Comment by joachimmetz** [comment]
@woanware thx for the report

I'll add 'web' as a word to ignore in the product string

BTW what version of plaso are you using? Since this code has changed a bit https://github.com/log2timeline/plaso/blob/master/plaso/containers/artifacts.py#L158

**Comment by woanware** [comment]
I am using "plaso - psteal version 20190131"

**Comment by joachimmetz** [comment]
> I am using "plaso - psteal version 20190131"

Ack, know that the current release is 20190429

**Comment by woanware** [comment]
Ah ok, was my first time using in years, so installed direct on Ubuntu via PPA

**Comment by joachimmetz** [comment]
Hmm, the GIFT PPA should provide you with the latest version https://launchpad.net/~gift/+archive/ubuntu/stable/+packages?field.name_filter=plaso&field.status_filter=published&field.series_filter=

**Comment by woanware** [comment]
Possible because I am on Ubuntu Disco e.g. 19.04?

**Comment by joachimmetz** [comment]
that could be, the GIFT PPA does not provide plaso for 19.04 so not sure where you got it from then
