### ISSUE TITLE
Firmware file causes utmp extraction warnings

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2381]
Noticed in 'acserver' Greendale image:
```
********************************* Warning: 17 **********************************
           Message : unable to decode hostname string
      Parser chain : utmp
Path specification : type: OS, location: /media/greendale_images/acserver.dd
                   : type: RAW
                   : type: TSK_PARTITION, location: /p1, part index: 2, start
                     offset: 0x00100000
                   : type: TSK, inode: 139450, location:
                     /lib/firmware/matrox/g400_warp.fw
```

g400_warp.fw is not a utmp file, but is being recognized as such.

**Comment by Onager** [comment]
This looks to be due to utmp files not having a good strong signature, so arbitrary binary files can readily pass the verification the utmp parser attempts.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2430

**Comment by joachimmetz** [comment]
Changes pushed, but likely more improvements possible

**Comment by joachimmetz** [comment]
@Onager close this issue? is there more you want to change in the context of this issue?

**Comment by Onager** [comment]
The extra checks have stopped the misleading warnings.
