### ISSUE TITLE
Dynamically adjust the maximum number of containers merged per loop

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2389]
Currently, the storage implementation merges 50 attribute containers, then goes and checks if there are more task stores to merge: https://github.com/log2timeline/plaso/blob/c396373dbb92dd7af60240845746b4d7853b3476/plaso/multi_processing/task_engine.py#L91

When there many large file results to merge, which often happens at the end of merging, this leads to a lot of unnecessary checks for more completed tasks. By increasing the number of containers merged per loop when the main processes isn't seeing more tasks to merge, and then dropping back once more are detected, we should be able to improve performance.

**Comment by joachimmetz** [comment]
Made changes to try to maximize for half a second of a merge.
