### ISSUE TITLE
Add entropy calculation "hasher"

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2390]
While calculating hashes, also calculate the entropy of the file.

**Comment by 82d28a** [comment]
While you are at it can you calculate import hash for PE files?

**Comment by Onager** [comment]
PE import hashing is already done - see
https://github.com/log2timeline/plaso/blob/50d904cc9d4760e54579858073e0396a85581723/plaso/parsers/pe.py#L24

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2430
