### ISSUE TITLE
Request for feature to pause and resume log2timeline.py. 

### ISSUE THREAD

**Issue by 82d28a** [log2timeline/plaso#2391]
**Feature request: I would like to stop and resume log2timeline.py for given job.

**Comment by MariasStory** [comment]
Also, crach recover and continue.

**Comment by joachimmetz** [comment]
>  I would like to stop and resume log2timeline.py for given job.

@82d28a log2timeline.py is not intended as an interactive tool. Could you explain your need for this

> Also, crach recover and continue.

@MariasStory if you want less crashes then reply to input to bug reports instead (such as https://github.com/log2timeline/plaso/issues/2190) so we can fix them

**Comment by 82d28a** [comment]
I agree it doesn't need to be interactive. Things come up during investigations, and priorities shift. I want to be able to pause and run higher priority jobs, without restarting the paused job. In the end some, if not most users of plaso do not have the luxury of having a farm of worker nodes dedicated to plaso processing. Thank you for your consideration.

**Comment by joachimmetz** [comment]
> Things come up during investigations, and priorities shift.

You can tun log2timeline.py incrementally adding relevant artifacts.

If you need to run "kitchen sink" and are maxing out your system resources consider starting with less workers.

Suspend resume functionality will add a lot more complexity to log2timeline.py without much benefit. 
E.g. how can log2timeline.py distinguish between a worker process that ws timed out or was suspended?

**Comment by 82d28a** [comment]
I understand the need to avoid additional complexity and appreciate you looking at it. I agree in the grand scheme of things doing selective artifacts may be better approach. In the spirit of avoiding human error, I tend to do kitchen sink. 
  
This is likely a great over simplification, with regards to time out vs suspended, maybe gracefully finish existing work items and gracefully pause.  Pause doesn't need to be immediate, just faster then waiting for end of job.

**Comment by joachimmetz** [comment]
Depending on the case we would do both:

1. get specific data/artifacts for a quick assessment
2. kitchen sink for a full timeline

We've considered a more distributed worker approach before. Also see https://github.com/log2timeline/plaso/issues/2293

and suspend/resume is something we could take consideration for such a solution.

As I currently see it there are a lot of other bugs/features we want in plaso that provide more benefit IMHO. So this would be something low on the to do list for me.

**Comment by 82d28a** [comment]
Thanks again. I understand priorities.

**Comment by whitneychampion** [comment]
has this been revisited? would greatly benefit from being able to pause/resume and essentially chunk the processing. this would enable splitting a long running task into chunks for use within other platforms.

**Comment by joachimmetz** [comment]
@whitneychampion this is not a priority at this time, but feel free to send a PR
