### ISSUE TITLE
Investigate possible plist parsing issues with whitespace and plistlib

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2401]
Ref: https://medium.com/dfir-dudes/mac-forensics-no-one-said-it-would-be-easy-8bf2f5e4956c

**Comment by joachimmetz** [comment]
biplist was replaced with plistlib https://github.com/log2timeline/plaso/issues/3193

**Comment by joachimmetz** [comment]
plistlib will raise InvalidFileException if the first line of an XML plist file is empty

**Comment by joachimmetz** [comment]
Issue investigated and pending changes to handle XML plist file with leading whitespace
