### ISSUE TITLE
Possible flaky test

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#242]
* [ ] Try to reproduce/Have a look at the code and make changes accordingly

From: https://groups.google.com/forum/#!topic/log2timeline-discuss/TtrBoKfopOA

```
FAIL: testProcess (plaso.parsers.sqlite_plugins.gdrive_test.GoogleDrivePluginTest)
Tests the Process function on a Google Drive database file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./plaso/parsers/sqlite_plugins/gdrive_test.py", line 65, in testProcess
    self.assertEqual(event_object.document_type, u'DOCUMENT')
AssertionError: u'PRESENTATION' != u'DOCUMENT'
- PRESENTATION
+ DOCUMENT
```

**Comment by joachimmetz** [comment]
Also gdrive does not seems to parse the protobuf strings.

**Comment by joachimmetz** [comment]
Does this error imply that the order of event objects on the queue is different across different platforms?

**Comment by joachimmetz** [comment]
Some clean up related to this issue: https://codereview.appspot.com/251800043/

**Comment by kiddinn** [comment]
are these tests still flaky? Have you been able to reproduce these?

**Comment by joachimmetz** [comment]
Not on Travis and AppVeyor, closing issue for now.
