### ISSUE TITLE
Reduce the need to run psort multiple times

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#244]
Presently, if a user wants tags in their plaso report (produced by psort), they need to run psort twice, once to run the analysis (perhaps using the null output plugin), and then again to generate the output.

If a user tries to both steps at once, running an analysis plugin that adds tags while also producing a report, they will get a report without tags.

This is not intuitive. Come up with a better way to do this.

**Comment by joachimmetz** [comment]
Needs psort clean up or rewrite.

**Comment by joachimmetz** [comment]
This was implemented as part of psort clean up needed for the 1.5 release.
