### ISSUE TITLE
psort doesn't work: "Determined data location: /usr/share/plaso"

### ISSUE THREAD

**Issue by kudkud** [log2timeline/plaso#2449]
when I try to run psort.py with the following command:
psort.py -o elastic win-image.plaso --index_name win-image --raw_fields
it aborts with the following information?
2019-04-03 16:05:23,617 [INFO] (MainProcess) PID:2779 <data_location> Determined data location: /usr/share/plaso

Is there any workaround for this?

Plaso version:
plaso - log2timeline version 20190331

Operating system Plaso is running on:
Ubuntu 16.04 

Installation method:
GiFT PPA

**Comment by Onager** [comment]
That's not an error, that's a just a status message - does running with `-d` give any more information?

**Comment by kudkud** [comment]
-d parameter doesn't give more information..

it's not an error, but psort does not start, which is confusing

**Comment by Onager** [comment]
That is strange. Does elastic show up if you run `psort.py -o list`?

**Comment by kudkud** [comment]
elastic output module is enabled

psort.py -o list

******************************** Output Modules ********************************
Name : Description
--------------------------------------------------------------------------------
l2tcsv : CSV format used by legacy log2timeline, with 17 fixed fields.
xlsx : Excel Spreadsheet (XLSX) output
l2ttln : Extended TLN 7 field | delimited output.
elastic : Saves the events into an Elasticsearch database.
4n6time_sqlite : Saves the data in a SQLite database, used by the tool 4n6time.

(...)

**Comment by Onager** [comment]
I can't reproduce this - on a fresh Ubuntu 16.04, install gift packages and run the same command.

Does the psort log say anything interesting? By default it's psort-<timestamp>.log.gz

**Comment by kudkud** [comment]
I tried another file which worked well..
probably the other file was corrupt

**Comment by Onager** [comment]
OK, thanks for the update.
