### ISSUE TITLE
strange linear output

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#245]
When running on a directory intermittent `events extracted: 0 - file:  - running: True <sleeping>` notifications.

```
Worker_04 (PID: 24056) - events extracted: 17099 - file: GZIP:auth/auth.log.4.gz - running: True <running>
Worker_05 (PID: 24058) - events extracted: 0 - file:  - running: True <sleeping>
Worker_06 (PID: 24061) - events extracted: 0 - file:  - running: True <sleeping>
Worker_07 (PID: 24064) - events extracted: 0 - file:  - running: True <sleeping>
Worker_08 (PID: 24065) - events extracted: 0 - file:  - running: True <sleeping>
Worker_09 (PID: 24067) - events extracted: 0 - file:  - running: True <sleeping>
```

Output is because there are more workers that input files. Maybe try to determine this situation?

**Comment by joachimmetz** [comment]
Also gzip support seems to be VERY slow.

**Comment by SleuthKid** [comment]
I can also confirm very slow GZIP processing when working on a bitlocker fuse mount (bdemount). 256GB image is now processing over 14 hours. Two out of four workers are at 100% CPU two are ideling. Very strange behaviour.

**Comment by joachimmetz** [comment]
Leave as-is for now.
