### ISSUE TITLE
Inconsistent NTFS file_reference formatting

### ISSUE THREAD

**Issue by obsidianforensics** [log2timeline/plaso#2453]
**Description of problem:**

Some _file_reference_ fields are displayed in hex and some are converted to MFT#-Sequence# (eg: 1234-2). I think the value should be displayed consistently so users can search for it and find all instances easily. 

**Examples:**

**fs:stat:ntfs** and  **fs:ntfs:usn_change** convert hex to {0:d}-{1:d} for message string in formatter; _file_reference_ is still in hex (this is in plaso/formatters/file_system.py). Same behavior with _parent_file_reference_.

**windows:shell_item:file_entry** converts hex to {0:d}-{1:d} for _file_reference_ field; no hex saved (this is in plaso/parsers/shared/shell_items.py).

For **windows:prefetch:execution** in _mapped_files_, something like "[MFT entry: 41069, sequence: 1]" is appended after the file path for each file (this is in plaso/parsers/winprefetch.py).

**Plaso version:**

20190131

**Fix**

I think the decimal version (1234-2) is more user-friendly and better for searching, but I don't know the ramifications (if any) of eliminating the hex value. Maybe save the hex in a different field? Let me know what you think and I can do a PR.

**Comment by joachimmetz** [comment]
@Onager this is likely something for the event data style guide as well

**Comment by joachimmetz** [comment]
> file_reference is still in hex

do you mean with this that file_reference is a 64-bit integer?

> I think the decimal version (1234-2) is more user-friendly and better for searching

It is also more accurate when the file system is ReFS (which also has file references)

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2487

**Comment by obsidianforensics** [comment]
Yes, sorry - I meant 64-bit int

**Comment by joachimmetz** [comment]
@obsidianforensics thx for confirming, changes merged, closing isssue
