### ISSUE TITLE
Failed to execute script log2timeline - Directory is corrupted and unreadable

### ISSUE THREAD

**Issue by cgisecurity** [log2timeline/plaso#2454]
Running log2timeline against a mounted .Ex01 image. It errors out within a couple of seconds with "dfvfs.lib.errors.BackEndError: Unable to retrieve stat object with error: [Error 1392] The file or directory is corrupted and unreadable: u'H:\\Documents and Settings'. Failed to execute script log2timeline"

This has happened on multiple Windows 10 images lately, where the hidden shortcut for "Documents & Settings" is seen as corrupted. In order to get around this, I have to mount the image as writable and delete the short cut.

log2timeline -z UTC --status_view window [DESTINATION DIR] [Mounted Image Drive letter]

**Plaso version:**
20190331

**Windows Version**
Windows 10 17134.648 (1803)

**Installation method:**

* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] master branch

Debug log files only state "Starting processing". This is the only line on the three debug files I have attempted to create.

**Comment by joachimmetz** [comment]
What mount tool do you use?

**Comment by cgisecurity** [comment]
FTK Imager. I've also tried using Arsenal Image Mounter.

**Comment by joachimmetz** [comment]
So the `dfvfs.lib.errors.BackEndError` comes from the Python os implementation (backend). Anything that indicates that the (I assume) NTFS file system is corrupted? And that mounting in write replays the journal and fixes the issue?

**Comment by cgisecurity** [comment]
Not that I can see. This has happened over several of the systems we've triaged lately, and I tested it on my machine as well.

You asked what I use to mount the image, and that made me think to use something else. So I just used OSFMount, mounted the image as read-only, and then ran the same l2t command as previously and it's working just fine... I guess it very well may be how FTK Imager mounts the drive?

**Comment by joachimmetz** [comment]
> I guess it very well may be how FTK Imager mounts the drive?

Is a possibility, especially seeing that it occurs on multiple machines. Any system log entries that hint to an underlying cause.

**Comment by joachimmetz** [comment]
Maybe relevant: https://stackoverflow.com/questions/33376788/how-to-troubleshoot-windows-device-class-installer-returning-error-1392-the-fi

**Comment by cgisecurity** [comment]
Not that I can find, may need to turn some additional logging on and do some additional testing. I can mark this as closed since it is working now.

**Comment by joachimmetz** [comment]
> I can mark this as closed since it is working now.

Sounds good, reopen if you learn more that might indicate an issue in plaso or dfVFS
