### ISSUE TITLE
Additional broken links in documentation.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2468]
Similar to #2302 the link to the l2t style guide on  https://plaso.readthedocs.io/en/latest/sources/developer/Style-guide.html is broken.

The packaged release link here: https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#installing-the-packaged-release is also broken.

**Comment by joachimmetz** [comment]
information about https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#installing-the-packaged-release is missing.

@Onager what about adding some test to check if the links in the documentation are correct?
