### ISSUE TITLE
Add an option to JSON output module to for a JSON lines support

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#248]
Instead of just having a JSON book support, add an argument to psort that allows the output to be JSON  lines instead of book.

The option could be something like:

```
$ psort.py -o json_line ...
```

That is to create a new output module that spits out JSON structures, one entry per line.

TODO:
- [x] Create JSON line output module,  [WIP](https://codereview.appspot.com/255740043/)
- [ ] Add an argument helper to provide options to split the file into multiple files, or compress the output.

**Comment by rodgermoore** [comment]
This request comes from:

https://groups.google.com/forum/#!topic/log2timeline-discuss/14VPXITT0FY

The json lines format is making life a lot easier if you want to use Logstash with psort output (https://www.elastic.co/products/logstash).

**Comment by kiddinn** [comment]
Added new output module, json_lines in here: http://codereview.appspot.com/255740043

**Comment by rodgermoore** [comment]
First step is promising but json lines output is huge. Run json_lines after processing a 600 Gig E01 image and json_lines file is approx 8 gigs. In Linux I can open it with vi but Windows can't handle this. You want to be able to open the file in some occasions (checking, copying, make a subset, etc). Is it possible to split the json_lines output in multiple files, user definable by size for example?

**Comment by kiddinn** [comment]
Well you can always run it through gzip to compress it. Or pipe it through
split

**Comment by kiddinn** [comment]
But we should be able to add some options, especially if you are on a
system like Windows, which doesn't have built in tools like split at your
disposal.

**Comment by kiddinn** [comment]
I'll add that to the feature request and add that later, will not be part
of the first version.

**Comment by joachimmetz** [comment]
I do not understand this workflow, why would you generate 8G of JSON text files and then manually edit them?

**Comment by rodgermoore** [comment]
This is a "nice to have" option not a "need to have" option. 
*I do not understand this workflow, why would you generate 8G of JSON text files and then manually edit them?*
Its not really editing, mostly for viewing and copying some lines to a test file. If you're writing a config file for Logstash it can come in handy to be able to open the json_lines file to test with a couple of lines first. The 8 gigs file is not really suitable for this and compression is not solving this for this use case. Pipe it through split is an extra effort for the user but for me its fine to do for now, no problem. Tnx

**Comment by joachimmetz** [comment]
So basically if you can limit the number of events in the output that would do the trick as well for you.

**Comment by rodgermoore** [comment]
True

**Comment by kiddinn** [comment]
un-assigning myself from this bug

**Comment by Onager** [comment]
Output module was added, closing issue.
