### ISSUE TITLE
Workers Getting Killed

### ISSUE THREAD

**Issue by utkonos** [log2timeline/plaso#2482]
**Description of problem:**

Over time, the number of workers that are killed grows and grows and the process slows to a crawl.

**Command line and arguments:**

psteal.py --source /path/to/directory -o json -w output.json --workers 3

**Source data:**

Linux web server directory

**Plaso version:**

plaso-20190429

**Operating system Plaso is running on:**

Kubuntu 18.10

**Installation method:**

pip install from requirements.txt

**Comment by joachimmetz** [comment]
Could you provide us with:
* the output of `log2timeline.py --troubles`
* debug logs of a failing worker and foreman (main) process

**Comment by joachimmetz** [comment]
14 days without additional input original reporter.

Issue not actionable without additional input, closing for now. Reopen if more information is provided.
