### ISSUE TITLE
Change pyparsing parsers to return none instead of empty bytes values when no match for token

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2491]
Some pyparsing parsers seem to return empty bytes values when pyparsing has no match for the value. Seen in syslog and syslog cron.

* [x] ~~syslog https://github.com/log2timeline/plaso/pull/2500~~
* [x] ~~single line parsers https://github.com/log2timeline/plaso/pull/2538~~
* [x] ~~mutli line parsers https://github.com/log2timeline/plaso/pull/2542~~

**Comment by joachimmetz** [comment]
For context see: https://travis-ci.org/log2timeline/plaso/jobs/528483547

**Comment by ptmcg** [comment]
Let me know if I can be of any help with this

**Comment by joachimmetz** [comment]
@ptmcg thx what needs to be done is:

* determine which parsers and which fields generate `b''` empty values when there is no value
* changes these parsers to generate `None` instead

**Comment by ptmcg** [comment]
Look over these changes in my forked repo: https://github.com/ptmcg/plaso/commit/0cc9145631fbaccfaf805de4d3e90ede2c635749 If this will work for you I'll work up a PR.

**Comment by joachimmetz** [comment]
@ptmcg thx for the suggestion, we're happy to accept PRs

Though I'm hesitant to use the solution you propose. `PyParseInsertDefaultNone` seems to to involve manipulating Python internal methods. With the plaso codebase we're very cautious about debug-ability and maintainability, and shun for using Python "magic" as much as we can. For context also see: https://github.com/log2timeline/l2tdocs/blob/master/process/Style-guide.md

There seems to be a more straight forward approach e.g. https://github.com/log2timeline/plaso/blob/master/plaso/parsers/syslog.py#L314

`event_data.severity = structure.severity` if we change this into `event_data.severity = structure.get('severity', None)` it appears to have the desired result.

**Comment by joachimmetz** [comment]
Issue seems to be cause by accessing a non-exiting token in a Pyparsing structure when using `structure.name` instead of `structure.get(name, None)`

**Comment by ptmcg** [comment]
That works fine too, if you prefer to go that route. I was just trying to address your request, "change these parsers to generate None instead." For the scope of this issue, it looks like it affects any data field that is parsed using `Optional`. You can use my changeset as a guide for where these have related results names, and then use `.get('name', None)` to get None values if the particular attribute is not present in the parsed data.

But by way of reassurance, if there is any "magic" going on, it is captured in pyparsing's `ParseResults` class, which is what the tokens variable actually is. `ParseResults` support list, dict, and namespace access modes, so treating it like a dict is perfectly valid. But assigning a new value using dict semantics is also a common practice in pyparsing parse actions, and fully supported as part of the pyparsing API.

So of course, the choice is completely up to you, either way is supported. I'm glad to have another strong pyparsing usage example to cite on the wiki.

**Comment by joachimmetz** [comment]
> "change these parsers to generate None instead."

I was referring to the plaso parsers, it seems you might have read this as pyparsing parsers; communication is complex ;)
