### ISSUE TITLE
Create a parser for Windows SetupAPI logs

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2549]
Originally from https://github.com/log2timeline/plaso/issues/518

**Comment by js-forensic** [comment]
@joachimmetz I'll pick this one up.

**Comment by joachimmetz** [comment]
@js-forensic I've added you to plaso-contributors, you should have a github "invite", once you're part of that group I can assign the issue  to you

**Comment by js-forensic** [comment]
@joachimmetz We can probably close this issue now.
May update the parser in the future to include more from the body of each log entry.
