### ISSUE TITLE
Remove Timesketch output module in favor of the generic Elasticsearch output

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#2560]
Placeholder issue for removing the Timesketch output module and use the generic Elasticsearch module instead.

* [x] ~~disable end-to-end tests~~
* [x] update Development-Dependencies.md (remove Timesketch specific instructions) - https://github.com/log2timeline/plaso/pull/3500
* [x] remove Timesketch output module - https://github.com/log2timeline/plaso/pull/3500
* [x] remove end-to-end tests

**Comment by joachimmetz** [comment]
Blocked on having new elastic-ts output module. Once that is working determine deprecation path

**Comment by kiddinn** [comment]
new elastic-ts module is being added in #3470 

After that, a new TS API module should be added, and then we can decide upon the deprecation path for the TS output module
