### ISSUE TITLE
move all documentation to readthedocs and remove the github wiki

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2594]
move all documentation to readthedocs and remove the github wiki

* [x] ~~deprecate documentation on wiki~~
* [x] fix documentation issues
  * https://github.com/log2timeline/plaso/issues/2468

**Comment by Onager** [comment]
We should not disable the github wiki if that's going to make the pages unavailable. We're should link to the new documentation instead.

**Comment by joachimmetz** [comment]
ack I've been doing that, but let's have a target for the wiki turn-down as well

**Comment by Onager** [comment]
I don't see a reason to disable the wiki, so I'll reassign this to you.

All the content has been moved to readthedocs.

**Comment by joachimmetz** [comment]
> I don't see a reason to disable the wiki, so I'll reassign this to you.

to not documentation in 2 places and that in the wiki not updated

**Comment by joachimmetz** [comment]
For now I've removed all the wiki pages except Home.md that references read the docs.
