### ISSUE TITLE
Large .exe files use too much memory; Replacement workers do not appear to pick up tasks quickly

### ISSUE THREAD

**Issue by mboerwinkle** [log2timeline/plaso#2596]
**Description of problem:**

When targeting a directory containing a single large (2x the size of worker memory limit) .exe file using PE parser, worker will use too much memory and be killed.

In addition, all other progress will halt. Abandoned: 0, Merging: 0. After 5 minutes, the job finally completes showing that the one file failed to process. Memory usage for all other processes remains constant. In large jobs, I have had multiple workers being killed by the same .exe file, with jobs taking significantly longer than they should and hundreds of workers killed while the replacements just remain idle for huge amounts of time. (#589 #1534 ?) (--disable_zeromq does not change behavior)

With --single-process, the job will complete just fine, with the process ending with memory usage above the worker limit.

 Is this normal behavior? Is there some way to exclude files over a certain size for particular parsers? Do you know what the workers are doing when they remain idle for 5 minutes?

Let me know if you need any other information. Thanks for your help.

**Command line and arguments:**

```
 sudo docker run -v /home/sansforensics/:/data:ro log2timeline/plaso log2timeline -z US/Central -d --logfile /data/[[[]]]/log2timeline/log2timeline.log --buffer_size 100000000 --queue_size 5000  --profilers memory  --hasher_file_size_limit 10 --profiling_directory /data/[[[]]]/log2timeline/profile /data/[[[]]]/log2timeline/out.db /data/mnt
```

**Source data:**

A large .exe file in a directory.

**Plaso version:**

>20190429

**Operating system Plaso is running on:**

Sift (Ubuntu 64), Docker image.

**Installation method:**

```
Docker pull log2timeline/plaso
```

**Debug output/tracebacks:**
```
Main log shows processes as killed by lead process for using too much memory.
2019-05-31 13:56:20,363 [WARNING] (MainProcess) PID:6 <engine> Process: Worker_01 (PID: 15) killed because it exceeded the memory limit: 2147483648.
2019-05-31 13:56:20,363 [DEBUG] (MainProcess) PID:6 <task_manager> Task 20e93755a470482089eb76ca6457bc19 was queued, now processing.
2019-05-31 13:56:20,871 [ERROR] (MainProcess) PID:6 <engine> Process Worker_01 (PID: 15) is not functioning correctly. Status code: killed.
2019-05-31 13:56:20,871 [WARNING] (MainProcess) PID:6 <engine> Terminating process: (PID: 15).
2019-05-31 13:56:20,871 [DEBUG] (MainProcess) PID:6 <engine> Stopped monitoring process: Worker_01 (PID: 15)
2019-05-31 13:56:20,871 [INFO] (MainProcess) PID:6 <engine> Attempt: 1 to start replacement worker process for Worker_01
2019-05-31 13:56:20,871 [DEBUG] (MainProcess) PID:6 <task_engine> Starting worker process Worker_07
```

Killed worker log shows:
```
[DEBUG] (Worker_01 ) PID:15 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/data/test/xxx.exe with parser: pe
```

**Comment by joachimmetz** [comment]
> When targeting a directory containing a single large (2x the size of worker memory limit) .exe file using PE parser, worker will use too much memory and be killed.

If the worker consumes more memory than allowed it will get killed. Is to prevent misbehaving dependencies grinding the system on which they are running to a halt.

If I understand you correctly this exe file is 4-6 G of size? Is this a ZIP self-extractor or equiv?

> In large jobs, I have had multiple workers being killed by the same .exe file

By default plaso will retry the same tasks multiple times (from memory 3 times if I'm not mistaken).

> with jobs taking significantly longer than they should and hundreds of workers killed while the replacements just remain idle for huge amounts of time.

Could you explain this in more detail what you mean with this. How did you determine the workers remained idle based on the status view or from debug logs?

> Do you know what the workers are doing when they remain idle for 5 minutes?

What do the debug logs indicate?

> Is this normal behavior?

I would need to understand better which behaviour you in particular are referring to.

> Is there some way to exclude files over a certain size for particular parsers? 

There currently is not, but you could easily add this to the parser as a work-around.

**Comment by mboerwinkle** [comment]
Thank you for your quick response.

>If I understand you correctly this exe file is 4-6 G of size? Is this a ZIP self-extractor or equiv?
Yes. I took a look at pe.py, and I think I understand now why this is causing OOM.
>pe_data = file_object.read()
reads in the whole file

>Could you explain this in more detail what you mean with this. How did you determine the workers remained idle based on the status view or from debug logs?
Status view. I looked at the logs, and it actually appears that the foreman waits exactly five minutes before declaring the processing task abandoned (maybe _ZEROMQ_NO_WORKER_REQUEST_TIME_SECONDS) I was mistaken in thinking it was the workers' faults. 

I'm going to try to modify pe.py this weekend to play nicer with large files.

Since the long timeout and the worker reading the entire file are both expected behaviors, I am going to close this ticket. Thanks again for your time.

**Comment by joachimmetz** [comment]
> I'm going to try to modify pe.py this weekend to play nicer with large files.
> Yes. I took a look at pe.py, and I think I understand now why this is causing OOM.
> pe_data = file_object.read()

thx, let us know (I'll reopen this issue, as a reminder to have a look at changing this in the pe parser)

> Since the long timeout and the worker reading the entire file are both expected behaviors, I am going to close this ticket.

It could be related to the load time of the executable
