### ISSUE TITLE
CLI tools add unattended mode

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2617]
To run plaso CLI tools e.g. from turbina, add an unattended mode.

behavior of unattended mode is to fail if input from user is required.

**Comment by taishi8117** [comment]
When `--credential` is used with an incorrect credential, Plaso currently hangs and waits for the correct one from stdin, which makes it hard to integrate with a tool like turbinia.

**Comment by joachimmetz** [comment]
Please read https://en.wikipedia.org/wiki/Hang_(computing) for the meaning of a hang.

**Comment by joachimmetz** [comment]
Related issue: https://github.com/log2timeline/plaso/issues/968
