### ISSUE TITLE
Add xlsx output module

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#263]
* [x] [CL](https://codereview.appspot.com/255980043/) - @dc3-plaso 
  * TODO: update .travis.yml, config/dpkg/control
* [x] Add xlsxwriter to l2tdevtools - @joachimmetz
  * [CL](https://codereview.appspot.com/256870043/)
  * https://xlsxwriter.readthedocs.org/
  * https://pypi.python.org/pypi/XlsxWriter/0.7.3
  * https://github.com/jmcnamara/XlsxWriter
  * LICENSE: https://xlsxwriter.readthedocs.org/license.html
* [x] Package and deploy - @joachimmetz
  * ~~GIFT PPA~~
  * ~~l2tbinaries - Mac OS X, Win32, Win64~~
* [x] Update documentation - @joachimmetz
  * ~~Licenses dependencies~~
  * ~~Dependencies Fedora Core~~
  * ~~Dependencies Mac OS X~~
  * Dependencies Ubuntu
  * ~~Dependencies Windows~~

**Comment by kiddinn** [comment]
is this not all completed?

**Comment by joachimmetz** [comment]
As you can see on top no.
