### ISSUE TITLE
remove regvalue

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2630]
Left over from https://github.com/log2timeline/plaso/issues/2566 for backwards compatibility

* check remaining instances of regvalue
  * plaso/formatters/winreg.py
  * plaso/lib/definitions.py
  * plaso/output/shared_elastic.py
* check remaining instances of source_append
  * plaso/formatters/winreg.py

**Comment by Onager** [comment]
@joachimmetz is this complete?

**Comment by joachimmetz** [comment]
> @joachimmetz is this complete?

Nope, these are left overs for backwards compatibility.

@Onager let's pick a date and time for the removal of this, maybe the December release?

**Comment by joachimmetz** [comment]
I've picked a date it is going to be the June release, also since the serializer will now error if dict event data attribute container is passed.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/3014
