### ISSUE TITLE
Encountering issues with Windows Pyinstaller builds

### ISSUE THREAD

**Issue by johnmccash** [log2timeline/plaso#2679]
I was just updating my log2timeline for the first time since 20180630. It appears that processing of E01 files (I tried both Mac and Win7) has been broken for some time in the various Windows ports. The images I'm testing with are from a couple of SANS classes.

**Back in plaso-20180630-amd64, it mostly worked, though it threw the error:**
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]

**plaso-20180818-py2.7-amd64 throws these errors, then terminates:**
Checking availability and versions of dependencies.
[FAILURE]       elasticsearch version: 5.5.1 is too old, 6.0 or later required.
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.

**plaso-20180930-py2.7-amd64 throws the following, but then seems to start working:**
Checking availability and versions of dependencies.
[OPTIONAL]      elasticsearch version: 5.5.1 is too old, 6.0 or later required.
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.
[OK]

**plaso-20181219-py2.7-amd64 throws the following, then exits immediately:**
F:\l2t>D:\Downloads\plaso-20181219-py2.7-amd64\log2timeline --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01"
2019-06-26 13:39:49,196 [INFO] (MainProcess) PID:11960 <data_location> Determined data location: D:\DOWNLO~1\PLASO-~3.7-A\data
2019-06-26 13:39:49,196 [INFO] (MainProcess) PID:11960 <artifact_definitions> Determined artifact definitions path: D:\DOWNLO~1\PLASO-~3.7-A\artifacts
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.
[OK]

Source path     : E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01
Source type     : storage media image
Processing time : 00:00:00

Processing started.
2019-06-26 13:39:51,746 [WARNING] (MainProcess) PID:11960 <manager> Unable to collect value from artifact definition: MacOSUserPasswordHashesPlistFiles with error: Unable to read plist file: /private/var/db/dslocal/nodes/Default/users/_amavisd.plist with error: no element found: line 1, column 0
2019-06-26 13:39:55,068 [WARNING] (MainProcess) PID:11960 <manager> Unable to find any user accounts on the system.
2019-06-26 13:39:55,078 [INFO] (MainProcess) PID:11960 <engine> Preprocessing detected operating systems: MacOS
2019-06-26 13:39:55,078 [INFO] (MainProcess) PID:11960 <extraction_tool> Parser filter expression changed to: macos
, 20190429, 

**plaso-20190131-py2.7-amd64 throws the following and terminates:**
F:\l2t>D:\Downloads\plaso-20190131-py2.7-amd64\log2timeline --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01"
2019-06-26 13:45:17,444 [INFO] (MainProcess) PID:12828 <data_location> Determined data location: D:\DOWNLO~1\PL7BAA~1.7-A\data
2019-06-26 13:45:17,463 [INFO] (MainProcess) PID:12828 <artifact_definitions> Determined artifact definitions path: D:\DOWNLO~1\PL7BAA~1.7-A\artifacts
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.
[OK]

Source path     : E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01
Source type     : storage media image
Processing time : 00:00:00

Processing started.
2019-06-26 13:45:20,246 [WARNING] (MainProcess) PID:12828 <manager> Unable to collect value from artifact definition: MacOSUserPasswordHashesPlistFiles with error: Unable to read plist file: /private/var/db/dslocal/nodes/Default/users/_amavisd.plist with error: no element found: line 1, column 0
2019-06-26 13:45:23,667 [WARNING] (MainProcess) PID:12828 <manager> Unable to find any user accounts on the system.
2019-06-26 13:45:23,687 [INFO] (MainProcess) PID:12828 <engine> Preprocessing detected operating systems: MacOS
2019-06-26 13:45:23,687 [INFO] (MainProcess) PID:12828 <extraction_tool> Parser filter expression set to: macos
Traceback (most recent call last):
  File "tools\log2timeline.py", line 68, in <module>

**plaso-20190331-py2.7-amd64 goes back to working after throwing these errors. This is the last version that seems to start working (I haven’t tested to see if it completes yet):**
Checking availability and versions of dependencies.
[OPTIONAL]      elasticsearch version: 5.5.1 is too old, 6.0 or later required.
[OPTIONAL]      missing: lz4.
[OPTIONAL]      missing: lzma.
[OK]

**plaso-20190429-py2.7-amd64 throws the following errors, then terminates:**
F:\l2t>D:\Downloads\plaso-20190429-py2.7-amd64\log2timeline --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01"
D:\DOWNLO~1\PLASO-~2.7-A\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
2019-06-26 13:50:51,355 [INFO] (MainProcess) PID:13192 <data_location> Determined data location: D:\DOWNLO~1\PLASO-~2.7-A\data
2019-06-26 13:50:51,375 [INFO] (MainProcess) PID:13192 <artifact_definitions> Determined artifact definitions path: D:\DOWNLO~1\PLASO-~2.7-A\artifacts
Checking availability and versions of dependencies.
[OPTIONAL]      missing: lzma.
[OK]

Source path             : E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01
Source type             : storage media image
Processing time         : 00:00:00

Processing started.
D:\DOWNLO~1\PLASO-~2.7-A\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
D:\DOWNLO~1\PLASO-~2.7-A\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!

**plaso-20190531-py2.7-amd64 throws the following errors, then terminates:**
F:\l2t>D:\Downloads\plaso-20190531-py2.7-amd64\log2timeline --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01"
2019-06-26 13:52:53,973 [INFO] (MainProcess) PID:12468 <data_location> Determined data location: D:\DOWNLO~1\PLASO-~1.7-A\data
2019-06-26 13:52:53,993 [INFO] (MainProcess) PID:12468 <artifact_definitions> Determined artifact definitions path: D:\DOWNLO~1\PLASO-~1.7-A\artifacts
Checking availability and versions of dependencies.
[OK]

Source path             : E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01
Source type             : storage media image
Processing time         : 00:00:00

Processing started.

**I also tried plaso-20190531-py2.7-amd64 on a Win7 E01 image, with the following results, after which it terminates immediately:**
F:\l2t>D:\Downloads\plaso-20190531-py2.7-amd64\log2timeline --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\windows\win7-c-drive\complete-win7-c-drive.E01"
2019-06-26 13:57:05,408 [INFO] (MainProcess) PID:492 <data_location> Determined data location: D:\DOWNLO~1\PLASO-~1.7-A\data
2019-06-26 13:57:05,428 [INFO] (MainProcess) PID:492 <artifact_definitions> Determined artifact definitions path: D:\DOWNLO~1\PLASO-~1.7-A\artifacts
Checking availability and versions of dependencies.
[OK]

The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2012-03-15 23:12:03.5713605
vss2            2012-03-23 04:00:15.6540950
vss3            2012-03-31 04:00:12.2104490
vss4            2012-04-04 20:05:02.5026467

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores
can be defined as: 1,3,5 (a list of comma separated values). Ranges
and lists can also be combined as: 1,3..5. The first store is 1. All
stores can be defined as "all". If no stores are specified none will
be processed. You can abort with Ctrl^C.

VSS identifiers: 1..4

Source path             : E:\DFIRNW-19.2\endpoint\windows\win7-c-drive\complete-win7-c-drive.E01
Source type             : storage media image
Processing time         : 00:00:00

Processing started.

**Comment by joachimmetz** [comment]
The following look like warnings not errors

```
...
[OPTIONAL] missing: lzma.
[OK]
```

**Comment by joachimmetz** [comment]
This is a failure due to a missing dependency
```
Checking availability and versions of dependencies.
[FAILURE] elasticsearch version: 5.5.1 is too old, 6.0 or later required.
[OPTIONAL] missing: lz4.
[OPTIONAL] missing: lzma.
```

**Comment by joachimmetz** [comment]
Information and warning log messages, I see no errors or failures
```
Processing started.
2019-06-26 13:39:51,746 [WARNING] (MainProcess) PID:11960 Unable to collect value from artifact definition: MacOSUserPasswordHashesPlistFiles with error: Unable to read plist file: /private/var/db/dslocal/nodes/Default/users/_amavisd.plist with error: no element found: line 1, column 0
2019-06-26 13:39:55,068 [WARNING] (MainProcess) PID:11960 Unable to find any user accounts on the system.
2019-06-26 13:39:55,078 [INFO] (MainProcess) PID:11960 Preprocessing detected operating systems: MacOS
2019-06-26 13:39:55,078 [INFO] (MainProcess) PID:11960 <extraction_tool> Parser filter expression changed to: macos
, 20190429,
```

**Comment by joachimmetz** [comment]
> then exits immediately:
> after which it terminates immediately

anything in the debug logs why?

1. please use the latest version
2. double check if you have the right VS runtime version installed https://plaso.readthedocs.io/en/latest/sources/user/Windows-Packaged-Release.html
3. please check if you might be running into known issues
4. please file an issue with all the necessary details
5. please provide debug logs https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html

Unfortunately just the console output will not help us trouble shoot what might be going wrong on your installation, or if this is a broader issue

**Comment by joachimmetz** [comment]
> It appears that processing of E01 files (I tried both Mac and Win7) has been broken for some time in the various Windows ports.

It looks to me I should be removing old Windows PyInstaller builds to prevent people from using them

> The images I'm testing with are from a couple of SANS classes.

Can these images be shared?

**Comment by johnmccash** [comment]
Joachim,
	I just included the old version data for completeness. Since I hadn’t updated for some time, I wanted to see how far back the problem went. I was surprised to see that it went back more than one release.

Here’s the output of log2timeline –troubles. Debug logs are also attached. Apologies, I hadn’t seen the new troubleshooting docs, or more properly, I failed to look for them. My bad.

		John

F:\l2t2>D:\Downloads\plaso-20190531-py2.7-amd64\log2timeline --troubles  --workers 32  storage_file "E:\DFIRNW-19.2\endpoint\mac\dademurphy.E01"
2019-06-27 07:21:20,398 [INFO] (MainProcess) PID:11656 <data_location> Determined data location: D:\DOWNLO~1\PLASO-~1.7-A\data
Using Python version 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]

Path: F:\l2t2\log2timeline.py

plaso - log2timeline version 20190531

Checking availability and versions of dependencies.
[OK]            Crypto version: 2.6.1
[OK]            artifacts version: 20190320
[OK]            bencode
[OK]            biplist
[OK]            certifi version: 2019.03.09
[OK]            chardet version: 3.0.4
[OK]            dateutil version: 2.8.0
[OK]            dfdatetime version: 20190517
[OK]            dfvfs version: 20190511
[OK]            dfwinreg version: 20190517
[OK]            dtfabric version: 20190120
[OK]            elasticsearch version: 6.3.1
[OK]            future version: 0.17.1
[OK]            idna
[OK]            lz4
[OPTIONAL]      missing: lzma and backports.lzma.
[OK]            pefile version: 2019.4.18
[OK]            psutil version: 5.6.2
[OK]            pybde version: 20190317
[OK]            pyesedb version: 20181229
[OK]            pyevt version: 20181227
[OK]            pyevtx version: 20181227
[OK]            pyewf version: 20140807
[OK]            pyfsapfs version: 20190510
[OK]            pyfsntfs version: 20190104
[OK]            pyfvde version: 20190104
[OK]            pyfwnt version: 20181227
[OK]            pyfwsi version: 20181227
[OK]            pylnk version: 20181227
[OK]            pymsiecf version: 20181227
[OK]            pyolecf version: 20181231
[OK]            pyparsing version: 2.4.0
[OK]            pyqcow version: 20181227
[OK]            pyregf version: 20190303
[OK]            pyscca version: 20181227
[OK]            pysigscan version: 20190103
[OK]            pysmdev version: 20190315
[OK]            pysmraw version: 20181227
[OK]            pytsk3 version: 20190506
[OK]            pytz
[OK]            pyvhdi version: 20181227
[OK]            pyvmdk version: 20181227
[OK]            pyvshadow version: 20190323
[OK]            pyvslvm version: 20181227
[OK]            requests version: 2.22.0
[OK]            six version: 1.12.0
[OK]            pysqlite2.dbapi2 version: 3.19.2
[OK]            urllib3 version: 1.25.3
[OK]            xlsxwriter version: 1.1.8
[OK]            yaml version: 5.1
[OK]            yara version: 3.10.0
[OK]            zmq version: 18.0.1

Also see: https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html

[log2timeline-20190627T071846.log.gz](https://github.com/log2timeline/plaso/files/3334711/log2timeline-20190627T071846.log.gz)
[Worker_00_log2timeline-20190627T072809.log.gz](https://github.com/log2timeline/plaso/files/3334712/Worker_00_log2timeline-20190627T072809.log.gz)
[log2timeline-20190627T072809.log.gz](https://github.com/log2timeline/plaso/files/3334713/log2timeline-20190627T072809.log.gz)

**Comment by joachimmetz** [comment]
> Since I hadn’t updated for some time, I wanted to see how far back the problem went. I was surprised to see that it went back more than one release.

Based on your output this does not the same thing for the different versions. It does not look like "a single problem" for certain versions at all; though I cannot tell for sure without debug logs of the different version. It is very likely for older versions, that you are running into known issues that have been addressed.

I'll have a look at the debug logs as soon as time permits and see what I can find.

**Comment by joachimmetz** [comment]
`[OK] pyewf version: 20140807`

pyeewf is the right version, so not an issue with the experimental version

**Comment by joachimmetz** [comment]
log2timeline-20190627T071846.log.gz

```
2019-06-27 07:18:48,592 [WARNING] (MainProcess) PID:7172 <manager> Unable to collect value from artifact definition: MacOSUserPasswordHashesPlistFiles with error: Unable to read plist file: /private/var/db/dslocal/nodes/Default/users/_amavisd.plist with error: no element found: line 1, column 0
```
2019-06-27 07:18:56,063 [ERROR] (MainProcess) PID:7172 <task_engine> Unable to monitor replacement worker process: Worker_00 (PID: 12532) with error: Process with PID: 12532 does not exist
2019-06-27 07:18:56,063 [WARNING] (MainProcess) PID:7172 <engine> Terminating process: (PID: 12532).
2019-06-27 07:18:56,063 [ERROR] (MainProcess) PID:7172 <task_engine> Unable to create worker process: 0
```

This looks like an issue in the preprocessor for macOS, nothing related to E01
I'll have a closer look at `/private/var/db/dslocal/nodes/Default/users/_amavisd.plist` in the images to see what the issue here is and if that triggers `Unable to create worker process: 0`. Which hints more at a multi processing issue

**Comment by joachimmetz** [comment]
log2timeline-20190627T072809.log.gz

```
2019-06-27 07:28:14,664 [DEBUG] (MainProcess) PID:12996 <task_engine> Starting worker process Worker_00
2019-06-27 07:28:17,588 [ERROR] (MainProcess) PID:12996 <task_engine> Unable to monitor replacement worker process: Worker_00 (PID: 11888) with error: Process with PID: 11888 does not exist
2019-06-27 07:28:17,588 [WARNING] (MainProcess) PID:12996 <engine> Terminating process: (PID: 11888).
2019-06-27 07:28:17,589 [ERROR] (MainProcess) PID:12996 <task_engine> Unable to create worker process: 0
2019-06-27 07:28:17,589 [DEBUG] (MainProcess) PID:12996 <task_engine> Starting worker process Worker_00
```

This looks more like a multi processing issue

**Comment by joachimmetz** [comment]
Worker_00_log2timeline-20190627T072809.log.gz

```
2019-06-27 07:28:15,632 [DEBUG] (Worker_00 ) PID:11888 <zeromq_queue> Worker_00 task queue connected to tcp://127.0.0.1:51657
2019-06-27 07:28:15,632 [DEBUG] (Worker_00 ) PID:11888 <zeromq_queue> Pop on Worker_00 task queue queue, port 51657
```

**Comment by joachimmetz** [comment]
@johnmccash So it looks like psutil might be unable to monitor the worker process on your configuration.

* Which version of Windows do you run plaso on?
* any system configuration / software that would prevent the main plaso process (foreman) determining the PIDs of the child processes?

**Comment by johnmccash** [comment]
NTAC:3NS-20
Joachim,
This on Win7x64 Ultimate, and it worked fine on the same host, and in this exact config, a few releases ago.
                                John

**Comment by joachimmetz** [comment]
> and it worked fine on the same host, and in this exact config, a few releases ago.

something might have changed in psutil

**Comment by joachimmetz** [comment]
@johnmccash as requested per email, could you indicate what your plan is to migrate off Windows 7. Seeing its end of life and looking closer into this issue might be time consuming.

**Comment by joachimmetz** [comment]
No update from original reporter, closing issue. Reopen if additional information comes available.

**Comment by johnmccash** [comment]
NTAC:3NS-20
Joachim,
                (Sorry, just back from vacation this week) We've budgeted for replacement of the forensic workstation early next year, just before EOL for Win7. Are you certain that this issue doesn't affect Win10?
                                Thanks
John

**Comment by joachimmetz** [comment]
> Are you certain that this issue doesn't affect Win10?

I ran the tests on a latest stable Windows 10 machine, the thing is that Windows 10 is not a single Windows version. Also note that Windows is configuration dependent.

We have CI tests that run/test the PyInstaller build https://ci.appveyor.com/project/log2timeline/l2tbinaries/builds/25963137 on 2008 or 2010.

Passing
* https://ci.appveyor.com/project/log2timeline/l2tbinaries/builds/25963137/job/2ca1wyvy3ev4u2r0
* https://ci.appveyor.com/project/log2timeline/l2tbinaries/builds/25963137/job/7q0nccfx796mvrvn

Failing with a pyzmq DLL related issue (likely pyzmq DLL not properly bundled by PyInstaller, I'll have a look)
* https://ci.appveyor.com/project/log2timeline/l2tbinaries/builds/25963137/job/k3cd2fgbbenqnf4e

Unfortunately these issues are very Windows configuration specific and the PyInstaller builds are tricky and time consuming to troubleshoot. One alternative is to install from l2tbinaries. https://plaso.readthedocs.io/en/latest/sources/developer/Developing-Windows.html

**Comment by johnmccash** [comment]
NTAC:3NS-20
Joachim,
                I just reran the test on my Win10 laptop, using the most recent plaso:

E:\l2t>C:\Users\jm460\Downloads\plaso-20190531-py2.7-amd64\log2timeline --log-file=log2timeline_problem.log.gz --debug --workers 5 storage_file "G:\netwars2017\endpoint\endpoint-windows\win7-32-nromanoff-c-drive\win7-32-nromanoff-c-drive.E01"
2019-07-19 09:45:18,325 [INFO] (MainProcess) PID:26548 <data_location> Determined data location: C:\Users\jm460\DOWNLO~1\PLASO-~1.7-A\data
2019-07-19 09:45:18,348 [INFO] (MainProcess) PID:26548 <artifact_definitions> Determined artifact definitions path: C:\Users\jm460\DOWNLO~1\PLASO-~1.7-A\artifacts
Checking availability and versions of dependencies.
[OK]

The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2012-03-15 23:12:03.5713605
vss2            2012-03-23 04:00:15.6540950
vss3            2012-03-31 04:00:12.2104490
vss4            2012-04-04 20:05:02.5026467

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores
can be defined as: 1,3,5 (a list of comma separated values). Ranges
and lists can also be combined as: 1,3..5. The first store is 1. All
stores can be defined as "all". If no stores are specified none will
be processed. You can abort with Ctrl^C.

VSS identifiers: all

Source path             : G:\netwars2017\endpoint\endpoint-windows\win7-32-nromanoff-c-drive\win7-32-nromanoff-c-drive.E01
Source type             : storage media image
Processing time         : 00:00:00

Processing started.

E:\l2t>
It finishes immediately, and leaves nothing in the current directory but a gzipped log file (attached).

                                John
[log2timeline_problem.log.gz](https://github.com/log2timeline/plaso/files/3412168/log2timeline_problem.log.gz)

**Comment by joachimmetz** [comment]
> It finishes immediately, and leaves nothing in the current directory but a gzipped log file (attached).

this is a different issue than the psutil one, as I indicated I see and issue with the 64-bit 2.7 Pyinstaller build ("Failing with a pyzmq DLL related issue (likely pyzmq DLL not properly bundled by PyInstaller, I'll have a look)") tracking this https://github.com/log2timeline/plaso/issues/2722

though the error you have is different than the missing DLL

can you check your event logs, I suspect pyzmq to be failing

**Comment by joachimmetz** [comment]
BTW latest version is not 20190531 but 20190708
