### ISSUE TITLE
Modify the Parser Manager to allow for "always-on" parsers

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#269]
Add a flag to the Parser Manager for parsers to register themselves as "always-on".

Then have a way to query the parser manager to return back a list of "always-on" parsers and others that do not require always being turned on.

Then change the worker so that it uses these two lists, instead of having the filestat parser explicitly run.

 - [ ] Add a flag to the registration for the parser manager to be "always-on"
 - [ ] Add a function to the parser manager to return a list of both essential and non-essential parsers
 - [ ] Change the filestat parser so that it is registered as an essential/always-on parser
 - [ ] Change the worker to make use of these two lists and remove the explicit mention of the filestat parser

**Comment by Onager** [comment]
Just for my clarity, "always on" means "does not require a particular sigscan match", correct?

**Comment by joachimmetz** [comment]
Yeah, I've commented on better terminology in the corresponding document.

**Comment by joachimmetz** [comment]
Depends on phased processing

**Comment by joachimmetz** [comment]
I forgot why we though these changes were useful. Currently reading this issue I would say https://github.com/log2timeline/plaso/issues/321 is the preferred way forward. Closing this issue.
