### ISSUE TITLE
Support for AD1 encrypted .E01 image?

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#2726]
**Description of problem:**
Hi,

do you consider to be able to do timeline from an encrypted .E01 image.
Basically, I create and image with FTKimager with a password and want to have timeline from that image directly with plaso/log2timeline.
It is possible?

Thank you for the good work ;-)

**Comment by joachimmetz** [comment]
Which type of encryption? If you mean the basic E01 password, it does not encrypt the image. If you mean something else please point us to the technical details of the encryption format.

**Comment by MariasStory** [comment]
Hi @joachimmetz,

Thanks for correcting the title.
It is an AD Image Encryption implemented by AccessData:
https://support.accessdata.com/hc/en-us/article_attachments/201953867/AD1___Image_Encryption_Technical_White_Paper.pdf

Overview
AD Encryption is whole image encryption. Not only the raw data (e.g., sector data) is
encrypted, but also any metadata inside the image. Each segment (file) of the image is
encrypted with a randomly-generated image key using strong encryption (AES-256). The
image key is protected by desired credentials, a password or a cert public key. The encrypted
image key is prepended to the front of the first image segment.

Image Formats
AD Encryption is currently enabled for E01, S01, and raw/dd disk images, and for AD1 images.
More image formats may be supported in the future, as the design is not tied to any specific
format.

Appendix B - ADEncrypt Header File Format
The ADEncrypt header contains the encrypted image key and is prepended to the first image
segment. The ADEncrypt header can be decrypted when the correct credentials are provided.
See table from PDF.
The salt, encrypted key, and HMAC immediately follow the header. Then there is padding
with zeroes up to the next 512-byte boundary.

**Comment by joachimmetz** [comment]
AD1 encryption is an FTK specific proprietary container format and currently not supported by plaso/dfvfs.

**Comment by joachimmetz** [comment]
Question answered, closing issue.
