### ISSUE TITLE
Fedora Core package release hyperlink is dead

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#2731]
**Description of problem:**

The release blog mentions that a build is available for Fedora Core, and points to https://plaso.readthedocs.io/en/latest/sources/user/Fedora-Core-Packaged-Release.html . No build is available here.

**Comment by Onager** [comment]
I fixed the link and updated the latest blog post - the correct link is https://plaso.readthedocs.io/en/latest/sources/user/Fedora-Packaged-Release.html
