### ISSUE TITLE
Volume arguments, like --vss_stores, are not handled correctly

### ISSUE THREAD

**Issue by kinky-it** [log2timeline/plaso#2733]
--vss_stores parameter value format unclear

**Description of problem:**

The `log2timeline.py -h` output specifies that `--vss_stores 1,2` would be the correct parameter value format. This value is not accepted, nor is `--vss_stores 1..2`

**Command line and arguments:**

`--vss_stores "1,2"` results in:
`Volume missing for identifier: ,.`

`--vss_stores "1..2"` results in:
`Volume missing for identifier: ..`

`--vss_stores 1,2` results in:
`Volume missing for identifier: ,.`

`--vss_stores 1..2 results in:`
`Volume missing for identifier: ..`

Note that when the parameter is not used, `log2timeline.py` will list the vss stores, and enabled selection. Input `1..2` as well as `1,2` are accepted here.

**Source data:**

Input E01 file of system image with 13 VSS.

**Plaso version:**

plaso - log2timeline version 20190708

**Operating system Plaso is running on:**

Fedora release 30 (Thirty)

**Installation method:**

RPM plaso-20190708-1.fc30.x86_64 from LiFTeR ( https://forensics.cert.org/ )

**Comment by joachimmetz** [comment]
This is a bug in how the vss_stores argument is handled.
