### ISSUE TITLE
MIME types and permission flags in psort.py output

### ISSUE THREAD

**Issue by tomchop** [log2timeline/plaso#2736]
It would be nice to have MIME types and linux permission flags in psort.py output for `fs:stat` events.

**Comment by joachimmetz** [comment]
* MIME type would need to be determined by an analyzer and would be stored in the event data stream
* POSIX file mode and uid/gid are stored in the file stat and could be extracted depending on the dfVFS file system back-end

**Comment by sydp** [comment]
Might be of interest for MIME type matching: 

https://github.com/trailofbits/polyfile#libmagic-implementation

**Comment by joachimmetz** [comment]
Unfortunately there are multiple conflicting python bindings for libmagic https://github.com/log2timeline/plaso/issues/3114#issuecomment-653794725

**Comment by joachimmetz** [comment]
Seeing that file mode and uid/gid are now formatted (https://github.com/log2timeline/plaso/blob/main/data/formatters/generic.yaml#L294) and there is a separate issue for Mime type. Closing this issue.
