### ISSUE TITLE
Plaso 20190708 - Still issues with hashing big files?

### ISSUE THREAD

**Issue by Joe860** [log2timeline/plaso#2742]
**Description of problem:**

If using any of the hashers, workers still hashes bigfiles (especially hiberfil.sys and pagefile.sys) and that makes no sense. It causes delays.

**Command line and arguments:**

log2timeline.py --parsers=win7_slow --hashers=sha1 workstatation.plaso /image.raw
**Source data:**

**Plaso version:**

For example 20190708

**Operating system Plaso is running on:**

Latest docker build using Ubuntu 18.04 as platform

**Installation method:**

$ git clone https://github.com/log2timeline/plaso
$ cd plaso/config/docker
$ docker build -f Dockerfile .

If multiple methods were used please indicate.

No details.

Is there solution how to fix this?

**Comment by joachimmetz** [comment]
@Joe860 sry for the delay we've been preoccupied. Per `--help` you can set the maximum file size to be hashed  with `--hasher_file_size_limit`. 

@Onager should we reconsider a black listing file for the hashers?

**Comment by joachimmetz** [comment]
No updates, closing issue.
