### ISSUE TITLE
Refactor storage to normalize event sources

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2748]
Placeholder, need to check if this is a duplicate

**Comment by joachimmetz** [comment]
@Onager what do you mean with this? Is this corresponding with some of the ongoing event data stream work?

**Comment by joachimmetz** [comment]
Adding to June milestone as a reminder to either get clarification or just close this issue.

**Comment by Onager** [comment]
This is resolved by the eventdatastream changes.
