### ISSUE TITLE
log2timeling windows_run - Run/RunOnce - not populating Values

### ISSUE THREAD

**Issue by prats84** [log2timeline/plaso#2749]
**Description of problem:**

When running either the win7_slow or the specific windows_run parser, the values for the Run Key values (NTUser.dat) are not populated in the .plaso or the psorted .jsonl output. I have verified that there were two values in the Run key  using registry-dump. One of the Values had a long encoded string. 

**Command line and arguments:**

```
log2timeline.py --workers 50 --worker-memory-limit 0 --hasher_file_size_limit 30000000 --queue_size 400000  --buffer_size 30000 --parsers win7_slow -f /usr/share/plaso/filter_windows.txt --logfile /media/9999/results/tmp/ /media/9999/results/l2t/test.plaso /mnt/9999/drive.dd

```

**Source data:**

n/a

**Plaso version:**

20190429

**Operating system Plaso is running on:**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
**Installation method:**

For example:
From PPA
```
Full Text Search... Done
plaso/xenial,xenial 1.4.0+dfsg-2 all
  super timeline all the things

plaso-data/xenial,xenial,now 20190429-6ppa1~xenial all [installed,automatic]
  Data files for plaso (log2timeline)

plaso-tools/xenial,xenial,now 20190429-6ppa1~xenial all [installed]
  Tools of plaso (log2timeline)

python-plaso/xenial,xenial,now 20190429-1ppa1~xenial all [installed]
  Python 2 module of plaso (log2timeline)

python3-plaso/xenial,xenial,now 20190429-6ppa1~xenial all [installed,automatic]
  Python 3 module of plaso (log2timeline)
```

**Comment by joachimmetz** [comment]
@prats84 I see you are using version 20190429 please use the most recent version and reopen this issue if the problem persist with the most recent version of plaso.

Also the GIFT PPA does not support ubuntu 16.04 anymore (for a while now).
