### ISSUE TITLE
Timestamp convert error? (01.01.1970)

### ISSUE THREAD

**Issue by KarouBlou** [log2timeline/plaso#2751]
recently I researched Log2Timeline and Plaso (version 31.05.2019). I tried to analyse Google Chrome databases with them. Because I got just the databases, I can't tell which version of Google Chrome I got. And during my analysis I discovered that the Unix timestamp (01.01.1970) is displayed repeatedly for the  column date. ​I'm using the command
``` 
psort.py -o ... plasodateifile -w outputfile
```

For the output I used .csv file formats. But when I manual convert the Unix timestamps with an online converter, I get the real timestamps.

Do you have any idea why there are these convert errors? Or what I can do so the timestamps get converted automatically?

Thx  in advance

**Comment by joachimmetz** [comment]
@KarouBlou can you post one of these events from the outputfile? (sanitize if needed) so we can determine which parser this is

**Comment by KarouBlou** [comment]
![cookies_log2timeline](https://user-images.githubusercontent.com/43642677/65371554-f9f60100-dc64-11e9-90f5-d17624811cc2.PNG)
Do you mean that?

**Comment by joachimmetz** [comment]
yes, can you provide this in the dynamic output (instead of l2tcsv) or the raw cookie information. It is likely that one of the Google Analytics Cookie parsers is not handling the format of your cookies properly (since they can vary).

**Comment by KarouBlou** [comment]
I created it new in dynamic format. This time the timestamps were interpreted correctly! 
Thanks for your help 👍

**Comment by joachimmetz** [comment]
Question appears to be answered, closing issue
