### ISSUE TITLE
image_export.py includes duplicates if additional flags are specified

### ISSUE THREAD

**Issue by meeehow** [log2timeline/plaso#2757]
**Description of problem:**

image_export.py includes duplicates if --partitions all --no_vss are specified

**Command line and arguments:**

image_export.py --logfile image_export.log --signatures exe_mz,elf -w ~/export ext4.img 
does not include duplicates

image_export.py --logfile image_export.log --partitions all --no_vss --signatures exe_mz,elf -w ~/export ext4.img
includes duplicates, even though --include_duplicates is not provided
**Source data:**

Any type of evidence.

**Plaso version:**

20190708

**Comment by joachimmetz** [comment]
I've been able to reproduce the issue with `test_data/ext4_with_binaries.dd` will add end to end tests and look at a fix

**Comment by joachimmetz** [comment]
Extended the end-to-end tests to hash the results https://github.com/log2timeline/plaso/pull/3102

**Comment by joachimmetz** [comment]
The behavior is due to https://github.com/log2timeline/plaso/blob/master/plaso/cli/image_export_tool.py#L758

**Comment by joachimmetz** [comment]
Per chat @meeehow his use case would be to deduplicate files on the same volume as well, independent of VSS or not

**Comment by joachimmetz** [comment]
Per conversation @kiddinn no specific need to keep it limited to VSS
