### ISSUE TITLE
improve status view window

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#277]
- [x] ~~Make status-view=window default for non-Windows multi processing (1.4 release)~~
- [x] ~~refactor to stand-alone view~~
- [x] ~~move status updates frontend code (and beyond)~~
  - ~~https://codereview.appspot.com/229410043/~~
  - ~~window mode: less equal than "## (##)" needs additional tab~~
  - ~~single process mode~~
- [x] ~~indicate which file a worker was "killed"~~
- [x] ~~add duration of total process~~
- [x] ~~Improve status-view=window for Windows~~
  - https://github.com/log2timeline/plaso/pull/2375
- [x] ~~track kill ☠ (\U2620) and spawn ♥ (\U2665)count~~
  - somewhat visible in status view
- [x] clean up debug info - ongoing process
  - logging now turned on by default

**Comment by Onager** [comment]
@joachimmetz is this realistic for the 1.4 release, or should we remove it?

**Comment by joachimmetz** [comment]
The improvements for Windows are still pending and the error reporting clutters up the windowed status view, so I opt to move this to a next release.

**Comment by Onager** [comment]
@joachimmetz How about making this default for OSX and Linux for 1.4? Even with the error reporting, I think it's a more useful view than the scrolling list.

**Comment by joachimmetz** [comment]
Yeah I can do that, let's make sure the release notes will describe this behavior.

**Comment by joachimmetz** [comment]
Suggestions to improve windows status view for windows 10

https://stackoverflow.com/questions/36760127/how-to-use-the-new-support-for-ansi-escape-sequences-in-the-windows-10-console

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2375 seems to help a bit, still a bit of flicker
