### ISSUE TITLE
Speeding up log2timeline with PyPy

### ISSUE THREAD

**Issue by korc** [log2timeline/plaso#2777]
_This might be pretty stupid idea, but I believe it still would be good to have at least a record of it._
Unfortunately with couple of years worth of real-life data `log2timeline.py` runs pretty slow even on a high-end machine.
Would it be possible to speed up the analysis process using PyPy, which advertises speed as it's main feature? (cf. https://speed.pypy.org/)
I guess plaso's dependence on C libraries is going to be the toughest problem, but is actually making this avenue completely impossible?

**Comment by Onager** [comment]
Thanks for the suggestion @korc - we're keen to make Plaso faster, but PyPy is not the way we're trying to improve things at present. As you mentioned, Plaso uses a lot of C libraries, and while this doesn't make PyPy impossible, it does make it a lot more work than other options.
