### ISSUE TITLE
pycrypto is outdated

### ISSUE THREAD

**Issue by cugu** [log2timeline/plaso#2779]
**Description of problem:**

`pycrypto`s last update was 2013/2014 and it is not maintained any more (s. https://github.com/dlitz/pycrypto/issues/238). `pip install pycrypto` (contained in `requirements.txt`) results in errors on my system. https://github.com/Legrandin/pycryptodome offers a drop in replacement. 

**Suggestion:**

Replace `pycrypto >= 2.6` with `pycryptodome >= 3.9.4` in the requirements.txt

**Command line and arguments:**

`pip install -r requirements.txt`

**Plaso version:**

master

**Operating system Plaso is running on:**

Windows 10, 1803

**Installation method:**

`git clone ...`

**Comment by joachimmetz** [comment]
Thx for the heads up. Closing this issue in favor of https://github.com/log2timeline/dfvfs/issues/181
