### ISSUE TITLE
Move source types to output modules

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#2785]
Consider moving source types from formatters to output modules

**Comment by joachimmetz** [comment]
Source is used by the following output formats:
* dynamic
* l2t_csv
* tln
* elasticsearch, timesketch

IMHO we can remove source from elasticsearch, timesketch and dynamic but likely need to keep it for backwards compatibility with l2t_csv and tln. A possible solution is to have some configuration (in code or file) that maps event data type to source with a default of LOG.

**Comment by joachimmetz** [comment]
@kiddinn who indicated that source might be use TS analyzers

**Comment by joachimmetz** [comment]
Move sources to a sources field formatter that reads the configuration from file (csv?).
```
data_type,source_long,source_short
```

**Comment by joachimmetz** [comment]
The file stat formatter has a "customized" (long) source formatter https://github.com/log2timeline/plaso/blob/master/plaso/formatters/file_system.py#L98.

@kiddinn what were the design ideas behind this?

**Comment by kiddinn** [comment]
As chatted offline, unsure about the origin of this, safe to remove imho

**Comment by joachimmetz** [comment]
Step 1 to remove customized sources fields https://github.com/log2timeline/plaso/pull/3214

**Comment by joachimmetz** [comment]
Step 2 move source field definitions to configuration file

**Comment by joachimmetz** [comment]
Todo step 3, remove source field definitions from formatters

**Comment by joachimmetz** [comment]
Todo step 4 update documentation

**Comment by joachimmetz** [comment]
Not removing for now but have moved this to an output config file
