### ISSUE TITLE
plaso does not parse some WebCacheV01.dat files

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#2789]
**Description of problem:**

I noticed that plaso does not extract anything from some WebCacheV01.dat files.
Looking at the affected WebCacheV01.dat files,  they do not have a Partitions table but have a PartitionsEx table.
So the required tables for msie_webcache plugin are not present and the plugin is not run.

After commenting out 'Partitions': 'ParsePartitionsTable' from REQUIRED_TABLES in plaso/parsers/esedb_plugins/msie_webcache.py,  I was able to extract some browsing history with plaso

**Plaso version:**

libesedb 20181229 and 20191111
plaso 20190916 and 20191203

**Comment by joachimmetz** [comment]
If you can please provide some test files, that will make adding support easier

**Comment by ant1** [comment]
I have put a sample at https://people.freebsd.org/~antoine/WebCacheV01.dat

SHA256 (WebCacheV01.dat) = 3b2958f0283d20d38de63e110da59e03f58c927f4360e8fe5161fdb1a99c3330

**Comment by joachimmetz** [comment]
thx, I have a look shortly

**Comment by joachimmetz** [comment]
Some format analysis notes.

It looks like in this new format various table names have been renamed ("extended") such as:
```
PartitionsEx
CookieEntryEx_3
DependencyEntryEx_7
HstsEntryEx_8
AppCacheEx_20
AppCacheEntryEx_20
```

Previously Containers would refer to Container_8 but it appears that now Containers also can refer to other tables such as: HstsEntryEx_8

**Comment by joachimmetz** [comment]
Minimal changes to get the new format parsed https://github.com/joachimmetz/plaso/commit/89140120f5e18d1f299b081b32e486fc7dbce24e.

@ant1 do you mind if I add your WebCacheV01.dat file to the plaso tests files?

**Comment by ant1** [comment]
You can add it.

**Comment by joachimmetz** [comment]
excellent thx

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/2794

**Comment by joachimmetz** [comment]
changes merged
