### ISSUE TITLE
Improve support of recent versions of Amcache.hve

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#2790]
**Description of problem:**

According to [ANALYSIS OF THE AMCACHE](https://www.ssi.gouv.fr/uploads/2019/01/anssi-coriin_2019-analysis_amcache.pdf), since Windows 10 version 1807 (Redstone 5) the four keys from the first AmCache.hve, File, Programs, Orphan and Generic have been deleted, marking the end of the transition to their new counterparts: InventoryApplicationFile, InventoryApplication and InventoryDriverBinary.

Plaso parses the File and Programs keys.

**Plaso version:**

20191203

**Comment by joachimmetz** [comment]
If you can please provide some test files, that will make adding support easier

**Comment by ant1** [comment]
I have put a sample at https://people.freebsd.org/~antoine/Amcache.hve

SHA256 (Amcache.hve) = 4e574ac939d423947701302bc35d9a0da0b669a5fb86dbf8157a46c6f38f2c6d

**Comment by joachimmetz** [comment]
thx, I have a look shortly

**Comment by joachimmetz** [comment]
Note to self consider merging https://github.com/log2timeline/plaso/pull/2563 as part of amcache parser revamp

**Comment by joachimmetz** [comment]
Started looking into this, amcache parser can use some clean up as well.

**Comment by joachimmetz** [comment]
moving adding support for new subkeys to next milestone

**Comment by joachimmetz** [comment]
Not making the April release, bumping to next

**Comment by joachimmetz** [comment]
Note to self also have a look at https://github.com/log2timeline/plaso/issues/2059

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/pull/3340 should provide most information in Amcache.hve files. Keeping issue open since there are additional date time values that could be extracted

**Comment by joachimmetz** [comment]
Added support for application LinkDate, InstallDate and InstallDateMsi in https://github.com/log2timeline/plaso/pull/3701

**Comment by joachimmetz** [comment]
Based on value names there are a couple of more date and time values https://github.com/libyal/dtformats/blob/main/documentation/AMCache%20file%20(AMCache.hve)%20format.asciidoc but unclear at this point how useful / frequently these are used.
