### ISSUE TITLE
unable to install plaso-tools on Ubuntu 19.04?

### ISSUE THREAD

**Issue by nocomp** [log2timeline/plaso#2791]
hi,
tryin desesperately to install plaso-tools on unbuntu 19.04 but it seems i have an issue :/

i ve followed these instructions:
sudo add-apt-repository ppa:gift/stable
Update and install plaso:

sudo apt-get update
sudo apt-get install plaso-tools

but the update gives an error due to a 404
Err :7 http://ppa.launchpad.net/gift/stable/ubuntu disco Release      
  404  Not Found [IP : 91.189.95.83 80]

E: Le dépôt http://ppa.launchpad.net/gift/stable/ubuntu disco Release n'a pas de fichier Release.

no release filefor this ppa t says and after another  message sayin it needs to be done securely 

d'apt-secure(8)

any idea what i could do to get it working?
thxx for your time

**Comment by joachimmetz** [comment]
The PPA is only for 18.04

**Comment by nocomp** [comment]
hi,
how can i install it on 19.04 from github ? no other options?

**Comment by joachimmetz** [comment]
You have various options they are all explained here https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#how-to-get-started

**Comment by nocomp** [comment]
thxx a lot
