### ISSUE TITLE
GIFT PPA icat missing EWF support?

### ISSUE THREAD

**Issue by kmbMA** [log2timeline/plaso#281]
I recently built a brand new Ubuntu 14.04 system and went through the instructions found here:

github.com/log2timeline/plaso/wiki/Ubuntu-Packaged-Release

The install seemed to go without any issues however when I went to try to run icat to export the $MFT from the image, the option for EWF format is not available. It only allows RAW. Would it be possible to correct this? I know the EWF option is available but not sure why it's not available.

Thank you

**Comment by joachimmetz** [comment]
That because we don't build Sleuthkit with libewf support. Plaso basically only needs libtsk and adding libewf to libtsk would be unnecessary duplication. In the past this caused problems with controlling memory consumption.

**Comment by joachimmetz** [comment]
No response from OP, closing issue. Reopen if needed.
