### ISSUE TITLE
Unknown parser or plugin names in element(s): "sqlite/chrome_cookies" of parser filter expression

### ISSUE THREAD

**Issue by olivierlab45** [log2timeline/plaso#2832]
Hello, I'm sorry to annoy you but I have a problem with log2timeline.py.
Sorry for the translation, I'm French :)
I have a problem when I start building my bodyfile.
I have the error on a parsers.
I downloaded the latest update, did everything I could, but I don't know.
Error : Unknown parser or plugin names in element(s): "sqlite/chrome_cookies" of parser filter expression
If you could help me, it would be great.
Thank you so much.
Olivier

log2timeline.py /root/Bureau/Pasto/timeline.body ./image.dd

2020-02-22 17:11:47,155 [INFO] (MainProcess) PID:2490 <data_location> Determined data location: /usr/local/lib/python3.7/dist-packages/plaso-20200121-py3.7.egg/share/plaso
2020-02-22 17:11:47,170 [INFO] (MainProcess) PID:2490 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]

The following partitions were found:

Identifier      Offset (in bytes)       Size (in bytes)
p1              1048576 (0x00100000)    100.0MiB / 104.9MB (104857600 B)
p2              105906176 (0x06500000)  465.7GiB / 500.0GB (500000882688 B)

Please specify the identifier of the partition that should be
processed. All partitions can be defined as: "all". Note that you can
abort with Ctrl^C.

Partition identifiers: 2
The following Volume Shadow Snapshots (VSS) were found:

Identifier      Creation Time
vss1            2020-01-19 20:16:08.2979793
vss2            2020-01-23 09:18:04.5665054
vss3            2020-02-03 20:50:50.0895178
vss4            2020-02-12 09:32:27.9491618

Please specify the identifier(s) of the VSS that should be processed:
Note that a range of stores can be defined as: 3..5. Multiple stores
can be defined as: 1,3,5 (a list of comma separated values). Ranges
and lists can also be combined as: 1,3..5. The first store is 1. All
stores can be defined as "all". If no stores are specified none will
be processed. You can abort with Ctrl^C.

VSS identifiers: 4

Source path             : /media/root/HD_SAUVE/DD/image.dd
Source type             : storage media image
Processing time         : 00:00:00

Processing started.
Unknown parser or plugin names in element(s): "sqlite/chrome_cookies" of parser filter expression: amcache,bencode,binary_cookies,chrome_cache,chrome_preferences,custom_destinations,czip/oxml,esedb,esedb/file_history,esedb/msie_webcache,filestat,firefox_cache,gdrive_synclog,java_idx,lnk,mcafee_protection,msiecf,olecf,olecf/olecf_automatic_destinations,opera_global,opera_typed_history,pe,plist/safari_history,prefetch,recycle_bin,sccm,setupapi,skydrive_log,skydrive_log_old,sqlite/chrome_27_history,sqlite/chrome_8_history,sqlite/chrome_autofill,sqlite/chrome_cookies,sqlite/chrome_extension_activity,sqlite/firefox_cookies,sqlite/firefox_downloads,sqlite/firefox_history,sqlite/google_drive,sqlite/skype,symantec_scanlog,usnjrnl,winevtx,winfirewall,winjob,winreg
Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

**Plaso version:**
Log2timeline.py --info
2020-02-22 17:24:00,933 [INFO] (MainProcess) PID:2551 <data_location> Determined data location: /usr/local/lib/python3.7/dist-packages/plaso-20200121-py3.7.egg/share/plaso
======================== log2timeline/plaso information ========================

*********************************** Versions ***********************************
        Name : Description
--------------------------------------------------------------------------------
plaso engine : 20200121
      python : 3.7.6 (default, Jan 19 2020, 22:34:52) 
[GCC 9.2.1 20200117]
--------------------------------------------------------------------------------

**Comment by olivierlab45** [comment]
Log2timeline.py --info
2020-02-22 17:24:00,933 [INFO] (MainProcess) PID:2551 <data_location> Determined data location: /usr/local/lib/python3.7/dist-packages/plaso-20200121-py3.7.egg/share/plaso
======================== log2timeline/plaso information ========================

*********************************** Versions ***********************************
        Name : Description
--------------------------------------------------------------------------------
plaso engine : 20200121
      python : 3.7.6 (default, Jan 19 2020, 22:34:52) 
[GCC 9.2.1 20200117]
--------------------------------------------------------------------------------

**Comment by olivierlab45** [comment]
Hello, thank you very much it works.
Another big thank you to everyone.
Good day and well done for what you are doing.
Olivier

**Comment by joachimmetz** [comment]
Reopening since changes still need to be merged

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/pull/2831
