### ISSUE TITLE
Where are the Windows binaries of the 20200121 release?

### ISSUE THREAD

**Issue by thesilas** [log2timeline/plaso#2845]
**Description of problem:**

Unlike the plaso-20191203 release, the plaso-20200121 does not include a Windows binary.
![image](https://user-images.githubusercontent.com/10263598/75696773-63fee180-5cac-11ea-9709-114e8065a802.png)

How can I use/install the latest plaso-20200121 release on a Windows host.

**Command line and arguments:**
N/A

**Source data:**

N/A

**Plaso version:**

20200121

**Operating system Plaso is running on:**

Windows 10.

**Installation method:**
Download from the GitHub releases page: https://github.com/log2timeline/plaso/releases.

**Debug output/tracebacks:**
N/A

For more information see the [troubleshooting
guide][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html].

**Comment by joachimmetz** [comment]
> Unlike the plaso-20191203 release, the plaso-20200121 does not include a Windows binary.

Correct we are no longer shipping the PyInstaller packaged Windows builds. Also see the 20200121 release notes: http://blog.kiddaland.net/2020/01/plaso-20200121-released.html If you feel like sponsoring PyInstaller go ahead and feel free to use plaso's packaging scripts https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html

> How can I use/install the latest plaso-20200121 release on a Windows host.

We recommend using docker, see: https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#installing-the-packaged-release

If you are more adventurous and well versed with pip you can try pip with virtualenv https://plaso.readthedocs.io/en/latest/sources/developer/Developing-Virtualenv.html

or l2tbinaries, which we use in palso tests https://github.com/log2timeline/l2tdevtools/wiki/Update-script

**Comment by joachimmetz** [comment]
Closing issue assuming the question is answered
