### ISSUE TITLE
parsing userassist from ntuser.dat with the winreg_plugins never processed

### ISSUE THREAD

**Issue by D2R9** [log2timeline/plaso#2848]
**Description of problem:**

Plaso is not parsing userassist from the NTUSER.DAT.

**Command line and arguments:**

$ ls -1 /home/test
NTUSER.DAT

$ docker run -v /home/test/:/data/ log2timeline/plaso log2timeline /data/evidences.plaso /data/

**Plaso version:**

plaso-20200227

**Operating system Plaso is running on:**

In a docker container

**Comment by joachimmetz** [comment]
Since there are multiple variants of user assist (https://github.com/libyal/winreg-kb/blob/master/documentation/User%20Assist%20keys.asciidoc) could you provide more details about the input file. Or share the input file if possible?

**Comment by joachimmetz** [comment]
@D2R9 friendly ping, any addition input you can provide to troubleshoot the issue?

**Comment by joachimmetz** [comment]
No additional input from reporter, closing issue. Reopen when more information comes available.
