### ISSUE TITLE
incorrect calculated year for daemon.log file which spans several years #1114

### ISSUE THREAD

**Issue by speknet** [log2timeline/plaso#2871]
When using plaso to parse a daemon.log file which spans several years, the years are mixed up.
This leads to inconsistent forensic timeline data.
Please see also #1114 which was closed without resolution.

**Comment by joachimmetz** [comment]
@speknet thx for flagging, could you clarify in more detail how the years are mixed up.

Regarding a structural fix. A current idea we are working towards is to store yearless dates during parsing (https://github.com/log2timeline/plaso/issues/910) and see if we can do a more accurate assessment of the year at a later stage (e.g. analysis plugin).

**Comment by speknet** [comment]
@joachimmetz I have attached a sample of the timeline and the daemon.log file.
The last modification date of daemon.log is 2019, Mar 31 (matching last entry).
Please look at the events in the timeline and you will understand what I am talking about.
*I know the daemon.log contains some strange events but this is not the point here*

[timeline.txt](https://github.com/log2timeline/plaso/files/4414511/timeline.txt)
[daemon.log](https://github.com/log2timeline/plaso/files/4414514/daemon.log)

**Comment by joachimmetz** [comment]
note to self, one thing possible with the example log is to detect date with a year in the log rules

**Comment by joachimmetz** [comment]
Should be resolved by https://github.com/log2timeline/plaso/issues/4266
