### ISSUE TITLE
SkyDrive log file new format

### ISSUE THREAD

**Issue by dfirfpi** [log2timeline/plaso#288]
Despite the fact that SkyDrive became OneDrive, with different log file formats, in the meantime the SkyDrive log file changed and now it partially uses the SkyDrive error log file format. The actual two SkyDrive parsers will be melt together to reflect these changes. Old SkyDrive file format will not be supported anymore.

**Comment by joachimmetz** [comment]
> Old SkyDrive file format will not be supported anymore.

I opt to keep support for it in plaso, in case someone runs into the old format.

**Comment by dfirfpi** [comment]
Ok.
