### ISSUE TITLE
Add installation troubleshooting guide

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#291]

**Comment by kiddinn** [comment]
added page: https://github.com/log2timeline/plaso/wiki/Installation-Problems

no content as of now though

**Comment by kiddinn** [comment]
un-assigning myself from this bug

**Comment by joachimmetz** [comment]
Initial version of pages created but not a 1.4 blocker.

**Comment by joachimmetz** [comment]
Closing issue work in progress.
