### ISSUE TITLE
PSORT: Elasticsearch 7.x do not support additional document field "_type" as it is depreciated

### ISSUE THREAD

**Issue by aretenidas** [log2timeline/plaso#2922]
Elasticsearch removed support for multiple document types (_type) and refusing to ingest data from psort: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

Elasticsearch error log /var/log/elasticsearch/clustername.log:

`java.lang.IllegalArgumentException: Rejecting mapping update to [cdqr-cdqr_test_ingest] as the final mapping would have more than 1 type: [_doc, plaso_event]`

Now, PSORT utilizes additional type for_type field, like "plaso_event" or "windows:evtx". Any workaround I can use in plaso to assigne doc type to the generic tag "type" instead of using doctype "_type"?

Code:
`CDQR Version: 20191226
**Plaso Version: 20200227**
Using parser: win
Number of cpu cores to use: 13
Destination Folder: Results
Attempting to extract source file: /home/local-admin/test0.zip
All files extracted to folder: Results/artifacts/test0
Source data: Results/artifacts/test0
Log File: Results/test0.log
Database File: Results/test0.plaso`

Start time was: 2020-05-06 14:50:29.398936
Processing started at: 2020-05-06 14:50:29.399000`

Parsing image
`"log2timeline.py" "--partition" "all" "--vss_stores" "all" "--status_view" "linear" "--parsers" "bash_history,bencode,czip,esedb,filestat,lnk,mcafee_protection,olecf,pe,prefetch,recycle_bin,recycle_bin_info2,sccm,sophos_av,sqlite,symantec_scanlog,winevt,winevtx,webhist,winfirewall,winjob,winreg,zsh_extended_history" "--hashers" "md5" "--workers" "13" "--logfile" "Results/test0_log2timeline.gz" "Results/test0.plaso" "Results/artifacts/test0" "--no_dependencies_check"
Parsing ended at: 2020-05-06 14:54:09.636203
Parsing duration was: 0:03:40.237203`

`Removing uncompressed files in directory: Results/artifacts/ `

`Process to export to ElasticSearch started
Exporting results in Kibana format to the ElasticSearch server
**"psort.py" "-o" "elastic" "--status_view" "none" "--index_name" "case_cdqr-cdqr_test_ingest" "--logfile" "Results/test0_psort.gz" "--server" "127.0.0.1" "--port" "9200" "Results/test0.plaso"** `

**Comment by joachimmetz** [comment]
Elasticsearch 7 support was added in the 20200227 version http://blog.kiddaland.net/2020/02/plaso-20200227.html. Seeing 20191226 predates, I recommend trying the new version first.

**Comment by aretenidas** [comment]
@joachimmetz just tested with 20200227, having same exact issue (updated version above).
I actually went ahead and installed plaso directly to VM.

**Comment by aretenidas** [comment]
``

**Comment by joachimmetz** [comment]
@berggren @kiddinn any insights?

**Comment by joachimmetz** [comment]
Per chat @berggren indicates this should be addressed in the 20200227 release. @aretenidas can you attach the output of `log2timeline.py --troubles`

**Comment by berggren** [comment]
We support both ES6.x and 7.x and handle doc_type based on the version of the ES python client. I wonder if this could be a case of your ES python client being for 6.x, but running against a 7.x server.

@aretenidas What version of elasticsearch client are you running?
`pip3 show elasticsearch`

**Comment by aretenidas** [comment]
Here we go:

`# log2timeline.py --troubles
2020-05-08 11:14:39,397 [INFO] (MainProcess) PID:20396 <data_location> Determined data location: /usr/local/lib/python3.6/dist-packages/plaso-20200227-py3.6.egg/share/plaso
Using Python version 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]

Path: /usr/local/lib/python3.6/dist-packages/plaso-20200227-py3.6.egg/EGG-INFO/scripts/log2timeline.py

plaso - log2timeline version 20200227

Checking availability and versions of dependencies.
[OK]		artifacts version: 20200118
[OK]		bencode
[OK]		biplist
[OK]		certifi version: 2018.01.18
[OK]		cffi version: 1.11.5
[OK]		chardet version: 3.0.4
[OK]		cryptography version: 2.1.4
[OK]		dateutil version: 2.8.1
[OK]		defusedxml version: 0.5.0
[OK]		dfdatetime version: 20200121
[OK]		dfvfs version: 20200211
[OK]		dfwinreg version: 20200121
[OK]		dtfabric version: 20200119
[OK]		elasticsearch version: 6.3.1
[OK]		future version: 0.18.2
[OK]		idna version: 2.6
[OK]		lz4
[OK]		pefile version: 2019.4.18
[OK]		psutil version: 5.7.0
[OK]		pybde version: 20191221
[OK]		pyesedb version: 20191220
[OK]		pyevt version: 20191221
[OK]		pyevtx version: 20191221
[OK]		pyewf version: 20140808
[OK]		pyfsapfs version: 20191221
[OK]		pyfsntfs version: 20200223
[OK]		pyfvde version: 20191221
[OK]		pyfwnt version: 20191222
[OK]		pyfwsi version: 20191221
[OK]		pylnk version: 20191221
[OK]		pyluksde version: 20200205
[OK]		pymsiecf version: 20191221
[OK]		pyolecf version: 20191221
[OK]		pyparsing version: 2.4.6
[OK]		pyqcow version: 20191221
[OK]		pyregf version: 20191221
[OK]		pyscca version: 20191222
[OK]		pysigscan version: 20191221
[OK]		pysmdev version: 20200210
[OK]		pysmraw version: 20191221
[OK]		pytsk3 version: 20200117
[OK]		pytz
[OK]		pyvhdi version: 20191221
[OK]		pyvmdk version: 20191221
[OK]		pyvshadow version: 20191221
[OK]		pyvslvm version: 20200102
[OK]		requests version: 2.18.4
[OK]		six version: 1.11.0
[OK]		urllib3 version: 1.22
[OK]		xlsxwriter version: 1.2.8
[OK]		yaml version: 3.12
[OK]		yara version: 3.8.1
[OK]		zmq version: 18.1.1`

and 
`# pip3 show elasticsearch
Name: elasticsearch
Version: 6.3.1
Summary: Python client for Elasticsearch
Home-page: https://github.com/elastic/elasticsearch-py
Author: Honza Král, Nick Lang
Author-email: honza.kral@gmail.com, nick@nicklang.com
License: Apache License, Version 2.0
Location: /usr/lib/python3/dist-packages
Requires: `

Wow, it seems that my python version is 6.3.1.

**Comment by aretenidas** [comment]
upgraded elasticsearch version by running

pip3 install -v elasticsearch==7.6.0

Trying to ingest package again

**Comment by joachimmetz** [comment]
@aretenidas thx for the updates, let us know if upgrading elasticsearch-py does the trick for you

**Comment by aretenidas** [comment]
Thank you so much for all your help!
It is ingesting without issues.
These are commands that I setup my ELK, CDQR and Plaso setup, that got me to my first post and solution:

Download Source Code from CDQR page => https://github.com/orlikoski/CDQR/releases
Install Plaso => sudo add-apt-repository ppa:gift/stable
                          sudo apt update
                          sudo apt install plaso-tools mock
Install python3

Run CDQR: python3 cdqr.py -y -p win --mft --es_kb INDEXNAME -z zipfile.zip => GET ERROR in ELK (GO to 1st post)

Solution:

pip3 install -v elasticsearch=7.6.0

Thank you all!

**Comment by joachimmetz** [comment]
Thx for confirming, I'll close this out then. @berggren let's discuss separately if we can detect the server side version and compare that against the ES client version?
