### ISSUE TITLE
Excluding Parsers - 20200430

### ISSUE THREAD

**Issue by 13Cubed** [log2timeline/plaso#2929]
**Description of problem:**
I'm trying to exclude a parser. For example, win7,-prefetch, but I receive errors each time saying that "-prefetch" is not a known parser or plugin name. The same is true when attempting to exclude any other parser. I've also tried !, but that won't work on the Linux CLI without being escaped as it would be interpreted as an event.

**Command line and arguments:**
-parser_name_here

**Source data:**
N/A

**Plaso version:**
20200430

**Operating system Plaso is running on:**
Ubuntu 18.04

**Installation method:**
Added repo, installed with apt

**Debug output/tracebacks:**
N/A

**Comment by joachimmetz** [comment]
From: log2timeline.py --help

```
  --parsers PARSER_FILTER_EXPRESSION
                        Define which presets, parsers and/or plugins to use,
                        or show possible values. The expression is a comma
                        separated string where each element is a preset,
                        parser or plugin name. Each element can be prepended
                        with an exclamation mark to exclude the item. Matching
                        is case insensitive. Examples: "linux,!bash_history"
                        enables the linux preset, without the bash_history
                        parser. "sqlite,!sqlite/chrome_history" enables all
                        sqlite plugins except for chrome_history".
                        "win7,syslog" enables the win7 preset, as well as the
                        syslog parser. Use "--parsers list" or "--info" to
                        list available presets, parsers and plugins.
```

Use `!` instead of `-`

**Comment by joachimmetz** [comment]
> but that won't work on the Linux CLI without being escaped as it would be interpreted as an event.

this will depend on your shell use single quotes or escape the `!` with commonly used bash

**Comment by 13Cubed** [comment]
Ahh, I had to escape it. On a Linux box it would be something like:
win7,\!prefetch
The backslash must be present in front of the exclamation mark.

Thanks

**Comment by 13Cubed** [comment]
For reference, do you recall in which Plaso version this change was made (no longer using a -, but instead an !)?

**Comment by joachimmetz** [comment]
> The backslash must be present in front of the exclamation mark.

If you are using bash or similar shell, yes.

> For reference, do you recall in which Plaso version this change was made (no longer using a -, but instead an !)?

`-` is special character for the CLI on many platforms/shell. Very early version have used `-`, but this has been changed since May 2016 (https://github.com/log2timeline/plaso/commit/28ee1825036b7386bb3f2c231261cbed3524716f)

**Comment by 13Cubed** [comment]
Ah ok, thank you!

**Comment by joachimmetz** [comment]
Considering this question answered, closing issue.
