### ISSUE TITLE
Make tagging file tests more data driven

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#2937]
Per: https://github.com/log2timeline/plaso/pull/2933 first iteration of tagging file tests are tedious to use and contain a lot of repetition. Consider a more data driven approach to the tests e.g.:

event_data_class, {attributes_to_test: [values_to_test]}

**Comment by joachimmetz** [comment]
First stab at making this less tedious https://github.com/log2timeline/plaso/pull/2938/files. Next step is to:
* clean up remaining Linux tagging tests
* move check method to test lib
* clean up MacOS and Windows tests

**Comment by pyllyukko** [comment]
Implementing unit test for #2942 was so much more simpler and straightforward :+1:

**Comment by joachimmetz** [comment]
Good to hear, I'll keep this issue open as a reminder to migrate the remaining tests and a reminder to see where additional improvements can be made.

**Comment by joachimmetz** [comment]
Done for now, closing issue.
