### ISSUE TITLE
Add an artifact-driven analysis plugin

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#296]
In reference to #155 

Motivating example here is using the WindowsCommonFilePlacementAttacks artifact to label events from planted DLLs in the timeline.

**Comment by Onager** [comment]
This isn't going to make the 1.4 release, retargeting to 1.5.

**Comment by joachimmetz** [comment]
Blocking on artifacts integration

**Comment by joachimmetz** [comment]
Closing as obsolete
