### ISSUE TITLE
Linter script should prompt user to run git fetch after adding upstream

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#297]

**Comment by joachimmetz** [comment]
Can you describe the issue you ran into?

**Comment by Onager** [comment]
Sure - also, it was the linter script, not review:

1.  Working on branch of my fork, decide to run linter
2.  Run linter, get "missing upstream" message
3.  Run ```git remote add upstream https://github.com/log2timeline/plaso.git```
4.  Run linter, get ```fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.```
5.  Debug for a little, end up running ```git fetch upstream```
6.  Run linter, and it works.

**Comment by Onager** [comment]
We can probably fix this by just changing the message to tell the user to run the fetch.

**Comment by joachimmetz** [comment]
Why not just run `git fetch upstream` automatically?

**Comment by joachimmetz** [comment]
So review script already contains a fetch https://github.com/log2timeline/plaso/blob/master/utils/review.sh#L131

I'll add one to the linter script as well.

**Comment by joachimmetz** [comment]
http://codereview.appspot.com/260490043
