### ISSUE TITLE
Psort.py output to an authenticated elasticsearch can't be run in a non interactive way

### ISSUE THREAD

**Issue by william-billaud** [log2timeline/plaso#2976]
**Description of problem:**

The password for elasticsearch must be provided interactively (the use of getpass prevents the use of common workaround like echo $PASSWORD | psort or something like that)

I understand the security concern behind the use of getpass, but it's really annoying if you start putting some automation around , and it would be helpful if we can provide the password via the cli (unsafe) or via Environment variable.

I Have already worked on a potential pr to fix this issue, but would like to know your point of view on this subject before submitting

**Command line and arguments:**

```
psort.py -o elastic ./source.plaso --elastic_user elastic_username

```

**Source data:**
N/A

**Plaso version:**

20200430

**Operating system Plaso is running on:**

ubuntu 18.04

**Installation method:**

For example:
* installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Comment by joachimmetz** [comment]
> I Have already worked on a potential pr to fix this issue, but would like to know your point of view on this subject before submitting

IMHO we can add an option to pass a password, useful for automated testing as well. However we would need to add a warning to discourage using this on more sensitive set ups. I would be interested in a more secure automated solution with time bound tokens, but this typically makes things more complex quickly.
