### ISSUE TITLE
imphash bytes attribute generated by 20191203 no longer supported by 20200430

### ISSUE THREAD

**Issue by MrNonoss** [log2timeline/plaso#2994]
**Description of problem:**

When I want to output the result of a Plaso storage file to a timesketch format, I almost instantly got the error "imphash of type bytes is not supported"

**Command line and arguments:**

`psort.py -d -o timesketch -z Europe/Paris --status_view window /home/data/file.plaso `

I also tried to output a file with the -w argument, withe the same result.

**Source data:**

I made a plaso storage file from an E01 image of a windows server machine.

**Plaso version:**

20200430

**Operating system Plaso is running on:**

It is the Timesketch docker version running on Tsurugi Linux

**Installation method:**

Installed from Docker

**Debug output/tracebacks:**

```
plaso - psort version 20200430

Storage file		: /home/data/file.plaso
Processing time		: 00:00:03

Events:         Filtered        In time slice   Duplicates      MACB grouped    Total
                0               0               0               131             4765647

Identifier              PID     Status          Memory          Events          Tags            Reports
Main                    106     exporting       547.8 MiB       138 (138)       0 (0)           0 (0)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 518, in _DeserializeAttributeContainer
    attribute_container = self._serializer.ReadSerialized(serialized_string)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 400, in ReadSerialized
    return cls.ReadSerializedDict(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 419, in ReadSerializedDict
    json_object = cls._ConvertDictToObject(json_dict)
  File "/usr/lib/python3/dist-packages/plaso/serializer/json_serializer.py", line 243, in _ConvertDictToObject
    'supported.').format(attribute_name))
ValueError: Event data attribute value: imphash of type bytes is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 95, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 72, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 571, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 1007, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/lib/python3/dist-packages/plaso/multi_processing/psort.py", line 488, in _ExportEvents
    event_data_identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/file_interface.py", line 308, in GetEventDataByIdentifier
    return self._storage_file.GetEventDataByIdentifier(identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 262, in GetEventDataByIdentifier
    self._CONTAINER_TYPE_EVENT_DATA, identifier)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 262, in _GetAttributeContainerByIdentifier
    container_type, identifier.row_identifier - 1)
  File "/usr/lib/python3/dist-packages/plaso/storage/sqlite/sqlite_file.py", line 303, in _GetAttributeContainerByIndex
    container_type, serialized_data)
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 525, in _DeserializeAttributeContainer
    raise IOError('Unable to read serialized data: {0!s}'.format(exception))
OSError: Unable to read serialized data: Event data attribute value: imphash of type bytes is not supported.
```

**Comment by joachimmetz** [comment]
event data attributes should not be byte streams.

* What version of pefile are you using?
* What version of plaso do you use to create file.plaso?

**Comment by joachimmetz** [comment]
Note for troubleshooting issue pefile seems to return a string for `get_imphash()`
```
import pefile
x = pefile.PE('Projects/plaso/test_data/test_pe.exe')
x.get_imphash()
type(x.get_imphash())
```
```
str
```

**Comment by MrNonoss** [comment]
Hi @joachimmetz,

Thanks for the reply.
- I don't know what pefile is. I am going to take a look at that.
- I used Plaso version 20191203 to create file.plaso
- The image was built two days ago based on the latest "[table](https://github.com/google/timesketch/tree/table)" repo version

**Comment by joachimmetz** [comment]
> I don't know what pefile is. I am going to take a look at that.

pefile is another Python module that is used by Plaso 

Have a look at https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html. I recommend using the `--troubles` option to get this informatio.

> I used Plaso version 20191203 to create file.plaso

I recommend using 20200430 or later to generate the file . Plaso has become more strict over time, to ensure features like filtering work correctly. Also note that we are continuously updating format support and addressing bugs.

I think this might be the cause of the issue you are seeing.

**Comment by MrNonoss** [comment]
Thanks for all your inputs.
I will update and try again to generate the plaso file (generation took more than 3 days the first time :/)

I will input the result here.

**Comment by joachimmetz** [comment]
> generation took more than 3 days the first time :/

Note that enabling everything (kitchen sink) is time consuming, and that being selective in what you need can be more time effective (http://blog.kiddaland.net/2013/02/targeted-timelines-part-i.html)

There are many factors that influence the performance of log2timeline.py. Frequently simple tweaks can make a major difference, sometimes this is due to third party code e.g. we recently made a factor 2 performance improvement by using a different NTFS implementation https://osdfir.blogspot.com/2020/05/plaso-20200430-released.html

If you can help us understand how you are running log2timeline on what data that could be beneficial.

* on a VM or native?
* how much memory available to log2timeline.py?
* how many concurrent workers?
* what type of input and output storage e.g. SSD, USB, etc.
* what do you have enabled?
* What is your input data?
* Do you run with all VSS?
* etc,

**Comment by MrNonoss** [comment]
Oh great, thanks for the links

To somehow improve perf, I disabled the hashers.
I let all plugins because I want to have all informations at the same place. I want to be able to filter on specific events, and also specific file creations for exemple. In any case, I will take a close look at the kiddaland link. 

I am running it on a pretty fair bare metal (32gb ram, I7 gen8) tsurugi install, with default options for memory, workers and parsers.
The input is an E01 image disk of a windows server stored on the system ssd nvme. The output is on the same drive as it's the only drive available.

**Comment by joachimmetz** [comment]
Sound like a reasonable set up. Note you can run plaso with multiple profilers to pin point the bottleneck https://plaso.readthedocs.io/en/latest/sources/developer/Profiling.html

**Comment by MrNonoss** [comment]
Re,
Looks like this issue is closed. 
However, I'm not done yet....

I am using the last official log2timeline docker image.
It runs for 1 day now and I have like 284+ workers logs. 
My terminal shows only from worker 37 to 99, they are all "killed".
Taking a look at the endless "log2timeline-20200531T141233.log.gz" whose size is more than 2.8gb, there is a lot of :
`2020-05-31 14:28:01,004 [DEBUG] (MainProcess) PID:6 <task_engine> Source heap is full.`

It is the first time I have issues creating a timeline... So strange...

However, I noticed the "NTFS" implementation is much much much more efficient than the "TSK" thing. A lot faster and less stressing for the computer. ### Congrats

**Comment by joachimmetz** [comment]
> My terminal shows only from worker 37 to 99, they are all "killed".

It would be useful to pinpoint what is causing workers to die.

`2020-05-31 14:28:01,004 [DEBUG] (MainProcess) PID:6 <task_engine> Source heap is full.`

this is a debug logging statement, any indication which paths / file types / parser is causing the workers to die?

**Comment by MrNonoss** [comment]
There are two files that seems to be processed continuously, with errors:
- A "gz" compressed SQL dump: 
`2020-06-02 06:28:10,197 [DEBUG] (MainProcess) PID:6 <task_engine> Scheduled task b990cecf3cd84f1c9fad25707969f490 for path specification type: OS, location: /home/data/evid/ewf1 type: RAW type: TSK_PARTITION, location: /p4, part index: 7, start offset: 0x1ad00000 type: NTFS, location: REDACTED.sql.gz, MFT attribute: 3, MFT entry: 157757 type: GZIP`
- Another one is also a "tar.gz" archive.
`2020-06-02 06:42:22,744 [DEBUG] (MainProcess) PID:6 <task_engine> Scheduled task 5202b1a6e8fc423f9ea96a6271beccf7 for path specification type: OS, location: /home/data/evid/ewf1 type: RAW type: TSK_PARTITION, location: /p4, part index: 7, start offset: 0x1ad00000 type: NTFS, location: REDACTED.tar.gz, MFT attribute: 2, MFT entry: 260294 type: GZIP`

 If I focus on a killed worker, lets take 570 for exemple, here are the messages of the log file.
`2020-06-02 06:39:19,242 [WARNING] (MainProcess) PID:6 <engine> Process: Worker_570 (PID: 2349) killed because it exceeded the memory limit: 2147483648.`
`2020-06-02 06:39:19,776 [ERROR] (MainProcess) PID:6 <engine> Process Worker_570 (PID: 2349) is not functioning correctly. Status code: killed.`
`2020-06-02 06:39:19,776 [DEBUG] (MainProcess) PID:6 <engine> Stopped monitoring process: Worker_570 (PID: 2349)`
`2020-06-02 06:39:19,777 [INFO] (MainProcess) PID:6 <engine> Attempt: 1 to start replacement worker process for Worker_570`

I don't really know how to troubleshoot further :/

**Comment by joachimmetz** [comment]
> I don't really know how to troubleshoot further :/

Noworries, this is already useful

```
2020-06-02 06:39:19,242 [WARNING] (MainProcess) PID:6 <engine> Process: Worker_570 (PID: 2349) killed because it exceeded the memory limit: 2147483648.
```

So this indicates the worker is being killed in a controlled manner. If I'm not mistaken it looks like the gz and tar.gz files that are causing the workers to run out of memory?

Could you indicate the file size of these gz files?

**Comment by MrNonoss** [comment]
> Noworries, this is already useful

Great, thank you ^^

- The tar.gz is an SQL dump. Its size is 1.4Gb and 6.6 uncompressed
- The gz is also an SQL dump. Its size is 398Mb...

There are larger files in the image so this should not be problematic... There are also other SQL dump...

**Comment by joachimmetz** [comment]
Next steps are to see if the memory limit issues can be reproduced with a larger gzip file.

**Comment by MrNonoss** [comment]
How could I do that ?

**Comment by joachimmetz** [comment]
> How could I do that ?

This was a note to self ;)

**Comment by joachimmetz** [comment]
GZIP issue likely related to https://github.com/log2timeline/plaso/issues/2746
