### ISSUE TITLE
Add rsyslog file format support to syslog parser

### ISSUE THREAD

**Issue by cshanahan** [log2timeline/plaso#3002]
**Description of problem:**

On newer Linux distributions, there is an option to enable high-precision timestamps in rsyslog. With that option enabled, on RHEL 7 or 8 or SLES 12 systems for example, the Plaso syslog parser doesn't recognize the pattern and skips the log files.

```
z800:# head -n 5 /var/log/messages
2020-05-31T00:00:45.698463+00:00 localhost rsyslogd:  message repeated 76 times: [-- MARK --]
2020-05-31T00:00:45.698885+00:00 localhost rsyslogd:  [origin software="rsyslogd" swVersion="8.33.1" x-pid="1138" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
2020-05-31T00:00:45.738158+00:00 localhost systemd[1]: Reloaded System Logging Service.
2020-05-31T00:00:46.599903+00:00 localhost systemd[1]: Started Rotate log files.
2020-05-31T00:00:47.044800+00:00 localhost systemd[1]: Started Do daily mandb update.
```

The following excerpt is from rsyslog.conf on a SLES 12.1 server. The last line is commented out, which enables high-precision timestamps.

```
# Use rsyslog native, rfc5424 conform log format as default
# ($ActionFileDefaultTemplate RSYSLOG_FileFormat).
#
# To change a single file to use obsolete BSD syslog format
# (rfc 3164, no high-precision timestamps), set the variable
# bellow or append ";RSYSLOG_FileFormat" to the filename.
# See
#   http://www.rsyslog.com/doc/rsyslog_conf_templates.html
# for more informations.
#
#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
```

**Plaso version:**

20200430

**Operating system Plaso is running on:**

Ubuntu 18.04.4

**Installation method:**

Installed from GiFT PPA stable track [https://launchpad.net/~gift]

**Comment by joachimmetz** [comment]
Per conversation on the slack channel, this looks like variant of syslog the current implementation of the parser does not support.

**Comment by joachimmetz** [comment]
Per https://www.rsyslog.com/doc/v8-stable/configuration/templates.html the rsyslog format (RSYSLOG_FileFormat) consists of:

```
template(name="RSYSLOG_FileFormat" type="list") {
     property(name="timereported" dateFormat="rfc3339")
     constant(value=" ")
     property(name="hostname")
     constant(value=" ")
     property(name="syslogtag")
     property(name="msg" spifno1stsp="on")
     property(name="msg" droplastlf="on")
     constant(value="\n")
}
```

The Plaso syslog parser currently supports the rsyslog traditional file format (RSYSLOG_TraditionalFileFormat)

**Comment by joachimmetz** [comment]
Changes in https://github.com/log2timeline/plaso/pull/3011

**Comment by joachimmetz** [comment]
Changes merged
