### ISSUE TITLE
Where to find the latest Windows build/executable of plaso for usage with Autopsy

### ISSUE THREAD

**Issue by Baricanac** [log2timeline/plaso#3003]
For example as it was written [here ](http://blog.kiddaland.net/2019/07/plaso-20190708-released.html); "Where/how to get Plaso 20190708?
See Plaso's Users' Guide. As usual, builds are available for Docker, MacOS, Ubuntu, Fedora and Windows."

So I'm left wondering where all the builds/executables for Docker, MacOS, Ubuntu, Fedora and primarily in my case Windows have gone?

**Comment by joachimmetz** [comment]
> So I'm left wondering where all the builds/executables for Docker, MacOS, Ubuntu, Fedora and primarily in my case Windows have gone?

How to install Docker, Ubuntu, Fedora are documented here: https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#installing-the-packaged-release

MacOS you'll need to build from source: https://plaso.readthedocs.io/en/latest/sources/user/MacOS-Source-Release.html 

Windows we mentioned in http://blog.kiddaland.net/2020/01/plaso-20200121-released.html we no longer provide PyInstaller packaged builds, due the state of the PyInstaller project. You can build the PyInstaller version yourself if needed.

However if the Autopsy project depends on having an executable I opt that they work out supporting the PyInstaller project.

**Comment by joachimmetz** [comment]
@Baricanac I cannot see who put the thumbs up there but I assume that was you and this question is answered. So I'm closing the issue. Reopen if this is not the case.
