### ISSUE TITLE
Some dependencies not updated on installation (Ubuntu)

### ISSUE THREAD

**Issue by gtback** [log2timeline/plaso#301]
When installing Plaso from the GIFT PPA, I was running into an error due to an outdated version of some EWF-related packages. To reproduce, on a fresh Ubuntu 14.04 VM (prior to adding the GIFT PPA):

```
sudo apt-get install libewf-dev
sudo add-apt-repository ppa:gift/stable
sudo apt-get update
sudo apt-get install python-plaso
```

Then open a Python prompt:

```
>>> import dfvfs.resolver.ewf_resolver_helper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/ewf_resolver_helper.py", line 5, in <module>
    import dfvfs.file_io.ewf_file_io
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/ewf_file_io.py", line 13, in <module>
    dependencies.CheckModuleVersion(u'pyewf')
  File "/usr/lib/python2.7/dist-packages/dfvfs/dependencies.py", line 364, in CheckModuleVersion
    module_name, module_version))
ImportError: Module pyewf is too old, minimum required version 20130416
```

Taking a look at the installed packages verifies the old version:
```
$ dpkg -l | grep ewf
ii  libewf                           20140608-1ppa1~trusty            amd64        Library to access the Expert Witness Compression Format (EWF)
ii  libewf-dev                       20130416-3                       amd64        support for Expert Witness Compression format (development)
ii  libewf-python                    20140608-1ppa1~trusty            amd64        Python bindings for libewf
ii  libewf-tools                     20140608-1ppa1~trusty            amd64        Several tools for reading and writing EWF files
ii  libewf2                          20130416-3                       amd64        library with support for Expert Witness Compression Format
```

This manifests itself in the following way when running log2timeline:

```
$ log2timeline.py output.l2t image.E01 
[INFO] Data files will be loaded from /usr/share/plaso by default.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 676, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 662, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 558, in ProcessSources
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 939, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 559, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 395, in _ScanNode
    source_path_spec = self.ScanForVolumeSystem(scan_node.path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/source_scanner.py", line 672, in ScanForVolumeSystem
    source_path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 349, in GetVolumeSystemTypeIndicators
    resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 185, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 108, in OpenFileObject
    u'{0:s}.').format(path_spec.type_indicator))
KeyError: u'Resolver helper object not set for type indicator: EWF.'
```

The `ImportError` is being masked, such that there is no support for EWF files. 

There may be other packages this holds true for; this is just the one that I ran into.

**Comment by kiddinn** [comment]
It seems as if you've got libewf2 installed, which conflicts with libewf

can you uninstall libewf2?

```
$ sudo apt-get remove libewf2
```

and see if the problem still persists?

you can also do

```
$ ipython
...

In [1]: import pyewf

In [2]: pyewf.get_version()
Out[2]: u'20140608'
```

And to know where that EWF library got loaded from:

```
In [3]: pyewf.__file__
Out[3]: '/usr/lib/python2.7/dist-packages/pyewf.so'
```

which will help you determine from where python is reading that old file from.

**Comment by gtback** [comment]
Before uninstalling libewf2:
```
In [1]: import pyewf

In [2]: pyewf.get_version()
Out[2]: u'20130416'

In [3]: pyewf.__file__
Out[3]: '/usr/lib/python2.7/dist-packages/pyewf.so'
```

After uninstalling:

```
In [1]: import pyewf

In [2]: pyewf.get_version()
Out[2]: u'20140608'

In [3]: pyewf.__file__
Out[3]: '/usr/lib/python2.7/dist-packages/pyewf.so'
```

With it working (libewf2 not installed), I ran:
```
$ dpkg --search /usr/lib/python2.7/dist-packages/pyewf.so
libewf-python: /usr/lib/python2.7/dist-packages/pyewf.so
$ ldd /usr/lib/python2.7/dist-packages/pyewf.so 
	linux-vdso.so.1 =>  (0x00007fffd92ef000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fda46ee5000)
	libewf.so.2 => /usr/lib/libewf.so.2 (0x00007fda46b7f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fda467b8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fda4659a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fda46381000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fda4617c000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fda45f79000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fda45c73000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fda4766b000)
$ dpkg --search /usr/lib/libewf.so.2.0.0
libewf: /usr/lib/libewf.so.2.0.0
```
Once I put libewf2 back, I get:
```
$ ldd /usr/lib/python2.7/dist-packages/pyewf.so 
	linux-vdso.so.1 =>  (0x00007ffff97fe000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f3f3c1df000)
	libewf.so.2 => /usr/lib/libewf.so.2 (0x00007f3f3be79000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3f3bab2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3f3b894000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f3f3b67b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3f3b476000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f3f3b273000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3f3af6d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3f3c965000)
$ dpkg --search /usr/lib/x86_64-linux-gnu/libewf.so.2.0.0
libewf2: /usr/lib/x86_64-linux-gnu/libewf.so.2.0.0
```

It looks like pyewf.so grabs the first libewf.so.2 that it finds. With libewf2 installed, it's in /usr/lib/x86_64-linux-gnu/, but when it's gone, it finds the correct one in /usr/lib/

**Comment by joachimmetz** [comment]
> It looks like pyewf.so grabs the first libewf.so.2 that it finds.

That is how the loader of your operating system works

**Comment by joachimmetz** [comment]
Just install the libewf2 place holder package from GIFT PPA besides libewf to prevent your distribution from installing libewf2 when it thinks it needs it but it could be using the files from the libewf package instead.

**Comment by gtback** [comment]
Thanks, @joachimmetz !

I can explicitly install `libewf2` after or concurrently with `python-plaso` (in fact, I'm already doing this to work around this issue). I brought this up because I wasn't sure if there is a way in the Debian configuration for plaso to indicate that the 20130416-3 version is insufficient, or if there are potentially other packages that could be impacted (The first error message I saw, `Resolver helper object not set for type indicator: EWF.` was not helpful to determining the actual problem).

If the recommended workaround is just to install `libewf2` explicitly, in addition to `python-plaso`, feel free to close this.

**Comment by joachimmetz** [comment]
> The first error message I saw, Resolver helper object not set for type indicator: EWF. was not helpful to determining the actual problem

dfVFS can to run without EWF support, so as far as dfVFS is concerned it is not show stopper and throws an exception that is has no EWF resolver helper.

> If the recommended workaround is just to install libewf2 explicitly, in addition to python-plaso, feel free to close this.

This is a necessary hack due to limitations in the Debian packaging system and distros making it worse by putting the ld library version in the package name, instead of relying on the actual content of a package.

> if there are potentially other packages that could be impacted

Yes but this is not really the concern of GIFT, since its focus is plaso only at the moment. Most of these other packages should have updated by now. My take on it is, you either maintain the packages in your distro or you don't include it. Not something in between causing more issues then its worth having the package there in the first place. Especially with tools used for DFIR purposes.

> I wasn't sure if there is a way in the Debian configuration for plaso to indicate that the 20130416-3 version is insufficient

There is, but its tedious to maintain.
