### ISSUE TITLE
Determine why CL re-generated sphinx docs

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#302]
This CL seems to have re-generated sphinx docs while not needed:
https://github.com/log2timeline/plaso/commit/6f7910f82f6c7b1a8160237fa3596ddc210d864f

Let's investigate if different versions of sphinx generate different docs. We need to prevent the docs from continuous changing when not needed.

**Comment by joachimmetz** [comment]
Looks like the sphinx version
https://github.com/log2timeline/plaso/commit/0e9de1694aba1612c277904ffcd93b9237ba651a (Sphinx v1.1.3)
https://github.com/log2timeline/plaso/commit/4f3a85fbea10637c1cdbf0cde9fc539fdcea9c47

Any means to pull a config regarding templates/extensions ?

**Comment by Onager** [comment]
Maybe we can specify a particular version of sphinx-apidoc to generate these. Probably the same version as on readthedocs.

**Comment by joachimmetz** [comment]
I've added a minimal version check in: https://codereview.appspot.com/269830043/

**Comment by Onager** [comment]
We should fix this before the release, so that the docs are consistent.

**Comment by joachimmetz** [comment]
@Onager IMO this is not a 1.4 blocker.

**Comment by joachimmetz** [comment]
Closing issue, reopen if needed.
