### ISSUE TITLE
IIS Parser fails when log lines don't have date or time column.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#303]
Right now, if the log line in the parser does not have a date or time column, the IIS parser will produce the "Unable to extract timestamp from IIS log line" error at line (203) and will continue to produce this error for every line in the file. 

One solution would be to not have the parser parse the file if the date or time column is missing from the Fields line. This would improve speed, however we can be missing valuable information.

Another solution is to use the date and/or time from the "#Date:" line in the header if one of the respective columns doesn't exist. We then perhaps change the `timestamp_desc` when this situation occurs.

**Comment by dc3-plaso** [comment]
You can assign me this if you if you would like.

**Comment by joachimmetz** [comment]
Thanks, needed to change some github group config to actually assign you ;)
