### ISSUE TITLE
Add MISP (Malware Information Sharing Platform) analysis plugin

### ISSUE THREAD

**Issue by elhoim** [log2timeline/plaso#304]
[MISP](https://github.com/MISP/MISP) is a platform to exchange IOCs.
It would be great to have integration with it, more specifically to lookup hashes (MD5/SHA1/SHA256) in MISP. Or implement it the other way around, download the hashes from MISP, and then compare those to the ones from the image being analyzed.

MISP has a key-authenticated REST API available.

Existing MISP data types that might be of interest to be used inside plaso analysis plugins: yara rules, ip, hostname, url, filename, mutex. [New data types](https://github.com/MISP/MISP/issues/460) to be implemented in the future: URI-regexp, filename-regexp, ssdeep, imphash, pehash, authentihash, pipe, mailslot, mutex, SSL certificates attributes, windows service name.

I can arrange access to a MISP instance hosting IOCs if you need it for testing.

**Comment by joachimmetz** [comment]
Any links to documentation of the API and examples on how to use it?

**Comment by elhoim** [comment]
[This document](https://github.com/MISP/MISP/blob/master/INSTALL/documentation.pdf) under the chapter REST API.
There is a reference python library to access the API: [PyMISP](https://github.com/CIRCL/PyMISP)
It does not use all the REST API features, but most of them.
Feel free to open tickets on PyMISP if you need some specific additions to the library.

**Comment by joachimmetz** [comment]
Cannot use PyMISP until there is more clarity about the license: https://github.com/CIRCL/PyMISP/issues/16

Also see: [Adding a new dependency](https://github.com/log2timeline/plaso/wiki/Adding-a-new-dependency)

**Comment by Rafiot** [comment]
The documentation of the API is not exactly great for now so if you have any question, do not hesitate to ask me.

**Comment by berggren** [comment]
Hi Raphaël,

It would be awesome to add MISP support, we accept contributions ;)

This would probably be super easy to implement without the python library
as it is a simple REST api. Look at the recent viper and virustotal analysis
<https://github.com/log2timeline/plaso/tree/master/plaso/analysis> plugins
for inspiration.

/jbn

**Comment by elhoim** [comment]
BTW, the license issue has been fixed

**Comment by elhoim** [comment]
@joachimmetz & @berggren do you want access to a MISP instance for testing integration?

**Comment by joachimmetz** [comment]
Longer term having a MISP test instance for plaso could be useful, but we lack the time to do anything useful with it short term.

**Comment by Rafiot** [comment]
@joachimmetz we can give you access to our instance, this way you can look at an existing instance, if you want. 

@berggren I'll look at it, but I think using the python API makes sense: the Rest API of MISP evolved quite a lot recently, so using the python module makes the outputs more reliable

**Comment by joachimmetz** [comment]
@berggren @tomchop would it make more sense to do this via Yeti / Timesketch?

**Comment by joachimmetz** [comment]
Adding to milestone as a reminder to get closure on where best to do this.

**Comment by joachimmetz** [comment]
Unfortunately since MISP is licensed under AGPL, hence I cannot set up end-to-end testing for this. Hence this functionality will not make it into plaso. We'll reconsider if there is an alternative for end-to-end testing. Closing issue.

**Comment by joachimmetz** [comment]
Also PyMISP moved to https://github.com/MISP/PyMISP

**Comment by adulau** [comment]
[PyMISP](https://github.com/MISP/PyMISP) is licensed under the 2-clause BSD.

There is no need to comply to the AGPL in such case (section 13) as there is no modification of the core MISP as is.

**Comment by joachimmetz** [comment]
I understand that PyMISP is not AGPL, but I cannot run MISP to test integration.
