### ISSUE TITLE
psort.py 1.3 error on 1.2 storage file

### ISSUE THREAD

**Issue by f-s-p** [log2timeline/plaso#305]
I have a bunch of log2timeline v1.2 output files and tried running psort on them and receive the following exception:

> $ psort.py log2timeline_v1.2.plaso
[INFO] Data files will be loaded from /usr/share/plaso by default.
datetime,timestamp_desc,source,source_long,message,parser,display_name,tag,store_number,store_index
Traceback (most recent call last):
  File "/usr/bin/psort.py", line 646, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 641, in Main
    tool.ProcessStorage()
  File "/usr/bin/psort.py", line 593, in ProcessStorage
    self._ProcessStorage()
  File "/usr/bin/psort.py", line 236, in _ProcessStorage
    time_slice=time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 422, in ProcessStorage
    analysis_queues=event_queue_producers)
  File "/usr/lib/python2.7/dist-packages/plaso/frontend/psort.py", line 467, in ProcessOutput
    event_object = storage_file.GetSortedEntry()
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1081, in GetSortedEntry
    event_object = self.GetEventObject(store_number)
  File "/usr/lib/python2.7/dist-packages/plaso/lib/storage.py", line 1146, in GetEventObject
    event_object.store_number = stream_number
AttributeError: 'dict' object has no attribute 'store_number'

I did not see any mention of this as a breaking change in the blog post announcing v1.3 nor in my quick search of the github repo.  Do you have plans of supporting v1.2 output for those of us without access to the original drive images, or do you have a converter available so we can use the latest psort to still access our data, especially given that v1.2 is no longer in either the sift or gift ppa?

**Comment by joachimmetz** [comment]
> I did not see any mention of this as a breaking change in the blog post announcing v1.3 nor in my quick search of the github repo.

Sorry about that but we've broke backwards compatibility. There are a couple of options here:

* We can look at building a converter.
* An alternative would be to build a virtualenv with version 1.2; it is largely dfvfs and plaso that you need for psort and both of them are available from the git repo.

How many plaso storage files are we talking about?

**Comment by kiddinn** [comment]
What platform are you using? You can always download a Mac or Windows binary for version 1.2 and use psort from there to parse the storage file.

Or if you are using Linux go the virtualenv route as Joachim is suggesting.

And then we can create a converter to make sure things are working. There were few things that changed in how we serialize the extracted events that break the backward compatibility between the versions, but we could create a convertor that converts them.

**Comment by f-s-p** [comment]
Using Linux (Ubuntu), so will try the virtualenv route.  I asked the team of people I support, and they do not have as many v1.2 storage files as I had thought.  The converter would be helpful, but not critical.  Thanks.

**Comment by joachimmetz** [comment]
Closing this issue. Reopen if needed.
