### ISSUE TITLE
Using "psteal" tool as a module

### ISSUE THREAD

**Issue by jleaniz** [log2timeline/plaso#3065]
Question for Joachim.

I am trying to integrate plaso into another application and i would like to use the processing tools  (psteal, for example) as a module, rather than a cli tool. 

I got to a point where everything seems to work, except that then the multiprocessing library throws the following error: AssertionError: daemonic processes are not allowed to have children

This happens after calling the following code:
        tool = psteal_tool.PstealTool(output_writer=writer)
        tool.ExtractEventsFromSources()

What would be the best way or best practice to be able to utilize Plaso's source processing and event extraction from another Python module? I want to try to avoid having to call subprocess() to run log2timeline/plaso/psteal

If there's a better place to have this discussion, happy to move this out of github.

Thanks

**Comment by joachimmetz** [comment]
The short answer is I would **not** encourage an approach that uses Plaso as module at this time.

The longer answer. Plaso was initially written as CLI tools in mind (like the old log2timeline.pl), over time we've pulled out certain elements with a more clearly defined API (such as dfVFS, dfWinreg, dfDateTime), but there is still much to do here.

> What would be the best way or best practice to be able to utilize Plaso's source processing and event extraction from another Python module? 

Depends on your needs, but process isolation is probably a better option. The challenge with the type of processing Plaso does is that your could would need to account for many unexpected behaviors, like a misbehaving parser allocating too much memory.

If you have an Open Source code/project I could look at, I might be able to hint at a possible solution.

**Comment by joachimmetz** [comment]
Per chat on slack channel. It sounds what you're trying to accomplish is similar to what [Turbinia](https://github.com/google/turbinia) does. Having a look at that first.

Alternatively using single process mode for the model you had in mind could work.

Considering this question answered, closing issue.

**Comment by joachimmetz** [comment]
Single processing appears to not be ready for output and analysis
https://github.com/log2timeline/plaso/issues/3066
