### ISSUE TITLE
Log2timeline text prepend option is not reflected in output

### ISSUE THREAD

**Issue by bwpixley** [log2timeline/plaso#310]
When using the -t switch such as "-t C", the C is not being prepended to the path. After running psort to output to l2tcsv, the path only shows TSK: as the path prefix.
Using log2timeline 1.3.0

**Comment by kiddinn** [comment]
The problem here lies in few places:
 + the tool (log2timeline) parses the argument but doesn't pass it up to the front end
 + the parser mediator when compiling the display name ignores the text prepend

Added http://codereview.appspot.com/264900043 to address this

**Comment by joachimmetz** [comment]
The bug here is that text prepend should be removed.

**Comment by kiddinn** [comment]
un-assigning me from this bug

**Comment by joachimmetz** [comment]
Closing issue in favor of tracking enhancements in https://github.com/log2timeline/plaso/issues/101
