### ISSUE TITLE
Exclude filters exclude too much

### ISSUE THREAD

**Issue by william-billaud** [log2timeline/plaso#3123]
**Description of problem:**

When running l2t with some include filters, and after that with the negation of this filter, the sum of the number of event show that some file that should have been analyzed were not.

I have run some test on a test image : 
- running l2t without filter (N°1)
- running l2t with an include filter (N°2)
- running l2t with an exclude filter that is the negation of the include filter (N°3)

When exported in csv the diff [here](https://gist.github.com/william-billaud/49c64087b823011bcb2c901de41dcefe) between the plaso file N°1 and N°3,  we can see that some file like the whole /windows/diagnostic were not present in the N°3.

I have run more test and it's seem like when the pattern \\\\.+\\\\ is absent from the filter file, the sum of the N°2 and N°3 is the N°1 

Is this a misuse of my part or a bug in the filter engine?

Thanks

**Command line and arguments:**

|  command |  filters |  pinfo Number of event sources |  psort.py -o l2tcsv number of line (wc -l) |
|---|---|---|---|
| `log2timeline.py --hashers none --partitions 2 --no-vss --parser filestat -f ./no_registry.yaml exclude.plaso  disk.raw` | description: Windows Registry files.<br>type: exclude<br>path_separator: '\\'<br/>paths:<br>- '\\\\(Users\|Documents And Settings)\\\\.+\\\\NTUSER[.]DAT'<br>- '\\\\Users\\\\.+\\\\AppData\\\\Loca\\l\\Microsoft\\\\Windows\\\\Usrclass[.]dat'<br>- '\\\\Documents And Settings\\\\.+\\\\Local Settings\\\\Application Data\\\\Microsoft\\\\Windows\\\\Usrclass[.]dat'<br>- '%SystemRoot%\\\\System32\\\\config\\\\(SAM\|SOFTWARE\|SECURITY\|SYSTEM)'<br>- '%SystemRoot%\\\\System32\\\\.+\\\\NTUSER[.]DAT'<br>  | 136088 | 334880 | 
| `log2timeline.py --hashers none --partitions 2 --no-vss --parser filestat -f 01_registry.yaml  include.plaso  disk.raw`  |  description: Windows Registry files.<br>type: include<br>path_separator: '\'<br>paths:<br>- '\\\\(Users\|Documents And Settings)\\\\.+\\\\NTUSER[.]DAT'<br>- '\\\\Users\\\\.+\\\\AppData\\\\Local\\\\Microsoft\\\\Windows\\\\Usrclass[.]dat'<br>- '\\\\Documents And Settings\\\\.+\\\\Local Settings\\\\Application Data\\\\Microsoft\\Windows\\\\Usrclass[.]dat'<br>- '%SystemRoot%\\\\System32\\\\config\\\\(SAM\|SOFTWARE\|SECURITY\|SYSTEM)'<br>- '%SystemRoot%\\\\System32\\\\.+\\\\NTUSER[.]DAT'<br> |  7 |  23 | 
|  `log2timeline.py --hashers none --partitions 2 --no-vss --parser filestat  all.plaso  disk.raw` |  None  | 136678  | 336309  | 

**Source data:**

https://www.enisa.europa.eu/ftp/ENISA-LOT3-Evidence.zip
(disk.raw is inside the vmdk)

**Plaso version:**

 20200430 on Ubuntu 18.04

**Installation method:**

* installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Comment by joachimmetz** [comment]
thx for the report I'll have a closer look when time permits.

**Comment by joachimmetz** [comment]
@william-billaud thanks for the detailed comparison and write up. I've been able to reproduce the issue. I confirmed it is a combination of several issues.

I've created https://github.com/log2timeline/dfvfs/pull/457 to address ambiguity in the find specification API. I'll do some more testing and make corresponding changes in Plaso.

**Comment by joachimmetz** [comment]
The pending PRs addresses the issue in my tests.
