### ISSUE TITLE
Running tool in single process with debug does not envoke pdb shell

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#314]
Running the tool (log2timeline) in single process mode with debug turned on does not get the tool to drop into a pdb session anymore.

Instead of the error handler in the extraction frontend handling the exception the worker catches it:
https://github.com/log2timeline/plaso/blob/master/plaso/engine/worker.py#L487

```python
    # All exceptions need to be caught here to prevent the worker
    # form being killed by an uncaught exception.
    except Exception as exception:
      logging.warning(
          u'Unhandled exception while processing path spec: {0:s}.'.format(
              path_spec.comparable))
      logging.exception(exception)
```

This effectively means that the worker has already caught the exception and logged it before it reaches the extraction front-end, thus not evoking the pdb debug shell.

Adding ```raise``` there causes multiprocessing to fail since there isn't a good handler for it. The worker ATM does not know whether or not it is being run as a single process or multi process.

There needs to be some sort of signal to the worker that it should present a debug shell if catching an un-handled exception and that signal should be sent to the worker in the case where the tool is run under single process and with debug turned on.

**Comment by Onager** [comment]
Is this a bug, or an enhancement? @joachimmetz Do you still plan to get this into the December release?

**Comment by joachimmetz** [comment]
The bug is that we broke the old way, the enhancement is that we want this functionality. Planning yes, but I would say this is lower on the prio list than some other issues.
