### ISSUE TITLE
psteal progress / status 

### ISSUE THREAD

**Issue by siftuser** [log2timeline/plaso#3151]
Is there a way to provide "remaining time" to process a volume ? 

**Command line and arguments:**

psteal.py --source /data/image/image.E01 -w /data/plaso/l2t.txt

**Plaso version:**

plaso - version 20200121

**Operating system Plaso is running on:**

ubuntu 18.04

**Installation method:**

`sudo apt-get install python-plaso plaso-tools`

**Comment by joachimmetz** [comment]
> Is there a way to provide "remaining time" to process a volume ?

I don't understand your question. Are you asking this as a feature request or as a question?

**Comment by siftuser** [comment]
Sorry ... as you can see in the following example the app is running for over 9 hours & I do not know, how long it would run. Wondering, is there a switch I could have included to know how long it would take to process/build the timeline ? Thank you for swift response

[
![plaso](https://user-images.githubusercontent.com/8371690/86515716-9f254300-be4d-11ea-9c0c-0d5003275029.png)
](url)

**Comment by joachimmetz** [comment]
Making a good estimate of the remaining time is complex, one VERY rough method is to use the number of sources generated by the main process as 100% and the total number of completed tasks as the current percentage

`( 31464 * 100 ) / 167445 = 18`

so that would put you at 18% 

The long current processing time can have many reasons have a look at https://plaso.readthedocs.io/en/latest/sources/developer/Profiling.html on how to profile and find potential bottlenecks.

My guess this is because you having VSS enabled and are running into the same VSS edge case as https://github.com/log2timeline/plaso/issues/1887

**Comment by siftuser** [comment]
Thank you @joachimmetz ! both links useful. Is there a way to just process `vss` separately. So that, primary volume can be done for triage and process `vss` separately if required

**Comment by joachimmetz** [comment]
> Is there a way to just process vss separately.

Yes from `psteal.py --help`:

```
  --vss_only, --vss-only
                        Do not process the current volume if Volume Shadow Snapshots (VSS) have been selected.
  --vss_stores VSS_STORES, --vss-stores VSS_STORES
                        Define Volume Shadow Snapshots (VSS) (or stores that need to be processed. A range of stores can be defined as: "3..5". Multiple stores can be defined as: "1,3,5" (a list of comma separated values). Ranges and
                        lists can also be combined as: "1,3..5". The first store is 1. All stores can be defined as: "all".
```

**Comment by joachimmetz** [comment]
Also seeing 20200121 you likely want to upgrade Plaso to 20200430 or later, since we've seen some major speed increases by not using TSK for NTFS. Also see: https://osdfir.blogspot.com/2020/05/plaso-20200430-released.html

**Comment by siftuser** [comment]
Yes, I noticed new releases after I started processing current task. I'll update once current task is completed. Thank you again.

**Comment by siftuser** [comment]
Sorry @joachimmetz  ... I tried upgrading to latest version as suggested [here](https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html)

When it completed ... 
`plaso-tools is already the newest version (20200630-1ppa1~bionic).
`
While checking the version, I get this error
```
psteal.py -V
Traceback (most recent call last):
  File "/usr/bin/psteal.py", line 23, in <module>
    from plaso.cli import psteal_tool
  File "/usr/lib/python3/dist-packages/plaso/cli/psteal_tool.py", line 17, in <module>
    from plaso.cli import extraction_tool
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 15, in <module>
    from plaso import parsers  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/plaso/parsers/__init__.py", line 35, in <module>
    from plaso.parsers import ntfs
  File "/usr/lib/python3/dist-packages/plaso/parsers/ntfs.py", line 8, in <module>
    import pyfsntfs  # pylint: disable=wrong-import-order
ImportError: /usr/lib/python3/dist-packages/pyfsntfs.so: undefined symbol: libfsntfs_file_name_attribute_get_name_space
```

**Comment by joachimmetz** [comment]
It looks like you're running an older version of pyfsntfs

**Comment by siftuser** [comment]
> It looks like you're running an older version of libfsntfs in combination with a newer pyfsntfs ? Do you have multiple versions installed on your system?

fsntfsinfo -V
`fsntfsinfo 20200223`

searching for `pyfsntfs`, shows
```
/usr/lib/python2.7/dist-packages/pyfsntfs.so
/usr/lib/python3/dist-packages/pyfsntfs.so
```

> Try invoking python3 directly instead

Sorry this is bit unclear

**Comment by joachimmetz** [comment]
> Sorry this is bit unclear

Instead of typing `python` <ENTER> type `python3` <ENTER>

> searching for pyfsntfs, shows

Please run: `find /lib* /usr/ -name \*fsntfs\*so\* 2> /dev/null`

**Comment by siftuser** [comment]
```
python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyewf
>>> pyewf.get_version()
'20140808'
>>> pyewf.__file__
'/usr/lib/python3/dist-packages/pyewf.so'
>>>
```


```
$ find /lib* /usr/ -name \*fsntfs\*so\* 2> /dev/null
/usr/local/lib/libfsntfs.so.1.0.0
/usr/local/lib/libfsntfs.so.1
/usr/local/lib/libfsntfs.so
/usr/lib/libfsntfs.so.1.0.0
/usr/lib/python3/dist-packages/pyfsntfs.so
/usr/lib/python2.7/dist-packages/pyfsntfs.so
/usr/lib/libfsntfs.so.1
/usr/lib/libfsntfs.so
/usr/lib/x86_64-linux-gnu/libfsntfs.so.1.0.0
/usr/lib/x86_64-linux-gnu/libfsntfs.so.1
```

**Comment by joachimmetz** [comment]
so you have a 2x installations of libfsntfs one in `/usr/local/lib/` and one in `/usr/lib/`

properly uninstall the one in `/usr/local/lib/`

and make sure the one in `/usr/lib` was installed via `apt-get` (or equiv)

if you want the fsntfstools, just install the libfsntfs-tools package; `apt-get install libfsntfs-tools`

**Comment by siftuser** [comment]
Thank you ... I followed installation document 

```
wget https://github.com/libyal/libfsntfs/releases/download/20200627/libfsntfs-experimental-20200627.tar.gz
tar xfv libfsntfs-experimental-20200627.tar.gz
cd libfsntfs-20200627/
./configure --enable-verbose-output --enable-debug-output --prefix=/usr --enable-static-executables=yes --enable-python
make
sudo make install
sudo ldconfig
```

For uninstall I ran `sudo make uninstall`, but I get bunch of `Nothing to be done for 'uninstall'.`

When I run `find /lib* /usr/ -name \*fsntfs\*so\* 2> /dev/null` command, there is no change ... any clue to uninstall ?

**Comment by joachimmetz** [comment]
So your installation does not match the configuration. `--prefix=/usr` would install it in `/usr/lib` not in `/usr/local/lib`

2 options here

* first one, re-run `./configure` to match your original configuration `./configure --prefix=/usr/local` 
* second one, manually remove the version installed in `/usr/local`

**Comment by joachimmetz** [comment]
* Or a third one, remove both and install it from the GIFT PPA instead

**Comment by siftuser** [comment]
Thank you ... sorry, how do I clean remove both ?

**Comment by joachimmetz** [comment]
How did you install them?

**Comment by siftuser** [comment]
```
wget https://github.com/libyal/libfsntfs/releases/download/20200627/libfsntfs-experimental-20200627.tar.gz
tar xfv libfsntfs-experimental-20200627.tar.gz
cd libfsntfs-20200627/
./configure --enable-verbose-output --enable-debug-output --prefix=/usr --enable-static-executables=yes --enable-python
make
sudo make install
sudo ldconfig
```

**Comment by joachimmetz** [comment]
As I said that does not matches your configuration based on the installation in /usr/local. I'm assuming you forgot to add `--prefix=/usr` add some point.

Try the following:

```
cd libfsntfs-20200627/
./configure --enable-python
sudo make uninstall
./configure --prefix=/usr --enable-python
sudo make uninstall
```

If that does not remove the installation in /usr/local try

```
sudo rm -rf /usr/local/lib/libfsntfs* /usr/local/bin/fsntfs* /usr/local/share/libfsntfs
```

Then resinstall from the GIFT PPA, assuming that is correctly configured on your system

```
sudo apt-get install --reinstall libfsntfs-python3
```

**Comment by siftuser** [comment]
Thanks ton @joachimmetz
