### ISSUE TITLE
Inquiry: Is it possible to run plaso on a redline ".mans" file? 

### ISSUE THREAD

**Issue by TonyCrespoMe** [log2timeline/plaso#3152]
**Description of problem:**

I would like to run plaso on ".mans" acquisition file.

**Comment by joachimmetz** [comment]
> I would like to run plaso on ".mans" acquisition file.

You'll have to do this yourself. We cannot "run" it for you ;)

> Is it possible to run plaso on a redline ".mans" file?

Yes. Just "run" it.

If you meant to ask if this format is supported than the answer, is no. For the formats supported by Plaso see https://plaso.readthedocs.io/en/latest/sources/user/Overview.html

Question seems answered.

**Comment by TonyCrespoMe** [comment]
> > I would like to run plaso on ".mans" acquisition file.
> 
> You'll have to do this yourself. We cannot "run" it for you ;)
> 
> > Is it possible to run plaso on a redline ".mans" file?
> 
> Yes. Just "run" it.
> 
> If you meant to ask if this format is supported than the answer, is no. For the formats supported by Plaso see https://plaso.readthedocs.io/en/latest/sources/user/Overview.html
> 
> Question seems answered, closing issue

Great stuff. 

Thanks for the info.

**Comment by joachimmetz** [comment]
If you want support for it what can help is:

* publicly shareable test files
* a data format specification
* a Python module that can read the format and is compatible with Apache 2 license

**Comment by TonyCrespoMe** [comment]
> If you want support for this data format, what can help is:
> 
> * publicly shareable test files
> * a data format specification
> * a Python module that can read the format and is compatible with Apache 2 license

Once again, thank you for the info. 

I currently have a working python script that parses the mans file contents (file records collection in xml format) for the purpose of feeding it to splunk, however, i am looking to be able to use windows artifact parsers from plaso to have a cleaner output. 

Will try to get test data.
