### ISSUE TITLE
pinfo running working in Docker is passed unsupported unattended option

### ISSUE THREAD

**Issue by b4stet** [log2timeline/plaso#3166]
Hi,

When using the docker image, pinfo returns an error:
"pinfo.py: error: unrecognized arguments: --unattended"

command:
$ docker run log2timeline/plaso pinfo

In fact, when running pinfo.py in the container, it works well:
$ docker run -it -v /my/folder:/data_dest --entrypoint /bin/bash log2timeline/plaso
then:
pinfo.py /data_dest/disk.plaso

Looking at /usr/local/bin/plaso-switch.sh, it seems there is a typo in pinfo switch case, and the command does not support the option '--unattended'.

Best Regards

**Comment by joachimmetz** [comment]
Thx for flagging this is bug in the script. It makes no sense to run pinfo in unattended mode, hence it does not have one.
