### ISSUE TITLE
Consider removing dynamic output module --additional_fields option

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3174]
For some reason the dynamic output module helper defines the options `--fields` and `--additional_fields`. It is unclear what the intent of `--additional_fields` was.

https://github.com/log2timeline/plaso/blob/master/plaso/cli/helpers/dynamic_output.py#L40

@kiddinn do you recall what `--additional_fields` was intended for? Was it intended as a shorthand for `--fields=DEFAULT_FIELDS,...` ?

**Comment by kiddinn** [comment]
```
            'Defines extra fields to be included in the output, in addition to'
            ' the default fields, which are {0:s}.'.format(default_fields)))
```

IIRC `--fields` overwrote the default fields and defined exactly what fields were to be included, whereas `--additional_fields` included the default fields but just added new ones.

**Comment by joachimmetz** [comment]
thx, let's keep it as-is for now

**Comment by joachimmetz** [comment]
Closing issue, option still serves a purpose
