### ISSUE TITLE
psort filter date error

### ISSUE THREAD

**Issue by siftuser** [log2timeline/plaso#3187]
Running `psort version 20200717` on ubuntu 18.04

`psort.py --output-time-zone UTC /image.plaso -o l2tcsv -w /plaso.csv "date < '2020-01-01' and date > '2020-08-01'"`

throws error `psort.py: error: unrecognized arguments: date < '2020-01-01' and date > '2020-08-01'`

**Comment by joachimmetz** [comment]
Per: https://github.com/google/timesketch/issues/1319

the answer is the order of arguments is the issue, try

```
psort.py --output-time-zone UTC -o l2tcsv -w /plaso.csv /image.plaso "date < '2020-01-01' and date > '2020-08-01'"
```

**Comment by siftuser** [comment]
Thank you @joachimmetz
