### ISSUE TITLE
Mac OS installation guide references requirements.txt but not seeing file in download

### ISSUE THREAD

**Issue by jeffg2k** [log2timeline/plaso#3197]
[MacOS install](https://plaso.readthedocs.io/en/latest/sources/user/MacOS-Source-Release.html) says this:
```
Install the Plaso dependencies:

cd /tmp/plaso-20200430/
pip install -r requirements.txt
```

But there is no requirements.txt, just a dependencies.ini, which I have no idea how to reference with pip.

**Comment by joachimmetz** [comment]
You likely downloaded the wrong file:
```
Under the latest release you should see four links to different packages, you will need to download the “Source code (tar.gz)” package file
```

Please don't use pip if you're not familiar with it. It can be easy to mess up your installation with.

**Comment by jeffg2k** [comment]
Thanks, I did download the wrong package.  The documentation could still be updated.  While it says to download the source code, the instructions reference the other package, so it's not entirely clear that the other package doesn't include the needed file to install the dependencies.  Aside from that one file, everything else worked, so why not include it?
cd /tmp
tar zxf ~/Downloads/plaso-20200430.tar.gz
```
I'm familiar with pip, which is why I didn't understand the dependencies.ini (expecting the -r requirements.txt), but Docker is definitely the easier way to go.

**Comment by joachimmetz** [comment]
> Aside from that one file, everything else worked, so why not include it?

To prevent people messing up their installations with pip or having broken build environment and the time it takes to help troubleshoot them.

dependencies.ini is a project specific configuration file to generate files that define dependencies, like requirements.txt.
