### ISSUE TITLE
Missing events when using USNjrnl parser with pyfsntfs 20200627

### ISSUE THREAD

**Issue by william-billaud** [log2timeline/plaso#3199]
**Description of problem:**

The parser usnjrnl does not generate any event when libntfs == 20200627.

With libfsntfs-python-20200805 the bug is not here anymore and event are generated as expected

It's not a bug anymore but it could be useful to update the requirement.txt to prevent this issue.

**Command line and arguments:**

`log2timeline.py --parser usnjrnl --status_view linear --partition p2 --single_process --logfile log.txt usn.plaso ./disk.raw`
 and 
`log2timeline.py --parser usnjrnl --status_view linear --partition p2 --single_process --logfile log.txt --vfs_back_end tsk usn.plaso ./disk.raw`

After both usnjrnl did not generate any event

**Source data:**

https://www.enisa.europa.eu/ftp/ENISA-LOT3-Evidence.zip
(disk.raw is inside the vmdk)

That was not the sample where I first found the bug, but I was able to reproduce the bug on this sample.
Both sample are Windows 10

**Plaso version:**

20200717
libfsntfs-python==20200627

**Operating system Plaso is running on:**

Ubuntu 18.04, installed via pip + pip install requirement.txt

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html#producing-debug-logs]

For more information see the [troubleshooting
guide][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html].

**Comment by joachimmetz** [comment]
So technically libfsntfs was recently enhanced to better support the sparse data runs of the $UsnJrnl:$J data stream. libfsntfs is still experimental, but I can bump the minimum required version. 

> libfsntfs-python==20200627

we typically don't pin to specific versions, only to minimum versions

**Comment by william-billaud** [comment]
Sorry I was not clear.
The requirement when I installed was libfsntfs-python >= 20200414. 

libfsntfs-python==20200627 was the result of my pip freeze

**Comment by joachimmetz** [comment]
Ack. Note that we fix issues and update dependencies on a regular basis. Some are still experimental and can update frequently.

Changes to change the minimum requirement in: https://github.com/log2timeline/plaso/pull/3200
