### ISSUE TITLE
Padded unix timestamps can lead to incorrect conversion to human time strings. 

### ISSUE THREAD

**Issue by callowforensics** [log2timeline/plaso#3224]
**Description of problem:**

When running AnalyzeMFT against an $MFT file, one of the attributes parsed shown in the resulting body file has a unix timestamp (representing Content Modification Time) of "943378176", which converts to "11/23/1999 @ 5:29pm (UTC)". Upon processing the body file using log2timeline.py and psort.py, the resulting JSON lines output file has a padded version of the unix timestamp, which is shown as "943378176000000". Whilst all values in the JSON lines output seem to be padded, it might be preferable for them not to be as when these timestamps are read by other tools it can lead to incorrect interpretation of them. Generally I can take a padded timestamp such as "1244465284000000," and convert it to a human date by using just its first 10 numbers (1244465284). Whilst a similar trim should be possible for the "943378176000000" timestamp, it would have to be done using the first 9 numbers rather than 10 (the first 10 numbers convert to 12/11/2268 @ 6:56am (UTC)), which causes unnecessary complications rather than just having the number be presented in the json lines file without padding. 

It should however be noted that there might be a very good reason for this padding and that my best approach here would be to amend my ingestion tool to just strip all trailing zeros during conversion to human time. It might also be the case that I'm missing something obvious in my approach.

**Command line and arguments:**

- analyzeMFT.py -b 'mft.body' -f '$mft' --bodyfull

- log2timeline.py -z UTC mft.plaso mft.body

- log2timeline.py -o json_line -w mft.json mft.plaso

**Source data:**

I can provide this to you upon request.

**Plaso version:**

20200717

**Operating system Plaso is running on:**

Linux version 5.4.0-45-generic (buildd@lcy01-amd64-014) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020

**Installation method:**

Via instructions detailed here: https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html

If multiple methods were used please indicate.

**Debug output/tracebacks:**

No tracebacks noted.

**Comment by joachimmetz** [comment]
> Upon processing the body file using log2timeline.py and psort.py, the resulting JSON lines output file has a padded version of the unix timestamp, which is shown as "943378176000000"

This is not "padding", the "Plaso timestamp" is microseconds since Jan 1, 1970 00:00:00.000000

AnalyzeMFT has removed 100ns accuracy from the when it stored the results in a bodyfile (also see: https://dfdatetime.readthedocs.io/en/latest/sources/Date-and-time-values.html#accuracy-and-precision)

So it is unclear to me what you want in the context of this issue?

**Comment by callowforensics** [comment]
You are correct. Thank you for the quick response.

**Comment by joachimmetz** [comment]
@callowforensics also AnalyzeMFT is no longer maintained and has known shortcomings https://github.com/dkovar/analyzeMFT/issues/56.

**Comment by callowforensics** [comment]
Thank you @joachimmetz . Appreciate the responses and apologies for my misunderstanding of the time format.
