### ISSUE TITLE
Unable to parse export of in-memory Windows NT Registry data

### ISSUE THREAD

**Issue by Silentcartographer** [log2timeline/plaso#3266]
I am currently trying to automate some workflows and one thing I was looking at doing was using log2timeline to process registry files extracted from memory using Volatility 3 on an Ubuntu 18.04 build.

I have successfully extracted the files and ran third party tools to parse things such as the amcache successfully. 

On using log2timeline to run over the directory the dumped hives are in I only get last written times for the keys from the winreg parser and nothing else. 
I have also tried to use the same on the VMDK of the source mounted in Linux and get the same result. 

Using log2timeline over the VMDK directly gives the correct result with the registry files parsed. 

I would like to be able to parse dumped registry hives from memory images.

**Command line and arguments:**

log2timeline --parsers winreg,amcache /home/sansforensics/yar/regdump /home/sansforensics/yar/reg2.plaso

**Source data:**

Source data is the vmem file of an MSEdge developer VM from Microsoft, Windows 10 with the registry hives dumped using Volatility 3 

**Plaso version:**

plaso - log2timeline version 20200121

**Operating system Plaso is running on:**

Ubuntu 18.04 LTS Desktop 

**Installation method:**

Part of SIFT distribution 

**Debug output/tracebacks:**

```
**************** Session: 7a817a16-8d0a-451c-9c30-3e849b34ebeb *****************
                Start time : 2020-10-08T20:36:23.338649Z
           Completion time : 2020-10-08T20:36:33.343865Z
              Product name : plaso
           Product version : 20200121
    Command line arguments : /usr/bin/log2timeline.py --parsers winreg,amcache
                             /home/sansforensics/yar/registry2.plaso
                             /home/sansforensics/yar/regdump/
  Parser filter expression : amcache,winreg
Enabled parser and plugins : amcache, winreg, winreg/appcompatcache,
                             winreg/bagmru, winreg/bam, winreg/ccleaner,
                             winreg/explorer_mountpoints2,
                             winreg/explorer_programscache,
                             winreg/microsoft_office_mru,
                             winreg/microsoft_outlook_mru,
                             winreg/mrulist_shell_item_list,
                             winreg/mrulist_string,
                             winreg/mrulistex_shell_item_list,
                             winreg/mrulistex_string,
                             winreg/mrulistex_string_and_shell_item,
                             winreg/mrulistex_string_and_shell_item_list,
                             winreg/msie_zone, winreg/mstsc_rdp,
                             winreg/mstsc_rdp_mru, winreg/network_drives,
                             winreg/networks, winreg/userassist,
                             winreg/windows_boot_execute,
                             winreg/windows_boot_verify, winreg/windows_run,
                             winreg/windows_sam_users, winreg/windows_services,
                             winreg/windows_shutdown,
                             winreg/windows_task_cache,
                             winreg/windows_timezone,
                             winreg/windows_typed_urls,
                             winreg/windows_usb_devices,
                             winreg/windows_usbstor_devices,
                             winreg/windows_version, winreg/winlogon,
                             winreg/winrar_mru, winreg/winreg_default
        Preferred encoding : UTF-8
                Debug mode : False
          Artifact filters : N/A
               Filter file : N/A
   Number of event sources : 44
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
         windows_run : 4
   windows_sam_users : 22
  windows_typed_urls : 4
      winreg_default : 43022
               Total : 43052
--------------------------------------------------------------------------------

************************ Warnings generated per parser *************************
Parser (plugin) name : Number of warnings
--------------------------------------------------------------------------------
              winreg : 18
--------------------------------------------------------------------------------

************************* Pathspecs with most warnings *************************
Number of warnings : Pathspec
--------------------------------------------------------------------------------
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.BBI.0x840cede23000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.dosvcStatedat.0x840cef428000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.SOFTWARE.0x840ceae98000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.NONAME.0x840cea60c000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.HARDWARE.0x840cea6a2000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.BCD.0x840ceaf5c000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.DEFAULT.0x840cedaa0000.hive
                 2 : type: OS, location:
                     /home/sansforensics/yar/regdump/registry.COMPONENTS.0x840ceec34000.hive
                 1 : type: OS, location:
                     /home/sansforensics/yar/regdump/system32/config/SYSTEM
                 1 : type: OS, location:
                     /home/sansforensics/yar/regdump/system32/config/SYSTEM.hive
```

Please note I changed the directory structure for the SYSTEM hive to identify if the issues was path related.

**Comment by joachimmetz** [comment]
1. I see you are using 20200121, try a more recent version fist.
2. can you provide us with a test file to have a look if the dump is proper Windows NT Registry file, and not an in-memory state, of the hive which can be differetn

**Comment by Silentcartographer** [comment]
Attempted to parse with the latest release, plaso - log2timeline version 20201007  
Same issue with the registry files. 

**Pifo Output**
************************** Plaso Storage Information ***************************
            Filename : output1.plaso
      Format version : 20200523
        Storage type : session
Serialization format : json
--------------------------------------------------------------------------------

*********************************** Sessions ***********************************
a852c14b-f2f9-465e-9b71-dcf944ae0459 : 2020-10-09T10:10:17.992411Z
--------------------------------------------------------------------------------

************************* Events generated per parser **************************
Parser (plugin) name : Number of events
--------------------------------------------------------------------------------
         windows_run : 2
   windows_sam_users : 22
  windows_typed_urls : 2
      winreg_default : 21761
               Total : 21787
--------------------------------------------------------------------------------

No events labels stored.

************************ Warnings generated per parser *************************
Parser (plugin) name : Number of warnings
--------------------------------------------------------------------------------
              winreg : 9
--------------------------------------------------------------------------------

************************* Pathspecs with most warnings *************************
Number of warnings : Pathspec
--------------------------------------------------------------------------------
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.dosvcStatedat.0x840cef428000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.DEFAULT.0x840cedaa0000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.COMPONENTS.0x840ceec34000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.SOFTWARE.0x840ceae98000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.SYSTEM.0x840cea649000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.NONAME.0x840cea60c000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.HARDWARE.0x840cea6a2000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/registry.BBI.0x840cede23000.hive
                 1 : type: OS, location:
                     /home/dev/Documents/regdump/system32/config/SYSTEM.hive
--------------------------------------------------------------------------------

No analysis reports stored.

Files requested attached. Dumped with latest volatility3. 

[regdump.zip](https://github.com/log2timeline/plaso/files/5354162/regdump.zip)

**Comment by joachimmetz** [comment]
> Same issue with the registry files.

These don't look like regular Windows NT Registry files. See: https://en.wikipedia.org/wiki/Computer_file for a definition of file.

```
Unable to open: registry.SYSTEM.0x840cea649000.hive.
libregf_file_header_read_data: mismatch in file header checksum ( 0x42ff0ee0 != 0x42ff0ee1 ).
libregf_file_header_read_file_io_handle: unable to read file header.
libregf_internal_file_open_read: unable to read file header.
libregf_file_open_file_io_handle: unable to read from file handle.
libregf_file_open: unable to open file: registry.SYSTEM.0x840cea649000.hive.
info_handle_open_input: unable to open input file.
```

```
libregf_hive_bins_list_get_cell_at_offset: unable to retrieve hive bin cell at offset: 186496 (0x0002d880).
libregf_key_item_read_sub_keys_list: unable to retrieve hive bin at offset: 186496 (0x0002d880).
libregf_key_item_read: unable to read sub keys list at offset: 186496 (0x0002d880).
libregf_key_initialize: unable to read key item at offset: 384 (0x00000180).
libregf_key_get_sub_key: unable to initialize sub key: 0.
info_handle_key_fprint: unable to retrieve sub key: 0.
info_handle_file_fprint: unable to print root key info.
```

Plaso does not support export or in-memory Windows NT Registry structures.

**Comment by joachimmetz** [comment]
Closing issue, supporting in-memory structures not something on the current short list for Plaso.

**Comment by etinoxa** [comment]
I am new to plaso tools and still finding my way around. I want to extract the Windows version from the SOFTWARE reg file and display the output in the terminal.

**Comment by joachimmetz** [comment]
@etinoxa I recommend to learn some github etiquettes first and don't just hijack some random issue thread

**Comment by etinoxa** [comment]
@joachimmetz I am sorry I did that. couldn't find a forum to ask questions. I'll delete my comments
