### ISSUE TITLE
Unable to exclude parser when running log2timeline.py in Docker

### ISSUE THREAD

**Issue by mark-hallman** [log2timeline/plaso#3271]
**Description of problem:**

Using the nor or exclude operator on parsers no longer works.  This syntax has worked in prior versions of log2timeline to exclude specific parser that is part of a parser preset list.  The error is "Unknown parser or plugin names in element(s):"  I have incuded screenshots to illustrate the issue.

**Command line and arguments:**

`docker run log2timeline/plaso log2timeline.py -z UTC --parsers "win7,-filestat" /tmp/plaso.dump .`

`docker run log2timeline/plaso log2timeline.py -z UTC --parsers "win7,\!filestat" /tmp/plaso.dump .`

**Plaso version:**

Plaso - log2timeline version 20201007 running in the official docker image

**Operating system Plaso is running on:**

Ubuntu 20.04 Desktop & Docker version 19.03.13, build 4484c46d9d

**Installation method:**

Docker image  log2timeline/plaso was used.

**Debug output/tracebacks:**

################################### with --parsers "win7,-filestat"  ###################################### 
root@ubuntu:~# `docker run log2timeline/plaso log2timeline.py -d -z UTC --parsers "win7,-filestat" /tmp/plaso.dump .`
2020-10-22 17:05:08,366 [INFO] (MainProcess) PID:6 <data_location> Determined data location: /usr/share/plaso
2020-10-22 17:05:08,383 [INFO] (MainProcess) PID:6 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]

Source path		: /home/plaso
Source type		: directory
Processing time		: 00:00:00

Processing started.
Unknown parser or plugin names in element(s): "-filestat" of parser filter expression: -filestat,amcache,bencode,binary_cookies,chrome_cache,chrome_preferences,custom_destinations,czip/oxml,esedb,esedb/file_history,esedb/msie_webcache,filestat,firefox_cache,gdrive_synclog,java_idx,lnk,mcafee_protection,msiecf,olecf,olecf/olecf_automatic_destinations,opera_global,opera_typed_history,pe,plist/safari_history,prefetch,recycle_bin,sccm,setupapi,skydrive_log,skydrive_log_old,sqlite/chrome_17_cookies,sqlite/chrome_27_history,sqlite/chrome_66_cookies,sqlite/chrome_8_history,sqlite/chrome_autofill,sqlite/chrome_extension_activity,sqlite/firefox_cookies,sqlite/firefox_downloads,sqlite/firefox_history,sqlite/google_drive,sqlite/safari_historydb,sqlite/skype,symantec_scanlog,usnjrnl,winevtx,winfirewall,winjob,winreg
root@ubuntu:~# 

################################### with --parsers "win7,\!filestat"  ###################################### 

root@ubuntu:~#` docker run log2timeline/plaso log2timeline.py -d -z UTC --parsers "win7,\!filestat" /tmp/plaso.dump .`
2020-10-22 17:08:08,292 [INFO] (MainProcess) PID:9 <data_location> Determined data location: /usr/share/plaso
2020-10-22 17:08:08,309 [INFO] (MainProcess) PID:9 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]

Source path		: /home/plaso
Source type		: directory
Processing time		: 00:00:00

Processing started.
Unknown parser or plugin names in element(s): "/!filestat" of parser filter expression: /!filestat,amcache,bencode,binary_cookies,chrome_cache,chrome_preferences,custom_destinations,czip/oxml,esedb,esedb/file_history,esedb/msie_webcache,filestat,firefox_cache,gdrive_synclog,java_idx,lnk,mcafee_protection,msiecf,olecf,olecf/olecf_automatic_destinations,opera_global,opera_typed_history,pe,plist/safari_history,prefetch,recycle_bin,sccm,setupapi,skydrive_log,skydrive_log_old,sqlite/chrome_17_cookies,sqlite/chrome_27_history,sqlite/chrome_66_cookies,sqlite/chrome_8_history,sqlite/chrome_autofill,sqlite/chrome_extension_activity,sqlite/firefox_cookies,sqlite/firefox_downloads,sqlite/firefox_history,sqlite/google_drive,sqlite/safari_historydb,sqlite/skype,symantec_scanlog,usnjrnl,winevtx,winfirewall,winjob,winreg
root@ubuntu:~# 

########################################
![image](https://user-images.githubusercontent.com/16808320/96906099-f54ede00-145e-11eb-84b2-862dffaeab35.png)

**Comment by joachimmetz** [comment]
@mark-hallman First of all the `-` was changed to `!` about 4+ years ago see: https://github.com/log2timeline/plaso/commit/28ee1825036b7386bb3f2c231261cbed3524716f

Since `!` can be a special character for some shells try passing single quotes instead of double `'win7,!filestat'`

Since I have your attention can you respond to: https://github.com/mark-hallman/plaso_filters/issues/created_by/joachimmetz and update your filters

**Comment by joachimmetz** [comment]
Seeing that https://github.com/mark-hallman/plaso_filters was archive without any accompanying explanation. I assume you read my reply and I'll consider this question answered.

**Comment by mark-hallman** [comment]
Hey Joachim,

No,  your assumption is not correct.  The plaso_filters repo was archived
weeks ago.   It was done at the same time that I asked SANS to take down
the Plaso Filters Cheatsheet because it is outdated.   SANS is taking that
cheat sheet off their website and will no longer be distributing it in
their classes.  This was done as a courtesy to you in response to your
request to remove the outdated material.  Is there anything else you would
like me to do in that regard?

Regards,

-Mark

**Comment by joachimmetz** [comment]
> No,  your assumption is not correct.  The plaso_filters repo was archived weeks ago.

Yeah, an update from your end on the issue tracker could have prevented the incorrect assumption.
The lack of communication and direct contribution from the SANS side regarding Plaso has been very disappointing over the year.

> This was done as a courtesy to you in response to your request to remove the outdated material.  

The request was to make sure what ever SANS is distributing regarding Plaso is up to date, seeing some of the material was out of date multiple years. A courtesy would have been to keep the material up to date and answer my issues back in May.
