### ISSUE TITLE
winevt_rc: unhandled sqlite3.OperationalError

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#329]
A condition that uses a Unicode character raises a sqlite3.OperationalError in
https://github.com/log2timeline/plaso/blob/master/plaso/formatters/winevt_rc.py#L90
- [ ] reproduce (str should be UTF-8 https://docs.python.org/2/library/sqlite3.html)
- [ ] find root cause (pysqlite Unicode handling?)
- [ ] come up with a fix

**Comment by joachimmetz** [comment]
@wdrone can you add more information about the conditions under which you encountered the issue you tried to solve in PR #328

**Comment by wdrone** [comment]
@joachimmetz I will have to hunt down the exact data that caused the error. I'll post back within a week.

**Comment by joachimmetz** [comment]
Thx that would be useful/

**Comment by Onager** [comment]
@wdrone Have you been able to reproduce this?

Removing as a blocker for 1.4 until we can reproduce this.

**Comment by wdrone** [comment]
Negative, haven't been able to find the E01 that caused the issue.

**Comment by joachimmetz** [comment]
Unable to reproduce. Closing this issue seeing that we're moving to SQLite storage and considering integrating winevtrc functionality into plaso extraction directly https://github.com/log2timeline/plaso/issues/163.
