### ISSUE TITLE
worker_timeout integer type require

### ISSUE THREAD

**Issue by forensicsrookie** [log2timeline/plaso#3294]
I try to change the minutes before a worker gets killed using --worker_timeout.
It seems like the option is expecting a float value. However, I can't get the argument to work. Every time I get the following error:
`ERROR: Unsupported option: worker_timeout integer type required.`

I use the following statement:
`log2timeline.py windows.plaso apl_win10.E01 --worker_timeout 60.0`

I also tried the following different versions of 60 minutes:
60, 60.0, 60,0, '60', '60.0', '60,0', "60", "60.0", "60,0"

I'm using the current release (20201007). Thanks!

**Comment by joachimmetz** [comment]
So https://github.com/log2timeline/plaso/blob/master/plaso/cli/helpers/workers.py#L39 is set to float.

But https://github.com/log2timeline/plaso/blob/master/plaso/cli/helpers/workers.py#L83 expects it to be an integer https://github.com/log2timeline/plaso/blob/614e2c889d42a5db06424f6ec97dbbc6bf647c15/plaso/cli/helpers/interface.py#L24

A work-around for now is change https://github.com/log2timeline/plaso/blob/master/plaso/cli/helpers/workers.py#L39 in to int

I'll make some changes to address this short coming

**Comment by joachimmetz** [comment]
However note that a worker timing out typically is an indication of an underlying problem with one of the parsers

**Comment by joachimmetz** [comment]
Changes merged, closing issue.
