### ISSUE TITLE
Replace PyCrypto with PyCryptodome

### ISSUE THREAD

**Issue by rhertzog** [log2timeline/plaso#3323]
plaso doesn't use PyCrypto but it still has dependencies on it due to #1024

Once dfvfs has been updated to use PyCryptodome (see https://github.com/log2timeline/dfvfs/issues/517) instead of PyCrypto, then that indirect dependency needs to be updated too.

**Comment by joachimmetz** [comment]
See https://github.com/log2timeline/dfvfs/issues/517

**Comment by joachimmetz** [comment]
Related issue: https://github.com/log2timeline/plaso/issues/2779
