### ISSUE TITLE
pe parser: add support for additional date and time values

### ISSUE THREAD

**Issue by binglot** [log2timeline/plaso#3324]
Plaso currently supports parsing various timestamps from PE files such as Compilation, Resources directory or Imports directory.

For example:
https://github.com/log2timeline/plaso/blob/6debdabbce3619b3210efa2a2cbc91242c02d4e3/plaso/parsers/pe.py#L82

However, it doesn't seem to support parsing all the timestamps the `pefile` library provides access to, for example the Exports Directory or the Debug Directory (https://github.com/erocarrera/pefile/blob/ab5f27a26c7f408aba61d02c5ec91ee8a28b1e50/pefile.py#L1674).

The value of supporting more sources of timestamps is that it increases the chances of detecting timestamp manipulation if one of them was mistakenly forgotten.

**Comment by joachimmetz** [comment]
Possible duplicate issue: https://github.com/log2timeline/plaso/issues/1557

**Comment by joachimmetz** [comment]
Support for extracting more date and time values has been added in the mean time. Reopen if there are more to be added.
