### ISSUE TITLE
Refactor data_location setting.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#336]
Currently it's tied to option parsing, which is causing problems for timesketch. See https://github.com/google/timesketch/issues/111

**Comment by joachimmetz** [comment]
Not sure what you mean by "refactor" here but the data location selection as in: https://github.com/log2timeline/plaso/blob/master/plaso/cli/tools.py#L101 should remain as-is. It's the tool that can determine the data location not the front-end.

It should be passed to the front-end with at call to  SetDataLocation
https://github.com/log2timeline/plaso/blob/master/plaso/frontend/analysis_frontend.py#L40

**Comment by Onager** [comment]
Hmm, I think you're right - I was thinking that the CLI handling code is the wrong place to keep a default, but with the way we do auto-detection, I suppose this code does belong here.
