### ISSUE TITLE
Where can I find log2timeline.exe and psort.exe?

### ISSUE THREAD

**Issue by tej7gandhi** [log2timeline/plaso#3364]
Hello,

Please provides details for location of log2timeline.exe and psort.exe?

Thanks and Regards
Tej Gandhi

**Comment by joachimmetz** [comment]
These are no longer provided. The reason why are in previous release notes. We recommend to use the Plaso Docker image instead.

**Comment by tej7gandhi** [comment]
Hello Jaochimmetz,

I was utilizing cdqr.exe to parse artifacts on Windows machine,
https://github.com/orlikoski/CDQR/releases/tag/20191226
 which makes utilization of log2timeline.exe;how should I go about executing that?

Thanks and Regards
Tej Gandhi

**Comment by joachimmetz** [comment]
@tej7gandhi this is not the CDQR project. So I cannot help you there. 

If you want exe versions of the Plaso tools you can build ones yourself using the (previous) maintainer instructions: https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html

Note that you are on your own here. We don't support it. 

If you want to run log2timeline independent of CDQR, have a look at https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html

**Comment by tej7gandhi** [comment]
Hello Joachm,

If I have a folder of artifacts such as MFT,log file,event logs etc and a
docker image of plaso running on that system,how can I parse those
files?How would I map the directory of Windows System to plaso directory?

Thanks and Regards
Tej Gandhi

**Comment by joachimmetz** [comment]
@tej7gandhi this is explained in the documentation: https://plaso.readthedocs.io/en/latest/sources/user/Installing-with-docker.html

**Comment by joachimmetz** [comment]
Closing issue since original question seems to have been answered
