### ISSUE TITLE
Chrome preferences parser test relies on dictionary ordering

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#340]
Dictionary ordering is not deterministic

**Comment by joachimmetz** [comment]
I assume this results in flaky testing?

**Comment by Onager** [comment]
Yep, flaky testing.

Some testing (run with tests with python -R) suggests this actually more widespread.

This isn't required for the 1.4 release, but we should try to get it fixed across the codebase.

Assigning to @vonnopsled to fix this specific issue, as he wrote the plugin.

**Comment by Onager** [comment]
Well, turns out I can't assign this, but @vonnopsled, please take a look.

**Comment by vonnopsled** [comment]
I will investigate.

**Comment by vonnopsled** [comment]
Fix committed: https://github.com/log2timeline/plaso/commit/067f3c34b45d8470de50f449915534010acb8cb2
