### ISSUE TITLE
Add parser: Google Drive client sync_log.log

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#343]
Add parser for Google Drive client sync_log.log text format.

**Comment by johngalvin** [comment]
I've got a nearly-functional (hopefully) first pass of this which I'm hoping to clean up some more and mail for review in the next couple of days, assuming I can get over the next few bumps. Can someone assign this to me whenever is convenient?

Thanks!

**Comment by joachimmetz** [comment]
@johngalvin I've added you to plaso-contributors once you accept I can make you an owner

**Comment by johngalvin** [comment]
I believe #1735 closes this out. I might work on it more in the future but basic support should be present.
