### ISSUE TITLE
log2timeline abort: detected cache full

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#345]
Issue seen on p1 of "SIFT Workstation 3.0 Core Drive.vmdk" with libtsk/pytsk 4.2.0 and dfvfs 20150915

```
2015-09-28 21:32:14,252 [ERROR] (Worker_02 ) PID:15761 <worker> ABORT: detected cache full error while processing path spec: type: OS, location: SIFT Workstation 3.0 Core Drive.vmdk
type: VMDK
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00100000
type: TSK, data stream: , inode: 16122815, location: /usr/lib/jvm/java-6-openjdk-amd64/man/ja_JP.eucJP/man1/jsadebugd.1.gz
type: GZIP
```

Abort kicks in correctly:
```
2015-09-28 21:37:16,077 [ERROR] (MainProcess) PID:15752 <multi_process> Workers idle for too long
```

* [x] ~~[SQLite clean up](https://codereview.appspot.com/266280043/)~~
* [x] ~~[dfvfs no need the set data_stream in path spec when empty string](https://codereview.appspot.com/268230043)~~
* [x] ~~[Removed file entry reference from data stream](https://codereview.appspot.com/268300043)~~
* [x] ~~[Bug fixes](https://codereview.appspot.com/263630043)~~
  * mediator does not open data stream file object

**Comment by Onager** [comment]
I can reproduce this, also on processing a .gz file:
```
2015-09-28 23:01:30,630 [ERROR] (MainProcess) PID:12975 <worker> ABORT: detected cache full error while processing path spec: type: OS, location: /images/acserver.dd
type: RAW
type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00100000
type: TSK, data stream: , inode: 265735, location: /usr/share/consolefonts/CyrAsia-Fixed13.psf.gz
type: GZIP
```

**Comment by joachimmetz** [comment]
Have a look at data streams as a possible root cause

**Comment by Onager** [comment]
Data streams looks very suspect, syncing to 26f9099adf04619198f336d79ab60c9e141750df let me process the image that triggered the error last time.
