### ISSUE TITLE
PyInstaller build is unable to determine location of data files

### ISSUE THREAD

**Issue by SpongeBobCodePants** [log2timeline/plaso#3451]
**Description of problem:**
I've built log2timeline using this guide (and a few variations while troubleshooting):
https://plaso.readthedocs.io/en/latest/sources/developer/Packaging%20with%20pyinstaller.html?highlight=pyinstaller

When I run log2timeline.exe with any options I receive:
"ERROR: Unable to determine location of data files."

**Command line and arguments:**
If I am running a command option like -h, it works fine even with the error present. However, the tool will not actually run against an image or any files.

**Source data:**
The source of the data I run log2timeline against appears to be irrelevant. The error occurs in every situation I have tested.

**Plaso version:**
20201228

**Operating system Plaso is running on:**
Windows 10 Pro x64

**Installation method:**
Fresh Win 10 Pro x64 installation, python 3.9.1 and Windows Security/Defender disabled (due to making my life miserable).
https://github.com/log2timeline/plaso
https://github.com/log2timeline/l2tdevtools

**Debug output/tracebacks:**
The debug option for log2timeline doesn't produce any additional output. 

Before running "make_release.ps1" from l2tdevtools, I ran "run_tests.py" from plaso. All of the dependencies have a status of "OK" except for the "OPTIONAL" for elasticsearch. The tool reports running 1247 tests, 7 skipped, and 2 failed. The failures are:

```
======================================================================
FAIL: testPrintExtractionStatusUpdateWindow (cli.status_view.StatusViewTest)
Tests the _PrintExtractionStatusUpdateWindow function.
----------------------------------------------------------------------
======================================================================
FAIL: testWrite (cli.views.CLITabularTableView)
Tests the Write function.
----------------------------------------------------------------------
```

I searched around for this error message and found a similar issue from last year.

https://github.com/log2timeline/plaso/issues/2923

I read the replies and verified pytsk.pyd exists and is 64-bit. I also performed the same check with pyfsntfs. Also, Visual C runtime DLLs are installed.

Based on the previous conclusion, this is probably not a true "issue" and just something that requires tweaking (and more knowledge than I possess about this process, lol). Any help or nudge in the right direction is appreciated.

**Comment by joachimmetz** [comment]
You can specify the location of the data directory with `--data`. Seeing that you are creating a PyInstaller build make sure the data directory is included in the build.

**Comment by joachimmetz** [comment]
> I searched around for this error message and found a similar issue from last year.

Looks like a slightly different issue to me (different tests failing), you'll need to resolve the issues that the unit test are reporting to ensure your build environment is sane.

**Comment by joachimmetz** [comment]
No updates from reporter, assuming question has been answered, closing issue.

**Comment by SpongeBobCodePants** [comment]
I guess I should say I'm receiving "the same error when running log2timeline" instead of "I'm having the same issue" since different tests are failing. 

The main misunderstanding of mine is what "data files" means. I was thinking this was my evidence or the .plaso output file or something like that. I was able to fix the "data files" error by copying the "data" folder to the correct location.

After that, I received a similar error about "artifact definitions". So, pretty much the same process. 

As you mentioned, a tweak to pyinstaller should fix this during the build. It's easier to have the folders located where log2timeline can find everything vs adding it at the command line, but it is nice to have both options. 

Everything seems to be working at this point. I just need to put a bit more work in to figure out the cause of the failed tests. The issue seems to be related to how the tool communicates the current status while running. I'm still not sure what is wrong there. 

------------------------
FAIL: testPrintExtractionStatusUpdateWindow (cli.status_view.StatusViewTest)
Tests the _PrintExtractionStatusUpdateWindow function.
------------------------
FAIL: testWrite (cli.views.CLITabularTableView)
Tests the Write function.
------------------------

The one thing common in the error message from both is "Assertion Error: Lists differ:" Like the other issues, I suspect I need to figure out the right tweak for the build process.

Thank you!

**Comment by SpongeBobCodePants** [comment]
Full output below. Thank you.

======================================================================
FAIL: testPrintExtractionStatusUpdateWindow (cli.status_view.StatusViewTest)
Tests the _PrintExtractionStatusUpdateWindow function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\examiner\Desktop\plaso\plaso-20201228\plaso-20201228\tests\cli\status_view.py", line 156, in testPrintExtractionStatusUpdateWindow
    self._CheckOutput(output, expected_output)
  File "C:\Users\examiner\Desktop\plaso\plaso-20201228\plaso-20201228\tests\cli\status_view.py", line 61, in _CheckOutput
    self.assertEqual(output[5:], expected_output[5:])
AssertionError: Lists differ: ['', '\x1b[1mIdentifier      PID     Status    [173 chars], ''] != ['', 'Identifier      PID     Status          M[159 chars], '']

First differing element 1:
'\x1b[1mIdentifier      PID     Status    [61 chars]b[0m'
'Identifier      PID     Status          M[47 chars]File'

  ['',
-  '\x1b[1mIdentifier      PID     Status          Memory          '
?   -------

+  'Identifier      PID     Status          Memory          Sources         '
?                                                           ++++++++++++++++

-  'Sources         Events          File\x1b[0m',
+  'Events          File',
   'f_identifier    123     f_status        0 B             29 (29)         456 '
   '(456)       f_test_file',
   '',
   '']

======================================================================
FAIL: testWrite (cli.views.CLITabularTableView)
Tests the Write function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\examiner\Desktop\plaso\plaso-20201228\plaso-20201228\tests\cli\views.py", line 150, in testWrite
    self.assertEqual(string.split(b'\n'), expected_strings)
AssertionError: Lists differ: [b'\x1b[1mName            Description\x1b[0m[99 chars] b''] != [b'Name            Description', b'First nam[85 chars] b'']

First differing element 0:
b'\x1b[1mName            Description\x1b[0m'
b'Name            Description'

- [b'\x1b[1mName            Description\x1b[0m',
?    -------                           -------

+ [b'Name            Description',
   b'First name      The first name in the table',
   b'Second name     The second name in the table',
   b'']

----------------------------------------------------------------------

**Comment by joachimmetz** [comment]
looks like an issue in determining your platform is Windows e.g. https://github.com/log2timeline/plaso/blob/20201228/tests/cli/views.py#L147

What is the value of `sys.platform` on your configuration (Operating system + Python version)?

**Comment by SpongeBobCodePants** [comment]
If I execute `print (sys.platform)` on the machine where I performed the build, I get a value of "win32". 
The system is Windows 10 v20H2 Build 19042.746.  
When I type "python" at a command prompt, it returns: "Python 3.9.1 (tags/v3.9.1:1e5d33e) [MSC v.1927 64 bit (AMD64)] on win32.

**Comment by SpongeBobCodePants** [comment]
I decided to watch things in VS Code to see what I could find. It still appears that the 
`if not sys.platform.startswith('win'):` 
logic is fine. So the value `expected_strings` reads...well, as expected. It's this line that contains the "x1b" string:
`output_writer = test_lib.TestBinaryOutputWriter()` @https://github.com/log2timeline/plaso/blob/301cf89361ee23a7d92f1abfed978d5ac7b1a1ea/tests/cli/views.py#L129
...and then converted to a string @
https://github.com/log2timeline/plaso/blob/301cf89361ee23a7d92f1abfed978d5ac7b1a1ea/tests/cli/views.py#L137
I looked at test_lib.py, but haven't been able to figure it out yet, lol.
![plaso-test](https://user-images.githubusercontent.com/70819570/106754984-9a02bf00-65fb-11eb-9ed8-1d54f285b689.png)

**Comment by joachimmetz** [comment]
That is likely generated here https://github.com/log2timeline/plaso/blob/master/plaso/cli/views.py#L246. Do you have pywin32 installed?

**Comment by SpongeBobCodePants** [comment]
That seems to have done it. Thank you! Now I just need to figure out how I missed that.

I often use Linux for this, but there are some lab / air-gapped situations where having the Windows binary helps.
