### ISSUE TITLE
Unable to run setup.py with Python 3.5

### ISSUE THREAD

**Issue by raghadalhelal** [log2timeline/plaso#3452]
**Description of problem:**

I was trying to run log2timeline.py with python2 and it worked (it was installed on the SIFT already) but _not_ with python3.

**Command line and arguments:**

I tried to install plaso module for python3
`python3 -m pip install plaso`

and I got this error message

```
Collecting plaso
  Downloading https://files.pythonhosted.org/packages/8f/15/465806317d8ef766845b03db928f4e450e068220a47823d99bbab54e2abc/plaso-20201228.tar.gz (2.7MB)
    100% |████████████████████████████████| 2.7MB 530kB/s 
    Complete output from command python setup.py egg_info:
    Unsupported Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)
    [GCC 5.4.0 20160609], version 3.6 or higher required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q6hhnybu/plaso/
You are using pip version 8.1.1, however version 21.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by joachimmetz** [comment]
> Unsupported Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)

You'll need to use Python 3.6 or later, we no longer support Python 2 or earlier version of Python 3

**Comment by joachimmetz** [comment]
For context:

Per the Python Software Foundation, Python 3.4.10 received its last security and bug fixes on March 18, 2019, and has been marked as end-of-life. Similarly, Python 3.5 released its final non-security update on November 1, 2019, and reached end-of-life status on September 13, 2020.
