### ISSUE TITLE
option --vss_only is not honored

### ISSUE THREAD

**Issue by tobraha** [log2timeline/plaso#3455]
**Description of problem:**

When using the option --vss_only, the output does not exclude the standard partition; both the VSS and 'live' partition data are included.  The tool completes with no errors, but upon reviewing the storage file data, the unwanted data is present.

![image](https://user-images.githubusercontent.com/37032081/106359692-7543da00-62d1-11eb-90d1-b9498babc341.png)
                   **screenshot of some sample data uploaded to elasticsearch/kibana*

Side note:  I've used plaso for years and this is the first occasion on which I've tried to use the --vss_only option (I can't recall when the option was even introduced).  I gazed at the code for a few hours to try to figure this out, but had no such luck.

**Command line and arguments:**

Docker command-line:
```
docker run -ti -v $PWD/Evidence:/case/Evidence -v $PWD/plaso:/case/plaso log2timeline/plaso log2timeline.py --partition 1 --vss_stores 12 --vss_only -t C: --hashers md5 --workers 8 -f /case/plaso/plaso_excludes.yaml --logfile /case/plaso/Results/item001-vss12_log2timeline.gz /case/plaso/Results/item001-vss12.plaso /case/Evidence/ITEM001/image/001_hp-desktop-500gb_seagate.E01 --debug
```

From 'pinfo.py -v':
```
    Command line arguments : /usr/bin/log2timeline.py --unattended --partition
                             1 --vss_stores 12 --vss_only -t C:
                             --hashers md5 --workers 8 -f
                             /case/plaso/plaso_excludes.yaml --logfile
                             /case/plaso/Results/item001-vss12_log2timeline.gz
                             /case/plaso/Results/item001-vss12.plaso
                             /case/Evidence/ITEM001/image/001_hp-desktop-500gb_seagate.E01
                             --debug
```

Content of 'plaso_excludes.yaml':
```
description: Windows Component Store Files
type: exclude
path_separator: '\'
paths:
  - '%ProgramFiles%'
  - '%ProgramFilesX86%'
  - '%SystemRoot%\\WinSxS'
  - '%SystemRoot%\\assembly'
  - '%SystemRoot%\\System32\\DriverStore'
  - '%SystemRoot%\\Inf'
  - '%SystemRoot%\\SysWOW64'
  - '%SystemRoot%\\System32\\oem'
  - '%SystemRoot%\\SoftwareDistribution'
  - '%SystemRoot%\\Installer'
  - '%SystemRoot%\\servicing'
  - '\\\$WINDOWS.\~BT'
  - '\\Windows10Upgrade'
```

**Source data:**

* Segmented EWF file captured using FTK Imager v4.3.0.18
* Source machine was an HP desktop running Windows 7; 500 GB HDD
* Capture contains 12 VSS stores

**Plaso version:**

20201228

**Operating system Plaso is running on:**

Ubuntu Server 18.04.5 LTS

**Installation method:**

For example:
* installed from hub.docker.com/r/log2timeline
* i.e. `docker pull log2timeline/plaso`
* Docker version 20.10.2, build 2291f61

**Debug output/tracebacks:**

Debug output was produced, but I'm not sure of a good way to provide the relevant content here...  if needed, I can send the file privately.

**Comment by joachimmetz** [comment]
@tobraha thx for the report, I'll have a look to see if I can reproduce and address the issue.

**Comment by joachimmetz** [comment]
@tobraha was able to reproduce this, the check for VSS only option was lost.

Note to self: the implementation of the VSS only option is clunky. Determine a cleaner solution as part of https://github.com/log2timeline/plaso/issues/3315

**Comment by tobraha** [comment]
Thank you, Mr. Metz!  :+1:   You (and other contributors here) do amazing work; the more I look at this code the more I appreciate this wonderful beast of a program.
