### ISSUE TITLE
How can I have a file-like object interface with pefile SignedPEFile?

### ISSUE THREAD

**Issue by ragehead** [log2timeline/plaso#3456]
I'm using python3 and I want to use another module that verifies the digital signature of an execution file. So I tried to add some 
lines in image_export_tool.py for the definition `_CalculateDigestHash` but I got an error message.

The command line that I used is:

`python3 image_export.py --signatures exe_mdz image.e01
`
And here is the code that I added after defining `file_object`

```
file_object = file_entry.GetFileObject(data_stream_name=data_stream_name)
pf = signify.signed_pe.SignedPEFile(file_object)
        try:
            pf.verify()
            print("Signature: valid")
        except Exception as e:
            print("Signature: invalid")
            print("    {}".format(e))
```

But all I get is `Signature: invalid` (it usually works with reading files from the file system), which seems that the file object is somehow modified because I also tried to test it with other modules.

**Comment by joachimmetz** [comment]
Maybe you need to set the file_object to offset 0 if SignedPEFile assumes this to be the case. Also what interface does SignedPEFile expect? Since for other parts of pefile a slice interface was needed.

**Comment by joachimmetz** [comment]
@ragehead for context this is mainly a pefile or dfVFS related question not a Plaso one
