### ISSUE TITLE
Preferred platform to run Plaso?

### ISSUE THREAD

**Issue by LordGarithm** [log2timeline/plaso#3522]
Dear team,

This is is not an issue or bug to be fix, it is just a question which answer I couldn't find by browsing.

I would like to know if there is a preferred OS to run Plaso or if the OS selection is not relevant from the efficiency point of view. I was thinking to install plaso in Linux but I have been suggested to use Docker in Winows for compatibility with other tools.

I apologies if this is not the proper channel for such questions.

Best regards,

**Comment by joachimmetz** [comment]
Both Linux and (Linux) Docker on Windows are supported https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html

A couple of things to consider:
* running in Docker will introduce some overhead and a little bit more more complex to use
* Python on Linux has a better support for multi processing then on Windows
* GIFT PPA (Ubuntu) and GIFT COPR (Fedora) support is provided, no package manager equiv for Windows

**Comment by joachimmetz** [comment]
No additional input from original poster, assuming question was answered.
