### ISSUE TITLE
psort failing on corrupt storage file

### ISSUE THREAD

**Issue by alfonsocaponi** [log2timeline/plaso#3524]
**Description of problem:**

After locking a psort running session with "Ctrl+C"...

**Command line and arguments:**

`# psort.py -o l2tcsv -w home.timeline.csv /mnt/home.plaso.dump`

**Source data:**

Linux home dirs

**Plaso version:**

plaso - psort version 20210213

**Operating system Plaso is running on:**

Ubuntu 20.04.2 LTS

**Installation method:**

apt-get

**Debug output/tracebacks:**

`lab ~ # psort.py -o l2tcsv -w home.timeline.csv /mnt/home.plaso.dump
2021-03-16 16:07:16,468 [INFO] (MainProcess) PID:1241 <data_location> Determined data location: /usr/share/plaso
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 417, in GetSessions
    session_start = next(session_start_generator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 541, in ProcessStorage
    for session in storage_reader.GetSessions():
  File "/usr/lib/python3/dist-packages/plaso/storage/interface.py", line 419, in GetSessions
    raise IOError('Missing session start: {0:d}'.format(session_index))
OSError: Missing session start: 2
`

**Comment by joachimmetz** [comment]
Looks like your storage file is corrupt.

**Comment by alfonsocaponi** [comment]
> Looks like your storage file is corrupt.

What checks can I do? (in addition to using another storage)

**Comment by joachimmetz** [comment]
The storage file is a SQLite3 file. You can tweak it with the SQLite CLI tool. I would need to take a closer look first, where psort.py is raising the error and see what could be possibly corrupt. Though my time is very limited at the moment.

**Comment by alfonsocaponi** [comment]
The sqlite3 file seems ok:

$ sqlite3 home.plaso.dump
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> **pragma integrity_check**;
**ok**

:(

**Comment by joachimmetz** [comment]
as the error message might suggest, it's the data that is inconsistent (corrupt), not the underlying SQLite data structures

**Comment by alfonsocaponi** [comment]
Ok, I'm re-creating the storage file.

**Comment by joachimmetz** [comment]
I assume the question has been answered and I'll close the issue then
