### ISSUE TITLE
Add support for None value in FlagsEventFormatterHelper

### ISSUE THREAD

**Issue by davidschmidt-github** [log2timeline/plaso#3525]
If psort.py runs over a plaso file it comes to a error.
If the input_value is type of None, the code throws a exception.
https://github.com/log2timeline/plaso/blob/7533db2d1035ca71d264d6281ebd5db2d073c587/plaso/formatters/interface.py#L178

```python
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```
https://github.com/log2timeline/plaso/blob/7533db2d1035ca71d264d6281ebd5db2d073c587/plaso/formatters/interface.py#L182

FIX could be:
```python
      for flag, mapped_value in self.values.items():
    	if input_value is not None:
          if flag & input_value:
            output_values.append(mapped_value)
```

**Comment by joachimmetz** [comment]
Thx for flagging, this only happens when a flag value is None and the flags format helper is used. Added alternative changes to skip such flag values in https://github.com/log2timeline/plaso/pull/3528.

**Comment by davidschmidt-github** [comment]
THX
