### ISSUE TITLE
plaso.parsers.ntfs.NTFSFileStatEventData has no file_size attribute?

### ISSUE THREAD

**Issue by ctmayhew** [log2timeline/plaso#3527]
I don't see any file size attribute to `NTFSFileStatEventData`. The real size of the file should be in the MFT record, but it does not seem to be parsed? (or I could be mistaken)

https://plaso.readthedocs.io/en/latest/sources/api/plaso.parsers.html?highlight=fs%3Astat%3Antfs#plaso.parsers.ntfs.NTFSFileStatEventData

**Comment by joachimmetz** [comment]
depends on what you are looking at the "file" size is related to a `$DATA` attribute, not a `$STANDARD_INFORMATION` or `$FILE_NAME` attribute

**Comment by ctmayhew** [comment]
I've pointed plaso at an $MFT file I extracted from a host. Would the file size be stored somewhere else?

**Comment by joachimmetz** [comment]
There is not necessarily a single file size for an MFT attribute. Have a read of https://osdfir.blogspot.com/2020/04/parsing-mft-ntfs-metadata-file.html

**Comment by joachimmetz** [comment]
No update from original reporter, assuming question is answered, closing issue.
