### ISSUE TITLE
psort l2tcsv fails with TypeError on HEAD

### ISSUE THREAD

**Issue by blue212121** [log2timeline/plaso#3574]
**Description of problem:**

psort fails with exception when trying to export to l2tcsv format
xlsx format works fine with same Plaso file

**Command line and arguments:**

psort.py -o l2tcsv -w <outfile.csv> <log2timeline.dump>

**Source data:**

Please provide the source data you used when you experienced the problem.
For publicly available data please provide an URL or path of the source data.

- can upload dumpfile somewhere i guess if it's needed

**Plaso version:**

psort version ~~20210412~~ HEAD

**Operating system Plaso is running on:**

5.4.0-72-generic #80~18.04.1-Ubuntu

**Installation method:**

cloned github repo and setup using python3 setup.py install and python3 -m pip install -r requirements.txt

**Debug output/tracebacks:**

```
Traceback (most recent call last):
  File "/usr/local/bin/psort.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20210412', 'psort.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/EGG-INFO/scripts/psort.py", line 101, in <module>
    if not Main():
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/EGG-INFO/scripts/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/cli/psort_tool.py", line 603, in ProcessStorage
    time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/multi_processing/psort.py", line 1059, in ExportEvents
    use_time_slicer=use_time_slicer)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/multi_processing/psort.py", line 592, in _ExportEvents
    deduplicate_events=deduplicate_events)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/multi_processing/psort.py", line 485, in _ExportEvent
    storage_reader, output_module, deduplicate_events=deduplicate_events)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/multi_processing/psort.py", line 642, in _FlushExportBuffer
    output_module.WriteEventMACBGroup(macb_group)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/output/l2t_csv.py", line 255, in WriteEventMACBGroup
    event_macb_group)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/output/l2t_csv.py", line 49, in GetFormattedEventMACBGroup
    field_name, event, event_data, event_data_stream, event_tag)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/output/formatting_helper.py", line 552, in GetFormattedField
    output_value = callback_function(event, event_data, event_data_stream)
  File "/usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/plaso/output/l2t_csv.py", line 126, in _FormatDate
    return '{0:02d}/{1:02d}/{2:04d}'.format(month, day_of_month, year)
TypeError: unsupported format string passed to NoneType.__format__
```

debug file does not generate with "-d" or "--debug" option even if i use "--logfile <filename>" with debug option as well

**Comment by blue212121** [comment]
log2timeline.py --troubles output:

`2021-05-08 07:59:01,740 [INFO] (MainProcess) PID:1777 <data_location> Determined data location: /usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/share/plaso
Using Python version 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

Path: /usr/local/lib/python3.6/dist-packages/plaso-20210412-py3.6.egg/EGG-INFO/scripts/log2timeline.py

plaso - log2timeline version 20210412

Checking availability and versions of dependencies.
[OK]		artifacts version: 20210404
[OK]		bencode
[OK]		certifi version: 2018.01.18
[OK]		chardet version: 3.0.4
[OK]		cryptography version: 2.1.4
[OK]		dateutil version: 2.6.1
[OK]		defusedxml version: 0.7.1
[OK]		dfdatetime version: 20200824
[OK]		dfvfs version: 20210501
[OK]		dfwinreg version: 20201006
[OK]		dtfabric version: 20200621
[OK]		elasticsearch version: 7.12.1
[OK]		future version: 0.18.2
[OK]		idna version: 2.6
[OK]		lz4 version: 3.1.3
[OK]		pefile version: 2019.4.18
[OK]		psutil version: 5.8.0
[OK]		pybde version: 20210327
[OK]		pycreg version: 20210502
[OK]		pyesedb version: 20210424
[OK]		pyevt version: 20210424
[OK]		pyevtx version: 20210424
[OK]		pyewf version: 20201230
[OK]		pyfsapfs version: 20210424
[OK]		pyfsext version: 20210504
[OK]		pyfshfs version: 20210424
[OK]		pyfsntfs version: 20210503
[OK]		pyfsxfs version: 20210403
[OK]		pyfvde version: 20210425
[OK]		pyfwnt version: 20210421
[OK]		pyfwsi version: 20210419
[OK]		pylnk version: 20210417
[OK]		pyluksde version: 20210419
[OK]		pymodi version: 20210501
[OK]		pymsiecf version: 20210420
[OK]		pyolecf version: 20210419
[OK]		pyparsing version: 2.4.7
[OK]		pyqcow version: 20210419
[OK]		pyregf version: 20210419
[OK]		pyscca version: 20210419
[OK]		pysigscan version: 20210419
[OK]		pysmdev version: 20210418
[OK]		pysmraw version: 20210418
[OK]		pytsk3 version: 20210419
[OK]		pytz
[OK]		pyvhdi version: 20210425
[OK]		pyvmdk version: 20210418
[OK]		pyvsgpt version: 20210207
[OK]		pyvshadow version: 20210425
[OK]		pyvslvm version: 20210425
[OK]		redis version: 3.5.3
[OK]		requests version: 2.18.4
[OK]		six version: 1.11.0
[OK]		urllib3 version: 1.22
[OK]		xlsxwriter version: 1.4.1
[OK]		yaml version: 3.12
[OK]		yara version: 4.1.0
[OK]		zmq version: 22.0.3

Also see: https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html
`

**Comment by blue212121** [comment]
> So it looks like you're running the development version (HEAD) not 20210412 https://github.com/log2timeline/plaso/blob/20210412/plaso/output/l2t_csv.py#L126

oh so 20210412 version has different line 126 i see, will try to install that version directly and get back to you

**Comment by joachimmetz** [comment]
Yes, and please do use one of the recommended installation methods https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html

pip without virtualenv is not one of them

**Comment by blue212121** [comment]
Followed: https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html

l2tcsv export now works fine... my problem is solved thank you for helping me out

should i close the issue or keep it open since error happens on HEAD?

**Comment by joachimmetz** [comment]
Keep it open as are reminder that HEAD is failing is due to recent changes.
