### ISSUE TITLE
Deprecate SlowLexicalTextParser

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#358]
This requires:

* [x] Replace the syslog parser with a different approach
* [x] [Replace the SELinux parser with a different approach](https://codereview.appspot.com/304790044/)
* [x] [Remove the SlowLexicalTextParser](https://codereview.appspot.com/304790044/)

**Comment by kiddinn** [comment]
This was the first approach to rewrite the syslog parser: https://codereview.appspot.com/57170053/ but this CL hasn't been touched for quite a while.

Possible to salvage something from this CL and continue it.

**Comment by joachimmetz** [comment]
Per discussion will try to tackle this later this week.
