### ISSUE TITLE
pcap parser: ValueError

### ISSUE THREAD

**Issue by rodgermoore** [log2timeline/plaso#360]
Plaso 1.3.0, Ubuntu 14.04.03 LTS server with default Python version 2.7.6 gives the following error on parsing pcap file captured with latest Wireshark version (1.12.7). 

```
2015-10-06 10:24:11,042 [ERROR] (MainProcess) PID:1607 <worker> Unknown format code 'd' for object of type 'float'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 471, in _ProcessPathSpec
    self._ProcessFileEntry(file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 430, in _ProcessFileEntry
    self._ParseFileEntryWithParser(parser_object, file_entry)
  File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 213, in _ParseFileEntryWithParser
    parser_object.UpdateChainAndParse(self._parser_mediator)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 72, in UpdateChainAndParse
    self.Parse(parser_mediator, **kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 256, in Parse
    self.ParseFileObject(parser_mediator, file_object, **kwargs)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/pcap.py", line 762, in ParseFileObject
    len(ethernet_frame), ethernet_frame.data)
  File "/usr/lib/python2.7/dist-packages/plaso/parsers/pcap.py", line 550, in _ParseIPPacket
    timestamp, source_ip_address, destination_ip_address)
ValueError: Unknown format code 'd' for object of type 'float'
Processing completed.
```

**Comment by joachimmetz** [comment]
Thanks for reporting this.

@kiddi the timestamp calculation here makes no sense:
https://github.com/log2timeline/plaso/blob/master/plaso/parsers/pcap.py#L754

In light of: https://wiki.wireshark.org/Development/LibpcapFileFormat
```
typedef struct pcaprec_hdr_s {
        guint32 ts_sec;         /* timestamp seconds */
        guint32 ts_usec;        /* timestamp microseconds */
        guint32 incl_len;       /* number of octets of packet saved in file */
        guint32 orig_len;       /* actual length of packet */
} pcaprec_hdr_t;
```

**Comment by joachimmetz** [comment]
Looks like this might have come from the dpkt documentation:
http://dpkt.readthedocs.org/en/latest/_modules/dpkt/pcap.html

**Comment by joachimmetz** [comment]
@kiddinn a couple of open points regarding this issue:

* improve tests (unit tests, end-to-end tests) the code path in the bug is not covered
* in context of: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/pcap.py#L550 what is the purpose of timestamp. Shouldn't this be an event?

**Comment by rodgermoore** [comment]
Reminder Ubuntu 14.04.03 LTS comes with python 2.7.6.

Only patched pcap.py. Tried the fix on this file http://download.netresec.com/pcap/maccdc-2012/maccdc2012_00016.pcap.gz . Log2timeline fills up memory to 3845 MB (4096 is max) and the process stalls, system gets unresponsive. Had to kill the process manually.

Do I have to have to update Plaso to dev release to test this fix?

**Comment by joachimmetz** [comment]
Looks like this parser consumes a large amount of memory when reconstruction streams. This likely requires a complete rewrite of this parser to fix.

> Log2timeline fills up memory to 3845 MB (4096 is max on test system) and the process stalls, system gets unresponsive. 

You'll find that your system is trying to free memory.

> Reminder Ubuntu 14.04.03 LTS comes with python 2.7.6.

Not sure what you are trying to say with this reminder.

> Do I have to have to update Plaso to dev release to test this fix?

What makes you think this?

**Comment by rodgermoore** [comment]
> Reminder Ubuntu 14.04.03 LTS comes with python 2.7.6
*Not sure what you are trying to say with this reminder.*

Issue #267 Psort Analysis plugins fills up memory, possibly caused because using an old version of Python. Ubuntu 14.04.03 does not have the latest Python version by default.

> Do I have to have to update Plaso to dev release to test this fix?
*What makes you think this?*

Plaso is a framework of scripts and dependencies. Wanted to check if just updating the pcap.py parser would be sufficient to test the fix. Maybe core functionality or dependencies have been altered / optimized in dev release which aren't tested when not updated to latest dev release.

**Comment by joachimmetz** [comment]
> Issue #267 Psort Analysis plugins fills up memory, possibly caused because using an old version of Python. Ubuntu 14.04.03 does not have the latest Python version by default.

As Issue #267 indicates:

> I suspect some issue with the multiprocessing queue on 2.7.5.

It does not indicate which version of Python this might have been fixed. Nor can you compare the Debian/Ubuntu version with a stock version of Python. I opt to have a look at the dpkg package and the patches that are included.

Also without knowing the root cause speculation about a solution/fix does not solve the issue.

> Maybe core functionality or dependencies have been altered / optimized in dev release which aren't tested when not updated to latest dev release.

We'll typically indicate that if that is the case.

**Comment by joachimmetz** [comment]
Disabling parser until rewrite.

**Comment by joachimmetz** [comment]
Updated: https://codereview.appspot.com/261650043/ to disable parser.
