### ISSUE TITLE
pinfo.py change how time zone information is represented

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#3615]
Issue created due to a question on the Slack channel.

pinfo.py shows the preferred time zone as part of the system configuration. However it would be likely better UX to show the preferred time zone as part of the session information and the detected system time zone as part of the system configuration.

**Comment by mistersimmons** [comment]
Hey @joachimmetz, I'm pretty green here, but would love to take a stab at this. Is this system configuration accessed locally within organization, or is it open to other external users?

**Comment by joachimmetz** [comment]
@mistersimmons I don't understand your question, FYI

"system configuration" is an attribute container https://github.com/log2timeline/plaso/blob/main/plaso/containers/artifacts.py#L420 stored part of the preprocessing information. 

pinfo.py and Plaso are open source, so everything is open to "external users"

If you want to get started helping out, I recommend starting with a simple parser or helping with documentation. Also see: https://plaso.readthedocs.io/en/latest/sources/developer/Developers-Guide.html

**Comment by mistersimmons** [comment]
@joachimmetz thank you for clarifying--I'll look into your recommendation. I'm just getting into UX and thought this issue would be good for me to apply some of what I'm learning from my bootcamp.

**Comment by joachimmetz** [comment]
UX in this context just refers to user experience and there is nothing special about it in the context of this issue
It refers to making certain domain specific information being represented in a less ambiguous way

Also note that general UX practices are not always a good fit for digital forensic purposes

**Comment by joachimmetz** [comment]
Time zone currently presented in:

* Session
* System configuration
* as available time zones

Closing issue
