### ISSUE TITLE
log2timeline does not enable all parser plugins unless the plugin list is explicitly specified

### ISSUE THREAD

**Issue by michael-ashburn** [log2timeline/plaso#3688]
For example, `win7_slow` includes `esedb`, but `esedb/srum` will not be used.

The problem is inconsistency in [`ParsersManager.GetParserObjects`](https://github.com/log2timeline/plaso/blob/030db76c23fcdabd7462f37924f724d34ee66b67/plaso/parsers/manager.py#L237):
- [ `ParserFilterExpressionHelper.SplitExpression`](https://github.com/log2timeline/plaso/blob/030db76c23fcdabd7462f37924f724d34ee66b67/plaso/filters/parser_filter.py#L194) uses an asterisk character ('*') to represet all plugins
- [`BaseParser.EnablePlugins`](https://github.com/log2timeline/plaso/blob/030db76c23fcdabd7462f37924f724d34ee66b67/plaso/parsers/interface.py#L112) expects that None or an empty list represents all plugins.

**Comment by joachimmetz** [comment]
thx for the report, I'll have a look as soon as time permits

**Comment by joachimmetz** [comment]
Made some changes in https://github.com/log2timeline/plaso/pull/3689

**Comment by joachimmetz** [comment]
Changes merged closing issue
