### ISSUE TITLE
Is there a limitation to the number of workers?

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#3757]
Hi team. Thanks for the great solution.
I am curious why is the maximum workers count seems to be limited to 15?
In my case, there are enough CPUs and IO speed, but processing is slow. Only 2 processors are working on what it seems MFT processing and all the rest of workers are idle.
Please advice on how to speed up processing.

**Comment by joachimmetz** [comment]
> I am curious why is the maximum workers count seems to be limited to 15?

It is not from `log2timeline.py --help`

```
  --workers WORKERS     Number of worker processes. The default is the number
                        of available system CPUs minus one, for the main
                        (foreman) process.
```

> Please advice on how to speed up processing.

@MariasStory I've told you this multiple times before. First of all can you explain in more details what your set up, is and what payloads you are processing? May things can have performance impact e.g. reading from and/writing to a network based share.

**Follow the issue template here, otherwise we cannot help you.**

> processing is slow

Can you provide some numbers instead of making some hand wavy claims.

**Comment by joachimmetz** [comment]
> Only 2 processors are working on what it seems MFT processing and all the rest of workers are idle.

15 workers should be still enough to utilize more than 2 cores. 15 here is more a maximum upper bound. As I requested in my previous reply can you describe your situation in more detail.

**Comment by MariasStory** [comment]
OK the --workers WORKERS helped to increase the workers count.

I cannot share all details, but at the moment, I am re-running with the debug logs on.

As you can see from the screenshot, the 2 "extracting" tasks are the two MFT files related and are running. All the rest are idle.
![image](https://user-images.githubusercontent.com/6576335/122771216-83a58900-d2a6-11eb-8f84-f4b255cb3534.png)

**Comment by joachimmetz** [comment]
From your screenshot there are only 2 tasks; 1 task per worker. Increasing the number of workers is not going to help you in this case.

**Comment by MariasStory** [comment]
BZW: I am using a docker version. If it meters.

**Comment by joachimmetz** [comment]
> BZW: I am using a docker version. If it meters.

yes that matters, Docker has more overhead, lower IO throughput,

> 4.9G and 500M

The 4.9G is going to take a while, assuming 8 - 12 events per 1024 bytes 10 - 15 Million events, which will not be a small timeline.

**Comment by MariasStory** [comment]
Infect, $MFT parsing is a time consuming procedure with plaso. Even when when the $MFT is of reasonable several hundred MB.
The old processor is much faster: https://github.com/dkovar/analyzeMFT

**Comment by MariasStory** [comment]
Merging is also a single process and very slow.
It also takes way too much memory.

**Comment by joachimmetz** [comment]
> The old processor is much faster: https://github.com/dkovar/analyzeMFT

that is because analyzeMFT skips essential information https://github.com/dkovar/analyzeMFT/issues/56

> Merging is also a single process and very slow.
> It also takes way too much memory.

If you think you can do it better why not contribute code changes instead of only complaints?

**Comment by MariasStory** [comment]
@joachimmetz I am sorry.
I did not mean to complain.
Just thought to point it out.
I am sure that you know it all very well ;-)

**Comment by joachimmetz** [comment]
> Just thought to point it out.

Just to point what out? Be aware that your comments come across as complaining, and someone that is not acting very constructive. 

> I am sure that you know it all very well ;-)

If you want to be funny or sarcastic, I'm not amused. Also you might want to read https://docs.github.com/en/github/site-policy/github-community-guidelines#building-a-strong-community 

```
Respect each other. Nothing sabotages healthy conversation like rudeness. Be civil and professional, and don’t post anything that a reasonable person would consider offensive, abusive, or hate speech. Don’t harass or grief anyone. Treat each other with dignity and consideration in all interactions.

You may wish to respond to something by disagreeing with it. That’s fine. But remember to criticize ideas, not people. Avoid name-calling, ad hominem attacks, responding to a post’s tone instead of its actual content, and knee-jerk contradiction. Instead, provide reasoned counter-arguments that improve the conversation.
```

Or do you want me to block you from this project?

**Comment by MariasStory** [comment]
@joachimmetz I am really sorry that you got offended.
I do respect your good work.
--
I did shortly look in the code for the merging procedure.
It looks like Redis is used, but I am not sure if I am looking in the right direction.
Maybe you can point me out, where the memory consumption happens?

**Comment by joachimmetz** [comment]
> I am really sorry that you got offended. I do respect your good work.

Realize that you are wasting my time, that might be the largest offense. First I have to ask you to give me necessary details, to try to help you out. You return the favor by giving bad advice and nonconstructive complaints.

> Maybe you can point me out, where the memory consumption happens?

Why? From your previous comments I got the impression you had this solved?
