### ISSUE TITLE
feature request: psort.py - remove ordering of output if timesketch or elasticsearch

### ISSUE THREAD

**Issue by davidrudduck** [log2timeline/plaso#3783]
Generally processing a triage image takes < 30 minutes, but pushing the data to elastic can take hours.

Is it possible to make it so that if the output is elasticsearch or timesketch, psort.py doesn't bother trying to order the output?

What would the performance benefit be?

**Comment by joachimmetz** [comment]
@davidrudduck there is already an issue open for this https://github.com/log2timeline/plaso/issues/2501. Closing this as a duplicate

**Comment by davidrudduck** [comment]
My bad! i did search but didn't see that!
