### ISSUE TITLE
Add SQLite parser plugin for Windows EventTranscriptDB.db database

### ISSUE THREAD

**Issue by MariasStory** [log2timeline/plaso#3803]
In some cases MS activates the EventTranscriptDB. It should be easy to parse this SQLite database:
https://github.com/rathbuna/EventTranscript.db-Research

**Comment by joachimmetz** [comment]
>  It should be easy to parse this SQLite database

@MariasStory are you planning to provide a PR including test data? should I assign this issue to you then?

**Comment by MariasStory** [comment]
At the moment, I cannot take the task. Thanks for offering.
I'll try to contribute.
--- additional information so far.
Kape file:
https://github.com/EricZimmerman/KapeFiles/blob/9982efa29950c1b427cf746b9f61eb77929f1e61/Targets/Windows/EventTranscriptDB.tkape
Parser map:
https://github.com/EricZimmerman/SQLECmd/blob/master/SQLMap/Maps/Windows_EventTranscriptDB.smap

**Comment by joachimmetz** [comment]
Blindly copying other peoples work does not help. We need reproducible test data.
This will have to wait until someone is able to provide this and work on it.

**Comment by joachimmetz** [comment]
@roshanmaskey who indicated wanting to take a stab at generating reproducible test data and using that to build a parser plugin
