### ISSUE TITLE
No prompt for volume shadow copies.

### ISSUE THREAD

**Issue by SpongeBobCodePants** [log2timeline/plaso#3811]
**Description of problem:**
I can no longer get log2timeline to prompt for which volume shadow copies (VSCs) I want to timeline. When log2timeline is run on a partition with VSCs and I don't specify any VSS options (i.e., --no_vss, --vss_only, --vss_stores), log2timeline no longer prompts for VSCs to be selected. Please note, the --unattended option is not used. The following tests were conducted.

- The command line (provided below) was run against two different E01 images. 
- The E01 images were mounted with Arsenal Image Mounter, and this tool verifies that VSCs do exist on the OS partition.
-  `vssadmin list shadows` was also run to confirm the existence of the VSCs
-  log2timeline was run with the `--vss_stores all` option, and it timelines the VSCs as expected.
-  The same idea was tested with the `--partitions` option. When I omit this option, I am prompted to select a partition as expected.

**Command line and arguments:**
`log2timeline.py --status_view window  --file_filter filter_no_winsxs.yaml  --log-file ./myfolder/mylog.txt --storage-file ./myfolder/mystorage.plaso ./myfolder/mysourcedata.e01`

`log2timeline.py --status_view window --partitions all --file_filter filter_no_winsxs.yaml  --log-file ./myfolder/mylog.txt --storage-file ./myfolder/mystorage.plaso ./myfolder/mysourcedata.e01`

**Source data:**
I am unable to share the source data.

**Plaso version:**
20210606

**Operating system Plaso is running on:**
Ubuntu 20.04

**Installation method:**
From the official documentation for Ubuntu 20.04
https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html

**Debug output/tracebacks:**
Conversation with joachimmetz in Slack indicated a potential issue with:
https://github.com/log2timeline/plaso/blob/main/plaso/cli/storage_media_tool.py#L621

**Comment by joachimmetz** [comment]
This breaks previous behavior of log2timeline and looks like was introduced in https://github.com/log2timeline/plaso/pull/3644

**Comment by joachimmetz** [comment]
Changes merged, closing issue
