### ISSUE TITLE
Unable to process path specfication with error:  'utf8' codec can't decode byte 0xf0 in position 14: invalid continuation byte

### ISSUE THREAD

**Issue by seliyyah** [log2timeline/plaso#3830]
**Description of problem:**

I honestly hope I'm not overlooking something here.
Have a data set (directory path) on Ubuntu 18.04 LTS that I'm scanning. The tool runs and iterates through the data set but when it's complete it tells me there was no report analysis.

**Command line and arguments:**

sudo log2timeline.py /plaso/plaso/plaso_dump.dmp /path/folder/logs

**Source data:**

********************************* Error: 3854 **********************************
           Message : unable to process path specification with error: 'utf8'
                     codec can't decode byte 0xf0 in position 14: invalid
                     continuation byte
      Parser chain : 
Path specification : type: OS, location:
                     /path/folder/data/postgresql/data.11/base/16401/277399

**Plaso version:**

plaso - log2timeline version 1.5.1

**Operating system Plaso is running on:**

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Installation method:**

Installed Log2Timeline from source-code
git clone https://github.com/log2timeline/plaso

changed directories into 'plaso' 
Then installed the required Python Libraries with:
pip install -r requirements.txt

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Large data set.  Because of where it's located and how the traffic restrictions are configured I will need to toggle VPN to allow time to complete the scan.

For more information see the [troubleshooting
guide][https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html].

**Comment by joachimmetz** [comment]
> plaso - log2timeline version 1.5.1

this is a VERY OLD version and try the most recent release. I recall a similar issue has been address a while ago

**Comment by joachimmetz** [comment]
Also your version does not add up with the installation method? Do you have 2 versions installed?

**Comment by joachimmetz** [comment]
> The tool runs and iterates through the data set but when it's complete it tells me there was no

could you complete this sentence? there was no what?

**Comment by joachimmetz** [comment]
can you also tell me a bit more about the source data? what is  /path/folder/logs is that a network share? local file system, if so what type?

**Comment by seliyyah** [comment]
> > plaso - log2timeline version 1.5.1
> 
> this is a VERY OLD version, so try the most recent release. I recall a similar issue has been addressed a while ago

I will definitely see why I installed an old version and give that a try.  Thank you!

**Comment by seliyyah** [comment]
> Also your version does not add up with the installation method? Do you have 2 versions installed?

I don’t think I do but will double check.

**Comment by seliyyah** [comment]
> > The tool runs and iterates through the data set but when it's complete it tells me there was no
> 
> could you complete this sentence? there was no what?

my apologies, I fixed it after I submitted comment the first time but we missed each other.  This was the full comment below:

The tool runs and iterates through the data set but when it's complete it tells me there was no report analysis.

**Comment by seliyyah** [comment]
> can you also tell me a bit more about the source data? what is /path/folder/logs is that a network share? local file system, if so what type?

Path/folder/logs is basically a docker image on an Ubuntu OS in AWS.

**Comment by joachimmetz** [comment]
> The tool runs and iterates through the data set but when it's complete it tells me there was no report analysis.

which tool psort or psteal? an analysis report is the output of a analysis module, if don't specify one there should be no analysis report.

> Path/folder/logs is basically a docker image on an Ubuntu OS in AWS.

do you know which file system encoding?

**Comment by joachimmetz** [comment]
@seliyyah could you provide us with the additional information, without it we're not able to address the issue

**Comment by seliyyah** [comment]
> Also your version does not add up with the installation method? Do you have 2 versions installed?

Hi @joachimmetz I apologize for the delay (2 kids in diapers).  So I was looking at the documentation but I don't see anything recommended for clean uninstall/removal for Ubuntu.  I'd also like to try re-installing with the recommended method as well and realize my current install may be the reason for all of the issues.  Can you please provide me any recommended uninstall/reinstall documentation (if it exists)?  I only have the environment to analyze for another 2 weeks.

Thanks again for your assistance.

**Comment by joachimmetz** [comment]
See https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html

Try: `sudo apt-get remove plaso`

**Comment by seliyyah** [comment]
> See https://plaso.readthedocs.io/en/latest/sources/user/Ubuntu-Packaged-Release.html
> 
> > I don't see anything recommended for clean uninstall/removal for Ubuntu.
> 
> Try: `sudo apt-get remove plaso`

Uhh.  Yep, I did not see this.  I was using a trusted blog but it looks like it was older as well so it all makes sense now.  Normally I would have tried the sudo 'remove' method but wanted to verify first because although it's trivial I didn't see it spelled out in the docs but i could have missed that as well.  

I really appreciate your diligence and consistency with helping me get this resolved so great work!

I'm going to close this issue under the premise that I goofed the install and re run the tool.  If any other issues pop up i'll open up a new issue (after correctly installing and providing thorough details).

Thanks again!

**Comment by joachimmetz** [comment]
> I was using a trusted blog but it looks like it was older as well so it all makes sense now. 

Unfortunately unofficial sources about Plaso go out of date pretty quickly since their authors are not involved in the project.

**Comment by seliyyah** [comment]
Wanted to circle back in case anyone runs into this issue.  @joachimmetz was correct, my version and installation method were incorrect.  As indicated above I was using Ubuntu 18.04 LTS but after removing and reinstalling the issue is gone for good.  Thanks again!
