### ISSUE TITLE
SkyDrive log parsers merge

### ISSUE THREAD

**Issue by dfirfpi** [log2timeline/plaso#388]
The two SkyDrive log parsers (skydrivelog_old and skydrivelog) can be merged together.
- [x] ~~[merge skydrivelog and skydrivelog_old into single files](https://codereview.appspot.com/273060043/)~~
- [x] ~~Change SkyDriveLog1TextPlugin  (skydrivelog_old) must be refactored to use PyparsingMultiLineTextParser.~~
- [x] ~~Fix issue https://github.com/log2timeline/plaso/issues/504~~
- [x] ~~Merge PyParsing definitions from the two parsers to avoid duplicates.~~
  - ~~Change VerifyStructure method to handle both formats (current and old one)~~
  - formats are significantly different, so this is a non-issue
- [x] ~~Look at merging the event object (including formatters)~~
  - https://github.com/log2timeline/plaso/pull/4439

**Comment by joachimmetz** [comment]
Assigned this to @dfirfpi but as discussed let's work on this collaboratively. I've started step 1 in https://codereview.appspot.com/273060043/
