### ISSUE TITLE
Dropbox sync_history.db parser

### ISSUE THREAD

**Issue by sydp** [log2timeline/plaso#3964]
The Dropbox desktop application stores recently synced (added/deleted) files in a sqlite3 database.

Schema
```
CREATE TABLE sync_history (event_type TEXT NOT NULL,file_event_type TEXT,direction TEXT,file_id TEXT,local_path TEXT,timestamp INTEGER NOT NULL, other_user INTEGER)
```

Database location:
- Linux: $HOME/.dropbox/instance1/sync_history.db
- Windows 10: $HOME/AppData/Local/Dropbox/instance1/sync_history.db

**Comment by joachimmetz** [comment]
@sydp want me to assign this to you?

**Comment by jleaniz** [comment]
There is also a config.dbx sqlite database (encrypted) that contains interesting information such as the user's email address associated with dropbox. Might be interesting to add this as well
