### ISSUE TITLE
incorrect paths in filter_windows.txt

### ISSUE THREAD

**Issue by eoyslebo** [log2timeline/plaso#397]
Running image_export against a Windows 7 Home Premium image, I get the follow:

[INFO] [PreProcess] Set attribute: sysregistry to /Windows/System32/config
[INFO] [PreProcess] Set attribute: systemroot to /Windows
[INFO] [PreProcess] Set attribute: windir to /Windows

filter_windows.txt tries to collect {systemroot}/winevt/Logs/.+[.]evtx

Changing this to {systemroot}/System32/winevt/Logs/.+[.]evtx resolves the issue.

Not sure if this is an error in the filter file or if systemroot is incorrectly set.

**Comment by joachimmetz** [comment]
Error in the filter file. {systemroot} should be equivalent to %SystemRoot%

https://en.wikipedia.org/wiki/Environment_variable
