### ISSUE TITLE
Tag names should be alphameric plus undescore and hyphen only

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#400]
The current list of tag names is Human readable. While this is nice for some outputs it makes it hard to use them programmatically from e.g. Timesketch. This is because of Elasticsearch treating whitespace items in an array as separate words and will index them separately which makes it hard to do exact filtering etc.

I suggest that tag names only has (alphameric _ -) and then let whatever UI deal with pretty printing them.

**Comment by Onager** [comment]
Plan for doing this:

[] Change tag file
[] Change tagging plugins (viper, virustotal etc.)
[] Add checks to Plaso to make sure that whitespace-containing tags cause an exception

**Comment by Onager** [comment]
I don't think we should support hyphens and underscores, as it makes things confusing. For the moment, I'm proposing we don't allow hyphens.

**Comment by joachimmetz** [comment]
@Onager let's also document these conventions on the wiki.

**Comment by berggren** [comment]
@onager I'm wondering why hyphens and underscores makes things confusing? Could you elaborate a bit more on that? I'm in favor of hyphens and underscores, maybe I'm missing something here?

**Comment by Onager** [comment]
@joachimmetz Definitely

@berggren I don't think it's clear when one would use a hypen instead of an underscore, or vice versa. I'm keen to avoid tags called both "file_download" and "file-printed". If you have a good use case for using both hyphens and underscores, I'm not violently opposed.

**Comment by joachimmetz** [comment]
Reopening, because not all steps are completed.

**Comment by Onager** [comment]
Added note about tag naming to style guide. Closing.
