### ISSUE TITLE
VSS support on Win2k3 raising exception

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#401]
VSS support on Win2k3 raising exception
```
2015-11-02 10:38:38,044 [WARNING] (MainProcess) PID:24552 <log2timeline>
Unable to scan source with error: Unable to open file system with error:
pyvshadow_volume_open_file_object: unable to open volume.
libvshadow_store_block_read: invalid store block list header identifier.
libvshadow_store_descriptor_read_store_header: unable to read store block at offset: 0.
libvshadow_volume_open_read: unable to read store: 0 header.
libvshadow_volume_open_file_io_handle: unable to read from file IO handle.
```

* [x] ~~Improve format support: https://github.com/libyal/libvshadow/issues/3~~
* [x] update libvshadow releases
  * ~~gift ppa~~
  * ~~macosx~~
  * ~~win32~~
  * ~~win64~~
* [x] ~~[change dfvfs to ignore stores without in-volume data](https://codereview.appspot.com/281310043/)~~
* [x] update dfvfs releases
  * ~~gift ppa~~
  * ~~macosx~~
  * ~~win32~~
  * ~~win64~~

**Comment by cshanahan** [comment]
As requested here (https://groups.google.com/forum/#!topic/log2timeline-discuss/54aEXD09CN0), I compiled both libvmdk and libvshadow from source (Git) with verbose and debug options enabled.
  - vmdkmount 20150712
  - vshadowinfo 20150905

I mounted the VMDK without error and ran vshadowinfo with -v option. No VSS found.
```
root@DFIR-VM:~# file /mnt/vmdk/vmdk1 
/mnt/vmdk/vmdk1: x86 boot sector
```
```
root@DFIR-VM:~# vshadowinfo -v /mnt/vmdk/vmdk1 
vshadowinfo 20150905

No Volume Shadow Snapshots found.
```

Let me know if you need any other info. I'd be glad to help.

/Chris

**Comment by joachimmetz** [comment]
> I mounted the VMDK without error and ran vshadowinfo with -v option. No VSS found.

Thx

> vshadowinfo -v /mnt/vmdk/vmdk1 

I would expect a large amount of debug output to stderr here. However I think I have an idea what is going wrong. Sigscan detects a VSS that cannot be opened since it does not have stores. I'll look into handling this in dfvfs.

**Comment by joachimmetz** [comment]
@cshanahan you forgot to add the offset here
```
vshadowinfo -v /mnt/vmdk/vmdk1 
```

vshadowinfo should show you the number of stores is 0
