### ISSUE TITLE
Replace elastic_ts by opensearch_ts

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4012]
Timesketch changed back-ends from Elasticsearch to OpenSearch, make necessary changes to Plaso

* [x] ~~add opensearch_ts output module - https://github.com/log2timeline/plaso/pull/4011~~
* [x] ~~remove elastic_ts output module - https://github.com/log2timeline/plaso/pull/4098~~
* [x] remove elastic output module - https://github.com/log2timeline/plaso/pull/4099

**Comment by WoBuGs** [comment]
Is there a reason why the elastic module was removed all together?

I think there can be use cases when an investigator's toolset include ELK and not Timesketch. For instance, the FOR508  (2021 edition) course have an hands-on lab with Plaso + ELK.

**Comment by joachimmetz** [comment]
> For instance, the FOR508 (2021 edition) course have an hands-on lab with Plaso + ELK.

Yes because Elasticsearch is no longer Freely usable, as in FOSS. See: https://opensource.org/sspl-not-open-source and https://en.wikipedia.org/wiki/Free_and_open-source_software

Regarding FOR508 (1) the course material is not transparent/open (2) we asked SANS representatives multiple times over 5+ years to provide input on features they are using, without any reaction.

**Comment by WoBuGs** [comment]
Ok, that's clear, thank you for the quick reply! (I prefer TS anyway :D)
