### ISSUE TITLE
Add support for Windows Defender scan DetectionHistory files

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#4022]
Parse Windows Defender scan DetectionHistory files

Example file https://github.com/jklepsercyber/defender-detectionhistory-parser/blob/main/8CC4BE3D-8D3F-4952-9953-F24EB6638A37

**Comment by joachimmetz** [comment]
Would strongly recommend getting some more test data first

**Comment by jklepsercyber** [comment]
Any way I can help with this? I have some more test data I can provide, or you can feel free to implement my parser in your solution.

**Comment by joachimmetz** [comment]
@jklepsercyber great are these publicly available? Are these and reproducible (e.g. documented or can be generated) e.g. which versions of Defender have been used ? An example of what I'm referring to https://github.com/dfirlabs/chrome-specimens

**Comment by joachimmetz** [comment]
Took a quick look at the format, the current research on the format looks very early. Files in the MputHistory start with the same 5 bytes. The UTF-16 string "Magic.Version:1.2" at offset 0x30 might be a more reliable "signature". 

The format looks like a simple value type container format. 

> or you can feel free to implement my parser in your solution.

@jklepsercyber it does not look like your current code can be used as a Python module, nor is the license compatible with Plaso. Also see: https://github.com/log2timeline/l2tdocs/blob/main/process/Dependencies.md

**Comment by joachimmetz** [comment]
If someone is interest, the current research could benefit from a more diverse set of test files.

**Comment by Fryyyyy** [comment]
I have written a dtFabric parser for this which works on both files I pulled from my own Windows 10 computer as well as the same file provided by the original reporter.
I still need to spin up a few different version of Windows and produce Defender hits to make sure the coverage is good.

**Comment by joachimmetz** [comment]
> I still need to spin up a few different version of Windows and produce Defender hits to make sure the coverage is good.

This will likely be dependent on different versions of Defender. Let's make sure we have a good broad coverage of versions and different types of detections. There are a bunch of files by Microsoft to test Defender, similar to Eicar.
