### ISSUE TITLE
Parser for iOS Mobile Installation Logs

### ISSUE THREAD

**Issue by rick-slin** [log2timeline/plaso#4048]
Create a parser to parser iOS mobile installation logs. They are found at

```
/private/var/installd/Library/Logs/MobileInstalation/.log
```

**Comment by rick-slin** [comment]
I'd like to work on this issue.

**Comment by joachimmetz** [comment]
@rick-slin excellent,  don't hesitate to reach out if you have questions about setting up a dev environment.

**Comment by rick-slin** [comment]
Thanks @joachimmetz. I'm good with setup up a dev environment but I'm sure I'll have questions.
