### ISSUE TITLE
Add dockerfile for building plaso from scratch

### ISSUE THREAD

**Issue by rgayon** [log2timeline/plaso#405]
I'll provide a docker file to build plaso and (non-packaged) dependencies from source

**Comment by bf** [comment]
@rgayon any news on this?

**Comment by joachimmetz** [comment]
CL pending https://codereview.appspot.com/272350043/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/f91934ff3a33b04c23f6a5bcbdb2c3f777449ca9

**Comment by bf** [comment]
That's great - thank you @joachimmetz
