### ISSUE TITLE
Parser for powerlogs from iOS to obtain application usage

### ISSUE THREAD

**Issue by rick-slin** [log2timeline/plaso#4064]
Create a parser for the CurrentPowerlog.PLSQL file which contains application usage data. It can be obtained from an iOS sysdiagnose dump at 

`<sysdiagnose_DATE_OS_DEVICE_BUILD>/logs/powerlogs/powerlog_YYYY-MM-DD_XXXXXXXX.PLSQL`

or from a physical acquisition at:
`/private/var/mobile/Library/BatteryLife/CurrentPowerlog.PLSQL`
`Archives/powerlog_YYYY-MM-DD_XXXXXXXX.PLQSQL.gz`

Based on the research by Sarah Edwards (https://papers.put.as/papers/ios/2016/iOS_of_Sauron_04162016.pdf)

**Comment by rick-slin** [comment]
Please assign this issue to me. Thank you.

**Comment by joachimmetz** [comment]
@rick-slin thx, issue has been assigned to you
