### ISSUE TITLE
Why do I get "DeprecationWarning: Call to deprecated function: GetByteSize"?

### ISSUE THREAD

**Issue by shadywiki** [log2timeline/plaso#4065]
**Description of problem:**

When I run log2timeline within Ubuntu WSL I recieve the following errors.

/usr/local/lib/python3.8/dist-packages/dfvfs/lib/cpio.py:62: DeprecationWarning: Call to deprecated function: GetByteSize.
  _CPIO_BINARY_BIG_ENDIAN_FILE_ENTRY.GetByteSize())
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/cpio.py:68: DeprecationWarning: Call to deprecated function: GetByteSize.
  _CPIO_BINARY_LITTLE_ENDIAN_FILE_ENTRY.GetByteSize())
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/cpio.py:74: DeprecationWarning: Call to deprecated function: GetByteSize.
  _CPIO_PORTABLE_ASCII_FILE_ENTRY.GetByteSize())
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/cpio.py:79: DeprecationWarning: Call to deprecated function: GetByteSize.
  _CPIO_NEW_ASCII_FILE_ENTRY_SIZE = _CPIO_NEW_ASCII_FILE_ENTRY.GetByteSize()
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/gzipfile.py:112: DeprecationWarning: Call to deprecated function: GetByteSize.
  _MEMBER_HEADER_SIZE = _MEMBER_HEADER.GetByteSize()
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/gzipfile.py:117: DeprecationWarning: Call to deprecated function: GetByteSize.
  _MEMBER_FOOTER_SIZE = _MEMBER_FOOTER.GetByteSize()
/usr/local/lib/python3.8/dist-packages/dfvfs/lib/gzipfile.py:121: DeprecationWarning: Call to deprecated function: GetByteSize.
  _UINT16LE_SIZE = _UINT16LE.GetByteSize()

**Command line and arguments:**

log2timeline.py --storage-file /mnt/4tb/plaso.dmp /mnt/4TB/MGMT2016/evidencefile.vmdk

**Plaso version:**

plaso - log2timeline version 20220129

**Operating system Plaso is running on:**

Ubuntu 20.04

**Installation method:**

Install using pip install plaso

**Comment by joachimmetz** [comment]
This is because you're using an unsupported installation method and are running experimental version in the process

**Comment by shadywiki** [comment]
Understood, thanks for linking me to the documentation.

Kind Regards

**Comment by joachimmetz** [comment]
> When I run log2timeline within Ubuntu WSL I recieve the following errors.

I would also recommend reading up on what deprecation is https://en.wikipedia.org/wiki/Deprecation. This is **NOT** an error but a warning that the code calls a function/method that is no longer favored to use.
