### ISSUE TITLE
docs CI tests failing

### ISSUE THREAD

**Issue by jleaniz** [log2timeline/plaso#4071]
**Description of problem:**

```tox -edocs``` fails with errors. This is causing GitHub tests to fail.

See: https://github.com/log2timeline/plaso/runs/5977142890?check_suite_focus=true

```
/plaso/plaso/engine/engine.py:docstring of plaso.engine.engine.BaseEngine.GetSourceFileSystem:15: ERROR: Unexpected indentation.
/plaso/plaso/formatters/yaml_formatters_file.py:docstring of plaso.formatters.yaml_formatters_file.YAMLFormattersFile:15: ERROR: Unexpected indentation.
/plaso/plaso/lib/dtfabric_helper.py:docstring of plaso.lib.dtfabric_helper.DtFabricHelper:32: ERROR: Unexpected indentation.
/plaso/plaso/parsers/docker.py:docstring of plaso.parsers.docker.DockerJSONParser:5: ERROR: Unexpected indentation.
/plaso/plaso/parsers/dpkg.py:docstring of plaso.parsers.dpkg:13: ERROR: Unexpected indentation.
/plaso/plaso/parsers/dpkg.py:docstring of plaso.parsers.dpkg:20: ERROR: Unexpected indentation.
/plaso/plaso/parsers/presets.py:docstring of plaso.parsers.presets.ParserPresetsManager.GetPresetsInformation:9: ERROR: Unexpected indentation.
/plaso/plaso/parsers/sqlite_plugins/ls_quarantine.py:docstring of plaso.parsers.sqlite_plugins.ls_quarantine.LsQuarantinePlugin:5: ERROR: Unexpected indentation.
/plaso/plaso/parsers/sqlite_plugins/mac_notificationcenter.py:docstring of plaso.parsers.sqlite_plugins.mac_notificationcenter.MacNotificationCenterPlugin:8: ERROR: Unexpected indentation.
/plaso/plaso/parsers/sqlite_plugins/windows_timeline.py:docstring of plaso.parsers.sqlite_plugins.windows_timeline.WindowsTimelinePlugin.ParseGenericRow:5: ERROR: Unexpected indentation.
/plaso/plaso/parsers/winreg_plugins/ccleaner.py:docstring of plaso.parsers.winreg_plugins.ccleaner.CCleanerPlugin:16: ERROR: Unexpected indentation.
build finished with problems, 87 warnings.
```

**Command line and arguments:**

```tox -edocs```

**Plaso version:**

latest ```main``` branch

**Full output**
See https://github.com/log2timeline/plaso/runs/5977142890?check_suite_focus=true

**Comment by Digitalisx** [comment]
Hello @jleaniz, could you assign me this issue?

**Comment by joachimmetz** [comment]
@jleaniz this is the culprit

```
(sources/user/Getting-started: line   48) broken    https://docs.github.com/en/get-started/quickstart - 403 Client Error: Forbidden for url: https://docs.github.com/en/get-started/quickstart
```

**Comment by joachimmetz** [comment]
rerunning test since this could be a temporary thing

**Comment by joachimmetz** [comment]
@Digitalisx could you indicated why should this be assigned to you?

**Comment by Digitalisx** [comment]
@joachimmetz Ah I asked for an assignment to look at this issue with interest and solve it, it would be much better if it was resolved sooner than I was looking at it. 🙂

**Comment by joachimmetz** [comment]
Appreciate the help but you do not have the access to restart the tests that might make it harder.

I would opt to add your debug findings to the issue.

However this looks like to be just a temporary flakiness in the broken URL check.

**Comment by joachimmetz** [comment]
```
sources/user/Getting-started.md:48: [broken] https://docs.github.com/en/get-started/quickstart: 403 Client Error: Forbidden for url: https://docs.github.com/en/get-started/quickstart
sources/Troubleshooting.md:34: [broken] https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github: 403 Client Error: Forbidden for url: https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github
```

`https://docs.github.com/en/get-started/quickstart` and `https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github` resolve in a browser but github does not like the urlcheck client?

**Comment by Digitalisx** [comment]
> Appreciate the help but you do not have the access to restart the tests that might make it harder.
> 
> I would opt to add your debug findings to the issue.
> 
> However this looks like to be just a temporary flakiness in the broken URL check.

You're right, so I was running a test in a similar environment locally. It's easier for an authorized person to solve this problem, but I think this is also a good process for me.

From now on, debugging related to testing issues will be left in the thread of the issue without requesting an assignment.
I think the solution you found will be more helpful in solving the problem this time.
Let's hope it works out!

I will continue to be interested in various problems of plaso.
To ask you an additional question, is there any criteria for Assign for Issue?
Or should I work on the issue first and then connect the PR?

**Comment by joachimmetz** [comment]
> From now on, debugging related to testing issues will be left in the thread of the issue without requesting an assignment.

Don't hesitate to add debug findings to an issue thread. We can always assign it later. I'm wary of issues that need attention and sit on expectation to be resolved by assignee. For feature requests I'm happy to assign you, indicates that you're working on it.

> Or should I work on the issue first and then connect the PR?

Yeah feel free to propose a PR. Though I would recommend getting to the core of the issue first and discuss possible solution.

> To ask you an additional question, is there any criteria for Assign for Issue?

No this is not a formal process at this time.

**Comment by joachimmetz** [comment]
GitHub docs pages also appear flaky with local browser, adding an URL check ignore for now https://github.com/log2timeline/plaso/pull/4072
