### ISSUE TITLE
Syslog parser is confused by out-of-order messages that cross a month boundary

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#408]
https://github.com/log2timeline/plaso/blob/master/plaso/parsers/syslog.py#L69

If a log contains a series of events like so:
21 Feb 12:00:00 Some message
11 Jan 00:00:01 Other message
21 Feb 12:00:01 Another message
11 Jan 00:10:01 Yet Another message

The syslog parser will keep incrementing the dates of the events, eventually becoming non-sensical (I observed a log message that was allegedly from 2246). This sequence of out-of-order logs can be produced by the RepeatedMsgReduction option to rsyslog: http://bugzilla.adiscon.com/show_bug.cgi?id=527

**Comment by Onager** [comment]
I note that this parser is on the shortlist for being re-written soon.

**Comment by Onager** [comment]
Should be addressed with a new syslog parser in 1.5.

**Comment by joachimmetz** [comment]
@Onager was this addressed as part of the syslog refactor?

**Comment by Onager** [comment]
Addressed in syslog parser refactor.
