### ISSUE TITLE
image_export run third party tools

### ISSUE THREAD

**Issue by eoyslebo** [log2timeline/plaso#410]
In addition to log2timeline, I routinely run a collection of third party tools against a list of files containing artefacts.

As an example, I always run [RegRipper](https://github.com/keydet89/RegRipper2.8) against {systemroot}/System32/config/SAM to generate a quick summery of users. I use [autorip.pl](http://journeyintoir.blogspot.no/2013/05/unleashing-autorip.html) to partially automate the process, but I still need to determine that Windows is installed and therefore this tool should be run.

image_export with a filter file (or hopefully [ForensicArtifacts](https://github.com/ForensicArtifacts) in the near future) is my tool of choice for extracting artefacts. For my workflow, it would be useful if image_export could be extended so that it can be used to launch a curated list of third party tools, depending on what the preprocessor detects.

Feel free to close this issue if you feel that it falls outside the project's scope.

**Comment by joachimmetz** [comment]
FYI artefacts/artifact support is on the roadmap, see: https://github.com/log2timeline/plaso/issues/155

**Comment by joachimmetz** [comment]
So the challenge with running arbitrary third party tools is that they do not have a clear input and output. You'll also have to test these the various versions of third party tools with various versions of plaso.

I rather approach this from a different angle and determine what functionality you think is missing from plaso and we can consider adding it there. Where there are different approaches IMO:

* use analysis plugins; 
* re-use core functionality; e.g. we split of https://github.com/log2timeline/dfvfs and we are working on splitting off plaso's Registry parsing functionality into https://github.com/log2timeline/dfwinreg which can be easily used outside plaso e.g. as in https://github.com/libyal/winreg-kb.

**Comment by eoyslebo** [comment]
From what I understand, the ForensicArtifacts project defines paths, names and conditions for artifacts of interest. I am looking for a framework or a way to add rules along the lines of "given that you find this artifact, process the output using this tool with these options, and write the output to this file". For example:

* given a file that looks like a pst archive, try processing it with pffexport storing output to processed-output/$file-path/pffexport

* given that you find a file that looks like a Windows SAM registry file in c:\Windows\System32\config\SAM, try running regripper.pl -f SAM -r $file and pipe the output to processed-output/Windows\System32\config\SAM.regripperoutput.txt

* given a folder that looks like a Skype profile, try processing it with the command line version of NirSoft SkypeLogView, storing output to processed-output/$folderpath/NirSoftSkypeLogView

Plaso excels at presenting information chronically, but for including information about user accounts in a report I prefer the output format provided by RegRipper.

I'm not sure if this could be implemented as an analysis plugin or if it would be better to break off into a separate project. I just realized preprocessing information can be extracted from a plaso storage file, and in combination with image_export, the only thing missing is defining rules.

**Comment by joachimmetz** [comment]
> Plaso excels at presenting information chronically, but for including information about user accounts in a report I prefer the output format provided by RegRipper.

So this is largely an output formatting concern?

> the only thing missing is defining rules.

IMO what do describe you could already do with a small script or batch file:

* extract the files that match your criteria with image_export and a filter file describing your file type
* set up the exported files as needed for the tool
* run the tool you want
* repeat for other file types if needed

Once artifact support is in you could switch from the filter file to an artifact definition.

If we build similar functionality into plaso I would like to take this idea a step further. Why waste IO and processing to extract the dtaWhy dump all this information into a report using separate tools if you could do more useful automated processing with it?

**Comment by joachimmetz** [comment]
Closing issue full feature request out of scope of plaso.
