### ISSUE TITLE
Remove implicit assumptions of dictionary ordering

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#411]
Noticed in #340 several Plaso components rely on dictionaries being ordered. We need to identify these, then make sure we run tests with "python -R" to catch any new introduction of similar issues.

**Comment by joachimmetz** [comment]
These also occur inside dependencies changes to address some of these: https://codereview.appspot.com/285950043/

**Comment by joachimmetz** [comment]
@vonnopsled I'm reassigning this to myself, feel free to drop me line if you're actively working on this.

**Comment by joachimmetz** [comment]
`python -R ./run_tests.py` now passes, closing issue
