### ISSUE TITLE
Unable to parse AppConduit log files?

### ISSUE THREAD

**Issue by studiawan** [log2timeline/plaso#4118]
**Description of problem:**

I run log2timeline to an iOS forensic image that was downloaded from Digital Corpora (https://digitalcorpora.s3.amazonaws.com/corpora/mobile/ios_13_4_1/ios_13_4_1.zip). Several text log files are unreadable by plaso. Is it because the file extension not ended with extensioin .log? 
For example, in directory $HOME/iOS 13.3.1 Extraction/Extraction/Volumes/JOSH/NoTar-13-3-1/private/var/Mobile/Library/Logs/AppConduit, there are two log files, i.e.,  AppConduit.log.0 and AppConduit.log.1. However, plaso does not parse these log files.

Sample of log entries from AppConduit.log.0:

Sun Apr 12 10:54:23 2020 [139] <notice> (0x16b77b000) -[ACXCompanionSyncConnectionManager devicesAreNoLongerConnected:]: Device device:752E8F13-7BDE-4974-A011-A03492737221 (pairing ID 8DDD238A-F8E1-41D2-B0BC-D2756E655890) is no longer connected (isActive:Y)
Sun Apr 12 10:54:23 2020 [139] <notice> (0x16b5d7000) -[ACXInstallQueue reachabilityChangedForDevice:]_block_invoke: Suspending because device:752E8F13-7BDE-4974-A011-A03492737221 is no longer reachable
Sun Apr 12 10:54:23 2020 [139] <notice> (0x16b663000) -[ACXLocalAppStoreInstallQueue reachabilityChangedForDevice:]_block_invoke: Suspending because device:752E8F13-7BDE-4974-A011-A03492737221 is no longer reachable
... 

**Command line and arguments:**

psteal.py --source 'iOS 13.3.1 Extraction' -o dynamic -w ios.csv

'iOS 13.3.1 Extraction' is a directory from iOS image zip file extraction results.

**Source data:**

iOS forensic image was downloaded from https://digitalcorpora.s3.amazonaws.com/corpora/mobile/ios_13_4_1/ios_13_4_1.zip

**Plaso version:**

20211229

**Operating system Plaso is running on:**

* macOS Monterey version 12.4 (Apple M1)
* Python 3.8
* Anaconda virtual environment

**Installation method:**

* installed from https://github.com/log2timeline/plaso/releases/tag/20211229
* installation steps: https://plaso.readthedocs.io/en/latest/sources/user/MacOS-Source-Release.html

**Debug output/tracebacks:**

-

**Comment by joachimmetz** [comment]
> However, plaso does not parse these log files.

where does is say plaso supports iOS AppConduit log files?
