### ISSUE TITLE
How to run a test for a specific plugin

### ISSUE THREAD

**Issue by studiawan** [log2timeline/plaso#4134]
Hi, how to run a test for a specific plugin? I have written a new sqlite parser plugin and I do not know how to run a test for the newly created plugin.
Previously, I just re-build plaso and nothing happens when I run plaso against the intended sqlite file.

Thanks.

**Comment by studiawan** [comment]
I just found out how to do that. In plaso root directory, run `python -m unittest tests/parsers/sqlite_plugins/name_of_plugin.py` where `name_of_plugin.py` is the specific plugin we want to test.

**Comment by joachimmetz** [comment]
`PYTHONPATH=. python tests/parsers/sqlite_plugins/name_of_plugin.py`
