### ISSUE TITLE
cups_ipp parser produces unserializable strings

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#414]
Bug privately reported. 

The cups_ipp parser produces events with raw string values. These occasionally contain invalid unicode values, eg.

 'date-time-at-completed': ['\x07\xdf....

The parser uses construct.PascalString() and puts the output directly into the events. Strings produced by PascalString() are raw, not unicode.

**Comment by joachimmetz** [comment]
```
[WARNING] Unicode error in event object [fbe975f3be41468dab48e82cf7c9e563] which was generated by parser chain: asl_log. Error was: 'ascii' codec can't decode byte 0xe2 in position 114: ordinal not in range(128). The event will not be included in the timeline.
```

**Comment by Onager** [comment]
Fixed by https://codereview.appspot.com/284330043/
