### ISSUE TITLE
OpenSearch output module: add CLI option to pass predefined output field

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4152]
use case: when exporting the contents of a Plaso storage file, add a custom (user defined) field to OpenSearch output.

Idea add custom fields option e.g. `--custom_fields="hostname:MYHOST"`

**Comment by joachimmetz** [comment]
Note to self, this might be a good/more elegant alternative to the current log2timeline.py `--text` option (text prepend)

**Comment by DfirJos** [comment]
Yes, this would be perfect! I'm also looking for ways to include the hostname.  I have a not-so-elegant solution which is uploading the file from a Path which includes the hostname - this way I can see the hostname in Opensearch. Let me know if you found a more elegant solution. In the meantime I will track this enhancement.
