### ISSUE TITLE
Add plist parser for iOS CarPlayApp.plist file

### ISSUE THREAD

**Issue by studiawan** [log2timeline/plaso#4155]
I propose to add a plist parser for iOS CarPlayApp.plist. I will make a pull request for this parser.

**Comment by joachimmetz** [comment]
@studiawan excellent, I've assigned the issue to you. Let us know if you're running into challenges writing the parser plugin

**Comment by studiawan** [comment]
Hi @joachimmetz please review my pull request. Thanks.

**Comment by joachimmetz** [comment]
I'll let the tests run first and check with @Onager which one of us will do the review.
