### ISSUE TITLE
Mediator warns about being unable to determine creation year

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#417]
This is while running log2timeline against a directory on the file system:

```
2015-11-27 16:56:21,150 [ERROR] (Worker_07 ) PID:10618 <mediator> Unable to determine creation year from file stat information.
```
Generating code is here: https://github.com/log2timeline/plaso/blob/master/plaso/parsers/mediator.py#L165

To be determined:
*   Does the code that calculates the year need to be tweaked
*   Is ERROR the right level for this condition

**Comment by joachimmetz** [comment]
Changed label, the description reads as this is an enhancement not a bug.

**Comment by Onager** [comment]
This is actually a bug - there's a 'not' on line 160 which doesn't belong.

**Comment by joachimmetz** [comment]
Ack, pending fix looks good to go in
