### ISSUE TITLE
additional_fields option shown for non-supported output modules

### ISSUE THREAD

**Issue by aarontp** [log2timeline/plaso#4177]
**Description of problem:**

It appears when specifying both `--output_format json` and  `--additional_fields something` to `psort.py` it causes an error.  It's possible that `--additional_fields` is not needed or used when the output is JSON, but it still shouldn't throw an error.

**Command line and arguments:**

Here's the command that fails:
```
# psort.py --additional_fields yara_match --output_format json -w test.json 20220729T202757-test.plaso 
usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST] [--process_memory_limit SIZE] [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE] [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u] [--status_view TYPE] [--slice DATE_TIME] [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a] [--language LANGUAGE_TAG] [--dynamic_time] [--output_time_zone TIME_ZONE] [-o FORMAT] [-w OUTPUT_FILE]
                [--profilers PROFILERS_LIST] [--profiling_directory DIRECTORY] [--profiling_sample_rate SAMPLE_RATE]
                [PATH] [FILTER]
psort.py: error: unrecognized arguments: --additional_fields 20220729T202757-test.plaso
```

But using one or the other flag works fine (e.g. these commands both work):
```
psort.py  --output_format json -w test.json 20220729T202757-test.plaso
psort.py  --additional_fields yara_match  -w test.csv 20220729T202757-test.plaso
```

**Source data:**

n/a

**Plaso version:**
```
plaso - log2timeline version 20220428
```

**Operating system Plaso is running on:**
Debian

**Installation method:**

* installed from [GiFT PPA][https://launchpad.net/~gift] stable track

**Debug output/tracebacks:**

Adding `-d` doesn't change the output from above.

**Comment by joachimmetz** [comment]
`--additional_fields` is only supported by dynamic, opensearch and xslx
