### ISSUE TITLE
OSError: Session identifier mismatch for session configuration: 1

### ISSUE THREAD

**Issue by tschla1** [log2timeline/plaso#4178]
**Description of problem:**

Please describe the problem in as much detail as possible.
What does the tool not do that it should? What would you like it to do?

**Command line and arguments:**

Please provide the command with arguments you ran when you experienced
the problem.

**Source data:**

Please provide the source data you used when you experienced the problem.
For publicly available data please provide a URL or path of the source data.

**Plaso version:**

For example 20171231

**Operating system Plaso is running on:**

Not the operating system of the image/files you're trying to analyze.

**Installation method:**

For example:
* installed from [GiFT PPA][https://launchpad.net/~gift] stable track
* installed from [GiFT COPR][https://copr.fedorainfracloud.org/coprs/g/gift/] stable track
* installed from [l2tbinaries][https://github.com/log2timeline/l2tbinaries] main branch
* built using [l2devtools][https://github.com/log2timeline/l2tdevtools]
* other, namely ...

If multiple methods were used please indicate.

**Debug output/tracebacks:**

Please run the tool with "-d" to generate debug output, and include anything relevant.
Also see: [Producing debug logs][https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html#producing-debug-logs]

For more information see the [troubleshooting guide][https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html]

**Comment by tschla1** [comment]
Can anyone advise me on what may be causing this "Session identifier mismatch" error?  


plaso@C9100E022B6673E:~$ psort.py -o l2tcsv -w /mnt/o/WSPISIM/Plaso/WSPISIM_timeline-filtered_1.csv /mnt/o/WSPISIM/Plaso/wspisim_Vol_C_1.plaso
2022-08-01 11:54:27,311 [INFO] (MainProcess) PID:106 <data_location> Determined data location: /usr/share/plaso
WARNING: the output format: l2tcsv has significant limitations such as second-
only date and time values and/or a limited predefined set of output fields. It
is strongly recommend to use an alternative output format like: dynamic.

Waiting for 15 second to give you time to cancel.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/plaso/storage/reader.py", line 161, in GetSessions
    session.CopyAttributesFromSessionConfiguration(session_configuration)
  File "/usr/lib/python3/dist-packages/plaso/containers/sessions.py", line 114, in CopyAttributesFromSessionConfiguration
    raise ValueError('Session identifier mismatch.')
ValueError: Session identifier mismatch.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/psort.py", line 101, in <module>
    if not Main():
  File "/usr/bin/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "/usr/lib/python3/dist-packages/plaso/cli/psort_tool.py", line 459, in ProcessStorage
    for session_index, session in enumerate(storage_reader.GetSessions()):
  File "/usr/lib/python3/dist-packages/plaso/storage/reader.py", line 163, in GetSessions
    raise IOError((
OSError: Session identifier mismatch for session configuration: 1

**Comment by joachimmetz** [comment]
@tschla1 can you provide the information in the issue template? Based on you current description looks like your storage file might be corrupt.

**Comment by joachimmetz** [comment]
Closing issue, insufficient information from reporter
