### ISSUE TITLE
Behavior of "use_tsk" in artifact collector flow for Windows Regitry artifacts

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#419]
Can someone confirm or deny that when running an artifact collection for Windows Registry artifacts and ticking on "use_tsk" that the collection will have the client use the TSK VFS handler and not the Registry one?

**Comment by Onager** [comment]
I think you meant to file this on GRR....

**Comment by joachimmetz** [comment]
Thx, yes wrong tab :-~
