### ISSUE TITLE
Unable to find mapped path in Docker container

### ISSUE THREAD

**Issue by splunk-user1** [log2timeline/plaso#4197]
**Description of problem:**

Unable to find evidence present in the folder on the host (mapped folder)

**Command line and arguments:**
```
docker run -v ~/data:/data log2timeline/plaso log2timeline --storage-file evidences.plaso data/evidences -d
```
**Source data:**

https://docs.google.com/document/d/1XM4Gfdojt8fCn_9B8JKk9bcUTXZc0_hzWRUH4mEr7dw/

**Plaso version:**
```
20220724
```

**Operating system Plaso is running on:**
```
20.04.4 LTS (Focal Fossa)
```
**Installation method:**
```
docker pull log2timeline/plaso
```
**Debug output/tracebacks:**

```
2022-08-17 13:49:56,030 [INFO] (MainProcess) PID:7 <data_location> Determined data location: /usr/share/plaso
2022-08-17 13:49:56,040 [INFO] (MainProcess) PID:7 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
Checking availability and versions of dependencies.
[OK]

No such device, file or directory: /home/plaso/data/evidences
```

**Comment by joachimmetz** [comment]
And does `~/data/evidences` exist on your host system?

**Comment by joachimmetz** [comment]
evidences.plaso is currently also written inside the container, likely not what you want. I strongly recommend reading up on how Docker works.

**Comment by splunk-user1** [comment]
Yes agree with you @joachimmetz Thank you for responding. 
 

> This does not look like a Plaso issue but how to use Docker issue.
> 
> Does `~/data/evidences` exist on your host system?
Yes it does.

> 
> This explains Docker volumes in much detail https://docs.docker.com/storage/volumes/

**Comment by joachimmetz** [comment]
> > Does ~/data/evidences exist on your host system?
> Yes it does.

selinux ?

**Comment by splunk-user1** [comment]
nope. It's Ubuntu 20.04.4 LTS (Focal Fossa) - HyperV guest running on Windows 10

**Comment by joachimmetz** [comment]
looks like you're pointing log2timeline at data/evidences (which is /home/plaso/data/evidences) not at the actual mapped volume /data/evidences. Try something like:

```
docker run -v ~/data:/data log2timeline/plaso log2timeline --storage-file /data/evidences.plaso /data/evidences -d
```

**Comment by splunk-user1** [comment]
Nm @joachimmetz. This document was a good pointer https://docs.docker.com/storage/volumes/ 

Fixed broken mapping :) Thank you again
