### ISSUE TITLE
add support to process ISO images as an "archive"

### ISSUE THREAD

**Issue by tomchop** [log2timeline/plaso#4239]
add support to process ISO disk images as an "archive"

Similar to https://github.com/log2timeline/plaso/issues/3686 for MacOS disk images (e.g. .dmg)

**Comment by joachimmetz** [comment]
Will require to add ISO9660 support to dfVFS first https://github.com/log2timeline/dfvfs/issues/689

Note that the TSK back-end has limited ISO9660 support but should be sufficient to start with.

**Comment by joachimmetz** [comment]
Needs a way to distinguish an ISO-9660 image from any other TSK supported image
