### ISSUE TITLE
Unable to connect to Elasticsearch

### ISSUE THREAD

**Issue by alex87fr** [log2timeline/plaso#4258]
Hello, 
how to use psort with elasticsearch ? please....im using -o opensearch  but : Unable to create OpenSearch index with error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7efc5e382020>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7efc5e382020>: Failed to establish a new connection: [Errno -2] Name or service not known)

Do you have a solution ? please

Regards,

**Comment by joachimmetz** [comment]
@alex87fr first of all if you report issues, can you follow the issue reporting template and provide us with the necessary information.

We no longer support Elasticsearch seeing the limited information you provided we cannot help you. Closing issue.
