### ISSUE TITLE
Add parser for System Resource Usage Monitor (SRUM) data

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#427]
* [x] ~~Get test file C:\Windows\System32\sru\SRUDB.dat~~
* [x] ~~Add dfdatetime OLE Automated Date support~~
  * ~~https://codereview.appspot.com/333470043~~
* [x] ~~Add parser, tests and test data~~
  * ~~https://codereview.appspot.com/340160043/~~
* [x] Collect and map Application identifiers to readable strings (+/-)

**Comment by Onager** [comment]
Adding to 1.5 release per planning meeting.
