### ISSUE TITLE
Collection filters and parsers option?

### ISSUE THREAD

**Issue by vikas891** [log2timeline/plaso#4322]
** General Query around Filter/Parsers **

I have read the documentation but it wasn't clear or there may be a lack in my understanding. Apologies in advance. 
In my understanding, a parser for e.g. winevt.py --> wouldn't the code know that if I give it an image or a drive letter where an image is mounted, to look for EVTXs in C:\Windows\system32\winevt\logs OR log2timeline actually "processes" each and every file, looks for "headers" to identify what kind of file is it, and then processes it accordingly?

Filters - We're ideally pointing log2timeline to look for "these files" to process. So, if my original point is correct(log2timeline practically tries to process everything) it means we're narrowing down on the set of files for it to process?

I remember raising this with EricZ last year and he was very helpful to clear some of the doubts around this, I'd love some inputs on this please. 

Thanks,
Vikas

**Comment by joachimmetz** [comment]
@vikas891 first of all you question is very convoluted but let me try to provide an answer 

> log2timeline actually "processes" each and every file, looks for "headers" to identify what kind of file is it, and then processes it accordingly?

yes a parser will identify a file based on its content. Not every file format has a "header" or unique signature for that matter

> wouldn't the code know that if I give it an image or a drive letter where an image is mounted, to look for EVTXs in C:\Windows\system32\winevt\logs

you can point log2timeline to mounted directory, not all mount points have drive letters. Can you explain what your use case is?

> Filters - We're ideally pointing log2timeline to look for "these files" to process. 

there are collection filters https://plaso.readthedocs.io/en/latest/sources/user/Collection-Filters.html that define what to collect and what not

> I remember raising this with EricZ last year and he was very helpful to clear some of the doubts around this

He's not in any ways associated or involved with this project and been seen mostly pushing his own work in the past instead of helping others.

**Comment by vikas891** [comment]
Thank you Joachim for the quick response. I'm fairly comfortable using Plaso for a variety of use cases such as pointing it to an E01, VHDX or a C: folder structure, it never gave me troubles!
I only wanted to understand the inner workings just enough for me to be able to guide others. 

For e.g. I point log2timeline to a triage image which follows the usual drive structure (C:\Windows\ .. and so on) 

I input only webhist as a parser. Now, would log2timeline assess each and every file in the image to identify if it contains web history or would it know where the SQLLite DBs are associated to Chrome/Firefox and ignore other files such as $MFT, EVTXs etc. 

Thank you once again.

**Comment by joachimmetz** [comment]
> For e.g. I point log2timeline to a triage image which follows the usual drive structure (C:\Windows\ .. and so on)

Inside an image (that is not mounted) there is no concept of drive letters, this something Windows add run-time.

> I input only webhist as a parser.

webhist is a (parser) preset, so not a single parser, see: https://github.com/log2timeline/plaso/blob/main/data/presets.yaml#L167

if you define that as the only set of parsers to apply, log2timeline.py will traverse the file system looking for data streams (file content) that are supported by these parsers. It might do other things depending on your configuration

**Comment by vikas891** [comment]
That clears it up! I noticed we can simply point log2timeline to a flat DIR containing a mix n match of artifacts, select presets/parsers and it'll do the magic! Ah, wow. Thank you once again, I really appreciate it.
