### ISSUE TITLE
pinfo.py: invalid JSON when using selective sections in output

### ISSUE THREAD

**Issue by stbe** [log2timeline/plaso#4324]
**Description of problem:**

When using `pinfo.py` with with limited section output and json output format, the resulting json is not well formed:
`{, "storage_counters": {"parsers": {"winevtx": 6, "total": 6}, "event_labels": {}}}`

**Command line and arguments:**

`docker run -v $(pwd):/data log2timeline/plaso:20220930 pinfo.py --sections events --output-format json /data/susp_explorer_exec.plaso`

**Source data:**

Source data is generated from https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Execution/susp_explorer_exec.evtx like so:

`docker run -v $(pwd):/data log2timeline/plaso:20220930 log2timeline.py --storage_file /data/susp_explorer_exec.plaso /data/susp_explorer_exec.evtx`

**Plaso version:**

20220930

**Operating system Plaso is running on:**

Current docker image: `log2timeline/plaso:20220930`

**Comment by joachimmetz** [comment]
looks like the session information is missing.

**Comment by joachimmetz** [comment]
@stbe your Plaso storage file is corrupt, it is missing session information.
