### ISSUE TITLE
"log2timeline.py --archive list" and "--archive all" fails to run. 

### ISSUE THREAD

**Issue by 82d28a** [log2timeline/plaso#4330]
**Description of problem:**

I would like to use log2timeline to use process all available archives supported. Documentations states using:
"log2timeline.py --archives list" to list available but i get following error.

Also when using --archives all it gives error to quick to capture. Debug doesn't show the python stack trace. 

**Command line and arguments:**
"log2timeline.py --archives list"

"log2timeline.py --archives all..."

**Source data:**
"log2timeline.py --archives list"
2022-10-24 02:40:55,174 [INFO] (MainProcess) PID:57904 <data_location> Determined data location: /usr/share/plaso
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 103, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 46, in Main
    tool.ListArchiveTypes()
  File "/usr/lib/python3/dist-packages/plaso/cli/extraction_tool.py", line 774, in ListArchiveTypes
    for name, description in sorted(self._SUPPORTED_ARCHIVE_TYPES):
ValueError: too many values to unpack (expected 2)

**Plaso version:**

20220930

**Operating system Plaso is running on:**

Ubuntu 22.04

**Installation method:**

* installed from [GiFT PPA][https://launchpad.net/~gift] stable track
AND tried same from docker hub "$ docker pull log2timeline/plaso"

If multiple methods were used please indicate.

**Debug output/tracebacks:**

**Comment by joachimmetz** [comment]
Has been addressed in https://github.com/log2timeline/plaso/commit/e71a7fbdb2ea648a0f7a96adb814aca1862d9cf3
