### ISSUE TITLE
_PrintUserWarning() written to stdout instead of stderr

### ISSUE THREAD

**Issue by nflexfo** [log2timeline/plaso#4370]
**Description of problem:**

User warnings from `_PrintUserWarning()` (`plaso/cli/tools.py`) are written to `sys.stdout` by default instead of `sys.stderr`.

When running an old version of plaso (more than 6 months), plaso prints a warning on `sys.stdout` from `CheckOutDated()`. Unfortunately, this also breaks the output of tools like `pinfo.py` with  `--output_format json` argument. Because of the warning, the output is not a valid json anymore.

**Plaso version:**

The current version `20220930` as well as previous ones (probably more than a year at least).

**Operating system Plaso is running on:**

Linux.

**Installation method:**

Source code.

**Comment by joachimmetz** [comment]
That is correct. This is an important user warning and should not be hidden from the user when stderr is redirected.

**Comment by joachimmetz** [comment]
We could consider changing pinfo to write the json output to a file instead.

**Comment by nflexfo** [comment]
We typically use plaso, as well as other tools, in air-gapped environment where we might not be able to upgrade plaso on a regular basis. So, this is just a time-bomb for us (which is currently worked around with the pull request).

In addition, we have some custom patches to improve performances during `psort.py` to use a `SELECT ... WHERE data_type=XXX` approach which imply modifying the storage file, EventData object, etc.. (we already discussed about it a year or two ago). We use `pinfo.py` during this phase to know what are the data types available before running `psort.py` multiple times (one per data type to benefit from the `additional_fields` argument). Since the JSON is corrupted because of the warning, it breaks the chain. Writing the json output to a file could be a workaround.

On the other hand, if people are willing to ignore `stderr`, I guess they won't really care about a warning print on stdout. In my opinion, errors and warnings are the purpose of stderr to keep a clean chaining with stdout.

P.S.: I will probably send more pull requests later on (e.g. injecting data types stats into the storage file), I'm sure other people might benefit from it.

**Comment by nflexfo** [comment]
I just checked `pinfo.py` options and there is already the `-w (--write)` options. Closing the issue, thanks for the quick response.
