### ISSUE TITLE
Add support for Safari Downloads.plist

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#4486]
* [x] generate test data
* [x] add plist plugin and tests - https://github.com/log2timeline/plaso/pull/4491
* [x] add artifact definition - https://github.com/ForensicArtifacts/artifacts/blob/main/data/webbrowser.yaml#L1176

**Comment by chb2mn** [comment]
[Downloads.zip](https://github.com/log2timeline/plaso/files/10230863/Downloads.zip)

Hey Joachim, here is a test example. lmk if you'd like something more diverse

**Comment by joachimmetz** [comment]
@chb2mn thanks will take a more detailed look tomorrow
