### ISSUE TITLE
Allocate name for Plaso 1.4 release

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#454]
* [x] Plaso 1.4 needs an appropriate name....

Assigning to @kiddinn as the expert in the field.

**Comment by joachimmetz** [comment]
https://simple.wikipedia.org/wiki/List_of_Norse_gods_and_goddesses

* Forseti - God of justice, peace and truth. Son of Baldr and Nanna.
* Freyja - Goddess of love, fertility, and battle. Consort: Óður.
* Freyr - God of fertility. Consort: Gerð.
* Frigg - Goddess of marriage and motherhood. Consort: Óðinn. Can also be pronounced "Frigga".
* Fulla - Frigg´s handmaid.

**Comment by kiddinn** [comment]
we've discussed this and I think Freyja is the chosen one... assigning back to Daniel

**Comment by Onager** [comment]
Yep, Freyja is the name - closing issue.
