### ISSUE TITLE
Plaso 1.4 rc1 - log2timeline fails to run on dependency check

### ISSUE THREAD

**Issue by CdtDelta** [log2timeline/plaso#455]
Windows 10 64-bit
Plaso 1.4 rc1

Attempting to run log2timeline produces the following output:

[INFO] Data files will be loaded from None by default.
Checking availability and versions of plaso dependencies.
[FAILURE]       missing: artifacts.
[OK]            bencode
[OK]            binplist version: 0.1.5
[OK]            construct version: 2.5.2
[OK]            dateutil version: 2.4.2
[OK]            dfvfs version: 20151216
[FAILURE]       missing: dpkt.
[OK]            google.protobuf
[FAILURE]       missing: IPython.
[OK]            pefile version: 1.2.10-139
[OK]            psutil version: 1.2.1
[OK]            pyparsing version: 2.0.6
[OK]            pytz
[FAILURE]       missing: requests.
[OK]            six version: 1.9.0
[OK]            xlsxwriter version: 0.7.7
[OK]            yaml version: 3.10
[OK]            zmq version: 15.1.0
[OK]            SleuthKit version: 4.2.0
[OK]            pytsk3 version: 20150406
[OK]            libbde (pybde) version: 20150204
[OK]            libesedb (pyesedb) version: 20151213
[OK]            libevt (pyevt) version: 20151206
[OK]            libevtx (pyevtx) version: 20151206
[OK]            libewf (pyewf) version: 20140608
[OK]            libfsntfs (pyfsntfs) version: 20151205
[OK]            libfwsi (pyfwsi) version: 20150701
[OK]            liblnk (pylnk) version: 20151205
[OK]            libmsiecf (pymsiecf) version: 20151205
[OK]            libolecf (pyolecf) version: 20151205
[OK]            libqcow (pyqcow) version: 20151219
[OK]            libregf (pyregf) version: 20151205
[OK]            libsigscan (pysigscan) version: 20151205
[OK]            libsmdev (pysmdev) version: 20151219
[OK]            libsmraw (pysmraw) version: 20151219
[OK]            libvhdi (pyvhdi) version: 20151205
[OK]            libvmdk (pyvmdk) version: 20150516
[OK]            libvshadow (pyvshadow) version: 20150106

**Comment by yani1shu** [comment]
same issue for me. Windows 10 x64.

**Comment by joachimmetz** [comment]
@CdtDelta and @yani1shu per RC1 release mail:

Make sure you include:

* The version of Plaso, and how you installed it
* The platform and version you’re running Plaso on
* The command you’re using to run Plaso

**Comment by CdtDelta** [comment]
Version of Plaso: plaso-1.4.0-rc1-win-amd64-vs2010
Platform: Windows 10 Pro 64-bit
Command I'm running:

log2timeline.exe /path/to/dump /path/to/.E01

I installed it by downloading the Windows zip binary from the Plaso binary site, unzipped the directory, copied the plaso directory to another directory on my C: volume, and then renamed it plaso-1.4.0-rc1 (as I already have a plaso directory in the same parent folder that has 1.3 in it).

**Comment by joachimmetz** [comment]
thanks, that would indicate these dependencies were not packaged by pysintaller.
having a look

**Comment by joachimmetz** [comment]
Confirmed this seems to be a packaging issue with both the win32 and win64 builds, trying a different version of PyInstaller to build them.

**Comment by joachimmetz** [comment]
Forcing them as hidden import did the trick for me I'll package an new RC that included https://codereview.appspot.com/278610043/

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/280530043/

**Comment by joachimmetz** [comment]
Fix for packing batch file: https://codereview.appspot.com/280530043/

**Comment by joachimmetz** [comment]
To new Windows RCs that work for me on a clean Win 10 machine:
https://googledrive.com/host/0B30H7z4S52FleW5vUHBnblJfcjg/1.4.0/RC2/

Can you give these a try.

**Comment by CdtDelta** [comment]
That worked for me, I have a test run going now.
