### ISSUE TITLE
gcp:log:entry message formatter does not generate "action" or "resource" values

### ISSUE THREAD

**Issue by jonathan-greig** [log2timeline/plaso#4550]
**Description of problem:**

The GCP logging parser doesn't provide the "action" and "resource" field required for psort to generate a legible message. 

At some point the GCP log parser was refactored and logic for extracting the "action" and "resource" from GCP log fields was removed. 

The [formatter for GCP logs](https://github.com/log2timeline/plaso/blob/main/data/formatters/generic.yaml#L341) is:
```
message:
- '{text_payload}'
- 'User {user}'
- 'performed {action}'
- 'on {resource}'
```

Which is leading to messages like `User fakeemailxyz@gmail.com` without an action or resource.

Messages should instead look like `User fakeemailxyz@gmail.com performed beta.compute.networks.insert on resource projects/fake-project/global/networks/test`

**Command line and arguments:**

```
$ wget https://raw.githubusercontent.com/log2timeline/plaso/main/test_data/gcp_logging.jsonl
$ docker run --rm -v /tmp/plaso:/tmp/plaso log2timeline/plaso:20221229 log2timeline.py --storage_file /tmp/plaso/gcp_logging.plaso --parsers jsonl /tmp/plaso/gcp_logging.jsonl
$ docker run --rm -v /tmp/plaso:/tmp/plaso log2timeline/plaso:20221229 psort.py -o json_line -w /tmp/plaso/gcp_logging_out.jsonl /tmp/plaso/gcp_logging.plaso
$ cat gcp_logging_out.jsonl |jq .message
"This is a text payload"
"User fakeemailxyz@gmail.com"
"User fakeemailxyz@gmail.com"
[...]
```

**Source data:**

[test_data/gcp_logging.jsonl](https://github.com/log2timeline/plaso/blob/main/test_data/gcp_logging.jsonl)

**Plaso version:**

20221229

**Operating system Plaso is running on:**

Running docker images.

**Installation method:**

* Docker run with image tagged 20221229

**Comment by joachimmetz** [comment]
Note to self make sure to extent test coverage.

**Comment by joachimmetz** [comment]
So the original parser seems to extract `action` from `serviceData` https://github.com/log2timeline/plaso/pull/3938/files#diff-f29cf60f1bd92c1908491fba36c350b62cc66f730e133117cf35e0209589df5cR190

but the test data does not appear to contain such a field, do you have an example for testing purposes?

**Comment by joachimmetz** [comment]
I see that there is some indirection ongoing in the original parser, updating the formatter is likely the easiest

**Comment by joachimmetz** [comment]
@jonathan-greig PTAL https://github.com/log2timeline/plaso/pull/4553 note that more work is needed to support `resource_label_instance_id`. Having test data with that value will help.

**Comment by joachimmetz** [comment]
immediate issue addressed removing from January milestone
