### ISSUE TITLE
Why data formatting is not working for me ?

### ISSUE THREAD

**Issue by antoine-virgos** [log2timeline/plaso#4552]
**Description of problem:**

I want to remove this message from default formatter:
```<WARNING DEFAULT FORMATTER> Attributes: message: <value>```

I used this Plaso docker image : ```log2timeline/plaso:20210606``` and Timesketch. Timesketch corresponds to the last available release on GitHub : **20210224**. I can't afford to update Timesketch.

So, I created a copy of Plaso image to add my parser and other files to format the data.

I edited ```generic.yaml``` file and I put it ```/usr/share/plaso/formatters``` in my copy of Plaso.

I added these lines in this file :

```
---
type: 'basic'
data_type: 'myparser:entry'
message: '{message}'
short_message: '{message}'
---
```

This should remove the message from the default formatter, no ?  Nothing happens, the default formatter is always used in Timesketch.

Also, I edited ```sources.config``` with the parser I created and I put it in ```/usr/share/plaso```.

My parser is working well so no need to give details about it. Except that, ```{message}``` is a variable defined in my parser as ```self.message = None```.

**Plaso version:**

20210606

**Timesketch version:**

20210224

I hope you can help me to solve this problem for this version of Plaso.

I am at your disposal if you have any questions.

Thanks in advance.

**Comment by joachimmetz** [comment]
Also 20210606 is more than a year old (older than 6 months) and no longer supported, strongly encourage using the latest version instead.

@berggren why is 20210224 the latest GitHub Timesketch release? I thought there were newer versions.

`message` is a special/reserved name use something different https://plaso.readthedocs.io/en/latest/sources/user/Output-and-formatting.html?highlight=output#dynamic-output-module-fields

Have you tried running with debug logging to indicate what might be going wrong? Also see https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html

**Comment by antoine-virgos** [comment]
> Also 20210606 is more than a year old (older than 6 months) and no longer supported, strongly encourage using the latest version instead.

I tried to use the latest version of Plaso: ```log2timeline/plaso:latest``` but unfortunately I get the error below on Timesketch ```worker.log``` :

```
ERROR: Format of storage file: /usr/share/timesketch/upload/4e6c688fca604c5785e50e68987daa3a not supported

usage: psort.py [-h] [--troubles] [-V] [--analysis PLUGIN_LIST]
                [--process_memory_limit SIZE]
                [--temporary_directory DIRECTORY] [--worker_memory_limit SIZE]
                [--worker_timeout MINUTES] [--logfile FILENAME] [-d] [-q] [-u]
                [--status_view TYPE] [--slice DATE_TIME]
                [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                [--language LANGUAGE] [--dynamic_time]
                [--output_time_zone TIME_ZONE] [-o FORMAT] [-w OUTPUT_FILE]
                [--index_name NAME] [--flush_interval INTERVAL]
                [--additional_fields ADDITIONAL_FIELDS]
                [--elastic_mappings PATH] [--elastic_user USERNAME]
                [--elastic_password PASSWORD] [--use_ssl]
               ...'
```

I think you don't support ```elastic_ts``` anymore and this is a problem with the version I have of Timesketch: it uses Elasticsearch and not OpenSearch. 
Here is the corresponding code -> https://github.com/google/timesketch/blob/8b38cc2d54779907e2a5bb43ecc9dbd85f9b5fbb/timesketch/lib/tasks.py

```
    cmd = [
        psort_path, '-o', 'elastic_ts', file_path, '--server', elastic_server,
        '--port', str(elastic_port), '--status_view', 'none',
        '--index_name', index_name,
    ]
```
That's why I use an older version of Plaso using ```elastic_ts``` with ```psort```.


> `message` is a special/reserved name use something different https://plaso.readthedocs.io/en/latest/sources/user/Output-and-formatting.html?highlight=output#dynamic-output-module-fields

I used ```message``` so that Timesketch would not put a field in addition to the **default** ```message``` field. This is in order to have the most readable events possible.

> Have you tried running with debug logging to indicate what might be going wrong? Also see https://plaso.readthedocs.io/en/latest/sources/Troubleshooting.html

I didn't see this section about debugging.

I did this ```log2timeline --troubles``` and here is the result:

```
Using Python version 3.8.5 (default, May 27 2021, 13:30:53)
[GCC 9.3.0]

Path: /usr/bin/log2timeline.py

plaso - log2timeline version 20210606

Checking availability and versions of dependencies.
[OK]            artifacts version: 20210404
[OK]            bencode
[OK]            certifi version: 2021.05.30
[OK]            chardet version: 3.0.4
[OK]            cryptography version: 3.4.7
[OK]            dateutil version: 2.8.1
[OK]            defusedxml version: 0.7.1
[OK]            dfdatetime version: 20210509
[OK]            dfvfs version: 20210606
[OK]            dfwinreg version: 20201006
[OK]            dtfabric version: 20200621
[OK]            elasticsearch version: 7.9.1
[OK]            future version: 0.18.2
[OK]            idna version: 3.2
[OK]            lz4 version: 3.1.3
[OK]            pefile version: 2021.5.24
[OK]            psutil version: 5.8.0
[OK]            pybde version: 20210605
[OK]            pycreg version: 20210502
[OK]            pyesedb version: 20210424
[OK]            pyevt version: 20210424
[OK]            pyevtx version: 20210525
[OK]            pyewf version: 20140812
[OK]            pyfsapfs version: 20210424
[OK]            pyfsext version: 20210522
[OK]            pyfshfs version: 20210602
[OK]            pyfsntfs version: 20210503
[OK]            pyfsxfs version: 20210403
[OK]            pyfvde version: 20210425
[OK]            pyfwnt version: 20210421
[OK]            pyfwsi version: 20210419
[OK]            pylnk version: 20210417
[OK]            pyluksde version: 20210419
[OK]            pymodi version: 20210515
[OK]            pymsiecf version: 20210420
[OK]            pyolecf version: 20210512
[OK]            pyparsing version: 2.4.7
[OK]            pyqcow version: 20210419
[OK]            pyregf version: 20210419
[OK]            pyscca version: 20210419
[OK]            pysigscan version: 20210419
[OK]            pysmdev version: 20210418
[OK]            pysmraw version: 20210418
[OK]            pytsk3 version: 20210419
[OK]            pytz
[OK]            pyvhdi version: 20210425
[OK]            pyvmdk version: 20210418
[OK]            pyvsgpt version: 20210207
[OK]            pyvshadow version: 20210425
[OK]            pyvslvm version: 20210524
[OK]            redis version: 3.5.3
[OK]            requests version: 2.24.0
[OK]            six version: 1.16.0
[OK]            urllib3 version: 1.25.9
[OK]            xlsxwriter version: 1.4.3
[OK]            yaml version: 5.3.1
[OK]            yara version: 4.1.0
[OK]            zmq version: 22.1.0

Also see: https://plaso.readthedocs.io/en/latest/sources/user/Troubleshooting.html
```

I tried to produce a debug log (```log2timeline --logfile=log2timeline_problem.log.gz --debug```) but I don't find ```log2timeline_problem.log.gz``` whether it's my machine or my Docker container.

It seems to generate it. ```myparser``` only detects one event and the debug generates three:

```
plaso - log2timeline version 20210606

Source path             : <file>
Source type             : single file
Processing time         : 00:00:00

Identifier      PID     Status          Memory          Sources         Events          File
Main            7       completed       90.4 MiB        1 (0)           4 (4)

Processing completed.
```

**Comment by joachimmetz** [comment]
> I think you don't support elastic_ts anymore and this is a problem with the version I have of Timesketch: it uses Elasticsearch and not OpenSearch.

have you tried if the OpenSearch Python bindings support your version of Elasticsearch?

> ERROR: Format of storage file: /usr/share/timesketch/upload/4e6c688fca604c5785e50e68987daa3a not supported

This indicates the Plaso version used to create the storage file it too new for the Plaso version that is used to ingest the data in to Timesketch.

> I used message so that Timesketch would not put a field in addition to the default message field. This is in order to have the most readable events possible.

In Plaso the formatter generates the `message` field, so if you put your data in attribute `bla` and have the formatter output `bla` then the TS output will have the `message` field containing the contents of `bla`.

> I tried to produce a debug log (log2timeline --logfile=log2timeline_problem.log.gz --debug) but I don't find log2timeline_problem.log.gz whether in my computer or my Docker container.

they are likely in the Docker container but you can point `--logfile=` to a different path that is stored outside your Docker container.

> It seems to generate it. myparser only detects one event and the debug generates three:

the other 3 are likely filestat related, but note that log2timeline.py generates the event data in the storage file. The output with formatter is generated by psort.py and seeing that is running as part of TS that is the location where the configuration needs to be updated.

**Comment by antoine-virgos** [comment]
> This indicates the Plaso version used to create the storage file it too new for the Plaso version that is used to ingest the data in to Timesketch.

So, I have to stay with the 20210606 Plaso version.

> In Plaso the formatter generates the `message` field, so if you put your data in attribute `bla` and have the formatter output `bla` then the TS output will have the `message` field containing the contents of `bla`.

I changed the field ```message``` by ```msg``` (in ```myparser.py```: ```self.message = None```  replaced by ```self.msg = None```) and I modified my ```generic.yaml``` file with these lines:

```
---
type: 'basic'
data_type: 'myparser:entry'
message: ' -> {msg}'
short_message: '-> {msg}'
---
```

As I have done previously, I removed last copy of Plaso image and rebuilt it.
I confirm that the added and edited files are there since I went to have a look in the copy of the Plaso image.

When I put the ```.plaso``` file in Timesketch, nothing has changed from the previous ```.plaso``` file ingested by Timesketch. Indeed, the ```message``` field is always present in this way: ```<WARNING DEFAULT FORMATTER> Attributes: message: <value>``` and the ```msg```  field does not appear anywhere. 

> they are likely in the Docker container but you can point `--logfile=` to a different path that is stored outside your Docker container.

Thanks to your advice I managed to generate the log file running this command : 
```docker run -v /home/exp:/home/exp log2timeline/plaso:20210606 log2timeline --parsers myparser --logfile=/home/exp/log2timeline_problem.log.gz --debug <input-file>```

```
2023-01-12 06:52:32,325 [WARNING] (MainProcess) PID:7 <tools> This version of plaso is more than 6 months old.
2023-01-12 06:52:32,410 [DEBUG] (MainProcess) PID:7 <extraction_tool> Parser filter expression set to: myparser
2023-01-12 06:52:32,410 [DEBUG] (MainProcess) PID:7 <log2timeline_tool> Starting extraction in single process mode.
2023-01-12 06:52:32,410 [DEBUG] (MainProcess) PID:7 <extractors> Active parsers: myparser
2023-01-12 06:52:32,411 [DEBUG] (MainProcess) PID:7 <hashing_analyzer> Got hasher names: sha256
2023-01-12 06:52:32,411 [DEBUG] (MainProcess) PID:7 <single_process> Processing started.
2023-01-12 06:52:32,414 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntry] processing file entry: OS:/home/exp/<input-file>
2023-01-12 06:52:32,414 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntryDataStream] processing data stream: "" of file entry: OS:/home/exp/<input-file>
2023-01-12 06:52:32,414 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeDataStream] analyzing file: OS:/home/exp/<input-file>
2023-01-12 06:52:32,415 [DEBUG] (MainProcess) PID:7 <hashing_analyzer> Processing results for hasher sha256
2023-01-12 06:52:32,415 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeFileObject] attribute sha256_hash:d2420a5b72bafd8e61faaf884352e8cc3d3851bc376b906a387ce3f73f134f33 calculated for file: OS:/home/exp/<input-file>
2023-01-12 06:52:32,415 [DEBUG] (MainProcess) PID:7 <worker> [AnalyzeDataStream] completed analyzing file: OS:/home/exp/<input-file>
2023-01-12 06:52:32,415 [DEBUG] (MainProcess) PID:7 <worker> [ExtractMetadataFromFileEntry] processing file entry: OS:/home/exp/<input-file>
2023-01-12 06:52:32,415 [DEBUG] (MainProcess) PID:7 <extractors> [ParseFileEntryWithParsers] parsing file: OS:/home/exp/<input-file> with parser: myparser
2023-01-12 06:52:32,433 [DEBUG] (MainProcess) PID:7 <worker> [ProcessFileEntry] done processing file entry: OS:/home/exp/<input-file>
2023-01-12 06:52:32,439 [DEBUG] (MainProcess) PID:7 <single_process> Processing completed.
```

But I don't see anything about the files ```generic.yaml```, required for formatting, and ```sources.config```

Finally, can you confirm that this is the right way to format your data and remove the default message ?

**Comment by joachimmetz** [comment]
> When I put the .plaso file in Timesketch, nothing has changed from the previous .plaso file ingested by Timesketch. Indeed, the message field is always present in this way: <WARNING DEFAULT FORMATTER> Attributes: message: <value> and the msg field does not appear anywhere.

> But I don't see anything about the files generic.yaml, required for formatting, and sources.config

per my previous message: "The output with formatter is generated by psort.py and seeing that is running as part of TS that is the location where the configuration needs to be updated."

**Comment by antoine-virgos** [comment]
```
```
2023-01-12 09:29:35,673 [WARNING] (MainProcess) PID:283 <tools> This version of plaso is more than 6 months old.
2023-01-12 09:29:35,684 [INFO] (MainProcess) PID:283 <base> HEAD http://elasticsearch:9200/a05f144191374daa9fc84a51ec7a532b [status:200 request:0.007s]
2023-01-12 09:29:35,685 [WARNING] (MainProcess) PID:283 <mediator> Using default message formatter for data type: myparser:entry
```

**Comment by antoine-virgos** [comment]
I went into the Timesketch container and noticed a lot of logs related to ```psort```.

Last ```psort``` log :
```
2023-01-12 09:42:08,469 [WARNING] (MainProcess) PID:16 <tools> This version of plaso is more than 6 months old.
2023-01-12 09:42:08,478 [INFO] (MainProcess) PID:16 <base> HEAD http://elasticsearch:9200/a05f144191374daa9fc84a51ec7a532b [status:200 request:0.005s]
2023-01-12 09:42:08,479 [WARNING] (MainProcess) PID:16 <mediator> Using default message formatter for data type: myparser:entry
2023-01-12 09:42:09,154 [INFO] (MainProcess) PID:16 <base> POST http://elasticsearch:9200/a05f144191374daa9fc84a51ec7a532b/_bulk [status:200 request:0.173s]
```
Still in the Timesketch container:

```
# log2timeline.py -V

plaso - log2timeline version 20210606
```

```
# psort.py -V

plaso - psort version 20210606
```

I have the impression that the version of ```psort``` used by Timesketch is the same as the one on my computer.

**Comment by joachimmetz** [comment]
> I have the impression that the version of psort used by Timesketch is the same as the one on my computer.

I don't have insight into your configuration, by default TS uses a Dockerized version of psort that is independent from other installations.

**Comment by joachimmetz** [comment]
No update from orginal reporter closing
