### ISSUE TITLE
does psort slice support ISO8601 format?

### ISSUE THREAD

**Issue by jfstenuit** [log2timeline/plaso#4582]
**Describe the problem:**

ISO8601 argument supplied to psort's "slice" argument is not recognized

**To Reproduce:**

The version of Plaso you used:

20230311

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 22.04 + SIFT

Steps to reproduce the behavior including command line and arguments and output:

```
$ psort.py --version
plaso - psort version 20230311
$ psort.py -o l2tcsv  -w xxx_slice.csv --slice '20230310T00:00:00+01:00' --slice-size 1440 xxx.plaso
2023-03-15 10:18:23,385 [INFO] (MainProcess) PID:7042 <data_location> Determined data location: /usr/share/plaso
ERROR: Unsupported time slice date and time: 20230310T00:00:00+01:00. The date and time must be defined in ISO 8601 format, for example: 20200619T20:09:23+02:00
```

The method you used to install Plaso:

Installed with DFIR : 
```
# dpkg -i cast_v0.14.0_linux_amd64.deb 
# cast install teamdfir/sift-saltstack

```

**Expected behavior:**

"20230310T00:00:00+01:00" should be recognized as a legit ISO8601 datetime string

**Debug output/tracebacks:**

N.A.

**Additional context**

N.A.

**Comment by joachimmetz** [comment]
> does psort slice support ISO8601 format?

```
Filter Arguments:
  --slice DATE_TIME     Date and time to create a time slice around. This parameter, if defined, will display all events that happened X minutes before and after the defined date, where X is controlled by the --slice_size option, which
                        is 5 minutes by default. The date and time must be specified in ISO 8601 format including time zone offset, for example: 20200619T20:09:23+02:00.
```

looks like the example in the documentation might be wrong try adding `-` to the date `'2023-03-10T00:00:00+01:00'`
