### ISSUE TITLE
Missing required artifact definition: LinuxHostnameFile on WSL installation

### ISSUE THREAD

**Issue by tad-schlatre** [log2timeline/plaso#4595]
I ran the following commands on a clean Ubuntu 22.04 WSL:

sudo apt-get update
sudo apt-get upgrade
cd /opt
sudo git clone https://github.com/log2timeline/plaso.git
sudo chmod 755 /opt/plaso -recursive
sudo apt install python3-pip
sudo python3 setup.py install             
pip3 install -r requirements.txt
psteal.py -V
plaso - psteal version 20230311

I then ran the command and received the following error:
**plaso@C9100E022B6673E:/$** _psteal.py --source /mnt/e/source.raw -o l2tcsv -w /mnt/o/DFeD-2023-02-0040/Attack_Emulation/WPCE21B04/WPCE21B04_timeline-out_8.csv --storage_file /mnt/o/DFeD-2023-02-0040/Attack_Emulation/WPCE21B04/WPCE21B04_storage.plaso -z utc
2023-03-28 21:49:25,128 [INFO] (MainProcess) PID:11876 <data_location> Determined data location: /usr/local/lib/python3.10/dist-packages/plaso-20230311-py3.10.egg/share/plaso
2023-03-28 21:49:25,139 [INFO] (MainProcess) PID:11876 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts
**_ERROR: Missing required artifact definition: LinuxHostnameFile__**

My artifact definitions folder is _/usr/share/artifacts_ and contains the following files:
antivirus.yaml
applications.yaml
cloud_services.yaml
config_files.yaml
containerd.yaml
docker.yaml
file_systems.yaml
hadoop.yaml
installed_modules.yaml
instant_messaging.yaml
java.yaml
kaspersky_careto.yaml
kubernetes.yaml
legacy.yaml
linux.yaml
linux_proc.yaml
macos.yaml
shell.yaml
tomcat.yaml
triage.yaml
unix_common.yaml
user.yaml
webbrowser.yaml
webservers.yaml
windows.yaml
windows_dll_hijacking.yaml
wmi.yaml

What file am I missing in my artifacts definition folder?

**Comment by joachimmetz** [comment]
the error message is telling you that `LinuxHostnameFile` is missing from these files, not that a file is missing. Make sure you have the latest version of artifacts-data installed.

**Comment by joachimmetz** [comment]
Closing since WSL is not a recommended / supported platform. Also see https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html#how-to-get-started
