### ISSUE TITLE
Opensearch: why is datetime field outputted as a string?

### ISSUE THREAD

**Issue by 4553n** [log2timeline/plaso#4615]
**Describe the problem:**

When a plaso file is created (successfully) and subsequently uploaded to OpenSearch, the corresponding index contains the filed "datetime" but its type is "string" instead of "date". 

![index_no_contain_date_field](https://user-images.githubusercontent.com/100310841/230151256-ce8ac0d6-c893-45e9-a455-692580729348.png)
Even the message, when an index pattern is created, the field appears as ```string``` (expected, I guess)

![datetime_field](https://user-images.githubusercontent.com/100310841/230152595-37068ec8-9285-4803-a430-1445d0ef2101.png)

**To Reproduce:**

- The version of Plaso you used: ```20230402 (same results with previous versions as well) Installed in venv.```
- The operating system you are running Plaso on: ```Ubuntu 22.04```
- Vesrion of OpenSearch: ```2.6.0```

Steps to reproduce the behavior including command line and arguments and output:

```bash
./log2timeline.py --storage_file /home/user/cases/test/test.plaso /home/user/cases/test/test.vhdx (successfull)
./psort.py -o opensearch --index_name test --opensearch-server 192.168.1.xxx --opensearch-mappings ../data/opensearch.mappings /home/user/cases/test/test.plaso
```
tried with:
```bash
./psort.py -o opensearch --index_name test --opensearch-server 192.168.1.xxx --opensearch-mappings ../data/opensearch.mappings --dynamic_time /home/user/cases/test/test.plaso
```
as well

**Expected behavior:**

The corresponding index should have the ```"datetime"``` field as ```"date"```, not ```"string"```, so that the analyst is able to set time frames, sort by time etc., e.g.:

![expected](https://user-images.githubusercontent.com/100310841/230152117-c3f1189f-c32c-4c22-921c-bc8590df5d35.png)

**Comment by joachimmetz** [comment]
what does your `opensearch.mappings` look like?

**Comment by 4553n** [comment]
It is the default one, that comes from the "data" folder of the main repository of "plaso".

**Comment by joachimmetz** [comment]
> It is the default one, that comes from the "data" folder of the main repository of "plaso".

you will need to change it if you want datetime to be a date field, but not sure if OpenSearch accepts the string format

**Comment by joachimmetz** [comment]
also version 20230402 is a development version, use at your own risk

**Comment by joachimmetz** [comment]
Also conversion to OpenSearch date (https://opensearch.org/docs/latest/field-types/date/) seems to be lossy, also see https://osdfir.blogspot.com/2021/10/pearls-and-pitfalls-of-timeline-analysis.html

**Comment by joachimmetz** [comment]
I'm mentioning "also version 20230402 is a development version, use at your own risk" for different reasons. That "datetime" is a string is working as expected

**Comment by 4553n** [comment]
Noted, thanks. So if I need this field to be imported as "date" into OpenSearch, I have to add a description for ```datetime``` in `opensearch.mappings``` and set it to be a date?

**Comment by joachimmetz** [comment]
correct, however make sure the string is compatible with OpenSearch date type

https://opensearch.org/docs/latest/field-types/mappings/

**Comment by 4553n** [comment]
Added the following snippet to the ```opensearch.mappings``` file:
```
    "datetime": {
      "type": "date",
      "fields": {"keyword": {"type": "keyword"}}
    },
```

Initial tests looks promising. 
Will update further here.

**Comment by joachimmetz** [comment]
sounds good, I'll close this issue though, since the question has been answered.

**Comment by 4553n** [comment]
Thanks Joachim.
