### ISSUE TITLE
Add Chrome history visit count

### ISSUE THREAD

**Issue by chb2mn** [log2timeline/plaso#4643]
Sqlite/ChromeHistory queries for visit_count and drops in on the floor. In-code documentation suggests this is what "Typed_count" means, but that's incorrect.

**Comment by chb2mn** [comment]
I can't assign this to myself nor label it as is requested here: https://plaso.readthedocs.io/en/latest/sources/developer/Developers-Guide.html#contributing-code

I could also just be a dumdum

**Comment by joachimmetz** [comment]
> Sqlite/ChromeHistory queries for visit_count and drops in on the floor. In-code documentation suggests this is what "Typed_count" means, but that's incorrect.

Regarding typed_count this seems to be be better description https://developer.chrome.com/docs/extensions/reference/history/

```
The number of times the user has navigated to this page by typing in the address.
```
