### ISSUE TITLE
Could not build wheels for libvhdi-python, libvmdk-python, libvslvm-python, pytsk3

### ISSUE THREAD

**Issue by slo-sleuth** [log2timeline/plaso#4645]
**Describe the problem:**

While attempting to install plaso, I receive the following error message: **Could not build wheels for libvhdi-python, libvmdk-python, libvslvm-python, pytsk3, which is required to install pyproject.toml-based projects.**

Build errors indicate issues with libbfio, for example (full stderr log attached):

```sh
In file included from pyvmdk/pyvmdk.c:33:
      In file included from pyvmdk/pyvmdk_extent_descriptor.h:28:
      In file included from pyvmdk/pyvmdk_handle.h:28:
      In file included from pyvmdk/pyvmdk_libbfio.h:31:
      libbfio/libbfio_definitions.h:44:6: error: redefinition of 'LIBBFIO_FLAGS'
      enum LIBBFIO_FLAGS
           ^
      /usr/local/include/libbfio/definitions.h:35:6: note: previous definition is here
      enum LIBBFIO_FLAGS
           ^
      In file included from pyvmdk/pyvmdk.c:33:
      In file included from pyvmdk/pyvmdk_extent_descriptor.h:28:
      In file included from pyvmdk/pyvmdk_handle.h:28:
      In file included from pyvmdk/pyvmdk_libbfio.h:31:
      libbfio/libbfio_definitions.h:48:9: error: redefinition of enumerator 'LIBBFIO_FLAG_IO_HANDLE_NON_MANAGED'
              LIBBFIO_FLAG_IO_HANDLE_NON_MANAGED              = 0x00,
              ^
...
```

[libbfio-alpha-20221025](https://github.com/libyal/libbfio/releases/tag/20221025) release installed as part of a [sleuthkit](https://github.com/sleuthkit/sleuthkit) 4.12.0 build from the sleuth kit GitHub repository.

```sh
$ echo $CFLAGS 
-I/usr/local/include
$ echo $LDFLAGS
-L/usr/local/lib
$ find /usr/local -iname "*libbfio*"
/usr/local/include/libbfio
/usr/local/include/libbfio.h
/usr/local/lib/pkgconfig/libbfio.pc
/usr/local/lib/libbfio.a
/usr/local/lib/libbfio.la
/usr/local/lib/libbfio.1.dylib
/usr/local/lib/libbfio.dylib
/usr/local/share/man/man3/libbfio.3
```

**To Reproduce:**

The version of Plaso you used:

 plaso-20230311

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

macOS 12.6.5

The method you used to install Plaso:

```sh
$ mkdir plaso
$ cd plaso
$ wget https://github.com/log2timeline/plaso/releases/download/20230311/plaso-20230311.tar.gz
$ python --version
Python 3.11.3
$ xcode-select -v
xcode-select version 2395.
$ python -m venv venv
$ source venv/bin/activate
$ pip install -r plaso-20230311/requirements.txt
```

**Expected behavior:**

Completed python build of plaso without fatal errors.

**Comment by joachimmetz** [comment]
This is not a Plaso problem but likely an issue the pytsk3 configuration in combination with your build environment. Try adding `--without-libbfio to pytsk3 setup.py https://github.com/py4n6/pytsk/blob/main/setup.py#L317

**Comment by joachimmetz** [comment]
Regarding the build warning for pyvmdk and pyvhdi which versions are you trying to build since recent versions should disable any use of a shared version of libbfio also see https://github.com/libyal/libvhdi/blob/main/setup.py#L102

**Comment by joachimmetz** [comment]
I'm closing this issue. Please open individual issues with the corresponding projects including version information, config.log from the wheel build and detailed description of how you set up your build environment.

**Comment by slo-sleuth** [comment]
Ok, I will do so.

I posted here since I was following the Plaso macOS installation instructions from the docs, and the errors occurred while installing dependencies listed in requirements.txt from this project.  

I forgot to attach the stderr log previously, so I'm attaching now.

[stderr_log.txt](https://github.com/log2timeline/plaso/files/11379346/stderr_log.txt)

**Comment by joachimmetz** [comment]
Unfortunately no instructions can account for all the issues that surface due to different environments.
