### ISSUE TITLE
Are AWS VPC Netflow log supported?  

### ISSUE THREAD

**Issue by mathurin68** [log2timeline/plaso#4650]
I'm trying to create a supertimeline with IIS logs, load balancer logs and AWS VPC flow logs(https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)

![image](https://user-images.githubusercontent.com/5932961/236628455-f462deb5-19db-461b-9e63-f3dee0e04c7a.png)

This is the log2timeline command I run to create the plaso
```
log2timeline.py --storage-file awstimeline.plaso /mnt/c/Users/me/Downloads/log2timeline/
```
This is the command I run to create the csv 
```
psort.py -w supertimeline.csv awstimeline.plaso "date > '2023-04-13' AND date < '2023-04-20'"
```

It seems to completely ignore the AWS VPC flow logs, all the other logs are in there 
![image](https://user-images.githubusercontent.com/5932961/236628604-59253626-ecd3-474a-b900-97c899fb2b72.png)

IIS logs and LB logs look great in the supertimeline... but it seems to completely ignore the VPC flow logs(netflow) that are in this format - 
```
4/13/2023 9:03	2	0.0978F+07	foj-09f9bfdf30568cd47	10.0.0.1	10.0.0.2	8834	59703	6	8	3060	1681391004	1681391033	ACCEPT	OK
4/13/2023 9:03	2	0.0978F+07	foj-09f9bfdf30568cd47	10.0.0.1	10.0.0.2	8834	59706	6	8	3060	1681391004	1681391033	ACCEPT	OK
```

They came without headers but looking at the page above I think these are the headers -
```
TimeStamp	Version	account-id	interface-id	srcaddr	dstaddr	srcport	dstport	protocol	packets	bytes	start	end	action	log-status
```

I'm totally new to log2timeline, but up until these logs, it's been easy to place all the logs in a folder and just point log2timeline at the folder!  

I'm sure I'm just missing something but I'm hoping someone can point me in the right direction.  Is there something else log2timeline needs to parse the log and add it to the timeline? 

Thank you!

**Comment by joachimmetz** [comment]
What format are these "AWS VPC Netflow Logs", we don't mention it in the supported formats (see: https://plaso.readthedocs.io/en/latest/sources/Supported-formats.html)

**Comment by mathurin68** [comment]
Ah, wow, ok that answers alot... I just read through a couple blogs and jumped right into it!  I should have rtfm.  

Stupid question... there isn't a 'catchall' format I could kind of put it in?  

Thank you for your answers!

**Comment by joachimmetz** [comment]
> Stupid question... there isn't a 'catchall' format I could kind of put it in?

how would you propose doing this? a lot of log formats are more or less different from oneandother

**Comment by mathurin68** [comment]
@joachimmetz sorry, in the middle of an incident, exhausted, and grasping at straws... this tool has been an absolute LIFE SAVER the last week or so, and I can't wait to dig through it more.  Thank you!!
