### ISSUE TITLE
What output should I expect for dynamic?

### ISSUE THREAD

**Issue by sikige** [log2timeline/plaso#4683]
Hi,

Using the last Docker Plaso version, I run `log2timeline --storage-file timeline.plaso Security.evtx` and then `psort -o dynamic -w timeline.csv timeline.plaso.` The CSV contains all the main Windows Event information into the `message` column. I expected this coulum was parsed more to have for example a column for the Event ID, another for the User, etc.

Is the original output normal ? Did I do something wrong ?

Thanks in advance.

**Comment by joachimmetz** [comment]
> I except this coulum was parsed more to have for example a column for the Event ID, another for the User, etc.

why would you expect this? this is not what is stated in the documentation https://plaso.readthedocs.io/en/latest/sources/user/Output-and-formatting.html#dynamic-output-module-fields

**Comment by sikige** [comment]
The goal is to be able to do a better timeline analysis with easier reading and filtering.
How do you analyse if information is all in the same cell? Maybe my timeline analysis approach isn't the right one.
An example of what I could expect is the output of the Eric Zimmerman’s EvtxECmd tool.

**Comment by sikige** [comment]
>how does it handle duplicate properties? How does it handle different event data versions?

I don't know how to answer, him and his tools are quite well known in the forensic industry, also used into SANS courses.

> Could you elaborate what you mean with "better timeline analysis"

How do you analyse a timeline in Kibana or Timesketch if all information are in the same column?

I also use Timesketch, can you explain me in what `opensearch_ts` differ from `opensearch?` Should I deduce to use `opensearch_ts` if I use Timesketch and `opensearch` if I use the native OpenSearch?
