### ISSUE TITLE
Re-add Elasticsearch output module support?

### ISSUE THREAD

**Issue by sikige** [log2timeline/plaso#4684]
Hi,

I saw the issue #4012, Elasticsearch is not open-source anymore, but there is still the free version. Timesketch is well, but Elastic Suite offers interesting features, in particular when you use it as SIEM.

Is there no possibility to add again Elastic psort output, please?

Thank you.

**Comment by joachimmetz** [comment]
> Is there no possibility to add again Elastic psort output, please?

Elasticsearch has an incompatible license, we cannot support it. 

Doesn't the OpenSearch module allow to interact with Elasticsearch?

**Comment by joachimmetz** [comment]
Closing, seeing that this cannot be resolved without Elasticsearch changing its license.
