### ISSUE TITLE
ConnectionError opensearch module

### ISSUE THREAD

**Issue by sikige** [log2timeline/plaso#4689]
Hello,

This is related to a comment from #4684.

I tried to use the `opensearch` module to send date to Elasticsearch using `psort -o opensearch --opensearch-server localhost --opensearch-port 9200 --index_name test --opensearch-mappings opensearch.mappings timeline.plaso`. I received the following error message.
```
Unable to create OpenSearch index with error: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f4a147a1570>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f4a147a1570>: Failed to establish a new connection: [Errno 111] Connection refused)
```
The Elasticsearch is reacheable.
```
curl localhost:9200
{
  "name" : "c1923b783d6a",
  "cluster_name" : "docker-cluster",
  "version" : {
    "number" : "8.8.0",
[...]
```

Perhaps the version of Elasticsearch is too recent?

**Comment by joachimmetz** [comment]
> Perhaps the version of Elasticsearch is too recent?

Could be, as indicated before, we don't support Elasticsearch. You're on your own here.

**Comment by joachimmetz** [comment]
Duplicate of https://github.com/log2timeline/plaso/issues/4684
