### ISSUE TITLE
How do I use output module opensearch_ts?

### ISSUE THREAD

**Issue by hasamba** [log2timeline/plaso#4707]
**Describe the problem:**

trying to psort plaso file to timesketch output format gets an error

**To Reproduce:**

The version of Plaso you used:

20230311

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 20.04

Steps to reproduce the behavior including command line and arguments and output:

sudo docker run -v /outputs/:/data -v /opt/timesketch/etc/timesketch/:/etc/timesketch log2timeline/plaso psort.py -o opensearch_ts -w /data/artifacts_ready_for_ts.plaso /data/artifacts.plaso

The method you used to install Plaso:

Docker

**Comment by joachimmetz** [comment]
opensearch_ts is intended to be used by the Timesketch importer, it is not intended for direct use unless you manually perform the required additional steps on the side of Timesketch.

**Comment by hasamba** [comment]
@joachimmetz thanks for your answer 🙏
so the most productive workflow from kape to timesketch using plaso is?
1. log2timeline #INTPUT --parsers $PARSERS $OUTPUT
2. timesketch import $OUTPUT

are there any steps (from psort) i can sanitize/sort/clean the $OUTPUT for timesketch?

**Comment by joachimmetz** [comment]
> so the most productive workflow from kape to timesketch using plaso is?
