### ISSUE TITLE
How should I interpret the OpenSearch output when using Kibana?

### ISSUE THREAD

**Issue by salty4n6** [log2timeline/plaso#4711]
Hi,
I noticed that if I leverage the kitchen sink approach to running through some data and use psort to export to opensearch (elasticsearch/kibana 7.14.0) that the datetime data is different than using webhist, win7, win_gen, or win7_slow.

When creating a new Kibana index pattern using webhist, win7, win_gen, or win_slow, datetime is of type date.

When creating a new Kibana index pattern using the kitchen sink approach, datetime is of type date, text causing the index to not contain any usable time fields.

Here is the error/message when creating a kibana index pattern based on the kitchen sink approach.

"The indices which match this index pattern don't contain any time fields."

Any help would be appreciated.

I'm using the latest docker container of plaso, and version 7.14.0 of Elasticsearch and Kibana containers.

~Salty

**Comment by salty4n6** [comment]
An example of how the datetime field is populated with the kitchen sink approach:
<html>
<body>


datetime | 2023-07-19T13:26:49.957806+00:00
-- | --



</body>
</html>

An example of datetime using win_gen

<html>
<body>


datetime | Jul 19, 2023 @ 15:25:01.450
-- | --



</body>
</html>

**Comment by joachimmetz** [comment]
As you can see here datetime is exported as a string https://github.com/log2timeline/plaso/blob/main/plaso/output/shared_opensearch.py#L69 it is intended to be a string. Have a read of https://osdfir.blogspot.com/2021/10/pearls-and-pitfalls-of-timeline-analysis.html about date time representations.

`Jul 19, 2023 @ 15:25:01.450` is not a common Plaso date time pattern what is the data type of the event?

timestamp is the "normalized" date and time output

**Comment by joachimmetz** [comment]
No response from original reporter, closing issue.
