### ISSUE TITLE
systemd journal parser does not parse logs from systemd 249

### ISSUE THREAD

**Issue by sydp** [log2timeline/plaso#4728]
**Describe the problem:**

Please provide a clear and detailed description of what the problem is.

**To Reproduce:**

The version of Plaso you used:

20230623

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 22.04

```
systemd --version                 
systemd 249 (249.11-0ubuntu3.9)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

Steps to reproduce the behavior including command line and arguments and output:

Running:

```./tools/log2timeline.py --storage_file ~/test.plaso /var/log/journal/```

results in only filestat events (no systemd_journal events).

**Expected behavior:**

I would expect there to be systemd_journal events (that correspond to journalctl entries).

**Additional context**

Any other context about the problem here.

**Comment by joachimmetz** [comment]
any extraction warnings or related information in debug logs?

**Comment by sydp** [comment]
There is an error in debug logs -  unsupported file header size: 256.

**Comment by sydp** [comment]
Per the systemd --version output, it appears to support `ZSTD` compression.  Will confirm if there are log files/entries using this compression format.

**Comment by joachimmetz** [comment]
@sydp changes have been merged, does this fully address this issue?

**Comment by sydp** [comment]
> @sydp changes have been merged, does this fully address this issue?

Yes it does, thanks.  I didn't encounter any zstd compression entries and was able to parse the journal files without any warnings/errors.  I can create a new issue to add support for ZSTD compression.
