### ISSUE TITLE
Add support for Edge browser load_statistics.db

### ISSUE THREAD

**Issue by trashg0blin** [log2timeline/plaso#4732]
New enhancement request to parse load_statistics.db file used in Edge tracking prevention mechanisms

**Comment by joachimmetz** [comment]
@trashg0blin do you have test data you can share? Otherwise this will go on the long-term wish list

**Comment by trashg0blin** [comment]
@joachimmetz PR created for review and merge

**Comment by joachimmetz** [comment]
@trashg0blin thanks for the PR, I'll have a look later this week, when time permits

**Comment by joachimmetz** [comment]
Changes merged, closing issue
