### ISSUE TITLE
How do I install Plaso from source?

### ISSUE THREAD

**Issue by q2dg** [log2timeline/plaso#4734]
After cloning Plaso's git, I suspect the way would be doing setup.py install but this method is deprecated, so I don't know how to go
Thanks

**Comment by q2dg** [comment]
Hello. Thanks

I overlooked MacOS instructions because they are listed below a section in "https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html with the title "Installing the **packaged** release" (and my system is not a MacOS). Maybe adding a "Installing from source" section where MacOS and Linux system were listed would help 

On the other hand, I've tried to install Plaso on my Fedora 38 system from source (in a very dirty way, though) and I think I've succeed. I write down the command I've used for reference:

1.-I've installed these packages first: "gcc", "gcc-c++", "python-devel" and "openssl-devel" (in Ubuntu the name of these packages are, respectively: "gcc", "g++", "python-dev" and "libssl-dev")
2.` git clone https://github.com/log2timeline/plaso`
3. `cd plaso && sudo pip install -r requirements.txt`
4. `sudo ./setup.py install`

However, when doing step 3 I've got a bunch of these warning messages (each for nearly every module): _"DEPRECATION: libxxxx-python is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559"_  So I insist, this installation seems deprecated, so I would like to know another diferent way to install Plaso from sources.

Thanks!

**Comment by joachimmetz** [comment]
> Maybe adding a "Installing from source" section where MacOS and Linux system were listed would help

No it would not, because it will trick people that are not too familiar with installing from source to believe this is straightforward. I strongly recommend to stick with a recommended installation.
