### ISSUE TITLE
How to update Plaso on Ubuntu 20.04?

### ISSUE THREAD

**Issue by RSOCKS** [log2timeline/plaso#4735]
I've downloaded the newest release.  However a version check indicates nothing has changed from the previous version.

![plaso](https://github.com/log2timeline/plaso/assets/42501298/9053b2f2-5a84-4112-9eba-f403ef04d057)

The version of Plaso you used: plaso-20230717

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 20.04.6 LTS

Steps to reproduce the behavior including command line and arguments and output:

I ran log2timeline.py --version from the freshly downloaded release for plaso-20230717

**Comment by joachimmetz** [comment]
how did you download 20230717? Note that this project does not provide Ubuntu 20.04 packages.

**Comment by RSOCKS** [comment]
Hello, thanks for the reply.

I downloaded the tar.gz from the releases page.

![plaso](https://github.com/log2timeline/plaso/assets/42501298/ceb89653-939a-4b45-9107-b0a48b391fab)

**Comment by joachimmetz** [comment]
Have a read of https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html first. I strongly encourage to stick one of the documented installation methods such as Docker; especially if you're less familiar with installing from source.

**Comment by RSOCKS** [comment]
Hello,

I switched to Ubuntu 22.04 LTS (jammy) and installed as documented in the provided guide.  All is well.

Thank you!
