### ISSUE TITLE
Unable to determine location of data files.

### ISSUE THREAD

**Issue by tobecert** [log2timeline/plaso#4741]
when I try to use log2timeline.py, the error which is below always happen.

ERROR: Unable to determine location of data files.

I tried all of things that I could 

log2timeline.py --storage_file timeline.plaso userdata.img

log2timeline.py --storage_file timeline.plaso userdata.img

log2timeline.py --storage_file timeline.plaso {my_full_path}/userdata.img

log2timeline.py timeline.plaso userdata.img**

**To Reproduce:**

The version of Plaso you used:

20230717

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 22.04, Ubuntu 18.04

Steps to reproduce the behavior including command line and arguments and output:

First I ran `log2timeline.py --help` that provided me the following output `...`

Please provide the source data you used when you experienced the problem. For publicly available data please provide a URL or path of the source data.

ERROR: Unable to determine location of data files.

The method you used to install Plaso:

I tried to install plaso using pip3, and download plaso-20230717 with zip file

**Comment by joachimmetz** [comment]
> I tried to install plaso using pip3, and download plaso-20230717 with zip file

You are using a non-recommended installation method, use a recommend installation method https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html or pass the data files location as a parameter.
