### ISSUE TITLE
Turn Off  Status Screen

### ISSUE THREAD

**Issue by Alspeedo** [log2timeline/plaso#4750]
**Describe the problem:**

Currently, I am experiencing issues with the status screen in log2timeline, as it overwhelms my automation process and causes it to slow down. I would like to have the ability to either turn off the status screen entirely using a flag or delay its refresh rate to reduce the frequency of updates. This would help ensure a smoother and more efficient automation process.
**To Reproduce:**

The version of Plaso you used:

20230717

The operating system you are running Plaso on (Not the operating system of the image/files you're trying to analyze):

Ubuntu 22.04

Expected Outcome

By implementing either of the proposed solutions, users will have more control over the status screen in log2timeline. This will enable a cleaner and less intrusive experience, especially for those running automated tasks. The reduced frequency of updates will prevent the automation process from being overwhelmed and improve overall efficiency.

**Comment by william-billaud** [comment]
You should take a look at the [status_view](https://github.com/log2timeline/plaso/blob/307aea10ea4a42a3a6ee7cfe1f159d95d044b159/plaso/cli/helpers/status_view.py#L30) flag.

It allows control of refresh rate and output mode.

**Comment by joachimmetz** [comment]
as @william-billaud there are already options for this, see the help
