### ISSUE TITLE
Import Plaso timeline 

### ISSUE THREAD

**Issue by maxdal89** [log2timeline/plaso#4751]
Hello everyone,

I should import timelines generated with plaso into timesketch.

My idea is to use the command:
`psort.py -o opensearch_ts -w timeline_for_timesketch.csv timeline.plaso
`
and manually upload the timeline_for_timesketch.csv file to timesketch.

However, I have the following error

`ERROR: No such OpenSearch mappings file: /etc/timesketch/plaso.mappings.
`

If I copy the file https://github.com/google/timesketch/blob/master/data/plaso.mappings to /etc/timesketch/plaso.mappings and run psort again, I get a loop here:

Please specify a value for timeline_id:

`even if you enter an ID (e.g. 01) the processing does not proceed.
`
How can I easily import a timeline.plaso into timesketch?

**Comment by joachimmetz** [comment]
use the timesketch importer instead
