### ISSUE TITLE
"AttributeError: module 'main': Windows 11 and Python 3.10.11

### ISSUE THREAD

**Issue by dafneb** [log2timeline/plaso#4753]
Everytime I tried run any of tool without argument "--single-process" I get error "AttributeError: module '__main__' has no attribute '__spec__'. Did you mean: '__doc__'?"

Problem was fixed with simple adjusting of scripts:

- image_export.py 
- log2timeline.py
- pinfo.py
- psort.py
- psteal.py

```
if __name__ == '__main__':
  # For PyInstaller sake we need to define this directly after "__main__".
  # https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
  __spec__ = None
  multiprocessing.freeze_support()

  if not Main():
    sys.exit(1)
  else:
    sys.exit(0)
```

**Comment by dafneb** [comment]
Maybe problem is with installation, it's my first experience with Python ... 

Okay, I have got FlareVM based on Win11 22H2. I downloaded last release of log2timeline (plaso-20230717). 
Then I run these commands:

pip install -r requirements.txt
python setup.py build
python setup.py install

**Comment by dafneb** [comment]
And Python:
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by dafneb** [comment]
I found this solution at another projects:
https://github.com/eggnogdb/eggnog-mapper/issues/299
https://gitlab.com/ezlab/busco/-/issues/632
https://github.com/PoonLab/OpenRDP/issues/40

**Comment by joachimmetz** [comment]
> Maybe problem is with installation, it's my first experience with Python ...

I strongly recommend sticking with the recommended installation methods: https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html

> I found this solution at another projects:

What solution? Are you running in a virtual env? are you invoking the right script?

**Comment by dafneb** [comment]
Okay, my bad. I will install it at Linux.
