### ISSUE TITLE
AttributeError in psort when formatting message for Winreg event using dynamic output

### ISSUE THREAD

**Issue by nflexfo** [log2timeline/plaso#4754]
**Describe the problem:**

Crash in psort when exporting events

**To Reproduce:**

```
./tools/log2timeline.py --storage_file ./debug.plaso ./test_data/SYSTEM
./tools/psort.py ./debug.plaso -o dynamic -w debug.csv --additional_fields key_path,values
```

Plaso version 20230717, yet the bug seems introduced (or triggered) by commit
4656497775 "Changes to Windows Registry event data values (#4581)".

**Expected behavior:**

No crash

**Debug output/tracebacks:**

```
Traceback (most recent call last):
  File "<...>/plaso/./tools/psort.py", line 101, in <module>
    if not Main():
  File "<...>/plaso/./tools/psort.py", line 74, in Main
    tool.ProcessStorage()
  File "<...>/plaso/plaso/cli/psort_tool.py", line 509, in ProcessStorage
    output_engine.ExportEvents(
  File "<...>/plaso/plaso/multi_process/output_engine.py", line 491, in ExportEvents
    self._ExportEvents(
  File "<...>/plaso/plaso/multi_process/output_engine.py", line 298, in _ExportEvents
    self._ExportEvent(
  File "<...>/plaso/plaso/multi_process/output_engine.py", line 193, in _ExportEvent
    self._FlushExportBuffer(
  File "<...>/plaso/plaso/multi_process/output_engine.py", line 362, in _FlushExportBuffer
    output_module.WriteFieldValuesOfMACBGroup(
  File "<...>/plaso/plaso/output/interface.py", line 120, in WriteFieldValuesOfMACBGroup
    self.WriteFieldValues(
  File "<...>/plaso/plaso/output/text_file.py", line 234, in WriteFieldValues
    super(SortedTextFileOutputModule, self).WriteFieldValues(
  File "<...>/plaso/plaso/output/interface.py", line 104, in WriteFieldValues
    field_values = self._GetFieldValues(
  File "<...>/plaso/plaso/output/text_file.py", line 184, in _GetFieldValues
    return self._event_formatting_helper.GetFieldValues(
  File "<...>/plaso/plaso/output/shared_dsv.py", line 64, in GetFieldValues
    field_value = self._field_formatting_helper.GetFormattedField(
  File "<...>/plaso/plaso/output/formatting_helper.py", line 577, in GetFormattedField
    output_value = callback_function(
  File "<...>/plaso/plaso/output/formatting_helper.py", line 519, in _FormatValues
    values = event_data.values
AttributeError: 'EventData' object has no attribute 'values'
```

**Additional context**

Printing `event_data` shown that field `values` does not exist for every winreg
event. For instance, the key_path `HKEY_LOCAL_MACHINE\System\ControlSet002\services\coherence`
has no value. I'm not sure if this is expected to reduce the DB size on empty value
or not.

I tried to dig a bit on this bug and noticed that:

1) commit 4656497775 added the `'values': '_FormatValues',` callback for dynamic
  output in `_FIELD_FORMAT_CALLBACKS` in `dynamic.py` (as well as other output)

2) `callback_function` is always call in `FieldFormattingHelper::GetFormattedField()`,
  this might be triggered by the additional field "values" in the command line:

```
    callback_function = self._callback_functions.get(field_name, None)
    if callback_function:
      output_value = callback_function(
          output_mediator, event, event_data, event_data_stream)
```

3) We end up here:

```
# formatting_helper.py
    def _FormatValues(
        self, output_mediator, event, event_data, event_data_stream):
        """Formats a values. [...cut...]"""
        values = event_data.values # BUG: AttributeError
```

Looking at other formaters, like `_FormatSourceShort`, seems to use `getattr()`
to prevent this AttributeError.

This might be related to issue #4640.

Not sure if the formatter expect all values to be set when called, or should it
be more "defensive" and use getattr(). If so, there might be other places to
look for.

Otherwise, maybe let the value (even if empty) be always written in the storage
file in the first place.

Note that the bug is not triggered when the additional field `value` is not used
in command line:

```
# GOOD
./tools/psort.py ./debug.plaso -o dynamic -w debug.csv --additional_fields key_path

# BAD
./tools/psort.py ./debug.plaso -o dynamic -w debug.csv --additional_fields key_path,values
```

Let me know what you think about it, and thanks again for this wonderful tool
that is Plaso.

**Comment by joachimmetz** [comment]
Thanks for the report, I've been able to reproduce it. A missing values attribute should not break the formatter, I'll make some changes.

**Comment by nflexfo** [comment]
The fix worked for me, thank you.

I haven't found any similar bug while running check on every files in `test_data` with additional fields.
