### ISSUE TITLE
Missing required artifact definition: MacOSLocalTime on Kali installation?

### ISSUE THREAD

**Issue by Saycho** [log2timeline/plaso#4766]
hello,

After installing plaso on KALI, I tried to execute log2timeline.py but I get the issue below 

```
 ┌──(kali㉿kali)-[~]
 └─$ sudo log2timeline.py --artifact_definitions /usr/share/artifacts/ --storage-file /home/kali/Desktop/PLASO/timeline.plaso /home/kali/Desktop/SHARED_FOLDER_VM/xxxxx.dd
```

> 2023-12-22 10:44:57,700 [INFO] (MainProcess) PID:31883 <data_location> Determined data location: /usr/share/plaso
> 2023-12-22 10:44:57,706 [INFO] (MainProcess) PID:31883 <artifact_definitions> Determined artifact definitions path: /usr/share/artifacts/
> ERROR: Missing required artifact definition: MacOSLocalTime

I checked within the /usr/share/artifacts repo and it seems there is no MacOSLocalTime.yaml file. Even within the latest update of artifatcs /data files no file.

How can I solve this issue ?

Thx for your support
Regards,
Florent

**Comment by joachimmetz** [comment]
Can you provide the information requested in the template e.g.

* How did you installing Plaso and dependencies?
* What version?

MacOSLocalTime is an alias https://github.com/ForensicArtifacts/artifacts/blob/1a3fcd538027504a42eb5ff864b2355f6a44e2c0/data/unix_common.yaml#L45

**Comment by joachimmetz** [comment]
No update from reporter, closing issue for now.

**Comment by Saycho** [comment]
Hello Joachim,

Sorry for late answer. I have installed following this https://www.kali.org/tools/plaso/ with simple aptinstall plaso. I can see the yaml file in rtifact with the aliase but still the issue appears.

regards

**Comment by joachimmetz** [comment]
Those are not instructions/build created by this project and would recommend reporting the issue there.

**Comment by canwegetit** [comment]
First time so forgive the ignorance but I am struggling with the same issue Saycho was having. I did read that this wasn't created by this project but from the plaso site it redirects me to this website/issues page. If this is not the place to get help for log2timeline where should I be looking? 

-C

**Comment by joachimmetz** [comment]
@canwegetit this is the plaso issue tracker. https://www.kali.org/tools/plaso/ is not official project documentation if you have issues with that documentation reach out to the author instead.

The official plaso documentation can be found here https://plaso.readthedocs.io/en/latest/
