### ISSUE TITLE
Error while making a build from the file setup.py

### ISSUE THREAD

**Issue by EugeneSam** [log2timeline/plaso#4783]
Hello. I try to make a build from the file setup.py (command: python setup.py build) and I have a such error 
"ERROR: Could not build wheels for libewf-python, libfvde-python, which is required to install pyproject.toml-based projects"

The description of this error next:
"Creating library build\temp.win-amd64-cpython-312\Release\libbfio\pyfvde.cp312-win_amd64.lib and object build\temp.win-amd64-cpython-312\Release\libbfio\pyfvde.cp312-win_amd64.exp
      pyfvde_volume.obj : error LNK2001: unresolved external symbol PyUnicode_AsUnicode
      build\lib.win-amd64-cpython-312\pyfvde.cp312-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
      error: command 'd:\\Programming\\Microsoft Visual Studio\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libfvde-python"

"Creating library build\temp.win-amd64-cpython-312\Release\libbfio\pyewf.cp312-win_amd64.lib and object build\temp.win-amd64-cpython-312\Release\libbfio\pyewf.cp312-win_amd64.exp
      pyewf.obj : error LNK2001: unresolved external symbol PyUnicode_AsUnicode
      build\lib.win-amd64-cpython-312\pyewf.cp312-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
      error: command 'd:\\Programming\\Microsoft Visual Studio\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libewf-python"

What is the reason of this error? I use Python 3.12.1, log2timeline 20231224
Thanks in advance

**Comment by joachimmetz** [comment]
This method of installation is not recommend unless you are closely familiar with building from source. I recommend sticking with https://plaso.readthedocs.io/en/latest/sources/user/Users-Guide.html, given I don't have the time to help troubleshoot each build environment. Closing
