### ISSUE TITLE
have shellbag events provide the full shell item path

### ISSUE THREAD

**Issue by gregfreemyer** [log2timeline/plaso#48]
I have looked at the output of psort.py on a image of mine for shell bag activity.

The activity shows up, but there is not any folder information in the output file.  If I use ShellBagExplorer I do have folder info in some of the active shell bags so it is not a case of no data being available.

== details
I'm calling log2timeline / psort as:

/log2timeline.py -d --logfile plaso-debug.log --workers 4 --offset 411648 cu01c1.plasodb /mnt/imageCU01/ewf1

psort -z EST5EDT -w $dir.plaso.converted cu01c1.plasodb

I'm searching through the *.converted file.

**Comment by joachimmetz** [comment]
Proposed notation:
```
<Root> Path
```

E.g.
```
<My Computer> C:\Documents and Settings\Administrator
```

**Comment by joachimmetz** [comment]
http://codereview.appspot.com/219860043
