### ISSUE TITLE
 unable to determine version information for: flor

### ISSUE THREAD

**Issue by tad-schlatre** [log2timeline/plaso#4919]
Please delete

**Comment by william-billaud** [comment]
Hello,

flor is an optional dependency linked to [bloom analysis plugins](https://plaso.readthedocs.io/en/latest/sources/user/Analysis-plugin-bloom.html).

* If you don't use this plugin, you can ignore this warning.
* If you plan to use this plugin, you must install the flor package (either using the apt package [python3-flor](https://packages.ubuntu.com/noble/python3-flor), or using the python pip package [flor](https://pypi.org/project/Flor/), depending on how plaso was installed.
