### ISSUE TITLE
Feature Request: Parsing PCAP

### ISSUE THREAD

**Issue by JakePeralta7** [log2timeline/plaso#4920]
PCAP is a great artifact, for example it can be collected from IPS packet capture - it will be useful if it would be part of the super timeline.

PCAP files can be easily parsed in Python using scapy or pyshark.

**Comment by joachimmetz** [comment]
For context it was abandoned in the past due to issues https://github.com/log2timeline/plaso/issues/386 also could you provide some more context about what you want to extract from a PCAP, given it can contain many different things

**Comment by JakePeralta7** [comment]
That's a fair problem.

I find it hard to believe that parsing such a small number of packets will cause problems (packet capture of IPS logs only relevant packets).
The info that should be extracted is the content of the packets, preferably without needing to normalize it, but just providing all of the headers.

Here is an example of printing a packet using pypcapkit
```python
import pcapkit as pk

# Open the PCAP file
pcap = pk.PcapFile('your_file.pcap')

# Parse the packets
packets = [pkt._asdict() for pkt in pcap]

# Print the packets
for packet in packets:
    print(packet) 
```

**Comment by joachimmetz** [comment]
PCAP is a container format, you packet capture might be small, but others can be quite big. E.g.

```
packets = [pkt._asdict() for pkt in pcap]
```

can easily fill your memory

**Comment by joachimmetz** [comment]
> The info that should be extracted is the content of the packets, preferably without needing to normalize it, but just providing all of the headers.

what info? https streams, TPC/UDP information, IP information, Ethernet information, other? what use cases do you have mind?
