### ISSUE TITLE
Add field for start cluster to fsstat events

### ISSUE THREAD

**Issue by chrishargreaves** [log2timeline/plaso#4940]
Add field for the file start cluster in fsstat. Guess it's accessed anyway to get file content, just not recorded?

MFT resident files would probably need a special value to indicate NA, or another field to indicate resident/nonresident status.

**Comment by joachimmetz** [comment]
Could you explain your use case in more detail? I have a hard time understanding the added value of this information? 

Also what if the first cluster run is sparse or compressed? what if the file entry isn't a regular file? What if the file system is on a raid set?

**Comment by chrishargreaves** [comment]
Sorry for slow reply I didn't get a notification of this - will check my settings. 

It can potentially be used for detecting clock tampering, sorting files with the same timestamp (on FAT say) and a few other applications. It's not guaranteed, but with experiments on file system driver behaviour sometimes things can be said from the position on disk that files are written to. Mostly FAT examples at the moment but extending into other file systems. It would be facilitating the use of plaso for further research in this area. 

Applying digital stratigraphy to the problem of recycled storage media
https://doi.org/10.1016/j.fsidi.2024.301761

Beyond timestamps: Integrating implicit timing information into digital forensic timelines
https://doi.org/10.1016/j.fsidi.2024.301755


Agreed re edge cases. I think the start cluster is still ok when it's sparse or compressed? I haven't looked at raid set but is that not an abstraction layer below? Entries that are for example a reparse points or something would have NA like resident files I would imagine, and folders would also be either resident, or have a start cluster to the index record. I'm sure there are loads of edge cases, so I now appreciate this isn't trivial for everything, but could probably work out something sensible for the exceptions.

**Comment by joachimmetz** [comment]
I understand that this data has its value in certain context. What I'm trying to assess does it make sense to add to Plaso at this time given it is a generic date/time extraction tool.

> It would be facilitating the use of plaso for further research in this area.

Plaso is open source so it can be easily changed for specific research purposes before adding these changes to the core. Realize that adding data comes with a cost as well that might negatively impact other use cases of Plaso.

I'll read up on the articles you are referring to when time permits, but my first thought there are many factors that can influence the behavior, e.g. hotzones, volume managers, etc. So far it sounds to me this type of analysis could benefit from more research and specialized analysis tools.

Maybe interesting https://osdfir.blogspot.com/2021/10/pearls-and-pitfalls-of-timeline-analysis.html

**Comment by joachimmetz** [comment]
> Agreed re edge cases. I think the start cluster is still ok when it's sparse or compressed? 

depends on which cluster you are talking about, logical relative to file system, "physical" relative to file system, "physical" relative to (logical) storage media device, "physical" relative to physical storage media device.

In NTFS for sparse  "physical" relative to file system has technically no meaning and in other file systems it is often set to 0, and in NTFS certain compressed data is stored as reparse points and different reparse points can be used for various other purposes.

For context see: https://github.com/libyal/libfsntfs/blob/main/documentation/New%20Technologies%20File%20System%20(NTFS).asciidoc#555-data-runs

I'm worried that adding leads to more confusion than benefit given the general use case of Plaso.

**Comment by chrishargreaves** [comment]
Generally I'm talking about logical within the file system, but I appreciate this now needs entire classes of cluster offset types to differentiate. 

> I'm worried that adding this information, leads to more confusion than benefit given the general use case of Plaso.

No that's fair enough. For a lot of the stuff we are looking to do which is a bit more complex niche work with timelines there are a few useful fields this that aren't preserved (server time in Chrome cache items for example) and I thought I'd see what the likelihood was of getting these other bits of data exposed by plaso, but it's definitely fair enough that it isn't needed for the general use case.

I guess it's a shame there isn't something like 'advanced output' that just dumps json of all the fields that could be of use to anyone, which would give a lot of flexibility but avoid confusion to mainstream users, but that isn't going to get much use, even though its good for research. But given the lack of general interest in this, and the complexity of field labelling, I can see why this would not get done.

**Comment by joachimmetz** [comment]
> I guess it's a shame there isn't something like 'advanced output' that just dumps json of all the fields that could be of use to anyone

Doesn't the jsonl output already do this? but what you are asking for is to extract and store additional information, there is a limit to what can be captured.

**Comment by chrishargreaves** [comment]
Understood. Thanks anyway.

**Comment by joachimmetz** [comment]
> Understood. Thanks anyway.

Happy to chat more about this outside the context of Plaso, as I indicated earlier this type of analysis could benefit from more research and specialized analysis tools. So maybe something can be done in that direction first

**Comment by joachimmetz** [comment]
I'll close this for now, but happy to revisit if the use case for general purpose timelining is more clear.

**Comment by chrishargreaves** [comment]
Fair. Thanks. We'll build some test stuff and get back to you with proper use cases.
