### ISSUE TITLE
l2tTLN output: please add time indication

### ISSUE THREAD

**Issue by aozsyn** [log2timeline/plaso#5]
I've started down the path of debugging precisely why, but first off - thanks for adding the TLN outputs.  Unfortunately, it isn't quite right - specifically, when outputting filesystem timestamps, there's no indication of what the timestamp is (MACB, SI/FN, etc.).  

This appears to be because the FILE (and similar) types' "short" output lacks this metadata, and the TLN format uses these short outputs.  This unfortunately means the output isn't useful, I'm still outputting l2tcsv and using 0.65 to convert that to TLN.  I'm trying to get free time to work on a patch, but after a few months decided to just submit a placeholder ticket at least.

**Comment by joachimmetz** [comment]
TLN only defines:
```
Time|Source|Host|User|Description
```

Unless we overload "Description" the format does not offer a sensible place to put the "representation of the date and time value". Not sure if there is a definite source of this format some information I could find: http://windowsir.blogspot.com/2009/02/timeline-analysis-pt-iii.html. If the idea is to overload Description for this purpose I opt to switch to a different more expressive output format.

**Comment by aozsyn** [comment]
The problem is that I'm not requesting additional behavior, but a fix of existing behavior.  The TLN format Plaso outputs already has placeholders for MACB notation, it simply doesn't fill them out.  Log2timeline did, and the evident intent in creating the 5- and 7- field TLN outputs for Plaso was to emulate that.

If you're going to close this WONTFIX, then just eliminate the TLN output altogether, because it's broken.

**Comment by joachimmetz** [comment]
To confirm you mean the `|-|` in:
```
397334797|FILE|WKS-WIN764BITB|-|TSK:/Users/rsydow/AppData/Local/Microsoft/Feeds Cache/1RMRJ509/fwlink[1]
```

> If you're going to close this WONTFIX, then just eliminate the TLN output altogether,
> because it's broken.

True ;) 

I'll put in a CL to remove the `|-|` and then make a note to discuss killing of TLN support.

**Comment by aozsyn** [comment]
The reason I'd originally asked for TLN output was to shorten the process of going l2tcsv -> log2timeline -> tln.  I can resume that.  Here's an example from my own:
`852699600|FILE|system|-|TSK:/REGINI.EXE|UTC|File: TSK:/REGINI.EXE inode: 217211`

What it's lacking (and for a while was filled out as [....] is what of the 3, 4, or 8 timestamps that even is.  Taking the L2tcsv output from the same system and converting that line to TLN using log2timeline gets:
`852699600|FILE|system|-|[$FN M...] TSK:/REGINI.EXE|UTC| - inode:21721`

Evidently recent "fixes" just removed that very critical [....] box denoting what the timestamp is.

**Comment by joachimmetz** [comment]
It this is the TLN ["standard"](http://windowsir.blogspot.com/2009/02/timeline-analysis-pt-iii.html). Your changes void it from being TLN. Since you have 7 fields now.
```
52699600|FILE|system|-|[$FN M...] TSK:/REGINI.EXE|UTC| - inode:21721
```

What I opt is to overload the Description e.g.
```
52699600|FILE|system|-|1971-09-02T22:46:40.003651+00:00 - [M...] TSK:/REGINI.EXE - inode:21721
```

This is far from a structural solution but might provide you with the minimum additional information for the time being. What I as of you can you provide me with a list of bare essential information you want to add to the description.

> Regardless, without that content, the TLN output as it stands is relatively worthless.

The main reason for this is that the TLN "standard" is too limited (if one should be calling it a standard at all). It does not define some fields you and I think are essential to our timeline output, e.g. timezone, "meaning of date time value", high precision date and time value.

**Comment by joachimmetz** [comment]
To be verbose are you talking about `tln` or `l2ttln`?

**Comment by joachimmetz** [comment]
http://codereview.appspot.com/218250043

**Comment by joachimmetz** [comment]
Since the documentation on TLN as a "standard" seems to consist of a couple of blog post. I've created the following reference: http://forensicswiki.org/wiki/TLN. Feel free to extend this wiki page.

**Comment by aozsyn** [comment]
I'm specifically talking about l2ttln, the way I generated that first sample was:
`psort.py -o l2ttln system.plaso | grep <identifier>` 
The second example was generated nearly the following way (using a pipe instead of an interim file, since old log2timeline does not handle STDIN):
`psort.py -o l2tcsv system.plaso | grep <identifier> | log2timeline -Z UTC -f l2t_csv -o tln`

It's critical to point out that I am not making the above formats, I'm using what's already there in Plaso and log2timeline.  The 5- and 7-field TLN formats were added to Plaso at the same time since it was apparent that the original log2timeline had made its own extension.  TLN is certainly not a standard, but all I really care about is the left-heavy format that's deeply friendly to simple parsing with text-based tools (sed/awk/grep/vim).

As far as the other overloaded fields, I'm pretty indifferent.  A derived time field is redundant (if perhaps more accurate), and I convert the epoch timestamps when analyzing anyway; epoch is just an easier way to sort.

If anything I'd prefer that the timestamp name (MACB) remain the first item in the description field, followed by the file name.  The nice thing about the [....] format was that it allowed multiple timestamps on the same line, clearly (visually) illustrating clustering.  It's certainly not easier to provide that way with how Plaso is architected, but it would be nice.

**Comment by joachimmetz** [comment]
> It's critical to point out that I am not making the above formats,

Maybe you should, since you are running into the limitations of the formats.

> The nice thing about the [....] format was that it allowed multiple timestamps on the same line, clearly (visually) illustrating clustering.

Yes the reduction of lines of output is nice but I've noticed also a couple of short comings with the [MACB notation](http://wiki.sleuthkit.org/index.php?title=Mactime_output):
* it seems highly confusing for people with little disk forensics background; even authors of "forensic books" seem to confuse the meaning of the individual letter for different file systems;
* what about any other use of a date and time value, e.g. last visited time, last cache refresh time, deleted time, etc.

So technically plaso allows you add your own output format, to tailor your needs. If you have suggestions on what should be in a first iteration of that format let us know. Maybe we could come up with a "short" format or equiv that can provide the essentials. However I would suggest starting a discussion on the dev list to see what different analysts value in their output format.

**Comment by aozsyn** [comment]
> * what about any other use of a date and time value, e.g. last visited time, last cache refresh time, deleted time, etc.

This is the difficulty and value with timelines, sufficiently normalizing data to a common-enough format that it makes linear sense without altering the origin data too much.  TLN tends to wave a hand over the "details" field and I honestly wouldn't struggle with that too much - what's important are the timestamp, source, host, "user", and then "something" to represent the event at that timestamp.  That "something" need not really be very regular, it simply needs to provide sufficiently accurate data describing the event.  That's what it's historically done, and if the timestamp name is just added back to the output (which it appears you may have already done), it will be enough.  We can deal with "ideal" at a later point, if at all.

**Comment by joachimmetz** [comment]
> what's important are the timestamp, source, host, "user", and then "something" to represent the event at that timestamp

What's important or not depends on your use case and your workflow. I can think of cases where host and user would primarily clutter my timeline and where a very particular flags field is very interesting to have in the timeline. These "formats" are as useful as your need for them.

There seems to be a lot of points of view regarding what's important or not; what should be the emphasis or not. For one person allowing to set a unique field marker is important for another being able to import the output in Excel. None of them will ever give a "ideal" solution for everyone.

**Comment by joachimmetz** [comment]
But try the patch in http://codereview.appspot.com/218250043 see if that fits your short team needs.

**Comment by aozsyn** [comment]
That will suffice for what I need right now; I'd rather not have the interpreted timestamp, but will take it for at least working.  Thanks!

**Comment by joachimmetz** [comment]
Change is in, closing issue.
