### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#511]
Issue for tracking progress on adding Python 3 support. Also see [Python 3 Guide](https://github.com/log2timeline/plaso/wiki/Python-3-Guide)

- [x] ~~libyal add Python 3 support~~
- [x] ~~pytsk3 add Python 3 support~~
- [x] ~~migrate to construct version 3 - no need~~
- [x] ~~dfvfs add Python 3 support~~
- [x] ~~dfwinreg add Python 3 support~~
- [x] ~~Fix tests for tox~~
  - ~~https://codereview.appspot.com/305530043/~~
  - ~~https://codereview.appspot.com/312740043/~~
- [x] ~~Add tox configuration to test Python 2 and 3~~
- [x] ~~Distribute dependencies via pypi~~
  - ~~need latest pefile on pypi~~
- [x] ~~plaso add Python 3 support~~
  - ~~https://codereview.appspot.com/277580043/~~
- [x] ~~issue with bencode~~
  - ~~recommendation is to use https://pypi.python.org/pypi/bencode.py instead~~
- [x] ~~Enable Python 3 on Travis~~
  - ~~https://codereview.appspot.com/329730043/~~
  - unclear reason why coverage is failing on tox -epy34  - https://travis-ci.org/log2timeline/plaso/jobs/249702741
- [x] dependencies that are not Python 3.4 and later compatible - marked as optional
  - construct
  - hachoir
  - pylzma
  - https://codereview.appspot.com/335980043/
- [x] ~~fix libewf experimental~~ - no longer a blocker
- [x] [update l2tdevtools and l2tbinaries](https://github.com/log2timeline/l2tdevtools/issues/150)

**Comment by Onager** [comment]
Currently targeting compatbility with python 3.5.3+
