### ISSUE TITLE
Incredibly Long Parsing Time

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#517]
I have an issue where log2timeline has been parsing approximately 1GB of linux log files (/var/log/messages and the sort) for several weeks. That's right, several weeks. I haven't killed it mostly because I'm curious how long it will actually take to parse the files. 

Only one worker has remained alive and dedicated to parsing the log files. It seems to be parsing about 3-4 events every few seconds. Now, these log files have a gratuitous amount of entries due to brute force scan/login attempts against a machine but I still don't know why it is taking such an exponentially long amount of time to process these files. 

I'm using Plaso version 1.3.0 and the image is a VMware Snapshot vmdk of a RHEL 6/7 system. The only useful entries in dmesg buffer are the following that have occurred a few times over the last few weeks:

> BUG: soft lockup - CPU#4 stuck for 23s! [log2timeline.py:7167]

Any ideas what may be going on here?

**Comment by joachimmetz** [comment]
Likely related: https://github.com/log2timeline/plaso/issues/358

**Comment by joachimmetz** [comment]
Closing this issue.
