### ISSUE TITLE
timezone list AttributeError

### ISSUE THREAD

**Issue by cshanahan** [log2timeline/plaso#519]
Hello,
While testing the latest Plaso build from the GIFT repo on a Ubuntu 14.04 system I noticed the following error when listing timezones. Obviously not a show stopper, but an error none the less. As expected, both '-z list' and '--timezone list' produced the same error.
user@DFIR-VM:~$ log2timeline.py -z list
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 816, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 791, in Main
    tool.ListTimeZones()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/tools.py", line 324, in ListTimeZones
    table_view.AddColumnNames([u'Timezone', u'UTC Offset'])
AttributeError: 'CLITableView' object has no attribute 'AddColumnNames'

user@DFIR-VM:~$ log2timeline.py -V
plaso - log2timeline version 1.3.1_20151231

/Chris

**Comment by joachimmetz** [comment]
Thanks for reporting the issue. I've reproduced it and a fix will be pending soon.
