### ISSUE TITLE
Improve ASL parser

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#530]
- [x] Clean up and improve code
- [x] Document format
  * https://github.com/libyal/dtformats/blob/master/documentation/Apple%20System%20Log%20(ASL)%20file%20format.asciidoc
- [x] ~~seeing the usage of bitfields evaluate rewrite in C~~ - no for now

**Comment by moxilo** [comment]
Joachim,

Tell me how you want to improve the code and I can work on this.

Related to documentation, page 46 to 50:
https://www.ma.rhul.ac.uk/static/techrep/2015/RHUL-MA-2015-8.pdf

**Comment by joachimmetz** [comment]
@moxilo due to personal circumstances please check with @Onager as indicated per mail.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/347900043/
