### ISSUE TITLE
add kik messenger sqlite plugin

### ISSUE THREAD

**Issue by ken-doh** [log2timeline/plaso#534]
I'm looking to create a sqlite plugin to parse the Kik messenger chat database.

The database is stored on iOS devices in /private/var/mobile/Containers/Data/Application/<UUID>/ 
and on Mac OS X backups in:
/Users/<username>/Library/Application Support/MobileSync/Backup/
in Windows backups:
\Users\<username>\AppData\Roaming\Apple Computer\MobileSync\Backup\
When stored in a backup it has the filename: 8e281be6657d4523710d96341b6f86ba89b56df7

**Comment by joachimmetz** [comment]
Duplicate of: https://github.com/log2timeline/plaso/issues/535
