### ISSUE TITLE
add kik messenger sqlite plugin

### ISSUE THREAD

**Issue by MacleodKen** [log2timeline/plaso#535]
I'm looking to create a sqlite plugin to parse the Kik messenger chat database.

The database is stored on iOS devices in: /private/var/mobile/Containers/Data/Application/\<UUID\>/Documents/kik.sqlite
and on Mac OS X backups in:
/Users/\<username\>/Library/Application Support/MobileSync/Backup/
in Windows backups:
\Users\<username\>\AppData\Roaming\Apple Computer\MobileSync\Backup\
When stored in a backup it has the filename: 8e281be6657d4523710d96341b6f86ba89b56df7

**Comment by joachimmetz** [comment]
@MacleodKen thanks for your interest here is some information to get you started:

* https://github.com/log2timeline/plaso/wiki/Developers-Guide
* https://github.com/log2timeline/codelabs
* look at how other sqlite plugins are implemented

**Comment by MacleodKen** [comment]
Hi, I want to start a code review, but don't know who to email as this link 404'd
https://github.com/orgs/log2timeline/teams/owners

I'm following this guide https://github.com/log2timeline/plaso/wiki/Codereview

**Comment by Onager** [comment]
Thanks for the pointer, I'll fix the page.

You no longer need to specify an owner, the script will do it for you.

-Daniel

**Comment by MacleodKen** [comment]
I've submitted code for review.

**Comment by joachimmetz** [comment]
For reference: https://codereview.appspot.com/288960043/

**Comment by MacleodKen** [comment]
Updated code for review. https://codereview.appspot.com/288960043/

**Comment by MacleodKen** [comment]
Hi,

I updated git and ran my code today, but I'm getting the following error when running 
`psort.py -w kikPlug.xlsx -o xlsx kik.plaso`
`[ERROR] Processing stopped early: Unable to use an already existing file for output [kikPlug.xls]`
It is not an already existing file and it doesn't matter what I name the file, I get the same error. Outputing to screen doesn't have any problems.
I think this is a bug, and I'm unsure where to post it, so I decided to put it here.

**Comment by MacleodKen** [comment]
Updated code for review. [https://codereview.appspot.com/288960043/](url)

**Comment by Onager** [comment]
Let's open a new issue for the psort errors: #578

**Comment by MacleodKen** [comment]
Updated code https://codereview.appspot.com/288960043/

**Comment by joachimmetz** [comment]
I assume this issue can be closed
