### ISSUE TITLE
"--workers <X>" option appears to be ignored

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#536]
Currently using an 8-core VM on ESXi instrumented with FC21 and CERT Forensics Repo to give me the latest version of Plaso 1.3.0. When using log2timeline.py command-line option of "--workers 7", it still defaults to 5 (system cores minus 3).

**Comment by joachimmetz** [comment]
Was addressed in: https://github.com/log2timeline/plaso/issues/439.

Try current HEAD or wait for 1.4 release.
