### ISSUE TITLE
Select partition range

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#537]
It would be nice to select a partition range similar to the shadow volumes. I was processing a drive and plaso failed to process one particular partition stating that the collector was not working correctly and the program exited. In order to run plaso on the remainder of the drive I have to run plaso on each partition individually.

**Comment by joachimmetz** [comment]
> In order to run plaso on the remainder of the drive I have to run plaso on each partition individually.

@odibrowne thanks for the feedback I've added this as a feature request, seeing that LVM support is planned for 1.5 I'll have a look at implementing this when I'm working on that. Can you also file an issue for the error you noticed when the collector failed. Thanks in advance.

**Comment by joachimmetz** [comment]
This will have to wait after the phased processing

**Comment by joachimmetz** [comment]
Added to: https://codereview.appspot.com/307830043/
