### ISSUE TITLE
Add support for psutil 2 and later

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#542]
* [x] ~~Add support for psutil 2 and later~~
* [x] ~~test with psutil 4.3~~
* [x] ~~Package latest psutil for GIFT~~
* [x] ~~Package latest psutil for l2tbinaries~~

**Comment by gregfreemyer** [comment]
Just a note that Plaso 1.4 is working with psutil v2.1.2 from my perspective.

I was unable to get it to work with v3.x
