### ISSUE TITLE
flaky protobuf tests

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#553]
Testing with tox indicates the protobuf tests are flaky due to the same issue as the json, that the order of the resulting strings is not guaranteed.

* [ ] Add a plaso base object
* [ ] Add a CopyToDict() method
* [ ] in the protobuf tests use the CopyToDict() method to compare plaso objects
* [ ] in the json tests use the CopyToDict() method to compare plaso objects
* [ ] determine if _tags => _event_tags in Analsyis report should be serialized

**Comment by Onager** [comment]
We have an issue for all these: #411

**Comment by joachimmetz** [comment]
Ack, however this is not only the tests. I'm looking at lib/event.py and it could use some spring cleaning.

**Comment by joachimmetz** [comment]
This issue is addressed by https://github.com/log2timeline/plaso/issues/633
