### ISSUE TITLE
SCCM Error

### ISSUE THREAD

**Issue by kmbMA** [log2timeline/plaso#557]
I just completed a brand new install of Ubuntu 14.04 with the latest version of Plaso 1.4. When I try to run log2imeline, it fails over and over again on the SCCM data. I believe this could be due to that specific data being encrypted here so is there any way to exclude the SCCM parser?

**Comment by Onager** [comment]
Yes, you can specify which parsers you want to run. From ```log2timeline.py --help```:

```
  --parsers PARSER_LIST
                        Define a list of parsers to use by the tool. This is a
                        comma separated list where each entry can be either a
                        name of a parser or a parser list. Each entry can be
                        prepended with a minus sign to negate the selection
                        (exclude it). The list match is an exact match while
                        an individual parser matching is a case insensitive
                        substring match, with support for glob patterns.
                        Examples would be: "reg" that matches the substring
                        "reg" in all parser names or the glob pattern
                        "sky[pd]" that would match all parsers that have the
                        string "skyp" or "skyd" in its name. All matching is
                        case insensitive. Use "--parsers list" or "--info" to
                        list the available parsers.
```

What's the error message log2timeline is giving you about the SCCM parser?

**Comment by kmbMA** [comment]
It was a very generic error stating that it could not parse the files in the ccm directory. I tried excluding the sccm parser and that worked like a champ. THANKS!

**Comment by aleksf** [comment]
I believe I've hit the same error

Freshly installed Ubuntu 14.04

python-plaso installed from gift/stable repo

root@haxbox:~# log2timeline.py -V
plaso - log2timeline version 1.4.0

Having following SCCM parser related errors in the logfile:

2016-04-23 15:42:02,612 [ERROR] (Worker_00 ) PID:10016 <mediator> [sccm] unable to parse file: TSK:/Temp/Investigation/ccm/Logs/Discovery-20160326-215126.log with error: Unable to parse log line: u'<![LOG[DiscoveryProvider:Discovery Function none(): The interoperation method...'

**Comment by kmbMA** [comment]
I found out that in our environment those logs are encrypted so I had to exclude them by using –sccm in the parsers section.

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by sansstudent** [comment]
i just came accross this post i have exactly this error. how to you exclude the sccm parser only?
could you post your complete command?

thanks in advance
