### ISSUE TITLE
Missing dependency in plaso ppa

### ISSUE THREAD

**Issue by f-s-p** [log2timeline/plaso#561]
Sorry if this is the wrong place to report this.  Let me know if there's a better place.

When installing from the _stable_ Ubuntu GIFT ppa:
>  apt-get install python-plaso

The python-xlsxwriter package is pulled from the standard Ubuntu repository because it does not exist in the GIFT ppa, and then log2timeline complains that a dependency is not met, because the version in the standard repo is old.  Looks like you may have an updated package in your dev ppa that didn't get copied into stable?

**Comment by joachimmetz** [comment]
Thanks for notifying, copied the newer package. Should be available when lauchpad is done building.

**Comment by joachimmetz** [comment]
Build completed, pending publication. Closing this issue.
