### ISSUE TITLE
KML Output Module

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#562]
I have created an output module which writes all event objects that have the attributes "latitude" and "longitude" into a KML formatted file which can be used with Google Earth.

**Comment by dc3-plaso** [comment]
I would to submit this for code review, but I am having issues with the pyfsntfs dependency downloaded from the bleeding edge GIFT ppa. 
I get the following error:
  ```
ImportError: /usr/lib/python2.7/dist-packages/pyfsntfs.so: undefined symbol: libfsntfs_volume_get_usn_change_journal
   ```

**Comment by joachimmetz** [comment]
Can you check if you have multiple versions of libfsntfs.so on your installation? e.g. /usr/local/lib an /urs/local

**Comment by dc3-plaso** [comment]
Thanks, that worked. There were some lingering libfsntfs library files there even after I uninstalled it. Removing them and reinstalling the package solves the problem.

**Comment by joachimmetz** [comment]
Great that it solved it. It's a common issue when using multiple ways to install the libraries from source.
I recommend sticking with the PPA, typically it should not be lagging behind too much because we use it for CI testing as well.
