### ISSUE TITLE
output module KML enhancement

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#570]
* [x] ~~it is not clear from `ElementTree.tostring` that it does XML sanitation  - add comment~~
  * ~~https://codereview.appspot.com/288490043/~~
* [x] ~~merge generation of event object string with code in rawpy.py~~
  * ~~https://codereview.appspot.com/284410043/~~

**Comment by joachimmetz** [comment]
@dc3-plaso FYI in case you notice invalid KML output.

**Comment by dc3-plaso** [comment]
I believe the ElementTree module handles this for us. 

For example:

```python
from xml.etree import ElementTree
test = ElementTree.Element(u'test')
test.text = u'& \ufffd # < > \x00'
ElementTree.tostring(test)
# Gives us
'<test>&amp; &#65533; # &lt; &gt; \x00</test>'
```

**Comment by joachimmetz** [comment]
Great, I did not deduce that from reading the code. I'll add a comment.
