### ISSUE TITLE
rebase master?

### ISSUE THREAD

**Issue by f-s-p** [log2timeline/plaso#575]
Did someone rebase master sometime in the last few months?  I can't fast-forward.  Looks like the most recent common ancestor is 3362f5658bc6daf6c971ee06391f21978b8c2d26.

**Comment by Onager** [comment]
Yep, see Joachim's email to the dev list "WARNING git history rewrite".

-Daniel

**Comment by Onager** [comment]
Reproducing Joachim's mail here:

> To start the new year with a fresh plaso history I just made the changes for:
> https://github.com/log2timeline/plaso/issues/113
> 
> Which means a plaso git history rewrite.
> 
> Why the change:
> * To fix errors in the history
> * To be able to automatically generate the AUTHORS file
> 
> 
> If you have forked plaso do the following:
> 
> # Make a back up of your local plaso git history
> cp -rf plaso plaso.bck
> 
> cd plaso
> 
> # Update and rebase master
> git checkout master
> git fetch upstream && git pull --rebase upstream master
> git push -f
> 
> 
> If you have pending plaso CLs on feature branches:
> * do the same for your feature branch as for master
> * Update the review on rietveld via: ./utils/update.sh
> 
> If you run into merge conflicts and your git-fu is failing on you please reach out, we might able to guide you through the process.
