### ISSUE TITLE
Unexpected existing file warning in psort with XSLX output option

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#578]
From #535 

> I updated git and ran my code today, but I'm getting the following error when running 
> psort.py -w kikPlug.xlsx -o xlsx kik.plaso
> [ERROR] Processing stopped early: Unable to use an already existing file for output [kikPlug.xls]
> It is not an already existing file and it doesn't matter what I name the file, I get the same error. Outputing to screen doesn't have any problems.

@MacleodKen can you provide a little more context:

- Was the filename mismatched, (xslx vs xls) in the output, or was that a typo?
- Which OS was this?

**Comment by MacleodKen** [comment]
Sorry, that's a typo - should be 
`[ERROR] Processing stopped early: Unable to use an already existing file for output [kikPlug.xlsx].`
I'm using OS X 10.11.3

**Comment by dc3-plaso** [comment]
@MacleodKen This was a bug that was fixed in commit 3b85c0ca4869decb236a868bc089ac3442a88594
Are you using the latest release?

**Comment by MacleodKen** [comment]
I'm using: 
8ed2c8a Code review: 282480043: Fixes for fields argument handling #574

**Comment by MacleodKen** [comment]
I'm no longer experiencing this problem after updating today.
