### ISSUE TITLE
[Errno 24] Too many open files. (E01 image)

### ISSUE THREAD

**Issue by Sid-Vishez** [log2timeline/plaso#580]
Try to start windows version 1.4.0 to parse E01 image (638 files, every file is 1500Mb in size) with parameters:

```
log2timeline.exe --logfile grig1000.log -z Europe/Moscow --parsers win7 --partition all --vss_stores all grig1000.plaso "e:\grig-1000\1tb-1-grig.E01"
Checking availability and versions of pals dependencies.

[OK]
```
And in grig1000.log i see the error:
`2016-02-11 15:32:38,023 [WARNING] (MainProcess) PID:5984 <<string>> Unable to scan source with error: Unable to process source path specification with error: [Errno 24] Too many open files: u'e:\\grig-1000\\1tb-1-grig.EPS'.`

**Comment by joachimmetz** [comment]
This is a known issue. You have the following options:

* increase the number of open file handles on you system
* use ewfmount to expose the image within the EWF files.
* reduce the number of EWF segment files

**Comment by joachimmetz** [comment]
Closing issue.
