### ISSUE TITLE
Status View may not be working properly (v1.4.1_20160131)

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#581]
Instead of the status view window staying put in the screen with asynchronous updating (as has been the case to current), now with Plaso (v1.4.1_20160131) I see scrolling processing output like the below, with sporadic screen refresh/reprints of the status window amidst it all:

> libfdata_stream_get_segment_index_at_offset: segment: 000       mapped range: 0x00000000 - 0x3b9e656000 (size: 256060514304)
libfdata_stream_get_segment_index_at_offset: segment: 000       file index: 000 offset: 0x00000000 - 0x3b9e656000 (size: 256060514304)

> libfdata_stream_seek_offset: seeking offset: 88095043584.
libfdata_stream_get_segment_index_at_offset: requested offset: 0x1482dfb000
libfdata_stream_get_segment_index_at_offset: segment: 000       mapped range: 0x00000000 - 0x3b9e656000 (size: 256060514304)
libfdata_stream_get_segment_index_at_offset: segment: 000       file index: 000 offset: 0x00000000 - 0x3b9e656000 (size: 256060514304)

> libfdata_stream_seek_offset: seeking offset: 31558762496.
libfdata_stream_get_segment_index_at_offset: requested offset: 0x7590c8000
libfdata_stream_get_segment_index_at_offset: segment: 000       mapped range: 0x00000000 - 0x3b9e656000 (size: 256060514304)
libfdata_stream_get_segment_index_at_offset: segment: 000       file index: 000 offset: 0x00000000 - 0x3b9e656000 (size: 256060514304)

> libfdata_stream_seek_offset: seeking offset: 126354735104.
libfdata_stream_get_segment_index_at_offset: requested offset: 0x1d6b544000
libfdata_stream_get_segment_index_at_offset: segment: 000       mapped range: 0x00000000 - 0x3b9e656000 (size: 256060514304)
libfdata_stream_get_segment_index_at_offset: segment: 000       file index: 000 offset: 0x00000000 - 0x3b9e656000 (size: 256060514304)

> libfdata_stream_seek_offset: seeking offset: 126354751488.
libfdata_stream_get_segment_index_at_offset: requested offset: 0x1d6b54800
....

**Comment by jpoling-dswrx** [comment]
Currently running FC21 with CERT Repo latest updates.

**Comment by joachimmetz** [comment]
Looks like libfdata has debug/verbose output compiled in. Check your builds of libyal.

**Comment by joachimmetz** [comment]
Closing issue, does not seem to be a plaso specific issue.

**Comment by jpoling-dswrx** [comment]
I've not personally compiled libyal, only installed via CERT Forensics Repo. It comes this way. Perhaps this can be addressed via the builds in that Repo?

**Comment by joachimmetz** [comment]
The configs of the "CERT Forensics Repo" builds should be available, though I did not spotted a separate libfdata build and if it was an embedded libfdata showing debug output I would expect more additional output from other embedded libraries as well.

Can you check if the following yields output:
```
ldconfig --print | grep libfdata
```

**Comment by jpoling-dswrx** [comment]
No output from the above command.

**Comment by jpoling-dswrx** [comment]
Any further ideas on this?

**Comment by joachimmetz** [comment]
have you checked with "CERT Forensics Repo" if they have updates?

this seems to point to an issue in the builds installed on your system, not much we can do about within plaso.

**Comment by jpoling-dswrx** [comment]
Yep, checking with them as we speak.
