### ISSUE TITLE
OS X installer does not work

### ISSUE THREAD

**Issue by querist** [log2timeline/plaso#586]
It complains about an unexpected DO on line 31 of the install.sh script.

Also, after reading the script and running the commands manually as root, I encountered another problem. I believe it was the google analytics install did not set permissions correctly, it was set at 640 and thus you could only run log2timeline.sh as root. When I changed the permissions to 644 it ran as a normal user.

Running OS X 10.10 (Yosemite).

Also, since I don't know where to ask, is it possible to add to a plaso store after initial creation? I had something crash reading a strange evtx file so I want to read the evtx files one at a time to add the data.

Thanks!

**Comment by querist** [comment]
If you don't have a mac, I will be happy to help with OS X testing. This is an important tool that I plan to incorporate into my Master's level (MSc) forensics course that I teach at my university.

**Comment by Onager** [comment]
This is #554 which is fixed the current head Plaso.

**Comment by querist** [comment]
Thanks for the update. I pulled the head last night and after building I tried to run and it complained about dfvfs.lib being missing, so I downloaded the installer and tried that and encountered the problem listed in this ticket.

Thanks for the update. I'll uninstall (as soon as I figure out how), pull the head and try it again.
