### ISSUE TITLE
psort v1.4 --slice not working

### ISSUE THREAD

**Issue by mgardner99** [log2timeline/plaso#598]
Running psort.py or psort.exe with the "--slice" parameter does not return a time slice. The command appears to be ignored and returns the full timeline output. This issue does not appear in v1.3.

**Comment by joachimmetz** [comment]
Thanks for the report, we'll have a look if we can reproduce it and a fix in place.

**Comment by joachimmetz** [comment]
Pending fix for 1.4.1: https://codereview.appspot.com/288280043/

**Comment by joachimmetz** [comment]
A fix will be integrated in upcoming 1.4.1 release
