### ISSUE TITLE
Potential compatibility issue with EnCase 7.08 EWF files

### ISSUE THREAD

**Issue by kmbMA** [log2timeline/plaso#599]
I have had this same problem on the last two sets of E01 files I tried to build a timeline on. The operating system of the E01 files is Windows 7. The version of timeline is 1.4. I am not selecting any VSS files, I even tried only running timeline against the MFT but it fails on only that file as well.
The error below happens right before it stops running:

2016-02-19 09:34:43,798 [ERROR] (MainProcess) PID:3398 <multi_process> Process Collector (PID: 3408) is not functioning correctly. Status code killed.
2016-02-19 09:34:43,798 [WARNING] (MainProcess) PID:3398 <multi_process> Processing aborted with engine error: Collector unexpectedly terminated.

I'm happy to send the debug log it created but didn't want to post online.

**Comment by joachimmetz** [comment]
@kmbMA seeing you closed this issue I assume you intended to report it a part of another issue?

**Comment by kmbMA** [comment]
Joachim,

As it turns out the issue was with the E01 files. It appears that when I create E01 files with EnCase version 7.08, Plaso can’t process them. But when I go back to version 7.06 it has no problems.

We have seen similar problems in other tools. Sorry for the confusion.

Thank you,
Kevin Brisson | Corporate Investigative Services | Global Security Organization | Desk 508-898-7085 | Cell 508-331-3347 | Kevin.Brisson@emc.com<mailto:Kevin.Brisson@emc.com> | EMC ² Where Information Lives
Disclaimer: The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by joachimmetz** [comment]
Can you provide me with some sample files of both versions, that could be useful in seeing what was changed.

**Comment by joachimmetz** [comment]
No update from OP, closing issue
