### ISSUE TITLE
Improve psort and analysis end-to-end testing

### ISSUE THREAD

**Issue by jpoling-dswrx** [log2timeline/plaso#600]
The following command yields the following error:

`psort.py -d --analysis tagging --tagging-file tag_Windows7.txt -w NEW_2016_Tagged.csv -o l2tcsv -z UTC NEW.dump "date > '2016-01-01 00:00:00'" --logfile /NEW_2016_Tagged.log`

> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/multiprocessing/queues.py", line 266, in _feed
>     send(obj)
> IOError: [Errno 32] Broken pipe
> Report generated from: tagging
> Generated on: 2016-02-19T17:08:13+00:00
> Filter String: date > '2016-01-01 00:00:00'
> 
> Report text:
> Tagging plugin produced 0 tags.
> 
> Processing completed.

Tail of the logfile has the following:

> ...
> "[DEBUG] Returned state to INITIAL
> [DEBUG] Storing state 'INITIAL'
> [DEBUG] Storing attribute 'timestamp_desc'
> [DEBUG] Storing operator 'contains'
> [DEBUG] Storing state 'ARG'
> [DEBUG] Returned state to ARG
> [DEBUG] Storing argument: Printed
> [DEBUG] Adding ['data_type', 'metadata:hachoir']
> [DEBUG] Adding ['data_type', 'olecf:summary_info']
> [DEBUG] Adding [<plaso.lib.objectfilter.Equals object at 0x7f11c6e73550>, <plaso.lib.objectfilter.Equals object at 0x7f11c6e73710>]
> [DEBUG] Adding ['timestamp_desc', 'Printed']
> [DEBUG] Adding [<plaso.lib.objectfilter.OrFilter object at 0x7f11c6e736d0>, <plaso.lib.objectfilter.Contains object at 0x7f11c6e737d0>]
> [INFO] Starting analysis plugins.
> [INFO] Plugin: [tagging] started.
> [INFO] Analysis plugins running
> [DEBUG] ConsumeItems exiting with exception <class 'plaso.lib.errors.QueueEmpty'>.
> [INFO] Processing data from analysis plugins.
> [INFO] Waiting for analysis plugin: tagging to complete.
> [INFO] Plugin tagging has completed.
> [INFO] All analysis plugins are now completed.
> [DEBUG] ConsumeItems exiting with exception <class 'plaso.lib.errors.QueueEmpty'>.
> [DEBUG] [Storage] Closing the storage, number of events added: 0"

Nothing useful in dmesg.

I re-ran the above command without the tagging plugin (sans the `--analysis tagging --tagging-file <file>`) to rule out a general psort error and it completed successfully.

**Comment by Onager** [comment]
Interesting. I'll have to try and replicate this. A couple of things to try:

1. Does it happen without the filter?
1. Does the error also occur with --use-zeromq?
1. Does changing the output mode help (try with -o null)?

**Comment by jpoling-dswrx** [comment]
1. No, it does not. Please refer to the last sentence of my original post.
2. I will try that now.
3. Same as above.

**Comment by Onager** [comment]
I meant the filter "date > '2016-01-01 00:00:00'" , not the tagging.

**Comment by jpoling-dswrx** [comment]
Filtering completes fine without tagging. I'm just using the filter to reduce the time spent and output files in testing.

**Comment by jpoling-dswrx** [comment]
Ran with zeromq, produced an error, output below...

`psort.py -d --use-zeromq --analysis tagging --tagging-file tag_Windows7.txt -w NEW_2016_Tagged_zeromq.csv -o l2tcsv -z UTC NEW.dump "date > '2016-01-01 00:00:00'" --logfile NEW_2016_Tagged_zeromq.log`
> /home/PATH/checkrc.pxd(15)zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5934)()
(Pdb) bt
  /bin/psort.py(642)ProcessStorage()
-> self._ProcessStorage()
  /bin/psort.py(267)_ProcessStorage()
-> time_slice=self._time_slice, use_time_slicer=self._use_time_slicer)
  /usr/lib/python2.7/site-packages/plaso/frontend/psort.py(526)ProcessStorage()
-> time_slice=time_slice)
  /usr/lib/python2.7/site-packages/plaso/frontend/psort.py(414)ProcessEventsFromStorage()
-> self._AppendEvent(event_object, output_buffer, analysis_queues)
  /usr/lib/python2.7/site-packages/plaso/frontend/psort.py(79)_AppendEvent()
-> event_queue.ProduceItem(event_object)
  /usr/lib/python2.7/site-packages/plaso/engine/queue.py(180)ProduceItem()
-> self._queue.PushItem(item)
  /usr/lib/python2.7/site-packages/plaso/engine/zeromq_queue.py(363)PushItem()
-> self._zmq_socket.send_pyobj(item)
  /usr/lib64/python2.7/site-packages/zmq/sugar/socket.py(351)send_pyobj()
-> return self.send(msg, flags)
  /home/PATH/socket.pyx(571)zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5319)()
  /home/PATH/socket.pyx(618)zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5086)()
  /home/PATH/socket.pyx(181)zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2081)()
> /home/PATH/checkrc.pxd(15)zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5934)()

**Comment by jpoling-dswrx** [comment]
Ran with `-o null` output, same results as before - broken pipe. 

> psort.py -d --analysis tagging --tagging-file tag_Windows7.txt -o null -z UTC NEW.dump "date > '2016-01-01 00:00:00'" --logfile NEW_2016_Tagged_null.log
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe
Report generated from: tagging
Generated on: 2016-02-22T19:10:55+00:00
Filter String: date > '2016-01-01 00:00:00'

Report text:
Tagging plugin produced 0 tags.

Processing completed.

*********************************** Counter ************************************
      Stored Events : 2001846
Events Filtered Out : 1831501
    Events Included : 170345
 Duplicate Removals : 57225
      Total Reports : 1
    Report: tagging : 1
     Filter By Date : 0
--------------------------------------------------------------------------------

Log file output...

> [DEBUG] Writing to ZIP file with buffer size: 205520896
[DEBUG] Storing state 'INITIAL'
[DEBUG] Storing attribute 'data_type'
[DEBUG] Storing operator 'is'
[DEBUG] Storing state 'ARG'
[DEBUG] Returned state to ARG
[DEBUG] Storing argument: windows:prefetch
[DEBUG] Adding ['data_type', 'windows:prefetch']
[DEBUG] Storing state 'INITIAL'
[DEBUG] Storing attribute 'data_type'
...
>[DEBUG] Storing argument: Printed
[DEBUG] Adding ['data_type', 'metadata:hachoir']
[DEBUG] Adding ['data_type', 'olecf:summary_info']
[DEBUG] Adding [<plaso.lib.objectfilter.Equals object at 0x7fd82601a750>, <plaso.lib.objectfilter.Equals object at 0x7fd82601a910>]
[DEBUG] Adding ['timestamp_desc', 'Printed']
[DEBUG] Adding [<plaso.lib.objectfilter.OrFilter object at 0x7fd82601a8d0>, <plaso.lib.objectfilter.Contains object at 0x7fd82601a9d0>]
[INFO] Starting analysis plugins.
[INFO] Plugin: [tagging] started.
[INFO] Analysis plugins running
[DEBUG] ConsumeItems exiting with exception <class 'plaso.lib.errors.QueueEmpty'>.
[INFO] Processing data from analysis plugins.
[INFO] Waiting for analysis plugin: tagging to complete.
[INFO] Plugin tagging has completed.
[INFO] All analysis plugins are now completed.
[DEBUG] ConsumeItems exiting with exception <class 'plaso.lib.errors.QueueEmpty'>.
[DEBUG] [Storage] Closing the storage, number of events added: 0

**Comment by joachimmetz** [comment]
@Onager let's revisit this issue and see if it still persists

**Comment by Onager** [comment]
We need more end-to-end test for psort and analysis plugins in general, but this is unlikely to make the December release. Moving to Jan.

**Comment by Onager** [comment]
Tests are up and running.
