### ISSUE TITLE
psort: fields argument not handled correctly

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#610]
Have just update to the recent development I have tried to use psort to output to sqlite but getting the error 
```
root@dft:~# psort.py -d -o 4n6time_sqlite  -w testlog.sqlite testlog
[ERROR] Unsupported option: fields string type required.
```

I have used the same command on all previous versions and it worked perfectly. Has this output option been disabled?

**Comment by joachimmetz** [comment]
It was not disabled but there were recent related changes: https://github.com/log2timeline/plaso/commit/8ed2c8a66d58970c0e407a371927f537ef629de9 for more consistent behavior around the fields parameter. Looks like it was not entirely fixed yet.
