### ISSUE TITLE
Question: How to use custom winevt-kb.db + tags (in combination with Elasticsearch)

### ISSUE THREAD

**Issue by rodgermoore** [log2timeline/plaso#635]
VMware Workstation 12 on a WIndows 10 host system.
Guest is Ubuntu 14.04 with latest updates.
4 CPU threads, 8 Gigs mem.
Plaso 1.4

I made an E01 image of my Win10 256 SSD containing WIndows 10 (Dutch) using Guymager (Encase 6 format). It contains 3 VSS copies. I run log2timeline using:

```` log2timeline.py --workers 8 --status_view window --logfile /home/rodger/log2timeline09030216.log /home/rodger/samsung_ssd_09032016.plaso /mnt/ewf/ewf1 ````

I created a custom winevt-kb.db file using https://github.com/libyal/winevt-kb on the same E01. Renamed the old winevt-kb.db to winevt-kb.db.backup but kept it in the same directory. I copied the winevt-kb.db file to /usr/share/plaso. I output psort to Elasticsearch 1.7 so I can use Kibana as my frontend. The command used is: 

```` psort.py --language nl-nl --data /usr/share/plaso/ -o elastic --case_name plaso-systemx05032016 samsung_ssd_09032016.plaso ````

Yet I am missing message_string fields coming from the eventid's as described here http://blog.kiddaland.net/2015/04/windows-event-log-message-strings.html

Second. Tagging using defaults:
```` psort.py -w /dev/null --analysis tagging samsung_ssd_09032016.plaso ````

This does not result in tags in Elasticsearch (in the tag field)? To be complete, I first used the tagging plugin before using the psort command to send it to Elasticsearch.

What am I doing wrong?

**Comment by joachimmetz** [comment]
Could it be that you're running into one of the elastic search related issues? https://github.com/log2timeline/plaso/issues/607

**Comment by joachimmetz** [comment]
No update from OP, closing issue
