### ISSUE TITLE
Add Messages application sqlite plugin

### ISSUE THREAD

**Issue by MacleodKen** [log2timeline/plaso#637]
I'm developing an sqlite parser for Apple's Messages application.

In OSX the database is located in `/Users/<user>/Library/Messages/chat.db`

In iOS the database is in `/var/mobile/Library/SMS/sms.db`

**Comment by joachimmetz** [comment]
Great I've sent you an invite to add you to the plaso contributors github group. Once you've accepted that I'll assign this github issue to you.

**Comment by MacleodKen** [comment]
Help please:
`Create aborted - unable to determine github access token`
My ~/.netrc looks like this:
`machine github.com login Access Token: <40-digit code>`
What have I done wrong?

**Comment by MacleodKen** [comment]
code review started https://codereview.appspot.com/283670044

**Comment by Onager** [comment]
This is is done now - thanks again Ken!
