### ISSUE TITLE
Survey users to see which functionality is most used.

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#642]

**Comment by joachimmetz** [comment]
+1

**Comment by rodgermoore** [comment]
:+1:

**Comment by rough007** [comment]
Here is my dictionary of log2timeline parsing options for Windows, Linux and Mac images/artifacts
parse_options14 = {
	'win' : "appcompatcache,bagmru,binary_cookies,ccleaner,chrome_cache,chrome_cookies,chrome_extension_activity,chrome_history,chrome_preferences,explorer_mountpoints2,explorer_programscache,filestat,firefox_cache,firefox_cache2,firefox_cookies,firefox_downloads,firefox_history,google_drive,java_idx,mcafee_protection,mft,microsoft_office_mru,microsoft_outlook_mru,mrulist_shell_item_list,mrulist_string,mrulistex_shell_item_list,mrulistex_string,mrulistex_string_and_shell_item,mrulistex_string_and_shell_item_list,msie_zone,msiecf,mstsc_rdp,mstsc_rdp_mru,opera_global,opera_typed_history,prefetch,recycle_bin,recycle_bin_info2,rplog,safari_history,symantec_scanlog,userassist,usnjrnl,windows_boot_execute,windows_boot_verify,windows_run,windows_sam_users,windows_services,windows_shutdown,windows_task_cache,windows_timezone,windows_typed_urls,windows_usb_devices,windows_usbstor_devices,windows_version,winevt,winevtx,winfirewall,winiis,winjob,winrar_mru,winreg,winreg_default",
	'lin' : "binary_cookies,bsm_log,chrome_cache,chrome_preferences,filestat,firefox_cache,firefox_cache2,java_idx,mac_appfirewall_log,mcafee_protection,opera_global,opera_typed_history,popularity_contest,selinux,symantec_scanlog,utmp,utmpx,plist_default,safari_history,chrome_cookies,chrome_extension_activity,chrome_history,firefox_cookies,firefox_downloads,firefox_history,google_drive",
	'mac' : "binary_cookies,bsm_log,chrome_cache,chrome_preferences,filestat,firefox_cache,firefox_cache2,java_idx,mac_appfirewall_log,mac_keychain,mac_securityd,mactime,mcafee_protection,opera_global,opera_typed_history,plist,popularity_contest,selinux,utmp,utmpx,airport,apple_id,macosx_install_history,plist_default,spotlight,spotlight_volume,time_machine,appusage,chrome_cookies,chrome_extension_activity,chrome_history,firefox_cookies,firefox_downloads,firefox_history,google_drive,ls_quarantine,mackeeper_cache",

**Comment by joachimmetz** [comment]
@Onager let's include a section about the codelabs

**Comment by joachimmetz** [comment]
Work in progress, closing issue.

**Comment by rodgermoore** [comment]
Hey guys, I did the survey. Final (optional) question is about contact info. I filled in my e-mail address assuming it was for you guys only. After the survey you get to view all results exposing this contact info. Is it possible to keep the contact info out of the survey results summary page visible to everybody for privacy and spam reasons? Tnx

**Comment by Onager** [comment]
Sadly we can't just suppress one question from the summary page. I've
turned off the ability for respondents to see the summary results
altogether.
