### ISSUE TITLE
Replace object filter by efilter

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#646]
* [x] package https://github.com/google/dotty [@joachimmetz]
  * ~~https://codereview.appspot.com/294740043/~~
  * ~~https://codereview.appspot.com/290200043/~~
  *  ~~add to GIFT PPA~~
  * ~~https://codereview.appspot.com/283670043/ - changes for bdist_msi~~
  * ~~https://codereview.appspot.com/283680043/ - small changes for dpkg~~
  *  ~~add to l2tdevtools~~
  *  ~~add to l2tbinaries~~
* [x] ~~[replace tagging filter implement (object filter) with an efilter equivalent](https://codereview.appspot.com/293550043/)~~ @Onager

**Comment by Onager** [comment]
Code review: https://codereview.appspot.com/293550043/

**Comment by joachimmetz** [comment]
Updates to l2tdevtools to build efilter with setuptools epoch in version:
https://codereview.appspot.com/298690043/

Also updated packages on GIFT dev
