### ISSUE TITLE
Excluding parsers error

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#647]
When running the --parsers option where the first parser is excluded using the "-" character, windows seems to see this as a command line flag instead of an argument to the --parsers.

> log2timeline.py C:\Output C:\Input --parsers -chrome
> 
> usage: log2timeline.py [-h] [-V] [--use_zeromq] [--hashers HASHER_LIST]
>                        [--parsers PARSER_LIST] [-p] [--use_old_preprocess]
>  ...
> log2timeline.py: error: argument --parsers: expected one argument

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/648

https://codereview.appspot.com/293180043/
