### ISSUE TITLE
Filtering plugins within --parsers cli argument.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#648]
There is no way filter by individual plugins. Whenever I attempt to filter by a single plugin it runs all of the parent parser's plugins.

For example, the following will run all of the sqlite_plugins:
> log2timeline.py C:\Output C:\Input --parsers sqlite,-sqlite/appusage
> log2timeline.py C:\Output C:\Input --parsers appusage

Also the following commands will run no parsers at all.
> log2timeline.py C:\Output C:\Input --parsers sqlite/appusage
> log2timeline.py C:\Output C:\Input --parsers sqlite,-appusage 

I am not sure if this is the intended behavior. This is a similar issue to #125

**Comment by dc3-plaso** [comment]
I can work on this if you would like.

**Comment by joachimmetz** [comment]
@dc3-plaso thanks, please do
