### ISSUE TITLE
Incorrect URL on Developers Guide Wiki page

### ISSUE THREAD

**Issue by lautriv** [log2timeline/plaso#652]
On https://github.com/log2timeline/plaso/wiki/Developers-Guide the link for installing Windows dependencies is incorrect. 

It is currently pointing to https://github.com/log2timeline/plaso/wiki/Dependencies---Ubuntu, but likely should point to https://github.com/log2timeline/plaso/wiki/Dependencies-Windows

**Comment by joachimmetz** [comment]
Thanks for reporting, I've updated the URL

https://github.com/log2timeline/plaso/wiki/Developers-Guide/_compare/5ddf4594554d013093a01b576fda248ec1a1a339...beb6466560d998b2c175bf61bfefd5888a177a2f
