### ISSUE TITLE
refactor SAM users winreg plugin

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#653]
**Description of problem:**

https://github.com/log2timeline/plaso/blob/00a201ea602ac2e57947a377c85073d53f15972a/plaso/parsers/winreg_plugins/sam_users.py#L152

The SAM users winreg plugin current assumes account creation times based on the key last written time:
- [ ] change parser to produce event objects with last written time
- [ ] move the determination of the account creation times to an analysis plugin

**Comment by Onager** [comment]
Complete in https://github.com/log2timeline/plaso/pull/2584
