### ISSUE TITLE
Exporting Timeline with Tags (re: Issue #572)

### ISSUE THREAD

**Issue by NoahJaehnert** [log2timeline/plaso#654]
Hi there,

I believe I am running into the same issue as the others in Issue #572. Using the SANS DIFR 3.0 workstation, updated to the latest repos/info/etc. (via update-sift), I get the same "AttributeError: 'str' object has no attribute 'tags'" error. 

I've pulled the latest code via Github, but am still running into the same issue. Is there another location I should be looking for the fix? 

Thanks!

**Comment by joachimmetz** [comment]
Can you please provide us with the information requested in the issue template. We'll need more detail to guide you in the right direction. Running the development version (latest code via Github) should work.

**Comment by NoahJaehnert** [comment]
Sure, here are the details: 

Plaso Version: 1.4.0. (Just to confirm, after pulling the latest github code via git pull, I ran plaso/tools/psort.py -V and received the following response: psort version 1.4.0"

Operating system Plaso is running on: SANS SIFT Workstation 3.0. Based on Ubuntu 14.04.4 LTS

Installation method: Installed from Github

Description of problem: Please see my first comment above. 

Debug output/tracebacks: 

Debug output/tracebacks:
[ERROR] 'str' object has no attribute 'tags'
> /usr/lib/python2.7/dist-packages/plaso/output/dynamic.py(250)_FormatTag()
-> return u' '.join(tag.tags)

Source data: pinfo.py output below: 

 --------------------------------------------------------------------------------
		Plaso Storage Information
--------------------------------------------------------------------------------
Storage file:		timeline.working
Serialization format:	json
Source processed:	N/A
Time of processing:	2016-03-22T21:40:21+00:00

Collection information:
	parser_selection = win7
	recursive = False
	preferred_encoding = UTF-8
	os_detected = Windows
	workers = 0
	output_file = timeline.plaso
	method = imaged processed
	preprocess = True
	version = 1.4.0
	cmd_line = /usr/bin/log2timeline.py timeline.plaso dd.img
	debug = False
	runtime = multi process mode
	parsers = bencode, binary_cookies, chrome_cache, chrome_preferences, custom_destinations, esedb, filestat, firefox_cache, java_idx, lnk, mcafee_protection, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, prefetch, recycle_bin, sccm, skydrive_log, skydrive_log_old, sqlite, symantec_scanlog, winevtx, winfirewall, winjob, winreg
	configured_zone = MST7MDT
	protobuf_size = 0

Parser counter information:
	Counter: total = 1836651
	Counter: filestat = 765991
	Counter: winreg/winreg_default = 725970
	Counter: pe = 164127
	Counter: msiecf = 88580
	Counter: winevtx = 68103
	Counter: sqlite/chrome_history = 3314
	Counter: olecf/olecf_default = 2715
	Counter: winreg/appcompatcache = 2624
	Counter: winreg/bagmru/shell_items = 2085
	Counter: winreg/windows_services = 1930
	Counter: chrome_cache = 1769
	Counter: olecf/olecf_summary = 1679
	Counter: lnk = 1455
	Counter: lnk/shell_items = 1320
	Counter: winreg/bagmru = 802
	Counter: winreg/explorer_programscache/shell_items = 585
	Counter: custom_destinations/lnk/shell_items = 573
	Counter: olecf/olecf_document_summary = 535
	Counter: olecf/olecf_automatic_destinations/lnk = 409
	Counter: custom_destinations/lnk = 313
	Counter: winreg/windows_task_cache = 272
	Counter: winreg/userassist = 214
	Counter: esedb/msie_webcache = 201
	Counter: winreg/msie_zone = 156
	Counter: olecf/olecf_automatic_destinations/lnk/shell_items = 141
	Counter: sqlite/chrome_cookies = 129
	Counter: winreg/mrulistex_shell_item_list/shell_items = 108
	Counter: winreg/windows_usb_devices = 98
	Counter: olecf/olecf_automatic_destinations = 89
	Counter: chrome_preferences = 53
	Counter: winreg/windows_usbstor_devices = 52
	Counter: winreg/microsoft_office_mru = 39
	Counter: winreg/windows_run = 37
	Counter: winreg/explorer_mountpoints2 = 36
	Counter: winreg/explorer_programscache = 32
	Counter: winreg/mrulistex_string_and_shell_item_list/shell_items = 15
	Counter: winreg/mrulist_string = 15
	Counter: winreg/mrulistex_string_and_shell_item = 10
	Counter: winreg/ccleaner = 10
	Counter: winreg/windows_typed_urls = 9
	Counter: winreg/mrulistex_string = 9
	Counter: winreg/windows_version = 8
	Counter: winjob = 8
	Counter: winreg/windows_boot_execute = 8
	Counter: java_idx = 8
	Counter: winreg/mrulistex_shell_item_list = 5
	Counter: winreg/windows_shutdown = 4
	Counter: winreg/windows_timezone = 4
	Counter: winreg/microsoft_outlook_mru = 1
	Counter: winreg/mrulistex_string_and_shell_item_list = 1

Preprocessing information omitted (to see use: --verbose).

-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
--------------------------------------------------------------------------------
		Plaso Storage Information
--------------------------------------------------------------------------------
Storage file:		timeline.working
Serialization format:	json
Source processed:	timeline.working
Time of processing:	2016-03-24T12:28:03+00:00

Collection information:
	parser_selection = win7
	preprocess = True
	recursive = False
	preferred_encoding = UTF-8
	os_detected = Windows
	configured_zone = MST7MDT
	output_file = timeline.plaso
	method = Running Analysis Plugins
	Action = Adding tags to storage.
	version = 1.4.0
	cmd_line = /usr/bin/psort.py -o null --analysis tagging --tagging-file tag_windows.txt timeline.working
	plugins = [u'tagging']
	debug = False
	runtime = multi process mode
	parsers = bencode, binary_cookies, chrome_cache, chrome_preferences, custom_destinations, esedb, filestat, firefox_cache, java_idx, lnk, mcafee_protection, msiecf, olecf, openxml, opera_global, opera_typed_history, pe, plist, prefetch, recycle_bin, sccm, skydrive_log, skydrive_log_old, sqlite, symantec_scanlog, winevtx, winfirewall, winjob, winreg
	workers = 0
	protobuf_size = 0

Parser counter information:
	Counter: Total Tags = 5754
	Counter: application_execution = 2828
	Counter: action_success = 982
	Counter: job_success = 964
	Counter: file_download = 366
	Counter: login_attempt = 160
	Counter: logoff = 127
	Counter: name_resolution_timeout = 120
	Counter: shell_start = 72
	Counter: time_change = 59
	Counter: system_sleep = 32
	Counter: document_print = 28
	Counter: shutdown = 13
	Counter: system_start = 13
	Counter: session_disconnection = 3

Store information:
	Number of available stores: 13
	Store information details omitted (to see use: --verbose)

Preprocessing information omitted (to see use: --verbose).

Reporting information omitted (to see use: --verbose).
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

**Comment by NoahJaehnert** [comment]
Disregard, this can be closed. I was not using the latest version from Github and once installed properly, this worked fine

**Comment by joachimmetz** [comment]
> Disregard, this can be closed.

I was in the process of replying ;)

> Plaso Version: 1.4.0. (Just to confirm, after pulling the latest github code via git pull, I ran
> plaso/tools/psort.py -V and received the following response: psort version 1.4.0")

the github plaso version is 1.4.1_<date>

did you run `sudo setup.py install --prefix=/usr`  ?

**Comment by NoahJaehnert** [comment]
I ran sudo setup.py install, but did not give the --prefix=/usr flag. Will that cause issues?

Specifically, I'm able to see that my timeline.working file contains tags via pinfo.py (as noted above), but when I run an export to CSV (via psort.py -w output_tags.csv timeline.working), it appears I get no tag information in the resulting CSV. 

Any thoughts/ideas?

**Comment by joachimmetz** [comment]
> I ran sudo setup.py install, but did not give the --prefix=/usr flag. Will that cause issues?

Yes, the installation typically ends up in /usr/local while sift installed it in /usr

So you likely now have 2 versions installed side by side. So either remove one or point python to use the correct one (e.g. by setting PYTHONPATH)

I was also planning to push a packaged version of dev to the GIFT PPA. So another alternative would be to upgrade the plaso package installed.

Also see:

* https://github.com/log2timeline/l2tbinaries/blob/master/README.md

**Comment by NoahJaehnert** [comment]
Looks like SIFT Workstation didn't like trying to install in /usr:

```
root@siftworkstation:/home/sansforensics/plaso# sudo ./setup.py install --prefix=/usr
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/lib/python2.7/site-packages/test-easy-install-4638.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python2.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```

I've added the GIFT PPA and am upgrading via that route. We'll see what happens...

**Comment by NoahJaehnert** [comment]
Still no tags even after upgrading... Here are the steps I've taken: 

1. Upgraded to latest version of everything via GIFT PPA
2. Created new timeline_new.plaso file via `log2timeline.py --status_view window --logfile NewTimeline.log timeline_new.plaso image.dd.img`
3. Tagged the timeline_new.plaso file with `psort.py -o null --analysis tagging --tagging-file tag_windows.txt test.plaso `
4. Exported the tagged results with `psort.py -w output_tags.csv timeline_new.plaso `
5. Grepped for application_execution and found nothing. 

Am I missing something here?

-Noah

**Comment by joachimmetz** [comment]
what does psort tell you after running --analysis tagging?
```psort.py --analysis tagging --tagging-file tag_windows.txt test.plaso```

E.g.
```
Report text:
Tagging plugin produced 6532 tags.

Processing completed.

*********************************** Counter ************************************
     Stored Events : 2251218
   Events Included : 2251218
Duplicate Removals : 75279
     Total Reports : 1
   Report: tagging : 1
--------------------------------------------------------------------------------
```

Or get similar info with pinfo:
```pinfo.py --verbose test.plaso```

```
Report generated from: tagging
Generated on: 2016-03-25T20:05:00+00:00

Report text:
Tagging plugin produced 6532 tags.
```

**Comment by NoahJaehnert** [comment]
Results: 

```
Report generated from: tagging
Generated on: 2016-03-25T16:14:01+00:00

Report text:
Tagging plugin produced 3130 tags.
```

**Comment by joachimmetz** [comment]
I'll try to have a look later this week if/why the tags are not showing up in the output.

**Comment by NoahJaehnert** [comment]
Please let me know if you need any further information!

**Comment by joachimmetz** [comment]
For HEAD this looks like a bug in psort. Fixes pending in https://codereview.appspot.com/298710043/
