### ISSUE TITLE
weak signing key for gift ppa

### ISSUE THREAD

**Issue by SleuthKid** [log2timeline/plaso#657]
**Plaso version:**

1.4.0 Release

**Operating system Plaso is running on:**

Ubuntu 16.04 amd64

**Installation method:**

Installed from [GiFT][https://launchpad.net/~gift]

**Description of problem:**

The packages in the gift ppa are signed with a weak pgp key. As of Ubuntu 16.04 such packages are no longer installable. You might want to consider to update the signing key. Also 16.04 now ships plaso from the universe repos and gift is no longer needed for just running plaso. 

Reference: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1558331

**Comment by joachimmetz** [comment]
Thanks for the heads up. However the signing is done by launchpad itself. So we'll need to do some digging on how to get the key changed.

https://bugs.launchpad.net/launchpad/+bug/1556666

```
Launchpad will now sign PPAs using a SHA-512 digest in the event that it needs to publish something in them anyway. We're still working on the code to re-sign all existing PPAs (the scale means that it isn't trivial), but we should be done with that soon.
```

**Comment by joachimmetz** [comment]
Marking this as wontfix seeing this is to be fixed by launchpad
