### ISSUE TITLE
l2tcsv output not working

### ISSUE THREAD

**Issue by muhamadli302** [log2timeline/plaso#659]
Hello,
My plaso version is 1.4.0, operating system Ubuntu 14.04
I installed plaso by downloading the packages and installing offline.

Here is the command I'm running:
log2timeline.py --status_view window --workers 10 --parsers win7_slow,win_gen --partition 4 --output l2tcsv /path/to/output /dev/sdb

The work takes about 2 hours, and it says it's completed withput error. But when I try to open the csv file (both in Ubuntu and in windows), it won't open, and I get the following error: "we found a problem with some content in 'output.csv', it is corrupted."

I am now running the tool again with -d flag and will post the logs as soon as I can.

Thanks

**Comment by Onager** [comment]
The output option to log2timeline is experimental, and may not work properly. Try running logtimeline to generate a storage file, then running psort to produce the CSV.

**Comment by muhamadli302** [comment]
Thanks, that solved the problem!
