### ISSUE TITLE
Warnings when parsing an EVTX file

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#66]
* [x] determine root cause
* [x] fix root cause
* [x] deploy a new version of libevtx

While parsing a test image (Windows 8.1 image from SANS) I got these warning:

```
WARNING <winevtx> [winevtx] unable to parse event record: 10613 in file: **Archive-Security-2013-10-01-20-02-28-916.evtx** with error: pyevtx_record_get_string_by_index: unable to retrieve string: **1 size**. libfwnt_security_identifier_copy_from_byte_stream: **unsupported security identifier contains more than 10 sub authoritites**. libfvalue_value_get_value_instance_by_index: unable to copy value instance from byte stream. libfvalue_value_get_utf8_string_size: **unable to retrieve value instance: 0.** libfwevt_xml_tag_get_utf8_value_size: **unable to retrieve size of UTF-8 string of value**. libevtx_record_values_get_utf8_string_size: unable to retrieve string: 1 value size. libevtx_record_get_utf8_string_size: **unable to retrieve size of UTF-8 string: 1**.
```

A bit more human readable format:
 + File: Archive-Security-2013-10-01-20-02-28-916.evtx
 + *pyevtx_record_get_string_by_index*: unable to retrieve string: 1 size.
 + *libfwnt_security_identifier_copy_from_byte_stream*: unsupported security identifier contains more than 10 sub authoritites.
 + *libfvalue_value_get_value_instance_by_index*: unable to copy value instance from byte stream.
 + *libfvalue_value_get_utf8_string_size*: unable to retrieve value instance: 0. 
 + *libfwevt_xml_tag_get_utf8_value_size*: unable to retrieve size of UTF-8 string of value.  
 + *libevtx_record_values_get_utf8_string_size*: unable to retrieve string: 1 value size.  
 + *libevtx_record_get_utf8_string_size*: unable to retrieve size of UTF-8 string: 1.

File can be easily shared.

This is either a question of improving error handling in the evtx parser or by improving the libevtx library.

**Comment by joachimmetz** [comment]
Funny:
```
Event number                    : 1397289
Written time                    : Oct 01, 2013 18:51:20.821224100 UTC
Event level                     : Information (0)
Computer name                   : Bifrost
Provider identifier             : {54849625-5478-4994-A5BA-3E3B0328C30D}
Source name                     : Microsoft-Windows-Security-Auditing
Event identifier                : 0x0000127c (4732)
Number of strings               : 10
String: 1                       : -
String: 2                       : Unable to export record: 10645
```

**Comment by joachimmetz** [comment]
http://www.selfadsi.org/deep-inside/microsoft-sid-attributes.htm hints that the maximum number is 15 and not 10. Having a look at the data.

**Comment by joachimmetz** [comment]
https://github.com/libyal/libfwnt/commit/3d370d059d31a49c02be7f1091e0b4e78814194c

**Comment by joachimmetz** [comment]
https://github.com/libyal/libevtx/releases/tag/20150928
