### ISSUE TITLE
Question: Feedback on video tutorial (series)

### ISSUE THREAD

**Issue by rodgermoore** [log2timeline/plaso#660]
Today I finished the first part of a video tutorial series on Plaso in combination with Elasticsearch, Kibana and Logstash. 

~~I will add the videoscript including all used commands, credits and shout-outs to the video description later. The video is not yet "published" as public.~~ 
Done

https://www.youtube.com/watch?v=qeFutnKoLPY

I'll make the videos as straight forward and simple as I can to make it very easy for users to install and use the combination of tools.

Please let me know your thoughts on this, thanks!

PS: Is this the right place for providing feedback or should we use the Google Discussion Group for this?

**Comment by joachimmetz** [comment]
> Please let me know your thoughts on this, thanks!

Thanks, we'll try to have a look later this week.

> PS: Is this the right place for providing feedback or should we use the Google Discussion Group for this?

Discussion mailing list might reach a larger audience.

**Comment by BannersSecret** [comment]
Hi,

Have just watched this video - very clear, easy-to-follow steps. I really hope you continue the series. 

What software did you use to put the video together and to screen capture?

Thanks,

Andrew

PS Sorry if this should be posted elsewhere.

**Comment by rodgermoore** [comment]
> Have just watched this video - very clear, easy-to-follow steps. I really hope you continue the series.
Thanks, I will. But be patient, its quite time consuming to produce.

> What software did you use to put the video together and to screen capture?
It's made with an all-in-one screen capture and editing suite called Camtasia. https://www.techsmith.com/camtasia.html

**Comment by Onager** [comment]
Hey @rodgermoore I just had a moment to watch this, and I agree with @BannersSecret - it's a very clear description of what's going on, and adding the commands in the description is a great way to help people follow along.

Do you have any thoughts on how you'd like to "release" this?

**Comment by rodgermoore** [comment]
Hi @Onager 

Tnx!

> Do you have any thoughts on how you'd like to "release" this?

I was thinking about finishing the (3 part) series first before actively pushing it. When its finished maybe you guys can mention it on [blog.kiddaland.net](http://blog.kiddaland.net) ?

**Comment by Onager** [comment]
Yep, we can do that.

**Comment by joachimmetz** [comment]
@rodgermoore and @Onager what's the status of this? Otherwise I opt mentioning it in the upcoming 1.5 release blog post?

**Comment by rodgermoore** [comment]
I'm working on the next parts.

**Comment by Onager** [comment]
This is something we can follow up as new videos are released, and doesn't block the 1.5 release.

**Comment by rodgermoore** [comment]
Hi guys,

All good intentions aside, just too many personal things happened the last 6 months to be able to support this great project. For now it doesn't seem my life is going to slow down in any way so I'm not gonna be able to follow up on this on a short term. My apologies for that.

Luckily I noticed other people jumped in to create some great tutorials about Plaso <-> Elasticsearch Kibana. 

Keep on the great work and as soon as things settle down I'll sign in again.

Cheers,

Rodger
