### ISSUE TITLE
Add support for WAL file for sqlite parser

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#664]
**Description of problem:**

Plaso does not currently support access to data within WAL files when parsing sqlite databases.

I would like to initially add support for this by providing the deduplicated results of querying the database both with and without the wal file committed. 

In the future we could then add support for parsing the wal file for intermediate records that can only be found within the wal file. (eg. record that was both created and deleted in the wal)

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/291440043/

**Comment by joachimmetz** [comment]
Moved the future enhancement ideas to: https://github.com/log2timeline/plaso/issues/775. Closing issue.
