### ISSUE TITLE
Add dpkg.log parser

### ISSUE THREAD

**Issue by berggren** [log2timeline/plaso#665]
Add parser for dpkg logs. This log contains dpkg (debian package management system) activity on the system, e.g. installation of packages.

Location: /var/log/dpkg.log

**Comment by jnettesheim** [comment]
Can we please assign to me?

**Comment by joachimmetz** [comment]
> Can we please assign to me?

Added you to the right group after accepting the invite you should be able to assign the issue to yourself.

**Comment by jnettesheim** [comment]
Code committed, ready to close issue.
