### ISSUE TITLE
Log2Timeline.py - Running: True <sleeping> <zombie> (within SANS SIFT VM)

### ISSUE THREAD

**Issue by mds7777** [log2timeline/plaso#668]
I'm running log2timeline.py in the latest SANS SIFT download (v3.0) against an E01 image within a VMWare virtual machine. It has been running, but taking extremely long. I looked at the screen output and am seeing the following message over and over: 

2016-04-13 07:40:20, 367 [INFO] (Main Process) PID: 11964 foreman Worker_1 Events extracted: 99746 - File ([windows path] - Running: True zombie 
and sometimes it says "Running: True disk-sleep" or "Running: True sleeping

Thanks

**Comment by joachimmetz** [comment]
@mds7777 if you don't provide us with the information in the bug template we can only speculate what is happening, namely that you are running an old version of plaso.

**Comment by joachimmetz** [comment]
No update from original reporter closing issue.
