### ISSUE TITLE
Mac OS-X 10.11.4 install error

### ISSUE THREAD

**Issue by bsheridan** [log2timeline/plaso#670]
**Plaso version:**
1.4

**Operating system Plaso is running on:**
OSX El Capitan 10.11.4

**Installation method:**
Downloaded from https://e366e647f8637dd31e0a13f75e5469341a9ab0ee.googledrive.com/host/0B30H7z4S52FleW5vUHBnblJfcjg/1.4.0/plaso-1.4.0-macosx-10.11.dmg

Double clicked the .dmg file, cd /Volumes/plaso-1.4.0, sudo ./install.sh

**Description of problem:**
Plaso Mac OS-X installation script
./install.sh: line 31: syntax error near unexpected token `do'

./install.sh: line 31: `do'

**Comment by joachimmetz** [comment]
Can you try: https://github.com/log2timeline/plaso/releases/download/1.4.0/plaso-1.4.0-macosx-10.11.dmg

**Comment by joachimmetz** [comment]
Related to: 

* https://github.com/log2timeline/plaso/issues/554
* https://github.com/log2timeline/plaso/issues/559

I just update the file on drive with the file on github.

**Comment by bsheridan** [comment]
Thanks @joachimmetz it worked!
