### ISSUE TITLE
Psort json vs csv

### ISSUE THREAD

**Issue by muteb** [log2timeline/plaso#671]
I see extra parameters when I use Psort to export dumps to json. Also, I can' see the MACB on json.  I would really appreciate it if anyone explains the difference? 
  

Thanks

**Comment by joachimmetz** [comment]
@muteb you'll have to be more specific.

* what parameters do you see and from where `psort.py --help` ?

**Comment by joachimmetz** [comment]
No update from original reporter closing issue.
