### ISSUE TITLE
RE in plaso/engine/worker.py to identify Chrome cache files is incorrect

### ISSUE THREAD

**Issue by NZC-2270116** [log2timeline/plaso#673]
The regular expression at https://github.com/log2timeline/plaso/blob/master/plaso/engine/worker.py#L69 that is intended to identify Chrome cache files is incorrect.

This problem was introduced on 26 December 2015 here: https://github.com/log2timeline/plaso/pull/468

The RE currently reads:

_CHROME_CACHE_DATA_FILE_RE = re.compile(r'^[fF]_[0-9]{6}$')

This incorrectly assumes that Chrome cache files contain a sequence of six decimal digits, when the digits can be hexadecimal.  Therefore cache files with names like ...

/Users/XXXX/AppData/Local/Google/Chrome/User Data/Default/Cache/f_00002a

... do not match the RE test in _CanSkipContentExtraction() leading _CanSkipContentExtraction() to return False instead of True.  

The workers then become clogged up with gzip extraction which takes a long time, leading to an abort due to workers being idle for too long.

Problem occurs in 1.4.0 release and git repo code as of 20160414 (yes I have updated my dependancies).

Changing the RE to:

  _CHROME_CACHE_DATA_FILE_RE = re.compile(r'^[fF]_[0-9a-fA-F]{6}$')

(note the added "a-fA-F")

... fixed the problem and allowed the image I was working on to complete processing successfully.

Detailed debugging info (screenshots, logs with debug enabled, etc) is available but does not seem necessary for a such a straightforward fix.

**Comment by NZC-2270116** [comment]
Seems that the underscore disappeared from those REs.  There should be an underscore in the RE between the [fF] and [0-9 as there is in the current code.

**Comment by joachimmetz** [comment]
Thanks for the report we'll have a look as soon as time permits

**Comment by NZC-2270116** [comment]
Of course  _CanSkipContentExtraction() is just a work-around to specific known cases where workers might encounter a large enough (relative to worker count) number of files that take a long time to process such that all workers appear idle and a timeout abort is triggered.

The same image that aborted on the Chrome cache files (addressed by the above fix) is now nearly aborting because most of 22 workers are processing iPhone diagnostic files which are .gz files with few events coming from them.  The only reason it doesn't abort is, due to pure luck, there are a handful of workers not processing those .gz files and generating events.

There needs to be a better (i.e. more correct and more general) way of addressing this.  That should probably involve replacing the arbitrary timeout with a more reliable way of monitoring worker health.  Perhaps workers generating null 'keepalive' events every so often which don't make it to the dump file but let other parts of the tool chain know they are still alive?  And/or maybe a more sophisticated way of monitoring worker process health?

**Comment by joachimmetz** [comment]
> There needs to be a better (i.e. more correct and more general) way of addressing this.

We are working towards this: https://github.com/joachimmetz/l2tdocs/blob/design/design/Design%20proposal%20-%20phased%20processing.asciidoc

> Perhaps workers generating null 'keepalive' events every so often which don't make it to the dump file but let other parts of the tool chain know they are still alive?

You'll still need a time out to determine when to assume the worker is dead.
