### ISSUE TITLE
Plaso and Elasticsearch Error

### ISSUE THREAD

**Issue by muhamadli302** [log2timeline/plaso#676]
Hi,

I'm running plaso 1.4 on Ubuntu 14.0.4, and elasticsearch 2.1

I'm trying ti run the following command:

psort.py -o elastic --server **ip address** --port 9200 /path/to/dump/file

and I get the following error:

pyelasticsearch.exception.ElasticHttpError (400, u'mapper_parsing_exception)

Do you know what might be the source of the problem?
Thanks.

**Comment by joachimmetz** [comment]
Likely related to https://github.com/log2timeline/plaso/issues/607

**Comment by Scalvando** [comment]
I changed the mapper to

`mapping = {
        self._doc_type: {
            u'properties': {
                u'date': {
                    u'type': u'date',
                    u'format': u'date_time_no_millis'
                },
            }
        }
    }`
And it appears to work.

**Comment by Onager** [comment]
@berggren is working on refactoring all the elasticsearch stuff, which should get this fixed.

**Comment by berggren** [comment]
This is fixed in #607
