### ISSUE TITLE
Add analysis plugin to detect time shifts

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#697]
Add analysis plugin to detect time shifts e.g. EventLogs or syslog
- think about how to integrate time shifts in dfdatetime

**Comment by Onager** [comment]
Can you elaborate on what you mean by time shifts? Do you mean if the clock has been tampered with (set back)? Or if the timezone has changed?

**Comment by joachimmetz** [comment]
* daylight savings
* ntp/time sync correction
* clock tampering
* time zone changes

**Comment by joachimmetz** [comment]
Closing as obsolete
