### ISSUE TITLE
Run review.py test and lint offline.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#705]
Running `review.py test` and `review.py lint` requires connection to github.  Would be nice run these tests while not connected online and with no upstream remote available. (ie. run tests and linting based off of a diff of the master to feature branch)

**Comment by joachimmetz** [comment]
Moved to: https://github.com/log2timeline/l2tdevtools/issues/70

**Comment by joachimmetz** [comment]
added `--offline` option to review.py pending https://codereview.appspot.com/309960043/ for update of script in plaso
