### ISSUE TITLE
Twitter for Android

### ISSUE THREAD

**Issue by hmahalik** [log2timeline/plaso#714]
**Description of problem:**
Would like a parser for Twitter for Android v 4+

**Source data:**

Account Information - /data/data/com.twitter.android/databases/global.db
SELECT 
account_name
FROM account_settings   

Notifications- /data/data/com.twitter.android/databases/<user-id>.db
SELECT
notif_id,
source_user_name,
s_name,
s_id,
notif_txt,
type AS "13=Direct Message, 5=New Follower"
FROM notifications

Contacts - /data/data/com.twitter.android/databases/<user-id>.db
SELECT
_id,
user_id,
username,
name,
datetime (profile_created/1000,'UNIXEPOCH','localtime') AS "Profile Created",
description",
web_url,
location,
followers,
friends AS "Following",
users.statuses AS "Number of Tweets",
datetime (profile_created/1000,'UNIXEPOCH','localtime') AS "Profile Created",
image_url,
datetime (updated/1000,'UNIXEPOCH','localtime') AS "Profile Updated",
datetime (friendship_time/1000,'UNIXEPOCH','localtime') AS "Became Friends"
FROM users

Statuses - /data/data/com.twitter.android/databases/<user-id>.db
SELECT
statuses._id,
statuses.author_id,
users.username,
statuses.content AS "Tweet",
datetime (statuses.created/1000,'UNIXEPOCH','localtime') AS "Tweet Time",
statuses.favorited AS "1=Yes,0=No",
statuses.retweeted AS "1=Yes,0=No"
FROM statuses
left join users on statuses.author_id = users.user_id;

Search Queries- /data/data/com.twitter.android/databases/<user-id>.db  
SELECT
name,
QUERY,
datetime (time/1000, 'UNIXEPOCH','localtime') AS "Search Time"
FROM search_queries

Media File Sharing: 
    - /root/media/0/movies/Twitter
        -_.vid
    - /root/media/0/Pictures/Twitter
        -_.jpg
    - /root/media/0/Android/data/com.twitter.android/cache/photos
        -\* 
    - /root/media/0/Android/data/com.twitter.android/cache/users
        -*
[Android.zip](https://github.com/log2timeline/plaso/files/275328/Android.zip)

**Comment by Onager** [comment]
@someguyiknow is going to take a look at this one

**Comment by aguilajesus** [comment]
Merged in #2108
