### ISSUE TITLE
Twitter for iOS

### ISSUE THREAD

**Issue by hmahalik** [log2timeline/plaso#715]
**Description of problem:**
Would like a parser for Twitter for iOS 8+

**Source data:**
Contacts private/var/mobile/Containers/Data/Application/<GUID>/Library/Caches/databases/<User>/<GUID>/twitter.db
SELECT
id,
screenName,
profileImageUrl,
name,
location,
description,
url,
following AS "1=Yes, 0=No",
followersCount,
followingCount,
datetime (createdDate,'UNIXEPOCH','localtime') AS "Account Created",
datetime (updatedAt,'UNIXEPOCH','localtime') AS "Account Updated"
FROM Users

Statusesprivate/var/mobile/Containers/Data/Application/<GUID>/Library/Caches/databases/<User>/<GUID>/twitter.db
SELECT
Statuses.text,
datetime (Statuses.date,'UNIXEPOCH','localtime') AS "Tweet Date",
Statuses.userId,
Users.name,
Statuses.retweetCount,
Statuses.favoriteCount,
Statuses.favorited AS "Favorited by User (1=Yes, 0=No)",
datetime (Statuses.updatedAt,'UNIXEPOCH','localtime')
FROM Statuses
left join Users on Statuses.userId = Users.id;

[iOS_Twitter.zip](https://github.com/log2timeline/plaso/files/275334/iOS_Twitter.zip)

Preferences 
private/var/mobile/Containers/Data/Application/<GUID>/Library/Preferences/com.atebits.Tweetie2.plist

**Comment by Onager** [comment]
@aguilajesus is on the case.

**Comment by Onager** [comment]
Code review: https://codereview.appspot.com/296280043/
