### ISSUE TITLE
Assign name for 1.5 release

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#722]
In keeping with the naming scheme, this will be the name of a Norse god or Goddess. Options:

- [Gerðr](https://en.wikipedia.org/wiki/Ger%C3%B0r), goddess of winter giving way to spring
- [Gefjun](https://en.wikipedia.org/wiki/Gefjun) goddess of ploughing.
- [Gná](https://en.wikipedia.org/wiki/Gn%C3%A1_and_H%C3%B3fvarpnir) a godess who runs errands in other worlds, and rides a flying horse

**Comment by Onager** [comment]
Assigning to @kiddinn for expert guidance.

**Comment by vnoxygen** [comment]
a flying hose.. thats something :)

**Comment by Onager** [comment]
Gná it is.
