### ISSUE TITLE
Improve Windows timezone translations

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#726]
Currently, we use https://github.com/log2timeline/plaso/blob/master/plaso/winnt/time_zones.py to do timezone mappings between Windows timezones and the pytz Olson time zones. Unfortunately, our list isn't very complete, and updating it manually is a problem.

We should look at replacing this system, probably using [tzlocal](https://github.com/regebro/tzlocal), which is dedicated to handling theses mappings.

**Comment by joachimmetz** [comment]
Marking as duplicate: https://github.com/log2timeline/plaso/issues/290

> We should look at replacing this system, probably using tzlocal, which is dedicated to handling theses mappings.

Unfortunately it is not that straight forward, since these names can change for different versions of Windows, due to historical events.
