### ISSUE TITLE
Workers Idle on CryptnetCacheUrl files

### ISSUE THREAD

**Issue by cbboggs** [log2timeline/plaso#732]
Plaso 1.4 release

Running on Ubuntu 14.04.   

Installed via SANS SIFT installer script

Scenario:
Analying a Windows 7 raw image, taken with DD.   Tested log2timeline with default options on both the raw DD by providing an offset, as well as with the image mounted to a directory.

Problem:  
Workers hang and then perma-sleep on files within CryptnetCacheUrl directories of user profiles as well as in Windows/ServiceProfiles, eventually causing the "Idle too long" feature to kick in and stop log2timeline.   I attemted running log2timeline with root privileges just in case, but it didn't help.

This failure was occurring towards the end of a run on a 500GB drive, so to test it I re-ran log2timeline against one of the specific folders I know it was having trouble with, Windows/ServiceProfiles/LocalService/AppData/LocalLow/Microsoft/CryptnetUrlCache/
These CryptnetUrlCache folders also exist in each user's profile, within the same AppData folder structure.   

Debug log:
[test.txt](https://github.com/log2timeline/plaso/files/311995/test.txt)

This appears to be similar in nature to #589

**Comment by cbboggs** [comment]
As a follow up to this issue - is there a way to exclude certain files/folders (using a manner similar to the targeted list you can provide) from log2timeline?

**Comment by Onager** [comment]
Thanks for the report! From the logs, it looks like Plaso starts hashing the files, and then the workers never come back. Given that plaso isn't parsing these files, just reading the bytes, I suspect a bug in one of the underlying storage libraries, or file system/image corruption. Some questions:

1. Have you seen this only one image, or multiple?
1. Can you copy/read the files from the image with a different tool (fls, icat etc.)?

**Comment by cbboggs** [comment]
It has only occured on this image, but then again I've only analyzed one other Windows 7 image with log2timeline before.   

I haven't attempted icat or fls, but I'm able to simply cat the majority of the files when the image is mounted..  however at least one file in each instance of this directory (either under Windows directory or users profile) would not output anything with a cat, and shows up as a 0 byte pipe stream in linux, not sure if that's significant.  

I suppose it's possible some of these are corrupted, but even if a single file is corrupted I'm confused as to why the rest of the workers would also idle out on other readable files.

**Comment by Onager** [comment]
From the debug log (thank you for a log!) I suspect what's happening here is that one worker is stuck reading from the file (perhaps seeing it as a pipe, so the worker is never able to get to the "end" of the file).  The other workers process all the other pathspecs, and then complete. Plaso waits for the stuck worker to complete, which never happens. Eventually the failsafe kicks in and kills the stuck worker.

If there are multiple files that have this same property, the same thing will happen, just with more stuck workers. We're currently working on a big refactor that should address this and similar failure cases. 

For now, I think disabling hashing will let the processing finish. Setting ```--hashers none``` will stop Plaso trying to read the whole file.

To answer your other question, there's currently no way to exclude files from parsing.

**Comment by Onager** [comment]
One request if you're up for a little lower level forensics - could run ```fsntfsinfo`` on the MFT entries that seem to be causing the problem, and share the results? It's from https://github.com/libyal/libfsntfs and there's a package for SIFT machine in the GIFT dev repository: https://launchpad.net/~gift 

Let me know if you need a more detailed description of how to do this.

**Comment by joachimmetz** [comment]
Closing issue. Behavior has changed due to https://github.com/log2timeline/plaso/issues/338

**Comment by iwm911** [comment]
Hi all,

i got the same issue. log2timeline is stuck when ever he hits a filesystem pipe.
one way of resolving it was to just delete the pipes (not very elegant).

the other way (and the way i used) was to patch "worker.py" which is located at plaso/engine/worker.py and adding 
`
    if file_entry.IsPipe():
      return
`
at line 575 just at the beginning of the method _ProcessFileEntry.

this way if the file is a pipe (which is size zero and not relevant anyway for my timeline) it will just skip it.

`
  def _ProcessFileEntry(self, file_entry, data_stream_name=u''):
    """Processes a specific data stream of a file entry.

    Args:
      file_entry: A file entry object (instance of dfvfs.FileEntry).
      data_stream_name: optional data stream name. The default is
                        an empty string which represents the default
                        data stream.

    Raises:
      RuntimeError: if the parser object is missing.
    """
    if file_entry.IsPipe():
      return
    self._current_file_entry = file_entry
    self._current_display_name = self._parser_mediator.GetDisplayName(
        file_entry)

`

**Comment by joachimmetz** [comment]
@iwm911 thanks for the feedback, I'll make some changes to skip content extraction on special files.
