### ISSUE TITLE
Clean up docstrings

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#733]
- [x] Revisit ambiguity in [style guide](https://google.github.io/styleguide/pyguide.html) regarding writing good docstrings and add to plaso [style guide](https://github.com/log2timeline/plaso/wiki/Style-guide), with examples based on the existing codebase
  - Make sure docstrings are terse, don't contain unnecessary information and don't repeat the same information multiple times
  - Make sure docstring use sphinx formatting hints
- [ ] Update docstrings in codebase

**Comment by Onager** [comment]
Updated style guide.

**Comment by Onager** [comment]
The style guide has been moved and updated. Docstring format is now enforced via the pylint docparams extension.
