### ISSUE TITLE
Can't escape "\" in psort filter expression

### ISSUE THREAD

**Issue by m-terlinde** [log2timeline/plaso#737]
**Plaso version:**
1.4.0

**Operating system Plaso is running on:**

Windows 7 x64, run the exes in Cygwin

**Installation method:**
The Windows .zip file

**Description of problem:**

I can't escape the "\" in the filter expressions. "\\\" doesn't work aswell.

**Debug output/tracebacks:**

```
$ ./psort.exe -d -z "Europe/Berlin" "PathToPalso" "message contains 'JustAString' and message contains ' User=Domain\\Username'"
[ERROR] Invalid filter expression: message contains 'JustAString' and message contains ' User=Domain\\Username'

usage: psort.exe [-h] [-V] [--analysis PLUGIN_LIST] [--use_zeromq]
                 [--logfile FILENAME] [-d] [-q] [--slice DATE]
                 [--slice_size SLICE_SIZE] [--slicer] [--data PATH] [-a]
                 [--language LANGUAGE] [-o FORMAT] [-w OUTPUTFILE]
                 [-z TIMEZONE]
                 [STORAGE_FILE] [FILTER]

```

**Source data:**

Just a simple .palso file, nothing special here.

**Comment by joachimmetz** [comment]
> Windows 7 x64, run the exes in Cygwin

try cmd.exe or double the number of backslashes \\\\

**Comment by m-terlinde** [comment]
Great, '\\\\' works on Cygwin.

Thank you very much. Never thought of so much backslashes...
