### ISSUE TITLE
Elasticsearch output module error

### ISSUE THREAD

**Issue by muhamadli302** [log2timeline/plaso#738]
Hello,

I have plaso 1.4, on Linux 14.04

I also have a remote Elasticsearch server.

Here is the command I ran and the error:
psort.py -o elastic --server IP_ADDR --port 9200 '/home/user/new_case.dump'
[INFO] Starting new HTTP connection (1) IP_ADDR
No handlers could be found for logger "elastic.trace"
Inserting data.............
[ERROR] Unable to copy 183*****(very long number) to a datetime object with error: date value out of range. [DONE]
Processing complete.

Because of that error, it only inserted about 15% of the data.
What should I do?

**Comment by joachimmetz** [comment]
Elasticsearch output module is being refactored: https://github.com/log2timeline/plaso/pull/735

I opt to try again with the development version or the next Release Candidate once that CL has been committed to the codebase.

**Comment by joachimmetz** [comment]
Changes pending https://codereview.appspot.com/301030043/

Closing issue
