### ISSUE TITLE
Issue with Chrome Cache plugin

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#74]
running against a demo Mac OS X image.

    2014-12-19 05:15:13,818 WARNING <worker> [chrome_cache] Unable to process file: type: OS,   location: /PATH/mac_malware.raw
    type: RAW
    type: TSK_PARTITION, location: /p2, part index: 5, start offset: 0x0c805000
    type: TSK, inode: 338431, location:  /Users/demouser/Library/Caches/Google/Chrome/Default/Cache/index
    with error: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128).

And with the following traceback:

    File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 123, in _ParseFileEntryWithParser
        parser_object.Parse(self._parser_context, file_entry)
    File "/usr/lib/python2.7/dist-packages/plaso/parsers/chrome_cache.py", line 420, in Parse
        cache_entry = data_file.ReadCacheEntry(cache_address.block_offset)
    File "/usr/lib/python2.7/dist-packages/plaso/parsers/chrome_cache.py", line 287, in ReadCacheEntry
        string = u''.join(map(chr, byte_array))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128)

**Comment by Onager** [comment]
@kiddinn can you clarify where this is up to?

Removing as a blocker for now.

**Comment by joachimmetz** [comment]
Looking at the data this is actually part of a PNG
```
0x00000000  01 62 4b 47 44 8f f5 02  83 f9 00 00 01 68 49 44  .bKGD........hID
0x00000010  41 54 28 91 65 d2 f5 5f  c2 40 18 06 70 64 30 15  AT(.e.._.@..pd0.
0x00000020  c5 ee 0e b0 11 c5 4e 64  f3 14 bb c1 42 c4 ee 42  ......Nd....B..B
0x00000030  c5 4e 6c f4 f9 97 bd 9b  0c 27 3e bf 3d fb 7e b6  .Nl......'>.=.~.
0x00000040  bb dd bd 2a 75 58 54 a1  c8 4f b8 d8 f4 82 e2 ec  ...*uXT..O......
0x00000050  e4 a8 70 d1 e6 d5 40 4a  4b 55 c2 1f 89 33 03 fe  ..p...@JKU...3..
0x00000060  93 dd 35 ef 25 c5 12 fe  57 e2 3b 70 eb 26 52 86  ..5.%...W.;p.&R.
0x00000070  8e 02 a8 8c 94 45 df 86  63 3b 91 33 eb 47 99 e6  .....E..c;.3.G..
0x00000080  47 b4 26 9c 10 45 26 df  90 f1 23 39 b8 b3 93 ee  G.&..E&...#9....
0x00000090  b9 05 51 14 c4 e1 f5 3e  42 56 51 c3 5e 52 73 66  ..Q....>BVQ.^Rsf
```

**Comment by joachimmetz** [comment]
Changes pending in: http://codereview.appspot.com/279660043
