### ISSUE TITLE
Replace use_old_preprocess by more UX friendly approach

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#787]
Replace use_old_preprocess by more UX friendly approach
- [ ] determine use cases to support e.g. process image first then add individual files
- [ ] use_old_preprocess will be deprecated by preprocess object refactor need to find a new solution

**Comment by Onager** [comment]
use_old_preprocess is gone now - @joachimmetz can you update this issue please? I suspect it should be closed out, and specific issues opened for individual features similar to use_old_preprocess.

**Comment by joachimmetz** [comment]
Closing this out:
* no uses cases have surfaced
* preprocessing will undergo more change
