### ISSUE TITLE
SQLite error: file is encrypted or not a database

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#797]
**Plaso version:**

https://github.com/log2timeline/plaso/commit/ebe1a0e0822587fbbb7cfd3d2233b8d763aafe27

**Operating system Plaso is running on:**

Windows 7

**Installation method:**

Development environment.

**Description of problem:**

I'm getting a "file is encrypted or not a database" error when I try to parse sqlite files. 

**Solution:**

This is being caused by the file_object being at offset 24 instead of 0 when the database is opened.
This can be fixed by adding 

```python
file_object.seek(0)
```
after line:  https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite.py#L346

This was caused because of the incorrect assumption that "GetFileObject()" returns a file_object offset at 0.

**Comment by joachimmetz** [comment]
Can you try again with https://github.com/log2timeline/plaso/commit/2be0249235ccf7a77ec6153ba7d0ac8959d99806 or later. This should have been fixed already.

**Comment by dc3-plaso** [comment]
Yup, that fixed it. Now that the file_object is seeked within the database Open(). The seek at https://github.com/log2timeline/plaso/blob/master/plaso/parsers/sqlite.py#L355  can probably be removed now.

Also, I suggest adding a seek within the _OpenWALFileObject() function for the wal_file_object.
