### ISSUE TITLE
Unicode issue with log2timeline

### ISSUE THREAD

**Issue by darrenbilby** [log2timeline/plaso#80]
Installing from ppa repo, but appears to be in head as well:
https://github.com/log2timeline/plaso/blob/master/plaso/frontend/log2timeline.py#L169

This unicode char causes a failure to run help:
```
root@49b4cfe2da62:/home/grrdemo# /usr/bin/log2timeline.py 
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 451, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 412, in Main
    arg_parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2329, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2343, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 8758: ordinal not in range(128)
```
This is on a default ubuntu 14.04 Docker image with bash. Could cause some confusion for users.

**Comment by joachimmetz** [comment]
At first glance looks like a non-Unicode encoding setting by the terminal.

What do the following commands return:
```
echo $LANG
python -c 'import sys; print(sys.stdout.encoding)'
```

**Comment by darrenbilby** [comment]
yeh, no doubt it is, but it might be more common that we think, fix is not
super hard, but probably confusing for some if its easy to fix:
root@2c3948c496c0:/home/grrdemo# echo $LANG

root@2c3948c496c0:/home/grrdemo# python -c 'import sys;
print(sys.stdout.encoding)'
ANSI_X3.4-1968

root@2c3948c496c0:/home/grrdemo# ls /usr/lib/locale/
C.UTF-8

export LC_ALL=C.UTF-8

root@2c3948c496c0:/home/grrdemo# log2timeline.py
usage: log2timeline.py [-z TIMEZONE] [-t TEXT] [--parsers PARSER_LIST] [-h]
.....

**Comment by joachimmetz** [comment]
> fix is not super hard

A correct fix maybe,

**Comment by joachimmetz** [comment]
Looks like an issue in argparse, have some ideas to fix it but will take some reworking the terminal output handling.

**Comment by joachimmetz** [comment]
reminder also fix behavior of `--parsers list` indicating an error

**Comment by joachimmetz** [comment]
The work on https://github.com/log2timeline/plaso/issues/120 should eventually solve this issue.

**Comment by joachimmetz** [comment]
Closing issue since current approach seems to handle it:
```
PYTHONPATH=. LC_ALL=C ./tools/log2timeline.py
```
```
[ERROR] Unable to properly write output due to encoding error. Switching to error tolerant encoding which can result in non Basic Latin (C0) characters to be replaced with "?" or "\ufffd".
...
Run the tool against an image (full kitchen sink)
    log2timeline.py /cases/mycase/plaso.dump ?mynd.dd
```
