### ISSUE TITLE
plaso doesn't work on logical volumes exported with F-Response

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#83]
I'm testing plaso-1.2.0-win-amd64-vs2010 on Windows 7 64bits with different kind of setup

working on physical drive of the host:
`log2timeline.exe foo1.dump \\.\PhysicalDrive0`
-> works ok

working on logical volume of the host:
`log2timeline.exe foo2.dump \\.\C:`
-> works ok

working on physical drive exported through F-Response:
`log2timeline.exe foo3.dump \\.\PhysicalDrive3`
-> works ok

working on logical volume exported through F-Response:
`log2timeline.exe foo4.dump \\.\PhysicalDrive4`
-> doesn't work

```
Traceback (most recent call last):
  File "<string>", line 451, in <module>
  File "<string>", line 433, in Main
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.frontend.frontend", line 1559, in ProcessSource
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\plaso.frontend.frontend", line 749, in ScanSource
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.helpers.source_scanner", line 418, in Scan
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.helpers.source_scanner", line 265, in _ScanNode
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.helpers.source_scanner", line 470, in ScanForStorageMediaImage
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.analyzer.analyzer", line 186, in GetStorageMediaImageTypeIndicators
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.analyzer.analyzer", line 103, in _GetTypeIndicators
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.analyzer.scanner", line 648, in ScanFileObject
  File "c:\Projects\plaso\build\log2timeline\out00-PYZ.pyz\dfvfs.file_io.os_file_io", line 151, in read
IOError: pysmdev_handle_read_buffer: unable to read data.
```

An aquisition of the volume exported on `\\.\PhysicalDrive4` with Ftk Imager Lite works fine,  I don't really know how to debug this

**Comment by joachimmetz** [comment]
What kind of device is this; iSCSI?

```
log2timeline.exe foo4.dump \\.\PhysicalDrive4
-> doesn't work
```
It means the F-Response do not behave like as expected. Maybe something to do with synchronous vs asynchronous reads? Any details on the driver you are using?

**Comment by ant1** [comment]
Yes,  it is an iSCSI device.
The driver seems to be disk.sys provided by Microsoft

**Comment by ant1** [comment]
Here is what I see with Process Monitor:

```
"Time of Day","Process Name","PID","Operation","Path","Result","Detail"
"08:47:05,0732174","log2timeline.exe","1532","CreateFile","\Device\Harddisk2\DR4","SUCCESS","Desired Access: Generic Read, Disposition: Open, Options: Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a, OpenResult: Opened"
"08:47:05,0732839","log2timeline.exe","1532","CloseFile","\Device\Harddisk2\DR4","SUCCESS",""
"08:47:05,0776838","log2timeline.exe","1532","CreateFile","\Device\Harddisk2\DR4","SUCCESS","Desired Access: Generic Read, Disposition: Open, Options: Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a, OpenResult: Opened"
"08:47:05,0777209","log2timeline.exe","1532","CloseFile","\Device\Harddisk2\DR4","SUCCESS",""
"08:47:05,0810730","log2timeline.exe","1532","CreateFile","\Device\Harddisk2\DR4","SUCCESS","Desired Access: Generic Read, Disposition: Open, Options: Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a, OpenResult: Opened"
"08:47:05,0811368","log2timeline.exe","1532","CloseFile","\Device\Harddisk2\DR4","SUCCESS",""
"08:47:05,0903110","log2timeline.exe","1532","CreateFile","\Device\Harddisk2\DR4","SUCCESS","Desired Access: Generic Read, Disposition: Open, Options: Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a, OpenResult: Opened"
"08:47:05,0903748","log2timeline.exe","1532","DeviceIoControl","\Device\Harddisk2\DR4","SUCCESS","Control: IOCTL_DISK_GET_LENGTH_INFO"
"08:47:05,0924310","log2timeline.exe","1532","DeviceIoControl","\Device\Harddisk2\DR4","SUCCESS","Control: IOCTL_DISK_GET_DRIVE_GEOMETRY_EX"
"08:47:05,0924841","log2timeline.exe","1532","DeviceIoControl","\Device\Harddisk2\DR4","SUCCESS","Control: IOCTL_DISK_GET_LENGTH_INFO"
"08:47:05,1006056","log2timeline.exe","1532","ReadFile","\Device\Harddisk2\DR4","SUCCESS","Offset: 0, Length: 512, I/O Flags: Non-cached, Priority: Normal"
"08:47:05,1080158","log2timeline.exe","1532","ReadFile","\Device\Harddisk2\DR4","IO DEVICE ERROR","Offset: 64 317 554 176, Length: 512, I/O Flags: Non-cached, Priority: Normal"
"08:47:06,2373797","log2timeline.exe","1532","CloseFile","\Device\Harddisk2\DR4","SUCCESS",""
```

The size of the volume is a bit smaller in disk management console:  64 317 550 592

**Comment by joachimmetz** [comment]
So what does \\.\PhysicalDrive4 contain a volume or a partitioned disk?

> The size of the volume is a bit smaller

How much smaller 512 bytes by any chance?

**Comment by ant1** [comment]
\\.\PhysicalDrive4 contains a volume

The size of the volume is  64 317 550 592 and log2timeline tries to read at offset 64 317 554 176,  so it's 3584 bytes after the end of the volume.

**Comment by joachimmetz** [comment]
It is more likely that the driver reports a larger size than Windows shows. Can you run the following python commands on the device:
```
import pysmdev

handle = pysmdev.handle()
handle.open('\\.\\PhysicalDrive4')
print(handle.get_media_size())
handle.close()
```

And tell me what media size is given.

**Comment by ant1** [comment]
The size given is:  64317554688L

**Comment by joachimmetz** [comment]
```
64317554688 - 64317550592 = 4096
```
Looks like 1 NTFS cluster block missing from the size shown by disk management console. Which is not uncommon behavior in Windows for NTFS volumes. So there is likely an additional 4096 bytes and Windows probably does not let you access the last 512 bytes of the volume (backup volume header). Can you verify that with the originally volume, and here it is important to have the full volume size not only the size indicated by the file system.

**Comment by ant1** [comment]
With the original volume,  pysmdev also returns a size of 64317554688L

**Comment by joachimmetz** [comment]
Thanks, and to be verbose that is from running smdevinfo against a volume device e.g. \\.C (or equiv)?

I'll have a look to see if I can add a work around for libsmdev (libcfile) to compensate for this behavior in PhysicalDevice device files as well. Also see: https://github.com/libyal/libcfile/blob/master/libcfile/libcfile_file.c#L1993

**Comment by ant1** [comment]
This is from running this on the target:
```
import pysmdev

handle = pysmdev.handle()
handle.open('\\\\.\\C:')
print(handle.get_media_size())
handle.close()
```

**Comment by joachimmetz** [comment]
Closing this issue seeing this is very likely related to https://github.com/libyal/libcfile/issues/2

**Comment by joachimmetz** [comment]
I'm closing this issue seeing this is an issue outside plaso in a dependency
