### ISSUE TITLE
Handle psort abort more gracefully

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#838]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

N/A

**Installation method:**

Dev install

**Description of problem:**

Presently, when psort is interrupted it doesn't close the session completely. When psort is started again, with the same storage file as an arg, it sees an unclosed session and aborts.  

This is problematic, as if a user has to kill psort for any reason, the storage file can't be readily processed again. Users might want to kill psort if they typo an analysis plugin flag, for example.

**Debug output/tracebacks:**

```
[WARNING] Detected unclosed session.
[INFO] Starting analysis plugins.
[INFO] Plugin: [nsrlsvr] started.
[INFO] Analysis plugins running
[ERROR] Processing stopped early: Session start: 000002 already exists..
```

**Source data:**

N/A

**Comment by joachimmetz** [comment]
Will need to make some changes to psort that were scheduled for 1.6.0 https://github.com/log2timeline/plaso/issues/366

**Comment by joachimmetz** [comment]
Abort path handling was improved. Closing issue.
