### ISSUE TITLE
Absence of datetime field in psort.py output

### ISSUE THREAD

**Issue by gvlejd** [log2timeline/plaso#846]
**Plaso version:**

1.4.1_20160721

**Operating system Plaso is running on:**

Gubuntu

**Installation method:**

git@github.com:log2timeline/plaso.git clone

**Description of problem:**

After running psort.py -w events/acserver.json -o json plaso_dump/acserver.plaso
The resulting json in events/acserver.json does not contains datetime field. This field is mandatory for timesketch.

**Debug output/tracebacks:**

**Source data:**

acserver.plaso (derived from acserver.dd) from greendale incident

**Comment by joachimmetz** [comment]
can you check with pinfo.py what the format version of acserver.plaso is

**Comment by gvlejd** [comment]
pinfo.py says
Format version : 20160715

**Comment by joachimmetz** [comment]
Can you try again running log2timeline.py and psort.py with plaso 1.4.1_20160806 or later. I just ran both and did not encounter the error.

**Comment by joachimmetz** [comment]
No update from OP closing issue.
