### ISSUE TITLE
Windows 10 $I files from RecycleBin not parsed

### ISSUE THREAD

**Issue by bethlogic** [log2timeline/plaso#866]
**Plaso version:**

For example 1.4.0 Release

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

log2timeline.py -d RECYCLE.plaso ~/Downloads/\$I103S5F.jpg --parsers recycle_bin

An $I file from Windows 10 does not get parsed.

rifiuti2 0.6 has Win 10 support, but I cannot tell if we have updated our structs for it.
https://abelcheung.github.io/rifiuti2/

**Debug output/tracebacks:**

2016-07-27 14:23:55,092 [DEBUG] (MainProcess) PID:31458 <worker> recycle_bin unable to parse file: OS:/usr/local/google/home/eschwein/Downloads/$I103S5F.jpg with error: Not an $Ixxx file, wrong magic header.

**Source data:**

$ xxd ~/Downloads/\$I103S5F.jpg 
00000000: 0200 0000 0000 0000 2f64 0300 0000 0000  ......../d......
00000010: 20a7 6179 4ed2 d101 2600 0000 4300 3a00   .ayN...&...C.:.
00000020: 5c00 5500 7300 6500 7200 7300 5c00 7200  \.U.s.e.r.s.\.r.
00000030: 6100 6e00 6400 6f00 6d00 5c00 4400 6f00  a.n.d.o.m.\.D.o.
00000040: 7700 6e00 6c00 6f00 6100 6400 7300 5c00  w.n.l.o.a.d.s.\.
00000050: 6200 7500 6e00 6e00 6900 6500 7300 2e00  b.u.n.n.i.e.s...
00000060: 6a00 7000 6700 0000                      j.p.g...

**Comment by joachimmetz** [comment]
http://dfstream.blogspot.ch/2016/04/fun-with-recycle-bin-i-files-windows-10.html
