### ISSUE TITLE
image_export error: unable to read buffer

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/plaso#869]
**Plaso version:**

7ef0b9f431cb6e3c98d0057d72bd342a57cdbb49

pysigscan version 20160312

**Operating system Plaso is running on:**

Windows 7 64bit

**Installation method:**

Dev install

**Description of problem:**

Receive libsigscan error when trying to run image_export tool with signature filter.

**Debug output/tracebacks:**

```
image_export G:\WindowsImage.vmdk --signatures evt,evtx --write G:\export --partition all --vss_stores all
Filters:
  signature identifiers: evtx, evt
2016-07-28 14:54:54,180 [INFO] Processing started.
Traceback (most recent call last):
  File "C:/dev/plaso/tools/image_export.py", line 312, in <module>
    if not Main():

...

  File "C:/dev/plaso/plaso/frontend/image_export.py", line 342, in <module>
    self._file_scanner.scan_file_object(scan_state, file_object)
IOError: pysigscan_scanner_scan_file_object: unable to scan file. libsigscan_scanner_scan_file_io_handle: unable to read buffer.
```

After adding an IOError exception catch I was able to to determine this error is only happening on the $BadClus file.

**Comment by joachimmetz** [comment]
Might  be related to https://github.com/sleuthkit/sleuthkit/issues/504

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/306890043/
