### ISSUE TITLE
Windows 10 Prefetch Files not parsed

### ISSUE THREAD

**Issue by thePidge** [log2timeline/plaso#871]
**Plaso version:**

For example 1.4.0 Release

**Operating system Plaso is running on:**

Ubuntu

**Installation method:**

For example installed from [GiFT][https://launchpad.net/~gift], built using [l2devtools][https://github.com/log2timeline/l2tdevtools], or some other method.

**Description of problem:**

log2timeline.py -d prefetch.plaso /tmp/CHROME.EXE-CCF9F3F4.pf --parsers prefetch

A Windows 10 prefetch file is not parsed. 
libscca supports Windows 10, so perhaps things on this end need updating? https://github.com/libyal/libscca/blob/master/documentation/

**Debug output/tracebacks:**
There is no error thrown, just a lack of parsing, so there's not really anything to supply. 
 

**Source data:**

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/issues/234
