### ISSUE TITLE
check_dependencies: prints out dated URL

### ISSUE THREAD

**Issue by dnides** [log2timeline/plaso#89]
there is a link "Libyal libraries can be downloaded from..." at the end of run time to the following url -

https://googledrive.com/host/0B30H7z4S52FleW5vUHBnblJfcjg/libyal.html

which does not work.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/197910043/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/plaso/commit/4df0764714d950f93d99c85b80ecdcac1648b991
