### ISSUE TITLE
"Contains" tagging operator not working correctly (efilter 1.4)

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#899]
**Plaso version:** HEAD+1 and efilter 1.4

filter file:
```
repeated		
  body contains 'last message repeated'
```

"contains" still not working: https://github.com/log2timeline/plaso/issues/820

Newly generated storage file with `./config/tests/generate_test_files.sh` does not contain event tags (tested on https://github.com/joachimmetz/plaso/tree/fixes1 with and without current work around)

```
======================================================================
FAIL: testHasEventTags (__main__.ZIPStorageFileTest)
Tests the HasEventTags function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/storage/zip_file.py", line 1207, in testHasEventTags
    self.assertTrue(storage_file.HasEventTags())
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by Onager** [comment]
You mean efilter 1.4, correct? I don't see an efilter 1.5 anywhere.

**Comment by joachimmetz** [comment]
Correct should be 1.4 not 1.5

**Comment by Onager** [comment]
The rule seems to be created OK: ```<type 'tuple'>: (Union(Membership( Literal('a message') Var('body'))), Literal('text_contains'), Literal(None))``` but isn't matching correctly.

**Comment by Onager** [comment]
Bug looks to be here: https://github.com/google/dotty/blob/ee0f320c95bc978e911313ecc7dd7d0db1ea10c2/efilter/transforms/solve.py#L771

six.string_types is ```str```, not ```(str, unicode)``` as was probably expected. I'll follow up with efilter.

**Comment by Onager** [comment]
Filed https://github.com/google/dotty/issues/22

**Comment by joachimmetz** [comment]
Looks like this is fixed now.
