### ISSUE TITLE
Counterintuitive Boolean Flag Arguments

### ISSUE THREAD

**Issue by maurermj08** [log2timeline/plaso#912]
**Plaso version:**

1.5.0 RC

**Operating system Plaso is running on:**

Na

**Installation method:**

Na

**Description of problem:**

Confusing and non canonical Boolean flag arguments in helpers elastic_output.py and virustotal_analysis.py. They use type=bool and action=u'store'. This results in the unexpected behavior of the value *False* actually being stored as *True*.  This issue is easily fixed by removing the type and changing the action to *store_true* or *store_false*.

![bool_bug](https://cloud.githubusercontent.com/assets/13810976/17640667/d715866c-60d2-11e6-9ef1-03384c45f878.PNG)

see: http://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

**Source Code**

/plaso/cli/helpers/elastic_output.py line 56 is currently:
```
    argument_group.add_argument(
        u'--raw_fields', dest=u'raw_fields', type=bool,
        action=u'store', default=cls._DEFAULT_RAW_FIELDS, help=(
            u'For all string fields add attribute that are not analyzed.'))
```

Would expect:
```
    argument_group.add_argument(
        u'--raw_fields', dest=u'raw_fields',
        action=u'store_true', help=(
            u'Adds a not analyzed attribute for all string fields.'))
```

**Comment by joachimmetz** [comment]
Thanks for the report. We'll have a look to clean this up.
