### ISSUE TITLE
Worker processing untracked task message

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#930]
**Plaso version:**

1.5 RC1 

**Operating system Plaso is running on:**

Ubuntu 14.04LTS 64 bit

**Installation method:**

GIFT

**Description of problem:**

Originally reported in #924.
Main process reports that workers as processing tasks that aren't tracked.

**Debug output/tracebacks:**
```
2016-08-14 16:37:19,049 [ERROR] (MainProcess) PID:4482 <task_engine> Worker processing untracked task: ba99f4484c7a48fa88769f7c94c1f40f.
```

**Source data:**
victoria-v8.sda1.img from a Honeynet forensics challenge here: https://www.honeynet.org/challenges/2011_7_compromised_server

**Comment by Onager** [comment]
Assigning to @joachimmetz to take a look. Note that error log is attached to #924

**Comment by joachimmetz** [comment]
I cannot reproduce, so it is likely something specific to the run. This situation could happen if the task has been idle for too long, marked as stale, and then gets updated. I'll see if I can enhance handling reviving stale tasks.

**Comment by daniel-ayers** [comment]
I will re-test to confirm it is reproducible and to see if I can get more info.

**Comment by daniel-ayers** [comment]
Reproducible for me on Ubuntu 14.04LTS (fully updated) - Virtualbox VM 12CPU 12Gb RAM on a Xeon host

Does not occur on Ubuntu 16.04LTS - HP zBook Mobile Workstation 17in G3 laptop 64Gb RAM Quad core 2.7GHz i7

Both tests running 1.5 RC1 against victoria-v8.sda1.img with default options:

```
# log2timeline --debug --logfile X.log victoria_default.plaso victoria-v8.sda1.img
```

Here's the debug log from the 1404LTS test:

[victoria_default_1404.log.gz](https://github.com/log2timeline/plaso/files/417477/victoria_default_1404.log.gz)

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/301630043/

**Comment by joachimmetz** [comment]
> Reproducible for me on Ubuntu 14.04LTS (fully updated)

As indicate likely due to longer timeouts on your configuration. I've added functionality to reschedule abandoned tasks reopen or comment if the issue still persists.

**Comment by daniel-ayers** [comment]
Yes I think your analysis is correct.  Only observed on older/slower hardware and VMs. Possibly also an indication I had been too ambitious with --workers.
