### ISSUE TITLE
Psort.py browser_search plugin not showing results

### ISSUE THREAD

**Issue by odibrowne** [log2timeline/plaso#934]
I am presently using plaso - psort version 1.4.1_20160811

I am trying to run the browser_search plugin but there doesn't appear to be be outputting anything
I am running the command as follows:
psort.py --analysis browser_search  -o 4n6time_sqlite -w newlog.sqlite log2time > browser-searchterms.

It is generating the newlog.sqlite file correctly however it doesn't generate a list searchterms as in previous versions.

**Comment by joachimmetz** [comment]
Thanks for the report I'll try ot have a look later this week in preparations of RC2

**Comment by joachimmetz** [comment]
Still WIP: https://github.com/log2timeline/plaso/blob/master/tools/psort.py#L783

**Comment by joachimmetz** [comment]
reports are now printed at the end of the analysis run
