### ISSUE TITLE
log2timeline.py and psort.py missing from python-plaso-1.2.1-dev-20150121-1ubuntu1

### ISSUE THREAD

**Issue by apapadop** [log2timeline/plaso#94]
Attempting to run plaso today I got this:

alex@gtw:~$ sudo log2timeline.py
sudo: log2timeline.py: command not found

Hm?

alex@gtw:~$ which log2timeline.py
alex@gtw:~$ locate log2timeline.py
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.1.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.2.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.3.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.4.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.5.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.6.gz
/home/alex/.cache/upstart/update-notifier-crash-_var_crash__usr_bin_log2timeline.py.0.crash.log.7.gz
/usr/bin/log2timeline.py
/usr/lib/python2.7/dist-packages/plaso/frontend/log2timeline.py

Right, so it *used to* be under /usr/bin/...

Let's see if there is something wrong with the installed packages:

alex@gtw:~$ sudo apt-cache search plaso
python-plaso - Plaso Log2Timeline
log2timeline-perl - A framework to for timeline creation and analysis.
alex@gtw:~$ dpkg-query -L python-plaso
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/python-plaso
/usr/share/doc/python-plaso/copyright
/usr/share/doc/python-plaso/LICENSE.gz
/usr/share/doc/python-plaso/changelog.Debian.gz
/usr/share/doc/python-plaso/AUTHORS
/usr/share/doc/python-plaso/ACKNOWLEDGEMENTS
/usr/share/doc/python-plaso/README
alex@gtw:~$

Shouldn't the scripts be included here?

Here is the package I have installed:
alex@gtw:~$ sudo dpkg -l python-plaso
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                           Version                      Architecture                 Description
+++-==============================================-============================-============================-=================================================================================================
ii  python-plaso                                   1.2.1-dev-20150121-1ubuntu1~ amd64                        Plaso Log2Timeline

Seems to me the scripts are missing from the latest dev package.

**Comment by joachimmetz** [comment]
This is a bug in the dpkg files, I'll prep a fix later today.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/194350043/

**Comment by joachimmetz** [comment]
Root of the issue fixed: https://github.com/log2timeline/plaso/commit/6e28ea8e4908504cbd7688624a9ea567c119ad24

**Comment by apapadop** [comment]
Thanks, any indication on when this will be available in the repos again? Currently apt-get install python-plaso does not pull down the right files.

**Comment by joachimmetz** [comment]
When time permits.
