### ISSUE TITLE
Syslog parser cannot parse non-ASCII log messages

### ISSUE THREAD

**Issue by daniel-ayers** [log2timeline/plaso#946]
**Plaso version:**

1.5RC

**Operating system Plaso is running on:**

Ubuntu 16.04LTS

**Installation method:**

ppa:gift/dev

**Description of problem:**

Syslog parser uses ascii codec and therefore cannot parse syslog messages encoded in UTF8.

```
*********************************** Error: 3 ***********************************
           Message : Unable to read lines from file with error: 'ascii' codec
                     can't decode byte 0xc2 in position 112: ordinal not in
                     range(128)
      Parser chain : syslog
Path specification : type: OS, location: /home/Dev/ntfs.dd
                   : type: RAW
                   : type: TSK, inode: 3426, location: /log/syslog.1
--------------------------------------------------------------------------------
```

This syslog entry was generated by an Ubuntu 16.04LTS machine with locale set to en_NZ.  

An improvement would be to switch to utf8, a superset of ascii and a very common codec.

Perhaps the ultimate (future) solution would be to adapt the codec depending on system locale, and/or try other codecs in the event of this error.

**Comment by Onager** [comment]
Yep, syslog should use UTF8, per https://tools.ietf.org/html/rfc5424.

CL incoming.

**Comment by Onager** [comment]
Fixed in https://github.com/log2timeline/plaso/commit/57ee2752019becedab1b7390031de29833ceb26c

Thanks for the report!
