### ISSUE TITLE
Minor clean-up of log2timeline.py -h

### ISSUE THREAD

**Issue by ghost** [log2timeline/plaso#952]
**Plaso version:**

1.5RC

**Issues**

Clarify --parsers: Default all, 'none' for none.  (Compare with --hashers)

Zeromq no longer experimental?

**Comment by joachimmetz** [comment]
Can you please be less cryptic. 

> Clarify --parsers: Default all, 'none' for none. (Compare with --hashers)

I assume you mean that you are missing an explanation of "none" and "all" in the current help output of log2timeline.py ?

> Zeromq no longer experimental?

We'll likely change this after the release candidates.

**Comment by daniel-ayers** [comment]
Sorry to be cryptic. Im suggesting that the help output relating to the "--parsers" command line option on log2timeline.py should be enhanced to make it clear that 'none' is an option and 'all' is the default.

The implementation of --parsers vs --hashers is very consistent - the help text should be too.

**Comment by joachimmetz** [comment]
thanks for the clarification.

**Comment by joachimmetz** [comment]
So 'none' parsers currently does not make sense in the context of log2timeline. And I'm not sure about the usefulness of adding 'all' since you can define your own presets. What would 'all' represent?

**Comment by joachimmetz** [comment]
Marking as infeasible for now.
