### ISSUE TITLE
psort.py debug log not the same as log2timeline debug log

### ISSUE THREAD

**Issue by ghost** [log2timeline/plaso#953]
**Plaso version:**

1.5RC

**Operating system Plaso is running on:**

Ubuntu 16.04 LTS 64 bit

**Installation method:**

ppa:gift/dev

**Description of problem:**

Logfile generated by psort.py -d --logfile X.log omits timestamps at start of each log line (Compare log2timeline.py debug log).

Also format (e.g. of PIDs) inconsistent compared to log2timeline log.

**Comment by joachimmetz** [comment]
I've changed the title, is this what you mean?
