### ISSUE TITLE
Machine's IP history

### ISSUE THREAD

**Issue by ghost** [log2timeline/plaso#960]
**Description of idea:**

Add dhcp events. Those should contain the following: ip x.x.x.x was assigned to this machine  at time T.

**Source data:**

This should be possible but according to Daniel, it will be very platform dependent.

**Comment by Onager** [comment]
This would probably take the form of some sort of analysis-plugin-like functionality to aggregate DHCP events in a cross platform way.

**Comment by joachimmetz** [comment]
> Add dhcp events.

Can you explain this in more detail? What would be the source of these events? dhcpd logs?

> This should be possible but according to Daniel, it will be very platform dependent.

Since we have no background this conversation can you provide us with more details.

**Comment by joachimmetz** [comment]
Unclear what the request is, closing issue.
