### ISSUE TITLE
Excessive error messages due to symlinks

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#961]
**Plaso version:**

1.5RC

**Operating system Plaso is running on:**

All

**Installation method:**

Dev install

**Description of problem:**

Some OS' contain large number of symlinks. These produce a large number of not-particularly useful error messages, that can obscure more interesting errors. Opening this issue to consider options.

**Debug output/tracebacks:**
```
********************************** Error: 219 **********************************
           Message : unable to process path specification with error: Not a
                     regular file.
```

**Source data:**

Images with many symlinks.

**Comment by joachimmetz** [comment]
I think the cause of that is that AnalyzeDataStream is run on the links. https://github.com/log2timeline/plaso/blob/master/plaso/engine/worker.py#L640

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/303300043/

**Comment by joachimmetz** [comment]
Completed.
