### ISSUE TITLE
yara version detection not working

### ISSUE THREAD

**Issue by ant1** [log2timeline/plaso#969]
**Plaso version:**

1.5.0 RC2

**Operating system Plaso is running on:**

FreeBSD

**Installation method:**

Through FreeBSD ports, patched to have the update to 1.5.0 RC2

**Description of problem:**

When I try to run the regression tests,  I have this failure
```
[FAILURE]       unable to determine version information for: yara
```

I have yara-python 3.4.0 installed,  but it doesn't have any YARA_VERSION.
I grepped in the yara 3.4.0 sources and I couldn't find any YARA_VERSION either.

The patch below fixes the issue for me,  and the regressions tests pass:

```
--- plaso/dependencies.py.orig  2016-08-28 13:31:57 UTC
+++ plaso/dependencies.py
@@ -70,7 +70,7 @@ PYTHON_DEPENDENCIES = [
     (u'six', u'__version__', u'1.1.0', None),
     (u'xlsxwriter', u'__version__', u'0.9.3', None),
     (u'yaml', u'__version__', u'3.10', None),
-    (u'yara', u'YARA_VERSION', u'3.4.0', None),
+    (u'yara', u'', u'', None),
     (u'zmq', u'__version__', u'2.1.11', None)]

 # The tuple values are:
```

**Comment by joachimmetz** [comment]
YARA_VERSION has been there since early days: https://github.com/VirusTotal/yara-python/commit/4897fc4c5fe989debce39f47a2dda8fd12f8d5f5

please check if Python is importing the right yara module
```
import yara
yara.__file__
```

**Comment by ant1** [comment]
I didn't see that version 3.5.0 of yara was released.

Version 3.4.0 didn't have YARA_VERSION:  https://github.com/VirusTotal/yara/blob/v3.4.0/yara-python/yara-python.c

**Comment by joachimmetz** [comment]
![WTF](http://2.bp.blogspot.com/-bKvoFkCBYsU/U5iX4ffNOAI/AAAAAAAAI0Y/30ojE8J4dUc/s1600/WTF-smiley.png) that is another yara-python.

We are using the stand-alone one: https://github.com/VirusTotal/yara-python

**Comment by joachimmetz** [comment]
Seeing that yara-python directory has been removed from https://github.com/VirusTotal/yara/tree/master I'd guess that the idea is to use https://github.com/VirusTotal/yara-python. I opt trying that version, keep the plaso version check for what it is and see what yara-python will change in the future.

**Comment by joachimmetz** [comment]
Closing this issue.
