### ISSUE TITLE
Improvements to the chrome preferences parser

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/plaso#970]
A FR to add more details into the Chrome preferences parser, specifically to parse the:

- last_clear_browsing_data_time (WebKit timestamp) indicating the last time the browser history was cleared
- There are multiple other timestamps that are found within the Preferences file (that are webkit timestamped), such as,lastpingday, last_check, next_check, etc. that need to be investigated whether or not it makes sense to add them (ATM the only timestamp that is pulled in is the install_time for each extension)

**Comment by joachimmetz** [comment]
This looks like a duplicate of: https://github.com/log2timeline/plaso/issues/100

**Comment by kiddinn** [comment]
yes, it's a duplicate, didn't see that one, can close this one then.

**Comment by joachimmetz** [comment]
Copying comment to other issue.
