### ISSUE TITLE
idle worker issue - 1.4.1_20160904

### ISSUE THREAD

**Issue by jasonblanks** [log2timeline/plaso#984]
**Plaso version:**

plaso - log2timeline version 1.4.1_20160904

**Operating system Plaso is running on:**

.#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Installation method:**

git pull

**Description of problem:**
I see a few tickets closed with regards to idle workers, just want to make sure this isn't the same issue reporting to be worked on in 1.5. Otherwise I keep running into similar issues when plaso starts trying to process in /windows/winsxs, could be our build though.

I've been eyeing this job for a day, worker05 has been idle on  TSK:/Windows/savesmsts.log for 20+ hours it seems now.   The others I would say have just been sitting on 12+ hours and appear to be making no progress just by eye. 

Identifier      PID     Status          Sources         Events          File
Main            642     merging         18418 (0)       28260 (0)       166669d21a614e9db6d77805f4f5c2cb
Worker_00       653     idle            2060 (0)        3189 (0)        TSK:/Windows/winsxs/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.18205_none_0afa8883f490116d
Worker_01       657     idle            8352 (0)        31199 (0)       TSK:/Windows/winsxs/x86_netfx35cdf-cdf_wf_target_files_31bf3856ad364e35_6.1.7600.16385_none_6c39a732d1f6259e
Worker_02       661     idle            3154 (0)        3034 (0)        TSK:/Windows/winsxs/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.18410_none_0afbfa6df48eab41
Worker_03       665     idle            680 (0)         397 (0)         TSK:/Windows/savewimsmsts.log
Worker_04       671     idle            19913 (0)       5962 (0)        TSK:/Windows/winsxs/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.21884_none_f434f8420e3026f8
Worker_05       676     idle            9171 (0)        426 (0)         TSK:/Windows/savesmsts.log
Worker_06       680     idle            4293 (0)        3113748 (0)     TSK:/Windows/winsxs/x86_netfx-web_engine_dll_b03f5f7f11d50a3a_6.1.7601.18758_none_0aff44e9f48bde98

**Debug output/tracebacks:**
log2timeline.py -d --log-file=output_0906 --parsers usnjrnl,mft,win7 machine-0906.plaso 2016-0830-00.E01

.# tail output_0906
2016-09-07 00:34:44,438 [DEBUG](Worker_03) PID:665 <extractors> [ParseDataStream] parsing file: TSK:/Windows/savewimsmsts.log with parser: winjob
2016-09-07 00:34:44,440 [DEBUG](Worker_03) PID:665 <extractors> winjob unable to parse file: TSK:/Windows/savewimsmsts.log with error: Unsupported product version in: 0xbbef
2016-09-07 00:34:44,441 [DEBUG](Worker_03) PID:665 <extractors> [ParseDataStream] parsing file: TSK:/Windows/savewimsmsts.log with parser: java_idx
2016-09-07 00:34:44,441 [DEBUG](Worker_03) PID:665 <extractors> java_idx unable to parse file: TSK:/Windows/savewimsmsts.log with error: Not a valid Java IDX file
2016-09-07 00:34:44,442 [DEBUG](Worker_03) PID:665 <extractors> [ParseDataStream] parsing file: TSK:/Windows/savewimsmsts.log with parser: firefox_cache
2016-09-07 00:34:44,442 [DEBUG](Worker_03) PID:665 <extractors> firefox_cache unable to parse file: TSK:/Windows/savewimsmsts.log with error: Not a Firefox cache1 file.
2016-09-07 00:34:44,443 [DEBUG](Worker_03) PID:665 <extractors> [ParseDataStream] parsing file: TSK:/Windows/savewimsmsts.log with parser: mcafee_protection
2016-09-07 00:34:44,677 [DEBUG](Worker_03) PID:665 <extractors> mcafee_protection unable to parse file: TSK:/Windows/savewimsmsts.log with error: [mcafee_protection] Unable to parse CSV file: type: OS, location: /media/ir/cfi_drop/2016-0830-00/2016-0830-00.E01;type: EWF;type: TSK_PARTITION, location: /p1, part index: 2, start offset: 0x00100000;type: TSK, inode: 72545, location: /Windows/savewimsmsts.log;. Signature mismatch.
2016-09-07 00:34:44,681 [DEBUG](Worker_03) PID:665 <worker> [ProcessFileEntry] done processing file entry: TSK:/Windows/savewimsmsts.log
2016-09-07 00:34:44,688 [DEBUG](Worker_03) PID:665 <zeromq_queue> Pop on Worker_03 task queue queue, port 65279

.# date
Wed Sep  7 17:00:12 BST 2016

.#15M Sep  7 00:34 output_0906
Let me know if you need the full log file, or a tailored grep, doubting this tail is sufficient for you.

**Source data:**

**Comment by Onager** [comment]
Thanks Jason,
A couple of questions you might be able to answer:

   - What's do the CPU and Memory usage numbers look like for the
   log2timeline processes at this time?
   - What's the status of the storage files and result counts?

I'm curious as to if you're seeing similar things to #977.

**Comment by jasonblanks** [comment]
%Cpu(s): 13.5 us,  1.2 sy,  0.0 ni, 81.4 id,  4.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   8174408 total,  8052672 used,   121736 free,   106120 buffers
KiB Swap:  8384508 total,  6383868 used,  2000640 free.    41256 cached Mem
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  642 root      20   0 9479160 6.674g   2084 R  99.7 85.6   1608:55 log2timeline.py
28416 root      20   0  198840  15616    660 S   1.6  0.2 232:12.53 python
  657 root      20   0  710316   4164   1700 S   0.3  0.1 314:47.28 log2timeline.py
  665 root      20   0  665668   3668   1352 S   0.3  0.0 428:41.92 log2timeline.py
  671 root      20   0  716060   3960   1480 S   0.3  0.0 315:22.80 log2timeline.py
  676 root      20   0  649172   3720   1344 S   0.3  0.0 362:16.98 log2timeline.py
   

Looks similar with the parent process merging and almost at 100%cpu and 85%mem.

log2timel 642 root   62w   REG   104,17       2503 63963374 /media/XXX/tmpkIT8jr/machine-0906.plaso
log2timel 642 root   63r   REG   104,17  101469725 63963378 /media/XXX/tmpXOJS26/merge/166669d21a614e9db6d77805f4f5c2cb.plaso

Wed Sep  7 20:48:04 BST 2016
wc -l /media/tmpXOJS26/merge/166669d21a614e9db6d77805f4f5c2cb.plaso
299326 /media/tmpXOJS26/merge/166669d21a614e9db6d77805f4f5c2cb.plaso
wc -l /media/tmpkIT8jr/machine-0906.plaso
15 /media/tmpkIT8jr/machine-0906.plaso
wc -l /media/tmpXOJS26/merge/166669d21a614e9db6d77805f4f5c2cb.plaso
299326 /media/ir/cfi_drop/2016-0830-00/tmpXOJS26/merge/166669d21a614e9db6d77805f4f5c2cb.plaso
wc -l /media/tmpkIT8jr/machine-0906.plaso
15 /media/tmpkIT8jr/machine-0906.plaso

**Comment by jasonblanks** [comment]
Just an update after yesterdays comment.  CPU at 100% stuck at same spot it appears from before.


 9528 root      20   0  985660 502944  24996 R 100.3  6.2 930:34.19 log2timeline.py
28416 root      20   0  198840  15092    124 S   2.0  0.2 286:25.75 python
 1133 elastic+  20   0 8000952 438512      0 S   1.3  5.4 810:55.18 java
10184 root      20   0   29320   3180   2548 R   1.3  0.0   0:00.58 top
    7 root      20   0       0      0      0 S   0.3  0.0  42:56.59 rcu_sched
 9540 root      20   0  655020 228292   8556 S   0.3  2.8 339:58.60 log2timeline.py
 9548 root      20   0  700600 275516  10164 S   0.3  3.4 250:09.38 log2timeline.py
 9552 root      20   0  715236 290792  10740 S   0.3  3.6 250:25.20 log2timeline.py
 9556 root      20   0  705752 280948  10364 S   0.3  3.4 252:11.25 log2timeline.py

plaso - log2timeline version 1.4.1_20160908

Source path     : /media/2016-0830-00.E01
Source type     : storage media image

Identifier      PID     Status          Sources         Events          File
Main            9528    merging         18418 (0)       28236 (0)       8295542d6dd24f1280fed56e11e48cde
Worker_00       9536    idle            2770 (0)        3079 (0)        TSK:/Windows/winsxs/x86_microsoft-windows-wmvsdecd_31bf3856ad364e35_6.1.7601.17514_none_6880e489030d43b0
Worker_01       9540    idle            8847 (0)        304 (0)         TSK:/Windows/savesmsts.log
Worker_02       9544    idle            6826 (0)        2940 (0)        TSK:/Windows/winsxs/x86_microsoft-windows-wmvencod_31bf3856ad364e35_6.1.7601.19091_none_f1ac0e7f5cbdd4d8
Worker_03       9548    idle            3855 (0)        30673 (0)       TSK:/Windows/winsxs/x86_microsoft-windows-wmviddsp_31bf3856ad364e35_6.1.7601.23290_none_a91a44b2ece25751
Worker_04       9552    idle            6279 (0)        7423 (0)        TSK:/Windows/winsxs/x86_microsoft-windows-wmviddsp_31bf3856ad364e35_6.1.7601.19091_none_a891a64bd3c3d3b7
Worker_05       9556    idle            3619 (0)        3113345 (0)     TSK:/Windows/winsxs/x86_microsoft-windows-wmvencod_31bf3856ad364e35_6.1.7601.23290_none_f234ace675dc5872
Worker_06       9560    idle            844 (0)         365 (0)         TSK:/Windows/savewimsmsts.log



.# date
Fri Sep  9 13:49:35 BST 2016
.# wc -l /media/tmppNNZN_/machine-0908.plaso
125169 /media/tmppNNZN_/machine-0908.plaso
.# wc -l /media/tmpZunL2j/merge/8295542d6dd24f1280fed56e11e48cde.plaso
299940 /media/tmpZunL2j/merge/8295542d6dd24f1280fed56e11e48cde.plaso

--
# date
Fri Sep  9 15:03:01 BST 2016
.# wc -l /media/tmppNNZN_/machine-0908.plaso
136010 /media/tmppNNZN_/machine-0908.plaso
.# wc -l /media/tmpZunL2j/merge/8295542d6dd24f1280fed56e11e48cde.plaso
299940 /media/tmpZunL2j/merge/8295542d6dd24f1280fed56e11e48cde.plaso




Just a note, I see worker6 and worker1 are always on savewimsmsts.log and savesmsts.log from the begining to the end which seems odd, im guessing that means two workers have been tied up the whole time.  I tried running this with the gift/dev build and got errors, in the git repo no errors.  I killed the process yesterday, do you think it will eventually move past this file, or should i kill the job? (seeing progress on machine-0908.plaso, though still showing the same file hash on the merge)

**Comment by joachimmetz** [comment]
> Just a note, I see worker6 and worker1 are always on savewimsmsts.log and savesmsts.log from the beginning to the end which seems odd, im guessing that means two workers have been tied up the whole time.

Could be, how large are these log files?

> I tried running this with the gift/dev build and got errors

What errors?

**Comment by jasonblanks** [comment]
Once this job completes I can get that.  But for now is this behavior expected(amount of killed workers? Same process has been running this entire time)

plaso - log2timeline version 1.4.1_20160908

Source path     : /media/2016-0830-00.E01
Source type     : storage media image

Identifier      PID     Status          Sources         Events          File
Main            9528    merging         170725 (0)      4042631 (0)     2244cdc0e783494d92fbde0ad269de17
Worker_00       9536    killed          14151 (0)       41647 (0)
Worker_01       9540    killed          30629 (0)       171886 (0)
Worker_02       9544    killed          15598 (0)       54954 (0)
Worker_03       9548    killed          14237 (0)       68309 (0)
Worker_04       9552    killed          14938 (0)       37478 (0)
Worker_05       9556    killed          11518 (0)       3165989 (0)
Worker_06       9560    killed          7858 (0)        132624 (0)
Worker_07       12823   killed          88 (0)          4770 (0)
Worker_08       12830   killed          0 (0)           91 (0)
Worker_09       12835   killed          1537 (0)        15660 (0)
Worker_10       12840   killed          22 (0)          1210 (0)
Worker_11       12845   killed          2305 (0)        33397 (0)
Worker_12       12850   killed          1636 (0)        4753 (0)
Worker_13       12855   killed          1016 (0)        3315 (0)
Worker_14       12860   killed          1307 (0)        1706 (0)
Worker_15       12877   killed          257 (0)         4987 (0)
Worker_16       12882   killed          193 (0)         7438 (0)
Worker_17       12887   killed          97 (0)          1929 (0)
Worker_18       12893   killed          50 (0)          1286 (0)
Worker_19       12899   running         10029 (0)       58209 (0)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/newsview[3].js
Worker_20       12904   killed          17 (0)          303 (0)
Worker_21       12909   killed          7 (0)           439 (0)
Worker_22       12914   killed          0 (0)           8 (0)
Worker_23       12919   killed          3 (0)           1307 (0)
Worker_24       12924   killed          3 (0)           4967 (0)
Worker_25       12930   killed          0 (0)           3357 (0)
Worker_26       12938   killed          0 (0)           768 (0)
Worker_27       12943   killed          0 (0)           4851 (0)
Worker_28       12949   killed          0 (0)           6553 (0)
Worker_29       12954   killed          0 (0)           4874 (0)
Worker_30       12959   killed          0 (0)           2372 (0)
Worker_31       12965   killed          0 (0)           2652 (0)
Worker_32       12971   killed          0 (0)           1001 (0)
Worker_33       12976   killed          0 (0)           1999 (0)
Worker_34       12981   killed          0 (0)           437 (0)
Worker_35       12986   killed          0 (0)           972 (0)
Worker_36       12991   extracting      11805 (0)       64533 (4)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/l[2].js
Worker_37       12996   extracting      11608 (0)       52734 (4)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/tool_favourite[1].png
Worker_38       13001   killed          0 (0)           677 (0)
Worker_39       13006   idle            11970 (0)       69321 (8)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/getenvironment[1]
Worker_40       13011   running         11712 (0)       85308 (4)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/prompting[1].js
Worker_41       13016   killed          4 (0)           898 (0)
Worker_42       13022   running         9400 (0)        86833 (4)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/log[7]
Worker_43       13042   running         6881 (0)        39785 (4)       TSK:/Users/xxx/AppData/Local/Microsoft/Windows/Temporary Internet Files/Content.IE5/2G1CWV41/baseidentify[1].ejs


Sun Sep 11 18:49:12 BST 2016
.# wc -l /media/tmppNNZN_/branch_machine-0908.plaso
784145 /media/tmppNNZN_/branch_machine-0908.plaso

**Comment by joachimmetz** [comment]
Any indication why this are getting killed?

**Comment by joachimmetz** [comment]
which version of libewf are you using ?

**Comment by jasonblanks** [comment]
/git/plaso/utils# ./check_dependencies.py
Checking availability and versions of dependencies.
[OK]            artifacts version: 20160114
[OK]            bencode
[OK]            binplist version: 0.1.5
[OK]            construct version: 2.5.3
[OK]            dateutil version: 2.5.3
[OK]            dfdatetime version: 20160323
[OK]            dfvfs version: 20160803
[OK]            dfwinreg version: 20160428
[OK]            dpkt version: 1.8.8
[OK]            efilter
[OK]            hachoir_core version: 1.3.3
[OK]            hachoir_metadata version: 1.3.3
[OK]            hachoir_parser version: 1.3.4
[OK]            IPython version: 1.2.1
[OK]            pefile version: 1.2.10-139
[OK]            psutil version: 4.3.1
[OK]            pyparsing version: 2.1.5
[OK]            pytz
[OK]            requests version: 2.10.0
[OK]            six version: 1.10.0
[OK]            xlsxwriter version: 0.9.3
[OK]            yaml version: 3.11
[OK]            yara version: 3.4.0
[OK]            zmq version: 14.0.1
[OK]            sqlite3 version: 3.8.2
[OK]            SleuthKit version: 4.3.0
[OK]            pytsk3 version: 20160721
[OK]            libbde (pybde) version: 20160731
[OK]            libesedb (pyesedb) version: 20160622
[OK]            libevt (pyevt) version: 20160421
[OK]            libevtx (pyevtx) version: 20160421
[OK]            libewf (pyewf) version: 20160424
[OK]            libfsntfs (pyfsntfs) version: 20160418
[OK]            libfvde (pyfvde) version: 20160801
[OK]            libfwsi (pyfwsi) version: 20160110
[OK]            liblnk (pylnk) version: 20160420
[OK]            libmsiecf (pymsiecf) version: 20160904
[OK]            libolecf (pyolecf) version: 20160814
[OK]            libqcow (pyqcow) version: 20160123
[OK]            libregf (pyregf) version: 20160424
[OK]            libscca (pyscca) version: 20160108
[OK]            libsigscan (pysigscan) version: 20160312
[OK]            libsmdev (pysmdev) version: 20160320
[OK]            libsmraw (pysmraw) version: 20160424
[OK]            libvhdi (pyvhdi) version: 20160424
[OK]            libvmdk (pyvmdk) version: 20160119
[OK]            libvshadow (pyvshadow) version: 20160110

**Comment by joachimmetz** [comment]
Try an older version of libewf

20160424 is an experimental version.

**Comment by joachimmetz** [comment]
Closing issue, please try plaso 20170930 or later.
