### ISSUE TITLE
optimize merge behavior

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/plaso#985]
large merge in main loop halts status view and delays scheduling of new tasks if the queue is empty.

* [x] ~~https://codereview.appspot.com/306420043/~~
  * ~~merge slicing (or merge split)~~
  * ~~reduced task queue wait timeout~~
* [x] ~~https://codereview.appspot.com/306440043/~~
  * ~~try to prevent merge depletion - order tasks by source type~~
  * ~~order tasks by task storage file size~~
  * ~~preempt sliced merge of non-directory source type by directory source type~~
* [x] [additional changes](https://codereview.appspot.com/310200043/) @Onager

**Comment by Onager** [comment]
I have some code for the first point, deprioritzing large task stores.

**Comment by joachimmetz** [comment]
Related issue: https://github.com/log2timeline/plaso/issues/906

**Comment by joachimmetz** [comment]
Testing https://codereview.appspot.com/306420043/:

* merge depletion with limit of 1000 attribute containers, while merging 8G task file

**Comment by joachimmetz** [comment]
without merge slicing
```
profile name	number of samples	total CPU time	total system time
merge	18675	680.623643	674.571903229
merge_check	21550	88.822667	89.829305172
get_event_source	40226	2.948083	2.8270206451
schedule_task	18675	0.817826	0.8311195374
process_sources	1	776.844166	771.524183989
```

with merge slicing
```
profile name	number of samples	total CPU time	total system time
merge_check	32043	93.85758	93.7035036087
merge	26137	685.354012	677.78151989
process_sources	1	785.758294	777.753906012
get_event_source	50719	2.602577	2.566018343
fill_event_source_heap	32044	2.903775	2.8306655884
schedule_task	18675	0.666894	0.6561675072
```



```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/306440043/
```
profile name	number of samples	total CPU time	total system time
merge_check	30534	107.310377	113.110201836
merge	26137	689.232623	691.619571924
process_sources	1	803.293298	811.428506851
get_event_source	49210	2.580676	2.5983293057
fill_event_source_heap	30535	2.883644	2.8679082394
schedule_task	18675	0.682874	0.6793193817
```

**Comment by joachimmetz** [comment]
with bug fix
```
profile name	number of samples	total CPU time	total system time
merge_check	29359	189.778432	190.946797132
merge	26137	652.375716	649.030814886
process_sources	1	849.064957	846.686155796
get_event_source	48035	2.496865	2.4725184441
fill_event_source_heap	29360	2.806667	2.7444303036
schedule_task	18675	0.726968	0.7277309895
```
