### ISSUE TITLE
Too many open files running Psort on Ubuntu

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#988]
From #669, @fbruzzaniti reported: 

I was getting this error when running psort.py against a 3 gig plaso file (tagging).
A quick fix for anyone who is having this problem on Ubuntu (well it worked for me).
In the same user session that you plan to run psort.py type:

ulimit -Sn 4096 then run psort

4096 was enough for what I was doing it is the soft limit for my system. You could change the hard limit for the entire system via sysctl then rerun ulimit. FYI the line to add to /etc/sysctl.conf would be something like:

fs.file-max = 8192
sysctl -p

PS: If you want the limits you set in ulimit to be permanent you will need to edit /etc/security/limits.conf

**Comment by joachimmetz** [comment]
@fbruzzaniti can you

* provide us with your psort command line arguments, which analysis plugins
*  check which files are open? `/proc/$PID/fd`

**Comment by Onager** [comment]
No response from reporter, closing.
