### ISSUE TITLE
Modify the computer hostname from a parser

### ISSUE THREAD

**Issue by plasoUSER** [log2timeline/plaso#990]
Hello,

I am creating a parser for plaso and I would like to fix the computer hostname into my parser. In using l2tcsv output I would like to modify the field "host" into my parser. How I could achieve this ?

Thanks.

**Comment by joachimmetz** [comment]
at the moment this is not possible. a work around would be is to add the hostname to the output e.g. real_hostname and have formatter print it as part of the message

**Comment by plasoUSER** [comment]
I will do that.

Thanks.

**Comment by joachimmetz** [comment]
Maybe I initially understood you wrong. Does the data/log you are parsing contain the hostname? then my previous applies. If not and there is no hostname field in your data, there is no need for the parser to set it. It is up to the formatter or output module to add it based on the system configuration information.

**Comment by joachimmetz** [comment]
Closing issue but feel free to reopen if needed.

**Comment by plasoUSER** [comment]
Yes, my data contain the hostname.
