### ISSUE TITLE
Tests fail if timesketch is installed

### ISSUE THREAD

**Issue by Onager** [log2timeline/plaso#996]
**Plaso version:**

HEAD

**Operating system Plaso is running on:**

N/A

**Installation method:**

Dev install

**Description of problem:**

Running tests on a machine with timesketch and elasticsearch installed causes tool tests to fail.

**Debug output/tracebacks:**

```
Traceback (most recent call last):
 File "/home/user/plaso/tools/log2timeline_test.py", line 119, in testListOutputModules
   self.assertEqual(number_of_tables, 2)
AssertionError: 1 != 2
```

**Source data:**

N/A

**Comment by Onager** [comment]
This is due to the test looking for disabled output modules in the tool output, when there are no disabled modules.

**Comment by joachimmetz** [comment]
When we add elasticsearch-py to required / default set of dependencies this will likely resurface https://github.com/log2timeline/plaso/issues/1828

**Comment by joachimmetz** [comment]
Timesketch module was removed in https://github.com/log2timeline/plaso/commit/769d87addee8ef3ac585552da6e0b1be4c99345e
